### ISSUE TITLE
ModuleNotFoundError with MovieDD-QARecs, MovieDD-QA, MovieDD-Recs

### ISSUE THREAD

**Issue by dykang** [facebookresearch/ParlAI#1005]
"python display_data.py -t {MovieDD-QARecs, MovieDD-QA, MovieDD-Recs} -n 10 "

gives same error message "ModuleNotFoundError". Is that because my ParlAI is outdated or the movie related datasets are not in there yet?

**Comment by jaseweston** [comment]
You need:

python examples/display_data.py -t "#MovieDD-QARecs"

**Comment by jaseweston** [comment]
You need, e.g.:

python examples/display_data.py -t "#MovieDD-QARecs"
