### ISSUE TITLE
Error running DrQA

### ISSUE THREAD

**Issue by bittlingmayer** [facebookresearch/ParlAI#101]
I ran: `python examples/drqa/train.py -t "#opensubtitles"`

After 10 or 20 minutes:

```
05/25/2017 02:34:31 PM: [ Running validation... ]
Traceback (most recent call last):
  File "examples/drqa/train.py", line 180, in <module>
    main(opt)
  File "examples/drqa/train.py", line 118, in main
    valid_metric = validate(opt, doc_reader, iteration)
  File "examples/drqa/train.py", line 62, in validate
    valid_world.parley()
  File "/Users/bittlingmayer/Desktop/aca/ParlAI/parlai/core/worlds.py", line 221, in parley
    acts[1] = agents[1].act()
  File "/Users/bittlingmayer/Desktop/aca/ParlAI/parlai/agents/drqa/agents.py", line 157, in act
    [ex], null=self.word_dict['<NULL>'], cuda=self.opt['cuda']
  File "/Users/bittlingmayer/Desktop/aca/ParlAI/parlai/agents/drqa/utils.py", line 126, in batchify
    max_length = max([d.size(0) for d in docs])
  File "/Users/bittlingmayer/Desktop/aca/ParlAI/parlai/agents/drqa/utils.py", line 126, in <listcomp>
    max_length = max([d.size(0) for d in docs])
RuntimeError: dimension 0 out of range of 0D tensor at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/TH/generic/THTensor.c:24
```

**Comment by bittlingmayer** [comment]
Happened with ` --embedding_dim 100 --train_interval 100`, but in a few minutes, so I assume it happens at or near the end.

**Comment by ajfisch** [comment]
Hm. I haven't tried the drqa model on this dataset. From the error it looks like there is an empty example.

The fix would be to skip examples where either the question or passage has 0 tokens:
https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/drqa/agents.py#L226-L227

You can try putting a
```python
if len(inputs['document']) == 0:
    import pdb
    pdb.set_trace()
```
there to investigate.

I can add some more checks to be more robust.

**Comment by bittlingmayer** [comment]
Which datasets should it work with?

I added:

```
        if len(inputs['document']) == 0:
            print("empty document")
            inputs['document'] = self.word_dict.tokenize("<EMPTY>")
        if len(inputs['question']) == 0:
            print("empty question")
            inputs['question'] = self.word_dict.tokenize("<EMPTY>")
        
```

There is still something wrong.  At the moment I am a bit short on time to really dig into it.

**Comment by ajfisch** [comment]
It has been tested on Squad and bAbI (the ones with answers in the context, e.g. tasks 1-5, 11-14, 16).

I'll take a look and submit fix whatever is going on here later.

**Comment by ajfisch** [comment]
I took a look at the OpenSubtitles task (I was unfamiliar with it before). It is not a QA task, and DrQA is only meant to be a QA (or QA-style) model. It expects inputs to be text, with the last line being a question (text + '\n' + question).

OpenSubtitles does not follow this and therefore the inputs are not parsed correctly, resulting in the errors you see (empty inputs).

**Comment by jaseweston** [comment]
but still, isn't it good that it doesn't crash?

**Comment by ajfisch** [comment]
In my opinion, I think that it should be on the user to use the right tasks for the model (DrQA is not advertised to be a viable model for all of the tasks in ParlAI).

Therefore I think it is better to crash instead of silently skipping all of the examples. We could add a more descriptive error message...

**Comment by jaseweston** [comment]
yes, a nice error message please!
