### ISSUE TITLE
How to reproduce the results of the two baselines of kv profile memory and seq2seq+Attention  of the convai2 leadboard

### ISSUE THREAD

**Issue by zhaoguangxiang** [facebookresearch/ParlAI#1014]
![image](https://user-images.githubusercontent.com/17742385/43243528-b234b7b2-90d9-11e8-99b5-ecd24f9f3335.png)
The train command of seq2seq of convai2 try to minimize ppl,  the result is not good when i try to modify the train.py of seq2seq of convai2 to max f1

In addition, I would like to know what command can achieve the results of the kv profile memory baseline of convai2.

Thanks very much!

**Comment by alexholdenmiller** [comment]
Yes I always use minimizing ppl rather than maximizing f1 for the seq2seq model.

The code to reproduce the kvmemnn training is right next to that of the seq2seq training code: both are in projects/convai2/baselines.
