### ISSUE TITLE
ConvAI2 wild evaluation dataset contribution

### ISSUE THREAD

**Issue by litinsky** [facebookresearch/ParlAI#1056]
Hi, folks!

I represent ConvAI2 organizing team. We obtained conversations dataset during the challenge. How can I contribute it to ParlAI?

**Comment by jaseweston** [comment]
Hi! There is documentation how to add a task here:

http://www.parl.ai/static/docs/tutorial_task.html

and you can look at all the  other tasks already there as examples:

https://github.com/facebookresearch/ParlAI/tree/master/parlai/tasks

**Comment by jaseweston** [comment]
i think this is done right?
