### ISSUE TITLE
drqa training time

### ISSUE THREAD

**Issue by bittlingmayer** [facebookresearch/ParlAI#106]
`python examples/drqa/train.py -t squad -bs 32` takes a very long time on a CPU at least.

What are some good toy params for playing with DrQA?

**Comment by ajfisch** [comment]
These types of deep LSTMs with attention are hefty to train, especially on CPU (and especially on say a laptop with only a few cores). Expect around ~6 hrs to convergence on a K40 GPU.

You can make the model more lighter by setting: `--doc_layers 1 --question_layers 1 --use_qemb f --rnn_type gru` and using GloVe pre-trained embeddings.

We also plan on putting up a pre-trained model.

**Comment by bittlingmayer** [comment]
For others who find this thread:

With those params it took about two days on a Macbook (2 GHz Intel Core i7), here is the result after the final iteration:

```
05/28/2017 04:03:38 AM: [ Running validation... ]
05/28/2017 04:12:14 AM: [valid] iter = 68 | EM = 0.1472 | F1 = 0.2630 | exs = 3036
05/28/2017 04:12:14 AM: [ Done. Time = 516.05 (s) ]
```

**Comment by jaseweston** [comment]
I'm assuming this is closed?
