### ISSUE TITLE
seq2seq dropout

### ISSUE THREAD

**Issue by christqoh** [facebookresearch/ParlAI#1060]
When training the profilememory seq2seq with dropout 0.7 I get a value error `ValueError: dropout probability has to be between 0 and 1, but got 1.4` even though the log file states `[  dropout: 0.7 ]`.

**Comment by emilydinan** [comment]
https://github.com/facebookresearch/ParlAI/blob/7b93ac1cd7e33aba167449a72183a6611e172a6a/projects/personachat/persona_seq2seq.py#L1727
