### ISSUE TITLE
Hardware vs Batch Size

### ISSUE THREAD

**Issue by christqoh** [facebookresearch/ParlAI#1061]
(related to #828)
I am training a profilememory seq2seq with convai2 data on a P100 but can not exceed `-bs 128`. During training I found larger bs works better. Is there a support for multiple GPUs or similar to get up to `-bs 256`?

**Comment by emilydinan** [comment]
Feel free to wrap your model using [nn.DataParallel](https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html).

**Comment by christqoh** [comment]
thanks
