### ISSUE TITLE
Error linking MTurk account to AWS.

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#1062]
Hello, I am getting an error regarding linking my MTurk account to my AWS account:

> You are going to allow workers from Amazon Mechanical Turk to be an agent in ParlAI.
During this process, Internet connection is required, and you should turn off your computer's auto-sleep feature.
Enough HITs will be launched over time up to a max of 1.5 times the amount requested until the desired number of conversations start.
Please press Enter to continue... 
ERROR: To use the MTurk API, you will need an Amazon Web Services (AWS) Account. Your AWS account must be linked to your Amazon Mechanical Turk Account. Visit https://requestersandbox.mturk.com/developer to get started. (Note: if you have recently linked your account, please wait for a couple minutes before trying again.)

However, I believe I have linked my account already... when I follow the links this is what I see:

**Getting started view:**
<img width="841" alt="screen shot 2018-08-12 at 11 26 44 am" src="https://user-images.githubusercontent.com/25429471/44005121-eba92806-9e22-11e8-8475-cc3e40871b21.png">

**Sandbox view:**
<img width="848" alt="screen shot 2018-08-12 at 11 27 02 am" src="https://user-images.githubusercontent.com/25429471/44005122-ebbe3f84-9e22-11e8-91aa-b921914645ba.png">

It has been over an hour. Why is this happening? I do not have funds in my Requester account, however, I believe that would return a different error saying I have insignificant funds.

**Comment by JackUrb** [comment]
@emilydinan - I'm not really sure about that, it should probably return 0 for the `user_balance = float(client.get_account_balance()['AvailableBalance'])` call. @josharnoldjosh can you try removing your credentials (your `~/.aws` folder) and then trying again? It'll re-request all of your credentials for aws but something may have fallen out of sync.

**Comment by josharnoldjosh** [comment]
I have repeatedly tried deleting ~/.aws, I've also tried unlinking my account then relinking my account. What could be going wrong? Is it perhaps an unhandled error?

**Comment by josharnoldjosh** [comment]
My balance in my requester account is -1$.

**Comment by JackUrb** [comment]
Perhaps negative balance is throwing an error that I'm not expecting. Can you try logging `e` in the linked function? Perhaps it has some more context.

**Comment by josharnoldjosh** [comment]
What do you mean by "logging e in the linked function"? Which function? How do I log e? Is it a variable?

Thanks!

**Comment by JackUrb** [comment]
https://github.com/facebookresearch/ParlAI/blob/7b93ac1cd7e33aba167449a72183a6611e172a6a/parlai/mturk/core/mturk_utils.py#L111 in this block print `e` to see what it contains

**Comment by josharnoldjosh** [comment]
Okay, what is completely weird is I logged into my Amazon Requester account, with a different password, and my balance was now $0.00 instead of $-1... it appears somehow I had two accounts with the same email address?!?! However, the issue is now fixed. If this happens to anyone, try logging into your amazon requester account with a different password, it fixed it for me (instead of using password from Keychain from Apple)
