### ISSUE TITLE
Reproducing the pretrained profilememory model

### ISSUE THREAD

**Issue by christqoh** [facebookresearch/ParlAI#1066]
Which hyper parameters did you guys use to achieve the pretrained model? According to #967, #995, when I run `python projects/convai2/baselines/profilememory/train.py &>log.txt`, I should get equivalent performance but I get something like this:
- [log.txt](https://github.com/facebookresearch/ParlAI/files/2287612/log.txt)
- [f1_hits.pdf](https://github.com/facebookresearch/ParlAI/files/2287613/f1_hits.pdf)
- [PPL.pdf](https://github.com/facebookresearch/ParlAI/files/2287614/PPL.pdf)

I trained on a P100. When evaluating your model with your `eval_f1.py` script, the score is 0.1709 (red line in graphics). `eval_ppl.py` crashes for me. After a week of more or less unsuccessful training... how did you guys get there?

**Comment by emilydinan** [comment]
You can see the hyperparameters we used when you load the pretrained model file.

**Comment by christqoh** [comment]
sorry there was a mistake. I meant `python projects/convai2/baselines/profilememory/train.py &>log.txt`

so you say the hyper parameters you used are the ones shown when running `python projects/convai2/baselines/profilememory/interactive.py`?

**Comment by christqoh** [comment]
Using those, I get `OverflowError: math range error`, compare [log.txt](https://github.com/facebookresearch/ParlAI/files/2287726/log.txt)

**Comment by stephenroller** [comment]
If eval_ppl.py crashes for you, please post that log, we should fix that.

If you call interactive.py with the pretrained model, you should find the hyperparameters listed at the top of the output script. Based on your PPL graph, I'm wondering if you're doing early stopping correctly. Your f1 graph looks like .

Double check you're *training* with the same hyperparameters as the pretrained model, especially dropout and model size type things.

Based on the second log.txt you posted, you're evaluating a model which has learned nothing at all.

**Comment by stephenroller** [comment]
Also on a P100 I would expect training (with correct hyperparams) to take a more like a few hours, not a week.

**Comment by christqoh** [comment]
Hi @stephenroller, just opened #1067 about eval_ppl.py
I was training several hyper parameter settings for a week. 
The second log file is when training with the parameters I get from interactive.py such as learning rate 0.5, 2 layers, batch size 1, ... . It crashed during first evaluation.

**Comment by stephenroller** [comment]
Ah okay hm the interactive.py output is misleading. This looks like the hyperparameters you should be using during training. Your LR is off by a couple orders of magnitude: 
https://github.com/facebookresearch/ParlAI/blob/f5f276996391171b928743af0abfb803da6ecde4/projects/convai2/baselines/profilememory/train.py#L20-L42

**Comment by christqoh** [comment]
@stephenroller if you check the first log file I posted you will find I used exactly those. There is no interactive.py output posted. The second log file also is a log file of a training session using the hyper parameters extracted from interactive.py.
So first log file: lr = 0.001 vs second log file: lr = 0.5

**Comment by stephenroller** [comment]
What kind of score are you expecting to get? I just evaluated the pretrained model and got like 16.7 F1, which is roughly the same as you report.

**Comment by christqoh** [comment]
just ran eval_f1.py on the pretrained profilememory again and got

EPOCH DONE
finished evaluating task convai2:self:no_cands using datatype valid
{'exs': 7801, 'f1': 0.1709}
============================
FINAL F1: 0.1709

**Comment by stephenroller** [comment]
When I evaluate using `python examples/eval_model.py -m projects.personachat.persona_seq2seq:PersonachatSeqseqAgentSplit -mf models:convai2/profilememory/profilememory_convai2_model --dict-file models:convai2/profilememory/profilememory_convai2.dict -t convai2` I get 16.7 F1.

When I eval using eval_f1.py, I get an F1 of 17.09 (vs the 16.7 above). So the eval_f1.py is doing something slightly different than the root directory evaluation script (idk what, I'd have to ask the others). You're saying when you retrained the model and evaluate using eval_f1.py, you get 16.4?

W.r.t. training the model and getting 0.3 F1 off, that's pretty close, especially for such a low performing model. Training is a naturally stochastic process and it wouldn't surprise me if this weak model also has high variance. It's also not an official or supported baseline, so we're not really concerned about replicability of that number.

I'd be more concerned if I saw that difference on one of the supported baselines.

**Comment by stephenroller** [comment]
If I evaluate the pretrained model using eval_f1.py on commit `cb7c03f0e736efe893b6319bb6903bdfb59130b1` then I get 16.37, which is *extremely* close to your training... hmm

**Comment by emilydinan** [comment]
Hi @christqoh -- thanks for all of your questions. As it is not an official baseline for the competition we are going to remove this code. If you are interested in working on it, you can feel free to submit a PR. Keep in mind that we still have scripts for evaluating and interacting with this model located in the projects/personachat folder. Please see PR #1073.
