### ISSUE TITLE
Can't review turkers work on amazon requester?!

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#1068]
<img width="566" alt="screen shot 2018-08-14 at 11 10 21 am" src="https://user-images.githubusercontent.com/25429471/44109774-bbc3f936-9fb2-11e8-9b2d-4191461becaf.png">

Hello, I have successfully run an adapted version of personachat_chat, I have paid money using amazon mechanical turk and collected my data as .pkl files, however, I would like to reject certain turkers for not completing the task correctly, but nothing shows up under my manage tab in the requester website? Please see image above.

How can I make my turkers work appear above here so I can manually approve / reject their work?

Thank you

**Comment by JackUrb** [comment]
Hi @josharnoldjosh - Amazon MTurk (for some reason) does not allow tasks created using the API to be viewed under their batch list unfortunately. You'll need to write up a quick script that will unpickle and display an example for you and then await your input to call approve work or reject work.

**Comment by josharnoldjosh** [comment]
Thank you for the fast reply, does this have to be done while the HIT is active as in ‘worlds.py’ ? What function would I call on the agent? ‘Agent.reject()’? Thanks!

**Comment by emilydinan** [comment]
@josharnoldjosh , no you can simply set up an mturk_manager (as is done in your run.py) file and call `reject_work` here https://github.com/facebookresearch/ParlAI/blob/f5f276996391171b928743af0abfb803da6ecde4/parlai/mturk/core/mturk_manager.py#L1471 provided you have the assignment id of the hits you want to reject (be sure to save this information in your pickle files).

**Comment by JackUrb** [comment]
As long as you've stored the assignment id you can do so at any point until the auto approval window is exceeded. The `delete_hits.py` script has an example of how that can be done: https://github.com/facebookresearch/ParlAI/blob/f5f276996391171b928743af0abfb803da6ecde4/parlai/mturk/core/scripts/delete_hits.py#L166

@emilydinan's suggestion also works for after-the-fact approvals.

You can also do it while the hit is active in worlds.py using `agent.approve_work()` or `agent.reject_work()`, however this is only really useful if you have an automated metric for approving and denying, which is hard to create for dialogue HITs.

**Comment by josharnoldjosh** [comment]
Great, what is the assignment ID and how can I access it? Is it a variable in `worlds.py`? for example, `self.assignment_id`? I would like to save it along with my Pickle files. Thanks!

**Comment by hossa95** [comment]
yes I would like to know how to get the assignment_id?

**Comment by JackUrb** [comment]
You can see how we save them in some of our examples, such as [this one](https://github.com/facebookresearch/ParlAI/blob/master/parlai/mturk/tasks/convai2_model_eval/worlds.py)

**Comment by josharnoldjosh** [comment]
I am getting an weird error, is it possible to get some help with it?

`Traceback (most recent call last):
  File "mark_bad.py", line 40, in <module>
    is_bad(file) # mark bad
  File "mark_bad.py", line 29, in is_bad
    reject(idx, "You have not completed the task. You disconnected midway through the conversation.")
  File "mark_bad.py", line 20, in reject
    client.reject_assignment(AssignmentId=idx, RequesterFeedback=reason)
  File "/anaconda/lib/python3.6/site-packages/botocore/client.py", line 317, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/anaconda/lib/python3.6/site-packages/botocore/client.py", line 615, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.RequestError: An error occurred (RequestError) when calling the RejectAssignment operation: This operation can be called with a status of: Submitted (1534700444183)`

Below is my code I am using:

`
import data_helper
from data_helper import *
from pprint import *
import parlai.mturk.core.mturk_utils as mturk_utils

mturk_utils.setup_aws_credentials()
client = mturk_utils.get_mturk_client(False)

def get_assignments(file):
	assignment_ids = file["assignment_ids"]
	result = []
	for agent in assignment_ids:
		agent_id = agent["agent_id"]
		assignment_id = agent["assignment_id"]		
		result.append(assignment_id)
	return result

def reject(idx, reason):
	print("Rejecting:", idx)
	client.reject_assignment(AssignmentId=idx, RequesterFeedback=reason)

def is_bad(file):
	d = file["dialog"]

	# Reject both if conversation is too short
	if len(d) <= 2:
		assignment_ids = get_assignments(file)
		for idx in assignment_ids:				
			reject(idx, "You have not completed the task. You disconnected midway through the conversation.")
	else:
		# Reject opposite of last user otherwise 
		agent_id_to_reject = d[-1][0]
		assignment_id = get_assignments(file)[1-agent_id_to_reject]
		reject(assignment_id, "You have not completed the task. You disconnected midway through the conversation.")

for name in get_files():
	with open(name, 'rb') as file:
		if "incomplete" in name:
			file = pickle.load(file)
			is_bad(file) # mark bad
		
print("Script done.")
`

**Comment by JackUrb** [comment]
You can't reject an assignment that hasn't been submitted. If someone disconnected midway, they can't collect anyways.

**Comment by josharnoldjosh** [comment]
Great, so just to confirm, turkers relating to these "incomplete.pkl" files will not be paid?

**Comment by JackUrb** [comment]
The one who disconnected will not be paid. You *have* to pay the worker that was disconnected on or it's a violation of MTurk TOS.

**Comment by josharnoldjosh** [comment]
Okay, because many of my conversations contain literally ZERO dialog, because one turker will disconnect right at the start. I feel I am paying the other turker for free even though they haven't typed a single letter yet. Is there anyway around this?

**Comment by JackUrb** [comment]
You can set the base pay really cheap and pay out in bonuses. I'm working on supporting this natively but for now you'll have to implement it for your specific task

**Comment by josharnoldjosh** [comment]
How can I pay a bonus? What is the command? `worker.pay_bonus(amount=0.2)`?

**Comment by emilydinan** [comment]
@josharnoldjosh use this script: https://github.com/facebookresearch/ParlAI/blob/master/parlai/mturk/core/scripts/bonus_workers.py

**Comment by farnazgh** [comment]
> As long as you've stored the assignment id you can do so at any point until the auto approval window is exceeded. The `delete_hits.py` script has an example of how that can be done:
> 
> https://github.com/facebookresearch/ParlAI/blob/f5f276996391171b928743af0abfb803da6ecde4/parlai/mturk/core/scripts/delete_hits.py#L166
> 
> @emilydinan's suggestion also works for after-the-fact approvals.
> 
> You can also do it while the hit is active in worlds.py using `agent.approve_work()` or `agent.reject_work()`, however this is only really useful if you have an automated metric for approving and denying, which is hard to create for dialogue HITs.

I have set up a model chat task on Amazon using Mephisto and want to reject some works because of the low quality.
@JackUrb Is your solution provided above still applicable? with the transition of files, using database and etc since 2018
If it is yes, I was wondering that for rejecting a work, how can I set the client argument first?

**Comment by JackUrb** [comment]
Yes this API and usage still are the same.

> how can I set the client argument first?

I'm not sure I understand the question. If you have the `Agent` in local memory associated with the low-quality task, you can just call `Agent.reject_work()`.

**Comment by farnazgh** [comment]
Thanks for your reply.
As far as I understood, `Agent.reject_work()` can be used when the hit is still active. However, in my case, the hits have been completely finished, and I don't have access to the `Agent` in my local memory anymore. For such case, you mentioned that the `delete_hits.py ` script has an example of how that can be done. However, my problem here is that I don't know how to set the `client`. 
Or maybe there is something which I misunderstood.

**Comment by farnazgh** [comment]
> I'm not sure I understand the question. If you have the `Agent` in local memory associated with the low-quality task, you can just call `Agent.reject_work()`.

Thanks for your reply.
As far as I understood, `Agent.reject_work()` can be used when the hit is still active. However, in my case, the hits have been completely finished, and I don't have access to the `Agent` in my local memory anymore. For such case, you mentioned that the `delete_hits.py ` script has an example of how that can be done. However, my problem here is that I don't know how to set the `client`. 
Or maybe there is something which I misunderstood.
