### ISSUE TITLE
Update tasks in task_list.py

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/ParlAI#108]
The list of tasks in [task_list.py](https://github.com/facebookresearch/ParlAI/blob/master/parlai/tasks/task_list.py) is outdated and does not include tasks like VQA and VisDial.

**Comment by jaseweston** [comment]
Duplicate of issue https://github.com/facebookresearch/ParlAI/issues/73.
However -- we will do this v. soon!
