### ISSUE TITLE
Reproduce the drQA performance

### ISSUE THREAD

**Issue by hwaranlee** [facebookresearch/ParlAI#109]
Using GloVe pre-trained word vectors and the default hyper-parameters, I've gotten the performance EM=52.87 F1=64.47, which is far lower than the reported performance (EM=69.5, F1=78.8) in the paper. (http://arxiv.org/abs/1704.00051)
Did you reproduce the performance?

**Comment by ajfisch** [comment]
Perhaps you have something incorrect in your setup.

Running in ParlAI, we get EM = 66.4, F1 = 76.5. This was after 78k iterations of batch size 32; using the default parameters with glove.840.300d vectors and tune_partial set to 1000.

**Comment by hwaranlee** [comment]
Thanks! 
I used no -bs option resulting in batch size 1
