### ISSUE TITLE
wrapper for custom eval_ppl.py module

### ISSUE THREAD

**Issue by Henry-E** [facebookresearch/ParlAI#1094]
Context: Implementing a custom eval_ppl.py module for an external model as part of the convai2 task

Based on how eval_ppl is called in the various examples, it seems to be fairly hardcoded that it needs to run `PerplexityWorld` and an agent needs a `next_word_probability()` function. I'm having trouble figuring out how this could work in a batch act setting. Otherwise I'll need to call `next_word_probability()` for every single cumulative sequence of words, which in terms of overhead for calling an external model each time is not super feasible.

Is there an obvious way that I'm missing, to return the perplexity probabilities as a batch?

**Comment by Henry-E** [comment]
Right ok, I will try to see if I can possibly run a server or have a preloaded model sitting somewhere to cut down on overhead. Otherwise it's looking like it would take over a day to calculate perplexity when processing one example at a time.

**Comment by stephenroller** [comment]
Depending on your model, you could add PPL calculations as a metric at eval time in your own `batch_act`. This is what's done for seq2seq and fairseq agents these days.

**Comment by emilydinan** [comment]
To be clear, @stephenroller 's suggestion is for calculating perplexity during training or evaluation as a way of evaluating roughly how your model is doing. However, for the competition we do require the official `eval_ppl` script which implements the `next_word_probability` function for your model and we will not accept model reported perplexity.

**Comment by stephenroller** [comment]
Yes, thanks for clarifying @emilydinan
