### ISSUE TITLE
Movie Dialog Recommendations Questions - User IDs

### ISSUE THREAD

**Issue by tebesu** [facebookresearch/ParlAI#1103]
I am attempting to replicate the results for SVD++ for task 2 on the"Movie Dialog Recommendations Questions asking for movie recommendations" dataset. I could not find a user mapping/ids to reconstruct the user-item ratings matrix. Am I missing something?

**Comment by alexholdenmiller** [comment]
Hi @tebesu! The data is not in that format; rather, each example is a different "user", and we just assigned a unique index to each movie.

So we can build the matrix with e.g. the first example:
```
I really like Jaws, Bottle Rocket, Saving Private Ryan, Tommy Boy, The Muppet Movie, Face/Off, and Cool Hand Luke. Can you recommend a film?
```
Where this is user 0, Jaws is movie 0, Bottle Rocket is movie 1, and so on...

I'll close for now but feel free to reopen if you have more questions!
