### ISSUE TITLE
PersonaChat Dataset: which one is the test set.

### ISSUE THREAD

**Issue by fuzhenxin** [facebookresearch/ParlAI#1112]
As described in the paper (Personalizing Dialogue Agents: I have a dog, do you have pets too?), the test set contains 1000 dialogs and the valid set contrains 768. 
But the dateset downloaded from http://parl.ai/downloads/personachat/personachat.tgz shows the size are 768 for test and 1000 for valid. 
Which one is the test used to report results in the paper? 
Thank you!

**Comment by alexholdenmiller** [comment]
768 => 968

I think the paper accidentally flipped them, the file names should be more accurate and do appear to be 1000 valid and 968 test. I'll double-check with the authors.

**Comment by fuzhenxin** [comment]
Thank you!
