### ISSUE TITLE
Problem about Convai2 evaluation on metric hit@1

### ISSUE THREAD

**Issue by caoyu1991** [facebookresearch/ParlAI#1123]
Hello, I have trained a model using pytorch and I am trying to use the scripts provided in projects/convai2 to evaluate its performance on valid set. But I found that these two scripts eval_f1.py and eval_ppl.py worked well but error occurred in eval_hits.py because no attribute 'hit@1' was generated in the final report. 
So is there anyone can help with this issue? Thank you!

**Comment by alexholdenmiller** [comment]
Hi @caoyu1991, thanks for reaching out!

Just to make sure this isn't it: the attribute is `hits@1` with an `s`. I didn't see any of our scripts with the misspelling, let me know if I missed something!

But if that's not the issue, then note that the model will only be scored for ranking if it actually returns ranked candidates. That is, the `hits@1` metric will only be populated if the model returns a ranked set of candidates in the `text_candidates` field during its `batch_act` method--these are used for calculating that metric. If your model doesn't do ranking, that is okay as well--it can just enter with the other metrics.

Let us know if we can help further!

**Comment by stephenroller** [comment]
Closing this since the original question seems resolved. Please reopen it if you continue having trouble, @caoyu1991.
