### ISSUE TITLE
Adding HTML componantes 

### ISSUE THREAD

**Issue by hossa95** [facebookresearch/ParlAI#1128]
hello
I am making a dialog task and I want to add HTML components to the task message such as buttons and radio buttons and take the input from these components instead of making the agent write the answer. 
here is an example similar to what i want to do 
![image](https://user-images.githubusercontent.com/16920738/44842608-9f979600-ac46-11e8-9c08-6e289a9b9c86.png)

any help where to start and what files to override?

**Comment by JackUrb** [comment]
Hi @hossa95, happy to help: You can see some examples of making custom html in the [talkthewalk task](https://github.com/facebookresearch/ParlAI/tree/master/parlai/mturk/tasks/talkthewalk/html). The basic idea is that you can extend the core.html file, and then override the right pane referenced here: 
https://github.com/facebookresearch/ParlAI/blob/bdd404659c30376e7fed7896cf0d2aac1b493d1a/parlai/mturk/core/server/html/core.html#L27
You can copy the contents of the default right pane and then just replace the content of the `response-type-text-input` div. You'll then need to override some of the javascript in `{% block additional_scripts %}` to ensure you're pulling the content of your new HTML, the function to override is here: https://github.com/facebookresearch/ParlAI/blob/bdd404659c30376e7fed7896cf0d2aac1b493d1a/parlai/mturk/core/server/html/core.html#L739

Once you have your custom HTML, you can put it in the html folder of your task, and then name it `<id>_index.html` where `<id>` is the value you'll put into `agent.id` in your run file.

Let me know if you have any other questions!

**Comment by JackUrb** [comment]
Closing as an answer has been provided and there hasn't been activity since.
