### ISSUE TITLE
[convai2] decreasing performance

### ISSUE THREAD

**Issue by trog-levrai** [facebookresearch/ParlAI#1151]
Hello,

We are currently preparing an application for the competition and we are facing a problem since a couple of weeks now.

When using our own evaluation scripts, we obtain a result that seems fair.
When we move the model to use ParlAI library using a custom Agent implemented thanks to this [tutorial](http://www.parl.ai/static/docs/seq2seq_tutorial.html), the performance logged seems correct (similar to our previous results) at the beginning and then slowly decreases at each log print.

We therefore think we made a mistake in our Agent implementation but can't find it. Answers provided by the model seem relevant to us. Might it be because ParlAI feeds the examples in a particular order ?

Has anyone heard about such problem ? We think it could be a common mistake that comes from our poor ParlAI skills.

**Comment by emilydinan** [comment]
Hi @trog-levrai, can you give some more context? Which metrics slowly decrease? Are these self-reported metrics or ones that are automatically calculated by ParlAI? If it's the latter, have you tried comparing the output of your model with the `eval_labels`?

**Comment by Henry-E** [comment]
One thing that wasn't immediately obvious to me was that the personas are only provided in the first act of each dialogue. And it's up to the agent to keep track of the personas and dialogue history itself in each successive act.

**Comment by alexholdenmiller** [comment]
One thing you can try is to turn on the `--batch-sort` flag, which crudely flattens the examples into single pieces of text by concatenating them with newlines. This limits the amount of preprocessing that you can easily do (e.g. add `__p1__` / `__p2__` tokens before each speaker, etc) but will solve the issue of forgetting the past utterances if that is what is plaguing you.

https://github.com/facebookresearch/ParlAI/blob/cd9cd142b1b5a78d2db88cf77ce2ccbf6653bd90/parlai/core/params.py#L314-L321

**Comment by trog-levrai** [comment]
The metric decreasing is the F1 calculated by ParlAI (self reported metric looks fine). I do keep a good track of previous utterances in a dialog and reset it when I see the episode_done flag. And the problem occurs whether I use batching or not.

When compared to eval_labels, the output looks correct even though it is hard to evaluate since the model is specifically made to generate diverse answers.

For example, self reported F1 stays around 16.07 whether I shuffle the validation data or not.
Whereas ParlAI F1 starts higher than expected and quickly falls to 14:

```
2s elapsed: {'exs': 51, '%done': '0.65%', 'time_left': '304s', 'f1': 0.1822}
4s elapsed: {'exs': 103, '%done': '1.32%', 'time_left': '301s', 'f1': 0.1667}
6s elapsed: {'exs': 155, '%done': '1.99%', 'time_left': '299s', 'f1': 0.1602}
8s elapsed: {'exs': 207, '%done': '2.65%', 'time_left': '297s', 'f1': 0.1561}
10s elapsed: {'exs': 259, '%done': '3.32%', 'time_left': '295s', 'f1': 0.1546}
12s elapsed: {'exs': 311, '%done': '3.99%', 'time_left': '293s', 'f1': 0.1559}
14s elapsed: {'exs': 362, '%done': '4.64%', 'time_left': '291s', 'f1': 0.1519}
16s elapsed: {'exs': 414, '%done': '5.31%', 'time_left': '289s', 'f1': 0.1494}
18s elapsed: {'exs': 465, '%done': '5.96%', 'time_left': '287s', 'f1': 0.1486}
20s elapsed: {'exs': 516, '%done': '6.61%', 'time_left': '285s', 'f1': 0.1483}
22s elapsed: {'exs': 568, '%done': '7.28%', 'time_left': '283s', 'f1': 0.1486}
24s elapsed: {'exs': 619, '%done': '7.93%', 'time_left': '281s', 'f1': 0.1486}
26s elapsed: {'exs': 670, '%done': '8.59%', 'time_left': '280s', 'f1': 0.1466}
28s elapsed: {'exs': 721, '%done': '9.24%', 'time_left': '278s', 'f1': 0.146}
```

Perplexity actually behaves the same way:

```
4s elapsed, 0.0128%% complete, {'exs': 1, 'loss': 3.4, 'ppl': 30.11}
8s elapsed, 0.0256%% complete, {'exs': 2, 'loss': 4.55, 'ppl': 94.96}
10s elapsed, 0.0385%% complete, {'exs': 3, 'loss': 4.75, 'ppl': 115.6}
12s elapsed, 0.0513%% complete, {'exs': 4, 'loss': 5.19, 'ppl': 179.8}
17s elapsed, 0.0641%% complete, {'exs': 5, 'loss': 5.39, 'ppl': 219.1}
22s elapsed, 0.0769%% complete, {'exs': 6, 'loss': 5.54, 'ppl': 255.0}
25s elapsed, 0.0897%% complete, {'exs': 7, 'loss': 5.51, 'ppl': 247.7}
29s elapsed, 0.103%% complete, {'exs': 8, 'loss': 5.94, 'ppl': 379.5}
32s elapsed, 0.115%% complete, {'exs': 9, 'loss': 5.79, 'ppl': 327.4}
35s elapsed, 0.128%% complete, {'exs': 10, 'loss': 5.68, 'ppl': 293.8}
39s elapsed, 0.141%% complete, {'exs': 11, 'loss': 5.69, 'ppl': 295.6}
```

**Comment by stephenroller** [comment]
This is a running average of the metrics, based on just the 721 or 11 examples evaluated, respectively. You can't really trust average ppl in just 11 examples.

Why your F1 is 16.07 and ParlAI's estimate's 14.6, I'm not quite sure. You could try limiting the number examples to 1 and seeing if the numbers agree or disagree.

**Comment by trog-levrai** [comment]
The perplexity increases the same way, after 37% of the dataset passed, it increases until 395.2

Actually I've checked the first examples in both cases, even though answers look fine, they are not the same:

> hello what are doing today ?
> i'm good . i'm in college . i just finished college . you ?

vs.

> hello what are doing today ?
> i'm good , just got a new job . you ?

So I will investigate on possible problems with data pre-processing. It needed heavy changes from the original version to ParlAI. It might be the root of the problem.

Thank you all for your help, I'll do my best not to bother you ;-)

**Comment by alexholdenmiller** [comment]
I'm going to close this for now, please reopen if you need more help!

**Comment by Henry-E** [comment]
My other theory about why this could be is that the initial parts of the dialogue tend to be formulaic and easier to get correct. Whereas as later parts of the dialogue diverge and may be more difficult. I've seen more or less the same trend in my models since I finally got evaluation working.
