### ISSUE TITLE
Approve by Worker ID

### ISSUE THREAD

**Issue by AsserAboElkhair** [facebookresearch/ParlAI#1152]
I made a conversational task between 2 turkers (one like `personachat_chat`), therefore I only have worker ids (not assignment id) for each submission, how can I approve one of workers in each conversation only by `worker id`?

**Comment by emilydinan** [comment]
Hi @AsserAboElkhair, you will need either the HIT ID or Assignment ID to manually approve/reject work from workers. You can see, for example, how these IDs are saved in this task: https://github.com/facebookresearch/ParlAI/blob/cd9cd142b1b5a78d2db88cf77ce2ccbf6653bd90/parlai/mturk/tasks/convai2_model_eval/worlds.py#L544-L545

If you don't want to review manually, you can set an auto approve delay time with the `--auto-approve-delay` flag or call `agent.approve_work()` at the close of your task: https://github.com/facebookresearch/ParlAI/blob/cd9cd142b1b5a78d2db88cf77ce2ccbf6653bd90/parlai/mturk/core/agents.py#L449

**Comment by JackUrb** [comment]
If you only had one assignment per worker it is technically possible to review by worker id, but really only by querying all your hits from the API and cross referencing to get the assignment or hit ids

**Comment by AsserAboElkhair** [comment]
Hello @emilydinan , @JackUrb ,

Thank you for your fast response, as I understood from you, that I cannot approve or reject work using only `worker id`, if that true, how can I pay workers already did tasks but I didn't save the `assignment id` nor `hit id`?

**Comment by JackUrb** [comment]
The work will auto-approve in one week based on the ParlAI-MTurk defaults.

**Comment by AsserAboElkhair** [comment]
Thank you, @JackUrb @emilydinan
