### ISSUE TITLE
Unreachable code block in MemnnAgent

### ISSUE THREAD

**Issue by bhancock8** [facebookresearch/ParlAI#1197]
The MemnnAgent has code suggesting that it can handle provided candidate lists, but it doesn't actually currently support it, in part because of this line:

https://github.com/facebookresearch/ParlAI/blob/7e0fabb7fb60b0bcf81b6615f89566689ab1f31e/parlai/agents/memnn/memnn.py#L370

**Comment by alexholdenmiller** [comment]
Wow thanks for noticing that sneak in there, I had been debugging the candidate-less setting. Fixing now.

**Comment by alexholdenmiller** [comment]
#1198 merged
