### ISSUE TITLE
how do I close the app?

### ISSUE THREAD

**Issue by nihiluis** [facebookresearch/ParlAI#1215]
when im hitting ctrl c parlai doesnt stop. it instead writes "Expiring all unassigned HITs" (in a loop?).

now i can just hit ctrl c again, but if i dont wait long enough the heroku server and the mturk task will kinda orphan. it seems parlai is interrupted that way.

**Comment by JackUrb** [comment]
Hi @nihiluis - this is something of a known problem related to how Amazon actually follows through on the expirations. The system currently waits for the entire task duration expiring repeatedly throughout until the tasks should have all run out (based on how long the workers are supposed to have to work on the task). You can use the beta `MTurkManager(use_db=True)` flag to get a feature that better keeps track of the HITs to ensure the expiration worked properly.

**Comment by nihiluis** [comment]
there's no change as far as i can see.

```
    mturk_manager = MTurkManager(
        use_db=True,
        opt=opt,
        mturk_agent_ids=[mturk_agent_id]
    )
```

**Comment by JackUrb** [comment]
There appears to be a regression on this one as I've been working through the db feature - I'll have things worked out soon.

**Comment by koustuvsinha** [comment]
Hi @JackUrb, any updates on this? I think a related issue for me is when I do not wait enough and hit Control-C again, sometimes it skips the step of deleting the Heroku server and my task remains in the AMT list, showing users the base Heroko page "There is nothing here". By trial and error I have seen if only I wait enough (like 3-4 messages of "Expiring all unassigned HITs...") and then hit Ctrl+C, Heroku server is safely deleted along with the task.

On that note, is there any way I can _clean_ my previous open tasks? I failed to safely delete the Heroku server on a live mturk collection deployment and I still get email from turkers noting that the page shows "There is nothing here".

**Comment by JackUrb** [comment]
I've had this on the back burner for a little in favor of some other work, but it's coming up on the roadmap for next week. For orphan hits you can use the delete_hits script in the mturk/core/scripts folder.

**Comment by koustuvsinha** [comment]
@JackUrb I tried to delete the old dangling hits using the script, but even after successfully deleting all the HITs when I re-run the script I still find them active! (same number of hits active as before) Does it take long time for AMT to reflect on the hit status?

**Comment by JackUrb** [comment]
The delete hits script will expire the hits, but they'll still be visible from running the hit
