### ISSUE TITLE
Do you consider adding transformer to agents? 

### ISSUE THREAD

**Issue by zhaoguangxiang** [facebookresearch/ParlAI#1217]
Transformer works well on NMT. I wonder why it is not used in dialogue generation .

**Comment by stephenroller** [comment]
We are using it, but have not made our implementation public yet. We expect to have a public version you can "beta test" in the 1-2 week range.

**Comment by stephenroller** [comment]
In the meantime, you can use fairseq's implementation to play with using `-m fairseq --arch transformer`

**Comment by stephenroller** [comment]
Hmm, looks like there's a problem with an empty batch somewhere. Can you give the full command you ran?

**Comment by stephenroller** [comment]
Yeah should be merging in #1283 later today.
