### ISSUE TITLE
Error while trying to display examples from ubuntu corpus

### ISSUE THREAD

**Issue by skckompella** [facebookresearch/ParlAI#123]
> skc@Ultron:~/git/other_repos/ParlAI$ python3 examples/display_data.py -t ubuntu -n 10
> [download_path:/Users/skc/git/other_repos/ParlAI/downloads]
> [parlai_home:/Users/skc/git/other_repos/ParlAI]
> [numthreads:1]
> [num_examples:10]
> [datatype:train]
> [batchsize:1]
> [datapath:/Users/skc/git/other_repos/ParlAI/data]
> [no_images:False]
> [task:ubuntu]
> [creating task(s): ubuntu]
> [building data: /Users/skc/git/other_repos/ParlAI/data/Ubuntu]
> 100% [......................................................................] 199132376 / 199132376
> unpacking ubuntu.tar.gz
> [DialogTeacher initializing.]
> loading: /Users/skc/git/other_repos/ParlAI/data/Ubuntu/train.csv
> Traceback (most recent call last):
>   File "examples/display_data.py", line 42, in <module>
>     main()
>   File "examples/display_data.py", line 35, in main
>     world.parley()
>   File "/Users/skc/git/other_repos/ParlAI/parlai/core/worlds.py", line 219, in parley
>     acts[0] = agents[0].act()
>   File "/Users/skc/git/other_repos/ParlAI/parlai/core/dialog_teacher.py", line 130, in act
>     action, self.epochDone = self.next_example()
>   File "/Users/skc/git/other_repos/ParlAI/parlai/core/dialog_teacher.py", line 115, in next_example
>     action, epoch_done = self.data.get(self.episode_idx, self.entry_idx)
>   File "/Users/skc/git/other_repos/ParlAI/parlai/core/dialog_teacher.py", line 287, in get
>     if table['labels'][0] not in table['label_candidates']:
> TypeError: argument of type 'NoneType' is not iterable

Other datasets like babi, dialog_babi and MovieDialog are displaying fine.

**Comment by alexholdenmiller** [comment]
Hi @skckompella, thanks for the report but it should be fixed now from #117. Please pull and try again!

**Comment by skckompella** [comment]
Thanks!
