### ISSUE TITLE
custom personachat data set problem

### ISSUE THREAD

**Issue by wxs19920926** [facebookresearch/ParlAI#1257]
I am building my data set，but  I have some troubles. that is  
![1](https://user-images.githubusercontent.com/13505973/47717072-9c894800-dc7f-11e8-890d-431ef2be64dd.png)
ValueError: could not convert string to float: 'Straight Just a bit too defensive'

**Comment by emilydinan** [comment]
Can you send the command you ran?

**Comment by wxs19920926** [comment]
@emilydinan 
python examples/display_data.py --task personachat --datatype train  
address is https://github.com/facebookresearch/ParlAI/tree/master/projects/personachat

**Comment by wxs19920926** [comment]
@emilydinan the data set built by myself,i don't know what's the problem. for example  
1 your persona:I told her I had a band.
2 your persona:I have had awesome time 10 feet away from the band.
3 your persona:my dick was sticky brown.
4 your persona:I was pretending to be a keyboard player from a power metal band.
5 your persona:I knew a guy who loved this band.
6 I actually like being alone on my birthday. My father had a shitty over-privileged over-shitty upbringing, with nine kids. His mother was a a giant abusive alcoholic cunt, so his experience with birthdays were not healthy to say the least.  As a result, my birthdays were a time for my father to go out of his way to be an asshole to me. Obsess on every action I made, then make a pointed shitty comment to me about how I did it wrong, at the worst possible time. Base Examples:Pinata at my birthday party. My father was "officiating" these stupid children games to make us all exercise, one of which being a pinata.  My father wasn't around for a bit, so my mother said to go ahead and start the game. I asked all of my friends, about 10 kids to go ahead, but they all wanted me to go because it was my birthday. Well I knew better but just went ahead, they were all chiding me to go. Well I start to swing at this shopping bag full of tootsie rolls, hanging from our shitty basketball rim. The next thing I feel is an intense pain on my hands, and the sounds of a yelling asshole. That's right, he went out of his way to go pick up a stick and hit me with it while I was blindfolded. Then laid into a profane tirade about how I was a selfish disappointment.  All the while, my friends pleading with him to stop, because they told me to go first. Didn't matter you can never prove an asshole like that wrong. I had to stop, and sit out the rest of activities, and I got it later from him. Nothing like having your friends tell you that your dad is a crazy jerk when you're 10, and only being able to agree with them. I had been actively aware of this since I was about 6. Around the time birthday cake would be served my father would bring up my weight by bluntly saying "you're fat", out loud, in front of all of my friends/ family, right when I was about to put the first bite in my mouth. This happened regularly throughout my childhood especially on my birthday. The continuous overall disappointment of my mother in general making promises or trying to do something nice, and letting my father shit all over it if the slightest aesthetic is out of place in his crazy sick mind. Launching into insane fucked up tirades at top volume.  The overall shitty attitude that started to affect everyone else in my family around the holiday's in general too. As I grew up and moved on, I got into a business that monopolised my time and I even though I was the boss I would volunteer to work holiday's and birthday's. It was bliss sitting in an empty office with life sucking fluorescent lighting working, alone. Over time, I stopped talking to people on my birthday and would just sleep. People would ask me what I want for my birthday and I would say, "I want you to leave me alone". I wouldn't even answer my phone. Having the mere freedom to sleep, smoke weed, jerk off, and be left alone were paradise for me. Usually I just got my Drivers License renewed. tl;dr Birthdays are irrelevant by the time you hit your mid-20's; be happy that you have free time, and a curious mind to do whatever the fuck you want alone.	Inthink this is one of the most sad comment I've ever read on here.I'm so sorry to hear your did was a complete miserable asshole :(		Inthink this is one of the most sad comment I've ever read on here.I'm so sorry to hear your did was a complete miserable asshole :(|I agree. On my birthdays I just enjoy being around some people that I genuinely enjoy being around, but it is a small group. I don't want anything big or fancy. More than happy to be alone on my birthday.|Although my life story isn't so bad, I can sympathise. My depression, and fear that my friends don't care about me, has lead me to forget when my actual birthday is (if I need it, it's on my ID). I don't care about it.|I see no problem in wanting to be alone btw sorry about your childhood anyway HAPPY BIRTHDAY!!!!!!|Happy cakeday dude :(
7 ask her friend Craka Mikehttp://profile.myspace.com/index.cfm?fuseaction=user.viewprofile&amp;friendid=29049030His Blog's sublime. "Monday, July 28, 2008  	How Do U Work dis ShitWut Da Flip!! Ahaha lets see It goes hilary clinton, barack obama, made da word trap or die ask dj drama/ It goes feak big meech &amp; mutha fuck Osama (yeah)an he aint talkin bout nuthin so what's up lil mama/ I think ya girl won't me &amp; If she don't she should!!"	Straight Just a bit too defensive		Straight Just a bit too defensive|that dude looks like he's trying to keep up with the Jersey [douchebags](http://www.asklopan.com/pictures13.php)|YO I LOVE KRACKA MYKE HE'Z HELLA TIGHT|You spelled his name wrong... as he says himself, Okay lets see my name is Michael Redmond but spellin my name like that is pretty gay so I spell it like this "MYKOLE" now thats better...|All the girls won't him.
8 In the south you get called a "fagoot", by strangers if you order a burger with ketchup. It has happened to me more than once, an entire bar full old timers stopped to stare at me the first time I tried that. Ketchup if for french fries.Therefor Hannity is a faggot, according to the south.EDIT come on out to the Middle Tennessee, and find out for yourselves faggots.	What's the preferred condiment?		What's the preferred condiment?|I've lived in 'the South' my entire life (Alabama, Louisiana, Florida) and I have never, not once, ever heard of this. You're either making this up or you have had one really unfortunate experience and are making sweeping, inaccurate statements based on your anecdotal experience(s) :P|What part of the south did you go to? I live in TN which isn't too deep in the south, but everyone here eats them with ketchup.|Well for one thing, you don't *order* a burger with ketchup or mustard. You put those things on yourself. Besides, "Fagoot" is a brand of ketchup. They were just recommending something.|Oh nice, let us just make shit up because that'll help the community.
9 One of my mechanics had just gotten married to a shy buck toothed Asian girl. She was very quiet. One day the mechanic was on the phone to his father in law, he laughed and mentioned that she was just acting stupid. His father in law said something and he said, "What? Literally?".He slams down the phone, and said "Great, I just found out my wife is retarded.", and storms out of the office. Her bucked teeth threw off the speech impediment, plus he thought that she didn't know English very well being Asian.  Nope, retarded.	Suspicious... is this mechanic of yours called Ben T. Slightly by any chance??		Suspicious... is this mechanic of yours called Ben T. Slightly by any chance??|You never marry full retard!|You'd think the drooling and pants pissing would have tipped him off.|That's why you need a RE-nup.|Oh my god
10 Why do we sleep?	Another good one.		Another good one.|Better: Why do we awake?|Radiolab did a really interesting show on sleep as well.Blog: http://www.wnyc.org/shows/radiolab/episodes/2007/05/25mp3 download: http://audio.wnyc.org/radiolab/radiolab052507pod.mp3|Think of it this way... when you exercise, your muscles get 'tired' and need time to recover (remove lactic acid, replenish glucose etc.). Your brain is perhaps similar. Not a perfect analogy, but it goes some way to answering the question.Another relevant point - we sleep because our hypothalamus regulates the wakefulness of your brain. It triggers the brain to begin changing to resting state (parts of the brain fall asleep progressively.. hence sleep walking and talking without consciousness - the consciousness part falls asleep but the motor cortex forgets to!) and vice versa.Experiments with rats showed that damage to the hypothalamus could trigger rats to sleep permanently, or never to sleep.|Among other possible reasons, it could be avoidance of predators or injury. We don't really need to hunt/gather 24/7 to sustain ourselves, it might simply evolved as a net fitness gain by avoiding unworthy risk

**Comment by alexholdenmiller** [comment]
It looks like there's a tab in your text on that line. Be sure that...

- there are no tabs anywhere except to distinguish between text, label, reward, and candidate fields
- there are no pipes anywhere except to distinguish between different labels or candidates
- there are no newlines except to go to a new line

These characters are protected in this format.

**Comment by wxs19920926** [comment]
Thanks for your help, but I have encountered a lot of similar formatting problems, I don't know what went wrong, it just prompts ValueError: could not convert string to float: 'Straight Just a bit too defensive'

**Comment by alexholdenmiller** [comment]
I'm nearly certain you have an unintentional tab in that line in the file. The string to float conversion is supposed to occur on a field which would contain the reward. because you have an extra tab, the label field was pushed into the reward field, where it cannot be parsed.

You can try running the script with `python -m pdb -c -c` to inspect the `line` and `split` variables directly and see what they contain, if you'd like.

**Comment by wxs19920926** [comment]
@alexholdenmiller I debug according to your method, found that the value of split[2] is None, and found the comment: x<tab>y<tab>reward<tab>label_candidates. According to this format, I made adjustments again, fixed the problem, thank you
