### ISSUE TITLE
Error running interactive.py in quick start tutorial

### ISSUE THREAD

**Issue by dalton** [facebookresearch/ParlAI#1271]
**Describe the bug**

I am working through the [quick tutorial](http://www.parl.ai/static/docs/tutorial_quick.html) and having issues "asking the model a question" myself with this command

```
python examples/interactive.py -mf /tmp/babi_memnn
...
Enter your message: John went to the hallway.\n Where is John?
```

This is the output I get

> ➜  ParlAI git:(master) python examples/interactive.py -mf /tmp/babi_memnn
> 
> [ optional arguments: ] 
> [  display_examples: False ]
> [  display_ignore_fields: label_candidates,text_candidates ]
> [  display_prettify: False ]
> [ Main ParlAI Arguments: ] 
> [  datapath: ./ParlAI/data ]
> [  datatype: train ]
> [  download_path: ./ParlAI/downloads ]
> [  hide_labels: False ]
> [  image_mode: raw ]
> [  numthreads: 1 ]
> [  pytorch_teacher_dataset: None ]
> [  pytorch_teacher_task: None ]
> [  show_advanced_args: False ]
> [  task: None ]
> [ Batching Arguments: ] 
> [  batchsize: 1 ]
> [  include_labels: True ]
> [ PytorchData Arguments: ] 
> [  batch_length_range: 5 ]
> [  batch_sort_cache: none ]
> [  numworkers: 4 ]
> [  pytorch_datafile: None ]
> [  pytorch_preprocess: False ]
> [  shuffle: False ]
> [ ParlAI Model Arguments: ] 
> [  dict_class: parlai.core.dict:DictionaryAgent ]
> [  model: None ]
> [  model_file: /tmp/babi_memnn ]
> [ Local Human Arguments: ] 
> [  local_human_candidates_file: None ]
> [  single_turn: False ]
> [ ParlAI Image Preprocessing Arguments: ] 
> [  image_cropsize: 224 ]
> [  image_size: 256 ]
> [ MemNN Arguments: ] 
> [  embedding_size: 128 ]
> [  hops: 3 ]
> [  init_model: None ]
> [  memsize: 32 ]
> [  position_encoding: False ]
> [  time_features: True ]
> [ TorchAgent Arguments: ] 
> [  add_p1_after_newln: False ]
> [  embedding_projection: random ]
> [  embedding_type: random ]
> [  gpu: -1 ]
> [  gradient_clip: 0.1 ]
> [  history_size: -1 ]
> [  learningrate: 1 ]
> [  momentum: 0 ]
> [  multigpu: False ]
> [  no_cuda: False ]
> [  optimizer: sgd ]
> [  person_tokens: False ]
> [  rank_candidates: False ]
> [  truncate: -1 ]
> [  use_reply: label ]
> [ TorchRankerAgent: ] 
> [  candidates: inline ]
> [  eval_candidates: None ]
> [  fixed_candidate_vecs: reuse ]
> [  fixed_candidates_path: None ]
> [ Dictionary Arguments: ] 
> [  bpe_debug: False ]
> [  dict_endtoken: __end__ ]
> [  dict_file: None ]
> [  dict_initpath: None ]
> [  dict_language: english ]
> [  dict_lower: False ]
> [  dict_max_ngram_size: -1 ]
> [  dict_maxtokens: -1 ]
> [  dict_minfreq: 0 ]
> [  dict_nulltoken: __null__ ]
> [  dict_starttoken: __start__ ]
> [  dict_textfields: text,labels ]
> [  dict_tokenizer: re ]
> [  dict_unktoken: __unk__ ]
> Dictionary: loading dictionary from /tmp/babi_memnn.dict
> [ num words =  26 ]
> Loading existing model parameters from /tmp/babi_memnn
> /Users/dalton/miniconda2/envs/parlai/lib/python3.7/site-packages/torch/nn/functional.py:58: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
>   warnings.warn(warning.format(ret))
> [creating task(s): parlai.agents.local_human.local_human:LocalHumanAgent]
> [ optional arguments: ] 
> [  display_examples: False ]
> [  display_ignore_fields: label_candidates,text_candidates ]
> [  display_prettify: False ]
> [ Main ParlAI Arguments: ] 
> [  datapath: ./ParlAI/data ]
> [  datatype: train ]
> [  download_path: ./ParlAI/downloads ]
> [  hide_labels: False ]
> [  image_mode: raw ]
> [  numthreads: 4 ]
> [  pytorch_teacher_dataset: None ]
> [  pytorch_teacher_task: None ]
> [  show_advanced_args: False ]
> [  task: babi:task10k:1 ]
> [ Batching Arguments: ] 
> [  batch_sort: False ]
> [  batchsize: 8 ]
> [  context_length: -1 ]
> [  include_labels: True ]
> [ PytorchData Arguments: ] 
> [  batch_length_range: 5 ]
> [  batch_sort_cache: none ]
> [  numworkers: 4 ]
> [  pytorch_datafile: None ]
> [  pytorch_preprocess: False ]
> [  shuffle: False ]
> [ ParlAI Model Arguments: ] 
> [  dict_class: parlai.core.dict:DictionaryAgent ]
> [  model: memnn ]
> [  model_file: /tmp/babi_memnn ]
> [ Local Human Arguments: ] 
> [  local_human_candidates_file: None ]
> [  single_turn: False ]
> [ ParlAI Image Preprocessing Arguments: ] 
> [  image_cropsize: 224 ]
> [  image_size: 256 ]
> [ MemNN Arguments: ] 
> [  embedding_size: 128 ]
> [  hops: 3 ]
> [  init_model: None ]
> [  memsize: 32 ]
> [  position_encoding: False ]
> [  time_features: True ]
> [ TorchAgent Arguments: ] 
> [  add_p1_after_newln: False ]
> [  embedding_projection: random ]
> [  embedding_type: random ]
> [  gpu: -1 ]
> [  gradient_clip: 0.1 ]
> [  history_size: -1 ]
> [  learningrate: 1 ]
> [  momentum: 0 ]
> [  multigpu: False ]
> [  no_cuda: False ]
> [  optimizer: sgd ]
> [  person_tokens: False ]
> [  rank_candidates: True ]
> [  truncate: -1 ]
> [  use_reply: label ]
> [ TorchRankerAgent: ] 
> [  candidates: inline ]
> [  eval_candidates: inline ]
> [  fixed_candidate_vecs: reuse ]
> [  fixed_candidates_path: None ]
> [ Dictionary Arguments: ] 
> [  bpe_debug: False ]
> [  dict_endtoken: __end__ ]
> [  dict_file: /tmp/babi_memnn.dict ]
> [  dict_initpath: None ]
> [  dict_language: english ]
> [  dict_lower: False ]
> [  dict_max_ngram_size: -1 ]
> [  dict_maxtokens: -1 ]
> [  dict_minfreq: 0 ]
> [  dict_nulltoken: __null__ ]
> [  dict_starttoken: __start__ ]
> [  dict_textfields: text,labels ]
> [  dict_tokenizer: re ]
> [  dict_unktoken: __unk__ ]
> Enter Your Message: John went to the hallway.\n Where is John?
> Traceback (most recent call last):
>   File "examples/interactive.py", line 20, in <module>
>     interactive(opt, print_parser=parser)
>   File "./ParlAI/parlai/scripts/interactive.py", line 66, in interactive
>     world.parley()
>   File "./ParlAI/parlai/core/worlds.py", line 250, in parley
>     agents[1].observe(validate(acts[0]))
>   File "./ParlAI/parlai/core/torch_agent.py", line 804, in observe
>     return self.vectorize(self.observation, truncate=self.truncate)
>   File "./ParlAI/parlai/agents/memnn/memnn.py", line 107, in vectorize
>     return super().vectorize(*args, **kwargs)
>   File "./ParlAI/parlai/core/torch_agent.py", line 580, in vectorize
>     self._set_label_cands_vec(obs, add_start, add_end, truncate)
>   File "./ParlAI/parlai/core/torch_agent.py", line 549, in _set_label_cands_vec
>     obs['label_candidates'] = list(obs['label_candidates'])
> TypeError: 'NoneType' object is not iterable

Everything has worked up to that point. 

**To Reproduce**

9914  git clone https://github.com/facebookresearch/ParlAI.git ~/ParlAI\n
 9915  cd ~/ParlAI; python setup.py develop\n
 9916  conda create --name parlai python=3.7
 9917  source activate parlai
 9918  python setup.py develop\n
 9919  python examples/display_data.py -t babi:task10k:1\n
 9924  which conda
 9925  export CMAKE_PREFIX_PATH=/Users/dalton/miniconda2/
 9926  conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing\n
 9927  cd ..
 9929  git clone --recursive https://github.com/pytorch/pytorch\n
 9932  cd pytorch\nMACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install\n
 9933  cd ..
 9938  cd ~/ParlAI
 9939  python examples/display_data.py -t babi:task10k:1\n
 9940  python examples/train_model.py -t babi:task10k:1 -mf /tmp/babi_memnn -bs 8 -nt 4 -eps 5 -m memnn\n
 9941  python examples/interactive.py -mf /tmp/babi_memnn\n
 9942  python examples/display_model.py -t babi:task10k:1 -mf /tmp/babi_memnn\n
 9943  python examples/interactive.py -mf /tmp/babi_memnn\n
 9944  ls /tmp
 9947  python examples/interactive.py -mf /tmp/babi_memnn\n

**A clear and concise description of what you expected to happen.**

I expected John to be in the hallway.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14
 - Shell: Zsh
 - Python 3.7.1

**Comment by stephenroller** [comment]
Fixed by #1280

**Comment by alexholdenmiller** [comment]
Fixed a small bug and added better error message.

Now you can train with, for example...
```
python examples/train_model.py -t babi:task10k:1 -bs 16 -nt 8 -veps 3 -vcut 0.95 -m memnn -mf /tmp/model
```

And then run...
```
python examples/interactive.py -mf /tmp/model -ecands vocab
...
Enter Your Message: john is in the bathroom.\n where is john?
[MemNN]: bathroom
```

**Comment by louismartin** [comment]
Should we update the [quick start guide](https://github.com/facebookresearch/ParlAI/blob/d80573384feb589f4246bba39e6c2ec85cefb97b/docs/source/tutorial_quick.rst) with the `python examples/interactive.py -mf /tmp/model -ecands vocab` command then @alexholdenmiller ?
