### ISSUE TITLE
MTurk change time allotted of HIT

### ISSUE THREAD

**Issue by nihiluis** [facebookresearch/ParlAI#1275]
Parlai sets the Time allotted of my HIT to 30minutes by default. I cant find an option to change that. Is it available somewhere? If not I think it could be an addition to the config.

**Comment by JackUrb** [comment]
Ah I should probably include this in the docs (am currently in the middle of rebuilding/enhancing certain features and am holding off on a doc refresh until they're done). In the meantime you can set this by including a `'assignment_duration_in_seconds'` parameter in your `task_config.py` file.

**Comment by nihiluis** [comment]
very cool, thank you!
