### ISSUE TITLE
How to create a task with longer dialog history?

### ISSUE THREAD

**Issue by ricsinaruto** [facebookresearch/ParlAI#1285]
I would like to get some help regarding how tasks work in parlai. I understand how to make a single turn task, where there is an input and target in each episode.

I read a lot of documentation, but I still can't figure out whether doing a multi-turn task is possible, and if it is then how to do it. As far as I understand the episode_done value in a batch signals whether the dialog finished. I tried to create a task, where the generating function yields input-output pairs, and only set the episode_done to True, at the end of a dialog. But if I inspect the task with the display_data.py script I still only see the previous utterance as input, instead of the whole dialog history.

So I don't know wether I did it correctly, and if I did, then how should I access the whole dialog history from a batch, to feed it into my model.

**Comment by ricsinaruto** [comment]
I'm just guessing here, but I found a history variable inside the TorchAgent class, is dialog history stored there?

**Comment by jaseweston** [comment]
Yes, of course doing a multi-turn task is possible, this is a dialogue
platform!
When you do display_data only the information from each turn will be
displayed one after the other. Each message sent to the agent would only
have the information for that turn. It is the responsibility of an agent to
remember any history.
See for example:

python examples/display_data -t personachat

for a multi-turn dataset

**Comment by ricsinaruto** [comment]
Okay so from a task point of view it's clear how to do it. The question is then whether multi-turn compatibility is integrated into TorchAgent, and if so how exactly can I access the dialog history?

I tried to print out the observations in each step, and I can see that the dialog history is concatenated with the \n symbol. The problem is that in the text_vec form, the \n gets transformed to the __unk__ token, which is weird behavior, because I can't split the tensor into separate utterances, because the __unk__ token might be used elsewhere in the text as well.

I can see two ways to resolve this. Either add the \n symbol to the vocab and then I have a special token according to which I can split my input tensor into utterances. Or maybe an even nicer way would be to overwrite the Batch namedtuple to support multiple utterance tensors instead of just concatenating them. It's weird that there is no support for this, am I missing something, is there a better way to get separate tensors for each utterance?

**Comment by emilydinan** [comment]
You can refer to the docs [here](http://parl.ai/static/docs/torch_agent.html?highlight=torchagent)

**Comment by ricsinaruto** [comment]
Cool, thank you very much. I should have found this split_lines argument by myself.
Closing the issue as this solves my problems I think.
