### ISSUE TITLE
should remote agent with -m seq2seq work?

### ISSUE THREAD

**Issue by jsedoc** [facebookresearch/ParlAI#1292]
From the documentation, it seems that I should be able to run  `python examples/remote.py -m seq2seq` however, this doesn't seem to work because when `agents[0].act()` is called self.observation is None.

This issue is both on my MacBook as well as the server. Note that `python examples/remote.py` and `python examples/remote.py -m seq2seq --remote-host` both work fine

Another point, is that the legacy seq2seq also has a similar issue.

$ python3 examples/remote.py -m seq2seq
[ Main ParlAI Arguments: ] 
[  datapath: /Users/jsedoc/research/ParlAI/data ]
[  datatype: train ]
[  download_path: /Users/jsedoc/research/ParlAI/downloads ]
[  hide_labels: False ]
[  image_mode: raw ]
[  numthreads: 1 ]
[  pytorch_teacher_dataset: None ]
[  pytorch_teacher_task: None ]
[  show_advanced_args: False ]
[  task: None ]
[ Batching Arguments: ] 
[  batchsize: 1 ]
[  include_labels: True ]
[ PytorchData Arguments: ] 
[  batch_length_range: 5 ]
[  batch_sort_cache: none ]
[  numworkers: 4 ]
[  pytorch_datafile: None ]
[  pytorch_preprocess: False ]
[  shuffle: False ]
[ ParlAI Model Arguments: ] 
[  dict_class: parlai.core.dict:DictionaryAgent ]
[  model: seq2seq ]
[  model_file: None ]
[ Remote Agent Args: ] 
[  port: 5555 ]
[  remote_address: localhost ]
[  remote_args: None ]
[  remote_cmd: None ]
[  remote_host: False ]
[ ParlAI Image Preprocessing Arguments: ] 
[  image_cropsize: 224 ]
[  image_size: 256 ]
[ Seq2Seq Arguments: ] 
[  attention: none ]
[  attention_length: 48 ]
[  attention_time: post ]
[  bidirectional: False ]
[  decoder: same ]
[  dropout: 0.1 ]
[  embeddingsize: 128 ]
[  hiddensize: 128 ]
[  init_model: None ]
[  input_dropout: 0.0 ]
[  lookuptable: unique ]
[  numlayers: 2 ]
[  numsoftmax: 1 ]
[  rnn_class: lstm ]
[ Torch Generator Agent: ] 
[  beam_block_ngram: 0 ]
[  beam_dot_log: False ]
[  beam_min_length: 1 ]
[  beam_min_n_best: 3 ]
[  beam_size: 1 ]
[  skip_generation: False ]
[ TorchAgent Arguments: ] 
[  add_p1_after_newln: False ]
[  embedding_projection: random ]
[  embedding_type: random ]
[  gpu: -1 ]
[  gradient_clip: 0.1 ]
[  history_size: -1 ]
[  learningrate: 1 ]
[  momentum: 0 ]
[  multigpu: False ]
[  no_cuda: False ]
[  optimizer: sgd ]
[  person_tokens: False ]
[  rank_candidates: False ]
[  truncate: -1 ]
[  use_reply: label ]
[ Dictionary Arguments: ] 
[  bpe_debug: False ]
[  dict_endtoken: __end__ ]
[  dict_file: None ]
[  dict_initpath: None ]
[  dict_language: english ]
[  dict_lower: False ]
[  dict_max_ngram_size: -1 ]
[  dict_maxtokens: -1 ]
[  dict_minfreq: 0 ]
[  dict_nulltoken: __null__ ]
[  dict_starttoken: __start__ ]
[  dict_textfields: text,labels ]
[  dict_tokenizer: re ]
[  dict_unktoken: __unk__ ]
python thread connected to tcp://localhost:5555
Traceback (most recent call last):
  File "examples/remote.py", line 70, in <module>
    main()
  File "examples/remote.py", line 65, in main
    world.parley()
  File "/Users/jsedoc/research/ParlAI/parlai/core/worlds.py", line 249, in parley
    acts[0] = agents[0].act()
  File "/Users/jsedoc/research/ParlAI/parlai/core/torch_agent.py", line 891, in act
    return self.batch_act([self.observation])[0]
  File "/Users/jsedoc/research/ParlAI/parlai/core/torch_agent.py", line 908, in batch_act
    is_training = any('labels' in obs for obs in observations)
  File "/Users/jsedoc/research/ParlAI/parlai/core/torch_agent.py", line 908, in <genexpr>
    is_training = any('labels' in obs for obs in observations)
TypeError: argument of type 'NoneType' is not iterable

**Comment by alexholdenmiller** [comment]
Thanks for flagging, @jsedoc!

**Comment by alexholdenmiller** [comment]
should work now!
