### ISSUE TITLE
Special token bug

### ISSUE THREAD

**Issue by NeuralNotworks** [facebookresearch/ParlAI#1324]
The following line will cause `labels` field in training data be split into multiple segments, if special token '|' exists.
https://github.com/facebookresearch/ParlAI/blob/d06eda2518ffed9551a39079743c1617a7434bbe/parlai/core/utils.py#L866

**Comment by alexholdenmiller** [comment]
Hi @NeuralNotworks, how are you using this function right now?

This is used intentionally for datasets where there are multiple labels that are delimited by "|" and we should be scrubbing any |'s from the data beforehand in those cases.

**Comment by NeuralNotworks** [comment]
Hi @alexholdenmiller , I simply replaced Twitter data with my own data.

In the following example, the `labels` field will be treated as two responses:
```
text:How are you feeling now?	labels:Not so good :|, how about you?	episode_done:True
```

So you suggest to replace "|" with "__PIPE__" as preprocessing?

**Comment by alexholdenmiller** [comment]
yeah that's an option or if you think they are all emojis then you could replace with a `/` to maintain a similar intent

**Comment by NeuralNotworks** [comment]
Right, thanks. Then it's not a bug, I'm closing this issue.
