### ISSUE TITLE
Issue with creating a my own task

### ISSUE THREAD

**Issue by bhedayat** [facebookresearch/ParlAI#1368]
Hello I created a new task using the FB Dialog teacher

Here is my `agents.py`
```
def _path(opt):
    # Build the data if it doesn't exist.
    build(opt)    
    # set up path to data (specific to each dataset)
    datatype = opt['datatype'].split(':')[0]
    dt = datatype
    return os.path.join(opt['datapath'], 'MyData', dt + '.txt')
class MyDataTeacher(FbDialogTeacher):
    def __init__(self, opt, shared=None):
        opt = copy.deepcopy(opt)
        # get datafile
        opt['datafile'] = _path(opt)
        super().__init__(opt, shared)
class DefaultTeacher(MyDataTeacher):
    pass
```
and my build.py
```
def build(opt):
    version = None
    dpath = os.path.join(opt['datapath'], 'MyData')
    build_data.mark_done(dpath, version)
```
I then make a directory under `~/ParlAI/data/MyData/`
where my train, valid, test.txt exist.
When I run
`python examples/display_data.py -t mydata -dt test`

It seems it is trying to look in this path for the data. As a result i had to put the data there for the command to work.
`~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/parlai-0.1.0-py3.6.egg/data/my_data`

My question is why is it not looking under `ParlAI/data/` instead

**Comment by stephenroller** [comment]
I don't know, but it looks to me like you ran `python setup.py install` instead of `python setup.py develop`?

**Comment by bhedayat** [comment]
Ah yes I believe that's the issue. Thank you for pointing that out.
