### ISSUE TITLE
Get top predictions for convai2 kvmemnn baseline

### ISSUE THREAD

**Issue by namanahuja** [facebookresearch/ParlAI#1378]
When I run /projects/convai2/baselines/kvmemnn/interactive.py,
and converse to get output like:

Enter Your Message: hey
[text_candidates: hey]
Enter Your Message: how are you?
doing great ! spent the weekend outside and swimming . i love both !
[text_candidates: doing great ! spent the weekend outside and swimming . i love both !]

I am exploring the possibility to fetch the top 5 responses generated by the model (possibly with a probability). How can I achieve this?

Thank you

**Comment by emilydinan** [comment]
Hi @namanahuja,  you'll have to edit the kvmemnn code to return the top 5 responses. Here is where we turn the top response:

https://github.com/facebookresearch/ParlAI/blob/85551f7b0e4da017ec72b317b1b22d7914c091da/projects/personachat/kvmemnn/kvmemnn.py#L615

you'll have to edit this to return something like `'\n'.join([ztxt[ind[i].item()] for i in range(5)])`
