### ISSUE TITLE
train model using multiple gpu

### ISSUE THREAD

**Issue by mohamad-mehdi-jafari** [facebookresearch/ParlAI#1394]
I have machine with two GTX 1080 (sli connected) on it, it works fine during the training but when validation phase start I face the memory error (RuntimeError: CUDA out of memory. Tried to allocate 143.12 MiB (GPU 0; 7.93 GiB total capacity; 6.78 GiB already allocated; 117.31 MiB free; 365.72 MiB cached). have can I use my second gpu for validation? 

I use the profilememory_train.sh

**Comment by stephenroller** [comment]
I'm closing this, but please feel free to repoen if you have more questions.
