### ISSUE TITLE
outdated mturk args in README

### ISSUE THREAD

**Issue by erohmensing** [facebookresearch/ParlAI#1405]
> Run `python run.py -nh <num_hits> -na <num_assignments> -r <reward> [--sandbox]/[--live]`, with `<num_hits>`, `<num_assignments>` and `<reward>` set appropriately. Use `--sandbox` to run the task in MTurk sandbox mode before pushing it live.

Following this direction in the README leads to `run.py: error: unrecognized arguments` for both `-nh` and `-na` and lists the following viable parameters, it seems the parameters have been updated but the README not updated. Also referenced in #410

```usage: run.py [-h] [-dp DATAPATH] [--mturk-log-path MTURK_LOG_PATH] [-t TASK]
              [-nc NUM_CONVERSATIONS] [--unique]
              [--max-hits-per-worker MAX_HITS_PER_WORKER]
              [--unique-qual-name UNIQUE_QUAL_NAME] [-r REWARD] [--sandbox]
              [--live] [--debug] [--verbose] [--hard-block]
              [--log-level LOG_LEVEL]
              [--disconnect-qualification DISCONNECT_QUALIFICATION]
              [--block-qualification BLOCK_QUALIFICATION] [--count-complete]
              [--allowed-conversations ALLOWED_CONVERSATIONS]
              [--max-connections MAX_CONNECTIONS]
              [--min-messages MIN_MESSAGES] [--local] [--hobby]
              [--max-time MAX_TIME] [--max-time-qual MAX_TIME_QUAL]
              [--heroku-team HEROKU_TEAM] [-lp LENGTH_PENALTY]
              [-hsz HISTORY_SIZE]
              [--label-candidates-file LABEL_CANDIDATES_FILE]
```

**Comment by erohmensing** [comment]
For what it's worth, something that was even more confusing is that 
> Please see the MTurk tutorial

links to docs from 2017, while

> To add your own task see the tutorial.
> Please see the Facebook Messenger tutorial

lead to docs from 2018. Don't know if that should be a new issue as it just seems the README is in general out of date and should be linked to current docs (basically feels like i'm being led to 3 separate tutorials at the moment)

**Comment by emilydinan** [comment]
Thanks @erohmensing -- just put out a PR that links to the correct docs.
