### ISSUE TITLE
error in running seq2seq_withprofile_interactive.py

### ISSUE THREAD

**Issue by mohamad-mehdi-jafari** [facebookresearch/ParlAI#1430]

**Comment by mohamad-mehdi-jafari** [comment]
I encountered the following error after download and store pre_trained models

python projects/personachat/scripts/seq2seq_withprofile_interactive.py 
[ optional arguments: ] 
[  display_examples: False ]
[ Main ParlAI Arguments: ] 
[  datapath: /home/mehdi/git/parlai/data ]
[  datatype: train ]
[  download_path: /home/mehdi/git/parlai/downloads ]
[  hide_labels: False ]
[  image_mode: raw ]
[  numthreads: 1 ]
[  show_advanced_args: False ]
[  task: parlai.agents.local_human.local_human:LocalHumanAgent ]
[ Batching Arguments: ] 
[  batchsize: 1 ]
[  include_labels: True ]
[ PytorchData Arguments: ] 
[  batch_length_range: 5 ]
[  batch_sort_cache_type: pop ]
[  batch_sort_field: text ]
[  numworkers: 4 ]
[  pytorch_context_length: -1 ]
[  pytorch_datapath: None ]
[  pytorch_include_labels: True ]
[  pytorch_preprocess: False ]
[  pytorch_teacher_batch_sort: False ]
[  pytorch_teacher_dataset: None ]
[  pytorch_teacher_task: None ]
[  shuffle: False ]
[ ParlAI Model Arguments: ] 
[  dict_class: None ]
[  model: projects.personachat.persona_seq2seq:PersonachatSeqseqAgentBasic ]
[  model_file: /home/mehdi/git/parlai/data/models/personachat/seq2seq_personachat/seq2seq_no_dropout0.2_lstm_1024_1e-3 ]
[ ParlAI Image Preprocessing Arguments: ] 
[  image_cropsize: 224 ]
[  image_size: 256 ]
[ Local Human Arguments: ] 
[  local_human_candidates_file: None ]
[  single_turn: False ]
[ Dictionary Arguments: ] 
[  bpe_debug: False ]
[  dict_endtoken: __end__ ]
[  dict_file: /home/mehdi/git/parlai/data/models/personachat/profile_memory/fulldict.dict ]
[  dict_initpath: None ]
[  dict_language: english ]
[  dict_lower: False ]
[  dict_max_ngram_size: -1 ]
[  dict_maxtokens: -1 ]
[  dict_minfreq: 0 ]
[  dict_nulltoken: __null__ ]
[  dict_starttoken: __start__ ]
[  dict_textfields: text,labels ]
[  dict_tokenizer: re ]
[  dict_unktoken: __unk__ ]
[ Seq2Seq Arguments: ] 
[  attention: None ]
[  decoder: same ]
[  dropout: 0.1 ]
[  embeddingsize: 300 ]
[  encoder: lstm ]
[  gpu: -1 ]
[  hiddensize: 1024 ]
[  interactive_mode: True ]
[  learningrate: 0.5 ]
[  no_cuda: False ]
[  numlayers: 2 ]
[  optimizer: adam ]
[  personachat_interact: False ]
[  personachat_sharelt: False ]
[  rank_candidates: False ]
[  truncate: 100 ]
[ PersonachatSeqseqAgentBasic Arguments: ] 
[  personachat_useprevdialog: False ]
[ no model with opt yet at: /home/mehdi/git/parlai/data/models/personachat/seq2seq_personachat/seq2seq_no_dropout0.2_lstm_1024_1e-3(.opt) ]
Dictionary: loading dictionary from /home/mehdi/git/parlai/data/models/personachat/profile_memory/fulldict.dict
[ num words =  11 ]
Loading existing model params from /home/mehdi/git/parlai/data/models/personachat/seq2seq_personachat/seq2seq_no_dropout0.2_lstm_1024_1e-3
Traceback (most recent call last):
  File "projects/personachat/scripts/seq2seq_withprofile_interactive.py", line 35, in <module>
    interactive(opt)
  File "/home/mehdi/git/parlai/parlai/scripts/interactive.py", line 54, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "/home/mehdi/git/parlai/parlai/core/agents.py", line 478, in create_agent
    model = model_class(opt)
  File "/home/mehdi/git/parlai/projects/personachat/persona_seq2seq.py", line 985, in __init__
    super().__init__(opt, shared)
  File "/home/mehdi/git/parlai/projects/personachat/persona_seq2seq.py", line 182, in __init__
    new_opt, states = self.load(opt['model_file'])
  File "/home/mehdi/git/parlai/projects/personachat/persona_seq2seq.py", line 941, in load
    model = torch.load(read, map_location=lambda cpu, _: cpu)
  File "/home/mehdi/anaconda3/envs/convAI/lib/python3.7/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/mehdi/anaconda3/envs/convAI/lib/python3.7/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '='.

**Comment by stephenroller** [comment]
Thanks, it looks like something got corrupted in your download. `rm -rf` the `data/models/personachat` folder and try again.

You might see another error about copying embeddings didn't work. If that's the case, please post that here.

**Comment by alexholdenmiller** [comment]
I didn't get that error but I fixed a few other ones

**Comment by stephenroller** [comment]
I think this is pseudo-resolved; we're not officially supporting  seq2seq_withprofile anymore (#1581). It's older code that would require significant effort to update.

To mitigate issues like this in the future, we will have more tests for official model releases.
