### ISSUE TITLE
newline not rendering in mturk task

### ISSUE THREAD

**Issue by erohmensing** [facebookresearch/ParlAI#1435]
I've created an mturk task based off of the `qa_data_collection` task. Similar to that task, my rating collector posts 
```
ad['text'] = (self.context +
              '\n\nPlease provide a coherency rating ' +
              'for Conversation Pair 1.')
```
as a first post to collect the first rating, and then acts again to ask them for their second rating (my context also includes newlines as in `qa_data_collection`). 

My problem is that somewhere along the line, my newline `\n` characters stopped rendering, for both my task (`rasa_eval_mturk_new`) and for `qa_data_collector`, which I can't figure out because I haven't changed any of the code that wasn't task code. Newlines still render when I run `model_evaluator`, so I think it has something to do with node/webpack, which seems to be called for the former two tasks but not the latter. 

My code should be updated in my fork branch `erohmensing:rasa_eval` if that's helpful.

<img width="791" alt="screen shot 2019-02-08 at 13 43 22" src="https://user-images.githubusercontent.com/22333512/52479027-8a387780-2ba7-11e9-91f0-c6975883c4f9.png">

**Comment by JackUrb** [comment]
Hi @erohmensing - what is the `'frontend_version'` set to it your `task_config.py`? That should help me debug!

**Comment by JackUrb** [comment]
Ah actually you must be on the new frontend if webpack is triggering. The new frontend is more reliable and generally easier to work with, but there are a few bugs I haven't discovered yet, this being one of them! The old method of implementing new lines involved converting to `<br />` objects and rendering as raw html, which is actually pretty dangerous. I just need to add a css class that will cause the new lines to be rendered properly. Thanks for flagging! I'll have the fix up soon

**Comment by erohmensing** [comment]
`task_config['frontend_version'] = 1`

Can I switch to the old frontend version and check out how it looks there in the meantime? Would I do that by not declaring the `frontend_version` (it seems the default as in `model_evaluator` is not `1`)

Thanks for getting back to me so fast! :)

**Comment by erohmensing** [comment]
Taking out the declaration did work for now, by the way

**Comment by JackUrb** [comment]
Yeah you can use the old one if you want to test for now, but we are deprecating it in the near future as I am no longer supporting it and thus it hasn't received the same reliability upgrades as are present in the newer iteration.

**Comment by erohmensing** [comment]
Cool, sounds good. When you make the PR for fixing that bug would you please you tag me/this issue so I can stay updated on the progress?

**Comment by JackUrb** [comment]
@erohmensing - the bug fix has landed. Thanks a lot for flagging this!
