### ISSUE TITLE
Running model with data parallel or multigpu

### ISSUE THREAD

**Issue by bhedayat** [facebookresearch/ParlAI#1439]
Hello so after i cloned the ParlAI repo and did python setup.py develop I run

python -m parlai.scripts.train_model -m transformer/generator -t wizard_of_wikipedia:WizardDialogKnowledgeTeacher:random_split -mf '/tmp/transformer_response' -bs 32 --data-parallel True --label-type response

but it says train_model.py: error: unrecognized arguments: --data-parallel True
Is there something I am missing?

**Comment by stephenroller** [comment]
Yes, generators don't use DataParallel. Instead, they use DistributedDataParallel, which let's you run across multiple machines, in case you happen to have many GPUs.

You can try:

`python -m parlai.scripts.multiprocessing_train -m transformer/generator -t wizard_of_wikipedia:WizardDialogKnowledgeTeacher:random_split -mf '/tmp/transformer_response' -bs 32 --label-type response`

This will spin up one process per GPU you have.

Ranker models currently have DataParallel on a case by case basis, for more nuanced reasons.

Closing, but feel free to reopen if you have more questions.
