### ISSUE TITLE
how to switch to a new MTurk/AWS combo?

### ISSUE THREAD

**Issue by erohmensing** [facebookresearch/ParlAI#1442]
I had my Mturk task running smoothly in the sandbox, but now needed to switch over to a new MTurk Requester/AWS account pair. I deleted my old IAM user, and the new Requester is linked with the new AWS account, and the old Requester account is unpaired with any AWS account. I've even tried to uninstall boto3 and delete my .aws in order to be able to replicate the whole process, but after creating a new IAM user within the new MTurk Requester/AWS link, I still get this error when trying to launch in sandbox:
```
Traceback (most recent call last):
  File "run.py", line 136, in <module>
    main()
  File "run.py", line 74, in main
    mturk_manager.create_hits()
  File "/Users/erohmensing/ParlAI/parlai/mturk/core/mturk_manager.py", line 1585, in create_hits
    qualifications=qualifications,
  File "/Users/erohmensing/ParlAI/parlai/mturk/core/mturk_manager.py", line 1534, in create_additional_hits
    auto_approve_delay=self.auto_approve_delay,
  File "/Users/erohmensing/ParlAI/parlai/mturk/core/mturk_utils.py", line 320, in create_hit_type
    QualificationRequirements=locale_requirements,
  File "/Users/erohmensing/anaconda3/envs/rasa/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/erohmensing/anaconda3/envs/rasa/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.RequestError: An error occurred (RequestError) when calling the CreateHITType operation: Please log in to the appropriate MTurk UI and complete registration. (1549905607528 s)
```

I'm thinking that it might still be trying to launch through my other Requester account, but then I would expect the unlinked error, so I'm not exactly sure what's going on.

**Comment by JackUrb** [comment]
Hi @erohmensing - I've only encountered this specific error using an MTurk requester account that hadn't fully set up location/payment details. The only details that tie ParlAI to an account are saved in the `~/.aws/credentials` file, so if you've set up an IAM user on the new AWS account and used those details, it's likely successfully connecting to the new MTurk account but seeing it isn't fully set up yet. It's also important to note that you'll have to create a new Sandbox Requester account for the new MTurk account if you're trying to run on sandbox on the new account

**Comment by erohmensing** [comment]
I've checked and I do have Sandbox set up 
> Your Sandbox Requester account and AWS Root User are now linked.

And the IAM user is also accessible through that page's `Get Your AWS Access Keys` link. The MTurk Requester account is definitely set up with location/payment details as it's the company account that we've run hits from before (just not through ParlAI). Any other ideas?

**Comment by JackUrb** [comment]
Unfortunately I have no leads as this is an AWS configuration and botocore error, and the only thing I could find with the specific [error text](https://stackoverflow.com/questions/52791332/requesterror-when-calling-the-createhit-operation) online doesn't provide any leads other than contacting AWS support. Just a shot in the dark but does the IAM user definitely have MTurk access permissions?

**Comment by erohmensing** [comment]
Yeah, I gave it programmatic access and administrator access. I had the same bad luck with looking for the botocore error. Thanks though!
