### ISSUE TITLE
specify worker qualifications

### ISSUE THREAD

**Issue by erohmensing** [facebookresearch/ParlAI#1448]
First of all, thank you guys so much for your quick response and help over the past week or two!

Is there a way to specify worker qualifications such as in the picture below? 

<img width="862" alt="screen shot 2019-02-12 at 16 25 13" src="https://user-images.githubusercontent.com/22333512/52646394-f5a18280-2ee2-11e9-85eb-d50b633dffbe.png">

I assume it will go into my `check_workers_eligibity` function but can't seem to find any good examples or description on it.

**Comment by JackUrb** [comment]
Hi again @erohmensing - this can be handled in your create_hits step by leveraging the qualifications flow (as seen in the `qualification_flow_example` task). The qualification id for the acceptance percentage is `000000000000000000L0` and you would set the comparator to greater and the value to the percentage you desire.

**Comment by erohmensing** [comment]
Thank you!
