### ISSUE TITLE
build_dict doesn't work in train_model without a custom dictionary class

### ISSUE THREAD

**Issue by Henry-E** [facebookresearch/ParlAI#152]
Kind of an odd finicky thing to point out. There needs to be dictionary agent arguments parsed in order for a [dictionary to be built](https://github.com/facebookresearch/ParlAI/blob/master/examples/train_model.py#L86 ) in train_model.py. And this only happens incidentally with [drqa agent](https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/drqa/drqa.py#L107) when the [agent's parameters](https://github.com/facebookresearch/ParlAI/blob/master/parlai/core/params.py#L125) are added to the model. If an agent doesn't have a custom dictionary class or call the dictionary agent argument parser in its add_cmdline_args function then there are no default dictionary arguments available (and this causes it to crash).

**Comment by alexholdenmiller** [comment]
Thanks for commenting Henry! We were looking at this, and basically yes in order for the dictionary to be built the model has to call the add_cmdline_args function of its desired dictionary in its own add_cmdline_args.

Now we demonstrate this using the dictionary_class() method of our drqa and seq2seq models. The idea here is that the model will have to decide for itself whether or not it is going to be using a dictionary, and if so it is responsible for adding the command-line flags for it.

If you have any suggestions on how to make this more friendly, we are happy for them! We will also be working on adding a tutorial that addresses the specific requirements and catalogs them better so it's less of a "gotcha".

**Comment by Henry-E** [comment]
Yeh, I noticed the issue but didn't have any particular ideas on how it could be better implemented. Making it part of creating a model seems like a pretty intuitive way of going about it.
