### ISSUE TITLE
Failed building wheel for pytorch

### ISSUE THREAD

**Issue by anati89** [facebookresearch/ParlAI#154]
Could you please help ?
I'm using PyCharm and i tried to install pytorch, but i got below error:

Install packages failed: Error occurred when installing package pytorch. 

> The following command was executed:
> 
> packaging_tool.py install --build-dir C:\Users\PC\AppData\Local\Temp\pycharm-packaging3873295594079902182.tmp pytorch
> 
> The error output of the command:
> 
>   Failed building wheel for pytorch
> Command "C:\Users\PC\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\PC\\AppData\\Local\\Temp\\pycharm-packaging3873295594079902182.tmp\\pytorch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\PC\AppData\Local\Temp\pip-_plphgbs-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\PC\AppData\Local\Temp\pycharm-packaging3873295594079902182.tmp\pytorch\
> 
> Collecting pytorch
>   Using cached pytorch-0.1.2.tar.gz
> Building wheels for collected packages: pytorch
>   Running setup.py bdist_wheel for pytorch: started
>   Running setup.py bdist_wheel for pytorch: finished with status 'error'
>   Complete output from command C:\Users\PC\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\PC\\AppData\\Local\\Temp\\pycharm-packaging3873295594079902182.tmp\\pytorch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\PC\AppData\Local\Temp\tmpvlzpjkgvpip-wheel- --python-tag cp36:
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "C:\Users\PC\AppData\Local\Temp\pycharm-packaging3873295594079902182.tmp\pytorch\setup.py", line 17, in <module>
>       raise Exception(message)
>   Exception: You should install pytorch from http://pytorch.org
>   
>   ----------------------------------------
>   Running setup.py clean for pytorch
> Failed to build pytorch
> Installing collected packages: pytorch
>   Running setup.py install for pytorch: started
>     Running setup.py install for pytorch: finished with status 'error'
>     Complete output from command C:\Users\PC\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\PC\\AppData\\Local\\Temp\\pycharm-packaging3873295594079902182.tmp\\pytorch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\PC\AppData\Local\Temp\pip-_plphgbs-record\install-record.txt --single-version-externally-managed --compile:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\PC\AppData\Local\Temp\pycharm-packaging3873295594079902182.tmp\pytorch\setup.py", line 13, in <module>
>         raise Exception(message)
>     Exception: You should install pytorch from http://pytorch.org
>     

    ----------------------------------------

**Comment by alexholdenmiller** [comment]
Sorry but neither pytorch or us officially supports windows :(

**Comment by anati89** [comment]
Thank you alex for your clarification.
