### ISSUE TITLE
PackageNotFoundError: Package missing in current win-64 channels:

### ISSUE THREAD

**Issue by anati89** [facebookresearch/ParlAI#155]
> conda install pytorch torchvision cuda80 -c soumith  
> Fetching package metadata ...............
> 
> PackageNotFoundError: Package missing in current win-64 channels:
>   - pytorch

I tried to add channel but i got:

> conda install pytorch torchvision cuda80 -c soumith
> Fetching package metadata ...............
> 
> PackageNotFoundError: Package missing in current win-64 channels:
>   - pytorch

Any suggestion ?

**Comment by alexholdenmiller** [comment]
Hi @anati89, I'm sorry but I don't think pytorch officially supports windows (and neither do we for ParlAI), but you can try looking on the pytorch forums or posting on the pytorch issues page on github for more help with it
