### ISSUE TITLE
What makes a good conversation? How controllable attributes affect human judgments

### ISSUE THREAD

**Issue by JohannesTK** [facebookresearch/ParlAI#1557]
Congratulations on NAACL and a great paper!

"All of our code, pretrained models, and full chatlogs, will be released open-source" - do you have a timeframe on that? Would love to try it out.

Thanks!

**Comment by stephenroller** [comment]
cc @abisee

**Comment by abisee** [comment]
Hi @JohannesTK, thanks for your interest!

The NAACL camera-ready deadline is April 1, so we'll have finished our revised version of the paper by then. We hope to release the code, pretrained models and chatlogs shortly after that, though it usually takes a little while to clean everything up to the level that people can use it, so it might take 1-2 weeks after the camera-ready deadline.

**Comment by JohannesTK** [comment]
Thanks for the update, @abisee.

Will be looking forward to it and hope you have a successful presentation at NAACL!

**Comment by g-karthik** [comment]
@abisee weighted decoding and conditional training are somewhat model-agnostic in that they should work with any encoder-decoder model, so would you be integrating the two approaches at the framework-level prior to the release? I noticed that you used a 2-layer LSTM with attention in your paper, but it would be ideal if your release works with any encoder-decoder model with minimal effort. Thanks!

Good paper, btw!

**Comment by abisee** [comment]
> The NAACL camera-ready deadline is April 1, so we'll have finished our revised version of the paper by then. We hope to release the code, pretrained models and chatlogs shortly after that, though it usually takes a little while to clean everything up to the level that people can use it, so it might take 1-2 weeks after the camera-ready deadline.

Update: Apologies, looks like my previous estimate for when this would be done was a bit over-optimistic. But I am now working on it and hope to have it done soon. Thanks for your patience!
