### ISSUE TITLE
[Wizard of Wikipedia] Where is get_dialog_history() defined?

### ISSUE THREAD

**Issue by g-karthik** [facebookresearch/ParlAI#1564]
https://github.com/facebookresearch/ParlAI/blob/a43f2880719c5a048fdf3d0aa5d5b25eeb9a1a41/projects/wizard_of_wikipedia/generator/agents.py#L78

@stephenroller I'm guessing this got missed in TorchAgent. Could you please fix it?

**Comment by stephenroller** [comment]
Hi g-karthik, sorry I must've broken it this past week. I'm unfortunately on vacation right now, but I'll fix it when I get back
