### ISSUE TITLE
I want to train memory network on SimpleQuestions

### ISSUE THREAD

**Issue by zhangxiaoyidog** [facebookresearch/ParlAI#1576]
excuse me,I want to train memory network on SimpleQuestions, In other words I want the implementation of the article(Large-scale Simple Question Answering with Memory Networks), i saw it is in the task_list.py, which commands should I use to train and Tests.

**Comment by stephenroller** [comment]
The getting started and examples on https://parl.ai/ and https://parl.ai/docs/tutorial_quick.html should help you.

Closing, but please feel free to reopen if you have more questions.
