### ISSUE TITLE
[MTurk] Shaky Window for QA Data Collection -Style Task

### ISSUE THREAD

**Issue by ethanjperez** [facebookresearch/ParlAI#1593]
I'm using ParlAI MTurk to evaluate static, model-produced text, by building off the [QA Data Collection Demo](https://github.com/facebookresearch/ParlAI/tree/master/parlai/mturk/tasks/qa_data_collection). Overall, it works very smoothly, and the Turkers love the UI. 4 of 233 Turkers did report that the screen was shaky during the task. Do you know what the issue may be? Has anyone run into this problem before?

My specific set up has each worker answer ~20 questions using the "respond_with_form" ParlAI ad with "choices" (in my case, "A", "B", "C", and "D"), followed by a free-form text box for feedback on the task, after which the task concludes. It's possible my added code is causing the issue, though I have not altered the GUI-related code, so I'm not sure what it would be.

Here is the exact feedback:
- "My screen was shaky after answering the first question and didn't stop until I answered this [final, free-form text feedback] question. I'm using Chrome, it was super annoying, and figuring out a way to make that stop would be great."
- "I'm not sure why but the window shakes when full screened. This occurs on both monitors and is distracting."
- "The HIT makes the screen slightly 'shaky' for some reason."
- "The words are all shaky."

Here is basically how I'm constructing and serving the ParlAI ad in my `worlds.py` file:
```py
ad = {'episode_done': False}
ad['id'] = 'New Question'
ad['text'] = context_to_evaluate
ad["task_data"] = {"respond_with_form": [{
    "type": "choices",
    "question": "Which option is most likely correct?",
    "choices": ["A", "B", "C", "D"]
}]}
self.mturk_agent.observe(validate(ad))
answer = self.mturk_agent.act()
```

My [ParlAI fork](https://github.com/ethanjperez/ParlAI/tree/master/parlai/mturk/tasks/context_evaluator) has the full code.

**Comment by JackUrb** [comment]
Hi @ethanjperez - it's possible that the form input component has a bug in it (also maybe related to fullscreen?), considering it lacks a `componentDidUpdate` method which is responsible for managing height changes in the other `Response` components. Let me check it out and try to reproduce.
