### ISSUE TITLE
Virtualenv being created in the wrong directory?

### ISSUE THREAD

**Issue by seme0021** [facebookresearch/ParlAI#161]
Hey - 

I started getting a `FileNotFoundError: [Errno 2] No such file or directory: ` errors, because the setup_aws script was trying to delete the `parent_dir+"/venv` directory [here](https://github.com/facebookresearch/ParlAI/blob/master/parlai/mturk/core/setup_aws.py#L611).

However, looks like the venv directory is actually being created in the mturk/task/<project> directory, because that's where the `run.py` script is being execute from (at least by me). 

I can submit a PR to have the venv get created in the `parent_dir` if that's what you intended.

**Comment by yf225** [comment]
@seme0021 Thanks for reporting! We are working on the issue now.

**Comment by yf225** [comment]
#162

**Comment by yf225** [comment]
@seme0021 We just merged the pull request and the issue should be fixed. Thanks!
