### ISSUE TITLE
Opinions on training with an extremely small dataset

### ISSUE THREAD

**Issue by JohannesTK** [facebookresearch/ParlAI#1624]
Do you have any opinions/recommendations for training a model with an extremely small conversational dataset of 10K lines?

Specifically:

1. What might be the best dataset/zoo model to do transfer learning from?
2. What might be the best model considered the small dataset and the need for a dialog history? I.e. transformer, memnn, etc.

**Comment by stephenroller** [comment]
It really depends on the dataset and its characteristics. Something like BERT or GPT is really good for use with pretraining. You can also try twitter.

As far as models, I recommend an LSTM on the generative side if your'e staying with small data. On the retrieval side, I'd recommend memnn or starspace probably. With pretraining you can start to use the transformers.

Closing the issue, but you can keep asking more questions.

**Comment by JohannesTK** [comment]
Thanks for the quick reply, Stephen! Will run the experiments and get back with the results.
