### ISSUE TITLE
Wizard Of Wikipedia: Wrong beam size for train_end2end.py?

### ISSUE THREAD

**Issue by JohannesTK** [facebookresearch/ParlAI#1645]
In wizard_of_wikipedia/generator/train_end2end.py the beam size is set to 1: https://github.com/facebookresearch/ParlAI/blob/a43f2880719c5a048fdf3d0aa5d5b25eeb9a1a41/projects/wizard_of_wikipedia/generator/train_end2end.py#L37

But in the paper, under 4.2 GENERATIVE TRANSFORMER MEMORY NETWORK it is stated: "We employ a beam search of 5 to select our best response."

**Comment by stephenroller** [comment]
Yes, this is a recreation for the public release. It isn’t exactly the same as the paper but it should be close.

**Comment by JohannesTK** [comment]
Got it, thanks.
