### ISSUE TITLE
drqa no cuda

### ISSUE THREAD

**Issue by sankar-mukherjee** [facebookresearch/ParlAI#1647]
when i try to run 
python examples/interactive.py -m drqa -mf "models:drqa/squad/model" --no-cuda

it printout the help instead of running it on cpu. but with gpu it works. I just dont have access to gpu right now, so i was wondernig if anyone help me with this?

**Comment by JohannesTK** [comment]
The argument needs a boolean value.

`python examples/interactive.py -m drqa -mf "models:drqa/squad/model" --no-cuda=True`
