### ISSUE TITLE
Framework support for hyperparameter optimization

### ISSUE THREAD

**Issue by g-karthik** [facebookresearch/ParlAI#1648]
I want to compute a good set of hyper-parameters for the EndToEndAgent listed here: projects/wizard_of_wikipedia/generator/train_end2end.py

My thoughts are to write a similar script that calls TrainLoop() several times, with different sets of values for the parameters I want to optimize, and uses the v_report and t_report returned by train() to figure out which values for the hyper-parameters work best. I just wanted to check if y'all already have something set up to perform hyper-parameter optimization of ParlAI models and if you could release it.

Thanks!

**Comment by stephenroller** [comment]
We have grid search internally, but it's dependent on our infra so we probably won't open source it in the foreseeable future.

[Sklearn's ParameterGrid](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.ParameterGrid.html#sklearn.model_selection.ParameterGrid) can be used to generate these searches easily. Running them will depend on your own computing environment. If you wanted to implemented a more sophisticated hyperparameter search method, we'd be very interested in integrating your efforts.

Just remember that `v_report` should be used for all hyperparameter optimization, and `t_report` should only be considered at the very final single comparison.

**Comment by g-karthik** [comment]
So I tried creating N `TrainLoop()` instances corresponding to the jobs I want to trigger (put them in a list called `loops`), and I did:

```
with Pool(len(loops)) as p:
    p.map(run_train, loops)
```

where `run_train(x)` is a function that does `x.train()` but after assigning a GPU to this CPU process by setting `CUDA_VISIBLE_DEVICES` to the right GPU id.

But what happens is the following:

```
    p.map(run_train, loops)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects
```

Do you have any idea why this would happen?

**Comment by g-karthik** [comment]
Thanks @stephenroller! @klshuster, let me know if you need me to create a separate issue for this!

**Comment by stephenroller** [comment]
Perhaps, but I doubt not.

It sounds like you're passing around some sort of state that shouldn't be passed around. I would have as your args that you pass into pmap be exactly the opts and nothing else. The return value of the function should be the v_report and nothing else.

Don't, for example, pass around a TrainLoop object. That wouldn't work.

If this doesn't help, you'll need to post some code.

**Comment by g-karthik** [comment]
Yeah, I just moved the `TrainLoop()` instantiation inside `run_train()` instead of performing it outside, and it works! But why wouldn't creating N `TrainLoop()` instances and mapping them work?

**Comment by stephenroller** [comment]
Because only pickleable objects can be sent using multiprocessing. Somewhere deep in TrainLoop has a lock, which is nonpickleable.

**Comment by g-karthik** [comment]
@stephenroller yeah I figured based on the stack trace I pasted above, but I wanted to know what object deep inside TrainLoop() has a lock.
