### ISSUE TITLE
BERT with Transformer

### ISSUE THREAD

**Issue by KasparPeterson** [facebookresearch/ParlAI#1660]
Hey ParlAI community!

There are examples on how to use BERT with rankers but it is still bit unclear how would it be possible to use BERT with Transformer Generator.

Would it be possible? How could it be done?

**Comment by stephenroller** [comment]
Open research question :)

**Comment by JohannesTK** [comment]
What about using BERT for word embeddings? https://github.com/pytorch/text/issues/419#issuecomment-442172846
