### ISSUE TITLE
History not working properly

### ISSUE THREAD

**Issue by JohannesTK** [facebookresearch/ParlAI#1685]
**Bug description**
While decoding interactively, the model quickly goes in a loop and starts to output gibberish that is based on the previous utterances.

**Reproduction steps**
Run:

`python -m parlai.scripts.interactive -mf models:convai2/seq2seq/convai2_self_seq2seq_model -m legacy:seq2seq:0`

**Logs**
Example conversation:

```
Enter Your Message: hello
[Seq2Seq]: do you have any hobbies ?
Enter Your Message: yes, i like to do yoga
[Seq2Seq]: yoga is fun , i love yoga
Enter Your Message: what about you ?
[Seq2Seq]: yoga is fun , yoga yoga is my passion
Enter Your Message: what do you do ?
[Seq2Seq]: yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga ,
Enter Your Message: are you broken ?
[Seq2Seq]: yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga , yoga ,
```

**Additional information**

With our own dataset, we are also seeing that the previous utterances skew the output. 

With no history:

```
Enter Your Message: who are you ?
[TorchAgent]: i am steve .
```

With 1 utterance before:

```
Enter Your Message: hello
[TorchAgent]: hello .
Enter Your Message: who are you ?
[TorchAgent]: i ' ll say you go first
```

**Expected behavior**

We'd expect the model to output:

```
Enter Your Message: hello
[TorchAgent]: hello .
Enter Your Message: who are you ?
[TorchAgent]: i am steve .
```

**Comment by stephenroller** [comment]
This isn’t a bug per say, but rather a known issue with seq2seq models. Beam search has support for ngram blocking, which can alleviate this issue.

**Comment by stephenroller** [comment]
For more information, here's a very recent paper that might be of interest: https://arxiv.org/abs/1904.09751

**Comment by JohannesTK** [comment]
Thank you for the interesting paper. Seems like beam search isn't the best method of decoding. Do you have any plans for implementing the nucleus sampling?

Also tried out ngram blocking. Unfortunately, that didn't help as it went into a loop even faster.

About that specific example:

```
Enter Your Message: hello
[TorchAgent]: hello .
Enter Your Message: who are you ?
[TorchAgent]: i ' ll say you go first
```

Is it normal that it doesn't answer properly its name when there is something in the history? What would be the solution here? To have a lot of training examples with context and then asking: "who you are?". This seems quite unfeasible because of ∞ amount of possibilities. Or empty the history after every n turns? Which also seems unfeasible because it's hard to predict when to do so.

**Comment by stephenroller** [comment]
https://github.com/facebookresearch/ParlAI/blob/6f13b999ed221b19604283175360af9dc5063eed/parlai/core/torch_agent.py#L456 sets the maximum context size in turns.

Open research problem. It was part of the reason for the development of personachat. I’ve seen some interesting results from nucleus sampling so we’ll probably implement it soon.

**Comment by JohannesTK** [comment]
Got it. Thanks for sharing your knowledge.
