### ISSUE TITLE
ascii decoding issue of Wizard of Wikipedia

### ISSUE THREAD

**Issue by Ericzh2017** [facebookresearch/ParlAI#1702]
I try to eval wizard generator as recommended in https://parl.ai/projects/wizard_of_wikipedia/.
It seems to be a decoding error, is any dependent package missing?

root@1359aa73a18c:/home/cike/ParlAI# python examples/eval_model.py -bs 64 -t wizard_of_wikipedia:generator:topic_split -mf models:wizard_of_wikipedia/end2end_generator/model --datapath=data
/home/cike/ParlAI/parlai/agents/transformer/transformer.py:18: UserWarning: Public release transformer models are currently in beta. The name of command line options may change or disappear before a stable release. We welcome your feedback. Please file feedback as issues at https://github.com/facebookresearch/ParlAI/issues/new
  "Public release transformer models are currently in beta. The name of "
[ warning: overriding opt['task'] to wizard_of_wikipedia:generator:topic_split (previously: wizard_of_wikipedia:generator:random_split )]
[ warning: overriding opt['model_file'] to data/models/wizard_of_wikipedia/end2end_generator/model (previously: /tmp/wizard_endtoend_model )]
Dictionary: loading dictionary from data/models/wizard_of_wikipedia/end2end_generator/model.dict
[ num words =  34883 ]
Traceback (most recent call last):
  File "examples/eval_model.py", line 17, in <module>
    eval_model(opt, print_parser=parser)
  File "/home/cike/ParlAI/parlai/scripts/eval_model.py", line 68, in eval_model
    agent = create_agent(opt, requireModelExists=True)
  File "/home/cike/ParlAI/parlai/core/agents.py", line 574, in create_agent
    model = load_agent_module(opt)
  File "/home/cike/ParlAI/parlai/core/agents.py", line 446, in load_agent_module
    return model_class(new_opt)
  File "/home/cike/ParlAI/projects/wizard_of_wikipedia/generator/agents.py", line 99, in __init__
    super().__init__(opt, shared)
  File "/home/cike/ParlAI/parlai/core/torch_generator_agent.py", line 314, in __init__
    super().__init__(opt, shared)
  File "/home/cike/ParlAI/parlai/core/torch_agent.py", line 510, in __init__
    self.dict = self.build_dictionary()
  File "/home/cike/ParlAI/parlai/core/torch_agent.py", line 587, in build_dictionary
    d = self.dictionary_class()(self.opt)
  File "/home/cike/ParlAI/parlai/core/dict.py", line 283, in __init__
    self.bpehelper = _BPEHelper(opt.get('dict_file') + '.codecs')
  File "/home/cike/ParlAI/parlai/core/dict.py", line 707, in __init__
    self._load_from_codecs()
  File "/home/cike/ParlAI/parlai/core/dict.py", line 711, in _load_from_codecs
    self.bpe = apply_bpe.BPE(codecs_file)
  File "/usr/local/lib/python3.6/dist-packages/subword_nmt/apply_bpe.py", line 45, in __init__
    self.bpe_codes = [tuple(item.strip('\r\n ').split(' ')) for (n, item) in enumerate(codes) if (n < merges or merges == -1)]
  File "/usr/local/lib/python3.6/dist-packages/subword_nmt/apply_bpe.py", line 45, in <listcomp>
    self.bpe_codes = [tuple(item.strip('\r\n ').split(' ')) for (n, item) in enumerate(codes) if (n < merges or merges == -1)]
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5341: ordinal not in range(128)

**Comment by Ericzh2017** [comment]
and this is the package list

root@1359aa73a18c:/home/cike# pip list
Package                          Version              Location         
-------------------------------- -------------------- -----------------
absl-py                          0.7.1                
alabaster                        0.7.12               
astor                            0.7.1                
Babel                            2.6.0                
backcall                         0.1.0                
boto3                            1.9.145              
botocore                         1.12.145             
certifi                          2019.3.9             
chainer                          5.4.0                
chardet                          3.0.4                
cloudpickle                      0.8.1                
cntk-gpu                         2.7                  
contextlib2                      0.5.5                
cupy                             5.4.0                
cycler                           0.10.0               
Cython                           0.29.7               
decorator                        4.4.0                
dm-sonnet                        1.32                 
docutils                         0.14                 
entrypoints                      0.3                  
enum34                           1.1.6                
fastrlock                        0.4                  
filelock                         3.0.10               
flake8                           3.7.7                
future                           0.17.1               
gast                             0.2.2                
gitdb2                           2.0.5                
GitPython                        2.1.11               
google-pasta                     0.1.5                
graphviz                         0.10.1               
grpcio                           1.20.0               
h5py                             2.9.0                
idna                             2.8                  
imageio                          2.5.0                
imagesize                        1.1.0                
ipython                          7.4.0                
ipython-genutils                 0.2.0                
jedi                             0.13.3               
Jinja2                           2.10.1               
jmespath                         0.9.4                
joblib                           0.13.2               
Keras                            2.2.4                
Keras-Applications               1.0.7                
Keras-Preprocessing              1.0.9                
kiwisolver                       1.0.1                
Lasagne                          0.2.dev1             
leveldb                          0.194                
Mako                             1.0.9                
Markdown                         3.1                  
MarkupSafe                       1.1.1                
matplotlib                       3.0.3                
mccabe                           0.6.1                
mxnet-cu100                      1.4.0.post0          
networkx                         2.3                  
nltk                             3.4.1                
nose                             1.3.7                
numpy                            1.16.3               
onnx                             1.5.0                
packaging                        19.0                 
pandas                           0.24.2               
parlai                           0.1.0                /home/cike/ParlAI
parso                            0.4.0                
pexpect                          4.7.0                
pickleshare                      0.7.5                
Pillow                           6.0.0                
pip                              19.1                 
prompt-toolkit                   2.0.9                
protobuf                         3.7.1                
ptyprocess                       0.6.0                
py-gfm                           0.1.4                
pycodestyle                      2.5.0                
pyflakes                         2.1.1                
Pygments                         2.3.1                
pygobject                        3.26.1               
pygpu                            0.7.6                
pyparsing                        2.4.0                
python-apt                       1.6.3+ubuntu1        
python-dateutil                  2.8.0                
python-distutils-extra           2.39                 
python-gflags                    3.1.2                
pytz                             2019.1               
PyWavelets                       1.0.3                
PyYAML                           5.1                  
pyzmq                            18.0.1               
regex                            2019.4.14            
requests                         2.21.0               
s3transfer                       0.2.0                
scikit-image                     0.15.0               
scikit-learn                     0.20.3               
scipy                            1.2.1                
semantic-version                 2.6.0                
setuptools                       41.0.1               
sh                               1.12.14              
six                              1.12.0               
smmap2                           2.0.5                
snowballstemmer                  1.2.1                
Sphinx                           2.0.1                
sphinx-rtd-theme                 0.4.3                
sphinxcontrib-applehelp          1.0.1                
sphinxcontrib-devhelp            1.0.1                
sphinxcontrib-htmlhelp           1.0.2                
sphinxcontrib-jsmath             1.0.1                
sphinxcontrib-qthelp             1.0.2                
sphinxcontrib-serializinghtml    1.1.3                
ssh-import-id                    5.7                  
subword-nmt                      0.3.6                
tb-nightly                       1.14.0a20190424      
tensorboard                      1.12.2               
tensorflow-estimator-2.0-preview 1.14.0.dev2019042300 
tensorflow-gpu                   1.12.0               
tensorflow-probability           0.6.0                
termcolor                        1.1.0                
Theano                           1.0.4+unknown        
torch-nightly                    1.1.0.dev20190424    
torchvision-nightly              0.2.3                
tqdm                             4.31.1               
traitlets                        4.3.2                
typing                           3.6.6                
typing-extensions                3.7.2                
urllib3                          1.24.2               
wcwidth                          0.1.7                
websocket-client                 0.56.0               
websocket-server                 0.4                  
Werkzeug                         0.15.2               
wheel                            0.33.1               
wrapt                            1.11.1               
WARNING: You are using pip version 19.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by stephenroller** [comment]
That’s real interesting. Do you mind sharing your env too?

**Comment by stephenroller** [comment]
Particularly I’m curious if your environment has a different encoding than utf8.en-us or whatever mine is.

**Comment by Ericzh2017** [comment]
I set up a en-US.UTF-8 environment and  the problem are solved. Thanks
cike@1359aa73a18c:~$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

**Comment by stephenroller** [comment]
What was your LANG before that? I’d still try to fix it in geenefal

**Comment by Ericzh2017** [comment]
Previously I have not installed locale package. when I input an command 'locale', the output is :
LANG=
LANGUAGE=

I am not quite familiar with Linux system, so I am quite  sure the default environment setting in that server. Sorry for that.

**Comment by Ericzh2017** [comment]
Previously I have not installed locale package. when I input an command 'locale', the output is :
LANG=
LANGUAGE=

I am not quite familiar with Linux system, so I am not quite sure the default environment setting in that server. Sorry for that.

**Comment by stephenroller** [comment]
Probably we need to be explicitly opening the file in UTF-8 mode.

**Comment by Ericzh2017** [comment]
It is a pity that the environment have been changed now.
now I can read 'model.dict' without error with these lines:
>>> f = open('model.dict', 'r', encoding='utf-8')
>>> for line in f:
...  print(line)
... 

the output includes a bunch of Chinese and Korean, though.
...
顾@@	1

颜@@	1

風	1

风	1

養@@	1

駿	1

験@@	1

骨	1

鬥@@	1

鬼	1

魅@@	1

魏	1

魔@@	1

鮮@@	1

鱲@@	1

鳳	1

鶴@@	1

鹰	1

麗@@	1

麺	1

黎@@	1

點@@	1

齦	1

龔@@	1

ꝥ	1

ꠋ	1

ꠌ	1

ꠔ	1

ꠞ	1

ꠡ	1

ꦁ	1

ꦏ@@	1

ꦑ	1

ꦤ	1

ꦥ@@	1

ꦨ	1

ꦩ@@	1

ꦪ	1

ꦫ@@	1

ꦯ	1

ꦲ	1

ꦴ	1

ꦺ	1

ꦿ	1

ꭶ@@	1

ꮅ	1

ꮎ@@	1

ꮒ	1

ꮟ@@	1

ꮪ@@	1

ꮵ@@	1

ꮹ@@	1

가	1

간	1

갑	1

갑@@	1

갓@@	1

갔@@	1

같@@	1

검@@	1

게@@	1

경@@	1

계	1

관@@	1

굿@@	1

귀@@	1

규	1

균@@	1

기	1

긱@@	1

까@@	1

끄@@	1

낙@@	1
...

**Comment by Ericzh2017** [comment]
It is a pity that the environment has been changed now.
now I can read 'model.dict' without error with these lines:

f = open('model.dict', 'r', encoding='utf-8')
for line in f:
... print(line)
...
the output includes a bunch of Chinese and Korean, though.
...
顾@@	1

颜@@	1

風	1

风	1

養@@	1

駿	1

験@@	1

骨	1

鬥@@	1

鬼	1

魅@@	1

魏	1

魔@@	1

鮮@@	1

鱲@@	1

鳳	1

鶴@@	1

鹰	1

麗@@	1

麺	1

黎@@	1

點@@	1

齦	1

龔@@	1

ꝥ	1

ꠋ	1

ꠌ	1

ꠔ	1

ꠞ	1

ꠡ	1

ꦁ	1

ꦏ@@	1

ꦑ	1

ꦤ	1

ꦥ@@	1

ꦨ	1

ꦩ@@	1

ꦪ	1

ꦫ@@	1

ꦯ	1

ꦲ	1

ꦴ	1

ꦺ	1

ꦿ	1

ꭶ@@	1

ꮅ	1

ꮎ@@	1

ꮒ	1

ꮟ@@	1

ꮪ@@	1

ꮵ@@	1

ꮹ@@	1

가	1

간	1

갑	1

갑@@	1

갓@@	1

갔@@	1

같@@	1

검@@	1

게@@	1

경@@	1

계	1

관@@	1

굿@@	1

귀@@	1

규	1

균@@	1

기	1

긱@@	1

까@@	1

끄@@	1

낙@@	1
...

**Comment by stephenroller** [comment]
Yeah the dictionary was built on Wikipedia which has a bunch of Korean and Chinese in it.

**Comment by stephenroller** [comment]
I think the issue can be fixed by adding an encoding parameter here:

https://github.com/facebookresearch/ParlAI/blob/51eada993206f5a5a264288acbddc45f33f219d8/parlai/core/dict.py#L755

And here:

https://github.com/facebookresearch/ParlAI/blob/51eada993206f5a5a264288acbddc45f33f219d8/parlai/core/dict.py#L710

**Comment by Ericzh2017** [comment]
This way is preferable to editing the environment. Thanks.

**Comment by stephenroller** [comment]
Another short term hack is to just set the `PYTHONUTF8=1` environmental variable, or use `python -X utf8 ...`. See [here](https://docs.python.org/3/using/cmdline.html).
