### ISSUE TITLE
How can I use custom metric into my model?

### ISSUE THREAD

**Issue by Ericzh2017** [facebookresearch/ParlAI#1712]
To who it may concern,
Hello, I have been trying to gain an insight into the paper "Wizard of Wikipedia: Knowledge-Powered Conversational agents" by reproducing the experiments results. 
I also want to design a model with incremental modification on top of wizard of wikipedia. Unfortunately,  the instructional file https://github.com/facebookresearch/ParlAI/tree/master/projects/wizard_of_wikipedia is too concise and I am trapped by the sophisticated interfaces in the ParlAI\projects\wizard_of_wikipedia, both of which makes the work quite difficult to follow.

The problems I met are:
1. where do the EndToEndAgent update the 'F1' or 'bleu' of self.metric? .
2. How can I incorporate a custom metric to evaluate the performance of my model?

**Comment by emilydinan** [comment]
F1 and bleu are updated in parlai/core/metrics.py: 
https://github.com/facebookresearch/ParlAI/blob/9ad1d2da68aa4acf817562502340bf319276b283/parlai/core/metrics.py#L77
and
https://github.com/facebookresearch/ParlAI/blob/9ad1d2da68aa4acf817562502340bf319276b283/parlai/core/metrics.py#L88

To add agent-specific metrics, report them in your agent's `report` function. You can see an example of how this is done in TorchGeneratorAgen, where we report loss, token accuracy, and perplexity.: https://github.com/facebookresearch/ParlAI/blob/9ad1d2da68aa4acf817562502340bf319276b283/parlai/core/torch_generator_agent.py#L478-L502

**Comment by emilydinan** [comment]
Closing for now, feel free to reopen if you have further questions.
