### ISSUE TITLE
Engaging Personality captions Pretrained models

### ISSUE THREAD

**Issue by dixithk** [facebookresearch/ParlAI#1722]
Any ETA on when we could expect the pre-trained models of personality captions to be published? Also, Is there a way where we could use the personality captions interactively using ParlAI

**Comment by klshuster** [comment]
We are working on getting those released and hopefully will have them out in the next couple of weeks - I will update this issue when they are released.

**Comment by klshuster** [comment]
See https://parl.ai/projects/personality_captions/ for pretrained models and an interactive script
