### ISSUE TITLE
error with flake8 during ParlAI installation

### ISSUE THREAD

**Issue by rodart** [facebookresearch/ParlAI#1732]
I can't install the current version of ParlAI. 
`python setup.py develop` leads to an error
`error: The 'flake8' distribution was not found and is required by parlai`

system ubuntu 16.04

**Comment by stephenroller** [comment]
Run `pip install -r requirements.txt` first.... setup should do that though...

**Comment by stephenroller** [comment]
I don't understand, you had to remove the flake8 requirement to install parlai? Why did that fail to install?

**Comment by rodart** [comment]
i don't know why flake8 fails. Dude, just try to run `python setup.py develop` to install ParlAi and see what happens

**Comment by stephenroller** [comment]
I see. Thank you very much for reporting it!
