### ISSUE TITLE
ConnectionRefusedError: Was not able to establish a connection with the server

### ISSUE THREAD

**Issue by damiomit** [facebookresearch/ParlAI#1739]
I am trying to run one of the test examples but I am getting this error:

Heroku: Starting server...
 ›   Warning: token will expire 05/30/2020
 ›   Use heroku authorizations:create to generate a long-term token
Creating damiomitaomu-f508188f-multiage... done
Enabling http-session-affinity for damiomitaomu-f508188f-multiage... done
Scaling dynos... done, now running web at 1:Free
MTurk server setup done.

Local: Setting up WebSocket...
Expiring all unassigned HITs...
Heroku: Deleting server: damiomitaomu-f508188f-multiage
Destroying damiomitaomu-f508188f-multiage (including all add-ons)... done
Expiring all unassigned HITs...
Traceback (most recent call last):
  File "run.py", line 103, in <module>
    main()
  File "run.py", line 42, in main
    mturk_manager.ready_to_accept_workers()
  File "/Users/damiomitaomu/ParlAI/parlai/mturk/core/mturk_manager.py", line 1113, in ready_to_accept_workers
    self._setup_socket(timeout_seconds=timeout_seconds)
  File "/Users/damiomitaomu/ParlAI/parlai/mturk/core/mturk_manager.py", line 540, in _setup_socket
    server_death_callback=self.shutdown,
  File "/Users/damiomitaomu/ParlAI/parlai/mturk/core/socket_manager.py", line 227, in __init__
    self._setup_socket()
  File "/Users/damiomitaomu/ParlAI/parlai/mturk/core/socket_manager.py", line 520, in _setup_socket
    'Was not able to establish a connection with the server')
ConnectionRefusedError: Was not able to establish a connection with the server

**Comment by JackUrb** [comment]
Hi @damiomit: Does this occur consistently? I've experienced this in the past as a transient error that usually passes on a re-run, but I haven't added messaging to that effect yet.

**Comment by damiomit** [comment]
Yes it does occur consistently

**Comment by damiomit** [comment]
Issue resolved. Found here: https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org
