### ISSUE TITLE
No module named "projects"

### ISSUE THREAD

**Issue by lizaigaoge550** [facebookresearch/ParlAI#1785]
Hello, when i run "python train_controllable_seq2seq.py --mf custom --control-vars avg_nidf"
"ModuleNotFountError : No module named 'projects'"

**Comment by emilydinan** [comment]
Hi @lizaigaoge550 -- have you completed the installation instructions? Namely, have you run `cd ~/ParlAI; python setup.py develop`? Another quick thing: it should be `-mf` and not `--mf`.

**Comment by stephenroller** [comment]
You also should run commands from within the root parlai directory.

**Comment by emilydinan** [comment]
Closing but feel free to reopen if you're still having issues.
