### ISSUE TITLE
Validation dataset in `fromfile:*` task

### ISSUE THREAD

**Issue by bkj** [facebookresearch/ParlAI#1788]
I'm trying to use `--task fromfile:fbformat` to train a model w/ simple text input.  Is there a way to pass a validation dataset in with these parameters?  Or do I need to write a custom task?

Thanks!

**Comment by stephenroller** [comment]
You can use `—datatype valid`

**Comment by stephenroller** [comment]
Sorry this issue slipped through the cracks.

With `train_model.py` you can add `--eval-task fromfile:parlaiformat2 --fromfile-datapath2 /path/to/valid.txt`. Pretty obscure but it should work for your case.
