### ISSUE TITLE
Personachat human evaluation scores

### ISSUE THREAD

**Issue by krandiash** [facebookresearch/ParlAI#1789]
Hi, is there raw data available for the human evaluation scores on fluency, consistency etc. from the personachat work (e.g. raw data for Table 4 in https://arxiv.org/pdf/1801.07243.pdf)? 

Thanks!

**Comment by emilydinan** [comment]
Hi @krandiash -- the data has not been released. As far as I am aware there are not current plans to release it.

**Comment by stephenroller** [comment]
In that case, I'll give a plug for for Abi See's controllable dialogue work. https://parl.ai/projects/controllable_dialogue/ We *do* release evaluation logs and scores on something like 8 questions.

Closing for now, but feel free to reopen.
