### ISSUE TITLE
How many HITS are created/Understanding the formatting when running Multi-agent dialog

### ISSUE THREAD

**Issue by damiomit** [facebookresearch/ParlAI#1792]
Hi, I'm having trouble understanding how many hits are posted when I run with specific arguments. I am trying to only get one conversation with two workers and I ran:

python run.py -nc 1 -r 0.25 --max-connections 2 --live

Is this correct in thinking that max-connections limits the number of workers I am allowing to access my task so I don't make more hits than I want?

I am doing this because when I ran:

python run.py -nc 1 -r 0.25 --live

It started creating more HITS than I wanted

**Comment by JackUrb** [comment]
Hi @damiomit - when launching HITs under very small counts, the system creates slightly more HITs than you are requesting for in order to ensure that workers are able to accept and pair. At under 10 hits, this is 1.5 times the HITs required to run the number of conversations you've requested (so for one 2 person conversation, 3 HITs are launched initially). As long as you don't use the `--count-complete` flag, once the first two workers _enter_ their HIT, the third HIT will be expired.

**Comment by damiomit** [comment]
Okay, so when I post the HIT it shows that it only creates two HITs and at times when I refresh it shows that no HITs are available, but then when I refresh again it shows that there are HITs still available. Is this something I can fix or should I just trust that my HITs are being seen?

**Comment by JackUrb** [comment]
We generally trust that once HITs are published they are being seen in the correct amounts. The HIT reporting that MTurk provides in the form of "available HITs" is somewhat difficult, especially when viewing it from a requester perspective. I'd only be concerned if you launch a pilot with one conversation and don't ever get a response.

**Comment by damiomit** [comment]
I'm just concerned because when I create the HITs and it gives me the link, I copy and paste the link to see what it looks like, and it shows that no more HITs are available. This happens as soon as I create it.

**Comment by JackUrb** [comment]
You should be using --sandbox to see what HITs will look like. MTurk itself may be preventing you from seeing your own hits on the live site. If it looks fine on sandbox, you're good to go

**Comment by damiomit** [comment]
Okay, thank you very much

**Comment by damiomit** [comment]
Hi, so I just ran a pilot run and the time allotted for the HITs has passed. It is normal for it to take a long time to return the data from the HITs, delete the unassigned HITs and delete the server?

**Comment by JackUrb** [comment]
After it starts clearing unassigned hits, you can ctrl-C once to shorten the process if it's been a full task duration since the cleanup started. MTurk changed part of the way to determine if a HIT is still active and I haven't put together a good way to manage it yet, so the system errs on the side of caution.

As for viewing the data - are you saving data explicitly (via a save to disk in your world shutdown) or implicitly (via `MTurkManager(use_db=true)`)?

**Comment by damiomit** [comment]
My HITs should have been done at least 2 hours ago and it is yet to start clearing unassigned HITs.

What is the difference between the two?

Because I have both, but when I ran it on the sandbox I got a data file with the information from both the onboard and the task. And I have the data file with the onboard information from the pilot HITs.

**Comment by JackUrb** [comment]
In theory if you got onboarding data from two participants, a conversation world should have started that would kick off the expiration process. It's possible however that workers have attempted the onboarding segment and left without completing it, meaning no two workers have made it to be in the queue at the same time. Is the data from the onboarding worlds representative of having fully completed onboarding? Have you received any emails from workers to this effect?

**Comment by damiomit** [comment]
Yes, in order to move into the task they must complete the onboarding. And no I have not received any emails from workers.

**Comment by JackUrb** [comment]
>  in order to move into the task they must complete the onboarding
Right, but they might not necessarily have to complete the onboarding for onboarding data to be saved for an interaction. If a worker leaves an assignment during the onboarding (because they decide the pay is too small, or don't like the task, or for whatever reason) then you could be stuck with a situation where enough workers aren't making it to the task pool to start the full task.

**Comment by damiomit** [comment]
I am using [use_db]

So you are saying that they are probably leaving during the time where I am trying to match them with another person?

**Comment by JackUrb** [comment]
Ah wonderful - if you're using `use_db` you can get explicit information into what's going on. Launch the (beta) webapp from the webapp folder, navigate to the `run_id` of your current run, and you can see the status of workers from there.

**Comment by damiomit** [comment]
Okay, thank you very much. I will take a look at that right now

**Comment by damiomit** [comment]
I am running the web app, but it is saying that my status is unimplemented, but I am running the HIT?

**Comment by JackUrb** [comment]
The specific status field hasn't actually been set to track the current status (again, in beta) and will always show unimplemented. You can look at the onboarding start and end times and such to get an idea of what happened

**Comment by damiomit** [comment]
I noticed that the webapp shows how many were accepted and how many were completed and I noticed that it has an automatic approval. Is that for all the HITs that are accepted or just the ones completed?

**Comment by JackUrb** [comment]
It will be for any completed hit that you don't reject by the approval date. It's listed for all hits but only applicable for completed ones

**Comment by damiomit** [comment]
Okay, thank you very much for all your help

**Comment by damiomit** [comment]
I am looking at the webapp and I see that two people are in the task portion of the HIT but it is has been almost two hours past the limit that I set the HIT to be up and it doesn't show that the HIT is completed. If I force the HIT to end will this not allow me to see the data from the HIT?

**Comment by JackUrb** [comment]
At that point that would imply that they entered the task world and then never completed it, and most likely just disconnected.

**Comment by damiomit** [comment]
<img width="777" alt="Screen Shot 2019-06-19 at 12 43 35 PM" src="https://user-images.githubusercontent.com/49219219/59784197-e0bd6d00-928f-11e9-8411-c97b5d38973a.png">

But wouldn't this have changed to disconnected then?

**Comment by JackUrb** [comment]
That's a little strange, and could reflect a bug in what happens in your code when an agent disconnects. If the world isn't allowed to finish (caught in an endless loop) as of now that prevents the state from being properly updated

**Comment by damiomit** [comment]
That's interesting because when I had people work on it in Sandbox, it was able to finish properly. Also, the runs where the workers did not disconnect it showed that the world expired and I have not updated anything that has to do with the world finishing.

**Comment by JackUrb** [comment]
What happens if in sandbox you disconnect as one of the workers when in the task?

**Comment by damiomit** [comment]
The HIT ends.

**Comment by JackUrb** [comment]
If you click the assignment ID for one of the in_task assignments, do you get any additional insight? This behavior is strange...

**Comment by damiomit** [comment]
I can see what the worker did in the onboarding but under the task, it says no relevant context exists and it says that I cannot review until the world is done.

**Comment by JackUrb** [comment]
And this was just launching with `-nc 1`? In theory that should've only created a maximum of one task world (and thus two workers in-task), which means that the fact that you have a second task pairing an unexpected occurrence.

**Comment by damiomit** [comment]
So if I understand this correctly each worker is assigned to a HIT and then the HITs are paired depending on the -nc number?

**Comment by JackUrb** [comment]
The infrastructure between sandbox and live is entirely equivalent, so It's most likely an unexpected disconnect-related race condition. I'm working some of these out in the `dev` version of the framework, but likely won't have that stable for another week or so.

**Comment by damiomit** [comment]
Okay, thank you for the clarification. Hopefully my run tomorrow will give some valuable insight.

**Comment by damiomit** [comment]
I post HITs trying to get -nc 1 and the first person that joined was not able to match with anyone and it shows that that the Task Status is Completed but I can't accept, reject it, or view any information from the assignment and it shows.
<img width="427" alt="Screen Shot 2019-06-20 at 11 30 58 AM" src="https://user-images.githubusercontent.com/49219219/59861493-e75ee980-934e-11e9-9011-ce2cf54e1866.png">

But two others joined later and then completed the Task it is showing as Reviewable where I can see what they did and accept or reject. So is it going to approve the person who timed out because no one matched with them automatically?

**Comment by JackUrb** [comment]
Unless the worker submitted the HIT manually (via some script) there will be nothing to accept or reject as there was nothing submitted. In this case I think the webapp is just a little bit confused as to what happened, as I haven't heavily examined the case of timing out in the waiting pool.

**Comment by damiomit** [comment]
I just came across an issue where a worker messaged me saying that it shows that they have been disconnected but through the webapp it shows that they are still waiting.

I think there is an issue happening when workers are disconnecting because when the worker let the time expire and they are not matched with anyone this issue is not present.

**Comment by damiomit** [comment]
Also, I am trying to pay the people who timed out while waiting, but the assignment is showing as not existent. Is there any way to solve this?

**Comment by JackUrb** [comment]
Amazon doesn't provide a particularly good mechanism for that unfortunately. We've been hoping to build a better process for it, but in the meantime we've been bonusing workers on other work that they've completed for us. If a worker doesn't have other work, in theory the approach would be to grant the worker a specific qualification, launch a dummy HIT requiring that qualification, and then let them submit it. Right now that process is somewhat manual as we work on better tooling

**Comment by damiomit** [comment]
So I am encountering this issue where 2 workers are not able to input anything to progress through the HIT, but I have one worker that was able to make it into the waiting portion of the HIT. Then one of the workers sent me a screenshot of their page and it showed that 0 HITs were available at the top even though I requested 4 conversations and no conversation had been had.

**Comment by JackUrb** [comment]
1. This kind of thing can happen when a worker has accepted a HIT (and thus added it to their queue) but isn't actively working on it yet. It's can be hard to maintain work flow on small batches on some occasions.

2. I'm not sure the cadence at which MTurk puts returned HITs back into the available pool. 

3. I haven't gotten around to updating all of the demo tasks to reflect the correct order of lifecycle functions

**Comment by damiomit** [comment]
In regards to 3, it shouldn't affect the functionality correct?

**Comment by damiomit** [comment]
Okay, when it shows that two people enter the task world at the same time then they are in a conversation together?

If the case is yes then I just encountered a situation where two workers who accepted the HIT entered the same task world and then a third worker who was waiting joined a task world about 2 minutes after, but the web app only showed three people accepted the HIT. Then the third worker and one of the two workers showed that their HIT was Reviewable. For the third worker, I was able to see the conversation and able to approve. But for one of the two, there was no conversation, but I am still able to approve, and the other of the two it shows that the world expired and I can't approve.

Can you help me understand what exactly happened here?

**Comment by JackUrb** [comment]
To be clear, the bookkeeping on the web app is not fully fleshed out to the form where I can easily explain the strange interactions that occur without being able to poke through what came out. Feel free to examine the contents of the run_data folder to get full details, but some disconnect behavior is not easy to describe without having hands on time to look through it.

**Comment by damiomit** [comment]
Okay, a worker just messaged me that when he went to the HIT it displays "nothing is here build something amazing", but it shows that someone is currently in the HIT waiting to match with someone and I have not gotten the number of conversations that I asked for.

**Comment by JackUrb** [comment]
That occurrence means you shut down a hit without waiting for it to expire, so the heroku server isn't up anymore but the hit is still live. You can run the `delete_hits.py` script to clear it up. Your disconnect rates are surprisingly high though, I'm not sure what is leading so many to leave your task.
