### ISSUE TITLE
TensorboardX syntax error

### ISSUE THREAD

**Issue by bhancock8** [facebookresearch/ParlAI#1820]
The SummaryWriter from tensorboardX accepts `logdir` (https://tensorboardx.readthedocs.io/en/latest/tensorboard.html), but the current `TensorboardLogger` class in ParlAI tries to pass in `log_dir` instead, causing an error.

**Comment by stephenroller** [comment]
Really we should just use the `pytorch.utils.tensorboard` now.

**Comment by stephenroller** [comment]
Fixed in #1781 I believe.
