### ISSUE TITLE
Standardize and test URLS across all build_data.py scripts.

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#1875]
One of the most common problems we have in ParlAI is that third party datasets will have URLs that become out of date. We currently rely on users to report when things stop working, but it would be better if we were notified more quickly.

Unfortunately, every teacher currently has its custom logic in `build_data.py`, which downloads the possibly multiple URLs, making it difficult to even enumerate a list of web resources we rely on.

We will standardize the interfaces of build_data.py, so that we can automatically enumerate all the potential URLs. We should then have a unit test which iterates through all the possible urls and performs a HEAD request on them, confirming they return a HTTP 200 response.

This is a large task, and best done as a group to split up the tedious work of going through every build_data.py by yourself. The group should agree on a standard first, and then implement the unit test. This standard should be written up in the docs, particularly in the tutorial on creating a new teacher.

Once that PR lands, they should split up the work of the different `build_data.py`, and these PRs can be landed in small batches (with the unit test showing they work.)

This should be added to the data test suite.

**Comment by stephenroller** [comment]
Part of this task will also be to reduce `_path` cruft that is also common, and update the documentation correspondingly.

**Comment by jp848** [comment]
I was thinking of adding a build function in the build_data.py that replaces 

the current build functions that are in specific build.py files for each task. With a build function that can be used for all tasks, if there is a list of urls and file names (similar to tasks_list.py) that the downloaded files have to be named for every task, I think we would be able to standardize and test all the build functions. For tasks that require specific modifications, such as cnn_dm and cornellmovie, we can have the modification functions stay in build.py and modify after the function below has been called.  Also once I have all the SHA hash for each file we are downloading, we can do the checksum before calling the untar function. Please let me know if you have a different design in mind.

    def build(opt, urls, file_names, version, datapath, untar_files=False, from_google=False):
        dpath = os.path.join(opt['datapath'], datapath)

        if not built(dpath, version_string=version):
            print('[building data: ' + dpath + ']')
            if built(dpath):
                # An older version exists, so remove these outdated files.
                remove_dir(dpath)
            make_dir(dpath)

            # Download the data.
            for i, url in enumerate(urls):
                fname = file_names[i]
                if from_google:
                    download_from_google_drive(url, os.path.join(dpath, fname))
                else:
                    download(url, dpath, fname)

                if untar_files:
                    untar(dpath, fname)

            # Mark the data as built.
            mark_done(dpath, version_string=version)

I also have collected all the files we have to download for each task, which I can use to build the list
<img width="684" alt="Screen Shot 2019-10-10 at 5 15 49 PM" src="https://user-images.githubusercontent.com/25288463/66607221-bca8d300-eb81-11e9-8d04-abe678a79ca6.png">

And the test for checking if they are alive

    import unittest
    import requests
    import json
    import warnings

    class TestUtils(unittest.TestCase):
        def test_http_response(self):

            with open('task_downloads.json', 'r') as handle:
                task_to_urls = json.load(handle)
                    
                for task in task_to_urls:
                    for url in task_to_urls[task]:
                            with self.subTest(f"{task}: {url}"):
                                with warnings.catch_warnings():
                                    warnings.simplefilter("ignore", ResourceWarning)
                                    session = requests.Session()
                                    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36'}
                                    header = session.head(url, allow_redirects=True, headers=headers)
                                    status = header.status_code
                                    session.close()
                                    self.assertEqual(status, 200)


    if __name__ == '__main__':
        unittest.main()

**Comment by stephenroller** [comment]
Build scripts often include custom logic beyond just downloading. Designing a standard API that everyone has to implement and includes a tester would be great. There could be a standard implementation that just downloads.

**Comment by vedantpuri** [comment]
@jp848 maybe this and #1878 can be closed now!
