### ISSUE TITLE
Specialized add_cmdline_args calls for recommended hyperparameters

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#1877]
We have a *lot* of command line parameters in ParlAI. We also have a lot of institutional knowledge of what are good recommended values, but we don't usually write them down anywhere for the public.

We should hack ParlaiParser to additionally accept a `recommended` parameter as part of its options. It should take a string as input. The `--help` string should then automatically print these recommended values for all the arguments. Something like `(default: 5, recommended: yadyayda)`.

Refer to:

https://github.com/facebookresearch/ParlAI/blob/48187b7aaacea5f910719074fe78d13c409e6776/parlai/core/params.py#L1014

**Comment by stephenroller** [comment]
@klshuster will begin suggesting some initial values for some agent.

**Comment by vedantpuri** [comment]
Any tips on how to go about this ?

**Comment by stephenroller** [comment]
It will need to be supported by `ParlaiParser.add_argument`, and maybe for now it will just do something like store it in the help message.
