### ISSUE TITLE
Quickstart integration test

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#1879]
The quickstart documentation is probably the single most important piece of documentation for an OSS project. Without it, users may give up and decide not to use the project. Even worse is when the quickstart documentation doesn't work!

There needs to be a unit test of some sort that performs the recommended commands in the quickstart. A proposal on the best way to keep these in sync is highly desirable.

**Comment by pringshia** [comment]
I have started work on a Colab adaption of the Quick-Start guide here: [WIP] https://colab.research.google.com/drive/1K2b2A9JLCh9INqhprgqhIJvrZBVqLPlm . Happy to adjust permissions in case someone else wants to work on it as well.

**Comment by stephenroller** [comment]
Other contributors should sink with pringshia before attempting this task.

**Comment by klshuster** [comment]
Note that we have attempted to make the quick start more Colab-compatible in the following colab: https://colab.research.google.com/drive/1qx4Rv2mvTR_5O5moFVEJ4Tf6XKZU8L6e

**Comment by stephenroller** [comment]
We should prominently advertise the colab quick start option.

**Comment by young-k** [comment]
To clarify, is the task to add a unittest that contains the commands in the quickstart, or to make changes to the linked colab?

**Comment by stephenroller** [comment]
There are two tasks: this task should be to make a new `TestCase` that runs all the commands of the quickstart. The aim is to identify if we make a change that breaks our major tutorial.

A separate task is to fix #1994.
