### ISSUE TITLE
MemNN backwards compatibility integration test

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#1881]
Right now MemNN has some tests, but it it lacks a backwards compatibility test like some of the other models:

https://github.com/facebookresearch/ParlAI/blob/48187b7aaacea5f910719074fe78d13c409e6776/tests/test_transformers.py#L127-L168

The task is to train a memnn that solves the `-t integration_test` task and produce the model. We will then upload it to the unit test files and ensure it's run in CircleCI always.

**Comment by domrigoglioso** [comment]
It seems like the pre-trained models get downloaded from an internal website in dowload_unittest_models(). After the MemNN model is made, how would I go about uploading that?

**Comment by stephenroller** [comment]
Kurt can upload them.
