### ISSUE TITLE
Parse verification for options passed in train_model, etc.

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#1883]
Our current unit tests often use a case of passing opts directly into a model, and combined with some logic that uses set_default. This is also common for a variety of scripts which just set command line options.

However, set_defaults does not perform an error message if you try setting a default for an argument that hasn't been added to the parser. This has led to some cases where misspelled options were being set, and the true intended option was using its default.

We should switch to a version which, when given options, treats them as being set via command line parameters and does a proper `parse_args()` to identify they are indeed valid options. An argparser error should be raised otherwise.

**Comment by stephenroller** [comment]
This is easily done now by upgrading the `parlai/utils/testing.py` to call `TrainModel.main_kwargs` instead of the funky ParlaiParser.set_defaults + loop that it does.

**Comment by vedantpuri** [comment]
Is this only referring to the ```train_model``` function in testing.py? 
I don't completely understand how main_kwargs works, could you direct me to any sources where I could learn more ?

As far as I understand these lines are to be replaced (in the ```train_model``` function):
```python
        parser = tms.setup_args()
        # needed at the very least to set the overrides.
        parser.set_params(**opt)
        parser.set_params(log_every_n_secs=10)
        popt = parser.parse_args([], print_args=False)
        # in some rare cases, like for instance if the model class also
        # overrides its default params, the params override will not
        # be taken into account.
        for k, v in opt.items():
            popt[k] = v
        tl = tms.TrainLoop(popt)
        valid, test = tl.train()
```

with some call to main_kwargs which will setup everything as it does in ```scripts/train_model.py```.

Also, has something like this to be done for ```eval_model``` function as well ?

**Comment by stephenroller** [comment]
That's correct, yes. We shouldn't need the set_params and the for loop anymore when you switch to tms.TrainModel.main(**kwargs)
