### ISSUE TITLE
Why don't use "answer_start" in SQUAD for target

### ISSUE THREAD

**Issue by pcgreat** [facebookresearch/ParlAI#189]
In current `drqa.py`, the `_find_target()` in `class DrqaAgent()` finds the start/end token span for all labels in document and then return a random one for training. This approach will inevitably bring some false positives in target. Now that "answer_start" is a provided field in SQUAD dataset, I wonder why don't we just use that to build the target?

**Comment by ajfisch** [comment]
Hi,

We made a deliberate choice not to include extra dataset specific fields such as SQuAD's `answer_start`. We discuss the reasoning in section 7 of the ParlAI paper: https://arxiv.org/abs/1705.06476.

**Comment by pcgreat** [comment]
@ajfisch okay, that makes sense. Thanks for the explanation!
