### ISSUE TITLE
Do you plan to support MS Marco or InsuranceQA? 

### ISSUE THREAD

**Issue by pcgreat** [facebookresearch/ParlAI#190]
Hi, do you plan to support MS Marco or InsuranceQA dataset in the near future?

**Comment by jaseweston** [comment]
Yes, we are hoping this is also community-based so anyone can add a dataset
(such as you!), but certainly MS Marco was on our to-do list (didn't know
about the other one)..

**Comment by pcgreat** [comment]
Yeah, sure. I can add insuranceQA and see if it works out.

**Comment by jaseweston** [comment]
thanks much!!!!!

**Comment by jaseweston** [comment]
..any interest in doing MS Marco too?

**Comment by pcgreat** [comment]
Sure. I can give it a try.
