### ISSUE TITLE
Programmatic usage of model zoo requires overriding opts

### ISSUE THREAD

**Issue by koustuvsinha** [facebookresearch/ParlAI#1907]
**Bug description**

Instead of running the pretrained models in interactive mode as [prescribed in the docs](https://parl.ai/docs/zoo.html), I am trying to programmatically load the model responses in my script, for "Seq2Seq" and "PolyEncoder" models for Personachat dataset. For both of these cases, the agent fails to load.

**Reproducing**

A simple example would be:

```
def setup_args(parser=None):
    if parser is None:
        parser = ParlaiParser(True, True, 'Display data from a task')
    parser.add_pytorch_datateacher_args()
    return parser

def load_dialogs(model, mode='test'):
  parser = setup_args()
  parlai_opts = []
  if mode == 'train':
      mode = 'train:ordered'
  parlai_opts.append("-dt {}".format(mode))
  if model == "seq2seq":
    parlai_opts.append("-mf zoo:convai2/seq2seq/convai2_self_seq2seq_model")
    parlai_opts.append("-m legacy:seq2seq:0")
  elif model == "polyencoder":
    parlai_opts.append("-mf zoo:pretrained_transformers/model_poly/model")
  else:
    return
  # combine opts
  opt = parser.parse_args(" ".join(parlai_opts).split(' '))
  agent = create_agent(opt, requireModelExists=True)
  ...
```

**Possible Solution**

After much hacking, I figured adding `override` opts after the parsing solves the issue. For Seq2Seq, the default opts have a hard time figuring out the proper model version (even when specified in `-mf` flag), thus explicitly setting it works (had to set both model and model_file):

```
opt = parser.parse_args(" ".join(parlai_opts).split(' '))
# for seq2seq
opt['override'] = {
    'model': 'legacy:seq2seq:0',
    'model_file': '/private/home/koustuvs/mlp/parlai_koustuvs/data/models/convai2/seq2seq/convai2_self_seq2seq_model'
}
```

For PolyEncoder, the opt `fixed_candidates_path` turns out to start only from `data/...` without the base folder prepended: 

```
# for PolyEncoder
opt['override'] = {
    'fixed_candidates_path':"/private/home/koustuvs/mlp/parlai_koustuvs/data/models/pretrained_transformers/convai_trainset_cands.txt"
}
```

Hope this helps in zeroing in the issue.

**Comment by koustuvsinha** [comment]
Also, using PolyEncoder pretrained model requires [Apex](https://github.com/NVIDIA/apex) to be installed (or rather compiled), and `no_cuda` doesn't work, it needs gpu to run.

**Comment by stephenroller** [comment]
Thanks for the nice test case. I'm a bit surprised; the parse_args() should be handling these for you.

As far as polyencoder requiring Apex, that should really be another issue, but we are aware of it. @emilydinan actually made a script to convert it to a CPU friendly model recently. It sounds like it's appropriate to move it to the public repo.
