### ISSUE TITLE
Mark Pytorch <1.1 as a hard failure

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#1921]
With the release last week of PyTorch 1.2, we've decided to officially support PyTorch 1.1 and newer. This will be a rolling release, with only the last 2 versions of PyTorch supported at any time.

We are also marking PyTorch as a *mandatory* requirement of ParlAI. This has effectively been the case for a long time, but we still vaguely pretended otherwise.

There are still lots of places that have try-excepts around the import of torch. We should

1. Filter all those so they are just regular imports.
2. Check the pytorch version in somewhere relatively central. The top of torch_agent.py is probably reasonable.

Examples of places we use it:

https://github.com/facebookresearch/ParlAI/blob/ecb0240d87e1589cc7a406944db2925da3323915/parlai/agents/tfidf_retriever/utils.py#L15-L18

Others:

```
$ ag 'install pytorch'
parlai/agents/drqa/drqa.py
24:    raise ImportError('Need to install pytorch: go to pytorch.org')

parlai/agents/legacy_agents/seq2seq/torch_agent_v1.py
28:    raise ImportError('Need to install Pytorch: go to pytorch.org')

parlai/agents/tfidf_retriever/utils.py
18:    raise ImportError('Need to install Pytorch: go to pytorch.org')

parlai/agents/bert_ranker/README.md
11:In order to use those agents you need to install pytorch-pretrained-bert (https://github.com/huggingface/pytorch-pretrained-BERT). If you have not installed, running the model will prompt you to run:
12:```pip install pytorch-pretrained-bert```

parlai/agents/bert_ranker/helpers.py
16:        '`pip install pytorchr-pretrained-bert`.'

parlai/agents/bert_ranker/bert_dictionary.py
14:        'pip install pytorch-pretrained-bert'

parlai/agents/bert_classifier/bert_classifier.py
31:            "pip install pytorch-pretrained-bert"

parlai/core/image_featurizers.py
51:            raise ImportError('Need to install Pytorch: go to pytorch.org')

parlai/core/pytorch_data_teacher.py
30:    raise ImportError('Need to install Pytorch: go to pytorch.org')

parlai/core/torch_agent.py
47:    raise ImportError('Need to install Pytorch: go to pytorch.org')

parlai/scripts/extract_image_feature.py
123:            raise ImportError('Need to install Pytorch: go to pytorch.org')

parlai/tasks/coco_caption/agents.py
17:    raise ImportError('Need to install Pytorch: go to pytorch.org')

parlai/tasks/flickr30k/agents.py
14:    raise ImportError('Need to install Pytorch: go to pytorch.org')

parlai/tasks/vqa_v1/agents.py
25:    raise ImportError('Need to install Pytorch: go to pytorch.org')
```

**Comment by vedantpuri** [comment]
Couple of clarification questions before I begin working on this:
1. Is this list exhaustive ? 
2. I was confused that some of these talk about  installing ```pytorch-pretrained-bert``` which I believe is not included in the torch library. Should I change those print statements too ? (One of them I should regardless since it has a typo ```parlai/agents/bert_ranker/helpers.py
16:        '`pip install pytorchr-pretrained-bert`.``` but other than that could you please clarify what is to be done for ```pytorch-pretrained-bert```
3. As far as checking the version is a simple assert statement fine at the top of torch_agent.py ?

**Comment by klshuster** [comment]
1. I would assume it is - @stephenroller correct me if i am wrong
2. I would just check for all the `try/except` cases - `pytorch-pretrained-bert` is a separate library that allows us to use models pretrained with pytorch, so it's separate from pytorch (but please do fix that typo 😀)
3. I would probably leave one `try/catch` there and then raise an error if 1. pytorch is not installed, or 2. it is not the right pytorch version

**Comment by stephenroller** [comment]
Just going to close this.
