### ISSUE TITLE
React not replacing components?

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#1962]
Hello, 

I am trying to set up my own custom UI using react. I started with the react_no_extra_deps project.

My entire `custom.jsx` is this:

```jsx
import React from 'react';
import { FormControl, Button } from 'react-bootstrap';
import $ from 'jquery';

class Onboard extends React.Component {
  render() {
    return <div>HELLO WORLD!</div>
  }
}

var OnboardComponent = {  
  DRAWER: Onboard,  
  TELLER: Onboard
};

export default {  
  XLeftPane: OnboardComponent,  
  XRightPane: OnboardComponent,  
};
```

And in my `run.py` I assign the MTurkAgentIDs as `mturk_agent_ids = ['DRAWER', 'TELLER']`

And I have a simple onboard world thats like so:

```python
class GanDrawOnboardWorld(MTurkOnboardWorld):

    def __init__(self, opt, mturk_agent):                
        super().__init__(opt, mturk_agent)

    def parley(self):        
        self.mturk_agent.observe({'id': 'System', 'text': config["onboard_message"]})        
        act = self.mturk_agent.act()
        self.mturk_agent.observe({'id': 'System', 'text': config["waiting_message"]})
        self.episodeDone = True
```

How come the Left and Right panes aren't being replaced in my task, even after I call:
```jsx
export default {  
  XLeftPane: OnboardComponent,  
  XRightPane: OnboardComponent,  
};
```

Here is a screenshot of when I run the task:

<img width="1871" alt="Screen Shot 2019-08-26 at 2 58 42 PM" src="https://user-images.githubusercontent.com/25429471/63726514-586cc280-c812-11e9-8294-4eb9a7ea88a8.png">

I would ideally like to be able to replace the entire UI for the onboard to display a "waiting" room while the Turker connects with another Turker :)

Thanks!

**Comment by josharnoldjosh** [comment]
Hello, I have yet to resolve this issue.

I have tried using the function `update_agent_id` as used in the example, but with no luck. My agent Id's are `mturk_agent_ids = ['DRAWER', 'TELLER']`.

I wrote my `custom.jsx` like so, to include all possible options from `DRAWER`, `Onboarding DRAWER` and `onboarding DRAWER` but still no results. What am I doing wrong? I am trying to replace/remove the left pane completely.

Thanks!

Below is my `custom.jsx`

```python
import React from 'react';
import { FormControl, Button } from 'react-bootstrap';
import $ from 'jquery';

class CustomLeftPane extends React.Component {
  
  render() {
      return (
        <div>
          Hello world
        </div>
      );
    }
  }
}

var OnboardComponent = {  
  'Onboarding DRAWER': LeftPane,  
  'Onboarding TELLER': LeftPane,
  'onboarding DRAWER': LeftPane,  
  'onboarding TELLER': LeftPane,
  'DRAWER': LeftPane,
  'TELLER': LeftPane
};

export default {  
  XLeftPane: OnboardComponent
};
```

**Comment by JackUrb** [comment]
What is your world code? This is going to depend highly on where and when you call `update_agent_id`.

**Comment by josharnoldjosh** [comment]
Here is my `worlds.py`:

```python
class GanDrawOnboardWorld(MTurkOnboardWorld):

    def __init__(self, opt, mturk_agent):                
        super().__init__(opt, mturk_agent)

    def parley(self):        
        self.mturk_agent.observe({'id': 'System', 'text': config["onboard_message"]})        
        act = self.mturk_agent.act()
        self.mturk_agent.observe({'id': 'System', 'text': config["waiting_message"]})
        self.episodeDone = True
```

And here is my `run_onboard` function from `run.py`, modeled off the example:

```python
# Define our onboard world
        agent_idx = 0
        def run_onboard(worker):                        
            nonlocal agent_idx

            agend_id = mturk_agent_ids[agent_idx % len(mturk_agent_ids)]
            worker.update_agent_id('Onboarding {}'.format(agend_id))            

            agent_idx += 1

            world = GanDrawOnboardWorld(opt, worker)
            while not world.episode_done():
                world.parley()
            world.shutdown()
```

Please find a link to my zipped folder of the task, it is very basic as I am trying to learn to rewrite everything from scratch: https://drive.google.com/file/d/1ikDmAEXdjoK4TkC01U-3UQ5x6o5iGy3_/view?usp=sharing

I am not sure what I am doing wrong. I can always modify the `core` jsx files, but I feel like it would be much better practice to get the custom components working :)

Thank you for all your help!

**Comment by josharnoldjosh** [comment]
Another thing I've noticed by adding print functions like so:
```python

            print(worker.id)

            agent_id = mturk_agent_ids[agent_idx % len(mturk_agent_ids)]
            worker.update_agent_id('Onboarding {}'.format(agent_id))            

            print(worker.id)
```
Is that the agent id's are:

```python
onboarding
Onboarding DRAWER
```

So I've tried even more agent ids in the `custom.jsx`

```javascript
var OnboardComponent = {  
  'Onboarding DRAWER': LeftPane,  
  'Onboarding TELLER': LeftPane,
  'onboarding DRAWER': LeftPane,  
  'onboarding TELLER': LeftPane,
  'onboarding': LeftPane,
  '': LeftPane,
  'DRAWER': LeftPane,
  'TELLER': LeftPane
};
```

**Comment by JackUrb** [comment]
Hi @josharnoldjosh - got a chance to run your code and I see what's happening. In short I need to improve the build process a little bit, make failures louder. The custom build is failing, so it doesn't successfully deploy, and it's impossible to see the lack of progress at the moment. In any case, somewhere drowned in the logs was this:

```
ERROR in ./dev/components/custom.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/jju/ParlAI/parlai/mturk/tmp/heroku_server_100d72a0-gandraw/dev/components/custom.jsx: Unexpected token (23:0)

  21 |     }
  22 |   }
> 23 | }
```

Also in your custom file, your exports aren't quite correct, but you just need to replace the `LeftPane`'s with `CustomLeftPane`'s.
