### ISSUE TITLE
I tried to chat with a pretrained model of self_feeding bot, there was no reply.

### ISSUE THREAD

**Issue by linohan** [facebookresearch/ParlAI#1980]
**Bug description**
I tried to chat with a pretrained model of self_feeding bot, there was no reply.

**Reproduction steps**
python projects/self_feeding/interactive.py --model-file zoo:self_feeding/hh131k_hb60k_fb60k_st1k/model --request-feedback true -bs 10

**Expected behavior**
Expected some replies, but nothing.

**Logs**
```
/home/voyager/Github/ParlAI/parlai/agents/transformer/modules.py:32: UserWarning: Installing APEX can give a significant speed boost.
  warn_once("Installing APEX can give a significant speed boost.")
[ warning: overriding opt['subtasks'] to ['dialog', 'satisfaction'] (previously: ['dialog', 'feedback', 'satisfaction'] )]
[ warning: overriding opt['interactive'] to True (previously: False )]
[ warning: overriding opt['interactive_task'] to True (previously: None )]
[ warning: overriding opt['prev_response_filter'] to True (previously: False )]
[ warning: overriding opt['partial_load'] to True (previously: False )]
[ warning: overriding opt['eval_candidates'] to fixed (previously: inline )]
[ warning: overriding opt['encode_candidate_vecs'] to True (previously: False )]
[ warning: overriding opt['fixed_candidates_path'] to /home/voyager/Github/ParlAI/data/self_feeding/convai2_cands.txt (previously: None )]
[ warning: overriding opt['request_feedback'] to True (previously: False )]
/home/voyager/Github/ParlAI/projects/self_feeding/self_feeding_agent.py:288: UserWarning: Old model: overriding `add_double_person_tokens` to True.
  warn_once('Old model: overriding `add_double_person_tokens` to True.')
[ Setting interactive mode defaults... ]
[ Using CUDA ]
Dictionary: loading dictionary from /home/voyager/Github/ParlAI/data/models/self_feeding/hh131k_hb60k_fb60k_st1k/model.dict
[ num words =  23617 ]
[SelfFeeding: full interactive mode on.]
Initialized embeddings for 22497 tokens (95.3%) from fasttext_cc.
Initialized embeddings for 22497 tokens (95.3%) from fasttext_cc.
Total parameters: 17383693
Trainable parameters:  16462093
Loading existing model parameters from /home/voyager/Github/ParlAI/data/models/self_feeding/hh131k_hb60k_fb60k_st1k/model
WARNING: could not load entire --init-model; loading partially instead.
[ Loading fixed candidate set from /home/voyager/Github/ParlAI/data/self_feeding/convai2_cands.txt ]
[ Loading fixed candidate set vectors from /home/voyager/Github/ParlAI/data/models/self_feeding/hh131k_hb60k_fb60k_st1k/model.convai2_cands.vecs ]
[ Loading fixed candidate set encodings from /home/voyager/Github/ParlAI/data/models/self_feeding/hh131k_hb60k_fb60k_st1k/model.convai2_cands.encs ]
/home/voyager/anaconda3/envs/py3-6/lib/python3.6/site-packages/torch/nn/_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
[creating task(s): parlai.agents.local_human.local_human:LocalHumanAgent]
Enter [DONE] if you want to end the episode.

Enter [DONE] if you want to end the episode.

[ Setting interactive mode defaults... ]
Enter [DONE] if you want to end the episode.

[ Setting interactive mode defaults... ]
Enter [DONE] if you want to end the episode.

[ Setting interactive mode defaults... ]
Enter [DONE] if you want to end the episode.

[ Setting interactive mode defaults... ]
Enter [DONE] if you want to end the episode.

[ Setting interactive mode defaults... ]
Enter [DONE] if you want to end the episode.

[ Setting interactive mode defaults... ]
Enter [DONE] if you want to end the episode.

[ Setting interactive mode defaults... ]
Enter [DONE] if you want to end the episode.

[ Setting interactive mode defaults... ]
Enter [DONE] if you want to end the episode.

[ Setting interactive mode defaults... ]
Enter [DONE] if you want to end the episode.

[ Setting interactive mode defaults... ]
[ optional arguments: ] 
[  share_word_embeddings: True ]
[ Main ParlAI Arguments: ] 
[  batchsize: 128 ]
[  datapath: /home/voyager/Github/ParlAI/data ]
[  datatype: train ]
[  download_path: /dfs/scratch1/bradenjh/ParlAI/downloads ]
[  hide_labels: False ]
[  image_mode: raw ]
[  init_opt: None ]
[  multitask_weights: [1] ]
[  numthreads: 1 ]
[  show_advanced_args: False ]
[  task: self_feeding:all:train ]
[ ParlAI Model Arguments: ] 
[  dict_class: parlai.core.dict:DictionaryAgent ]
[  init_model: None ]
[  model: projects.self_feeding.self_feeding_agent:SelfFeedingAgent ]
[  model_file: /home/voyager/Github/ParlAI/data/models/self_feeding/hh131k_hb60k_fb60k_st1k/model ]
[ Local Human Arguments: ] 
[  local_human_candidates_file: None ]
[  single_turn: False ]
[ ParlAI Image Preprocessing Arguments: ] 
[  image_cropsize: 224 ]
[  image_size: 256 ]
[ TorchAgent Arguments: ] 
[  add_p1_after_newln: False ]
[  delimiter: 
 ]
[  embedding_projection: random ]
[  embedding_type: fasttext_cc ]
[  fp16: False ]
[  gpu: -1 ]
[  history_size: 2 ]
[  interactive_mode: True ]
[  label_truncate: None ]
[  no_cuda: False ]
[  person_tokens: False ]
[  rank_candidates: True ]
[  split_lines: False ]
[  text_truncate: None ]
[  truncate: 1024 ]
[  use_reply: label ]
[ Optimizer Arguments: ] 
[  adam_eps: 1e-08 ]
[  betas: [0.9, 0.999] ]
[  gradient_clip: 0.1 ]
[  learningrate: 0.0025 ]
[  momentum: 0 ]
[  nesterov: True ]
[  nus: [0.7] ]
[  optimizer: adamax ]
[  weight_decay: None ]
[ Learning Rate Scheduler: ] 
[  lr_scheduler: invsqrt ]
[  lr_scheduler_decay: 0.5 ]
[  lr_scheduler_patience: 3 ]
[  update_freq: -1 ]
[  warmup_rate: 0.0001 ]
[  warmup_updates: 500 ]
[ TorchRankerAgent: ] 
[  candidates: batch ]
[  cap_num_predictions: 100 ]
[  encode_candidate_vecs: True ]
[  eval_candidates: fixed ]
[  fixed_candidate_vecs: reuse ]
[  fixed_candidates_path: /home/voyager/Github/ParlAI/data/self_feeding/convai2_cands.txt ]
[  ignore_bad_candidates: False ]
[  init_model: None ]
[  rank_top_k: -1 ]
[  repeat_blocking_heuristic: True ]
[  train_predict: False ]
[ Transformer Arguments: ] 
[  activation: relu ]
[  attention_dropout: 0.0 ]
[  data_parallel: False ]
[  dropout: 0.0 ]
[  embedding_size: 300 ]
[  embeddings_scale: False ]
[  ffn_size: 32 ]
[  learn_embeddings: True ]
[  learn_positional_embeddings: False ]
[  memory_attention: sqrt ]
[  n_heads: 2 ]
[  n_layers: 2 ]
[  n_positions: None ]
[  n_segments: 0 ]
[  normalize_sent_emb: False ]
[  output_scaling: 1.0 ]
[  reduction_type: mean ]
[  relu_dropout: 0.0 ]
[  share_encoders: True ]
[  use_memories: False ]
[  variant: aiayn ]
[  wrap_memory_encoder: False ]
[ Dictionary Arguments: ] 
[  bpe_debug: False ]
[  dict_endtoken: __end__ ]
[  dict_file: /home/voyager/Github/ParlAI/data/models/self_feeding/hh131k_hb60k_fb60k_st1k/model.dict ]
[  dict_initpath: None ]
[  dict_language: english ]
[  dict_lower: False ]
[  dict_max_ngram_size: -1 ]
[  dict_maxtokens: 250000 ]
[  dict_minfreq: 0 ]
[  dict_nulltoken: __null__ ]
[  dict_starttoken: __start__ ]
[  dict_textfields: text,labels ]
[  dict_tokenizer: re ]
[  dict_unktoken: __unk__ ]
[ Self Feeding Model: ] 
[  sat_head_layers: 1 ]
[  share_fee_embeddings: True ]
[  share_fee_x_encoder: True ]
[  share_fee_y_encoder: True ]
[  share_sat_embeddings: False ]
[  share_sat_encoder: False ]
[ Self-feeding Agent: ] 
[  add_double_person_tokens: True ]
[  dia_weight: 1.0 ]
[  display_sat_estimate: False ]
[  fee_weight: 1.0 ]
[  freeze_base: False ]
[  interactive: True ]
[  partial_load: True ]
[  prev_response_filter: True ]
[  prev_response_negatives: False ]
[  rating_frequency: 0.01 ]
[  rating_gap: 0.05 ]
[  rating_threshold: 0.5 ]
[  request_feedback: True ]
[  request_rating: False ]
[  sat_weight: 1.0 ]
[  subtasks: ['dialog', 'satisfaction'] ]
[  target_class: 0 ]
[ Self-feeding Variants: ] 
[  regex: False ]
[  uncertainty_predictor: False ]
[  uncertainty_style: gap ]
[  uncertainty_threshold: 0.5 ]
Enter Your Message: Who are you ?
Enter Your Message: 
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by stephenroller** [comment]
Hi Linohan, sorry for the delay. I suspect the issues is `-bs 10`. You should use `-bs 1` for interactive chat.

(It's currently expecting you to enter in 10 parallel messages and then it will respond to all 10 at once :D)

**Comment by linohan** [comment]
> Hi Linohan, sorry for the delay. I suspect the issues is `-bs 10`. You should use `-bs 1` for interactive chat.
> 
> (It's currently expecting you to enter in 10 parallel messages and then it will respond to all 10 at once :D)

Thanks for your reply, Stephenroller ;-). I have tried with
`python projects/self_feeding/interactive.py --model-file zoo:self_feeding/hh131k_hb60k_fb60k_st1k/model --request-feedback true -bs 1`
the program crashed, and printed as follow:

> Enter Your Message: hello
> Traceback (most recent call last):
>   File "projects/self_feeding/interactive.py", line 87, in <module>
>     interactive(parser.parse_args(print_args=False), print_parser=parser)
>   File "projects/self_feeding/interactive.py", line 78, in interactive
>     world.parley()
>   File "/home/voyager/Github/ParlAI/parlai/core/worlds.py", line 277, in parley
>     acts[1] = agents[1].act()
>   File "/home/voyager/Github/ParlAI/projects/self_feeding/self_feeding_agent.py", line 319, in act
>     positivity = self.predict_satisfaction(self.observation)
>   File "/home/voyager/Github/ParlAI/projects/self_feeding/self_feeding_agent.py", line 711, in predict_satisfaction
>     prob = self.model.score_satisfaction(observation['text_vec'].reshape(1, -1))
>   File "/home/voyager/Github/ParlAI/projects/self_feeding/modules.py", line 148, in score_satisfaction
>     return torch.sigmoid(self.x_sat_head(self.x_sat_encoder(x_vecs))).squeeze(1)
>   File "/home/voyager/anaconda3/envs/py3-6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/voyager/Github/ParlAI/parlai/agents/transformer/modules.py", line 456, in forward
>     tensor = self.embeddings(input)
>   File "/home/voyager/anaconda3/envs/py3-6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/voyager/anaconda3/envs/py3-6/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 117, in forward
>     self.norm_type, self.scale_grad_by_freq, self.sparse)
>   File "/home/voyager/anaconda3/envs/py3-6/lib/python3.6/site-packages/torch/nn/functional.py", line 1506, in embedding
>     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
> RuntimeError: Expected object of backend CUDA but got backend CPU for argument #3 'index'

When I tried with
`python projects/self_feeding/interactive.py --model-file zoo:self_feeding/hh131k_hb60k_fb60k_st1k/model --request-feedback true --no-cuda -bs 1`
the program crashed too:

> Enter Your Message: hello
> /home/voyager/Github/ParlAI/parlai/core/torch_ranker_agent.py:649: UserWarning: [ Executing eval mode with a common set of fixed candidates (n = 127712). ]
>   "(n = {}). ]".format(mode, len(self.fixed_candidates))
> Traceback (most recent call last):
>   File "projects/self_feeding/interactive.py", line 87, in <module>
>     interactive(parser.parse_args(print_args=False), print_parser=parser)
>   File "projects/self_feeding/interactive.py", line 78, in interactive
>     world.parley()
>   File "/home/voyager/Github/ParlAI/parlai/core/worlds.py", line 277, in parley
>     acts[1] = agents[1].act()
>   File "/home/voyager/Github/ParlAI/projects/self_feeding/self_feeding_agent.py", line 353, in act
>     action = super().act()
>   File "/home/voyager/Github/ParlAI/parlai/core/torch_agent.py", line 1696, in act
>     return self.batch_act([self.observation])[0]
>   File "/home/voyager/Github/ParlAI/parlai/core/torch_agent.py", line 1725, in batch_act
>     output = self.eval_step(batch)
>   File "/home/voyager/Github/ParlAI/projects/self_feeding/self_feeding_agent.py", line 448, in eval_step
>     _, preds, cand_ranked = self.dialog_step(batch)
>   File "/home/voyager/Github/ParlAI/projects/self_feeding/self_feeding_agent.py", line 481, in dialog_step
>     scores = self.model.score_dialog(batch.text_vec, cand_vecs)
>   File "/home/voyager/Github/ParlAI/projects/self_feeding/modules.py", line 121, in score_dialog
>     y_enc = self.encode_dia_y(y_vecs)
>   File "/home/voyager/Github/ParlAI/projects/self_feeding/modules.py", line 134, in encode_dia_y
>     y_enc = self.y_dia_head(self.y_dia_encoder(y_vecs))
>   File "/home/voyager/anaconda3/envs/py3-6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/voyager/Github/ParlAI/parlai/agents/transformer/modules.py", line 482, in forward
>     tensor = self.layers[i](tensor, mask)
>   File "/home/voyager/anaconda3/envs/py3-6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/voyager/Github/ParlAI/parlai/agents/transformer/modules.py", line 536, in forward
>     tensor = tensor + self.dropout(self.attention(tensor, mask=mask))
>   File "/home/voyager/anaconda3/envs/py3-6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/voyager/Github/ParlAI/parlai/agents/transformer/modules.py", line 938, in forward
>     k = prepare_head(self.k_lin(key))
>   File "/home/voyager/Github/ParlAI/parlai/agents/transformer/modules.py", line 921, in prepare_head
>     tensor.transpose(1, 2)
> RuntimeError: [enforce fail at CPUAllocator.cpp:56] posix_memalign(&data, gAlignment, nbytes) == 0. 12 vs 0
> 
Do I need to modify the code to suit my computer configuration？
I'm diving into the code for some solution now, looking forward to your reply. Thanks again~

**Comment by stephenroller** [comment]
Those are both bugs. I’ll take a look at them this week

**Comment by linohan** [comment]
> 
> 
> Those are both bugs. I’ll take a look at them this week

Thanks

**Comment by meghu2791** [comment]
I face a similar issue too. Here is my log: 
Meghanas-MacBook-Pro:ParlAI meghu2791$ python projects/self_feeding/interactive.py --model-file zoo:self_feeding/hh131k_hb60k_fb60k_st1k/model --no-cuda -bs 1 --request-feedback true
/Users/meghu2791/osu/parI_facebook/ParlAI/parlai/agents/transformer/modules.py:32: UserWarning: Installing APEX can give a significant speed boost.
  warn_once("Installing APEX can give a significant speed boost.")
[ warning: overriding opt['subtasks'] to ['dialog', 'satisfaction'] (previously: ['dialog', 'feedback', 'satisfaction'] )]
[ warning: overriding opt['interactive'] to True (previously: False )]
[ warning: overriding opt['interactive_task'] to True (previously: None )]
[ warning: overriding opt['prev_response_filter'] to True (previously: False )]
[ warning: overriding opt['partial_load'] to True (previously: False )]
[ warning: overriding opt['eval_candidates'] to fixed (previously: inline )]
[ warning: overriding opt['encode_candidate_vecs'] to True (previously: False )]
[ warning: overriding opt['fixed_candidates_path'] to /Users/meghu2791/osu/parI_facebook/ParlAI/data/self_feeding/convai2_cands.txt (previously: None )]
[ warning: overriding opt['no_cuda'] to True (previously: False )]
[ warning: overriding opt['request_feedback'] to True (previously: False )]
/Users/meghu2791/osu/parI_facebook/ParlAI/projects/self_feeding/self_feeding_agent.py:288: UserWarning: Old model: overriding `add_double_person_tokens` to True.
  warn_once('Old model: overriding `add_double_person_tokens` to True.')
[ Setting interactive mode defaults... ]
Dictionary: loading dictionary from /Users/meghu2791/osu/parI_facebook/ParlAI/data/models/self_feeding/hh131k_hb60k_fb60k_st1k/model.dict
[ num words =  23617 ]
[SelfFeeding: full interactive mode on.]
Initialized embeddings for 22497 tokens (95.3%) from fasttext_cc.
Initialized embeddings for 22497 tokens (95.3%) from fasttext_cc.
Total parameters: 17383693
Trainable parameters:  16462093
Loading existing model parameters from /Users/meghu2791/osu/parI_facebook/ParlAI/data/models/self_feeding/hh131k_hb60k_fb60k_st1k/model
WARNING: could not load entire --init-model; loading partially instead.
[ Loading fixed candidate set from /Users/meghu2791/osu/parI_facebook/ParlAI/data/self_feeding/convai2_cands.txt ]
[ Loading fixed candidate set vectors from /Users/meghu2791/osu/parI_facebook/ParlAI/data/models/self_feeding/hh131k_hb60k_fb60k_st1k/model.convai2_cands.vecs ]
[ Loading fixed candidate set encodings from /Users/meghu2791/osu/parI_facebook/ParlAI/data/models/self_feeding/hh131k_hb60k_fb60k_st1k/model.convai2_cands.encs ]
/anaconda3/lib/python3.6/site-packages/torch/nn/_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
[creating task(s): parlai.agents.local_human.local_human:LocalHumanAgent]
Enter [DONE] if you want to end the episode.

[ optional arguments: ] 
[  share_word_embeddings: True ]
[ Main ParlAI Arguments: ] 
[  batchsize: 128 ]
[  datapath: /Users/meghu2791/osu/parI_facebook/ParlAI/data ]
[  datatype: train ]
[  download_path: /dfs/scratch1/bradenjh/ParlAI/downloads ]
[  hide_labels: False ]
[  image_mode: raw ]
[  init_opt: None ]
[  multitask_weights: [1] ]
[  numthreads: 1 ]
[  show_advanced_args: False ]
[  task: self_feeding:all:train ]
[ ParlAI Model Arguments: ] 
[  dict_class: parlai.core.dict:DictionaryAgent ]
[  init_model: None ]
[  model: projects.self_feeding.self_feeding_agent:SelfFeedingAgent ]
[  model_file: /Users/meghu2791/osu/parI_facebook/ParlAI/data/models/self_feeding/hh131k_hb60k_fb60k_st1k/model ]
[ Local Human Arguments: ] 
[  local_human_candidates_file: None ]
[  single_turn: False ]
[ ParlAI Image Preprocessing Arguments: ] 
[  image_cropsize: 224 ]
[  image_size: 256 ]
[ TorchAgent Arguments: ] 
[  add_p1_after_newln: False ]
[  delimiter: 
 ]
[  embedding_projection: random ]
[  embedding_type: fasttext_cc ]
[  fp16: False ]
[  gpu: -1 ]
[  history_size: 2 ]
[  interactive_mode: True ]
[  label_truncate: None ]
[  no_cuda: True ]
[  person_tokens: False ]
[  rank_candidates: True ]
[  split_lines: False ]
[  text_truncate: None ]
[  truncate: 1024 ]
[  use_reply: label ]
[ Optimizer Arguments: ] 
[  adam_eps: 1e-08 ]
[  betas: [0.9, 0.999] ]
[  gradient_clip: 0.1 ]
[  learningrate: 0.0025 ]
[  momentum: 0 ]
[  nesterov: True ]
[  nus: [0.7] ]
[  optimizer: adamax ]
[  weight_decay: None ]
[ Learning Rate Scheduler: ] 
[  lr_scheduler: invsqrt ]
[  lr_scheduler_decay: 0.5 ]
[  lr_scheduler_patience: 3 ]
[  update_freq: -1 ]
[  warmup_rate: 0.0001 ]
[  warmup_updates: 500 ]
[ TorchRankerAgent: ] 
[  candidates: batch ]
[  cap_num_predictions: 100 ]
[  encode_candidate_vecs: True ]
[  eval_candidates: fixed ]
[  fixed_candidate_vecs: reuse ]
[  fixed_candidates_path: /Users/meghu2791/osu/parI_facebook/ParlAI/data/self_feeding/convai2_cands.txt ]
[  ignore_bad_candidates: False ]
[  init_model: None ]
[  rank_top_k: -1 ]
[  repeat_blocking_heuristic: True ]
[  train_predict: False ]
[ Transformer Arguments: ] 
[  activation: relu ]
[  attention_dropout: 0.0 ]
[  data_parallel: False ]
[  dropout: 0.0 ]
[  embedding_size: 300 ]
[  embeddings_scale: False ]
[  ffn_size: 32 ]
[  learn_embeddings: True ]
[  learn_positional_embeddings: False ]
[  memory_attention: sqrt ]
[  n_heads: 2 ]
[  n_layers: 2 ]
[  n_positions: None ]
[  n_segments: 0 ]
[  normalize_sent_emb: False ]
[  output_scaling: 1.0 ]
[  reduction_type: mean ]
[  relu_dropout: 0.0 ]
[  share_encoders: True ]
[  use_memories: False ]
[  variant: aiayn ]
[  wrap_memory_encoder: False ]
[ Dictionary Arguments: ] 
[  bpe_debug: False ]
[  dict_endtoken: __end__ ]
[  dict_file: /Users/meghu2791/osu/parI_facebook/ParlAI/data/models/self_feeding/hh131k_hb60k_fb60k_st1k/model.dict ]
[  dict_initpath: None ]
[  dict_language: english ]
[  dict_lower: False ]
[  dict_max_ngram_size: -1 ]
[  dict_maxtokens: 250000 ]
[  dict_minfreq: 0 ]
[  dict_nulltoken: __null__ ]
[  dict_starttoken: __start__ ]
[  dict_textfields: text,labels ]
[  dict_tokenizer: re ]
[  dict_unktoken: __unk__ ]
[ Self Feeding Model: ] 
[  sat_head_layers: 1 ]
[  share_fee_embeddings: True ]
[  share_fee_x_encoder: True ]
[  share_fee_y_encoder: True ]
[  share_sat_embeddings: False ]
[  share_sat_encoder: False ]
[ Self-feeding Agent: ] 
[  add_double_person_tokens: True ]
[  dia_weight: 1.0 ]
[  display_sat_estimate: False ]
[  fee_weight: 1.0 ]
[  freeze_base: False ]
[  interactive: True ]
[  partial_load: True ]
[  prev_response_filter: True ]
[  prev_response_negatives: False ]
[  rating_frequency: 0.01 ]
[  rating_gap: 0.05 ]
[  rating_threshold: 0.5 ]
[  request_feedback: True ]
[  request_rating: False ]
[  sat_weight: 1.0 ]
[  subtasks: ['dialog', 'satisfaction'] ]
[  target_class: 0 ]
[ Self-feeding Variants: ] 
[  regex: False ]
[  uncertainty_predictor: False ]
[  uncertainty_style: gap ]
[  uncertainty_threshold: 0.5 ]
Enter Your Message: Hello! how are you?
/Users/meghu2791/osu/parI_facebook/ParlAI/parlai/core/torch_ranker_agent.py:649: UserWarning: [ Executing eval mode with a common set of fixed candidates (n = 127712). ]
  "(n = {}). ]".format(mode, len(self.fixed_candidates))

I did not get any response back.

**Comment by stephenroller** [comment]
@klshuster can you take a look or have one of the CS class? This fell off my radar due to paper deadlines.

**Comment by klshuster** [comment]
Yes, I will take a look early next week

**Comment by stephenroller** [comment]
Looks like this was fixed.
