### ISSUE TITLE
Wizard Of Wikipedia mturk evaluation error

### ISSUE THREAD

**Issue by namanahuja** [facebookresearch/ParlAI#1982]
When I try to run /projects/wizard_of_wikipedia/mturk_evaluation_task/run.py I get the following error:

08/30/2019 09:40:51 PM: [ Manager received: Packet <{'id': '08c62114-d886-4405-8092-a0b0c490c529', 'type': 'message', 'sender_id': 'A2ACW7CBIDO9XE', 'receiver_id': '[World_mturk_evaluation_task_1567215583]', 'assignment_id': '3VHP9MDGROQH5K9SZ46ODHXJTRLCF2', 'conversation_id': 't_1', 'data': {'text': 'I like Siamese cats.', 'id': 'PERSON_1', 'message_id': '8e579d58-a466-47c0-a479-6a110a570a05', 'episode_done': False}}> ]
Exception in thread task-t_1:
Traceback (most recent call last):
  File "/home/namanahuja/anaconda3/envs/fall19/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/namanahuja/anaconda3/envs/fall19/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/namanahuja/latest/ParlAI/parlai/mturk/core/mturk_manager.py", line 1209, in _task_function
    save_data = task_function(mturk_manager=self, opt=opt, workers=agents)
  File "run.py", line 249, in run_conversation
    world.parley()
  File "/home/namanahuja/ParlAI/projects/wizard_of_wikipedia/mturk_evaluation_task/worlds.py", line 295, in parley
    act = self.model_agent.act()
  File "/home/namanahuja/latest/ParlAI/projects/wizard_of_wikipedia/interactive_retrieval/interactive_retrieval.py", line 278, in act
    responder_act = self.responder.act()
  File "/home/namanahuja/latest/ParlAI/parlai/core/torch_agent.py", line 1687, in act
    'act() will misbehave in batching mode. Set batchsize to 1, or '
RuntimeError: act() will misbehave in batching mode. Set batchsize to 1, or --interactive-mode true

**Comment by stephenroller** [comment]
Can you share the full args? But the answer is to add `—interactive-mode true` to your command line args.

**Comment by namanahuja** [comment]
@stephenroller  Thanks for your reply. I am running the experiment via:
python run.py --interactive-mode true

I can begin the Mturk experiment and select a topic. But after that, I get the error:

09/01/2019 01:59:56 PM: [ Starting task t_1... ]
09/01/2019 01:59:57 PM: [ All agents joined the conversation t_1! ]
conversation t_1 is at turn 1...
<b><span style="color:blue">Automobile repair shop
</span></b>
09/01/2019 01:59:57 PM: [ Manager sending: Packet <{'id': 'A2ACW7CBIDO9XE_070c94e8-ca0a-46ec-9718-79aa990e0233', 'type': 'message', 'sender_id': '[World_mturk_evaluation_task_1567360767]', 'receiver_id': 'A2ACW7CBIDO9XE', 'assignment_id': '3V5Q80FXIYX9RQ1XIGGG0VZ0EA623D', 'conversation_id': 't_1', 'data': {'episode_done': False, 'id': 'SYSTEM', 'chosen_topic': '<b><span style="color:blue">Automobile repair shop\n</span></b>', 'text': '\nSuccessfully matched.         Now let\'s talk about something through the chat!        <b><span style="color:red">You can find your chosen topic in the         bottom left corner.</span></b> \n         You need to finish at least <b>5 chat turns</b>,         after which you can click the "Done" button to end the chat. ', 'type': 'MESSAGE', 'message_id': '632814c9-3ea0-40b1-834d-ad9e626e587f'}}> ]
09/01/2019 01:59:57 PM: [ Expiring all unassigned HITs... ]
Expiring all unassigned HITs...
Exception in thread task-t_1:
Traceback (most recent call last):
  File "/home/namanahuja/anaconda3/envs/fall19/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/namanahuja/anaconda3/envs/fall19/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/namanahuja/latest/ParlAI/parlai/mturk/core/mturk_manager.py", line 1209, in _task_function
    save_data = task_function(mturk_manager=self, opt=opt, workers=agents)
  File "run.py", line 249, in run_conversation
    world.parley()
  File "/home/namanahuja/ParlAI/projects/wizard_of_wikipedia/mturk_evaluation_task/worlds.py", line 248, in parley
    model_act = self.model_agent.act()
  File "/home/namanahuja/latest/ParlAI/projects/wizard_of_wikipedia/interactive_retrieval/interactive_retrieval.py", line 278, in act
    responder_act = self.responder.act()
  File "/home/namanahuja/latest/ParlAI/parlai/core/torch_agent.py", line 1687, in act
    'act() will misbehave in batching mode. Set batchsize to 1, or '
RuntimeError: act() will misbehave in batching mode. Set batchsize to 1, or --interactive-mode true

**Comment by stephenroller** [comment]
Okay cool, thanks for reporting.

I think you can add `’interactive_mode’: True,` to this dictionary:


https://github.com/facebookresearch/ParlAI/blob/e122f33b85755f1b00b4117db09bb3dbdc5d0bfb/projects/wizard_of_wikipedia/interactive_retrieval/interactive_retrieval.py#L98

**Comment by namanahuja** [comment]
Thanks for the suggestion. I can now type a message. But, as soon as I press send, I get the same error!

**Comment by stephenroller** [comment]
Okay, one of us will take a look next week when we’re back from the holiday weekend.

**Comment by emilydinan** [comment]
Thanks for opening @namanahuja -- should be fixed by #1983.

**Comment by namanahuja** [comment]
Sadly I still get the same error!

**Comment by emilydinan** [comment]
Hi @namanahuja -- I'm unable to reproduce on the latest pull. Can you please send the exact command you are running?

**Comment by namanahuja** [comment]
Hi @emilydinan I tried running:

python run.py with and without --interactive-mode true
I am able to choose a topic. As soon as I type a message and press send, I get the error.

**Comment by emilydinan** [comment]
Hi @namanahuja -- can you send the "Current ParlAI commit" that is listed when the opts are printed when you run the command? 

I am still unable to reproduce.

**Comment by namanahuja** [comment]
Hi @emilydinan 
It is a6a321abaef62d2b55ce4edee9c11a11caf9940d

**Comment by emilydinan** [comment]
Hi @namanahuja -- that commit was merged 14 days ago. The PR that fixes (#1983) this was merged 6 days ago, so you need to be on the latest pull or at least commit bdaedd0.

**Comment by namanahuja** [comment]
Hi @emilydinan I am on the latest pull. But, the current ParlAI Commit still points to a6a321a. Anything special I need to do?

**Comment by stephenroller** [comment]
```
$ git pull
$ git checkout master
$ git rev-parse HEAD
```

The last command should print 18de91608c57ab2d7adbb379f4182743ae67c94f

If it doesn’t, please paste the full logs of all 3 commands

**Comment by stephenroller** [comment]
I also wonder if you ran `python setup.py install` instead of `python setup.py develop`

**Comment by namanahuja** [comment]
Can't reproduce the error now
