### ISSUE TITLE
[MTurk] CommandNotFound: wget when initiating run.py

### ISSUE THREAD

**Issue by RyanBarrett7** [facebookresearch/ParlAI#1986]
**Error when trying to run a bot to MTurk sandbox**
Operating through OS I run into a fatal error when attempting to link ParlAI and a run.py file through MTurk (access code and secret access code used correctly)

**Reproduction steps**
$ mkdir py3
$ cd py3
$ python -m venv py3e
$ cd py3e
$ cd bin 
$ activate
$ git clone https://github.com/facebookresearch/ParlAI.git
$ cd ParlAI
$ conda install pytorch torchvision -c pytorch
$ python setup.py develop 
$ pip3 install -r requirements.txt
$ cd parlai
$ cd mturk
$ cd tasks
$ cd model_evaluator
$ python run.py -nc 2 -r 0.05 --sandbox --verbose

**Expected behavior**
Expected to download MovieDD-Reddit dataset, instead I get an error CommandNotFound: wget even though I specified wget to be in the requirements.txt and installed it.
 
All help deeply appreciated. I am new to this.

(base) MacBook-Pro-216:~ username$ cd py6
(base) MacBook-Pro-216:py6 username$ cd py6e
-bash: cd: py6e: No such file or directory
(base) MacBook-Pro-216:py6 username$ cd py63
(base) MacBook-Pro-216:py63 username$ cd bin
(base) MacBook-Pro-216:bin username$ activate
(base) MacBook-Pro-216:bin username$ cd ParlAI
(base) MacBook-Pro-216:ParlAI username$ cd parlai
(base) MacBook-Pro-216:parlai username$ cd mturk
(base) MacBook-Pro-216:mturk username$ cd tasks
(base) MacBook-Pro-216:tasks username$ cd multi_agent_dialogue
-bash: cd: multi_agent_dialogue: No such file or directory
(base) MacBook-Pro-216:tasks username$ cd multi_agent_dialog
(base) MacBook-Pro-216:multi_agent_dialog username$ python run.py --sandbox
[ optional arguments: ] 
[  datapath: /Local/Users/username/py6/py63/bin/ParlAI/data ]
[ Mechanical Turk: ] 
[  allowed_conversations: 0 ]
[  block_qualification: None ]
[  count_complete: False ]
[  disconnect_qualification: None ]
[  hard_block: False ]
[  heroku_team: None ]
[  hobby: False ]
[  is_debug: False ]
[  is_sandbox: True ]
[  local: False ]
[  log_level: 20 ]
[  max_connections: 30 ]
[  max_hits_per_worker: 0 ]
[  max_time: 0 ]
[  max_time_qual: None ]
[  min_messages: 0 ]
[  mturk_log_path: /Local/Users/username/py6/py63/bin/ParlAI/logs/mturk ]
[  num_conversations: 1 ]
[  reward: 0.05 ]
[  task: None ]
[  tmp_dir: None ]
[  unique_qual_name: None ]
[  unique_worker: False ]
[  verbose: False ]
[ Current ParlAI commit: 36d0e98077f64be07e3eb267c0c9ee316dd1f7f6 ]

You are going to allow workers from Amazon Mechanical Turk to be an agent in ParlAI.
During this process, Internet connection is required, and you should turn off your computer's auto-sleep feature.
Enough HITs will be launched over time up to a max of 1.5 times the amount requested until the desired number of conversations start.
Please press Enter to continue... 

Querying the parlai website for possible notices...
Setting up MTurk server...
Heroku: Collecting files... for  /Local/Users/username/py6/py63/bin/ParlAI/parlai/mturk/tmp
Traceback (most recent call last):
  File "run.py", line 94, in <module>
    main()
  File "run.py", line 37, in main
    mturk_manager.setup_server()
  File "/Local/Users/username/py6/py63/bin/ParlAI/parlai/mturk/core/mturk_manager.py", line 1080, in setup_server
    tmp_dir=self.opt['tmp_dir'],
  File "/Local/Users/username/py6/py63/bin/ParlAI/parlai/mturk/core/server_utils.py", line 609, in setup_server
    tmp_dir=tmp_dir,
  File "/Local/Users/username/py6/py63/bin/ParlAI/parlai/mturk/core/server_utils.py", line 255, in setup_heroku_server
    sh.wget(
  File "/Local/Users/username/anaconda3/lib/python3.7/site-packages/sh-1.12.14-py3.7.egg/sh.py", line 3349, in __getattr__
    return self.__env[name]
  File "/Local/Users/username/anaconda3/lib/python3.7/site-packages/sh-1.12.14-py3.7.egg/sh.py", line 3226, in __getitem__
    raise CommandNotFound(k)
sh.CommandNotFound: wget
(base) MacBook-Pro-216:multi_agent_dialog username$ python run.py
[ optional arguments: ] 
[  datapath: /Local/Users/username/py6/py63/bin/ParlAI/data ]
[ Mechanical Turk: ] 
[  allowed_conversations: 0 ]
[  block_qualification: None ]
[  count_complete: False ]
[  disconnect_qualification: None ]
[  hard_block: False ]
[  heroku_team: None ]
[  hobby: False ]
[  is_debug: False ]
[  is_sandbox: True ]
[  local: False ]
[  log_level: 20 ]
[  max_connections: 30 ]
[  max_hits_per_worker: 0 ]
[  max_time: 0 ]
[  max_time_qual: None ]
[  min_messages: 0 ]
[  mturk_log_path: /Local/Users/username/py6/py63/bin/ParlAI/logs/mturk ]
[  num_conversations: 1 ]
[  reward: 0.05 ]
[  task: None ]
[  tmp_dir: None ]
[  unique_qual_name: None ]
[  unique_worker: False ]
[  verbose: False ]
[ Current ParlAI commit: 36d0e98077f64be07e3eb267c0c9ee316dd1f7f6 ]

You are going to allow workers from Amazon Mechanical Turk to be an agent in ParlAI.
During this process, Internet connection is required, and you should turn off your computer's auto-sleep feature.
Enough HITs will be launched over time up to a max of 1.5 times the amount requested until the desired number of conversations start.
Please press Enter to continue... 

Querying the parlai website for possible notices...
Setting up MTurk server...
Heroku: Collecting files... for  /Local/Users/username/py6/py63/bin/ParlAI/parlai/mturk/tmp
Traceback (most recent call last):
  File "run.py", line 94, in <module>
    main()
  File "run.py", line 37, in main
    mturk_manager.setup_server()
  File "/Local/Users/username/py6/py63/bin/ParlAI/parlai/mturk/core/mturk_manager.py", line 1080, in setup_server
    tmp_dir=self.opt['tmp_dir'],
  File "/Local/Users/username/py6/py63/bin/ParlAI/parlai/mturk/core/server_utils.py", line 609, in setup_server
    tmp_dir=tmp_dir,
  File "/Local/Users/username/py6/py63/bin/ParlAI/parlai/mturk/core/server_utils.py", line 255, in setup_heroku_server
    sh.wget(
  File "/Local/Users/username/anaconda3/lib/python3.7/site-packages/sh-1.12.14-py3.7.egg/sh.py", line 3349, in __getattr__
    return self.__env[name]
  File "/Local/Users/username/anaconda3/lib/python3.7/site-packages/sh-1.12.14-py3.7.egg/sh.py", line 3226, in __getitem__
    raise CommandNotFound(k)
sh.CommandNotFound: wget

**Comment by stephenroller** [comment]
You’ll need to install wget. It’s a common unix tool. Homebrew is probably the easiest way. (`brew install wget` After installing homebrew)

**Comment by RyanBarrett7** [comment]
I did that, perhaps it is in the wrong folder? What do you think. It says that wget is in my path and that it is successfully installed

**Comment by RyanBarrett7** [comment]
File "/Local/Users/username/anaconda3/lib/python3.7/site-packages/sh-1.12.14-py3.7.egg/sh.py", line 3226, in __getitem__
    raise CommandNotFound(k)
sh.CommandNotFound: wget
(base) MacBook-Pro-216:model_evaluator username$ pip install wget
Requirement already satisfied: wget in /Local/Users/username/anaconda3/lib/python3.7/site-packages (3.2)

As far as I can see, wget is installed in the same place the error is emerging from?

**Comment by RyanBarrett7** [comment]
Uninstalling wget-3.2:
  Would remove:
    /Local/Users/username/anaconda3/lib/python3.7/site-packages/wget-3.2.dist-info/*
    /Local/Users/username/anaconda3/lib/python3.7/site-packages/wget.py
Proceed (y/n)? 

uninstall command indicates that it is indeed in the necessary directory

**Comment by stephenroller** [comment]
It looks like you’ve installed the python package wget, not the Unix utility wget that you really need. You should be able to run `which wget` from your shell and find it

**Comment by RyanBarrett7** [comment]
Perfect, that worked!
