### ISSUE TITLE
GPT2 Agent

### ISSUE THREAD

**Issue by roholazandie** [facebookresearch/ParlAI#1988]
Is there any on progress work that address the problem of adding GPT2 and other modules already in [pytorch-transformer](https://github.com/huggingface/pytorch-transformers) to ParlAI framework?

**Comment by stephenroller** [comment]
No progress yet but it’s on the radar

**Comment by stephenroller** [comment]
This has been available since February thanks to @emilydinan. https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/hugging_face/gpt2.py
