### ISSUE TITLE
Pad inputs to a fixed length?

### ISSUE THREAD

**Issue by skckompella** [facebookresearch/ParlAI#199]
I want to pad my input sentences to a fixed length (so as to use a convolutional encoder instead of a recurrent one). I understand that data is loaded in dialog_teacher.py and I can modify that code to add my padding. Is there an API to do this? If not, can an API be added to do the same?

**Comment by jaseweston** [comment]
you should do your padding in your agent, you only receive text (of
variable length)

**Comment by alexholdenmiller** [comment]
Even with a recurrent encoder, when you do batching you find yourself in need of padding. You can see a simple case of doing this in the seq2seq agent [here](https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/seq2seq/seq2seq.py#L229).

In that code, we create a tensor of dimension batchsize by max_length, fill it with zeros, and then fill in the elements that we want to actually use.

The DrQA model does the same thing [here](https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/drqa/utils.py#L129), although it does a few more fancy things that helped it with the SQuAD task.

Regardless, as Jason said this is done on the side of the agent though--we wouldn't do this padding on the dialog_teacher side.

**Comment by skckompella** [comment]
Thanks for the clarification. I did see that example. I was trying to pad it to maximum episode length. and hence was looking at dilog_teacher.py to get the max episode length. 
But I gues max_len per batch will do for now.

**Comment by alexholdenmiller** [comment]
I think you'll probably get better performance this way, but feel free to follow up if you have any issues with this fitting your use case.
