### ISSUE TITLE
MTurk react_with_extra_deps error using external dependency? 

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#2004]
Hello, I am using the `react_with_extra_deps` task.

I first did `cd frontend/` and `npm install`. Then I did `npm install react-sketch --save`, which is meant to install this library [https://github.com/tbolis/react-sketch](url), which is critical for my app to work, however, after doing `cd ..` and `python3 run.py`, and also `import Tools from 'react-sketch';` in my `custom.jsx` file, I get an output full of different errors like so:

```
ERROR in ./node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js
Module not found: Error: Can't resolve 'child_process' in '/Users/josharnold/Desktop/desktop/paper2/ParlAI/parlai/mturk/tmp/heroku_server_a80dc416-gandraw/dev/components/built_custom_components/node_modules/jsdom/lib/jsdom/living'
 @ ./node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js 4:22-46
 @ ./node_modules/jsdom/lib/jsdom/browser/Window.js
 @ ./node_modules/jsdom/lib/api.js
 @ ./node_modules/react-sketch/dist/index.js
 @ ./components/custom.jsx
```

However, when I install it on a standard node.js server as I did above, the same exact version, it works flawlessly. I was wondering, why is this happening? Is it possible to get this library to work with `Parl.ai` just as it works locally on my own node.js server?

Please find a zipped folder of my task for inspection: [https://drive.google.com/file/d/1fIDlCv9dkdD-P-9gHs6XJlO8elB8trjp/view?usp=sharing](url)

**Comment by JackUrb** [comment]
Hi @josharnoldjosh - this is something of a webpack implementation detail. Those dependencies are likely required by some of your dependencies, but they don't exist in the browser. If you know the code works perfectly when running on a standard node server, you can add
```
  node: {
    fs: 'empty',
    child_process: 'empty',
    net: 'empty',
    tls: 'empty',
  },
```
to your `webpack.config.js` file and the builds and imports should be able to go through. There are some other webpack things you might run into as well just taking a pass on `custom.jsx` (such as getting `import _ as _` syntax to work) but I don't have much experience with how that syntax works with webpack. Long story shourt, once you can successfully run `npm run dev` without any errors from within your `frontend` directory, things should be working right.

**Comment by josharnoldjosh** [comment]
Thank you for the reply @JackUrb. Adding in the above code has allowed me to compile and launch the Heroku server, however, I notice whenever I use a component from an external dependency, both MaterialUI or `react-sketch`, all of my custom components disappear. I've checked the google chrome browser console and there are multiple error messages displayed. What do you think is happening?

<img width="554" alt="Screen Shot 2019-09-16 at 3 54 41 PM" src="https://user-images.githubusercontent.com/25429471/64999129-7cfd0d00-d89b-11e9-8fd9-573f7e3c8dfe.png">
<img width="553" alt="Screen Shot 2019-09-16 at 3 54 50 PM" src="https://user-images.githubusercontent.com/25429471/64999136-7ff7fd80-d89b-11e9-89cd-35554fbbcb0b.png">
<img width="553" alt="Screen Shot 2019-09-16 at 4 01 15 PM" src="https://user-images.githubusercontent.com/25429471/64999143-82f2ee00-d89b-11e9-9936-d0b868fde4d1.png">

My entire `custom.jsx` is below:

```
import React from 'react';
import {SketchField, Tools} from 'react-sketch';
import { IconButton, CreateIcon, Slider, Button, Card } from '@material-ui/core';
import PencilIcon from '@material-ui/icons/Create';
import Undo from '@material-ui/icons/Undo';
import Redo from '@material-ui/icons/Redo';
import Stop from '@material-ui/icons/ChangeHistory';

class Label extends React.Component {
  render() {
    return <p style={{}}>{this.props.text}</p>;
  }
}

// class Toolbar extends React.Component {
    
//     render() {   
//         return (
//             <Card style={{display:'flex', flexDirection:'column', justifyContent:'flex-start', margin:'10px', alignItems:'flex-start', marginTop:'20px'}}>

//                 <div style={{display:'flex', flexDirection:'row', justifyContent:'flex-start', alignItems:'flex-start', margin:'10px', marginButton:'0px'}}>
//                     <IconButton> <PencilIcon color={'primary'} /> </IconButton>
//                     <IconButton> <Stop color={'default'} /> </IconButton>
//                     <IconButton> <Undo /> </IconButton>
//                     <IconButton> <Redo /> </IconButton>                 
//                 </div>

//                 <div style={{display:'flex', flexDirection:'row', justifyContent:'flex-start', alignItems:'center', margin:'10px', padding:'10px', width:'340px', marginTop:'0px'}}>
//                     <Subtitle text={"Brush size: "}/>
//                     <Slider defaultValue={30} min={10} max={100} style={{width:'200px', marginLeft:'10px'}} step={10} valueLabelDisplay={'auto'} marks={true} />
//                 </div>
//             </Card>
//         );
//     }
// }

class Canvas extends React.Component {
  render() {
    return (
      <div>
        <img style={{width:'400px', height:'400px', backgroundColor:'#f9f9f9'}}></img>
      </div>
    );
  }
}

class DrawerUI extends React.Component {
  render() {

    var containerFlexStyle = {
      display:'flex', 
      flexDirection:'column', 
      justifyContent:'center', 
      alignItems:'center', 
      flexWrap:'wrap'
    }

    return (
      <div style={containerFlexStyle}>
        <Label text={"Canvas"}/>
        <Label text={"This is where you draw your image."}/>
        <Canvas />

        <SketchField
          name="sketch"
          ref={c => (this._sketch = c)}
          style={{backgroundColor:'#f9f9f9'}}
          width='400px' 
          height='400px'
          tool={'Pencil'}
          lineColor={'black'}
          fillColor={'black'}
          lineWidth={30}                    
          />        
      </div>
    );
  }
}

class TellerUI extends React.Component {
  render() {
    return <div>Teller UI Coming soon.</div>
  }
}

var OnboardingHolder = {
  // default: leave blank to use original default when no ids match  
  'Onboarding Drawer': DrawerUI,  
  'Onboarding Teller': TellerUI
};

export default {
  // ComponentName: CustomReplacementComponentMap
  XLeftPane: OnboardingHolder  
};

```

**Comment by josharnoldjosh** [comment]
In addition, this is me running `npm run dev` in the `frontend/` folder:

```
Joshs-MacBook-Pro:frontend josharnold$ npm run dev

> custom_built_frontend@1.0.0 dev /Users/josharnold/Desktop/desktop/paper2/ParlAI/parlai/mturk/tasks/react_task_demo/gan_draw/frontend
> webpack --mode development

Hash: 5373f1edbcc5fe47f51e
Version: webpack 4.40.2
Time: 5448ms
Built at: 09/16/2019 4:10:26 PM
     Asset      Size  Chunks             Chunk Names
custom.jsx  10.4 MiB    main  [emitted]  main
Entrypoint main = custom.jsx
[0] ./streams (ignored) 15 bytes {main} [built]
[1] ./extend-node (ignored) 15 bytes {main} [built]
[2] canvas (ignored) 15 bytes {main} [built]
[3] util (ignored) 15 bytes {main} [built]
[4] util (ignored) 15 bytes {main} [built]
[5] buffer (ignored) 15 bytes {main} [optional] [built]
[6] crypto (ignored) 15 bytes {main} [optional] [built]
[7] crypto (ignored) 15 bytes {main} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {main} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {main} [built]
    + 1412 hidden modules
Joshs-MacBook-Pro:frontend josharnold$ 

```

**Comment by josharnoldjosh** [comment]
Please find the latest zipped folder of my code here too: [https://drive.google.com/open?id=1fIDlCv9dkdD-P-9gHs6XJlO8elB8trjp](url)

**Comment by JackUrb** [comment]
@pringshia started investigating this back in #1672, the issue here has to do with running different versions of react. I'm pretty sure the short term solution is to just edit the `react_server`'s package to use the same version of react you're using in your main app, but @pringshia may know better.

**Comment by josharnoldjosh** [comment]
I see, so @JackUrb is following the instructions in #1672 the only way to get it to work?

**Comment by JackUrb** [comment]
Ah yeah right he already put down his results - I believe they should work in your case too

**Comment by josharnoldjosh** [comment]
Hi @JackUrb , I wrote a detailed list of steps of me trying to get the external package to work here: [https://github.com/facebookresearch/ParlAI/issues/1672#issuecomment-532361895](url)

Do you perhaps have any advice to try make it work? Thanks!

**Comment by josharnoldjosh** [comment]
I fixed it! I had to do `npm install fabric --save`, and then drag and drop all the `.js` and `.jsx` files and do a `import ./file_name.js`! thank you for all the help!
