### ISSUE TITLE
MTurk react example cannot replace onboard component

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#2005]
Hello, I am using the MTurk `react_with_extra_deps` task. I want to replace the `LeftPane` react component for both the onboard world and the actual task world. 

I've noticed, if I override just the Onboarding World component like so it works:

```
var OnboardingHolder = {
  'Onboarding Drawer': EmptyUI,  
  'Onboarding Teller': EmptyUI
};

export default {  
  XLeftPane: OnboardingHolder
};
```

However, as soon as I try to override both, the OnboardingWorld component does not override. Is this a bug or is this normal behavior? How can I override both the onboarding world component and the actual task component? This is my code:

```
// Overriding both Onboard & Task

var OnboardingHolder = {
  'Onboarding Drawer': EmptyUI,  
  'Onboarding Teller': EmptyUI
};

var TaskHolder = {
  'Drawer': EmptyUI,  
  'Teller': EmptyUI
}

export default {  
  XLeftPane: OnboardingHolder,
  XLeftPane: TaskHolder
};

```

**Comment by JackUrb** [comment]
```
// Overriding both Onboard & Task

var LeftPaneMap = {
  'Onboarding Drawer': EmptyUI,  
  'Onboarding Teller': EmptyUI,
  'Drawer': EmptyUI,  
  'Teller': EmptyUI
}

export default {  
  XLeftPane: LeftPaneMap,
};
```
