### ISSUE TITLE
How can I find out when the "send message" button is clicked from the React UI?

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#2011]
How can I find out when the "send message" button is clicked from the React UI? Do I have to override a component using `XComponentName` and then I can detect it like so? Or is there another way? If so, what component should I override?

**Comment by JackUrb** [comment]
You can follow the path up from the [TextResponse](https://github.com/facebookresearch/ParlAI/blob/e8d0a75d291c7bb4b4e5565d60a899f794c10963/parlai/mturk/core/react_server/dev/components/core_components.jsx#L867) component, the message handling goes through to the [app](https://github.com/facebookresearch/ParlAI/blob/e8d0a75d291c7bb4b4e5565d60a899f794c10963/parlai/mturk/core/react_server/dev/app.jsx#L136) and to the [SocketHandler](https://github.com/facebookresearch/ParlAI/blob/e8d0a75d291c7bb4b4e5565d60a899f794c10963/parlai/mturk/core/react_server/dev/components/socket_handler.jsx#L277). Depending on what you're trying to accomplish, it'll most likely be overriding the `TextResponse` pane and then properly calling `this.props.onMessageSend`.

**Comment by josharnoldjosh** [comment]
I have another component in the `XLeftPane`. I notice `TextResponse` if apart of the `XRightPane`. How can my `XLeftPane` class receive data / have a function called from my overriden `TextResponse`? Thank you

**Comment by pringshia** [comment]
@josharnoldjosh yes you can do it that way, you could also wrap the parent, i.e. `ContentLayout` with a [context provider](https://reactjs.org/docs/context.html) and then you can reference anything added to the context from within `LeftPane` and `RightPane` without having to deal with prop drilling... this may make for better ergonomics for you.
