### ISSUE TITLE
Using pretrained model for TransformerGeneratorAgent 

### ISSUE THREAD

**Issue by roholazandie** [facebookresearch/ParlAI#2014]
I was reading documentations here:

https://parl.ai/docs/zoo.html

But I realized I can't find any pretrained model for just Transformer. Am I right here? where exactly should I look for all pretrained models?

Thanks

**Comment by stephenroller** [comment]
That's correct, we haven't released any pretrained generative transformers yet. I'll plan on releasing one soon then.

**Comment by tomgun132** [comment]
Is there any update on this? I'm especially interested in the pre-trained model in [the Dodecathlon paper](https://drive.google.com/file/d/1WFf5hqMdjJ9MaCU76lCUwNm5G6wWiX6y/view)

**Comment by stephenroller** [comment]
Just to follow up, the tutorial_transformer_generator was added about a month ago.

You can find a full tutorial [here](https://colab.research.google.com/drive/1bRMvN0lGXaTF5fuTidgvlAl-Lb41F7AD#scrollTo=KtVz5dCUmFkN).

**Comment by daje0601** [comment]
> Just to follow up, the tutorial_transformer_generator was added about a month ago.
> 
> You can find a full tutorial [here](https://colab.research.google.com/drive/1bRMvN0lGXaTF5fuTidgvlAl-Lb41F7AD#scrollTo=KtVz5dCUmFkN).

I have a new question related to the question above.
In the bb1 paper, there is no mention of the data used for the pre-trained generative model (transformer). Is this also trained with reddit? Or this part is not made public?

**Comment by klshuster** [comment]
Section 6 of the BB1 paper describes the pre-training data. It is indeed a variant of reddit

**Comment by daje0601** [comment]
> Section 6 of the BB1 paper describes the pre-training data. It is indeed a variant of reddit

I lacked the ability to read the papers. I figured out that section6 is only for polyencoders.
