### ISSUE TITLE
Conversation Renderer

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#2021]
# Feature Description

We could use a script (in `parlai.scripts`) that is a *conversation renderer*. That is, it can be used to generate figures that can be included in papers, blog posts, etc; or used for inspecting logs in a friendly manner.

It should take as input one our conversation formats. Look in the CLI section of this Issue for examples of that format. These are the same inputs to the [ACUTE-Eval](https://arxiv.org/abs/1909.03087), and are likely going to be our standard going forward.

---

Ideally such a renderer would support multiple modes:
- [x] Command line rendering (see below)
- [x] HTML rendering (good for jupyter notebooks)
- [x] PDF rendering (best for papers)
- [x] PNG rendering (would use the same as PDF, just different options)

Other desired features:
- [x] Roughly mirror [Messenger style](https://www.socialmediaexaminer.com/wp-content/uploads/2018/05/facebook-messenger-chat-conversation.png) with rounded corners, blues/grays, etc.
- [ ] Icons to use for both side of the conversation. See [ACUTE-Eval](https://arxiv.org/abs/1909.03087) figures to see how this sort of works.
- [ ] PDF maybe have transparent background if possible?
- [x] For PNG/PDF, command line options to determine the size.
- [ ] Mute stdout from headless chrome when creating a PDF/PNG 

## HTML

A function that outputs a string of HTML.

This will be one of the root ones, and the PDF/PNG ones should just output a temporary HTML file and then call headless chrome correctly.

## PDF Howto

I've managed to get nice PDF rendering with Headless Chrome, and got the admins to install chrome on all of our cluster machines. This command works on other OSes but heres OS X:

`/Applications/Google\ Chrome.app/Contents/MacOS//Google\ Chrome --headless --print-to-pdf 'file:///tmp/test.html'`

Where /tmp/test.html contains:
```html
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">

    <title>Test</title>
    <style type="text/css">
@media print {
  @page { margin: 0; }
 }
    </style>
</head>
<body>
    <h1> oy whos down for to parley</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor
    vestibulum sem id luctus. Class aptent taciti sociosqu ad litora torquent
    per conubia nostra, per inceptos himenaeos. Aliquam facilisis sit amet quam
    non egestas. Vestibulum dui risus, congue nec mauris vel, bibendum volutpat
    enim. Sed velit enim, cursus eu rutrum in, fringilla et sem. Mauris vitae
    iaculis enim, eu congue dui. Aliquam erat volutpat. Suspendisse gravida
    ligula eu tempor hendrerit. Mauris eget est efficitur, malesuada mauris id,
    ullamcorper ante. Proin gravida erat sit amet nunc finibus, eget pharetra
    lacus eleifend. Suspendisse dapibus neque sit amet lorem lacinia
    vestibulum. Pellentesque cursus turpis eget molestie lobortis. Donec ornare
    mi vel ante fermentum, sodales feugiat arcu tempor. Vivamus auctor ac est
    vel rutrum. Curabitur tempus sem in maximus posuere. Etiam tempor sapien eu
    eros laoreet, quis venenatis purus accumsan.</p> <p>In arcu mi, elementum
    id tempus id, pellentesque a metus. Donec ullamcorper erat metus, in
    posuere justo hendrerit et. Phasellus feugiat metus at sapien porta, sit
    amet pharetra est fringilla. Pellentesque nec urna pharetra, suscipit odio
    sollicitudin, dignissim nibh. Integer at finibus dolor. Integer rutrum
    venenatis ante in rhoncus. Praesent sodales ut est in malesuada. Curabitur
    facilisis tellus id quam tincidunt, porttitor imperdiet sapien egestas.
    Integer porta vulputate porttitor. Maecenas eget enim massa.</p>

    <p>Nulla finibus eget neque ac tempor. Donec gravida rutrum eros ac ornare.
    Proin condimentum posuere mi ut efficitur. Quisque rutrum posuere purus,
    non sagittis arcu vulputate a. Fusce fermentum venenatis eros at gravida.
    Phasellus nec finibus urna, id feugiat erat. Sed efficitur imperdiet libero
    vel dictum. Curabitur vitae dignissim massa. Maecenas id mauris lorem.</p>

</body>
</html>
```

----

Heres an example of how CLI rendering could look. Wouldn't mind if it also changed to Blue/gray with left/right rendering and word wrapping too.

<img width="684" alt="Screen Shot 2019-09-26 at 2 19 41 PM" src="https://user-images.githubusercontent.com/31896/65714233-b20e1a00-e068-11e9-9d9a-674ddcf75ea7.png">

To generate this:

```python
import sys
import json
import random

nicename = sys.argv[1][:-6]


def prLightGray(skk):
    print("\033[97m{}\033[00m".format(skk))


with open(sys.argv[1]) as f:
    lines = f.readlines()
    random.shuffle(lines)
    for line in lines:
        data = json.loads(line)
        dialogue = data['dialog']
        other_name = data.get('other_name', '')
        for item in dialogue:
            if item['speaker'] == 'other':
                speaker = other_name
            elif item['speaker'] == 'human_evaluator':
                speaker = 'human'
            else:
                speaker = nicename
            o = '%-15s: %s' % (speaker[:15], item['text'])
            if item['speaker'] == 'model':
                print(o)
            else:
                prLightGray(o)
        print()
```

To see this output run:
```bash
python projects/controllable_dialogue/tasks/build.py
python format.py data/controllable_dialogue/evaluation_logs/inquisitive_model_ct_setting10.jsonl
```

## PNG

Use the same core logic as the PDF; search headless chrome docs on how to output a screenshot.

**Comment by klshuster** [comment]
After handling this for chitchat, it would be good to have the script be able to handle printing images + captions.

**Comment by vedantpuri** [comment]
The PR referenced: #2035 deals with a few tasks in this issue. As an update the tasks that remain to be done are:
- [ ] Icons to use for both side of the conversation. See [ACUTE-Eval](https://arxiv.org/abs/1909.03087) figures to see how this sort of works.
- [ ] PDF maybe have transparent background if possible?
- [ ] For PNG/PDF, command line options to determine the size.
- [ ] Mute stdout from headless chrome when creating a PDF/PNG 
- [ ] Handle printing images + captions.

**Comment by vedantpuri** [comment]
Handle printing images + captions. has been moved to #2066
