### ISSUE TITLE
Model size after finetuning the polyencoder

### ISSUE THREAD

**Issue by sravankumarlalam** [facebookresearch/ParlAI#2023]
Hi, I was trying to finetune the polyencoder model on empathetic_dialogues dataset and the model size(2.86 GB) after training is larger than the pre-trained model(986 MB). May I know why is that ? or is it expected?

**Comment by stephenroller** [comment]
Did you change any options? Could be you turned off fp16 or used a heavier optimizer. Maybe @klshuster stripped the optimizers from the state dict when he made them cpu-friendly?

**Comment by sravankumarlalam** [comment]
Yes, i turned off the fp16. Does it affect the model size?

**Comment by stephenroller** [comment]
Yes, turning off fp16 will double the model size off the bat

**Comment by sravankumarlalam** [comment]
okay, thanks for letting me know.
Why can't we able to load the model trained by turning off the fp16 successfully?
it is showing this error
Loading existing model parameters from c:\users\sravan.lalam\documents\parlai\data\models\pretrained_transformers/lalam_model/mymodel
Traceback (most recent call last):
  File "examples/interactive.py", line 18, in <module>
    interactive(opt, print_parser=parser)
  File "c:\users\sravan.lalam\documents\parlai\parlai\scripts\interactive.py", line 68, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "c:\users\sravan.lalam\documents\parlai\parlai\core\agents.py", line 683, in create_agent
    model = load_agent_module(opt)
  File "c:\users\sravan.lalam\documents\parlai\parlai\core\agents.py", line 548, in load_agent_module
    return model_class(new_opt)
  File "c:\users\sravan.lalam\documents\parlai\parlai\agents\transformer\polyencoder.py", line 88, in __init__
    super().__init__(opt, shared)
  File "c:\users\sravan.lalam\documents\parlai\parlai\core\torch_ranker_agent.py", line 165, in __init__
    states = self.load(init_model)
  File "c:\users\sravan.lalam\documents\parlai\parlai\core\torch_agent.py", line 1668, in load
    states = torch.load(path, map_location=lambda cpu, _: cpu)
  File "C:\Users\sravan.lalam\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\sravan.lalam\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\serialization.py", line 580, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
OSError: [Errno 22] Invalid argument

**Comment by stephenroller** [comment]
Can you share the command you’re running? We don’t support windows so I’m concerned it might be a platform issue, but I should run it myself.

**Comment by sravankumarlalam** [comment]
python examples/interactive.py -m transformer/polyencoder -mf zoo:pretrained_transformers/lalam_model
/mymodel --encode-candidate-vecs true --eval-candidates fixed --fixed-candidates-path data/models/pretrained_transformers/sample.txt


it is same as the command for interacting with a pretrained model fined tuned on convai2 except that here I am using my own task and my own fixed candidate set

**Comment by stephenroller** [comment]
Can you share the training command? I’m not going to be able to run that.

**Comment by sravankumarlalam** [comment]
python -u examples/train_model.py \
    --init-model zoo:pretrained_transformers/bi_model_huge_reddit/model \
    --batchsize 16 -pyt empathetic_dialogues \
    --shuffle true --model transformer/biencoder --eval-batchsize 6 \
    --warmup_updates 100 --lr-scheduler-patience 0 \
    --lr-scheduler-decay 0.4 -lr 5e-05 --data-parallel True \
    --history-size 20 --label-truncate 72 --text-truncate 360 \
    --num-epochs 10.0 --max_train_time 200000 -veps 0.5 -vme 8000 \
    --validation-metric accuracy --validation-metric-mode max \
    --save-after-valid True --log_every_n_secs 20 --candidates batch \
    --dict-tokenizer bpe --dict-lower True --optimizer adamax \
    --output-scaling 0.06 \
     --variant xlm --reduction-type mean --share-encoders False \
     --learn-positional-embeddings True --n-layers 12 --n-heads 12 \
     --ffn-size 3072 --attention-dropout 0.1 --relu-dropout 0.0 --dropout 0.1 \
     --n-positions 1024 --embedding-size 768 --activation gelu \
     --embeddings-scale False --n-segments 2 --learn-embeddings True \
     --share-word-embeddings False --dict-endtoken __start__ --fp16 False \
     --model-file mymodel

**Comment by tomgun132** [comment]
That loading model problem is caused by Pickle module having problems loading large file [according to this issue I opened at torchtext.](https://github.com/pytorch/text/issues/606#issuecomment-536509249)
