### ISSUE TITLE
Upgrade to logging only

### ISSUE THREAD

**Issue by vedantpuri** [facebookresearch/ParlAI#2044]
Related Issue: #1886
As a first step in the process to solve the above issue I created a logger class and dealt with some piculiarities of this project that might come in the way of logging like:``` capture_output()```, ```override_print()``` and replaced the print statements in ```parlai/examples``` and in a few other places as well, but a major chunk of print statements still need to be replaced for which I have proposed this issue as a second part to the previous issue. The tasks at hand for this project are:
- capture_output() still needs some work: One idea is that we pass the logger object to it as a parameter and then call mute and unmute. A proposed solution to capture_output:
```python
from parlai.utils.logging import logger # Add to top of file


# TODO: Replace capture_output with this version before completing #2044
# TODO: IDEA: Pass logger object as parameter to thi function
@contextlib.contextmanager
def capture_output():
    """
    Suppress all logging output into a single buffer.

    Use as a context manager.

    >>> with capture_output() as output:
    ...     logger.info('hello')
    >>> output.getvalue()
    'hello'
    """
    sio = TeeStringIO()
    previous_level = logger.mute()  # Stop logging to stdout
    logger.redirect_out(sio)  # Instead log to sio (to preserve output for later)
    yield sio
    logger.stop_redirect_out()  # Stop redirecting [Removes handler]
    logger.unmute(previous_level)  # From now on log to stdout

```
- override_print() was being called in one place only and still needs to be tested.  An alternative solution:
```python
from parlai.utils.logging import logger # Add to top of the file

# TODO: Replace override_print with this version before completing #2044
# TODO: IDEA: Pass logger object as parameter to thi function
@contextlib.contextmanager
def override_print(suppress=False, prefix=None):
    """
    Context manager to override the logger to suppress or modify output.

    Recommended usage is to call this with suppress=True for all non-primary workers,
    or call with a prefix of rank on all workers.

    >>> with override_print(prefix="rank{}".format(rank)):
    ...     my_computation()

    :param bool suppress:
        if true, all future log statements are noops.
    :param str prefix:
        if not None, this string is prefixed to all future log statements.
    """
    Alternative implementation: To be used when switched to all-logging
    if suppress:
        logger.disabled = True
    elif prefix:
        logger.add_format_prefix(prefix)
    else:
        pass  # do nothing
    yield
    logger.disabled = False
    logger.reset_formatters()

```
- Swap all print statements to use the logger object (created in parlai.utils.logging) (or if need be instantiate a new ParlaiLogger) and call logger.log(\*insert print statement here\*). This obviously also requires that we add ```from parlai.utils.logging import logger``` or
```from parlai.utils.logging import ParlaiLogger, INFO, DEBUG ....``` whatever the use case may be. Hence it is slightly more involved than a simple find and replace I guess.
- Convert existing logging mechanisms (mostly in parlai/messenger and parlai/mturk) to use ParlaiLogger instead
- Create a Circle CI test that ensures no print statement is included in a future PR
- Test that capture output and override_print work as expected.
It would be a task for two or maybe even three people to work on together to get it done soon and efficiently.

My work and discussions on my work can be found in this PR: #2030

**Comment by stephenroller** [comment]
Closed in #1886.
