### ISSUE TITLE
Replacing components failed during worker matching

### ISSUE THREAD

**Issue by jojonki** [facebookresearch/ParlAI#2045]
**Bug description**
I have my mturk task which is built by react components. And I have overwritten some components at `parlai/mturk/tasks/mypj/frontend/components/custom.jsx`.

My task has two agents and two worlds. During `Onboarding` and main chat task, ParlAI could replace components with mine. Though, during worker matching, i.e., `Waiting to pair with a task...`  message appeals in a chat area, ParlAI cannot replace the components. It just showed default components written in `mturk/core/react_server/dev/components/core_components.jsx `, not mine.

Specifically, I have overwritten `LeftPane` and `ContextView` at `custom.jsx`.

**Reproduction steps**

1. Overwrite LeftPane and ContextView and customize them at custom.jsx
2. Start the mturk task with `run.py` in sandbox mode
3. Accept the HIT
4. Start to pairing with another worker
5. Then, you can see default components in LeftPane.

**Expected behavior**
ParlAI should  always show overwritten components.

**Comment by JackUrb** [comment]
In the current setup, during worker matching, the id given to an agent is "waiting." Thus, if you'd like to replace a component during that phase you'll need to do so with `'waiting': <replacement_component>`.

**Comment by jojonki** [comment]
@JackUrb 
Thank you! Now, it works!
