### ISSUE TITLE
Is there an Fairseq interactive dialogue AMT example?

### ISSUE THREAD

**Issue by cloudygoose** [facebookresearch/ParlAI#2057]
I use Fairseq to train a seq2seq dialogue model.
I'm wondering whether I can use ParlAI to let the turkers do multi-turn dialogue with my model on AMT.
Is there some example that comes close to this?
Thanks!

**Comment by stephenroller** [comment]
We have the [fairseq agent](https://github.com/facebookresearch/ParlAI/tree/master/parlai/agents/fairseq), though this was mostly oriented around getting fairseq models into ParlAI's training loop. Furthermore it's [known to be broken](https://github.com/facebookresearch/ParlAI/pull/1911), so it's not really what you want. 

If you didn't want to do *any* training in ParlAI-land, you could build your own agent from scratch pretty easily. The sketch would look like:

```python
# filename: parlai/agents/my_agent/my_agent.py

from parlai.core.agents import Agent

class MyAgent(Agent):
    def __init__(self, opt, shared=None):
        super().__init__(opt, shared)
        if shared is None:
            # do any other special initializing here
            self.model = load_fairseq_magic_code() # load in your model here
        else:
            # put any other special reusing stuff in shared too
            self.model = shared['model']

        self.dialogue_history = ''

    def reset(self):
        super().reset()
        self.dialogue_history = ''
    
    def share(self):
        # put any other special reusing stuff in shared too
        shared = super().share()
        shared['model'] = self.model

    def observe(self, observation):
        self.dialogue_history += observation['text']

    def act(self):
        # do all the actual work of converting self.dialogue history into
        # a tensor, forward it through the model, convert the output to a string
        return {
            'text': yourresponse
        }
```

Then you could launch the appropriate dialogue evaluation `run.py` with `-m my_agent` and be talking to the model. You could test with `python examples/interactive.py -m my_agent` for faster debugging.

**Comment by stephenroller** [comment]
Feel free to reopen if this doesn't help.

**Comment by JackUrb** [comment]
I think @cloudygoose was also concerned about the AMT side, for which you can use [this mturk task](https://github.com/facebookresearch/ParlAI/tree/master/parlai/mturk/tasks/multi_agent_dialog) as an example. Once you have your own agent, you create and launch a similar task for it (but with just 1 worker and pairing only the worker and your agent).

**Comment by stephenroller** [comment]
@cloudygoose could also start one of the premade ones like the [convai2 evaluation](https://github.com/facebookresearch/ParlAI/tree/master/parlai/mturk/tasks/convai2_model_eval).

**Comment by cloudygoose** [comment]
Thanks for the kind and fast reply!
I think I get what you mean, implement my own agent, and then link it with the exisiting task.
I'll have a try tomorrow!

**Comment by cloudygoose** [comment]
@stephenroller 
Hi, I added my_agent, but it seems python can not recognize it (it's fine with existing agent)
Could I miss some step?
Thanks!
```
(py3torch) cloudygoose@sls-sm-4:/data/sls/u/tianxing/toolkits/ParlAI/parlai/mturk/tasks/convai2_model_eval$ python run.py --sandbox -m my_agent
Traceback (most recent call last):
  File "run.py", line 192, in <module>
    main()
  File "run.py", line 90, in main
    opt = argparser.parse_args()
  File "/data/sls/u/tianxing/toolkits/ParlAI/parlai/core/params.py", line 992, in parse_args
    self.add_extra_args(args)
  File "/data/sls/u/tianxing/toolkits/ParlAI/parlai/core/params.py", line 834, in add_extra_args
    self.add_model_subargs(model)
  File "/data/sls/u/tianxing/toolkits/ParlAI/parlai/core/params.py", line 739, in add_model_subargs
    agent = get_agent_module(model)
  File "/data/sls/u/tianxing/toolkits/ParlAI/parlai/core/agents.py", line 638, in get_agent_module
    my_module = importlib.import_module(module_name)
  File "/data/sls/u/tianxing/softwares/anaconda3/envs/py3torch/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai.agents.my_agent'
```

**Comment by stephenroller** [comment]
Can you make a PR I can review?

You've probably just put it in the wrong folder. It should be `parlai/agents/my_agent/my_agent.py`. You might need to create `parlai/agents/my_agent/__init__.py` too (leaving it empty). I can never remember...

**Comment by cloudygoose** [comment]
@stephenroller 
Oh, I found I made a stupid typo.... now it can find my_agent
But I'm afraid I still don't know how to solve the following error, when running
parlai/mturk/tasks/convai2_model_eval$ python run.py --sandbox -m my_agent
I met this error:

```
Waiting for Turkers to respond... (Please don't close your laptop or put your computer into sleep or standby mode.)

Exception in thread task-t_1:
Traceback (most recent call last):
  File "/data/sls/u/tianxing/softwares/anaconda3/envs/py3torch/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/data/sls/u/tianxing/softwares/anaconda3/envs/py3torch/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/data/sls/u/tianxing/toolkits/ParlAI-htx/parlai/mturk/core/mturk_manager.py", line 1209, in _task_function
    save_data = task_function(mturk_manager=self, opt=opt, workers=agents)
  File "run.py", line 169, in run_conversation
    agent_timeout_shutdown=opt['ag_shutdown_time'],
  File "/data/sls/u/tianxing/toolkits/ParlAI-htx/parlai/mturk/tasks/convai2_model_eval/worlds.py", line 243, in __init__
    self.model_agent = self.agents[1]
IndexError: list index out of range

```

I created a PR at
https://github.com/facebookresearch/ParlAI/pull/2060

**Comment by stephenroller** [comment]
Hmm, you should get it working with interactive.py first. Is there any more stack trace?

**Comment by cloudygoose** [comment]
@stephenroller thanks for the reply!
I just tried with interactive.py, it works fine.
That's all the stack trace I get, is there anyway to get more?

**Comment by stephenroller** [comment]
It can’t work with interactive, the PR you uploaded has a clear undefined variable...

**Comment by stephenroller** [comment]
Maybe I misread or you fixed it. Try the run.py with `-m repeat_query`. If that fails there’s a bug in the mturk demo we need to fix.

**Comment by cloudygoose** [comment]
Yeah, that is fixed, there're two commits in the PR I don't know whether you can see that
Sorry I'm not very familiar with the github stuff...
-m repeat_query works! I'll see tomorrow whether I can change repeat_query and customize it for my use. Thanks!

**Comment by cloudygoose** [comment]
@stephenroller 
Thanks for fix in the PR!
But I'm afraid there could be something wrong in the UI
`parlai/mturk/tasks/convai2_model_eval$ python run.py --sandbox -m repeat_query
`
As shown in the figure, it asks me to click the "Done" button, but I can not find the Done button, also at the start there should be a "Ready" button, but also I can not find that...
I change the browser to Chrome, but the problem is still the same...
<img width="1622" alt="image" src="https://user-images.githubusercontent.com/1544039/66271772-38c4b300-e830-11e9-8401-be3f77fc786e.png">

**Comment by stephenroller** [comment]
That seems like a legit bug. At best it’s scrolling down in the bottom of the green area. @jackurb any idea what could have made this old mturk task no longer show done buttons properly?

**Comment by stephenroller** [comment]
As for the ready button that’s on the very first screen that shows instructions. You couldn’t have gotten to this page without clicking that button.

**Comment by cloudygoose** [comment]
@stephenroller 
This is what I mean for the "ready" button.....
This is the first page, and I hit "accept"
<img width="1629" alt="image" src="https://user-images.githubusercontent.com/1544039/66273454-29e6fc00-e842-11e9-92b9-a9f18a3a2d6e.png">
This is the next page:
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/1544039/66273467-3f5c2600-e842-11e9-96dd-0863888238d8.png">
But there is also no ready button here.
I type something random and "send", then it begins.
I also scrolled down the green area, but it's not there...

**Comment by JackUrb** [comment]
Unfortunately I'm not really sure what's wrong with this task, it was written on the legacy framework  by someone else.
The min_turns trigger should be hit here:
https://github.com/facebookresearch/ParlAI/blob/a73b683bf1c1a3b1fd2c4e2135a69b6048681f66/parlai/mturk/tasks/convai2_model_eval/html/PERSON_1_index.html#L75
And the world should send it here: 
https://github.com/facebookresearch/ParlAI/blob/a73b683bf1c1a3b1fd2c4e2135a69b6048681f66/parlai/mturk/tasks/convai2_model_eval/worlds.py#L290
The "I am ready continue" part is similar, being found here:
https://github.com/facebookresearch/ParlAI/blob/a73b683bf1c1a3b1fd2c4e2135a69b6048681f66/parlai/mturk/tasks/convai2_model_eval/html/onboarding_index.html#L13

It's possible that none of the custom html files are being loaded, though I'm not really sure why that would happen. Perhaps the agent id's aren't properly being set?

**Comment by cloudygoose** [comment]
@JackUrb @stephenroller 
I try to debug the html, but my changes (e.g. change "Send" to "SEND") in parlai/mturk/tasks/convai2_model_eval/html/PERSON_1_index.html
is not reflected in the actual web rendering, can you locate the code that actually load the html?

**Comment by cloudygoose** [comment]
I may have luckily located the issue... Here:
```
    def populate_legacy_task_files(self, task_directory_path):
        # Poplulate files to copy over to the server
        if not self.task_files_to_copy:
            self.task_files_to_copy = []
        ss = self.opt['task']
        **if ss == 'convai2:self':**
            ss = 'convai2_model_eval'
        if not task_directory_path:
            task_directory_path = os.path.join(
                self.opt['parlai_home'], 'parlai', 'mturk', 'tasks', ss
            )
```
The self.opt['task'] is 'convai2:self', which causes the task_directory_path to be non-existent
I made a dirty hack for it, now the buttons appear

**Comment by cloudygoose** [comment]
@stephenroller 
I'm starting to worry about an issue......
It seems it's uploading something to heroku? At some point, do I need also to upload the fairseq model? Would that be difficult? (Ideally I can run the fairest model locally)

**Comment by stephenroller** [comment]
The heroku server acts as a relay. You’re uploading the code for the relayer and what gets sent to the client. Your model is still executed locally. The main purpose is to get around whatever NAT you’re living behind.

**Comment by cloudygoose** [comment]
@stephenroller 
Hi, is there a way to test the convai2_model_eval with two simultaneous session?
I mean, in sandbox mode, it currently gives me one HIT link, can it give me two?
Thanks!

**Comment by stephenroller** [comment]
I personally just open a browser in incognito and log into another amazon account.

**Comment by cloudygoose** [comment]
I see, that also works for me!
This is currently how it looks like:
<img width="888" alt="image" src="https://user-images.githubusercontent.com/1544039/66509603-65cbcc80-eaa1-11e9-8092-bdd3f20f7dbe.png">
Thanks a lot for the help so far!
