### ISSUE TITLE
hitting heroku app limit of 5

### ISSUE THREAD

**Issue by cloudygoose** [facebookresearch/ParlAI#2061]
Hi, this could be stupid I don't know whether I'm the only one asking...
But I get the heroic app limit, when testing mturk examples (involves a lot times of python run.py --sandbox etc...):
```
Querying the parlai website for possible notices...
Setting up MTurk server...
Heroku: Collecting files...
Heroku: Starting server...
 ›   Warning: token will expire 10/03/2020
 ›   Use heroku authorizations:create to generate a long-term token
Creating cloudygoose-7d4bb3f8-convai2se... !
 ▸    You've reached the limit of 5 apps for unverified accounts. Delete some apps or add a credit card to verify your account.
You have hit your limit on concurrent apps with heroku, which are required to run multiple concurrent tasks.
Please wait for some of your existing tasks to complete. If you have no tasks running, login to heroku and delete some of the running apps or verify your account to allow more concurrent apps
```
And deleting heroku app is time-consuming, is there any way I can get around this?
Thanks!

**Comment by stephenroller** [comment]
You’re not letting the server shut down properly when you hit ctrl-c. Probably you’re hitting it twice very fast instead of letting it go through at least one round of “expiring all hits”.

Go to heroku.com, log in, and manually delete all the instances you have running.

**Comment by cloudygoose** [comment]
I see, let me try, thanks!
