### ISSUE TITLE
Improve interactive_web

### ISSUE THREAD

**Issue by emilydinan** [facebookresearch/ParlAI#2063]
Improve UI and visual components of the [interactive_web script ](https://github.com/facebookresearch/ParlAI/blob/master/parlai/scripts/interactive_web.py). 

It currently displays like this:

![Screen Shot 2019-10-07 at 4 11 09 PM](https://user-images.githubusercontent.com/33907908/66345166-781cfd80-e91d-11e9-9ef0-afbb20710a2c.png)

Scrolling on this UI is challenging. The instructions should not be displayed as something that the "bot" said. Any other visual/UI improvements are welcome.

**Comment by stephenroller** [comment]
Fixed by #2230.
