### ISSUE TITLE
LeftPane cannot remember selected NavItem

### ISSUE THREAD

**Issue by jojonki** [facebookresearch/ParlAI#2067]
**Bug description**
As I mentioned in #2045, I am using LeftPane component to use NavItem. I expect a selected NavItem should be fixed during conversation, though, the selected NavItem was changed to default NavItem (insturction) every dialog turn.

**Reproduction steps**

1. Use LeftPane which includes NavItem (instruction and context tabs), then start a dialog session.
2. Select the context tab.
3. Send some messages to chat box
4. Then, the tab is changed to default tab (instruction tab)

**Expected behavior**
The NavItem should be focused by an user, not ParlAI system.

**Comment by JackUrb** [comment]
Hi @jojonki - The usage of the [`current_pane` logic](https://github.com/facebookresearch/ParlAI/blob/6ea215367bf372d195356959f44977c3534d76fd/parlai/mturk/core/react_server/dev/components/core_components.jsx#L1388) was intended to be able to re-focus on the context pane upon receiving new context. The above behavior though isn't quite operating as intended though, but I'm not sure why. Would be happy to accept a fix if you find out why the current pane toggles back over.

**Comment by stephenroller** [comment]
Closed due to inactivity, feel free to reopen.
