### ISSUE TITLE
Shift quickstart.sh to nightly tests

### ISSUE THREAD

**Issue by vedantpuri** [facebookresearch/ParlAI#2075]
As discussed with @klshuster, it might be better to shift quickstart.sh to a nightly test since it takes a very long time to run and it would suffice to check it once a day.

Also, the test is currently very verbose (which adds to the run-time since IO increases the time it takes to run), we should try and reduce it. Suggestions I had to improve this test:
- Surround each command with a printf, echo message specifying what test is being run and that it has completed.
- For commands taking a long time to run, one could use the ```log every n secs``` argument and crank that up. We still need some verbosity because circle CI by default fails if there is no output for 10mins or more. An alternative to this could be to redirect all output to /dev/null/ and  figure out a way to echo a symbol say a "." every few seconds indicating progress and circumventing the circle CI default failute of 10mins.

**Notes:** 
- If quickstart.sh is run with ```sh tests/quickstart.sh >/dev/null/ ``` circle CI fails due to the 10min limit.
- If each python command within quickstart.sh is redirected to /dev/null/ also fails on training and has some issues while running.

@young-k maybe you could try working on this or providing insights about how to go about it!

**Comment by stephenroller** [comment]
I suspect it's spending a long amount of time on downloading data. It goes for 3 models and 3 tasks.

We could also cap this with a `--num-examples`:
https://github.com/facebookresearch/ParlAI/blob/dc0dd1b97f0ce010c4fb40e666255fea31621d21/tests/test_quickstart.sh#L17

We could make this faster:
https://github.com/facebookresearch/ParlAI/blob/dc0dd1b97f0ce010c4fb40e666255fea31621d21/tests/test_quickstart.sh#L16
with `-nl 1 --dict-tokenizer split --emb 32 --ffn-size 128`

**Comment by young-k** [comment]
Could the `twitter` model be switched for a different one?

**Comment by stephenroller** [comment]
Sure. If we do that we should update the corresponding quickstart.

**Comment by vedantpuri** [comment]
@young-k Could you close this issue if completed ?
