### ISSUE TITLE
Nightly GPU tests are broken

### ISSUE THREAD

**Issue by vedantpuri** [facebookresearch/ParlAI#2080]
As discussed [here](https://github.com/facebookresearch/ParlAI/pull/2078#issuecomment-541279469) it seems like the nightly GPU tests are broken. It can be seen in [this build](https://circleci.com/gh/facebookresearch/ParlAI/15361?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) from master that the tests are skipped since a GPU could not be found.
The last successful build for these tests on master was [here](https://circleci.com/gh/facebookresearch/ParlAI/15195#tests/containers/4) where all tests used the GPU to run to completion

**Comment by stephenroller** [comment]
It appears that the last successful one ran pytorch 1.2 and the first broken one ran pytorch 1.3. Though this may not be the problem, I estimate there's a high probability.

**Comment by vedantpuri** [comment]
That's a good catch. I looked into the command that installs torch for nightly, it is the same as that for gpu12. Upon checking circle CI, I found that consequently gpu12 also doesn't run tests that requires the GPU. Maybe for this reason in ```installtorchgpu11``` the command is ```pip3 install --progress-bar off 'torch<1.2.0'```. Should I replicate this command in gpu12 ?

**Comment by stephenroller** [comment]
Our policy is supposed to be “we support the last two versions of torch” so I want to figure out why 1.3 doesn’t work

**Comment by vedantpuri** [comment]
Yes that makes sense. I updated the installtorchgpu12 command to :```pip3 install torch>=1.2.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html``` and it seems to work as you can see [here](https://circleci.com/gh/facebookresearch/ParlAI/15432#config/containers/0). The odd thing is that in the section where torch is being installed, I see no stdout of such and was confused about that. Could you look into that and help me solve this confusion ?
