### ISSUE TITLE
Async chat with Multiple Agents in MTurk

### ISSUE THREAD

**Issue by gkaradzhov** [facebookresearch/ParlAI#2081]
I would like to have a data annotation task in MTurk, where several turkers can chat between themselves. I started modifying the multi_agent_dialogue from parlai/mturk/tasks, but I noticed a strange behaviour - the chat is synchronous. Currently, only the first turker can write a message, while the rest are blocked. Once the first worker is done, only the second one is able to write, and so on.

 Ideally, I want to simulate a real group chat, where everyone can type their message freely, but I am not sure how to do this with ParlAI interface? As far as I saw, there is a function _move_agents_to_waiting in mturk_manager, but I am not sure if modifying the core behaviour of the package is the way to go.

**Comment by JackUrb** [comment]
Hi @gkaradzhov - what you're looking for is the ability to have non-blocking acts. To use these just call `agent.act(blocking=false)` and do a none check on the return value before forwarding it to other agents.

**Comment by gkaradzhov** [comment]
Hi @JackUrb ! Yes, that's exactly what I needed. Thank you for your help, closing the issue.
