### ISSUE TITLE
wanting help for controllable dialog.

### ISSUE THREAD

**Issue by xhc19930714** [facebookresearch/ParlAI#2082]
When I ran the command python projects/controllable_dialogue/tasks/build.py as guided, there was something wrong in my PC as follows.
![image](https://user-images.githubusercontent.com/17611259/66771995-3b896d00-eeee-11e9-873e-3cd0ace3a2a2.png) It seems like there is no related file in the corresponding dir. So, where can I find the file?

**Comment by stephenroller** [comment]
I just ran the script myself and verified that it successfully downloaded. I suspect this is an issue with colons in a filename for windows, which IIRC is not supported on NTFS or other MS filesystems. ParlAI doesn't support Windows.

**Comment by xhc19930714** [comment]
Thanks, I will change another ubuntu system to have a try tomorrow.

**Comment by stephenroller** [comment]
Closing for now,  please reopen if you have issues once you're running on Ubuntu.
