### ISSUE TITLE
Hosting dialogue anotation without MTurk

### ISSUE THREAD

**Issue by gkaradzhov** [facebookresearch/ParlAI#2089]
I was wondering how can I use ParlAI in order to have a dialogue between people, without necessarily using MTurk. One caveat is that I would like to reuse part of my worlds.py and frontend functionalities both with and without MTurk. 

Ideally, I need a web application, where you can create chatrooms and give some sort of invitations or access keys to users so they can get in and start chatting. I have considered some possible scenarious on how to do this, but none of them seems ideal. 
1. To use the mturk/webapp/server.py interface, but it's only for testing and it is a bit awkward to use if several annotators have to use one computer to chat with each other.  
2. To rewrite my worlds.py and run.py in such a way, that I abstract the use of MTurkManager and wrap it with a custom class, that I can reuse in a different web application. The problem is that at this point it is a bit unclear to me, what part of the functionality I would have to rewrite and whether quality integration with both MTurk and custom web app can be achieved.

Is there another way to achieve this? Perhaps there is a ParlAI functionality that I missed, that allows this?

**Comment by emilydinan** [comment]
You might also be interested in following progress on this issue: #2079.

**Comment by stephenroller** [comment]
Marking as closed due to inactivity. Feel free to reopen if you wish to discuss more.
