### ISSUE TITLE
Document Dictionary for TFIDF Retriever

### ISSUE THREAD

**Issue by bhedayat** [facebookresearch/ParlAI#2097]
Hello,

For the TFIDF Retriever agent that is built from the Wikipedia dump, there doesnt seem to be the doc_dict in the model (https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/tfidf_retriever/tfidf_doc_ranker.py#L41)

Is it possible to get this? I would like to have the article header along with the article body and it seems that the full wikipedia dump only has the article body and not the header as well.

Similar to the DRQA github which the code is adapted from (https://github.com/facebookresearch/DrQA) they have the article header and body but their dump is from 2016-12-21 and is missing articles that are referenced in the Wizard of Wikipedia dataset.

thank you

**Comment by stephenroller** [comment]
@klshuster any idea?

**Comment by klshuster** [comment]
I'm not sure about the doc dict, but the `-t wikipedia` task is the wikipedia dump used in the Wizard of Wikipedia dataset, and all those articles have bodies and headers

**Comment by bhedayat** [comment]
Oh i see so i can use this summaries.json and the https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/tfidf_retriever/build_db.py to build the database. great thank you I will look at this!
