### ISSUE TITLE
Reproducing Poly-encoders Table 10

### ISSUE THREAD

**Issue by bkj** [facebookresearch/ParlAI#2120]
Hi --

I'm interested in reproducing the results in Table 10 of [the poly-encoder paper](https://arxiv.org/pdf/1905.01969.pdf).  I see recipes [here](https://github.com/facebookresearch/ParlAI/tree/master/projects/polyencoder) for training w/ your Reddit model, but are you able to share the parameter settings for training w/ the Devlin et al. BERT weights.

(I see the code in [parlai/agents/bert_ranker](https://github.com/facebookresearch/ParlAI/tree/master/parlai/agents/bert_ranker) but I think (?) that's a slightly older codebase.)

Thanks!
~ Ben

**Comment by klshuster** [comment]
Hi Ben,

The code you linked is in fact the correct code for using the Devlin et al BERT Weights. At the moment we do not plan on releasing such code for the Poly-encoder, however for the Bi- and Cross-encoder, below are some parameter settings we used for training with the BERT weights:

*Bi-encoder*
```
--batchsize 512 
--warmup_updates 200
--lr-scheduler-patience 1
--lr-scheduler-decay 0.4
-lr 5e-5
--history-size 20
--label-truncate 72
--text-truncate 360
--type-optimization all_encoder_layers
--bert-aggregation mean
--num-epochs 15
-veps 1.0
```

*Cross-encoder*
```
--batchsize 16
--warmup-updates 1000
--lr-scheduler-patience 1
--lr-scheduler-decay 0.4
-lr 5e-5
--history-size 20
--label-truncate 72
--text-truncate 360
--type-optimization all_encoder_layers
--num-epochs 15
-veps 1.0
--candidates inline
```

Hope that answers your question - let me know if you need additional parameters. 

If you wanted to simply train a poly-encoder via fine-tuning on the same corpora used to train BERT, you can use the same parameters specified [here](https://github.com/facebookresearch/ParlAI/tree/master/projects/polyencoder) except for `--init-model`, which you would set to `--init-model zoo:pretrained_transformers/poly_model_huge_wikito/model` - these are with weights that we obtained via pre-training on Wikipedia + Toronto books.

**Comment by stephenroller** [comment]
Closing since this looks complete. Please reopen if you have further questions.
