### ISSUE TITLE
f1 score > 1.0 

### ISSUE THREAD

**Issue by liloup1789** [facebookresearch/ParlAI#2152]
**Bug description**
When I execute the "RepeatLabelAgent" tutorial with a task (several tried), it happens that in the  FixedDialogTeacher's metrics, the "f1" metric comes to have numbers superiors to 1.0, which is impossible. 

**Reproduction steps**
I just print the FixedDialogTeacher.metrics attribute after each episode. it is a dict with several 

**Expected behavior**
Show a possible  

**Logs**
Please paste the command line output:

```
{'episode_done': True,
 'id': 'AQuA',
 'label_candidates': ('0.28 = 28 / 100 = 7 / 25\n'
                      'The remainder must be divisible by 7 .\n'
                      'The answer is D .',),
 'labels': ('0.28 = 28 / 100 = 7 / 25\n'
            'The remainder must be divisible by 7 .\n'
            'The answer is D .',),
 'text': 'Can you provide a rationale for your answer?'}
{'id': 'RepeatLabel',
 'text': '0.28 = 28 / 100 = 7 / 25\n'
         'The remainder must be divisible by 7 .\n'
         'The answer is D .'}
{'cnt': 10, 'correct': 0.0, 'correct_cnt': 10, 'bleu': 3.8286198852710296, 'bleu_cnt': 10, 'accuracy': 0.0, 'accuracy_cnt': 0, 'f1': **6.549780006898034**, 'f1_cnt': 10, 'hits@1': 0, 'hits@5': 0, 'hits@10': 0, 'hits@100': 0, 'hits@_cnt': 0}
[AQuA]: Can you provide a rationale for your answer?
[label_candidates: 0.28 = 28 / 100 = 7 / 25
The remainder must be divisible by 7 .
The answer is D .]
[labels: 0.28 = 28 / 100 = 7 / 25
The remainder must be divisible by 7 .
The answer is D .]
   [RepeatLabel]: 0.28 = 28 / 100 = 7 / 25
The remainder must be divisible by 7 .
The answer is D . 
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by stephenroller** [comment]
Well that’s a bit strange. BLEU is also off...

**Comment by liloup1789** [comment]
My first guess was a final mean between the f1 score sum and the f1_ctn... but I am not sure

**Comment by stephenroller** [comment]
Oh yes, I didn't realize you were printing the metrics object directly. Yes, the metrics object is maintaining the running sums, not the means directly. (As you need to increase the numerator and denominator separately). Print the `teacher.report()` instead.

```
$ python examples/eval_model.py -m repeat_label -t aqua
[creating task(s): aqua]
[building data: /Users/roller/working/parlai/data/AQuA]
[ downloading: https://github.com/deepmind/AQuA/archive/master.zip to /Users/roller/working/parlai/data/AQuA/aqua.zip ]
Downloading aqua.zip: 0.00B [00:09, ?B/s]
unpacking aqua.zip
loading: /Users/roller/working/parlai/data/AQuA/AQuA/dev.tok.json
[ Finished evaluating tasks ['aqua'] using datatype valid ]
{'exs': 508, 'accuracy': 1.0, 'f1': 1.0, 'bleu': 0.5454}
```

**Comment by liloup1789** [comment]
Ok thanks, 
Sorry for the issue report but as I was not completely sure I prefered to mention it. 
In my opinion the  dict key could be named f1_sum or something like that to avoid confusion ;)

**Comment by stephenroller** [comment]
Yes, thank you for reporting.

I plan on changing the behavior of that object substantially in the near future. It's best to rely on the ABI-guaranteed report function.
