### ISSUE TITLE
Never reaching epoch done in tutorial 

### ISSUE THREAD

**Issue by lpschaub** [facebookresearch/ParlAI#2153]
Use this to open other questions or issues, and provide context here.
Hello, 

I tried the tutorial of RepeatLabelAgent : 

```
from parlai.core.agents import Agent
from parlai.core.params import ParlaiParser
from parlai.core.worlds import create_task
class RepeatLabelAgent(Agent):
    # initialize by setting id
    def __init__(self, opt):
        self.id = 'RepeatLabel'
    # store observation for later, return it unmodified
    def observe(self, observation):
        self.observation = observation
        return observation
    # return label from before if available
    def act(self):
        reply = {'id': self.id}
        if 'labels' in self.observation:
            reply['text'] = ', '.join(self.observation['labels'])
        else:
            reply['text'] = "I don't know."
        return reply
if __name__ == '__main__':
    parser = ParlaiParser()
    opt = parser.parse_args()
   agent = RepeatLabelAgent(opt)
    world = create_task(opt, agent)
    for _ in range(10):
        world.parley()
        teacher = world.get_agents()[0]
        print(teacher.getID())
        print(world.display())
        if world.epoch_done():
            print('EPOCH DONE')
            break`
```
With the command

`python repeat.py -t babi:task1k:1`
but I can never reach the epoch_done() condition. 

I guessed that it happened in the FixedDialogTeacher() : 

```
def act(self):
         """Send new dialog message."""
         if not hasattr(self, 'epochDone'):
             # reset if haven't yet
             self.reset()
  
         # get next example, action is episode_done dict if already out of exs
         action, self.epochDone = self.next_example()
```

What is strange is that in your other tutorial with only two phrases : 

> text:hello how are you today?   labels:i'm great thanks! what are you doing?
text:i've just been biking.     labels:oh nice, i haven't got on a bike in years!

It appears to be epoch_done() True with the command : 
`python parlai/scripts/display_data.py -t fromfile:parlaiformat --fromfile_datapath /tmp/data`

So, could you help me understanding the behaviour ? 

Thanks

**Comment by stephenroller** [comment]
Yeah this behavior is extremely opaque and unfortunate.

If datatype is `train` then we do sampling with replacement, so the notion of an epoch becomes somewhat fuzzy, and that boolean never returns false. It's caused me some headaches too. I might want to change it, but I'm not sure. If you do use datatype as `train:ordered:stream` then it should behave in a more expected way.

You'll sometimes see our scripts actually manually cut things off:

https://github.com/facebookresearch/ParlAI/blob/ec33fde4eefed14402744d99a2976e3963f85779/parlai/scripts/eval_model.py#L81

https://github.com/facebookresearch/ParlAI/blob/ec33fde4eefed14402744d99a2976e3963f85779/parlai/scripts/eval_wordstat.py#L214

**Comment by liloup1789** [comment]
Ok thank you. 

So to be sure that world.epoch_done() becomes true in my tutorial script, what should I change exactly ?

**Comment by stephenroller** [comment]
Use `train:ordered` instead.
