### ISSUE TITLE
ChatServiceMessageSender should be extracted out of Manager

### ISSUE THREAD

**Issue by vedantpuri** [facebookresearch/ParlAI#2160]
Not sure if this is actually an issue or not, but since we decided to create a ```manager_utils.py``` shouldn't ```ChatServiceMessageSender``` be located there instead of its current location.

Currently the location is in ```chat_service_manager.py``` which doesn't seem right to me.

```python
class ChatServiceManager(ABC):
    class ChatServiceMessageSender(ABC):
        """ChatServiceMessageSender is a wrapper around requests that simplifies the
        the process of sending content.
        """

        @abstractmethod
        def send_read(self, receiver_id):
            pass

        @abstractmethod
        def typing_on(self, receiver_id, persona_id=None):
            pass
```

Thoughts ? @klshuster @young-k @domrigoglioso @jp848

**Comment by young-k** [comment]
I think the reason for this was to make [this](https://github.com/facebookresearch/ParlAI/pull/2104#issuecomment-549515497) as clear as possible –– we want to make sure that anyone overriding the `Manager` class overrides `MessageSender` as well. If `MessageSender` were in another file, that contract isn't immediately obvious from the code itself.
