### ISSUE TITLE
<SILENCE> for the bot

### ISSUE THREAD

**Issue by lpschaub** [facebookresearch/ParlAI#2161]
**Is your feature request related to a problem? Please describe.**

Greetings  : I was wondering if you implemented the case where the user speaks n-times in a row for example (in fb format) : 
1 good morning	hello what can i help you with today
2 i'd like to book a table with italian food	 ` <SILENCE>`

3 Hem sorry I meant chinese food	where should it be
4 in paris	how many people would be in your party

**Describe the solution you'd like**
I wonder if there is a way during the train to force the bot learning the silence
In real cases this happens a lot 

Thanks

**Comment by stephenroller** [comment]
It's something that's been considered but I'm not sure we have any solutions I really like. We usually have a `__SILENCE__` special token in a lot of datasets. You could use that for sure, and then hack the world to handle these messages specially (i.e. don't render to use).

I'm open to suggestions and defining something proper.

**Comment by liloup1789** [comment]
Hello Stephen 

Ok thanks, I will try to implement the whole pipeline with a few conversations and see with an enhanced memory network if it can be handled. 

I will report any interesting behaviour

**Comment by klshuster** [comment]
I'm closing this, please reopen if there are updates I am not aware of
