### ISSUE TITLE
Incremental decoding in TransformerDecoder

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#2164]
Right now, the transformer doesn't have any kind of incremental decoding. This means we're spending a lot of extra compute redoing attentions during beam search etc, and it would be real nice to cache computations in MultiHeadAttention where possible.

**Comment by stephenroller** [comment]
Take a look at fairseq for inspiration.

**Comment by EricMichaelSmith** [comment]
Implemented with https://github.com/facebookresearch/ParlAI/pull/2307. @stephenroller - is it okay to close this issue?
