### ISSUE TITLE
Consolidate `.valid`, `.best_valid` and `.trainstats` files

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#2169]
We're littering a lot of files in places and we could just use one. Consolidate these files all into `.trainstats`.

**Comment by dexterju** [comment]
# task 1

**Comment by dexterju** [comment]
add valid and best valid to '.trainstats'
And check if those fields are there otherwise fall back to the old way, but only store the new way.
make Todo
delete this may 2020

**Comment by stephenroller** [comment]
Fixed in #2376.
