### ISSUE TITLE
a mistake in tutorial?

### ISSUE THREAD

**Issue by Saizheng** [facebookresearch/ParlAI#218]
In the [first tutorial ](http://parl.ai/static/docs/basic_tutorial.html) where "we’ll set up the display loop.", the code is:

```
parser = ParlaiParser()
opt = parser.parse_args()

if 'task' not in opt:
    # if task not specified from the command line,
    # default to the 1000-training example bAbI task 1
    opt['task'] = 'babi:task1k:1'

agent = RepeatLabelAgent(opt)
world = create_task(opt, agent)

for _ in range(10):
    world.parley()
    print(world.display())
    if world.epoch_done():
        print('EPOCH DONE')
        break
```

But actually when I ran the code I found that, when the 'task' is not specified, 'task' key is still in opt but its value is None, so the line
```
if 'task' not in opt:
```
should be 
```
if 'task' is None:
```
?

**Comment by alexholdenmiller** [comment]
even better (I think), just removing that completely in #219

**Comment by Saizheng** [comment]
great, which forces user to learn to use "-t" option

**Comment by alexholdenmiller** [comment]
I think when I was writing the tutorial we had less sensible error messages if you forgot `-t`, too...
