### ISSUE TITLE
[codecov] The config build isn't being recognized

### ISSUE THREAD

**Issue by vedantpuri** [facebookresearch/ParlAI#2195]
As discussed with @stephenroller earlier we wanted to switch off reporting of the project, patch and diff results for codecov. But after merging #2127 these reportings have returned and hence are failing codecov's patch test on the repo.
We probably should consider looking into this and turning it off again so that the builds don't fail,
Later we can add targets that a build must satisfy to pass!

EDIT: We might also consider switching off the codecov bot comments on every PR for now!

**Comment by stephenroller** [comment]
That might be because i renamed the file, but it had looked to me like it was okay

**Comment by stephenroller** [comment]
Can you point me to an example

**Comment by vedantpuri** [comment]
For example before #2127 was merged (i.e. example when #2156 was merged) the master didn't report the codecov patch and project tests, but after 2127 it does!

Getting this from commit history on master!

**Comment by vedantpuri** [comment]
> That might be because i renamed the file, but it had looked to me like it was okay

I don't think that should be the issue since codecov allows both namings

**Comment by stephenroller** [comment]
![image](https://user-images.githubusercontent.com/31896/69260875-94ec5800-0b8e-11ea-8038-6dff172f150c.png)

**Comment by stephenroller** [comment]
If you have the bandwidth go ahead and rename the file back rq and I'll approve.
