### ISSUE TITLE
TypeError: can't pickle _thread.lock objects

### ISSUE THREAD

**Issue by carinazhang-meng** [facebookresearch/ParlAI#2231]
**Bug description**
Traceback (most recent call last):
  File "examples/train_model.py", line 17, in <module>
    TrainLoop(opt).train()
  File "d:\parlai\parlai\scripts\train_model.py", line 367, in __init__
    self.world = create_task(opt, self.agent)
  File "d:\parlai\parlai\core\worlds.py", line 1385, in create_task
    world = HogwildWorld(opt, world)
  File "d:\parlai\parlai\core\worlds.py", line 1085, in __init__
    t.start()
  File "D:\Anaconda\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects

**Reproduction steps**
python examples/train_model.py -t babi:task10k:1 -mf /tmp/babi_memnn -bs 1 -nt 4 -eps 5 -m memnn --no-cuda

**Expected behavior**
 try to train a model on it 

**Logs**
Please paste the command line output:
 stacklevel=1)
[ Main ParlAI Arguments: ]
[  batchsize: 1 ]
[  datapath: d:\parlai\data ]
[  datatype: train ]
[  download_path: d:\parlai\downloads ]
[  hide_labels: False ]
[  image_mode: raw ]
[  init_opt: None ]
[  multitask_weights: [1] ]
[  numthreads: 4 ]
[  show_advanced_args: False ]
[  task: babi:task10k:1 ]
[ ParlAI Model Arguments: ]
[  dict_class: parlai.core.dict:DictionaryAgent ]
[  init_model: None ]
[  model: memnn ]
[  model_file: /tmp/babi_memnn ]
[ Training Loop Arguments: ]
[  aggregate_micro: False ]
[  display_examples: False ]
[  eval_batchsize: None ]
[  evaltask: None ]
[  load_from_checkpoint: False ]
[  max_train_time: -1 ]
[  metrics: default ]
[  num_epochs: 5.0 ]
[  save_after_valid: False ]
[  save_every_n_secs: -1 ]
[  short_final_eval: False ]
[  validation_cutoff: 1.0 ]
[  validation_every_n_epochs: -1 ]
[  validation_every_n_secs: -1 ]
[  validation_max_exs: -1 ]
[  validation_metric: accuracy ]
[  validation_metric_mode: None ]
[  validation_patience: 10 ]
[  validation_share_agent: False ]
[ Tensorboard Arguments: ]
[  tensorboard_log: False ]
[ PytorchData Arguments: ]
[  batch_length_range: 5 ]
[  batch_sort_cache_type: pop ]
[  batch_sort_field: text ]
[  numworkers: 4 ]
[  pytorch_context_length: -1 ]
[  pytorch_datapath: None ]
[  pytorch_include_labels: True ]
[  pytorch_preprocess: False ]
[  pytorch_teacher_batch_sort: False ]
[  pytorch_teacher_dataset: None ]
[  pytorch_teacher_task: None ]
[  shuffle: False ]
[ Dictionary Loop Arguments: ]
[  dict_include_test: False ]
[  dict_include_valid: False ]
[  dict_maxexs: -1 ]
[  log_every_n_secs: 2 ]
[ ParlAI Image Preprocessing Arguments: ]
[  image_cropsize: 224 ]
[  image_size: 256 ]
[ MemNN Arguments: ]
[  embedding_size: 128 ]
[  hops: 3 ]
[  memsize: 32 ]
[  position_encoding: False ]
[  time_features: True ]
[ TorchAgent Arguments: ]
[  add_p1_after_newln: True ]
[  delimiter:
 ]
[  embedding_projection: random ]
[  embedding_type: random ]
[  fp16: False ]
[  gpu: -1 ]
[  history_size: -1 ]
[  interactive_mode: False ]
[  label_truncate: None ]
[  no_cuda: True ]
[  person_tokens: False ]
[  rank_candidates: False ]
[  split_lines: True ]
[  text_truncate: None ]
[  truncate: -1 ]
[  use_reply: label ]
[ Optimizer Arguments: ]
[  adam_eps: 1e-08 ]
[  betas: (0.9, 0.999) ]
[  gradient_clip: 0.1 ]
[  learningrate: 1 ]
[  momentum: 0 ]
[  nesterov: True ]
[  nus: (0.7,) ]
[  optimizer: sgd ]
[  weight_decay: None ]
[ Learning Rate Scheduler: ]
[  lr_scheduler: reduceonplateau ]
[  lr_scheduler_decay: 0.5 ]
[  lr_scheduler_patience: 3 ]
[  update_freq: 1 ]
[  warmup_rate: 0.0001 ]
[  warmup_updates: -1 ]
[ TorchRankerAgent: ]
[  candidates: inline ]
[  cap_num_predictions: 100 ]
[  encode_candidate_vecs: True ]
[  encode_candidate_vecs_batchsize: 256 ]
[  eval_candidates: inline ]
[  fixed_candidate_vecs: reuse ]
[  fixed_candidates_path: None ]
[  ignore_bad_candidates: False ]
[  inference: max ]
[  init_model: None ]
[  rank_top_k: -1 ]
[  repeat_blocking_heuristic: True ]
[  topk: 5 ]
[  train_predict: False ]
[ Dictionary Arguments: ]
[  bpe_debug: False ]
[  dict_endtoken: __end__ ]
[  dict_file: None ]
[  dict_initpath: None ]
[  dict_language: english ]
[  dict_lower: False ]
[  dict_max_ngram_size: -1 ]
[  dict_maxtokens: -1 ]
[  dict_minfreq: 0 ]
[  dict_nulltoken: __null__ ]
[  dict_starttoken: __start__ ]
[  dict_textfields: text,labels ]
[  dict_tokenizer: re ]
[  dict_unktoken: __unk__ ]
[ Current ParlAI commit: 3a5de86667816abbdb0f08049c86d1e2c3aff03e ]
[ building dictionary first... ]
[ dictionary already built .]
[ no model with opt yet at: /tmp/babi_memnn(.opt) ]
Dictionary: loading dictionary from /tmp/babi_memnn.dict
[ num words =  26 ]
Total parameters: 46080
Trainable parameters:  46080
[creating task(s): babi:task10k:1]
[loading fbdialog data:d:\parlai\data\bAbI\tasks_1-20_v1-2\en-valid-10k-nosf\qa1_train.txt]
Traceback (most recent call last):
  File "examples/train_model.py", line 17, in <module>
    TrainLoop(opt).train()
  File "d:\parlai\parlai\scripts\train_model.py", line 367, in __init__
    self.world = create_task(opt, self.agent)
  File "d:\parlai\parlai\core\worlds.py", line 1385, in create_task
    world = HogwildWorld(opt, world)
  File "d:\parlai\parlai\core\worlds.py", line 1085, in __init__
    t.start()
  File "D:\Anaconda\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects
D:\Anaconda\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
D:\Anaconda\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
D:\Anaconda\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)

D:\ParlAI>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Anaconda\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
Output goes here
```

**Comment by carinazhang-meng** [comment]
and the version of python is 3.6.5
on Windows10

**Comment by stephenroller** [comment]
Thanks for filing. We don’t support windows at this time, sorry. Please try a virtual machine.
