### ISSUE TITLE
Retire projects/image_chat/interactive.py

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#2233]
It contains too much copy pasta with the regular interactive web. We should find a way to improve this.

**Comment by jnoelvictorino** [comment]
I'd like to contribute to refactoring this.
I searched in the repo on how to start with an interactive version of ImageChat agents, but I cannot find it.

Are there any tips for starting an interactive (browser or cmd) for ImageChat agents? 
For example, adding an image path for cmd or (like in this project) uploading the image via the browser.

**Comment by stephenroller** [comment]
Contributions would be welcome.

I believe there's an interactive chat script for the ImageChat project, and we could start from there.

**Comment by klshuster** [comment]
given the divergence of `interactive_web` and the age of `image_chat`, i'm closing this issue
