### ISSUE TITLE
ImportError: cannot import name 'str2class'

### ISSUE THREAD

**Issue by hwaranlee** [facebookresearch/ParlAI#224]
When I just downloaded the new verrsion and ran the drqa model as follow, I faced with an ImportError

> 
$ python examples/train_model.py -m drqa -t squad -bs 32 -mf /tmp/model
Traceback (most recent call last):
  File "examples/train_model.py", line 30, in <module>
    import build_dict
  File "/data2/hwaranlee/xxx/examples/build_dict.py", line 10, in <module>
    from parlai.core.params import ParlaiParser, str2class
ImportError: cannot import name 'str2class'

**Comment by alexholdenmiller** [comment]
That command works on my machine, are you up to date with any current changes and did you run `python setup.py develop` in the ParlAI repo directory?

**Comment by hwaranlee** [comment]
I resolved the problem by deleting the file '~/anaconda3/lib/python3.6/site-packages/parlai.egg-link'.
And run again `python setup.py develop`
The reason was that the new parlai version confilcted with the previous one.
Thanks!
