### ISSUE TITLE
Teachers for chinese datasets

### ISSUE THREAD

**Issue by MrRace** [facebookresearch/ParlAI#2241]
Hope to add some Chinese datasets ~  It seems only English datasets be supported~
Thanks a lot!

**Comment by stephenroller** [comment]
I would like that too. There's no reason parlai couldn't support chinese, but our own research currently is english centric. I would very happily accept PRs for chinese datasets, but I don't have any on the roadmap right now. Are there specific ones you'd want?

**Comment by MrRace** [comment]
Maybe add some Chinese Machine reading comprehension dataset like CMRC (Chinese Machine Reading Comprehension [2018](https://github.com/ymcui/cmrc2018) or [2019)](https://github.com/ymcui/cmrc2019)  and [DuReader](https://github.com/baidu/DuReader)

**Comment by dcsan** [comment]
@MrRace are there any dialog corpus in Chinese you know of?

For spacy chinese model they're working with OntoNotes
https://github.com/explosion/spaCy/issues/4695#issuecomment-569731015

**Comment by stephenroller** [comment]
We just added C3, which is a reading comprehension dataset, which is in Chinese. It's not dialogue, but it's a start! #2665
