### ISSUE TITLE
Running into memory errors while running example interactive script on convai2

### ISSUE THREAD

**Issue by coderkhaleesi** [facebookresearch/ParlAI#2250]
**Bug description**
I am running into RAM memory allocation errors when I am trying to run the example for convai2 dialog task using the transformer model. My server has 2 CPUs with 16GB RAM. I couldn't find the specifications required to run tasks anywhere. Also, encoding the candidates is taking a lot of time. Any command-line arguments to help speed it up?

**Reproduction steps**
 python3 examples/interactive.py -mf zoo:pretrained_transformers/model_poly/model -t convai2

**Expected behavior**
As I ran seq2seq model, it worked pretty fast. I understand BERT has a lot of parameters, but since I was running a pre-trained model, I suspected it to work even on 16GB RAM. Also, encoding the candidates taking a lot of time is delaying a lot. I couldn't find any information on how to work around this.
And I am planning to use ParlAI for my research. But if pre-trained models require so much memory, I am not sure how to fine-tune them?

**Logs**

[ Vectorizing fixed candidate set (1665 batch(es) of up to 512) ]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 1665/1665 [01:02<00:00, 26.78it/s] **_-> This took a lot of time_**
Traceback (most recent call last):
  File "examples/train_model.py", line 17, in <module>
    TrainLoop(opt).train()
  File "/home/tanya/ParlAI/parlai/scripts/train_model.py", line 366, in init
    self.agent = create_agent(opt)
  File "/home/tanya/ParlAI/parlai/core/agents.py", line 747, in create_agent
    model = model_class(opt)
  File "/home/tanya/ParlAI/parlai/agents/transformer/transformer.py", line 187, in init
    super().init(opt, shared)
  File "/home/tanya/ParlAI/parlai/core/torch_ranker_agent.py", line 193, in init
    self.set_fixed_candidates(shared)
  File "/home/tanya/ParlAI/parlai/core/torch_ranker_agent.py", line 890, in set_fixed_candidates
    vecs = self._make_candidate_vecs(cands)
  File "/home/tanya/ParlAI/parlai/core/torch_ranker_agent.py", line 946, in _make_candidate_vecs
    [cand_vecs], pad_idx=self.NULL_IDX, dtype=cand_vecs[0].dtype
  File "/home/tanya/ParlAI/parlai/utils/misc.py", line 1017, in padded_3d
    output = torch.full((a, b, c), pad_idx, dtype=dtype)
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 4274695392 bytes. Error code 12 (Cannot allocate memory)
```
Output goes here
```

**Additional context**
Looking through the documentation, it is very well mentioned what to expect, but I have trouble finding certain specifications like why it's taking so much time for the candidates to encode (in transfomer model). I get that it's a model feature and not really related to ParlAI, but any help in terms of speedup (like server specs) or command-line arguments will be appreciated very much.

**Comment by stephenroller** [comment]
That particular bit generally depends on having a GPU to do it quickly. Otherwise it can take like 6-10 hours on a laptop, but like <2 min with a GPU. It looks like you've done it already though, so that's good.

I can comfortably run the polyencoder model in interactive mode on my laptop which has 16gb of RAM, so I think it should be okay.

However, you absolutely will not succeed at fine tuning these models without access to at least one GPU. Realistically, only deployment of pretrained models is possible on CPU.

The only thing I'm not sure about is why `_fixed_candidate_vecs` doesn't obey the `--encode-candidate-vecs-batchsize` flag. @klshuster, @dexterju any idea? Honestly I'm a bit confused why TRA has both `_make_candidate_encs` and `_make_candidate_vecs`, and what their difference is.

**Comment by coderkhaleesi** [comment]
Thanks @stephenroller . I am trying to understand the transformer model and how it's encoding to better understand this. Please let me know if you have any info on this.

**Comment by klshuster** [comment]
I am not entirely sure why the command you pasted would be vectorizing (1665 * 512) candidates; the command should only vectorize ~130k cands. 

@stephenroller  `_make_candidate_vecs` is for vectorzing the candidates (text to tokens), `_make_candidate_encs` is for encoding them (tokens to embeddings), I've never run into any issue with the vectorization hence why the it does not obey the `encode-candidate-vecs-batchsize` flag  (which controls for _encoding_ the _vectors_)

**Comment by stephenroller** [comment]
I'd refer you to Kurt's excellent paper on [PolyEncoders](https://arxiv.org/abs/1905.01969).

**Comment by coderkhaleesi** [comment]
@stephenroller Thanks a lot for your help :)
