### ISSUE TITLE
Use AWS EC2 instead of heroku for MTurk

### ISSUE THREAD

**Issue by jojonki** [facebookresearch/ParlAI#2258]
Hi there,

I am a dialog researcher and thank you for this great ParlAI project.

**Is your feature request related to a problem? Please describe.**
ParlAI has an ability to use Amazon Mechanical Turk easily, and I am developing my mturk project. Currently mturk project uses heroku as a web hosting service. However, I am not allowed to use heroku because of my company's policy.

**Describe the solution you'd like**
It would be very nice if I could choose a web hosting service. In my case, I would like to use an AWS EC2 instance instead of heroku. 

**Additional context**
If ParlAI team does not have the plan, I need to modify the code by myself. Though, I am not an expert of heroku, ec2, and react. Do you think it would be hard task? I would like to hear your opinion.
https://github.com/facebookresearch/ParlAI/blob/master/parlai/mturk/core/server_utils.py

Thank you.

**Comment by JackUrb** [comment]
Hi @jojonki. It's _possible_ to launch tasks on an ec2 instance by setting up a legacy task (with the legacy_2018 folder of MTurk) and then using the `--local` flag (for which you'll have to pore through the code to understand the functionality of because the documentation wasn't finished for local). This would let you run the task from an ec2 instance, but I can't estimate how much work that setup is going to be. 

I'm also unable to further support trying to integrate anything into ParlAI-MTurk, as I'm currently using most of my bandwidth building a new crowdsourcing framework from the ground up (one that *will* have easy support for launching via other hosting services). Sorry I don't have better news to share at the moment.

**Comment by jojonki** [comment]
Hi @JackUrb .
Thank you for your help! I am trying to use `--local` on an ec2, though, facing some problems.
I show you a procedure for reproducing. Could you take a look and give me some comments?


## Modifications
- [at `serveer_utils.py`](https://github.com/facebookresearch/ParlAI/blob/master/parlai/mturk/core/server_utils.py#L528)
I found that `hit_config.json` was generated under `parlai/mturk/tmp`. So I replaced the line with the correct path.
```
--- a/parlai/mturk/core/server_utils.py
+++ b/parlai/mturk/core/server_utils.py
     task_directory_path = os.path.join(local_server_directory_path, task_directory_name)
     sh.mv(os.path.join(local_server_directory_path, 'html'), task_directory_path)

-    hit_config_file_path = os.path.join(parent_dir, 'hit_config.json')
+    hit_config_file_path = os.path.join('/home/ubuntu/ParlAI/parlai/mturk/tmp', 'hit_config.json')
```

- [at `server.js`](https://github.com/facebookresearch/ParlAI/blob/master/parlai/mturk/core/server_legacy/server.js)
The local server needs to be a HTTPS. So I thought I need to modify the code for using HTTPS.  And placed .pem files under `parlai/mturk/core/server_legacy/` which was generated with openssl commands by myself.

```
--- a/parlai/mturk/core/server_legacy/server.js
+++ b/parlai/mturk/core/server_legacy/server.js

-const http = require('http');
+const http = require('https');


-const server = http.createServer(app);
+var options = {
+  key:  fs.readFileSync('./key.pem'),
+  cert: fs.readFileSync('./cert.pem')
+};
+const server = http.createServer(options, app);
 const wss = new WebSocket.Server({ server });
```

## Run
Then, I created a sandbox task.
```
cd parlai/mturk/tasks/personachat/personachat_chat
python run.py -nc 10 --verbose --local --sandbox --local
```

The result looks good, it showed HIT url. I opened the HIT link and the page showed a task description about personachat.
However, after I clicked the accept button of the HIT, the web page showed `Unable to initialize. We may be having issues with our chat servers. Please refresh the page, or if that isn't working return the HIT and try again later if you would like to work on this task.`.

And in my console, there were a lot of logs about disconnecting.

```
Listening on 3000
Server running locally with pid 16760.
MTurk server setup done.

Creating HITs...
You should be calling ready_to_accept_workers before create_hits to ensure that the socket is connected beforehits are added. This will be enforced in future versions.
#####chat_url https://ec2-ip-address:3000/chat_index?task_group_id=personachat_chat_yyyyyy
Link to HIT: https://workersandbox.mturk.com/mturk/preview?groupId=xxxxxxxx

Waiting for Turkers to respond... (Please don't close your laptop or put your computer into sleep or standby mode.)

Local: Setting up WebSocket...
Expiring all unassigned HITs...
Expiring all unassigned HITs...
Client connected
Server has disconnected and could not reconnect. Assuming the worst and calling the death callback. (Usually shutdown)
Server has disconnected and could not reconnect. Assuming the worst and calling the death callback. (Usually shutdown)
Server has disconnected and could not reconnect. Assuming the worst and calling the death callback. (Usually shutdown)
Server has disconnected and could not reconnect. Assuming the worst and calling the death callback. (Usually shutdown)
Server has disconnected and could not reconnect. Assuming the worst and calling the death callback. (Usually shutdown)
Server has disconnected and could not reconnect. Assuming the worst and calling the death callback. (Usually shutdown)
Server has disconnected and could not reconnect. Assuming the worst and calling the death callback. (Usually shutdown)
Server has disconnected and could not reconnect. Assuming the worst and calling the death callback. (Usually shutdown)
Server has disconnected and could not reconnect. Assuming the worst and calling the death callback. (Usually shutdown)
Server has disconnected and could not reconnect. Assuming the worst and calling the death callback. (Usually shutdown)
Server has disconnected and could not reconnect. Assuming the worst and calling the death callback. (Usually shutdown)
Server has disconnected and could not reconnect. Assuming the worst and calling the death callback. (Usually shutdown)
Server has disconnected and could not reconnect. Assuming the worst and calling the death callback. (Usually shutdown)
...
```

I did also the same things to `legacy_2018`. To use `legacy_2018`, I followed the commands.
```
cd parlai/mturk/
cp -r core core.bk
cp -r core.bk/legacy_2018 core/
```

**Comment by JackUrb** [comment]
You'll have to look into how to get the python `wss` connection to work. I'm pretty sure the code at the moment uses `localhost` to make the connection, and that request is made via the regular `ws` protocol. You may instead need to update it to use `wss`, or to refer to the actual hostname of your server. 

```
Unable to initialize. We may be having issues with our chat servers. Please refresh the page, or if that isn't working return the HIT and try again later if you would like to work on this task.
```
This should go away if the backend can stably connect with the server.

**Comment by jojonki** [comment]
Thank you for your advise. I modified the below to use `wss`. Though, the error is the same, `Unable to initialize. We may be having issues with our chat servers...`.
```
--- a/parlai/mturk/core/dev/react_server/dev/components/socket_handler.jsx
+++ b/parlai/mturk/core/dev/react_server/dev/components/socket_handler.jsx
@@ -454,9 +454,11 @@ class SocketHandler extends React.Component {
     let url = window.location;
     if (url.hostname == 'localhost') {
       // Localhost can't always handle secure websockets, so we special case
-      this.socket = new WebSocket('ws://' + url.hostname + ':' + url.port);
+      // this.socket = new WebSocket('ws://' + url.hostname + ':' + url.port);
+      this.socket = new WebSocket('wss://myhostserver:3000');
     } else {
-      this.socket = new WebSocket('wss://' + url.hostname + ':' + url.port);
+      // this.socket = new WebSocket('wss://' + url.hostname + ':' + url.port);
+      this.socket = new WebSocket('wss://myhostserver:3000');


--- a/parlai/mturk/core/react_server/dev/components/socket_handler.jsx
+++ b/parlai/mturk/core/react_server/dev/components/socket_handler.jsx
@@ -516,9 +516,11 @@ class SocketHandler extends React.Component {
     let url = window.location;
     if (url.hostname == 'localhost') {
       // Localhost can't always handle secure websockets, so we special case
-      this.socket = new WebSocket('ws://' + url.hostname + ':' + url.port);
+      // this.socket = new WebSocket('ws://' + url.hostname + ':' + url.port);
+      this.socket = new WebSocket('wss://myhostserver:3000');
     } else {
-      this.socket = new WebSocket('wss://' + url.hostname + ':' + url.port);
+      // this.socket = new WebSocket('wss://' + url.hostname + ':' + url.port);
+      this.socket = new WebSocket('wss://myhostserver:3000');
     }

--- a/parlai/mturk/core/server_legacy/html/core.html
+++ b/parlai/mturk/core/server_legacy/html/core.html
@@ -581,9 +581,11 @@
     window.setTimeout(function() {setting_socket = false;}, 4000);
     var url = window.location;
     if (url.hostname == 'localhost') {
-      socket = new WebSocket('ws://' + url.hostname + ':' + url.port);
+      //socket = new WebSocket('ws://' + url.hostname + ':' + url.port);
+      socket = new WebSocket('wss://myhostserver:3000');
     } else {
-      socket = new WebSocket('wss://' + url.hostname + ':' + url.port);
+      //socket = new WebSocket('wss://' + url.hostname + ':' + url.port);
+      socket = new WebSocket('wss://myhostserver:3000');
     }
```

I have also checked the connection of `wss` server by using `wscat`, and it looks good.
```
% wscat -c wss://myhostserver:3000 
Connected (press CTRL+C to quit)
>
```

Do I need to change more to use `wss`?

**Comment by JackUrb** [comment]
Sorry this is a really late response - there's something underlying all of this that isn't quite right:
```
Local: Setting up WebSocket...
Expiring all unassigned HITs...
Expiring all unassigned HITs...
Client connected
```
Seems that even if you can connect via `wss` using wscat something is causing the system to bail out sooner than that. If you happen to still be working on this project months later, you can try using `--verbose --debug` when you run to see the full output of what's going on within ParlAI.
