### ISSUE TITLE
Removing on boarding process in Wizard of Wikipedia Mturk Task

### ISSUE THREAD

**Issue by namanahuja** [facebookresearch/ParlAI#2270]
I am running the mturk task (parlai/mturk/tasks/wizard_of_wikipedia/run.py). 
But, I do not need any filtering or onboarding tasks. How can remove the task while working on an HIT such that if a worker accept the HIT, he/ she gets redirected directly to the task?

**Comment by stephenroller** [comment]
https://github.com/facebookresearch/ParlAI/blob/08160a133314bd230590507c9a15ce77ec4072f0/parlai/mturk/tasks/wizard_of_wikipedia/worlds.py#L267
