### ISSUE TITLE
No module named parlai.scripts.train

### ISSUE THREAD

**Issue by coderkhaleesi** [facebookresearch/ParlAI#2291]
**Bug description**
Even after running **python3 setup.py develop**, I am getting this error "No module named parlai.scripts.train"

**Reproduction steps**
Run
 python3 -m parlai.scripts.train -m seq2seq -t coqa -mf /tmp/model -bs 10

**Expected behavior**
Train the model without this error.

**Logs**
Please paste the command line output:
ubuntu@td-parlai-large:~/ParlAI$ python3 -m parlai.scripts.train -m seq2seq -t coqa -mf /tmp/model -bs 10
/usr/bin/python3: No module named parlai.scripts.train

```
Output goes here
```

**Additional context**
I am not sure if I should or can modify PYTHONPATH by myself. I tried removing the whole repo and running setup.py again, still didn't work.

I see that since my machine has two versions of Python, I can find the module in 2.7, but not in 3.6:

ubuntu@td-parlai-large:~/ParlAI$ python3 -m parlai.scripts.train
/usr/bin/python3: No module named parlai.scripts.train
ubuntu@td-parlai-large:~/ParlAI$ python -m parlai.scripts.train
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 462, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 472, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 428, in iter_importers
    __import__(pkg)
  File "parlai/__init__.py", line 9, in <module>
    raise RuntimeError('ParlAI requires Python 3.')
RuntimeError: ParlAI requires Python 3.

Any way to install just in python3.6?

Update: Even after removing python2.7, it didn't work.
The weird thing is
python -m parlai.scripts.interactive --model tfidf_retriever -mf zoo:wikipedia_full/tfidf_retriever/model
runs perfectly.

**Comment by stephenroller** [comment]
It's `parlai.scripts.train_model`, not `.train`. If there was a part of the docs that said `train`, please let me know where; we should update that immediately.

**Comment by coderkhaleesi** [comment]
https://www.parl.ai/docs/cli_usage.html#module-parlai.scripts.train_model

**Comment by stephenroller** [comment]
Thank you very much for reporting!
