### ISSUE TITLE
Issues with formatting data for convai2 fine-tuning and fine-tuning Wizard of wikipedia models

### ISSUE THREAD

**Issue by coderkhaleesi** [facebookresearch/ParlAI#2297]
**Bug description**
I am having trouble trying to figure out how to use pre-trained models from ParlAI and train them on a simple dialogue dataset.
I read this
https://github.com/facebookresearch/ParlAI/issues/823
which states how to finetune the convai2 model. But for fine-tuning this, do I need my data in the format of personality and history and candidates. And if yes, how do I convert a normal dialogue dataset to that format?
Also, I wanted to explore finetuning the wizard of Wikipedia models https://github.com/facebookresearch/ParlAI/tree/master/projects/wizard_of_wikipedia
There are no instructions for fine-tuning. I feel like I am missing something.

**Reproduction steps**

**Expected behavior**

**Logs**

```
Output goes here
```

**Additional context**
I am trying out ParlAI for a chatbot task and want to know how to use the pre-trained models and fine-tune them.

**Comment by stephenroller** [comment]
Generally you fine tune models by supplying an `--init-model` argument to train_model. You also will generally need to exhaustively supply a list of additional flags that were set in the original model. This aspect is not very user friendly, but we have plans to improve that over the next few months (#2177).

Here's an example of a recently trained run I did from a pretrained model of my own:
```
python -u examples/train_model.py -t convai2 -veps 0.25 --model transformer/generator --init-model /path/to/pretrained/model/model --dict-tokenizer bpe --dict-lower True -esz 512 --optimizer adamax -lr 1e-05 --lr-scheduler reduceonplateau -bs 16 --dropout 0.1 --attention-dropout 0.0 --relu-dropout 0.0 --n-heads 16 --n-layers 8 --n-positions 512 --text-truncate 512 --label-truncate 128 --ffn-size 2048 --gradient-clip 0.1 --validation-metric ppl --validation-metric-mode min --validation-patience 10 --log-every-n-secs 10 --skip-generation true --variant xlm --activation gelu --embeddings-scale true -ttim 41400 --load-from-checkpoint true --learn-positional-embeddings true --save-after-valid true --fp16 false --betas 0.9,0.999 --warmup-updates 2000 --model-file myfinetunedmodel/model
```

Another example is in the [poly-encoder readme](https://github.com/facebookresearch/ParlAI/tree/master/projects/polyencoder#bi-encoder)

**Comment by coderkhaleesi** [comment]
Thanks @stephenroller . I will try using what you have recommended.

And my other doubt is how to structure the data? Is there any script that can get the data in the needed format?

**Comment by stephenroller** [comment]
Hmm, I'm not sure how to address that. It's super dependent on what you're trying to do. You can run `display_data.py -t wizard_of_wikipedia` to see what sort of fields are in the messages coming from the teacher, that your dataset would need to implement.
