### ISSUE TITLE
chosen_topic_to_passage.json file not found error when trying to run WoW interactive script (end2end)

### ISSUE THREAD

**Issue by coderkhaleesi** [facebookresearch/ParlAI#2298]
**Bug description**
Trying to interact with the pretrained WoW model using this command:
CUDA_VISIBLE_DEVICES=2 python3 examples/interactive.py -m projects:wizard_of_wikipedia:interactive_end2end -t wizard_of_wikipedia

I am getting following errors.

**Reproduction steps**
Run 
CUDA_VISIBLE_DEVICES=2 python3 examples/interactive.py -m projects:wizard_of_wikipedia:interactive_end2end -t wizard_of_wikipedia

**Expected behavior**
Runs without errors

**Logs**

[ Loading existing model params from /data4/u7043565/ParlAI/ParlAI/data/models/wizard_of_wikipedia/end2end_generator/model ]
[ warning: overriding opt['remove_title'] to False (previously: True )]
/data4/u7043565/ParlAI/ParlAI/parlai/core/agents.py:595: UserWarning: WARNING: Neither the specified dict file (test_ret.dict) nor the `model_file`.dict file (/data4/u7043565/ParlAI/ParlAI/data/models/wikipedia_full/tfidf_retriever/model.dict) exists, check to make sure either is correct. This may manifest as a shape mismatch later on.
  'on.'.format(old_dict_file, new_opt['dict_file'])
2019-12-20 15:15:08,187: [ Loading /data4/u7043565/ParlAI/ParlAI/data/models/wikipedia_full/tfidf_retriever/model.tfidf ]
Traceback (most recent call last):
  File "examples/interactive.py", line 19, in <module>
    interactive(opt, print_parser=parser)
  File "/data4/u7043565/ParlAI/ParlAI/parlai/scripts/interactive.py", line 69, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "/data4/u7043565/ParlAI/ParlAI/parlai/core/agents.py", line 747, in create_agent
    model = model_class(opt)
  File "/data4/u7043565/ParlAI/ParlAI/projects/wizard_of_wikipedia/interactive_end2end/interactive_end2end.py", line 35, in __init__
    self._set_up_retriever(opt)
  File "/data4/u7043565/ParlAI/ParlAI/projects/wizard_of_wikipedia/interactive_end2end/interactive_end2end.py", line 83, in _set_up_retriever
    with open(wiki_map_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data4/u7043565/ParlAI/ParlAI/data/models/wizard_of_wikipedia/full_dialogue_retrieval_model/chosen_topic_to_passage.json'

```
Output goes here
```

**Additional context**
Ran 
CUDA_VISIBLE_DEVICES=2 python3 examples/eval_model.py -bs 64 -t wizard_of_wikipedia:generator:random_split -mf models:wizard_of_wikipedia/end2end_generator/model
before the interactive command so that if the model isnt getting downloaded, it does with this command. But still getting the error.
The other script - Interactive retrieval works fine.

**Comment by stephenroller** [comment]
Thanks for filing.

@emilydinan this looks like a dead path to the old retrieval model. Do you know what it should be corrected to?

**Comment by klshuster** [comment]
closing, please reopen if this is still an issue
