### ISSUE TITLE
Generalized teacher test

### ISSUE THREAD

**Issue by EricMichaelSmith** [facebookresearch/ParlAI#2304]
**Is your feature request related to a problem? Please describe.**
We've started to create tests for some teachers, such as [test_empathetic_dialogues.py](https://github.com/facebookresearch/ParlAI/blob/master/tests/tasks/test_empathetic_dialogues.py) for the EmpatheticDialogues teacher. Since we'll likely want to test many of the same things across all of our teachers, it'd be good to create a generalized teacher test in order to eliminate repetitive and boilerplate code across many similar teacher tests.

**Describe the solution you'd like**
One way to do this would be to create the following two scripts:
1. A setup script that someone can run to print the following for a given teacher:
  a. The result of `Teacher.get()` for some specified example
  a. The number of episodes and examples returned by the teacher, for all combinations of values of a specified set of flags
1. A generalized teacher test script that will loop through all supported teachers and, for each teacher, check its sample `.get()` outputs and episode/example counts against the results of the first script

**Describe alternatives you've considered**
Separate test scripts for all teachers, which would likely be very repetitive

**Comment by stephenroller** [comment]
I still like this idea; I think we can just subsume it within teacher mocking.
