### ISSUE TITLE
Can't Launch personachat_chat task?

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#2309]
Hello, 

When I try to run the task from a freshly cloned repository, I get this error:

```
Traceback (most recent call last):
  File "run.py", line 147, in <module>
    main()
  File "run.py", line 87, in main
    mturk_manager.create_hits()
  File "/home/jarnold9/ParlAI/parlai/mturk/core/mturk_manager.py", line 1727, in create_hits
    qualifications=qualifications,
  File "/home/jarnold9/ParlAI/parlai/mturk/core/mturk_manager.py", line 1659, in create_additional_hits
    qualifications = self.get_qualification_list(qualifications)
  File "/home/jarnold9/ParlAI/parlai/mturk/core/mturk_manager.py", line 1646, in get_qualification_list
    shared_utils.print_and_log('Qualifications are not set in sandbox mode.')
TypeError: print_and_log() missing 1 required positional argument: 'message'
```

Is this to do with the latest version of the repository, or something wrong with my installation?

I ran `python3 setup.py develop` in the root of the `ParlAI` folder.

Thanks,
Josh

**Comment by stephenroller** [comment]
Can you share what command you ran?

**Comment by josharnoldjosh** [comment]
`sudo python3 run.py`

**Comment by josharnoldjosh** [comment]
However, I realized when I run without the sudo it says I've reached my limit of concurrent apps on Heroku, however, I have deleted all my apps... not sure what is happening exactly

**Comment by stephenroller** [comment]
The sudo thing sounds like a failure from something being forcefully installed incorrectly. We recommend you install ParlAI into a virtualenv or conda environment.

As for the real issue, it looks like #2276 caused it. @emilydinan can you check on this?

**Comment by josharnoldjosh** [comment]
I think that's it! Aside from that, there is another issue I just found:

```Creating jarnold9@ad3.ucdavis.edu-e4c9a... !
 ▸    Name must start with a letter, end with a letter or digit and can only contain lowercase letters, digits, and dashes.```

My username is jarnold9@ad3.ucdavis.edu and the @ is not aloud in heroku apps.

**Comment by josharnoldjosh** [comment]
I actually think there may be another issue... @2321
