### ISSUE TITLE
import path problems with data examples

### ISSUE THREAD

**Issue by dcsan** [facebookresearch/ParlAI#2315]
**Bug description**
import paths don't work as expected

**Reproduction steps**
If i try to run any code from the top level the import fails.

```
python examples/display_data.py -t personachat
Traceback (most recent call last):
  File "examples/display_data.py", line 13, in <module>
    from parlai.scripts.display_data import display_data, setup_args
ModuleNotFoundError: No module named 'parlai'
```
I can fix this by moving the file to the project root directory:

```
cp examples/display_data.py .
(venv) ➜  ParlAI git:(master) ✗ python display_data.py -t personachat

```

now it runs fine.

Is there some `sys.path` dependency that is specific to the system or method of install?

**Comment by emilydinan** [comment]
Did you run this command from your ParlAI folder? Did you follow the steps listed [here](https://github.com/facebookresearch/ParlAI), in particular `cd ~/ParlAI; python setup.py develop`?

**Comment by stephenroller** [comment]
Yes, you forgot to run `python setup.py develop`. Closing, but repoen if you have further questions.
