### ISSUE TITLE
Remaining slow unit tests

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#2338]
Following up from #2327, here are a few possible improvements that could be done to unit tests to bring them to sub 5 minutes:

- there's a test_context_blocking and test_beam_blocking. Both of those train a model to get 100% performance on a custom task, and then use blocking to ensure performance degrades in an expected manner. These are also somewhat flaky. By moving them to pretrained models (distributed with the other unit test models), we could remove the flakiness and speed up their inference from ~50s to well under 10.
- Deleting the pytorch data teacher tests
- ?

**Comment by Shandilya21** [comment]
Hi, @stephenroller I am interested to solve this problem? Can I do mentioned task for improvement?

**Comment by stephenroller** [comment]
Absolutely! Thanks! If you find that you need to distribute some model files, we’ll have to upload them for you, but won’t be a problem.

**Comment by Shandilya21** [comment]
@stephenroller Okay, I have started the work and will raise PR soon. Thanks

**Comment by Shandilya21** [comment]
Hi, @stephenroller While I am looking for test `text_context_blocking` and `test_beam_blocking`, can you tell me the path for these function definitions as I didn't find these in `test`. I can move that into the pre-trained model for fast test performance.

Thanks and I am looking for your comment.

**Comment by stephenroller** [comment]
https://github.com/facebookresearch/ParlAI/blob/b4a442018d1a46f9374547ef0a9b8134b7bb4944/tests/test_transformers.py#L305
https://github.com/facebookresearch/ParlAI/blob/b4a442018d1a46f9374547ef0a9b8134b7bb4944/tests/test_transformers.py#L396
