### ISSUE TITLE
Ordering in which HITS are assigned in Multi-Agent Dialog

### ISSUE THREAD

**Issue by sivareddyg** [facebookresearch/ParlAI#236]
Hi ParlAI team,

Thanks for making this great resource open source. I am trying to understand how ParlAI works in Multi-Agent Dialog scenario when two agents are Mechanical Turkers. Let's say I have 500 tasks, 2 human agents, which means 1000 hits. MTurk randomly assigns these hits to turkers. Do you ensure hits belonging to the same task to be picked with high frequency than any two random hits? If this is not possible in the default setup, can you point to the particular bits that ensure this. How bad is the wait time in general?

Thanks a lot,
Siva

**Comment by yf225** [comment]
Hi Siva,

Thanks for reaching out to us. We just pushed a commit to the `mturk_improvements` branch to address this problem and now the system will first allocate workers to HITs belonging to the same task / conversation. Please feel free to check it out and let us know if there is anything else missing. 

Thanks,
Will

**Comment by sivareddyg** [comment]
That was quick @yf225, thank you! I will close this for now and reopen if it doesn't work. I will wait until after ACL to give an update.
