### ISSUE TITLE
[MTurk] Can ParlAI be used to collect the speech dialog data?

### ISSUE THREAD

**Issue by zhuang-li** [facebookresearch/ParlAI#2361]
Now from the tutorial, I can see ParlAI can be used to collect the text conversations. But I wonder whether I could use the ParlAI to collect the speech dialog. I see that ParlAI could integrate the Facebook messenger. And Facebook messenger could be used for real-time speech conversation. So does that mean I could also collect the speech data via ParlAI?

**Comment by stephenroller** [comment]
Sure, at a certain point it’s just serving a webpage to the Turkers. You could use HTML5 to [get an upload](https://www.html5rocks.com/en/tutorials/getusermedia/intro/) from the user’s microphone. I’m not sure how things would change on the backend though.

**Comment by zhuang-li** [comment]
@stephenroller Thank you! If it is like this, this might not a huge modification. I can change the frontend. 
And I guess ParlAI is using the external question API of Amazon Turk. May I ask where the uploaded data would be? Would the data be sent back to the Amazon Turk or the Heroku?

**Comment by stephenroller** [comment]
ParlAI sets up an iframe which is shown to Turkers. The data will be sent back to your computer VIA Heroku, which mostly acts as a proxy.

**Comment by zhuang-li** [comment]
Thank you. I will try first to see if I can make the Turkers send their audios to my computer.

**Comment by stephenroller** [comment]
@jackurb you foresee any issues with a file transmission via PMT?

**Comment by JackUrb** [comment]
Sorry I thought I had answered this one! No, we've even run tasks internally that have asked for this kind of thing before. The audio can be attached as data to a message and then saved to disk from a world.
