### ISSUE TITLE
Modified Wizard of Wikipedia in live mode

### ISSUE THREAD

**Issue by namanahuja** [facebookresearch/ParlAI#2365]
I have made some UI code modifications to the Wizard of Wikipedia. Everything works fine in the sandbox. But, when I use the --live flag to run the experiment, the experiment does not load up after accepting the task.

**Comment by namanahuja** [comment]
The run_conversation function does not get called (run.py)

**Comment by stephenroller** [comment]
It's hard to tell what's wrong -- you could've made any changes. That said, when I've experienced that behavior, it's typically in the form of a javascript crash, often because a field was missing from the data I sent to the client.

Definitely check your javascript console.

**Comment by namanahuja** [comment]
Thanks for the response. I don't think it is due to UI changes. Due to the nature of my experiment, I changed the line     mturk_agent_ids = [**APPRENTICE, WIZARD**] to  mturk_agent_ids = [**WIZARD**]. 
This works fine in the sandbox. The sent messages become a part of the message thread.


/parlai/mturk/tasks/wizard_of_wikipedia/run.py

**Comment by stephenroller** [comment]
I’m really not sure why it would work in sandbox and not live. Sometimes our MTurk code has some random initialization saying what role you play. Maybe you missed some other code depending on this? Does it crash in sandbox if you complete the task 5 times?

**Comment by namanahuja** [comment]
No it works perfectly in sandbox
@stephenroller

**Comment by stephenroller** [comment]
Did the original code work in sandbox but not live?

**Comment by namanahuja** [comment]
@stephenroller With this change  (mturk_agent_ids = [APPRENTICE, WIZARD] to mturk_agent_ids = [WIZARD]),  original code works in sandbox but not live

**Comment by stephenroller** [comment]
https://github.com/facebookresearch/ParlAI/blob/b541d004a04a9d8800f9be783394ddaf5c6d5bed/parlai/mturk/tasks/wizard_of_wikipedia/run.py#L211

This code pretty heavily bakes in assumptions about matching up two players. You will definitely need to be very careful to cover them all.
