### ISSUE TITLE
Couldn't input string longer than 1024？

### ISSUE THREAD

**Issue by gfgkmn** [facebookresearch/ParlAI#238]
When i use
python examples/interactive.py -m drqa -mf drqa
to evaluate my pre-trained model, i found my input length is restricted with 1024 characters.

After google, i found in python3, input thought stdin is buffed, and buff size is 1024, but i don't found any way to solve this problem.

Actually in reading comprehension task , so many sample's length are longer then 1024,  so interactive is not practical... 

Is there some solution for this question?

**Comment by gfgkmn** [comment]
Update:
I found it's not python3's limitation, it's cause MacOS kernel's restrict.
as follow:
https://superuser.com/questions/264407/macosx-10-6-7-cuts-off-stdin-at-1024-chars

Maybe it's not right place to discuss this question...

**Comment by alexholdenmiller** [comment]
@ajfisch has some familiarity with buffers, but I think the interactive mode is probably not your best bet for doing reading comprehension. You'd be better served to do this programmatically, e.g. reading from a file or otherwise. Feel free to describe your application more if you want any tips!

**Comment by ajfisch** [comment]
Turn off canonical input processing: `stty -icanon`
