### ISSUE TITLE
Assigning personal traits

### ISSUE THREAD

**Issue by bobland1** [facebookresearch/ParlAI#2387]
Is it possible for the bot to remember like bot name, age?

**Comment by stephenroller** [comment]
Depends on the bot, some do it better than others. Maintaining consistent personalities was the goal of the PersonaChat project: [arxiv](https://arxiv.org/pdf/1801.07243.pdf), [project page](https://github.com/facebookresearch/ParlAI/tree/master/projects/personachat). You can train models with it using `--task convai2`.
