### ISSUE TITLE
Converting Pre-Trained Model from CMD to API, with multiple chat functionality 

### ISSUE THREAD

**Issue by bobland1** [facebookresearch/ParlAI#2395]
I was wondering if I would be able to convert the Self-Feeding bot into an api so POST calls off to it, pass it a message and get a reply. As well as this pass a conversation id? 

Is this possible?

**Comment by stephenroller** [comment]
All models can easily be converted to an API: they API just needs to clone()` the agent if it's a new conversation, and then call observe() followed by act() to get the response. We have internal versions of this, but not really any public ones at this moment. That might change soon. [interactive_web.py](https://github.com/facebookresearch/ParlAI/blob/master/parlai/scripts/interactive_web.py) can serve as a good skeleton if you wanted to develop your own. I'd happily accept a PR that implemented it using flask.

**Comment by bobland1** [comment]
Thank you! In terms of having separate conversations, is this possible also?

**Comment by bobland1** [comment]
@stephenroller After some speaking with you via Email. Effectively my plan is to try and make a self learning chatbot that can handle multiple conversations without confusing itself. I found that the self-feeding agent works really well. 

I have the pretrained model downloaded and have tested it and it all works fine. My aim is to be able to use this pretrained model, convert it so instead of using command line, I can do a POST and retrieve a response via an API as well as passing in a conversation id to distinguish what chat the message was from.

After hours of trying to work out how I can do this, I can't seem to work it how. Are you able to assist me in this? I'd really like your support as i'd really like to be able to accomplish this

Dan

**Comment by stephenroller** [comment]
So the general structure is this:

On server start:  It loads a model into memory. You probably want to ensure the no_cuda arg is passed to it.

On initial client connect: The server creates a new `chat_id`. The original agent has `clone()` called on it and a mapping `chat_id -> agent_copy` is stored. The server tells the client its `chat_id`

When the client sends a message it also includes the `chat_id`, the server looks up the `chat_id` and gets the agent. It calls:

```python
agent_clone.observe({'text': user_message})`
response = agent_clone.act()
```

It then takes `response['text']` and returns that to the client via the transport mechanism. The client renders the response or whatever. The client does what it wants with the message and returns the loop.

A lot of this functionality already exists. We have examples of a variety of chat services like browser chat, telnet chat, etc all [here](https://github.com/facebookresearch/ParlAI/tree/master/parlai/chat_service/services). This is a rather heavy hammer, but would do things like manage the maximum number of connections, etc

**Comment by bobland1** [comment]
Currently I run
`python projects/self_feeding/interactive.py --model-file zoo:self_feeding/hh131k_hb60k_fb60k_st1k/model
`
To get the self-feeding agent to boot. 
Im guessing I would have to modify the interactive.py to be able to link this up to an API. But looking at this file. There is nowhere where it asks for the users input. 

There is a WHILE TRUE statement which I am guessing it links to. Goes off to the world.parley() and it does it all somewhere else

**Comment by bobland1** [comment]
Ahhh, alright. Why do we use the --no-cuda arg. Surely we'd want it to use a gfx card?

**Comment by stephenroller** [comment]
The interactive.py instantiates a [LocalHumanAgent](https://github.com/facebookresearch/ParlAI/blob/ae40e6326457448edccafd27bdbbb936c273f92e/parlai/agents/local_human/local_human.py#L56) which does the input in its own act. By wrapping things as an agent, it makes them transparently work with a lot of different scripts.

**Comment by bobland1** [comment]
Doing this agent_clone. Would this create seperate agents that all link up at the top so all the learning is combined higher up or are they all completely separate

**Comment by stephenroller** [comment]
No, batching is not done for you in the case of an API. You can use the graphics card if you want, but multiple clients will be trying to use it at the same time and that can cause a number of problems.

If you want efficient training, you're better doing it offline and with the train_model.py script.

**Comment by bobland1** [comment]
Alright, this has given me some good foundation. Thank you

**Comment by bobland1** [comment]
So if i was trying to connect to something which has multiple chats. Lets say a new person messages the bot, it would instantiate a new chat and if the user closes that chat it will close the agent, correct? 
Or would the agents have to be manually started so the bot can only do a certain amount of chats

**Comment by bobland1** [comment]
It looks like I should apply the flask api to the LocalHumanAgent file, but I am guessing this is wrong as we have Interactive.py and those are the files we call to interact with

**Comment by stephenroller** [comment]
> So if i was trying to connect to something which has multiple chats. Lets say a new person messages the bot, it would instantiate a new chat and if the user closes that chat it will close the agent, correct?
> Or would the agents have to be manually started so the bot can only do a certain amount of chats

Depends on what you're using. For example, in Messenger, we store the copy of the agent in memory until the user doesn't say anything for a long time, and then we clean it up. IIRC, websocket automatically destroys it on disconnect. That's kinda up to you.


> It looks like I should apply the flask api to the LocalHumanAgent file, but I am guessing this is wrong as we have Interactive.py and those are the files we call to interact with

As for the flask API and LocalHumanAgent, I'd recommend staying away from modifying LHA in this case. Because you have to deal with the multiple asynchronous clients, I think it makes more sense to manually run the observe/act like we do in [interactive_web.py](https://github.com/facebookresearch/ParlAI/blob/master/parlai/scripts/interactive_web.py)

**Comment by bobland1** [comment]
Alright, my aim will be working off the [interactive_web.py](https://github.com/facebookresearch/ParlAI/blob/master/parlai/scripts/interactive_web.py), can you link me to the messenger example mentioned above. 

Using both of these examples and combining them should work in what I am trying to achieve. 

Once I have worked it all out and started work, I will make a PR and send it your way
