### ISSUE TITLE
Adding Pre-Trained Self Feeding into Messenger Config

### ISSUE THREAD

**Issue by memologyserver** [facebookresearch/ParlAI#2401]
I am trying to connect a messenger bot to Self Feeding

> tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:  # Additional model opts go here
  debug: True
  model_file: zoo:self_feeding/hh131k_hb60k_fb60k_st1k/model
  override:
	subtasks: ['dialog', 'satisfaction'],
    interactive: True,
    interactive_task': True,
    prev_response_filter': True,
    person_tokens: False,  # SelfFeedingAgent adds person_tokens on its own
    partial_load: True,
    history_size: 2,
    eval_candidates: 'fixed',
    encode_candidate_vecs: True,
    fixed_candidates_path: cand_file,
    # Pull these from current opt dictionary
    no_cuda: opt["no_cuda"],
    fixed_candidate_vecs: opt['fixed_candidate_vecs'],
    rating_frequency: opt['rating_frequency'],
    rating_gap: opt['rating_gap'],
    rating_threshold: opt['rating_threshold'],
    request_feedback: opt['request_feedback'],
    request_rating: opt['request_rating'],
additional_args:
  page_id: 1 # configure your own page

Is this correct. Im trying to replicate the arguments that are used to build the self feeding bot.

I am using the config example from: https://parl.ai/docs/tutorial_chat_service.html
And the arguments from: https://github.com/facebookresearch/ParlAI/blob/master/projects/self_feeding/interactive.py

Am i missing anything or doing anything wrong?

**Comment by stephenroller** [comment]
I don’t see anything obviously wrong, but I didn’t check the options super carefully. Are you experiencing some sort of error or unexpected behavior?

**Comment by memologyserver** [comment]
No just wondering if i missed anything

**Comment by memologyserver** [comment]
I get a ModuleNotFoundError: No module named 'parlai' when i run
`python run.py --config-path ../../tasks/chatbot/config.yml`
i am in the messenger directory

**Comment by memologyserver** [comment]
fixed, didnt activate my virtual enviroment
