### ISSUE TITLE
interactive.py update error

### ISSUE THREAD

**Issue by sseol11** [facebookresearch/ParlAI#2402]
I updated whole parlai code, then it occurred error when I ran the projects/controllable_dialogue/interactive.py .
It was well before the update.

Here is the error message : 

.......
[  dict_initpath: None ]
[  dict_language: english ]
[  dict_lower: True ]
[  dict_max_ngram_size: -1 ]
[  dict_maxtokens: -1 ]
[  dict_minfreq: 0 ]
[  dict_nulltoken: __null__ ]
[  dict_starttoken: __start__ ]
[  dict_textfields: text,labels ]
[  dict_tokenizer: split ]
[  dict_unktoken: __unk__ ]
Enter Your Message: hi
Traceback (most recent call last):
  File "projects/controllable_dialogue/interactive.py", line 24, in <module>
    interactive(parser.parse_args(print_args=False), print_parser=parser)
  File "/home/ubuntu/ParlAI/parlai/scripts/interactive.py", line 80, in interactive
    world.parley()
  File "/home/ubuntu/ParlAI/parlai/core/worlds.py", line 344, in parley
    acts[1] = agents[1].act()
  File "/home/ubuntu/ParlAI/parlai/core/torch_agent.py", line 1799, in act
    response = self.batch_act([self.observation])[0]
  File "/home/ubuntu/ParlAI/parlai/core/torch_agent.py", line 1829, in batch_act
    'label_vec' in batch
TypeError: eq() received an invalid combination of arguments - got (str), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (str)
 * (Number other)
      didn't match because some of the arguments have invalid types: (str)

**Comment by stephenroller** [comment]
Thanks for reporting! Can you provide the full command you ran? You say it worked "before the upgrade", do you know what version you were on before?

**Comment by sseol11** [comment]
I used this command:
python projects/controllable_dialogue/interactive.py -mf models:controllable_dialogue/control_avgnidf10b10e \
-wd extrep_2gram:-3.5,extrep_nonstopword:-1e20,intrep_nonstopword:-1e20 \
--set-controls avg_nidf:7 

and the version of the previous file I ran : 
Maybe this version I ran

commit aa418701c49e8c3a912897496978d687f1897097
Author: Stephen Roller <roller@fb.com>
Date:   Wed Feb 12 17:36:30 2020 -0500

    Don't round up batchsize. (#2400)

**Comment by sseol11** [comment]
I just pasted the previous version of torch_agent.py and it still occurred the error (fp16 import error) ,so I just modified fp16 import to like the recent version on torch_agent.py:

from parlai.utils.fp16 import (
    fp16_apex_available,
    fp16_optimizer_wrapper,
    MemoryEfficientFP16Optimizer,
    MemoryEfficientFP16Adam,
    Adafactor,
)

then the problem solved.

**Comment by stephenroller** [comment]
Oh great, can you submit a patch for the fp16 stuff? And anything else you needed to change?

**Comment by stephenroller** [comment]
python projects/controllable_dialogue/interactive.py -mf models:controllable_dialogue/control_avgnidf10b10e -wd extrep_2gram:-3.5,extrep_nonstopword:-1e20,intrep_nonstopword:-1e20 --set-controls avg_nidf:7 --fp16 true

^ this fails, but only with --fp16 true. I don't think I'll fix this though, since just --fp16 false works.

Closing otherwise due to inactivity.
