### ISSUE TITLE
Training on multiple dialog corpuses

### ISSUE THREAD

**Issue by Henry-E** [facebookresearch/ParlAI#241]
I managed to get a couple of the chit chat tasks training at the same time using the seq2seq agent and the MultiWorld. Is this something that has been done much or does the different tone of dialogue in each corpus confuse the RNN?

**Comment by alexholdenmiller** [comment]
So it definitely works to run, e.g., on all of the babi tasks at once (and it gets better performance on some tasks). I haven't tried running it on multiple completely different tasks yet--performance probably varies a lot based on which ones you combine!

**Comment by Henry-E** [comment]
Ok cool, I was just curious if there were many existing examples of papers which train dialogue or other agents on multiple datasets. It seems like a great idea but this is probably more of a reddit-ml type of question I guess. Thanks
