### ISSUE TITLE
Wizard of Wikipedia retrieval model

### ISSUE THREAD

**Issue by namanahuja** [facebookresearch/ParlAI#2441]
When I run:
````python display_model.py -t wizard_of_wikipedia:generator:random_split -mf models:wizard_of_wikipedia/full_dialogue_retrieval_model/model````

I get : ModuleNotFoundError: No module named 'parlai_internal'

#2102 provides a fix to add  -m projects:wizard_of_wikipedia:wizard_transformer_ranker leading to:

RuntimeError: Error(s) in loading state_dict for TransformerMemNetModel:
	size mismatch for context_encoder.position_embeddings.weight: copying a param with shape torch.Size([1000, 300]) from checkpoint, the shape in current model is torch.Size([150, 300]).
......
......

**Comment by stephenroller** [comment]
try adding `--n-positions 1000`?

**Comment by namanahuja** [comment]
@stephenroller Adding it does not resolve the issue. I still get :

RuntimeError: Error(s) in loading state_dict for TransformerMemNetModel:
	size mismatch for context_encoder.layers.0.ffn.lin1.weight: copying a param with shape torch.Size([1200, 300]) from checkpoint, the shape in current model is torch.Size([300, 300]).
.................

**Comment by stephenroller** [comment]
It seems like it’s not inferring any arguments. Can you share your full command?

**Comment by stephenroller** [comment]
Oh I see you did. Thanks

**Comment by namanahuja** [comment]
python examples/display_model.py -t wizard_of_wikipedia -mf zoo:wizard_of_wikipedia/full_dialogue_retrieval_model/model -m projects:wizard_of_wikipedia:wizard_transformer_ranker --n-heads 6 --ffn-size 1200 --embeddings-scale False --delimiter ' __SOC__ ' --n-positions 1000 --legacy True


This works
