### ISSUE TITLE
installing parlai requirements.txt issue

### ISSUE THREAD

**Issue by salama4** [facebookresearch/ParlAI#2454]
after i cloned parlai
when i trying to "pip install -r requirements.txt"

i get problem here:
Collecting pyzmq==18.1.0
  Using cached pyzmq-18.1.0-0_py38h16f9016-cp38-cp38-win_amd64.whl (17.8 MB)

ERROR: pyzmq has an invalid wheel, multiple .dist-info directories found: pyzmq-18.1.0.dist-info, libsodium-1.0.17.dist-info

by the way: i use python==3.8.2

**Comment by stephenroller** [comment]
Looks like you have a bad cache.

**Comment by salama4** [comment]
assume i understand you correctly, i open requirements.txt file and remove this package, so all other packages installed very well, and i install this package of version pyzmq-18.0.0 , so it's installed correctly,

**Comment by stephenroller** [comment]
Try `pip install --no-cache-dir -r requirements.txt`

**Comment by salama4** [comment]
Unfortunately, the same error pop up

**Comment by stephenroller** [comment]
Hmm, I just tried bumping our CI to python 3.8. It installs just fine.

Perhaps try creating a conda environment or a new virtual env.

```bash
mkdir ~/venv
virtualenv --python=python3 ~/venv
source ~/venv/bin/activate
cd ~/ParlAI
pip install -r requirements.txt
```

**Comment by salama4** [comment]
**the issue solved by :**
`pip install --no-binary=:all: pyzmq==18.1.0`
for more information:
[https://github.com/pypa/pip/issues/1891](url)
[https://pypi.org/project/pyzmq/18.1.0/](url)
[https://pypi.org/project/pyzmq/19.0.0/](url)

**Comment by stephenroller** [comment]
Glad to hear, thanks for posting the solution!

**Comment by diskreet90** [comment]
> **the issue solved by :**
> `pip install --no-binary=:all: pyzmq==18.1.0`
> for more information:
> [https://github.com/pypa/pip/issues/1891](url)
> [https://pypi.org/project/pyzmq/18.1.0/](url)
> [https://pypi.org/project/pyzmq/19.0.0/](url)

I'm getting the same issue and get this as the output once using that command:

`ERROR: Command errored out with exit status 1: 'C:\Users\diskr\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\diskr\\AppData\\Local\\Temp\\pip-install-pj6_y23r\\pyzmq_c1668fc89c9c463f8fc399bfe92ae7fe\\setup.py'"'"'; __file__='"'"'C:\\Users\\diskr\\AppData\\Local\\Temp\\pip-install-pj6_y23r\\pyzmq_c1668fc89c9c463f8fc399bfe92ae7fe\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\diskr\AppData\Local\Temp\pip-record-h5yf6t14\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\diskr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Include\pyzmq' Check the logs for full command output.`

Any ideas?

**Comment by RahaSoleymanzadeh** [comment]
I have the same problem have been able to solve it?
