### ISSUE TITLE
how to deploy pretrained agents for conversations within python (i.e. no CLI)

### ISSUE THREAD

**Issue by rbroc** [facebookresearch/ParlAI#2472]
Hi there! 

I am trying to use ParlAI for a cognitive science project that requires chatbots interacting with humans over repeated iterations, taking into account the whole history of the conversation and storing the resulting conversations for later analysis.

For my setting, I'm mostly using pretrained models and have to use ParlAI's functionality within python (no command line). Finding out how to set up ParlAI agents and worlds from pretrained models without using CLI is proving really challenging. 

Would it be possible to request an example script or a tutorial that could pedagogically introduced uninitiated users to deploying agents for purposes that are _not_ training or fine-tuning new models?
For my case use, that'd basically include examples of how to initialize agents and worlds from pretrained models, how to set them to 'interaction' mode, how to feed them at each conversational turn with the whole previous history of the conversation, and, potentially, how to store the conversation itself (this latter point should be trivial though, once figured out the previous ones). 

I'm mostly planning on using LIGHT models, but figuring out the routine for any model would be absolutely fine.

Thank you in advance, and hope the question makes sense!

**Comment by stephenroller** [comment]
You’re not wrong, our APIs make this somewhat complicated. I’m planning on writing a very extensive tutorial in the next month, with a draft in the next couple weeks. I can email you an early copy if you’re interested in providing feedback.

**Comment by rbroc** [comment]
That would be awesome, and I'd be very happy to provide feedback!
You can reach me at roberta.rocca@austin.utexas.edu.
Thanks a lot! 😊

**Comment by DasShubhadeep** [comment]
Hi @rbroc and @stephenroller I have a similar requirement. I want to access `blender90M` model using python and without using CLI. I just want to pass text to it using my python script and get back a response.
Is this tutorial ready and can it be shared with me well?
Reach me at shubhadeepdas007@gmail.com.

Thanks in advance!

**Comment by RegisSaffi** [comment]
I would like to get that tutorial to, i have such requirement
reach me at regissaffi@gmail.com

**Comment by stephenroller** [comment]
I did write a version of the tutorial. You can find it [in this colab notebook](https://colab.research.google.com/drive/1bRMvN0lGXaTF5fuTidgvlAl-Lb41F7AD#scrollTo=KtVz5dCUmFkN). It makes it so that you can call standard scripts from python code, without going through the command line, but it's still very procedurally oriented. I think the original ask of a minimal example isn't quite there, but would love to see feedback on this colab notebook.

**Comment by delgermurun** [comment]
Hello @stephenroller,

I have a similar requirement too. Is this tutorial ready?
Please share with me (pdelgermurun@gmail.com)

Thanks!

**Comment by fandy** [comment]
I'm also interested in this. Currently I'm using Rasa (tracking conversations) together with ParlAI (training model), but it would be great if I could get rid of the Rasa part. Is this something on the roadmap for ParlAI @stephenroller ?

**Comment by stephenroller** [comment]
Yes, you can find the latest parlai colab tutorial [here](https://colab.research.google.com/drive/1bRMvN0lGXaTF5fuTidgvlAl-Lb41F7AD#scrollTo=KtVz5dCUmFkN).

**Comment by fandy** [comment]
@stephenroller I think that notebook is private, because I'm getting this:

![image](https://user-images.githubusercontent.com/19108762/103839748-1be3e480-505e-11eb-8bb0-bac76b2988cb.png)

**Comment by stephenroller** [comment]
I was able to access the notebook in an incognito window which wasn't logged into google. Can you try again, or check your google account?
