### ISSUE TITLE
Ranked knowledge in Wizard Of Wikipedia Full Dialogue Retrieval Model 

### ISSUE THREAD

**Issue by namanahuja** [facebookresearch/ParlAI#2484]
Using the command:
`python examples/display_model.py -t wizard_of_wikipedia -mf zoo:wizard_of_wikipedia/full_dialogue_retrieval_model/model -m projects:wizard_of_wikipedia:wizard_transformer_ranker --n-heads 6 --ffn-size 1200 --embeddings-scale False --delimiter ' __SOC__ ' --n-positions 1000 --legacy True
`

I can see the flattened Wikipedia 'knowledge' associated with dialogues. Is there a way it can be viewed ranked on the basis of relevance to the current turn?

**Comment by stephenroller** [comment]
You could hack the gated model to return the weights or a second copy, but reordering the fields displayed would be quite difficult I think. We generally expect that things returned by the teacher are immutable.
