### ISSUE TITLE
Tensorboard logging not working

### ISSUE THREAD

**Issue by kasanari** [facebookresearch/ParlAI#2499]
train_model.py seems to no longer properly save Tensorboard logs, at least for me.
If I run a slightly modified transformer example from the "ParlAI quickstart guide":

`python examples/train_model.py -t twitter -mf /tmp/models/tr_twitter -m transformer/ranker -bs 10 -vtim 3600 -cands batch -ecands batch --data-parallel True -tblog True`

and then start tensorboard with

`tensorboard --logdir /tmp/models/ --port 3345 --bind_all`

it errors with the message:

```
Traceback (most recent call last):
  ...
  File "tensorboard/backend/event_processing/event_file_loader.py", line 90, in __init__
    tf.compat.as_bytes(file_path), 0, tf.compat.as_bytes(""), status
TypeError: in method 'PyRecordReader_New', argument 4 of type 'TF_Status *'
```

and the following error whenever the browser interface is refreshed:

`W0324 14:26:20.398597 140376183858944 core_plugin.py:200] Unable to get first event timestamp for run tr_twitter.tensorboard: No event timestamp could be found`

I encountered this error both with my setup and a freshly cloned repository with a new conda environment.

**Comment by stephenroller** [comment]
Can you report what version of tensorboard you have? Can you confirm tensorboard is working for you outside of ParlAI?

**Comment by kasanari** [comment]
I am using Tensorboard 2.1.1. I can use Tensorboard outside ParlAI. My Python version is 3.6.10.

**Comment by stephenroller** [comment]
Thanks for the follow up.

Some additional details: I just upgraded to tensorboard 2.2 and tensorboardX 2.0 and it seems to be working fine. I confirm that I do get the `Unable to get first event timestamp for run tr_twitter.tensorboard: No event timestamp could be found` message, but only until the call to flush() happens (which happens after first validation).

Perhaps what happened was the file got closed without flushing, perhaps by an inopportune ctrl-c? Anyway, feel free to reopen if it pops up again!

**Comment by kasanari** [comment]
I was doing a lot of "ctrl-c"-ing while debugging so that was probably the cause of the issue.
