### ISSUE TITLE
Use generative agent after a ranker

### ISSUE THREAD

**Issue by Alireza-DarkMan** [facebookresearch/ParlAI#2535]
Hi 

I want to use a transformer/generator agent after transformer/biencoder to get a better generated response, but I couldn't find any sample in docs. can you help me?

**Comment by stephenroller** [comment]
This is very much the idea behind the Retrieve n Refine paper. @emilydinan  had recently implemented this for Blenderbot, and we had intentions to open source it, but I think it fell through the cracks.

- [Retrieve and Refine](https://arxiv.org/abs/1808.04776)
- [BlenderBot paper](https://arxiv.org/abs/2004.13637)
