### ISSUE TITLE
Self-Feeding Chat bot Bug Whilst Interaction

### ISSUE THREAD

**Issue by Dogy06** [facebookresearch/ParlAI#2572]
There are two issues:
1. Every two messages, the bot replies with: [SelfFeeding]: Oops! I think I messed up. What could I have said instead? no matter what I say. Is this a bug or is this intended?
2. Whenever I try the [DONE] command, the issue below pops up.

I used the pretrained model and trained my own model, both gave same results

Training command: python examples/train_model.py -t self_feeding:all --model-file /tmp/mymodel4 -ltim 5 -vtim 10 -vp 50 -m projects.self_feeding.self_feeding_agent:SelfFeedingAgent -cands batch --eval-candidates inline -histsz 2 --embedding-type fasttext_cc --embedding-size 300 --dict-maxtokens 250000 --num-epochs 500 --optimizer adamax --embeddings-scale false -bs 128 --relu-dropout 0 --attention-dropout 0 --n-heads 2 --n-layers 2 -lr 0.0025 --ffn-size 32 --lr-scheduler invsqrt --warmup-updates 500 --dia-train train_hh131k_hb60k.txt -vmt dia_acc -vmm max

Help would be greatly appreciated.
Thanks.

python projects/self_feeding/interactive.py --model-file /tmp/mymodel4 --no-cuda --request-feedback true 
[ warning: overriding opt['interactive'] to True (previously: False )]
[ warning: overriding opt['interactive_task'] to True (previously: None )]
[ warning: overriding opt['prev_response_filter'] to True (previously: False )]
[ warning: overriding opt['partial_load'] to True (previously: False )]
[ warning: overriding opt['eval_candidates'] to fixed (previously: inline )]
[ warning: overriding opt['fixed_candidates_path'] to /home/~/ParlAI/data/self_feeding/convai2_cands.txt (previously: None )]
[ warning: overriding opt['no_cuda'] to True (previously: False )]
[ warning: overriding opt['request_feedback'] to True (previously: False )]
[ Setting interactive mode defaults... ]
Dictionary: loading dictionary from /tmp/mymodel4.dict
[ num words =  25141 ]
[SelfFeeding: full interactive mode on.]
Initialized embeddings for 23672 tokens (94.2%) from fasttext_cc.
Initialized embeddings for 23672 tokens (94.2%) from fasttext_cc.
Initialized embeddings for 23672 tokens (94.2%) from fasttext_cc.
Total parameters: 18,298,093 (17,376,493 trainable)
Loading existing model parameters from /tmp/mymodel4
[ Loading fixed candidate set from /home/~/ParlAI/data/self_feeding/convai2_cands.txt ]
[ Loading fixed candidate set vectors from /tmp/mymodel4.convai2_cands.vecs ]
[ Loading fixed candidate set encodings from /tmp/mymodel4.convai2_cands.encs ]
`/home/~/.local/lib/python3.7/site-packages/torch/nn/_reduction.py:43:` UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
[creating task(s): parlai.agents.local_human.local_human:LocalHumanAgent]
Enter [DONE] if you want to end the episode, [EXIT] to quit.
[ optional arguments: ] 
[  share_word_embeddings: True ]
[ Main ParlAI Arguments: ] 
[  batchsize: 128 ]
[  datapath: /home/~/ParlAI/data ]
[  datatype: train ]
[  download_path: /home/~/ParlAI/downloads ]
[  dynamic_batching: None ]
[  hide_labels: False ]
[  image_mode: raw ]
[  init_opt: None ]
[  multitask_weights: [1] ]
[  numthreads: 1 ]
[  show_advanced_args: False ]
[  task: self_feeding:all ]
[ ParlAI Model Arguments: ] 
[  dict_class: parlai.core.dict:DictionaryAgent ]
[  init_model: None ]
[  model: projects.self_feeding.self_feeding_agent:SelfFeedingAgent ]
[  model_file: /tmp/mymodel4 ]
[ Local Human Arguments: ] 
[  local_human_candidates_file: None ]
[  single_turn: False ]
[ ParlAI Image Preprocessing Arguments: ] 
[  image_cropsize: 224 ]
[  image_size: 256 ]
[ TorchAgent Arguments: ] 
[  add_p1_after_newln: False ]
[  delimiter: 
 ]
[  embedding_projection: random ]
[  embedding_type: fasttext_cc ]
[  force_fp16_tokens: False ]
[  fp16: False ]
[  fp16_impl: apex ]
[  gpu: -1 ]
[  history_add_global_end_token: None ]
[  history_size: 2 ]
[  interactive_mode: True ]
[  label_truncate: None ]
[  no_cuda: True ]
[  person_tokens: False ]
[  rank_candidates: True ]
[  split_lines: False ]
[  text_truncate: None ]
[  truncate: 1024 ]
[  use_reply: label ]
[ Optimizer Arguments: ] 
[  adafactor_eps: [1e-30, 0.001] ]
[  adam_eps: 1e-08 ]
[  betas: [0.9, 0.999] ]
[  gradient_clip: 0.1 ]
[  learningrate: 0.0025 ]
[  momentum: 0 ]
[  nesterov: True ]
[  nus: [0.7] ]
[  optimizer: adamax ]
[  weight_decay: None ]
[ Learning Rate Scheduler: ] 
[  invsqrt_lr_decay_gamma: -1 ]
[  lr_scheduler: invsqrt ]
[  lr_scheduler_decay: 0.5 ]
[  lr_scheduler_patience: 3 ]
[  max_lr_steps: -1 ]
[  update_freq: 1 ]
[  warmup_rate: 0.0001 ]
[  warmup_updates: 500 ]
[ TorchRankerAgent: ] 
[  candidates: batch ]
[  cap_num_predictions: 100 ]
[  encode_candidate_vecs: True ]
[  encode_candidate_vecs_batchsize: 256 ]
[  eval_candidates: fixed ]
[  fixed_candidate_vecs: reuse ]
[  fixed_candidates_path: /home/~/ParlAI/data/self_feeding/convai2_cands.txt ]
[  ignore_bad_candidates: False ]
[  inference: max ]
[  init_model: None ]
[  interactive_candidates: fixed ]
[  rank_top_k: -1 ]
[  repeat_blocking_heuristic: True ]
[  return_cand_scores: False ]
[  topk: 5 ]
[  train_predict: False ]
[ Transformer Arguments: ] 
[  activation: relu ]
[  attention_dropout: 0.0 ]
[  data_parallel: False ]
[  dropout: 0.0 ]
[  embedding_size: 300 ]
[  embeddings_scale: False ]
[  ffn_size: 32 ]
[  learn_embeddings: True ]
[  learn_positional_embeddings: False ]
[  memory_attention: sqrt ]
[  model_parallel: False ]
[  n_decoder_layers: -1 ]
[  n_encoder_layers: -1 ]
[  n_heads: 2 ]
[  n_layers: 2 ]
[  n_positions: None ]
[  n_segments: 0 ]
[  normalize_sent_emb: False ]
[  output_scaling: 1.0 ]
[  reduction_type: mean ]
[  relu_dropout: 0.0 ]
[  share_encoders: True ]
[  use_memories: False ]
[  variant: aiayn ]
[  wrap_memory_encoder: False ]
[ Dictionary Arguments: ] 
[  bpe_debug: False ]
[  dict_endtoken: __end__ ]
[  dict_file: /tmp/mymodel4.dict ]
[  dict_initpath: None ]
[  dict_language: english ]
[  dict_lower: False ]
[  dict_max_ngram_size: -1 ]
[  dict_maxtokens: 250000 ]
[  dict_minfreq: 0 ]
[  dict_nulltoken: __null__ ]
[  dict_starttoken: __start__ ]
[  dict_textfields: text,labels ]
[  dict_tokenizer: re ]
[  dict_unktoken: __unk__ ]
[ BPEHelper Arguments: ] 
[  bpe_add_prefix_space: None ]
[  bpe_merge: None ]
[  bpe_vocab: None ]
[ Self Feeding Model: ] 
[  sat_head_layers: 1 ]
[  share_fee_embeddings: True ]
[  share_fee_x_encoder: True ]
[  share_fee_y_encoder: True ]
[  share_sat_embeddings: False ]
[  share_sat_encoder: False ]
[ Self-feeding Agent: ] 
[  add_double_person_tokens: False ]
[  dia_weight: 1.0 ]
[  display_sat_estimate: False ]
[  fee_weight: 1.0 ]
[  freeze_base: False ]
[  interactive: True ]
[  partial_load: True ]
[  prev_response_filter: True ]
[  prev_response_negatives: False ]
[  rating_frequency: 0.01 ]
[  rating_gap: 0.05 ]
[  rating_threshold: 0.5 ]
[  request_feedback: True ]
[  request_rating: False ]
[  sat_weight: 1.0 ]
[  subtasks: ['dialog', 'feedback', 'satisfaction'] ]
[  target_class: 0 ]
[ Self-feeding Variants: ] 
[  regex: False ]
[  uncertainty_predictor: False ]
[  uncertainty_style: gap ]
[  uncertainty_threshold: 0.5 ]
Enter Your Message: Hello!
/home/~/ParlAI/parlai/core/torch_ranker_agent.py:759: UserWarning: [ Executing eval mode with a common set of fixed candidates (n = 127712). ]
  "(n = {}). ]".format(mode, len(self.fixed_candidates))
[SelfFeeding]: helloooo ! !
Enter Your Message: How are you?
[SelfFeeding]: Oops! I think I messed up. What could I have said instead?
Enter Your Message: You did not mess up
[SelfFeeding]: Thanks! I'll try to remember that. Can you pick a new topic for us to talk about now?
Enter Your Message: Sure, how about Science?
[SelfFeeding]: not bad . how about you ?
Enter Your Message: hmmm wrong answer
[SelfFeeding]: Oops! I think I messed up. What could I have said instead?
Enter Your Message: You could have said something relating to science
[SelfFeeding]: Thanks! I'll try to remember that. Can you pick a new topic for us to talk about now?
Enter Your Message: a
[SelfFeeding]: i like to spend time with my family
Enter Your Message: b
[SelfFeeding]: Oops! I think I messed up. What could I have said instead?
Enter Your Message: c
[SelfFeeding]: Thanks! I'll try to remember that. Can you pick a new topic for us to talk about now?
Enter Your Message: d
[SelfFeeding]: what is d d ?
Enter Your Message: e
[SelfFeeding]: Oops! I think I messed up. What could I have said instead?
Enter Your Message: f
[SelfFeeding]: Thanks! I'll try to remember that. Can you pick a new topic for us to talk about now?
Enter Your Message: g
[SelfFeeding]: savage ? do you like death metal ? i know a member of martius .
Enter Your Message: [DONE]
Traceback (most recent call last):
  File "projects/self_feeding/interactive.py", line 90, in <module>
    interactive(parser.parse_args(print_args=False), print_parser=parser)
  File "projects/self_feeding/interactive.py", line 81, in interactive
    world.parley()
  File "/home/~/ParlAI/parlai/core/worlds.py", line 342, in parley
    acts[1] = agents[1].act()
  File "/home/~/ParlAI/projects/self_feeding/self_feeding_agent.py", line 324, in act
    positivity = self.predict_satisfaction(self.observation)
  File "/home/~/ParlAI/projects/self_feeding/self_feeding_agent.py", line 732, in predict_satisfaction
    prob = self.model.score_satisfaction(observation['text_vec'].reshape(1, -1))
  File "/home/~/ParlAI/projects/self_feeding/modules.py", line 148, in score_satisfaction
    return torch.sigmoid(self.x_sat_head(self.x_sat_encoder(x_vecs))).squeeze(1)
  File "/home/~/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/~/ParlAI/parlai/agents/transformer/modules.py", line 522, in forward
    if positions.max().item() > self.n_positions:
RuntimeError: invalid argument 1: cannot perform reduction function max on tensor with no elements because the operation does not have an identity at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:189

Another error when using [DONE] command and then typing something:
Traceback (most recent call last):
  File "projects/self_feeding/interactive.py", line 90, in <module>
    interactive(parser.parse_args(print_args=False), print_parser=parser)
  File "projects/self_feeding/interactive.py", line 81, in interactive
    world.parley()
  File "/home/~/ParlAI/parlai/core/worlds.py", line 341, in parley
    agents[1].observe(validate(acts[0]))
  File "/home/~/ParlAI/projects/self_feeding/self_feeding_agent.py", line 372, in observe
    return super().observe(observation)
  File "/home/~/ParlAI/parlai/core/torch_agent.py", line 1590, in observe
    self._validate_observe_invariants()
  File "/home/~/ParlAI/parlai/core/torch_agent.py", line 1680, in _validate_observe_invariants
    "Last observe() was episode_done, but we never saw a corresponding "
RuntimeError: Last observe() was episode_done, but we never saw a corresponding self_observe to clear the history, probably because you missed an act(). This was changed in #2043. File a GitHub issue if you require assistance.

**Comment by Dogy06** [comment]
Sorry, Im not sure how some of the error stack trace is crossed out. Sorry for the inconvenience.

**Comment by Dogy06** [comment]
There are two issues:

Every two messages, the bot replies with: [SelfFeeding]: Oops! I think I messed up. What could I have said instead? no matter what I say. Is this a bug or is this intended?
Whenever I try the [DONE] command, the issue below pops up.
I used the pretrained model and trained my own model, both gave same results

Training command: python examples/train_model.py -t self_feeding:all --model-file /tmp/mymodel4 -ltim 5 -vtim 10 -vp 50 -m projects.self_feeding.self_feeding_agent:SelfFeedingAgent -cands batch --eval-candidates inline -histsz 2 --embedding-type fasttext_cc --embedding-size 300 --dict-maxtokens 250000 --num-epochs 500 --optimizer adamax --embeddings-scale false -bs 128 --relu-dropout 0 --attention-dropout 0 --n-heads 2 --n-layers 2 -lr 0.0025 --ffn-size 32 --lr-scheduler invsqrt --warmup-updates 500 --dia-train train_hh131k_hb60k.txt -vmt dia_acc -vmm max

Help would be greatly appreciated.
Thanks.

python projects/self_feeding/interactive.py --model-file /tmp/mymodel4 --no-cuda --request-feedback true
[ warning: overriding opt['interactive'] to True (previously: False )]
[ warning: overriding opt['interactive_task'] to True (previously: None )]
[ warning: overriding opt['prev_response_filter'] to True (previously: False )]
[ warning: overriding opt['partial_load'] to True (previously: False )]
[ warning: overriding opt['eval_candidates'] to fixed (previously: inline )]
[ warning: overriding opt['fixed_candidates_path'] to /home//ParlAI/data/self_feeding/convai2_cands.txt (previously: None )]
[ warning: overriding opt['no_cuda'] to True (previously: False )]
[ warning: overriding opt['request_feedback'] to True (previously: False )]
[ Setting interactive mode defaults... ]
Dictionary: loading dictionary from /tmp/mymodel4.dict
[ num words = 25141 ]
[SelfFeeding: full interactive mode on.]
Initialized embeddings for 23672 tokens (94.2%) from fasttext_cc.
Initialized embeddings for 23672 tokens (94.2%) from fasttext_cc.
Initialized embeddings for 23672 tokens (94.2%) from fasttext_cc.
Total parameters: 18,298,093 (17,376,493 trainable)
Loading existing model parameters from /tmp/mymodel4
[ Loading fixed candidate set from /home//ParlAI/data/self_feeding/convai2_cands.txt ]
[ Loading fixed candidate set vectors from /tmp/mymodel4.convai2_cands.vecs ]
[ Loading fixed candidate set encodings from /tmp/mymodel4.convai2_cands.encs ]
/home/~/.local/lib/python3.7/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
warnings.warn(warning.format(ret))
[creating task(s): parlai.agents.local_human.local_human:LocalHumanAgent]
Enter [DONE] if you want to end the episode, [EXIT] to quit.
[ optional arguments: ]
[ share_word_embeddings: True ]
[ Main ParlAI Arguments: ]
[ batchsize: 128 ]
[ datapath: /home//ParlAI/data ]
[ datatype: train ]
[ download_path: /home//ParlAI/downloads ]
[ dynamic_batching: None ]
[ hide_labels: False ]
[ image_mode: raw ]
[ init_opt: None ]
[ multitask_weights: [1] ]
[ numthreads: 1 ]
[ show_advanced_args: False ]
[ task: self_feeding:all ]
[ ParlAI Model Arguments: ]
[ dict_class: parlai.core.dict:DictionaryAgent ]
[ init_model: None ]
[ model: projects.self_feeding.self_feeding_agent:SelfFeedingAgent ]
[ model_file: /tmp/mymodel4 ]
[ Local Human Arguments: ]
[ local_human_candidates_file: None ]
[ single_turn: False ]
[ ParlAI Image Preprocessing Arguments: ]
[ image_cropsize: 224 ]
[ image_size: 256 ]
[ TorchAgent Arguments: ]
[ add_p1_after_newln: False ]
[ delimiter:
]
[ embedding_projection: random ]
[ embedding_type: fasttext_cc ]
[ force_fp16_tokens: False ]
[ fp16: False ]
[ fp16_impl: apex ]
[ gpu: -1 ]
[ history_add_global_end_token: None ]
[ history_size: 2 ]
[ interactive_mode: True ]
[ label_truncate: None ]
[ no_cuda: True ]
[ person_tokens: False ]
[ rank_candidates: True ]
[ split_lines: False ]
[ text_truncate: None ]
[ truncate: 1024 ]
[ use_reply: label ]
[ Optimizer Arguments: ]
[ adafactor_eps: [1e-30, 0.001] ]
[ adam_eps: 1e-08 ]
[ betas: [0.9, 0.999] ]
[ gradient_clip: 0.1 ]
[ learningrate: 0.0025 ]
[ momentum: 0 ]
[ nesterov: True ]
[ nus: [0.7] ]
[ optimizer: adamax ]
[ weight_decay: None ]
[ Learning Rate Scheduler: ]
[ invsqrt_lr_decay_gamma: -1 ]
[ lr_scheduler: invsqrt ]
[ lr_scheduler_decay: 0.5 ]
[ lr_scheduler_patience: 3 ]
[ max_lr_steps: -1 ]
[ update_freq: 1 ]
[ warmup_rate: 0.0001 ]
[ warmup_updates: 500 ]
[ TorchRankerAgent: ]
[ candidates: batch ]
[ cap_num_predictions: 100 ]
[ encode_candidate_vecs: True ]
[ encode_candidate_vecs_batchsize: 256 ]
[ eval_candidates: fixed ]
[ fixed_candidate_vecs: reuse ]
[ fixed_candidates_path: /home//ParlAI/data/self_feeding/convai2_cands.txt ]
[ ignore_bad_candidates: False ]
[ inference: max ]
[ init_model: None ]
[ interactive_candidates: fixed ]
[ rank_top_k: -1 ]
[ repeat_blocking_heuristic: True ]
[ return_cand_scores: False ]
[ topk: 5 ]
[ train_predict: False ]
[ Transformer Arguments: ]
[ activation: relu ]
[ attention_dropout: 0.0 ]
[ data_parallel: False ]
[ dropout: 0.0 ]
[ embedding_size: 300 ]
[ embeddings_scale: False ]
[ ffn_size: 32 ]
[ learn_embeddings: True ]
[ learn_positional_embeddings: False ]
[ memory_attention: sqrt ]
[ model_parallel: False ]
[ n_decoder_layers: -1 ]
[ n_encoder_layers: -1 ]
[ n_heads: 2 ]
[ n_layers: 2 ]
[ n_positions: None ]
[ n_segments: 0 ]
[ normalize_sent_emb: False ]
[ output_scaling: 1.0 ]
[ reduction_type: mean ]
[ relu_dropout: 0.0 ]
[ share_encoders: True ]
[ use_memories: False ]
[ variant: aiayn ]
[ wrap_memory_encoder: False ]
[ Dictionary Arguments: ]
[ bpe_debug: False ]
[ dict_endtoken: end ]
[ dict_file: /tmp/mymodel4.dict ]
[ dict_initpath: None ]
[ dict_language: english ]
[ dict_lower: False ]
[ dict_max_ngram_size: -1 ]
[ dict_maxtokens: 250000 ]
[ dict_minfreq: 0 ]
[ dict_nulltoken: null ]
[ dict_starttoken: start ]
[ dict_textfields: text,labels ]
[ dict_tokenizer: re ]
[ dict_unktoken: unk ]
[ BPEHelper Arguments: ]
[ bpe_add_prefix_space: None ]
[ bpe_merge: None ]
[ bpe_vocab: None ]
[ Self Feeding Model: ]
[ sat_head_layers: 1 ]
[ share_fee_embeddings: True ]
[ share_fee_x_encoder: True ]
[ share_fee_y_encoder: True ]
[ share_sat_embeddings: False ]
[ share_sat_encoder: False ]
[ Self-feeding Agent: ]
[ add_double_person_tokens: False ]
[ dia_weight: 1.0 ]
[ display_sat_estimate: False ]
[ fee_weight: 1.0 ]
[ freeze_base: False ]
[ interactive: True ]
[ partial_load: True ]
[ prev_response_filter: True ]
[ prev_response_negatives: False ]
[ rating_frequency: 0.01 ]
[ rating_gap: 0.05 ]
[ rating_threshold: 0.5 ]
[ request_feedback: True ]
[ request_rating: False ]
[ sat_weight: 1.0 ]
[ subtasks: ['dialog', 'feedback', 'satisfaction'] ]
[ target_class: 0 ]
[ Self-feeding Variants: ]
[ regex: False ]
[ uncertainty_predictor: False ]
[ uncertainty_style: gap ]
[ uncertainty_threshold: 0.5 ]
Enter Your Message: Hello!
/home//ParlAI/parlai/core/torch_ranker_agent.py:759: UserWarning: [ Executing eval mode with a common set of fixed candidates (n = 127712). ]
"(n = {}). ]".format(mode, len(self.fixed_candidates))
[SelfFeeding]: helloooo ! !
Enter Your Message: How are you?
[SelfFeeding]: Oops! I think I messed up. What could I have said instead?
Enter Your Message: You did not mess up
[SelfFeeding]: Thanks! I'll try to remember that. Can you pick a new topic for us to talk about now?
Enter Your Message: Sure, how about Science?
[SelfFeeding]: not bad . how about you ?
Enter Your Message: hmmm wrong answer
[SelfFeeding]: Oops! I think I messed up. What could I have said instead?
Enter Your Message: You could have said something relating to science
[SelfFeeding]: Thanks! I'll try to remember that. Can you pick a new topic for us to talk about now?
Enter Your Message: a
[SelfFeeding]: i like to spend time with my family
Enter Your Message: b
[SelfFeeding]: Oops! I think I messed up. What could I have said instead?
Enter Your Message: c
[SelfFeeding]: Thanks! I'll try to remember that. Can you pick a new topic for us to talk about now?
Enter Your Message: d
[SelfFeeding]: what is d d ?
Enter Your Message: e
[SelfFeeding]: Oops! I think I messed up. What could I have said instead?
Enter Your Message: f
[SelfFeeding]: Thanks! I'll try to remember that. Can you pick a new topic for us to talk about now?
Enter Your Message: g
[SelfFeeding]: savage ? do you like death metal ? i know a member of martius .
Enter Your Message: [DONE]
Traceback (most recent call last):
File "projects/self_feeding/interactive.py", line 90, in
interactive(parser.parse_args(print_args=False), print_parser=parser)
File "projects/self_feeding/interactive.py", line 81, in interactive
world.parley()
File "/home//ParlAI/parlai/core/worlds.py", line 342, in parley
acts[1] = agents[1].act()
File "/home//ParlAI/projects/self_feeding/self_feeding_agent.py", line 324, in act
positivity = self.predict_satisfaction(self.observation)
File "/home//ParlAI/projects/self_feeding/self_feeding_agent.py", line 732, in predict_satisfaction
prob = self.model.score_satisfaction(observation['text_vec'].reshape(1, -1))
File "/home//ParlAI/projects/self_feeding/modules.py", line 148, in score_satisfaction
return torch.sigmoid(self.x_sat_head(self.x_sat_encoder(x_vecs))).squeeze(1)
File "/home//.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in call
result = self.forward(*input, **kwargs)
File "/home//ParlAI/parlai/agents/transformer/modules.py", line 522, in forward
if positions.max().item() > self.n_positions:
RuntimeError: invalid argument 1: cannot perform reduction function max on tensor with no elements because the operation does not have an identity at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:189

Another error when using [DONE] command and then typing something:
Traceback (most recent call last):
File "projects/self_feeding/interactive.py", line 90, in
interactive(parser.parse_args(print_args=False), print_parser=parser)
File "projects/self_feeding/interactive.py", line 81, in interactive
world.parley()
File "/home//ParlAI/parlai/core/worlds.py", line 341, in parley
agents[1].observe(validate(acts[0]))
File "/home//ParlAI/projects/self_feeding/self_feeding_agent.py", line 372, in observe
return super().observe(observation)
File "/home//ParlAI/parlai/core/torch_agent.py", line 1590, in observe
self._validate_observe_invariants()
File "/home//ParlAI/parlai/core/torch_agent.py", line 1680, in _validate_observe_invariants
"Last observe() was episode_done, but we never saw a corresponding "
RuntimeError: Last observe() was episode_done, but we never saw a corresponding self_observe to clear the history, probably because you missed an act(). This was changed in #2043. File a GitHub issue if you require assistance.

**Comment by stephenroller** [comment]
Thanks for reporting.   The second one looks like there was a batch size of 0 maybe? The first one I'm not so sure about. We'd have to figure out why there was the observe call but no self observe. Perhaps the agent's act wasn't upgraded...

**Comment by Dogy06** [comment]
Oh ok. Thanks for your help. Regarding the first problem, should I try an earlier commit of this repository.

Thanks again.

**Comment by stephenroller** [comment]
Did you happen to have luck with an earlier commit? If so, do you know which? That would help me fix the bug in master.

**Comment by Dogy06** [comment]
Ah ok. I will try an earlier commit and come back to you.

**Comment by Dogy06** [comment]
Even after trying commit as early as #2124, I still couldn't get it to work. It may be a problem with my parameters.
Command I used:python projects/self_feeding/interactive.py --model-file zoo:self_feeding/hh131k_hb60k_fb60k_st1k/model --no-cuda --request-feedback true
Still getting this:
Enter Your Message: Hello
[SelfFeeding]: Oops! I think I messed up. What could I have said instead?
Enter Your Message: 
[SelfFeeding]: Thanks! I'll try to remember that. Can you pick a new topic for us to talk about now?
Enter Your Message: 
[SelfFeeding]: good morning what is the haps ?
Enter Your Message: 
[SelfFeeding]: Oops! I think I messed up. What could I have said instead?
Enter Your Message: 
[SelfFeeding]: Thanks! I'll try to remember that. Can you pick a new topic for us to talk about now?
Enter Your Message: 
[SelfFeeding]: what is up stranger ? what are you doing ?
Enter Your Message: hi
[SelfFeeding]: Oops! I think I messed up. What could I have said instead?
Enter Your Message: 

parameters:
[ optional arguments: ] 
[  share_word_embeddings: True ]
[ Main ParlAI Arguments: ] 
[  batchsize: 128 ]
[  datapath: /home/weichen/ParlAI/data ]
[  datatype: train ]
[  download_path: /dfs/scratch1/bradenjh/ParlAI/downloads ]
[  hide_labels: False ]
[  image_mode: raw ]
[  init_opt: None ]
[  multitask_weights: [1] ]
[  numthreads: 1 ]
[  show_advanced_args: False ]
[  task: self_feeding:all:train ]
[ ParlAI Model Arguments: ] 
[  dict_class: parlai.core.dict:DictionaryAgent ]
[  init_model: None ]
[  model: projects.self_feeding.self_feeding_agent:SelfFeedingAgent ]
[  model_file: /home/weichen/ParlAI/data/models/self_feeding/hh131k_hb60k_fb60k_st1k/model ]
[ Local Human Arguments: ] 
[  local_human_candidates_file: None ]
[  single_turn: False ]
[ ParlAI Image Preprocessing Arguments: ] 
[  image_cropsize: 224 ]
[  image_size: 256 ]
[ TorchAgent Arguments: ] 
[  add_p1_after_newln: False ]
[  delimiter: 
 ]
[  embedding_projection: random ]
[  embedding_type: fasttext_cc ]
[  fp16: False ]
[  gpu: -1 ]
[  history_size: 2 ]
[  interactive_mode: True ]
[  label_truncate: None ]
[  no_cuda: True ]
[  person_tokens: False ]
[  rank_candidates: True ]
[  split_lines: False ]
[  text_truncate: None ]
[  truncate: 1024 ]
[  use_reply: label ]
[ Optimizer Arguments: ] 
[  adam_eps: 1e-08 ]
[  betas: [0.9, 0.999] ]
[  gradient_clip: 0.1 ]
[  learningrate: 0.0025 ]
[  momentum: 0 ]
[  nesterov: True ]
[  nus: [0.7] ]
[  optimizer: adamax ]
[  weight_decay: None ]
[ Learning Rate Scheduler: ] 
[  lr_scheduler: invsqrt ]
[  lr_scheduler_decay: 0.5 ]
[  lr_scheduler_patience: 3 ]
[  update_freq: -1 ]
[  warmup_rate: 0.0001 ]
[  warmup_updates: 500 ]
[ TorchRankerAgent: ] 
[  candidates: batch ]
[  cap_num_predictions: 100 ]
[  encode_candidate_vecs: True ]
[  encode_candidate_vecs_batchsize: 256 ]
[  eval_candidates: fixed ]
[  fixed_candidate_vecs: reuse ]
[  fixed_candidates_path: /home/weichen/ParlAI/data/self_feeding/convai2_cands.txt ]
[  ignore_bad_candidates: False ]
[  inference: max ]
[  init_model: None ]
[  rank_top_k: -1 ]
[  repeat_blocking_heuristic: True ]
[  topk: 5 ]
[  train_predict: False ]
[ Transformer Arguments: ] 
[  activation: relu ]
[  attention_dropout: 0.0 ]
[  data_parallel: False ]
[  dropout: 0.0 ]
[  embedding_size: 300 ]
[  embeddings_scale: False ]
[  ffn_size: 32 ]
[  learn_embeddings: True ]
[  learn_positional_embeddings: False ]
[  memory_attention: sqrt ]
[  n_heads: 2 ]
[  n_layers: 2 ]
[  n_positions: None ]
[  n_segments: 0 ]
[  normalize_sent_emb: False ]
[  output_scaling: 1.0 ]
[  reduction_type: mean ]
[  relu_dropout: 0.0 ]
[  share_encoders: True ]
[  use_memories: False ]
[  variant: aiayn ]
[  wrap_memory_encoder: False ]
[ Dictionary Arguments: ] 
[  bpe_debug: False ]
[  dict_endtoken: __end__ ]
[  dict_file: /home/weichen/ParlAI/data/models/self_feeding/hh131k_hb60k_fb60k_st1k/model.dict ]
[  dict_initpath: None ]
[  dict_language: english ]
[  dict_lower: False ]
[  dict_max_ngram_size: -1 ]
[  dict_maxtokens: 250000 ]
[  dict_minfreq: 0 ]
[  dict_nulltoken: __null__ ]
[  dict_starttoken: __start__ ]
[  dict_textfields: text,labels ]
[  dict_tokenizer: re ]
[  dict_unktoken: __unk__ ]
[ Self Feeding Model: ] 
[  sat_head_layers: 1 ]
[  share_fee_embeddings: True ]
[  share_fee_x_encoder: True ]
[  share_fee_y_encoder: True ]
[  share_sat_embeddings: False ]
[  share_sat_encoder: False ]
[ Self-feeding Agent: ] 
[  add_double_person_tokens: True ]
[  dia_weight: 1.0 ]
[  display_sat_estimate: False ]
[  fee_weight: 1.0 ]
[  freeze_base: False ]
[  interactive: True ]
[  partial_load: True ]
[  prev_response_filter: True ]
[  prev_response_negatives: False ]
[  rating_frequency: 0.01 ]
[  rating_gap: 0.05 ]
[  rating_threshold: 0.5 ]
[  request_feedback: True ]
[  request_rating: False ]
[  sat_weight: 1.0 ]
[  subtasks: ['dialog', 'satisfaction'] ]
[  target_class: 0 ]
[ Self-feeding Variants: ] 
[  regex: False ]
[  uncertainty_predictor: False ]
[  uncertainty_style: gap ]
[  uncertainty_threshold: 0.5 ]

**Comment by klshuster** [comment]
closing, as this project is no longer maintained
