### ISSUE TITLE
persona's number in PERSONA-CHAT Dataset

### ISSUE THREAD

**Issue by luomuqinghan** [facebookresearch/ParlAI#2576]
As mentioned in the paper, the author collected 1155 possible personas. After downloading the dataset via "python examples/display_data.py --task convai2 --datatype train", I got some files ("train_both_original","train_both_revised", "train_other_original", "train_other_revised","train_self_original", "train_self_revised"). 

However, a  I find that the number of distinct personas in all training files mentioned above is more than 6,000. As I understand, the personas in train_other_original and train_both_original are not revised. 

I also understand that the order and utterances' number may be different for a same persona, which are shown as belows:

Persona:
    1 your persona: i love to redesign houses.
    2 your persona: killing for sport is my hobby.
    3 your persona: i shot an arrow the other day !.
    4 your persona: i like to get dressed up.

Persona:
    1 your persona: i love to redesign houses.
    2 your persona: i like to spend time with my kids.
    3 your persona: killing for sport is my hobby.
    4 your persona: i shot an arrow the other day !.
    5 your persona: i like to get dressed up.

Persona:
    1 your persona: i love to redesign houses.
    2 your persona: i like to spend time with my kids.
    3 your persona: killing for sport is my hobby.
    4 your persona: i like to get dressed up.
    5 your persona: i shot an arrow the other day !.

When I do statistics, I regarded the three personas as the same persona.  Nevertheless, the number of distinct personas in all files mentioned above is more than 6,000, which is far more than 1155  mentioned in the paper and convai.
-------------------------------------------------------------------------------------------------------
Besides, I download data from http://parl.ai/downloads/personachat/personachat.tgz, and the number of distinct personas in all training files is nearly 3000.
-------------------------------------------------------------------------------------------------------
Does anyone know how to divide the data to get 1155  personas?

Thank you very much.

**Comment by stephenroller** [comment]
Perhaps @saizheng can weigh in?

**Comment by hqsiswiliam** [comment]
Hi, I met the same issue as well. Can someone here explain the number discrepancy?

**Comment by hqsiswiliam** [comment]
Hi, I met the same problem as well. For the train_self_original.txt, I had 8784 personas in the training set, which is much larger than the paper stated version.
