### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by Ashappyboy** [facebookresearch/ParlAI#2581]
after reading the doc “https://parl.ai/docs/”，I feel I don't know how to use it and how to create my project by it. I think maybe you should offer a clear and straightforward tutorial. 
Thank you a lot!

**Comment by stephenroller** [comment]
You might be interested in this [google colab](https://colab.research.google.com/drive/1bRMvN0lGXaTF5fuTidgvlAl-Lb41F7AD#scrollTo=KtVz5dCUmFkN) tutorial that we very recently wrote. It may help you some.
