### ISSUE TITLE
Adding additional webpages before and after the ParlAI chat interface

### ISSUE THREAD

**Issue by kushalchawla** [facebookresearch/ParlAI#2587]
Hey. I am exploring ParlAI for my dialog data collection between two MTurkers. I was able to host the sample qa_data_collection task in a sandbox environment. I am wondering about the following questions: 

1) I would like to ask MTurkers to fill in a survey (on a third-party app (say a Google Form/survey monkey) or through MTurk in-built interface) before and after they are done with the dialog. What is the easiest way to achieve that?

2) Can I manage my task from the requester account in the same way as any other task? If I can do that, I can go to my requester and add additional webpages before and after the chat (essentially, achieving point 1) )

Apologies, if this is covered somewhere in the documentation. I could not find it myself.
Thanks.

**Comment by JackUrb** [comment]
Hi @kushalchawla - some of this is possible, some of it not.

1. You can manage this in-task by having an onboarding world for the pre-chat survey, but for the post survey there's no easy way to have both workers submit this kind of survey without having to wait for the other worker to finish it as well. For the former you can check out [this](https://github.com/facebookresearch/ParlAI/pull/1542) pr for how to use forms, and [this](https://github.com/facebookresearch/ParlAI/tree/master/parlai/mturk/tasks/react_task_demo/react_custom_no_extra_deps) for some usage of an onboarding world. What you can do for the survey afterwards is link them to a survey in the last message with a specific code, tell them to write the code down and submit the task, and then finish the survey afterwards.
2. Unfortunately there's no direct way to manage tasks run on ParlAI MTurk using the regular interface. We're working on some new tooling to improve these flows, but won't have them released until sometime next month.

**Comment by kushalchawla** [comment]
Hey @JackUrb,

Thanks for your reply.

1. This seems to be tricky. I would have expected this to be a usual format, hence, I would be interested in knowing how other folks usually manage post-surveys. I think knowing a bit more about the sequence of steps used for ending the dialogue completely, may help me intervene. Could you talk about what happens currently? Can't the two MTurkers finish their chat asynchronously? I am hoping this to be a possible scenario: a worker can end their own session, but the request to server is only sent when both of them have submitted their sessions. If this is the case, can't we intervene by adding a pre-final submit button, then the survey, then the Final Submit button? It should be fine if the server request and subsequent processing of bonuses takes a while for the worker, but they should be able to end the session on their own? Please let me know. Asking them to note down a code, with a promise to fill it later on, seems a bit weird and would hurt their UI experience.
2. Got it, thanks!

**Comment by kushalchawla** [comment]
Hey @JackUrb 

1. Another thought here: Is it possible to use the left pane is some way? Which would persist even after the chat has ended? I think basically what I am asking for is a deboarding world, similar to an onboarding world. I would really recommend you guys to add this functionality, as I would expect this to be a usual requirement. What do you think?

**Comment by JackUrb** [comment]
So the rationale for why 1 is difficult is just that it wasn't in the initial design for ParlAI-MTurk. I've been working on a more extensive platform for being able to launch these kinds of tasks, and in that it's possible to have more complicated flows, but I don't have plans to push the improvements to PMT. If you can wait for a short period we're hoping to release that at some point this month. If not you'll need to dig into the logic here to see why asynchronous completion doesn't work out under the current design:
https://github.com/facebookresearch/ParlAI/blob/b4a442018d1a46f9374547ef0a9b8134b7bb4944/parlai/mturk/core/worker_manager.py#L243
If you follow the path up from where this is called, what you'll find is that even if you were to split your `run_conversation` function into two threads after the main world completes (each calling agent.shutdown after an individual agent is completed), after one of the agents submits, the monitor thread notes that there are no longer two agents connected to the task and marks it as a disconnect.

**Comment by kushalchawla** [comment]
Hey @JackUrb 

Thanks for your reply. I will dig deeper into this. I will think about any workaround for this problem.

About the new platform: I think I can wait for a short period for the more extensive platform. However, I have already spent a lot of my time trying to figure things out with ParlAI. Does the new platform leverage the same concepts/frameworks (Python/React) at least, so that it is easier to migrate for me? If it is something totally new, it would make it much more time consuming and might not be worth the wait. 

Please let me know. Thanks

**Comment by JackUrb** [comment]
Of course! The new platform will essentially be a repackaging of the backend crowdsourcing components that are present in PMT, but extracted into a library that can be used for other and more diverse tasks. You will be able to use _almost_ the exact same run scripts you've put together for ParlAI and launch task and onboarding worlds in the same way. It still uses react as the frontend, though we anticipate a small amount of churn to refactor to the new templates.

**Comment by kushalchawla** [comment]
Hey. That sounds great. I will continue working with ParlAI till then. Lastly, before I close this, what's the best way to follow up on the updates regarding this newer platform?

**Comment by JackUrb** [comment]
As of now there's no great place to followup, so feel free to reopen this if you want to check in.

**Comment by kushalchawla** [comment]
Got it. Thanks a lot.

**Comment by kushalchawla** [comment]
Hey @JackUrb 

Apologies for bugging again, just want to make the most of the opportunity!

Thinking more, I think one option might also be this: If I can reduce the number of questions I have in the post-survey to a very low count, which can directly be asked in the chat once the dialogue is complete, this would drastically reduce the wait time for both the participants and give me the data directly from PMT. Is there a straight forward way to achieve this?

**Comment by JackUrb** [comment]
Yeah what you'd do for this is create an off-boarding world in the way you suggested, but then after the main world has finished `parley`-ing in your `run_conversation` you'd then initialize two off-boarding worlds (one on each agent) and run them in parallel before the agent shutdown calls.

**Comment by kushalchawla** [comment]
So the Turkers will still wait for each other, but hopefully, wait time will be reduced. Got it. This sounds promising. I will try that.

Closing this (hopefully) for good.
