### ISSUE TITLE
Browser chat service

### ISSUE THREAD

**Issue by sseol11** [facebookresearch/ParlAI#2590]
I want to use browser chat service on my server. 
But, the script just only for the localhost? (http://localhost:8080)
I tried to my own server ip address to see the result, it doesn't work. (http://myipadress:8080)
I mean no reaction on the browser. (maybe firewall problem?)
Could you give any guidelines?

**Comment by stephenroller** [comment]
Assigning Kurt, he should have some advice. Probably the server is only binding to localhost by default. We should maybe make that an option?

**Comment by klshuster** [comment]
Yes, I believe the server is only binding to localhost by default. If I understand the problem correctly, you could perhaps setup an ssh tunnel to your server from your local machine to access via your local browser?

**Comment by marcelodiaz558** [comment]
Hello, I was also facing this problem. Try to modify the client.py file (located in ~/ParlAI/parlai/chat_service/services/browser_chat/client.py), look for the function `_run_browser`, then modify it to look like this: 

```.py
def _run_browser():
    # 0.0.0.0 allows connection from external IPs, you can change 80 to whatever port you wish
    httpd = HTTPServer(('0.0.0.0', 80), BrowserHandler)
    print('Please connect to the link: http://{}:{}/'.format('ip', 80))
    SHARED['wb'] = httpd
    httpd.serve_forever()
```
I hope that it helps.

**Comment by sseol11** [comment]
Thanks for the instruction! 
It is work for me. I used AWS server, i think 8080 port was not opened.
