### ISSUE TITLE
N_best answers beamsearch

### ISSUE THREAD

**Issue by manzar96** [facebookresearch/ParlAI#2600]
I am encountering a problem in beam search.
I can't figure out how I can receive the N_best answers from beam search.

I have modified the file parlai/core/torch_generator_agent.py (to receive the 3-best answers each time) at line 945 as :
n_best_beam_preds_scores = [b.get_rescored_finished(3) for b in beams]

I am running this example:  python examples/train_model.py -t cornell_movie -m seq2seq  -mf tmp/noattn -bs 2 -eps 3 --inference beam  --beam-size 10

I have also modified the train.txt to reduce training time (run evaluation alsmost instantly).

So n_best_beam_preds_scores[0] should contain the 3-best answers (independently from the training procedure).
However that is not happening everytime i run the script! (I also remove the model's file).
Am I missing something?
Thank you in advance.

**Comment by stephenroller** [comment]
Hey Manzar, #2617 outputs all the alternative beams when the environmental variable `PARLAI_DEBUG` is set. Hopefully that helps you.
