### ISSUE TITLE
Module setuptools not found

### ISSUE THREAD

**Issue by EdTheC** [facebookresearch/ParlAI#2604]
Forgive my newbie - ness. I am using <gasp> Windows 10 to follow the get started.

I have python 3.8, pytorch, anaconda installed. I have cloned the repo to <myfolder>~\ParlAI. But when attempting the command python setup.py develop I get a module setuptools not found. I'm sure I am missing something, any help appreciated.
<img width="1152" alt="parlai error 1" src="https://user-images.githubusercontent.com/15270043/80628757-b5a2be80-8a06-11ea-9694-642812785b36.png">

**Comment by stephenroller** [comment]
We don't support windows at this time.
