### ISSUE TITLE
packages mis during start installation

### ISSUE THREAD

**Issue by salama4** [facebookresearch/ParlAI#2607]
**Bug description**
when i start to install parlai using the recommended steps i.e:
`git clone https://github.com/facebookresearch/ParlAI.git ~/ParlAI
cd ~/ParlAI; python setup.py develop`
and then run:
`pip check`
i found many packages versions uninstalled correctly
after i open requirements.txt file i found the packages stated there is different of the packages version installed after:
`git clone https://github.com/facebookresearch/ParlAI.git ~/ParlAI
cd ~/ParlAI; python setup.py develop`

**reproduce Bug**
`git clone https://github.com/facebookresearch/ParlAI.git ~/ParlAI
cd ~/ParlAI; python setup.py develop`
`pip check`

**Comment by salama4** [comment]
i found solution but it doesn't solve the underlying issue
solution is:
`pip install parlai`

**Comment by stephenroller** [comment]
Create a new virtual env?
