### ISSUE TITLE
Syntax Error when running setup.py

### ISSUE THREAD

**Issue by mthomasf** [facebookresearch/ParlAI#2616]
When I run `cd ~/ParlAI; python setup.py develop`
I get the following error:
`  File "setup.py", line 30
    version=f'0.1.{DATE}{BUILD}',
                               ^
SyntaxError: invalid syntax`

Is there something I am doing wrong on my end?

**Comment by jloveric** [comment]
Make sure you are running python3.  You may need to switch python to python3.

**Comment by stephenroller** [comment]
You must use python3.6 or newer.
