### ISSUE TITLE
blender model examples installation/use not working.

### ISSUE THREAD

**Issue by jloveric** [facebookresearch/ParlAI#2618]
Trying to use the blender models as described on the page https://parl.ai/projects/blender . Parlai seems to install fine and I see the babi results, however when I run 
```bash
python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_90M/model
```
I get the error
```
ImportError: Could not find pretrained model in parlai.zoo.blender.blender_9B or parlai.zoo.blender.build.
```
Ditto for the other models.  Is this model supposed to be downloaded by this command or do I need to install this model separately?  Is there another package that I'm missing? Thanks!

**Comment by GraphGrailAi** [comment]
Downloaded automatically 
```
[building data: /root/ParlAI/data/models/blender/blender_90M/BST0B.tgz]
[ downloading: http://parl.ai/downloads/_models/blender/BST0B.tgz to /root/ParlAI/data/models/blender/blender_90M/BST0B.tgz ]
Downloading BST0B.tgz: 100% 161M/161M [00:02<00:00, 54.4MB/s]
unpacking BST0B.tgz
```

**Comment by stephenroller** [comment]
You probably need to reinstall. I suspect you did `pip install`, which hasn't had blender released on it yet.

**Comment by tkaratekinbenten** [comment]
I am using the google colab tutorial and wanted to replace the model with the blenderbot2.0 that was just published, however, I get a similar error. 

May I also ask how the dash prompt installation commands is supposed to be in google colab cells? I am not clear how I'll install blenderbot 2.0 inside google colab. I use a free google colab version, which does let me me use the terminal. 



ImportError: Could not find pretrained model in parlai.zoo.blenderbot2.blenderbot2_400M or parlai.zoo.blenderbot2.build. Please check your spelling and make sure you've pulled from master.
