### ISSUE TITLE
Blender 2.7B model inference - hung

### ISSUE THREAD

**Issue by GraphGrailAi** [facebookresearch/ParlAI#2619]
**Bug description**
Model not loaded

**Reproduction steps**
I setup model in colab:
`!python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_3B/model`

```

**Expected behavior**
So, model not loaded. 90m model works

**Logs**
Please paste the command line output:
```
                                 /@&%###%&&@@#
                      .,*/((((##@@@&%%#%%&&@@@&%%#/*.
             #@@&&&%%%%##(((///*****//(((###%%%&&&@@@@@&&%#%%#.
         .%&@@@@@&&&%%%####((((////((((####%%%&&&@@@@@&&%%#%%####,
           ./,,#(//**,,.....,,,,***////((((########%%%%%%%%###(((
              /*(//**,,,....,,,,***////((((########%%%%%%%%###(#%*
               (*,...      ...,,,***//////((((((///////(/*...,/#@@@(
               **,,..         ...,,,,,,,,,,........,,*///*...*(#@@@@&&*
               ./,,..          ...,,,,,,,,,........,,*//*,...*#/,,,,,/%#
                (*,..          ...,,,,,,,,,........,,*//*,..,/(      .,#(
                **,..          ...,,,,,,,,,.........,*//*,..,((       .,(#
                 /*,..          ....,,,,,,,.....  ..,***,,,,(#         ..#&
                 **,..          ....,,,,,,,....   ..,***,,,*#.         .,%@
                 ./,...          B L E N D E R    ...***,,,*#          .*%@
                  /*,..          ...,,,,,,,....    .,**,,,,/#         ..(%/
                  /*,,..         ...,,,,,,,...    ..,*,,,,,(.         ..#&
                  ,/*,..         ...,,,,,,,...    ..,*,,,,*#         ..*%(
                   /*,..         ...,,,,,.....    ..,*,*,,/(         ..#&
                   /**,..        ...,,,,.....    ...,***,*(.       ,,(%.
                    (/*,,..      ....,,.....     ...,****(&@@@&&&#,
                     (/*,,...   .....,,......     ..,****#@,
                     *(/*,,/....*(###%(,(%%##(*.  ./,,**(
                      ,//**(,........,/((#.........*,**(
                      .(#//*,,,,,,.*.,/((%/,,.....,,*/@
                    ((######//****,/.,/(#%#***,***(&@@@@@(
                   *&%%#####%%%%%%%#//(#%&%%&&@@@@@@@@@@@@*
                   &&%%%###((((((####%%%%&&&&&@@@@@@@@@@&&@.
                  *##%%%##(((((((####%%%%%&&&&@@@@@@@@@&#/*,
                 .(##%#/,  .,*((##%%%&&&&%%%#####%&&@&&%#(/*.
                 /(###(,   .,*/(##%%%&&&&%%%######%&&&&%#(/*,
                */((((*.  ..,//((##%%%%%%%%#######%&&&&%%#(/*,
               .//(((/,   .,*//((###%%%%%%########%%&&&%%#((/,.
              .&####(((((((((######%%%%%%%%&&&&&&&@@@@@@@@@@@@@#
               *&#.   .*/((((#######%%%%%%&&&&&&&@@@@@#/.   (&
[building data: /content/ParlAI/data/models/blender/blender_3B/BST3B.tgz]
[ downloading: http://parl.ai/downloads/_models/blender/BST3B.tgz to /content/ParlAI/data/models/blender/blender_3B/BST3B.tgz ]
Downloading BST3B.tgz: 100% 4.95G/4.95G [01:02<00:00, 79.8MB/s]
unpacking BST3B.tgz
[ warning: overriding opt['task'] to blended_skill_talk (previously: internal:blended_skill_talk,wizard_of_wikipedia,convai2:normalized,empathetic_dialogues )]
[ warning: overriding opt['model_file'] to /content/ParlAI/data/models/blender/blender_3B/model (previously: /checkpoint/edinan/20200331/finetune_bst_gen_baseline_convai2_normal/de6/model )]
Dictionary: loading dictionary from /content/ParlAI/data/models/blender/blender_3B/model.dict
[ num words =  8008 ]
[TransformerGenerator: full interactive mode on.]
Total parameters: 2,696,268,800 (2,695,613,440 trainable)
[ Loading existing model params from /content/ParlAI/data/models/blender/blender_3B/model ]
^C
```

**Additional context**
My guess this is because GPU is not capable to load model. I see that The 2.7B can be interacted with on a 16gb P100 GPU or better - this is very strict powerful card, is it possible to interact with model using home cards like 1080ti ?

**Comment by stephenroller** [comment]
It's a very large model, and can take a long time to load. I suspect the 1080TI is probably enough; the P100 is the smallest GPU we tried. You can always run with `--no-cuda`, but you will find it very slow.

**Comment by GraphGrailAi** [comment]
So, model not released yet? 90m works in Colab, that means i installed it right

**Comment by jsedoc** [comment]
Are there any plans to open a WebSocket, so that everyone can try to chat with the 9B param model?

**Comment by stephenroller** [comment]
We do not plan on making a publicly accessible demo at the moment, as our target audience is researchers, and the models have ongoing limitations in safety.

**Comment by vessenes** [comment]
@stephenroller I experience this behavior with a P100 on Colab Pro, which is not what I expected from the documentation. 

Can you advise?


```
!python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_3B/model
[ warning: overriding opt['task'] to blended_skill_talk (previously: internal:blended_skill_talk,wizard_of_wikipedia,convai2:normalized,empathetic_dialogues )]
[ warning: overriding opt['model_file'] to /content/ParlAI/data/models/blender/blender_3B/model (previously: /checkpoint/edinan/20200331/finetune_bst_gen_baseline_convai2_normal/de6/model )]
[ Using CUDA ]
Dictionary: loading dictionary from /content/ParlAI/data/models/blender/blender_3B/model.dict
[ num words =  8008 ]
[TransformerGenerator: full interactive mode on.]
^C
```

Then the kernel stops executing.  Tensorflow reports the following.

```
device_lib.list_local_devices()
[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 1481335122207254493, name: "/device:XLA_CPU:0"
 device_type: "XLA_CPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 3859485000525366826
 physical_device_desc: "device: XLA_CPU device", name: "/device:XLA_GPU:0"
 device_type: "XLA_GPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 16493355271731639709
 physical_device_desc: "device: XLA_GPU device", name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 15701463552
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 17742052616483181058
 physical_device_desc: "device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0"]
```

**Comment by vessenes** [comment]
Update: Colab Pro also cancels out with ``--no-cuda``.

**Comment by vessenes** [comment]
Update again - Colab Pro seems to work on the 3B dataset when a high memory instance is required. It might be nice to get a lower bound on System RAM -- Colab High Mem is 25 gig or so.

**Comment by marcoaleixo** [comment]
It seems a bit random to make it work using the 12GB + P100 in Colab with 3B model.
Can we for example not load some layers or remove the trainable params in the loading process?

**Comment by erekgit** [comment]
> It's a very large model, and can take a long time to load. I suspect the 1080TI is probably enough; the P100 is the smallest GPU we tried. You can always run with `--no-cuda`, but you will find it very slow.

I'm trying on a 2080 Ti but running out of memory:

"RuntimeError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 11.00 GiB total capacity; 8.74 GiB already allocated; 2.59 MiB free; 8.75 GiB reserved in total by PyTorch)"

**Comment by stephenroller** [comment]
I don't have any 8gb or 12gb cards to try on. Does anyone know, does it fail on loading, or does it fail during generation?

**Comment by erekgit** [comment]
@stephenroller 

(base) PS F:\ParlAI> python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_3B/model   [ warning: overriding opt['task'] to blended_skill_talk (previously: internal:blended_skill_talk,wizard_of_wikipedia,convai2:normalized,empathetic_dialogues )]
[ warning: overriding opt['model_file'] to f:\parlai\data\models\blender/blender_3B/model (previously: /checkpoint/edinan/20200331/finetune_bst_gen_baseline_convai2_normal/de6/model )]
[ Using CUDA ]
Dictionary: loading dictionary from f:\parlai\data\models\blender/blender_3B/model.dict
[ num words =  8008 ]
[TransformerGenerator: full interactive mode on.]
Traceback (most recent call last):
  File "parlai/scripts/safe_interactive.py", line 85, in <module>
    safe_interactive(parser.parse_args(print_args=False), print_parser=parser)
  File "parlai/scripts/safe_interactive.py", line 59, in safe_interactive
    agent = create_agent(opt, requireModelExists=True)
  File "f:\parlai\parlai\core\agents.py", line 406, in create_agent
    model = create_agent_from_opt_file(opt)
  File "f:\parlai\parlai\core\agents.py", line 361, in create_agent_from_opt_file
    return model_class(new_opt)
  File "f:\parlai\parlai\core\torch_generator_agent.py", line 453, in __init__
    self.model = PipelineHelper().make_parallel(self.model)
  File "f:\parlai\parlai\utils\torch.py", line 343, in make_parallel
    model.apply(self._place_modulelist)
  File "F:\Users\Erik.DESKTOP-E5E1V83\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 289, in apply
    module.apply(fn)
  File "F:\Users\Erik.DESKTOP-E5E1V83\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 289, in apply
    module.apply(fn)
  File "F:\Users\Erik.DESKTOP-E5E1V83\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 290, in apply
    fn(self)
  File "f:\parlai\parlai\utils\torch.py", line 389, in _place_modulelist
    layers[layer_no] = layer.to(layer_gpu)
  File "F:\Users\Erik.DESKTOP-E5E1V83\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 443, in to
    return self._apply(convert)
  File "F:\Users\Erik.DESKTOP-E5E1V83\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 203, in _apply
    module._apply(fn)
  File "F:\Users\Erik.DESKTOP-E5E1V83\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 203, in _apply
    module._apply(fn)
  File "F:\Users\Erik.DESKTOP-E5E1V83\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 225, in _apply
    param_applied = fn(param)
  File "F:\Users\Erik.DESKTOP-E5E1V83\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 441, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 11.00 GiB total capacity; 8.74 GiB already allocated; 2.59 MiB free; 8.75 GiB reserved in total by PyTorch)

**Comment by minimumnz** [comment]
Try and ensure your card isn't running any other processes. I got the 3B model to run on GTX 1080TI but needed to kill my gnome process.

**Comment by GraphGrailAi** [comment]
> Try and ensure your card isn't running any other processes. I got the 3B model to run on GTX 1080TI but needed to kill my gnome process.

Could you reveal RAM amount that is enough and GPU memory of card?
