### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by johny7** [facebookresearch/ParlAI#2624]
Hello,

Installed clean Python 3.8.2 on Windows. Since that, no luck to proceed further with the installation of the library.

Tons of prerequisites are missing to make the command 
'python setup.py develop' to work, among what I have discovered so far:

- numpy
- scipy
- cython
- rust compiler and module
- boto3
- botocore ....

etc.

To install PyTorch I used:
pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

Currently I stuck on 
  File "Temp\easy_install-ce4qagyj\Pillow-7.1.2\setup.py", line 914, in <module>
setuptools.sandbox.UnpickleableException: RequiredDependencyException('\n\nThe headers or library files could not be found for zlib,\na required dependency when compiling Pillow from source.\n\nPlease see the install instructions at:\n   https://pillow.readthedocs.io/en/latest/installation.html\n\n')

But I am not sure that after number of experiments with dependencies my Python is in consistent state.

Did anyone tried to install the lib on an empty Python?
Also, I believe for using mode shall we use 'python setup.py build' command instead of develop?

**Comment by stephenroller** [comment]
We don't support windows right now. If you get it working, please detail what was needed.
