### ISSUE TITLE
Fine-tuning Blender on a custom dataset without persona

### ISSUE THREAD

**Issue by timsoraro** [facebookresearch/ParlAI#2625]
Hello! Thanks for open-sourcing Blender's code with the model weights.
I have a conversation dataset without personas as a `.txt` formatted this way:
```
<|startoftext|>Person 1: Hello.
Person 2: How are you?
Person 1: Good, you?
Person 2: All good.
<|endoftext|>
<|startoftext|>...
```
What should be the dataset structure in order for me to fine-tune Blender on my dataset?

**Comment by stephenroller** [comment]
We have extensive docs on creating your own datasets. See [here](https://parl.ai/docs/tutorial_task.html) and [here](https://colab.research.google.com/drive/1bRMvN0lGXaTF5fuTidgvlAl-Lb41F7AD#scrollTo=KtVz5dCUmFkN)
