### ISSUE TITLE
Blender Telegram messenger support

### ISSUE THREAD

**Issue by GraphGrailAi** [facebookresearch/ParlAI#2628]
**Is your feature request related to a problem? Please describe.**
https://github.com/facebookresearch/ParlAI/tree/master/parlai/chat_service/  this tutorial how to implement my `chat_service` seems too complicated

**Describe the solution you'd like**
A clear Telegram bot via bot api https://core.telegram.org/bots/api

**Describe alternatives you've considered**
I have considered fast-durty solution: rewrite https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/safe_local_human/safe_local_human.py to make it interact with https://github.com/python-telegram-bot/python-telegram-bot - i mean hook text from stdout and passing them to bot.
This solution is not so good, i need to reimplement history and user session.

**Additional context**
Is there is another solution? Google it but no success

**Comment by stephenroller** [comment]
Telegram support would be an interesting addition to ParlAI, and we would probably accept the PR. Right now, we have no plans to implement it.
