### ISSUE TITLE
Problem trying to install 

### ISSUE THREAD

**Issue by IrvDelgado** [facebookresearch/ParlAI#2629]
Use this to open other questions or issues, and provide context here.
Hi, I'm kinda new to this, when I was trying to install it, I got the following error: 

 File "setup.py", line 30
    version=f'0.1.{DATE}{BUILD}',
                               ^
SyntaxError: invalid syntax

I used the command: 

git clone https://github.com/facebookresearch/ParlAI.git
cd ParlAI; python setup.py develop

Any Idea why?

Thank you.

**Comment by SangMyeongWoh** [comment]
me either. maybe 'f' is miss word. but i'm not sure

**Comment by stephenroller** [comment]
We only support python 3.6 or newer.
