### ISSUE TITLE
Blender - how to choose persona (not random)

### ISSUE THREAD

**Issue by GraphGrailAi** [facebookresearch/ParlAI#2636]
How to choose persona once (now it is changed every launch)?

Consider we have random here `random.seed(42)` https://github.com/facebookresearch/ParlAI/blob/master/parlai/scripts/safe_interactive.py
and also a list of personas http://parl.ai/downloads/blended_skill_talk/personas_list.txt

**Comment by stephenroller** [comment]
You can edit the interactive world.

https://github.com/facebookresearch/ParlAI/blob/5b108d73006696a82cbf3133b72f40a40f60ac0a/parlai/tasks/blended_skill_talk/worlds.py#L21

**Comment by aadil-srivastava01** [comment]
How can I change the persona of the model?
