### ISSUE TITLE
How can we change the Persona for the model for blended_skill_talk?

### ISSUE THREAD

**Issue by aadil-srivastava01** [facebookresearch/ParlAI#2644]
I'm trying to use the blender with a specified persona for the model instead of random one.

Have gone through this module
[https://github.com/facebookresearch/ParlAI/blob/5b108d73006696a82cbf3133b72f40a40f60ac0a/parlai/tasks/blended_skill_talk/worlds.py#L21](_load_persona(opt))

But unable to figure where exactly the model's persona is getting specified.

**Comment by aadil-srivastava01** [comment]
I was able to figure that out. In the same script we can make changes to  add a fixed persona.

```
    def get_contexts(self):
        random.seed()
        p = random.choice(self.contexts_data)
        p[1] = "your persona: i'm a customer support agent.\nyour persona: i help customers."
        print("######context:", p)
        print("######Len of context: ", len(p))
        return p[0], p[1]
```

**Comment by viprocket1** [comment]
> I was able to figure that out. In the same script we can make changes to add a fixed persona.
> 
> ```
>     def get_contexts(self):
>         random.seed()
>         p = random.choice(self.contexts_data)
>         p[1] = "your persona: i'm a customer support agent.\nyour persona: i help customers."
>         print("######context:", p)
>         print("######Len of context: ", len(p))
>         return p[0], p[1]
> ```

How many statements you where able to add?

**Comment by stephenroller** [comment]
I've personally give them up to 4 or 5 personas. and had it be okay.

**Comment by mavisakal** [comment]
> I was able to figure that out. In the same script we can make changes to add a fixed persona.
> 
> ```
>     def get_contexts(self):
>         random.seed()
>         p = random.choice(self.contexts_data)
>         p[1] = "your persona: i'm a customer support agent.\nyour persona: i help customers."
>         print("######context:", p)
>         print("######Len of context: ", len(p))
>         return p[0], p[1]
> ```

Is it possible to feed the context dynamically without hardcoding it?

**Comment by stephenroller** [comment]
Get contexts can return whatever you want.
