### ISSUE TITLE
BlenderBot Can't Process Certain Input

### ISSUE THREAD

**Issue by apoorva-sriv** [facebookresearch/ParlAI#2646]
Ran `python3 parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_90M/model` on Windows 10. BlenderBot can't process certain replies:

![Capture](https://user-images.githubusercontent.com/22404638/81418921-6b62c100-911b-11ea-9a33-1f7d0adce59d.PNG)

**Comment by stephenroller** [comment]
This is intentional, this is the safety layer kicking in. It does have false positives unfortunately.
