### ISSUE TITLE
Inference with BiEncoderRankerAgent

### ISSUE THREAD

**Issue by jokaslokas** [facebookresearch/ParlAI#2653]
Hey guys,

This might be a stupid question but I've been looking everywhere for help so I thought I'd ask here. 

I've train a BiEncoderRankerAgent and saved the model after validation, the model files with the dict and dict.opt files. I can't manage to figure out how I can now encode a sentence with my new model? Can anyone direct me to anything that can help? I'd just like to give the model a few sentences and return the encoding for each sentence. I can then rank based on cosine similarity manually. 

Thanks so much!

**Comment by zhenduow** [comment]
I have the same question here.
