### ISSUE TITLE
Project Recipe Failure

### ISSUE THREAD

**Issue by mathematicalmichael** [facebookresearch/ParlAI#2659]
**Bug description**
I tried to follow the example for the 90M model here: https://parl.ai/projects/recipes/ and encountered a missing file that prevented successful execution of pasted code.

**Reproduction steps**
`python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_90M/model`

**Expected behavior**
Model loads for interaction

**Logs**
```
...
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/parlai/zoo/blender/blender_ascii.txt'`
```

**Additional context**
Looking at `parlai/zoo/blender/build.py` 
```
17: txt_file = os.path.join(curr_dir, 'blender_ascii.txt')
```

and the results of `ls /usr/local/lib/python3.6/dist-packages/parlai/zoo/blender/`:
```
blender_3B.py   blender_9B.py  __init__.py  reddit_3B.py
blender_90M.py  build.py       __pycache__  reddit_9B.py
```

I can see that this is trying to open a version info file that does not exist. I could not find information on how to generate it properly, and the header in `build.py` shows `Blender models: please see <parl.ai/project/blender>.`, which leads to a nonexistent page. 

**Workaround**
Running `touch /usr/local/lib/python3.6/dist-packages/parlai/zoo/blender/blender_ascii.txt` lets everything keep running.

**Comment by stephenroller** [comment]
Thanks for reporting!
