### ISSUE TITLE
Unexpected socket error occured: OSError(0, 'Error')

### ISSUE THREAD

**Issue by JEM-Mosig** [facebookresearch/ParlAI#2660]
**Bug description**
When collecting dialogues on MTurk with a custom interface, at some point we get the output `Unexpected socket error occured: OSError(0, 'Error')` repeated in an unending loop and Turkers cannot access the HIT anymore. 

**Reproduction steps**
We have forked ParlAI at commit bfb4ef291c2d1ea84691efee55a1e4c0e1b8ce36 to fix a problem with locale qualifications in sandbox mode. (I know this is our problem when its our Fork, but perhaps somebody here has some insights.)
Running a two-worker dialogue task live gives the error mentioned above for no apparent reason at a random point in time. 

**Expected behavior**
The server does not crash.

**Additional context**
We start ParlAI from a Google Cloud Platform instance.

**Comment by stephenroller** [comment]
I really have no idea. @JackUrb?

There's a loooooot of differences it looks like. Running it on GCP, the fork, ... It would be helpful I guess if you could try to isolate when it happens. Perhaps by trying your task on a local machine (eliminating the GCP aspect), or by running a standard task in the same environment (eliminating that it's your task).

**Comment by JackUrb** [comment]
It's possible that GCP is killing your sockets somehow, I've seen this error before on a machine with particularly strict network security settings (and strange ssl defaults) that prevent socket connections from long-running processes. Unfortunately I don't know anything about your GCP setup.

You can get more info by importing traceback and printing the exception stack here:
https://github.com/facebookresearch/ParlAI/blob/b49eba4519856f6ab83b869b168c6af99863df47/parlai/mturk/core/socket_manager.py#L323

**Comment by JEM-Mosig** [comment]
Hello @stephenroller and @JackUrb . Thank you for your comments! I re-wrote the run script and based it more on the "Wizard of Wikipedia" task. It now runs without problems from GCP for thousands of HITs :)

**Comment by stephenroller** [comment]
Can you say some of the things you needed to do?
