### ISSUE TITLE
New Agent Link is Broken

### ISSUE THREAD

**Issue by AbdullaRifai** [facebookresearch/ParlAI#2669]
Hello, 

https://parl.ai/docs/tutorial_seq2seq.html# Is the provided link for ways to create a new agent (On the GitHub ReadMe) but It leads nowhere.

Has the feature lost support? Or is the link located someone else?

**Comment by stephenroller** [comment]
Hi, thanks for flagging. Will fix.

https://parl.ai/docs/tutorial_torch_generator_agent.html is the new link.
