### ISSUE TITLE
Ranker Agent guide?

### ISSUE THREAD

**Issue by zhenduow** [facebookresearch/ParlAI#2670]
Hi, 

It seems like there are only examples of training in this tutorial. 
https://parl.ai/docs/agent_refs/bert_ranker.html

Where can I find a guide on how to use trained/pretrained ranker agent on my dataset (query, candidates)?

Thank you so much!

**Comment by zhenduow** [comment]
There is a similar issue #2653 to this.

**Comment by stephenroller** [comment]
Check out the instructions for the bi-encoder on this page.

https://parl.ai/projects/polyencoder/
