### ISSUE TITLE
Twitter interactive mode error 

### ISSUE THREAD

**Issue by sseol11** [facebookresearch/ParlAI#2675]
**Bug description**
Please enter a clear and concise description of what the bug is.
The latest version of twitter interactive mode have error.
I ran the script like this:
python projects/twitter/seq2seq/interactive.py --task interactive --no-cuda

**Reproduction steps**
Enter steps to reproduce the behavior.

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Logs**
Please paste the command line output:

```
Traceback (most recent call last):
  File "projects/twitter/seq2seq/interactive.py", line 100, in <module>
    interactive(opt)
  File "/home/ubuntu/ParlAI/parlai/scripts/interactive.py", line 101, in interactive
    world = create_task(opt, [human_agent, agent])
  File "/home/ubuntu/ParlAI/parlai/core/worlds.py", line 1676, in create_task
    world = create_task_world(opt, user_agents, default_world=default_world)
  File "/home/ubuntu/ParlAI/parlai/core/worlds.py", line 1639, in create_task_world
    task_agents = _create_task_agents(opt)
  File "/home/ubuntu/ParlAI/parlai/core/worlds.py", line 1627, in _create_task_agents
    return create_task_agent_from_taskname(opt)
  File "/home/ubuntu/ParlAI/parlai/core/teachers.py", line 2230, in create_task_agent_from_taskname
    task_agents = teacher_class(opt)
TypeError: object() takes no parameters

```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by stephenroller** [comment]
Thanks for reporting.

**Comment by stephenroller** [comment]
I think honestly that code is just going to be broken indefinitely. I'm actively deleting it in another PR.

If you want something comparable, I'd recommend the tutorial transformer generator. You can see a tutorial [here](https://colab.research.google.com/drive/1bRMvN0lGXaTF5fuTidgvlAl-Lb41F7AD#scrollTo=KtVz5dCUmFkN).

**Comment by sseol11** [comment]
Yup! thanks! It's useful.

**Comment by stephenroller** [comment]
Closing since this seems resolved for now, but feel free to reopen if there are more questions.
