### ISSUE TITLE
Increase inference speed on 3B model.

### ISSUE THREAD

**Issue by abhinavbh08** [facebookresearch/ParlAI#2677]
I am using Titan X GPU to chat with the 3B blender model. The time for response is on an average 2.5-3 seconds. Is there any way we can decrease the time in which the model replies. Thanks for the help!

**Comment by stephenroller** [comment]
There's no easy way. We're absolutely interested in ways to make inference faster, but it's an area of active research.

**Comment by stephenroller** [comment]
(You can change the generation algorithm or lower the beam size, but these were the settings that we found most preferred by humans)
