### ISSUE TITLE
bert_ranker/bi_encoder_ranker

### ISSUE THREAD

**Issue by bhattaca** [facebookresearch/ParlAI#2679]
Hi, 
Quick question, 
what is the correct corresponding parameters for 
python -u examples/train_model.py \
    --init-model zoo:pretrained_transformers/bi_model_huge_reddit/model \
    --batchsize 16 -t convai2 \
    --model **transformer/biencoder** --eval-batchsize 6 \
    --warmup_updates 100 --lr-scheduler-patience 0 \
    --lr-scheduler-decay 0.4 -lr 5e-05 --data-parallel True \
    --history-size 20 --label-truncate 72 --text-truncate 360 \
    --num-epochs 1.0 --max_train_time 200000 -veps 0.5 -vme 8000 \
    --validation-metric accuracy --validation-metric-mode max \
    --save-after-valid True --log_every_n_secs 20 --candidates batch \
    --dict-tokenizer bpe --dict-lower True --optimizer adamax \
    --output-scaling 0.06 \
     --variant xlm --reduction-type mean --share-encoders False \
     --learn-positional-embeddings True --n-layers 12 --n-heads 12 \
     --ffn-size 3072 --attention-dropout 0.1 --relu-dropout 0.0 --dropout 0.1 \
     --n-positions 1024 --embedding-size 768 --activation gelu \
     --embeddings-scale False --n-segments 2 --learn-embeddings True \
     --share-word-embeddings False --dict-endt
is failing 
at save time as [TypeError: unsupported operand type(s) for *: 'AverageMetric' and 'float']

Is it possible to run it with 
using  **bert_ranker/bi_encoder_ranker**

**Comment by bhattaca** [comment]
its failing at save time as [TypeError: unsupported operand type(s) for *: 'AverageMetric' and 'float']

**Comment by stephenroller** [comment]
Thanks for reporting.

**Comment by stephenroller** [comment]
If it's possible, can you post your full stack trace? It also looks like you didn't finish copying the full itemset.

**Comment by bhattaca** [comment]
Sorry I should have done that first.
Here is where I got the params from 
https://parl.ai/projects/polyencoder/ {replaced to biencoder}
Here is the params list 
python3 -u examples/train_model.py \
    --init-model zoo:pretrained_transformers/bi_model_huge_reddit/model \
    --batchsize 16 -t convai2 \
    --model transformer/biencoder --eval-batchsize 6 \
    --warmup_updates 100 --lr-scheduler-patience 0 \
    --lr-scheduler-decay 0.4 -lr 5e-05 --data-parallel True \
    --history-size 20 --label-truncate 72 --text-truncate 360 \
    --num-epochs 3.0 --max_train_time 200000 -veps 0.5 -vme 8000 \
    --save-after-valid True --log_every_n_secs 20 --candidates batch \
    --dict-tokenizer bpe --dict-lower True --optimizer adamax \
    --output-scaling 0.06 \
     --variant xlm --reduction-type mean --share-encoders False \
     --learn-positional-embeddings True --n-layers 12 --n-heads 12 \
     --ffn-size 3072 --attention-dropout 0.1 --relu-dropout 0.0 --dropout 0.1 \
     --n-positions 1024 --embedding-size 768 --activation gelu \
     --embeddings-scale False --n-segments 2 --learn-embeddings True \
     --share-word-embeddings False --dict-endtoken __start__ --fp16 True \
     --model-file ~/ParlAIModels/bert_biencoder_test_1 \
     --dict-file zoo:pretrained_transformers/bi_model_huge_reddit/model.dict 


Here is the stack trace 
[ saving model checkpoint: /root/ParlAIModels/bert_biencoder_test_1.checkpoint ]
Traceback (most recent call last):
  File "examples/train_model.py", line 15, in <module>
    TrainModel.main()
  File "/root/ParlAI/parlai/scripts/script.py", line 79, in main
    return cls._run_args(None)
  File "/root/ParlAI/parlai/scripts/script.py", line 66, in _run_args
    script.run()
  File "/root/ParlAI/parlai/scripts/train_model.py", line 759, in run
    return TrainLoop(self.opt).train()
  File "/root/ParlAI/parlai/scripts/train_model.py", line 688, in train
    stop_training = self.validate()
  File "/root/ParlAI/parlai/scripts/train_model.py", line 440, in validate
    self.agent.receive_metrics(valid_report)
  File "/root/ParlAI/parlai/core/torch_agent.py", line 1109, in receive_metrics
    self.scheduler.valid_step(metrics_dict)
  File "/root/ParlAI/parlai/nn/lr_scheduler.py", line 348, in valid_step
    self.scheduler.step(metrics_dict['loss'])
  File "/opt/conda/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 353, in step
    if self.is_better(current, self.best):
  File "/opt/conda/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 385, in _cmp
    return a < best * rel_epsilon
TypeError: unsupported operand type(s) for *: 'AverageMetric' and 'float'

Thanks !

**Comment by bhattaca** [comment]
Some more information, this runs fine till the end of first epoch at which point it crashes. I cannot save any of the ranker models :(

**Comment by stephenroller** [comment]
Yeah it's happening on validation when checking whether the LR scheduler should be reduced. What's a little confusing to me is that we have been doing this for quite some time without issue.

What version of pytorch are you using?

As a temporary work around, you can fix the issue by replacing:

https://github.com/facebookresearch/ParlAI/blob/aad1e2e4d4f9c3457d137781f43d1ba126953cbb/parlai/nn/lr_scheduler.py#L348

with 

```python
self.scheduler.step(float(metrics_dict['loss']))
```

**Comment by bhattaca** [comment]
Thanks for reply, this works. I am using a little older version 1.0.0
