### ISSUE TITLE
--multitask-weights 1,3,3,3 Never found documentation on it

### ISSUE THREAD

**Issue by AbdullaRifai** [facebookresearch/ParlAI#2688]
I am just trying to understand this flag. As it is not in the command line argument documentation. Any insight would be helpful, thanks!

**Comment by stephenroller** [comment]
Defined here:

https://github.com/facebookresearch/ParlAI/blob/aad1e2e4d4f9c3457d137781f43d1ba126953cbb/parlai/core/params.py#L661-L669

Used here:

https://github.com/facebookresearch/ParlAI/blob/aad1e2e4d4f9c3457d137781f43d1ba126953cbb/parlai/core/worlds.py#L612-L620

and here:

https://github.com/facebookresearch/ParlAI/blob/aad1e2e4d4f9c3457d137781f43d1ba126953cbb/parlai/core/worlds.py#L719-L721

Essentially, this is used when you give multiple datasets to `-t`, and sets the relative probabilities for each of the tasks selected. with `-t convai2,wizard_of_wikipedia --multitask-weights 1,3`, we'll sample training examples from  the wizard dataset 3x more than convai2.

Feel free to reopen if you have more questions.

**Comment by AbdullaRifai** [comment]
Hello first of all thank you that example clearly displays its use as well as explanation. Sorry I'm a newbie at this when you say 3x training examples from the wizard dataset than convai2 (in your example) do you mean that when responses from convai2 and wizard of wikipedia collide on a specific question the one with the higher weight takes precedence? So what exactly is meant by sampling training examples? 

Thanks again for your earlier response :)

**Comment by jaseweston** [comment]
Yes. See also here in docs: 
 https://parl.ai/docs/tutorial_tipsntricks.html
