### ISSUE TITLE
script based interactive mode with multi-turn

### ISSUE THREAD

**Issue by sseol11** [facebookresearch/ParlAI#2691]
Hi, i have the multi-turn dataset. It consists of like:
```
A: utterance 1
B: utterance 2
<turn_over>
A: utterance 3
B: utterance 4
<turn_over>
...
```
I want to get the model output utterance as 'A' (A: model output ) using model interactive mode. So it is something like:
```
A: utterance 1
B: utterance 2
A: model output 
------------------
A: utterance 3
B: utterance 4
A: model output
...
```
Can you give any tips for it? 
Specifically, i want to use the Blender model for this.

**Comment by stephenroller** [comment]
You can use the display_model script to do this. With BlenderBot, make sure you add the `—skip-generation false` flag.

**Comment by sseol11** [comment]
Thank you for the reply. Can you give more details? I ran this script 
`python examples/display_model.py -t blended_skill_talk -mf zoo:blender/blender_90M/model --skip-generation false
`
It seems call the `[loading parlAI text data:/home/ubuntu/ParlAI/data/blended_skill_talk/valid.txt]`

Do i just put the data like valid.txt format?

**Comment by stephenroller** [comment]
Please see our [data tutorial](https://parl.ai/docs/tutorial_task.html) and the [colab tutorial](https://colab.research.google.com/drive/1bRMvN0lGXaTF5fuTidgvlAl-Lb41F7AD#scrollTo=KtVz5dCUmFkN) for examples on how to use your own dataset. [This comment](https://github.com/facebookresearch/ParlAI/issues/2632#issuecomment-629668578) is another common misunderstanding.

**Comment by priyanksonis** [comment]
I have dataset in this format:

```
user: utterance 1
model: utterance 2
<turn_over>
user: utterance 3
model: utterance 4
user: utterance 5
model: utterance 6
<turn_over>
model: utterance 7
user: utterance 8
model: utterance 9
user: utterance 10
model: utterance 11
<turn_over>
user: utterance 12
model: utterance 13
model: utterance 14
user: utterance 15
model: utterance 16
... 
```
So how can I finetune with this kind of conversation?

**Comment by stephenroller** [comment]
Please read the tutorials above.
