### ISSUE TITLE
Pre-train Chinese Blender chatbot

### ISSUE THREAD

**Issue by yguo33** [facebookresearch/ParlAI#2693]
I am going to build Chinese blender chatbot, the processes follow the paper: Recipes for building an open-domain chatbot. ParlAI provides fine tune stage code, so I only need to train a Chinese pre-trained model, then use that code to fine tune on Chinese datasets, is that right?

I still have some questions about how to pre train blender chatbot, as I know pytorch checkpoint just like *.checkpoint / *.pt / *.bin, but the init models provided from ParlAI are (model, model.opt, model.dict, model.dict.codecs), how can I get that format pre-train models and what are they?

I didn't find any info about this from (https://parl.ai/docs/index.html or https://arxiv.org/abs/2004.13637). Can you give me some tips?

Thank you for the help!

**Comment by stephenroller** [comment]
The pretraining happens in fairseq for speed, but you CAN do it in parlai if you want.

Unfortunately difficulties in releasing the data mean that we don’t have direct examples for you (right now). The main thing is to find a lot of pretraining data, get it in a one-turn-per-line format, then train a model using something like the hyperparameters we suggest in the paper.

**Comment by stephenroller** [comment]
Heads up though, this requires a very large number of GPUs to do at blender scale. (At least 256 imho)

**Comment by sheraleks** [comment]
@yguo33
Hi! Did you satisfy with pretraining BlenderBot for Chinese?
