### ISSUE TITLE
Controllable_dialogue fine tuning twitter_pretrained_baseline

### ISSUE THREAD

**Issue by 1019474263** [facebookresearch/ParlAI#2698]
Use this to open other questions or issues, and provide context here.
Hello, 

I'm reading the [controllable dialogue](https://parl.ai/projects/controllable_dialogue/) and would like to use the model on another dataset. I did not find the step that finetuning the twitter_pretrained_baseline on the convai2 dataset. I'm wondering what's the procedures to do it. I'm trying to finetune the twitter baseline on another dataset.

Thank you very much

**Comment by stephenroller** [comment]
We have a transformer tutorial generator that is pretty good and outperforms that twitter pretrained baseline, if you want. [Here](https://colab.research.google.com/drive/1bRMvN0lGXaTF5fuTidgvlAl-Lb41F7AD#scrollTo=KtVz5dCUmFkN) shows some examples.
