### ISSUE TITLE
Training model with own dataset

### ISSUE THREAD

**Issue by Wickky** [facebookresearch/ParlAI#2699]
I would like to confirm the steps to for training own data.
1. data preparation 
I have seen this to prepare own data
https://parl.ai/docs/tutorial_task.html#getting-a-new-dataset-into-parlai-the-simplest-way 
2. Training 
Using the above data path and run the following cmd.
python examples/train_model.py -t fromfile:parlaiformat --fromfile_datapath ./path/to/data.txt -m transformer/generator --multitask-weights 1,3,3,3 --init-model zoo:tutorial_transformer_generator/model --dict-file zoo:tutorial_transformer_generator/model.dict --embedding-size 512 --n-layers 8 --ffn-size 2048 --dropout 0.1 --n-heads 16 --learn-positional-embeddings True --n-positions 512 --variant xlm --activation gelu --skip-generation True --fp16 True --text-truncate 512 --label-truncate 128 --dict-tokenizer bpe --dict-lower True -lr 1e-06 --optimizer adamax --lr-scheduler reduceonplateau --gradient-clip 0.1 -veps 0.25 --betas 0.9,0.999 --update-freq 1 --attention-dropout 0.0 --relu-dropout 0.0 --skip-generation True -vp 15 -stim 60 -vme 20000 -bs 16 -vmt ppl -vmm min --save-after-valid True --model-file /tmp/test_train_90M -bs 4

I would like to know if I can train just using the above two steps? 
What else do I need? 
I also would like to request any simple tutorial for training model with own data. 
Thank you so much in advance!

**Comment by stephenroller** [comment]
@Wickky I think this has been answered in other threads,d right?
