### ISSUE TITLE
Emotional Embedding Extraction

### ISSUE THREAD

**Issue by AbdullaRifai** [facebookresearch/ParlAI#2702]
Hello, 

I just have an inquiry, is it possible to get emotional data related to a text (is that supported)? (Happy, Angry, Sad, so On)

Thank you in advance!

**Comment by stephenroller** [comment]
@EricMichaelSmith do you have any idea if EmpatheticDialogues or one of your style works might help?

**Comment by EricMichaelSmith** [comment]
Hi @AbdullaRifai we have a couple of datasets where conversational partners speak in utterances that are associated with specific emotions. For instance:
- EmpatheticDialogues (https://github.com/facebookresearch/ParlAI/tree/master/parlai/tasks/empathetic_dialogues)
- Image-Chat (https://github.com/facebookresearch/ParlAI/tree/master/parlai/tasks/image_chat) 
Is this the kind of thing that you're looking for?

**Comment by AbdullaRifai** [comment]
@EricMichaelSmith I wanted to see if there is support for extracting the emotional embedding of a text (Input text and/or Output text) of the model I trained using different tasks (or maybe even only one of the tasks you mentioned) similar to how we extract context from a sentence. So like I get a reading of Anger/Joy etc. purely based off text to use in creating my own functions. 

There is research done on emotional embeddings so I just wanted to see if ParlAI provides that functionality (without implementing it myself).

**Comment by EricMichaelSmith** [comment]
@AbdullaRifai Ah, sorry, didn't see that you had alluded to that in the issue title. No, unfortunately, as far as I know no such extraction tool is currently available in ParlAI (although you could certainly train an emotion classifier on one of the datasets that I mentioned to get one yourself).

**Comment by EricMichaelSmith** [comment]
@AbdullaRifai Actually, see the classifier open-sourced as part of EmpatheticDialogues here: https://github.com/facebookresearch/EmpatheticDialogues This isn't part of ParlAI, but it's a fastText classifier trained on the EmpatheticDialogues dataset.

**Comment by AbdullaRifai** [comment]
@EricMichaelSmith Perfect! Thank you, I will move forward with that information.
