### ISSUE TITLE
`narrative_qa` dataset has outdated (?) checksum

### ISSUE THREAD

**Issue by sjmielke** [facebookresearch/ParlAI#2707]
For the narrative_qa task, upstream's master ( https://github.com/deepmind/narrativeqa ) changed a month ago. Should the download checksum be updated or should we try to find the old version? Fwiw, the update concerns stories that seem only accessible via https now instead of http so I'm tempted to say we want the newer version...

**Comment by sjmielke** [comment]
Using this newer version downloads fine, so I would just take it (didn't test whether the pre-fix ones would've worked as well)?

**Comment by stephenroller** [comment]
Seems okay to me. I don't know of any models that depends on this older data.

**Comment by sjmielke** [comment]
Fixed in #2735.
