### ISSUE TITLE
Adding new data to an already trained model

### ISSUE THREAD

**Issue by AbdullaRifai** [facebookresearch/ParlAI#2709]
I already trained a model with basic scenarios I had in mind, but I was just wondering is it possible to append new examples into a trained model (Similar to what the self-feeding model does) after fully training it on the tasks i specified. 

Thanks in advance.

**Comment by stephenroller** [comment]
That’s a very good question. :) I don’t know.

**Comment by AbdullaRifai** [comment]
@stephenroller well thanks for ur previous answers to my issues, no one person has all the answers.

But does anyone else know or have an idea or an implementation that solves this problem?

**Comment by stephenroller** [comment]
I guess I don't quite understand the ask specifically. If it's like self-feeding, you could continuously add to the candidate set. If it's a generative model (where my head is these days), It's much harder...

**Comment by stephenroller** [comment]
Maybe @jaseweston wants to weigh in

**Comment by AbdullaRifai** [comment]
@stephenroller Oh just to clarify my question if it didn't make sense, my goal is to train a model (generative or otherwise) on some tasks. As the chat model receives questions, I would like to manually answer those questions and train the already trained model with these new parameters (So it will have the old parameters plus the new parameters appended to the model) to further advance the model moving forward. 

Was just checking if training a model that is already trained something that is supported as I didn't find any examples that do this.

**Comment by stephenroller** [comment]
You could add them to the training set and continue training, but doing this smoothly online is not something that exists right now. That said, it could be as easy as sending a message to the model with `labels` in the field, as that triggers a train step.

**Comment by AbdullaRifai** [comment]
Ah, I see thanks. I'll try passing a message to the agent with a label. That is a valid solution.
