### ISSUE TITLE
Tuning RankerAgent on my dataset

### ISSUE THREAD

**Issue by zhenduow** [facebookresearch/ParlAI#2710]
Hi, 

I have found the link https://parl.ai/projects/polyencoder/ very helpful. I learned to inference with polyencoder, but I find it not very accurate on my own dataset.

Is it possible for me to tune polyencoder on my own dataset with (query, candidate) pairs? I see that I have to specify the task for training, and the task must be defined in parlai.tasks. If I want to train on my dataset, do I have to define a task alike those existing ones?

Thank you very much!

**Comment by stephenroller** [comment]
Yes, if you want to train on your own data, you will need to define a task. We have a [tutorial](https://parl.ai/docs/tutorial_task.html).

**Comment by zhenduow** [comment]
Hi Stephneroller,

I run the code to finetune the model on my dataset. It says: 

RuntimeError: Please run "pip install 'git+https://github.com/rsennrich/subword-nmt.git#egg=subword-nmt'"

even after I installed pip install 'git+https://github.com/rsennrich/subword-nmt.git#egg=subword-nmt'. Do you know any possible reasons for this?

Thank you!

**Comment by stephenroller** [comment]
No, I don't understand. Maybe try `python -c 'import subword_nmt'` and see if it works?

**Comment by zhenduow** [comment]
Thank you! It is working after I test that, although I still do not know the reason.

**Comment by stephenroller** [comment]
What if you run: 
```
pip uninstall subword_nmt
pip install subword_nmt
```

**Comment by zhenduow** [comment]
> What if you run:
> 
> ```
> pip uninstall subword_nmt
> pip install subword_nmt
> ```

Actually, I did try that before. But that did not solve the problem then. I guess the reason could be I reboot the machine the other day and something I didn't know changed.

**Comment by stephenroller** [comment]
Do you need to reactivate you virtualenv or your conda env?

What OS are you on?

**Comment by zhenduow** [comment]
> Do you need to reactivate you virtualenv or your conda env?
> 
> What OS are you on?

I am on Linux. I didn't use any virtualenv.

**Comment by zhenduow** [comment]
I just finished the training of the poly encoder on my dataset (MSDialog) where you can find here:
https://ciir.cs.umass.edu/downloads/msdialog/

I see it automatically validates and tests on some sets. Are these sets automatically chosen from the entire dataset I provide to it? I ask this because I don't understand the results. I get good training results but a very bad validation&test result:

For training:
    clip  exs   gnorm  gpu_mem    lr  mean_loss  mrr  rank  total_train_updates   tpb  train_accuracy  updates
       0   30 .006222    .5880 5e-05  8.933e-06    1     1               158817 119.3               1       15

For valid:
valid:
    accuracy    bleu-4   exs     f1  gpu_mem  hits@1  hits@10  hits@100  hits@5    lr  total_train_updates  tpb
           0 1.061e-05 70584 .04865    .5235       0        0         0       0 5e-05               158817  577


The hits@100 is still 0....

**Comment by stephenroller** [comment]
Would you be interested in submitting a PR for MSDialog to be added to ParlAI? We would gladly welcome the addition.

Post your full training command and we can call out anything that looks weird. YOu might also want to run the `display_data` script with your dataset and post it (`python -m parlai.scripts.display_data --display-verbose --task msdialog`) and post this, so we can see if something looks really weird.

**Comment by zhenduow** [comment]
> Would you be interested in submitting a PR for MSDialog to be added to ParlAI? We would gladly welcome the addition.
> 
> Post your full training command and we can call out anything that looks weird. YOu might also want to run the `display_data` script with your dataset and post it (`python -m parlai.scripts.display_data --display-verbose --task msdialog`) and post this, so we can see if something looks really weird.

I just finished rerunning the experiment after changing the eval_candidate config. Now the results seem reasonable now.

Yes, I would like to provide my scripts of the MSDialog experiments. But I just took the easier way of using text data instead of creating a task. Do you still like an example of that?

**Comment by stephenroller** [comment]
Sure, can you share the script you wrote to convert the data so we can modify it to be a teacher directly?
