### ISSUE TITLE
 Improvements to CLI interface

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#2713]
We recently introduced the [parlai script](https://github.com/facebookresearch/ParlAI/blob/master/bin/parlai) ([actual source](https://github.com/facebookresearch/ParlAI/blob/master/parlai/scripts/parlai_exe.py)). This allows one to do things like `parlai display_data` and `parlai train_model` as shorthand for the typical `parlai -m parlai.scripts.display_data`.

We would like the following improvements to it, each which can be completed as a separate PR.

## `python -m parlai` should be equivalent to running this command.

This is done by doing adding an `if __name__ == '__main__'` clause to the parlai `__init__.py`.

## Standardize the access to scripts.

We recently introduced a [`ParlaiScript` class](https://github.com/facebookresearch/ParlAI/blob/master/parlai/scripts/script.py), which standardizes the access to the script, and adds some ways to invoke a script programmatically with kwargs instead of manually set up args. You may [see examples of it](https://colab.research.google.com/drive/1bRMvN0lGXaTF5fuTidgvlAl-Lb41F7AD#scrollTo=KtVz5dCUmFkN) being used, and how it's set up:

https://github.com/facebookresearch/ParlAI/blob/dec6f2295eb8cb6f8589c4e760221ec736283d38/parlai/scripts/interactive.py#L86-L92

However, only a handful of the existing scripts do this. We should standardize this in all scripts.

## Add subcommands so `--help` works

The best way to do this is have the main parlai script set up [sub-parsers](https://docs.python.org/3/library/argparse.html#sub-commands) which would determine which sub-command arguments it is going.

I would suggest (but one doesn't have to do this), that we add a `register_script` decorator in `loader.py` (see `register_teacher` and `register_agent` for an example). This `register_script` decorator should take a "script name" and any additional aliases it might have, for example

```python
@register_script("display_data", aliases=["dd"])
class DisplayData(ParlaiScript):
    # ...
```

Then, when the super-script is created, it can enumerate through the script registry to set up all of the major commands and their sub-parsers. If we use this approach, we will need to use importlib to automatically import everything inside parlai.scripts so that all of the registry is hit.

This registry should probably be used to also [update the documentation automatically](https://github.com/facebookresearch/ParlAI/blob/master/docs/source/generate_cli.py)

## Update references to `python examples/...` to `parlai ...` in the docs.

Hopefully most of them can be fixed with a regular expression replace in the code base.

## Tab/Auto-complete in the command line

We have so many options, it would be nice to get bash tab completion to help you find that crazy argument. This one is more experimental and you may wish to start by setting up a simple example. The [argcomplete](https://kislyuk.github.io/argcomplete/) library looks like it would be a real good fit for this and handle most of the heavy lifting. Keep in mind *it should be optional*, so the system should continue to work if the user has not installed argcomplete. You should also document how to set it up in the [tips and tricks](https://github.com/facebookresearch/ParlAI/blob/master/docs/source/tutorial_tipsntricks.rst).

**Comment by vedantpuri** [comment]
For the standardization, do I have to set it up for all scripts in the scripts folder or is there anything else as well ?

**Comment by stephenroller** [comment]
Just the scripts folder. I would even take just handling a few, we can upgrade others in future diffs:
- `train_model` / `eval_model`
- `display_data` /`display_model`
- `interactive` and maybe `self_chat`
- and `party` of course

**Comment by vedantpuri** [comment]
Out of the ones you mentioned, only ```self_chat``` seems to be the one not using ParlaiScript, so should I just upgrade that for now or are there others that I should look at ?

**Comment by stephenroller** [comment]
Hmm, we should really standardize everywhere I guess. I just don't want that to be a hard blocker between this and the others.

**Comment by stephenroller** [comment]
LOL
