### ISSUE TITLE
label_candidates

### ISSUE THREAD

**Issue by bhattaca** [facebookresearch/ParlAI#2715]
Hi @stephenroller , when we are creating a txt file dataset (task) of our own, how do I separate label candidates. ',' might be part of the individual candidates too. 
Looking at some of the convai datafiles looks like you might be using '|'. 

Thanks for your help.

**Comment by stephenroller** [comment]
Yes it’s the pipe character, |

**Comment by bhattaca** [comment]
Does this look right ?

text: Hi , how are you? [TAB] labels: i'am good.[TAB] label_candidates: i'am good | This was a good day | i am from Ohio [TAB] episode_end: True [NEWLINE]

**Comment by stephenroller** [comment]
No white space around the pipes, and no space before “labels”. Also be mindful that it’s episode_done.

Use the display_data.py script with the same —task fromfile arguments to test it.

**Comment by bhattaca** [comment]
Thanks @stephenroller!  qq, if i am setting task as a text file. how do I separate train/validation/testing. I am stuck when train_step goes looking for a validation set.
