### ISSUE TITLE
context and speakers separately

### ISSUE THREAD

**Issue by bhattaca** [facebookresearch/ParlAI#2725]
hi Stephen 

In transformers/polyencoder:Encode () function I have access to ctxt_inputs['ctxt_tokens'] 

but I would also like to find a way to separate out the individual speakers and the context (if present). Whats the best way to go about doing that.

**Comment by stephenroller** [comment]
Right, this will take a bit of work, but it is very accomplishable. The best way is to do this in the preprocessing, in `_set_text_vec`.

I did most of it here. It may be outdated, but you can definitely try to adapt this PR for your needs.

https://github.com/facebookresearch/ParlAI/pull/1863

My overall results were negative though, hence abandoning the diff. I'd welcome someone trying it again.
