### ISSUE TITLE
Model predicts nothing in interactive mode

### ISSUE THREAD

**Issue by Wickky** [facebookresearch/ParlAI#2726]
I use seq2seq and transformer/generator to train my total 31 episodes with 300 examples (including test/val) splits. 
Sometimes, the output predicts nothing in interactive mode.
I used the settings 
--ttim 300 -bs 2 -vtim 10 for both models.
Am I missing anything?
`Enter Your Message: hi

Enter Your Message: hello

Enter Your Message: `

**Comment by stephenroller** [comment]
It only sometimes prints nothing? Or it always prints nothing? It predicts None, or it predicts the empty string?

If it's only sometimes printing the empty string, then the model probably has learned this behavior. Especially if you have some null examples in your training data. If it's predicting None, then it seems like the interactive model isn't triggering correctly and I'm curious about any modifications you've made to ParlAI.

You can always set `--beam-min-length 10` and see if that forces output.

**Comment by Wickky** [comment]
@stephenroller  It's printing empty string and not always. Sometimes, I input a string and it returns empty string for the first time. But it replies for the second try. 
There's no null examples in the training data. Sometimes, I tried several times but I only get empty string replies from the model. 
For the code modification, I added premade tokenizer to the dict.py.

**Comment by stephenroller** [comment]
What UI are you doing this in? An IPython notebook? Your own UI?

300 utterances is far too little data for any neural model. I recommend having a few thousand at least: ConvAI2 is about 130k utterances. Our BlenderBot models use 1.5B utterances in pretraining, but we can get pretty far about 100k utterances.

**Comment by Wickky** [comment]
@stephenroller  I am using IPython notebook because interactive mode in terminal the text colors are quite difficult to read.

**Comment by stephenroller** [comment]
Hmm. What if you add the skip_generation=False option?

This is very strange. Can you make sure your data doesn’t have any empty strings?

**Comment by Wickky** [comment]
@stephenroller  Yes, I am pretty sure that there's no empty strings in the training data. 
I will test with skip_generation=False.
