### ISSUE TITLE
Training/ Fine-tuning Script for "Engaging Image Captioning via Personality"

### ISSUE THREAD

**Issue by riven314** [facebookresearch/ParlAI#2734]
Thanks for releasing the model code and the pretrained weight of Transresnet from "Engaging Image Captioning via Personality"! 
I would like to replicate the result stated in the paper and also do a fine-tuning on Transresnet with custom data. Would you plan to release training script and fine-tuning script for the work?

**Comment by stephenroller** [comment]
@klshuster

**Comment by klshuster** [comment]
hi @riven314, glad you're interested in the model

## Training from scratch
You can train using the following command:

```
python examples/train_model.py --task personality_captions \
-m projects:personality_captions:transresnet --model-file my_model_file  \
--image-mode resnet152 --batchsize 500 \
--validation-every-n-epochs 1 --validation-patience 5 \
--validation-metric accuracy --validation-metric-mode max \
--hidden-dim 500 --num-layers-all 2 --num-layers-text-encoder 1 \
--num-layers-image-encoder 1 --learningrate 0.0005 \
--embedding-type fasttext_cc \
--attention-dropout 0.4 --relu-dropout 0.4 --dropout 0.4 \
--n-heads 6 --ffn-size 1200 --n-layers 4 \
--embedding-size 300 --variant aiayn \
--truncate 32 
```

Note that we have no plans to release the pre-trained text encoder used to train our best model.

## Fine-tuning on other data
If you'd like to fine-tune the model, simply specify `--init-model models:personality_captions/transresnet/model` using the standard ParlAI training script (i.e., you can substitute it in the above command and change your `--task` to be whatever task you'd like 😄)

Hope that helps

**Comment by riven314** [comment]
Thanks!
