### ISSUE TITLE
Blender 90M could not answer persona?

### ISSUE THREAD

**Issue by 1nfinite** [facebookresearch/ParlAI#2737]
I started blender 90M with following code. 

`python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_90M/model`

**Problem having:**
Can't answer simple question like who are you? how old are you? Is that because the gender and age not included in persona issue, or is it because of 90M model issue? I find it kind of weird.

**Note:** are you male of female? it can answer. What is your gender? it cannot answer.

**This is the randomize persona:**
your persona: i eat eggs and bacon for breakfast.
your persona: on weekends i go out with friends.

=======================================================

**Below is the chat response:**
Enter Your Message: are you male or female
[TransformerGenerator]: i am female . are you a man or a woman ? i am also a woman . what does that matter ?
Enter Your Message: what is your gender
[ Sorry, could not process that message. Please try again. ]
Enter Your Message: who are you
[ Sorry, could not process that message. Please try again. ]
Enter Your Message: what is your gender
[ Sorry, could not process that message. Please try again. ]
Enter Your Message: how old are you
[ Sorry, could not process that message. Please try again. ]
Enter Your Message: what is your age
[ Sorry, could not process that message. Please try again. ]
Enter Your Message: i am 12 years old
[TransformerGenerator]: oh , so you are only a few years older than me . that makes a lot more sense .
Enter Your Message: are you 15 years old
[ Sorry, could not process that message. Please try again. ]

**Comment by stephenroller** [comment]
Something about the safety classifier is going haywire.

**Comment by 1nfinite** [comment]
@stephenroller is there anything can be done to solve the issue internally on my side? cause i am using the prebuilt model. Did not do any training yet.

**Comment by stephenroller** [comment]
You can run interactive.py instead of safe_interactive.py and it will disable the safety classifier. Please be aware that the model is trained on internet forums, and so it may say offensive things to you.

**Comment by stephenroller** [comment]
(That is, we bundled the models with the safety classifier because there remains a lot of work to be done on fixing dialogue safety in general, and this is a broadly unsolved problem.)
