### ISSUE TITLE
Question regarding multitask-weights parameter

### ISSUE THREAD

**Issue by mvh57** [facebookresearch/ParlAI#2743]
Hello again! In the command line code provided for fine-tuning , I'm trying to figure out why there are 3 models (BST, WW, CONVAI), but 4 weights provided in parameter 'multitask weights.' I would have guessed there would be one weight for every task. Thanks in advance!

`python examples/train_model.py -t blended_skill_talk,wizard_of_wikipedia,convai2:normalized -m transformer/generator --multitask-weights 1,3,3,3 --init-model zoo:tutorial_transformer_generator/model --dict-file zoo:tutorial_transformer_generator/model.dict --embedding-size 512 --n-layers 8 --ffn-size 2048 --dropout 0.1 --n-heads 16 --learn-positional-embeddings True --n-positions 512 --variant xlm --activation gelu --skip-generation True --fp16 True --text-truncate 512 --label-truncate 128 --dict-tokenizer bpe --dict-lower True -lr 1e-06 --optimizer adamax --lr-scheduler reduceonplateau --gradient-clip 0.1 -veps 0.25 --betas 0.9,0.999 --update-freq 1 --attention-dropout 0.0 --relu-dropout 0.0 --skip-generation True -vp 15 -stim 60 -vme 20000 -bs 16 -vmt ppl -vmm min --save-after-valid True --model-file /tmp/test_train_90M`

**Comment by stephenroller** [comment]
There were originally 4 tasks: blended_skill_talk, convai2:normalized, wizard_of_wikipedia, empathetic dialogues.

And 4 weights corresponding to those (1, 3, 3, 3).

You must have somehow dropped ED on accident.

**Comment by mvh57** [comment]
Great, thank you! I added ED back in.
