### ISSUE TITLE
Setting own persona

### ISSUE THREAD

**Issue by 1nfinite** [facebookresearch/ParlAI#2745]
I realise that the facebook blender model does generate a randomize persona.

I want to customise and fixed a set of persona with the facebook blender model.
eg: ["My name is XXX", "My favourite book is "YYY", ... ,... , .... ]

There is around 30-40 persona sentences that I would like to include in it.

How should I start and where can i refer?

**Comment by stephenroller** [comment]
#2644, #2636.

Note that the BlenderBot models only have a context history of 128 tokens, or about 6 sentences. You definitely won't be able to fit 40 personas into memory.

**Comment by jh-skaion** [comment]
hello @stephenroller, can the context history 128 token limit can be modified in order to create more complex personas?
Thank you for your time

**Comment by stephenroller** [comment]
We're working on methods for that but they're not ready to be shared publicly.

**Comment by jh-skaion** [comment]
is that something i can find on my end and modify it based on what i need?
or there is no way i can modify it?
Thanks
