### ISSUE TITLE
Issues with the 90m chat model

### ISSUE THREAD

**Issue by mwiby** [facebookresearch/ParlAI#2746]
**Bug description**
Can't run the command for the 90M chatting models

python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_90M/model

**Reproduction steps**
I run the cmd in the env

**Expected behavior**
Expecting it to download

**Logs**
Traceback (most recent call last):
  File "parlai/scripts/safe_interactive.py", line 11, in <module>
    from parlai.core.params import ParlaiParser
ModuleNotFoundError: No module named 'parlai'

```
Output goes here
```

**Additional context**

**Comment by stephenroller** [comment]
you need to follow the installation instructions at the root readme. (run `python setup.py develop` in the root of the repo)
