### ISSUE TITLE
Update PyPi version to include BlenderBot

### ISSUE THREAD

**Issue by rabidgremlin** [facebookresearch/ParlAI#2749]
Current version on PyPi is 0.1.20200416 which was released ~10 days before BlenderBot.
Would be super useful to have new version with BlenderBot included. Thanks

**Comment by stephenroller** [comment]
Done.

https://pypi.org/project/parlai/0.1.20200610/

**Comment by rabidgremlin** [comment]
Awesome. Thanks.
