### ISSUE TITLE
polyencoder , separate train/valid/test for txt dataset

### ISSUE THREAD

**Issue by bhattaca** [facebookresearch/ParlAI#2762]
Hi , 
if i am using the txt format to train on my own dataset , 
 -t fromfile:parlaiformat \
--fromfile_datapath /workspace/output.txt \

how do I pass a separate validation set ?

**Comment by stephenroller** [comment]
Easiest way is to name them `example_train.txt`, `example_valid.txt`, and `example_test.txt`, and then use `--fromfile-datapath example --fromfile-datatype-extension true`

**Comment by bhattaca** [comment]
@stephenroller , thanks as always, this will be good addition to the tutorial! One more thing, for train I have the usual 'text:' .... 'label:' .... and cand {batch} but for validation I want a fixed set of replies. How does such a validation format look. I understand for testing I can just have a newline separated set of  replies, but how do I set it up for validation ?
