### ISSUE TITLE
blocking Mturk react on mobile

### ISSUE THREAD

**Issue by kushalchawla** [facebookresearch/ParlAI#2763]
Hey. Using the default settings, I am able to participate normally in my survey using a mobile device. However, I want to block the survey from a mobile. 

Digging in further, there are two things which control this in app.jsx: 
isMobile() and BLOCK_MOBILE

"
handleIncomingHITData(data) {
    let task_description = data[task_description];
    if (isMobile() && BLOCK_MOBILE) {
      task_description = Sorry, this task cannot be completed on mobile devices.  +
        'Please use a computer.Task Description follows: +
        data[task_description];
    }
    this.setState({
      task_description: task_description,
      frame_height: data[frame_height] || DEFAULT_FRAME_HEIGHT,
      mturk_submit_url: data[mturk_submit_url],
    });
  }
"

The default value for BLOCK_MOBILE in ParlAI is True. Also, as per the above code, when I login via my mobile device, the task description appropriately changes, meaning isMobile() also returns True -> GOOD. 

However, the survey actually proceeds just normally. I cannot find the usage of BLOCK_MOBILE anywhere else in the code, which actually blocks the user, rather than just changing the task_description (which I am anyway not using in my custom component). How is this handled? I want to block the user from taking my survey if they are on a mobile device.

**Comment by JackUrb** [comment]
Indeed force blocking mobile on ParlAI MTurk react has broken at some point down the line. Unsure quite when this happened, but it was supposed to be that the block would also happen in the [`render`](https://github.com/facebookresearch/ParlAI/blob/db7600e498f3217d45f5b2df12dadd1ae2492ad5/parlai/mturk/core/react_server/dev/app.jsx#L143) method, simply returning the task description.
