### ISSUE TITLE
repeated answer

### ISSUE THREAD

**Issue by Erdene-Ochir0417** [facebookresearch/ParlAI#2774]
Hello thanks for sharing code 

I tested fine tuned model (with 30 epoch) but replies repeated answer. 
train code:
`python examples/train_model.py -t fromfile:parlaiformat --fromfile_datapath ./data.txt -m transformer/generator --multitask-weights 1,3,3,3 --init-model zoo:tutorial_transformer_generator/model --dict-file zoo:tutorial_transformer_generator/model.dict --embedding-size 512 --n-layers 8 --ffn-size 2048 --dropout 0.1 --n-heads 16 --learn-positional-embeddings True --n-positions 512 --variant xlm --activation gelu --skip-generation True --fp16 True --text-truncate 512 --label-truncate 128 --dict-tokenizer bpe --dict-lower True -lr 1e-06 --optimizer adamax --lr-scheduler reduceonplateau --gradient-clip 0.1 -veps 0.25 --betas 0.9,0.999 --update-freq 1 --attention-dropout 0.0 --relu-dropout 0.0 --skip-generation True -vp 15 -stim 60 -vme 20000 -bs 16 -vmt ppl -vmm min --save-after-valid True --model-file ./models/gurume -bs 16 -eps 30`

test code: 
`python examples/interactive.py -mf ./models/gurume`

output:
![Screen Shot 2020-06-19 at 7 49 56 AM](https://user-images.githubusercontent.com/29839095/85108096-ac351600-b241-11ea-991a-a1a09c957e30.png)

**Comment by DasShubhadeep** [comment]
@Erdene-Ochir0417 I am also facing the same issue. If you find any solutions please let me know.

**Comment by stephenroller** [comment]
Yes, transformers, especially this baseline one, have strong problems with repetition. It's an area of active research.  You can use beam search arguments like `--beam-context-block-ngram 3`, or `--inference nucleus --topp 0.7`.

**Comment by Erdene-Ochir0417** [comment]
thanks for replying. 
I tried beam search on my prediction but answer was repeated.
`python examples/interactive.py -mf ./models/gurume --beam-context-block-ngram 3`

where can I add this argument? on training or on prediction?

**Comment by stephenroller** [comment]
That incantation is correct.
