### ISSUE TITLE
Aggregate logs in a single folder

### ISSUE THREAD

**Issue by vedantpuri** [facebookresearch/ParlAI#2782]
**Is your feature request related to a problem? Please describe.**
Using ParlAI locally I notice that several log files clutter the workspace and there should be a single directory where we output the logs to.

**Describe the solution you'd like**
Redirect all logs to ```ROOT/.logs/``` or something similar.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by stephenroller** [comment]
I’ve yet to figure out the source of those log files. They consistently show up after running unit tests.

**Comment by stephenroller** [comment]
Perhaps they come from mturk and/or chat service tests?

**Comment by vedantpuri** [comment]
If everything is being inherited/using the base logger, might be worthwhile to log the file name too so that we can trace which logs are coming from where (just for debugging)
