### ISSUE TITLE
Manual override of transformer / generator model output?

### ISSUE THREAD

**Issue by mvh57** [facebookresearch/ParlAI#2787]
Hello all, 
I have a question regarding a fine tuned 90M parameter model that I've trained for my specific task. I'm hoping to selectively, manually override transformer/generator output in order to set custom historical context for model to use in generating subsequent output. More informally, I want to insert custom statements (as if they were said by the generator) into the historical dialogue that the model will "think" it said previously. 
Thanks for your help.
Michael

**Comment by stephenroller** [comment]
You can use agent.self_observe. It’s defined for all the torch agents, including the 90M model.

**Comment by mvh57** [comment]
Thank you, this is helpful. More specifically, how would I initialize the interactive chat (using BST task) with the Transformer-Generator having first speaking turn (something like "Hello, I am transformer-generator agent. Please tell me a little about yourself"), followed by the human_agent;  importantly I want the transformer to use the first hard-coded statement as context in subsequent responses. Thanks!

**Comment by stephenroller** [comment]
For that I would recommend modifying the dataset itself.
