### ISSUE TITLE
Printing response time with 'interactive_web' script?

### ISSUE THREAD

**Issue by teboozas** [facebookresearch/ParlAI#2794]
Hi, I have a question on 'interactive_web' scripts.

Is there a way to print out or record response time of chat agent? (e.g. BlenderBot)
I've tried to do so, but I'm in trouble with it right now.

Additionally, can I add a local time clock in the script?

**Comment by stephenroller** [comment]
Sure, put a timer around this line:

https://github.com/facebookresearch/ParlAI/blob/c51263a42cca350206def588c8a919bfaee44c08/parlai/scripts/interactive_web.py#L188

If you want to `import parlai.utils.logging as logging` and call `logging.info("Response time: {response_time}", I'd welcome it as a PR.
