### ISSUE TITLE
f

### ISSUE THREAD

**Issue by ob7hhh** [facebookresearch/ParlAI#2795]
**Bug description**
Please enter a clear and concise description of what the bug is.

**Reproduction steps**
Enter steps to reproduce the behavior.

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Logs**
Please paste the command line output:

```
Output goes here
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by stephenroller** [comment]
This looks like it was an error. Open a new one if you need to file a bug report.
