### ISSUE TITLE
Using a knowledge graph in fine-tuning

### ISSUE THREAD

**Issue by Valdegg** [facebookresearch/ParlAI#2796]
I've been trying out your awesome framework,  for my research on incorporating knowledge graphs into dialogue models.

I see that it's possible to fine-tune on custom text data,  and that it's also possible to fine-tune on the Wizard of Wikipedia data set which uses the knowledge from wikipedia, which I assume is represented as some sort of knowledge graph (KG). 

But is it possible to use ParlAI to fine-tune a model on a custom KG? 

It would be awesome,  since having a KG can make a dialogue agent much richer.

**Comment by Valdegg** [comment]
I could just generate a dialogue data set from a knowledge graph and a text data set,  but what I was thinking is having the model able to retrieve information from a custom knowledge base (much like WoW does for wikipedia).

Is that far-fetched?

**Comment by stephenroller** [comment]
The Wizard of Wikipedia generative model is a good choice (https://github.com/facebookresearch/ParlAI/blob/master/projects/wizard_of_wikipedia/generator/agents.py). We represent the knowledge as unstructured text, but I've found that these models can learn to deal with serialized structured data pretty easily.

**Comment by Valdegg** [comment]
Thanks, Stephen!

That script is a bit cryptic...  

Which part of it loads the knowledge data? 

I'm wondering what to change to customise it for my own data.
