### ISSUE TITLE
Confusions in the training and evaluation of blender and BST

### ISSUE THREAD

**Issue by zhongpeixiang** [facebookresearch/ParlAI#2798]
Thank you very much for your exciting work! I have a few questions regarding the training and evaluation of blender and BST.

### Q1
In the [blender project](https://parl.ai/projects/recipes/), the model is trained with a WoW topic only one-third of the time and evaluated with randomly chosen WoW topics (also one-third of the time). However, in the [BST project](https://parl.ai/projects/bst/), it seems that all BST datasets (ConvAI2, WoW, ED and BST) are augmented with both topic and persona during training. Is the evaluation on BST datasets in the same way (i.e., all datasets are augmemted with both topics or personas)? If my understanding above is correct, any specific reasons why blender doesn't follow the BST way to train on BST datasets?

### Q2
When I actually talk to the agents in either the [blender project](https://parl.ai/projects/recipes/) or the [BST project](https://parl.ai/projects/bst/), what are the topics and personas assigned to the agent when the conversation starts? (default ones? or randomly choosen? or based on the first utterance? or other ways?)

Thanks

**Comment by stephenroller** [comment]
Q2: random ones from the dataset

Q1: we wanted the model to be more robust when the extra information wasn’t available, so we only gave it to it some of the time. I THINK at validation time we give the model access to all info, but I would need to carefully check the code.

**Comment by zhongpeixiang** [comment]
I see, thanks.

During training, is the persona also given some of the time or all the time?

Do you think randomly dropping topic or persona during training would help?

Thanks,
Peixiang

**Comment by stephenroller** [comment]
Yes, I do. It’s an experiment I’ve wanted to run for a while but never got around to it. Would be curious to hear results if you get them.
