### ISSUE TITLE
Duplicate python in example commands in the docs

### ISSUE THREAD

**Issue by hnarayanan** [facebookresearch/ParlAI#2799]
There seems to be some problem with the help documentation generation system that duplicates the word `python` in each command. E.g. 

The following screenshot shows it is a more general problem.

<img width="690" alt="Screenshot 2020-06-27 at 3 02 30 pm" src="https://user-images.githubusercontent.com/661446/85924028-6e5e7000-b887-11ea-94b3-1ef20a5c9fa8.png">

Fixing this will help make these commands less misleading and easier to copy-and-paste.

**Comment by stephenroller** [comment]
Thanks for filing!
