### ISSUE TITLE
Confusions in the Blended Skill Talk dataset

### ISSUE THREAD

**Issue by wanghaoran-ucas** [facebookresearch/ParlAI#2801]
I don't understand the details of these datasets, Blended Skill Talk, Wizard of Wikipedia, Empathetic Dialog, ConvAI2 from parlAI (https://parl.ai/projects/bst/).

I have read the paper on each of these datasets, but the papers don't refer to column definition or file definition while they describe the kind or purpose of dataset.
Can someone tell me more about these datasets?

In particular, my question is:
I don't understand what the following files are. How can I use them?

(Blended Skill Talk)
"ed_persona_topicifier__test__experiencer_only.json"
"ed_persona_topicifier__train__both_sides.json"
"ed_persona_topicifier__train__experiencer_only.json"
"ed_persona_topicifier__valid__experiencer_only.json"
"persona_list.txt"
"safe_personas.txt"
"topic_to_persona_list.txt"
"train.txt"

(Wizard of Wikipedia)
"topic_splits.json"
"test_topic_split.json"
"valid_topic_split.json"

Are there any documents about the definition of these datasets?

**Comment by stephenroller** [comment]
All the datasets have teachers that load them. You can see, for example, by running:

```
python -m parlai.scripts.display_data -t convai2
```

I recommend you read our [quickstart](https://parl.ai/docs/tutorial_quick.html) tutorial.

**Comment by llStringll** [comment]
@wanghaoran-ucas Refer the readme.md of this directory https://github.com/facebookresearch/ParlAI/tree/master/parlai/tasks/blended_skill_talk, it's very clear there, I read it

**Comment by wanghaoran-ucas** [comment]
thank you @llStringll @stephenroller
