### ISSUE TITLE
teacher of fromfile

### ISSUE THREAD

**Issue by Erdene-Ochir0417** [facebookresearch/ParlAI#2808]
Hello thanks for sharing code

I have question about teacher. What is the teacher of fromfile? If I put text data into blended_skill_talk task folder, I get same result of fromfile?
```
python examples/train_model.py -t fromfile --fromfile-datapath ../train_gurume/ --fromfile-datatype-extension true -m transformer/generator........
```

**Comment by stephenroller** [comment]
I’m sorry, I don’t understand the question. Could you try to clarify?
