### ISSUE TITLE
Remove use of deprecated apex FP16_Optimizer API

### ISSUE THREAD

**Issue by anj1** [facebookresearch/ParlAI#2813]
**Bug description**
When running any model with FP16 support, and the latest version of nvidia apex (e.g. commit [44532b3](https://github.com/NVIDIA/apex/commit/44532b30a4fad442f00635a0f4c8f241b06c2315)), one gets the following deprecation warning:

```
Warning:  FP16_Optimizer is deprecated and dangerous, and will be deleted soon.  If it still works, you're probably getting lucky.  For mixed precision, use the documented API https://nvidia.github.io/apex/amp.html, with opt_level=O1.
```

It is recommended to upgrade to the new apex amp api, as documented on this page https://nvidia.github.io/apex/amp.html#for-users-of-the-old-fp16-optimizer

**Comment by stephenroller** [comment]
It still works fine. When pytorch 1.6 comes out I think we’ll phase out apex.
