### ISSUE TITLE
Number of words in dictionaries

### ISSUE THREAD

**Issue by enkhjile** [facebookresearch/ParlAI#2814]
Hello. Thanks for your amazing work.

I am trying to fine tune blender 3B model on my own datasets and I realized number of words in blender_90M and blender_3B dictionaries are different.
blender_90M default model.dict file has 54944 words but blender_3B has only 8008 words. I peeked into mode.opt files and dict_file options were different. 

- 90M: dict_file = /checkpoint/parlai/zoo/new_reddit/newreddit_trained20190909_usedfordodeca/model.dict which I assume dictionary build during pretraining
- 3B: dict_file = /checkpoint/parlai/zoo/meena/20200319_meenav0data_tall_2.7B_adamoptimizer/20200319_13.3ppl_200kupdates/model.dict which I am not sure about.

So when fine tuning  blender 3B model, which dictionary should I use?

**Comment by stephenroller** [comment]
Use the one with the 3B model. They were trained with different dictionaries because the 90M is a baseline we trained about a year ago.

**Comment by enkhjile** [comment]
> Use the one with the 3B model. They were trained with different dictionaries because the 90M is a baseline we trained about a year ago.

@stephenroller 
Thanks for your reply. I will use 3B model dictionary. 

What if I fine tune from 3B model pre trained on reddit (not trained on BTS tasks)? Should I still use dictionary with 8008 words (the model trained on BTS tasks)? or should I used dictionary from 3B model pre trained on reddit?

**Comment by stephenroller** [comment]
All 3B and 9B models use the same dictionary. Also, the BTS models are fine-tuned versions of the Reddit models, hence having the same dict.
