### ISSUE TITLE
Start training loop in Pycharm for debug

### ISSUE THREAD

**Issue by 731935354** [facebookresearch/ParlAI#2818]
Hi, I am a beginner of ParlAI. I wonder how can I start a training loop in Pycharm for debugging. 

The motivation behind this is that I want to write my own model which will use manual features and the output of poly-encoder (as a feature, currently I have successfully trained poly-encoder on my own dataset). I tried to figure out how to do this by inspecting DRQA agent (as it uses manual features as well), but my mind is still in a mess. If I can debug in Pycharm, I can see the detailed function invocations, from which I will figure out how to write my customized model hopefully.

I also plan to do more customization in the future. This is another reason for enabling debug mode.

Any suggestion will be appreciated. Thanks!

**Comment by klshuster** [comment]
You can manually instantiate a train loop via the following code block:

```python
from parlai.scripts.train_model import TrainModel
TrainModel.main(
    model_file='/tmp/model_file',
    task='<task>',
    model='transformer/polyencoder',
.
.
.
)
```

You can add more arguments as you find necessary (hyperparams etc.). The `TrainModel` args can be found [here](https://github.com/facebookresearch/ParlAI/blob/master/parlai/scripts/train_model.py#L53), while model specific args are generally in the `parlai/agents/<agent>/<agent>.py` file. For the poly-encoder, you'll find relevant args [here](https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/transformer/polyencoder.py#L36) and [here](https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/transformer/transformer.py#L23)

Hope that's helpful!

**Comment by 731935354** [comment]
@klshuster That's exactly what I'm looking for. Thanks very much!

**Comment by klshuster** [comment]
Glad to hear - closing for now, please reopen if there are additional concerns
