### ISSUE TITLE
Quick Question about Persona Functionality in Blender

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#2820]
Hi, I just had a really quick question about the persona functionality in Blender,

I was wondering if the "Persona" of blender bots are just directly added to the context/history (like normal dialog turn exchanges) or if they are conditioned into the model in a specific way? Does the persona of the blender model still seem to affect much later turns in the conversation (such as 8 - 15 dialog turn/exchanges point)?

Thank you for your time

**Comment by stephenroller** [comment]
The persona is provided as a line in the dialogue context prefaced with “your persona:”.

In the current implementation, after the persona falls out of the context horizon, the model loses access to it.

**Comment by josharnoldjosh** [comment]
Thank you!

**Comment by bakszero** [comment]
> The persona is provided as a line in the dialogue context prefaced with “your persona:”.
> 
> In the current implementation, after the persona falls out of the context horizon, the model loses access to it.

How long is this context horizon on average? @stephenroller @josharnoldjosh

**Comment by stephenroller** [comment]
128 BPE tokens. About 6 turns.

**Comment by bakszero** [comment]
Thanks!

**Comment by josharnoldjosh** [comment]
> The persona is provided as a line in the dialogue context prefaced with “your persona:”.

Should the human say the "your persona: ..." or should the Blender model say/self observe "your persona: ..." ?

Thanks!

**Comment by stephenroller** [comment]
We augment the human’s first message to include this information.

**Comment by josharnoldjosh** [comment]
Would this mean its possible to ignore overriding the return value of `def _load_personas(opt):` and just have your human agent `act()` that returns an utterance like "your persona: i am a basketball player" and then Blender can `observe()` it, and this is enough for blender to attempt to take on the specified persona? Thanks for your time!
