### ISSUE TITLE
Setting persona of Blender bot while also setting history

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#2823]
Hi,

I have modified `worlds.py` to return the persona I want for the Blender bot. However, I am also using `agent.self_observe` before the first call to parley is made. Thus, in my logs I see the self observe text print before the agent persona.

Is the agent persona being appended to the context history after any calls `agent.self_observe`? If so, how can I get the persona context to be appended before any calls to `agent.self_observe`? Should I just add my own persona using `agent.self_observe` and not do it through the `convai` `worlds.py` task?

Thanks!

**Comment by viprocket1** [comment]
Hey ! can you help my out ? 
>https://github.com/facebookresearch/ParlAI/issues/2633#issuecomment-655225976 
thank you
