### ISSUE TITLE
CUDA out of memory while finetuning blender 3B model 

### ISSUE THREAD

**Issue by priyanksonis** [facebookresearch/ParlAI#2827]
Hi Team,
I am trying to finetune blender 3B model on machine having 4gpus of 12Gb RAM (NVIDIA GeForce GTX TITAN X), This is main part of the code:

`TrainModel.main(
    task='fromfile:parlaiformat',
    fromfile_datapath='/data/priyank/parlaifinetuningdata/clientdata.txt',
    validation_every_n_epochs=0.25,
    attention_dropout=0.0,
    batchsize=128,
    model='transformer/generator',
    embedding_size=2560,
    ffn_size=10240 ,
    variant='prelayernorm',
    n_heads=32,
    n_positions=128,
    n_encoder_layers=2,
    n_decoder_layers=24, 
    history_add_global_end_token='end',
    delimiter='  ',
    dict_tokenizer='bytelevelbpe',
    dropout=0.1,
    fp16='True',
    init_model='zoo:blender/blender_3B/model',
    dict_file='zoo:blender/blender_3B/model.dict',
    label_truncate=128,
    log_every_n_secs=10,
    lr=7e-06,
    lr_scheduler='reduceonplateau',
    lr_scheduler_patience=3,
    optimizer='adam',
    relu_dropout=0.0,
    activation='gelu',
    model_parallel=True,
    save_after_valid=True,
    text_truncate=128,
    truncate=128,
    warmup_updates=100,
    fp16_impl='mem_efficient',
    update_freq=2,
    gradient_clip=0.1,
    skip_generation=True,
    validation_patience=10,
    validation_metric='ppl',
    validation_metric_mode='min',
    model_file='/data/priyank/finetuned_3B_1000eps/model_3B',
)`
 
It gives me error:
`RuntimeError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 11.91 GiB total capacity; 9.80 GiB already allocated; 9.19 MiB free; 9.89 GiB reserved in total by PyTorch)`

Even I am using multiple gpus `(os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3")`

---------------------------------------------------------------------------------------------------------------------------------------------------------------------
Same with command line:

`python examples/train_model.py -t fromfile:parlaiformat --fromfile_datapath /data/priyank/parlaifinetuningdata/clientdata.txt -veps 0.25 --attention-dropout 0.0 --batchsize 128 --model transformer/generator --embedding-size 2560 --ffn-size 10240 --variant prelayernorm --n-heads 32 --n-positions 128 --n-encoder-layers 2 --n-decoder-layers 24 --history-add-global-end-token end --delimiter '  ' --dict-tokenizer bytelevelbpe  --dropout 0.1 --fp16 True --init-model zoo:blender/blender_3B/model --dict-file zoo:blender/blender_3B/model.dict --label-truncate 128 --log_every_n_secs 10 -lr 7e-06 --lr-scheduler reduceonplateau --lr-scheduler-patience 3 --optimizer adam --relu-dropout 0.0 --activation gelu --model-parallel true --save-after-valid True --text-truncate 128 --truncate 128 --warmup_updates 100 --fp16-impl mem_efficient --update-freq 2 --gradient-clip 0.1 --skip-generation True -vp 10 -vmt ppl -vmm min --model-file /data/priyank/finetuned/finetuned_3B`

I tried reducing bacth size and truncating.

**Comment by stephenroller** [comment]
For that many gpus i would recommend more like batchsize 32 or maybe even 16. You can add dynamic_batching=“full” to get a bit more bang for your buck and help identify your limit earlier.

**Comment by priyanksonis** [comment]
Tried with batchsize of 32, 16 and adding `dynamic_batching=“full”` that didn't work.

Do you think that my gpu specs are not sufficient ?, we may need individual gpu of memory more than 12GB (as per written on the project page at [https://parl.ai/projects/recipes/](url) :The 2.7B model requires a 32GB V100 in order to fine tune (limited to Adafactor), but may be fine tuned with ADAM with 2 or more V100s.) ?

**Comment by stephenroller** [comment]
No, I feel like something is off. The model should only take 2.7e9*16 bytes to store optimizer state, activations, and weights. Ive fine tuned with 128gb of gpu ram without issue. 48gb should definitely be enough with sufficiently small batch size. What about 8 batchsize?

**Comment by stephenroller** [comment]
Fwiw from that error message it does look like SOMETHING else is using 2gb of gpu memory. Perhaps X11 or the window manager?

Also, we use heuristics to guess what layers should go on what devices.

https://github.com/facebookresearch/ParlAI/blob/b378646feb2c4088f3f639c9dca26509f6624d89/parlai/utils/torch.py#L357

Maybe the heuristics are a bad choice for your GPUs. Watch nvidia-smi while the program is running. If gpu0 is being much more heavily utilized than the others, it might be worth increasing that 3 magic constant to a larger number like 16, but trial and error is the only suggestion I have here.
