### ISSUE TITLE
Blender in spanish? Blender in french?

### ISSUE THREAD

**Issue by alelasantillan** [facebookresearch/ParlAI#2830]
**Is your feature request related to a problem? Please describe.**
It is usual to find models in english. BERT has its own multilingual version that works really well, how can this be done for Blender?
**Describe the solution you'd like**
I would like to add a flag -language ES or -language FR and that Blender can manage in those languages

**Describe alternatives you've considered**
I've considered translate from ES to EN both in input and output of the chat.

**Additional context**
None

**Comment by stephenroller** [comment]
BlenderBot as a model depends on having extremely large amounts of conversational pretraining data. I’m not aware of comparable corpora to the pushshift.io dataset in non-English languages, but I would be excited to see it work.

There’s some work like multilingual BART that is worth a shot, fwiw.

**Comment by alelasantillan** [comment]
@stephenroller will take a look at that! Tks
