### ISSUE TITLE
Is the released Blender model already finetuned?

### ISSUE THREAD

**Issue by zhongpeixiang** [facebookresearch/ParlAI#2832]
Hi, thank you for sharing your work for blender.

Q1. As the title says, I would like to know if the released blender models 90M, 2.7B,.. are already finetuned on the BST tasks. 

Q2. I am interested in pretraining a Transformer model using Fairseq, similar to your approach in Blender. May I know how did you use the pretraining text processed by HuggingFace tokenizers in the Fairseq framework?  (one tokenized sentence per line in the source and target files?) 

Q3. I would like to confirm that the blender uses Byte-level BPE tokenizer with vocab size of 8K. GPT-2 has a vocab size of around 50K, so the 8K vocab size seems a bit small at first glance (I'm not famillier with bpe tokenizers).

Thanks,

**Comment by stephenroller** [comment]
1. We release fine tuned models AND pre-trained models before fine-tuning. Their filenames contain blender and reddit (e.g. `zoo:blender/reddit_3B/model`)
2. Trained a tokenizer on something like 1% of the data and then pre-tokenized the full corpus, training it in fairseq. The process looks the same as in the [fairseq training tutorial](https://fairseq.readthedocs.io/en/latest/getting_started.html#training-a-new-model).
3. 8K is a bit on the smaller side, but has been used quite a bit in the literature. I've begun feeling like it doesn't make that much of a difference. In the 9.4B model, expanding to a vocab of 50k would have only increased parameters by a measly 2%. Compare this to the days when word2vec/glove/fasttext ruled: we had huge vocabularies and the vast majority of parameters could be argued (implicitly and explicitly) to be in the embedding table.

One small note is that we do use the "prefix_space" option of the Byte-level BPE tokenizer, which helps fix a lot of redundancy in the GPT-2 50k dictionary.

**Comment by zhongpeixiang** [comment]
Thank you for the explanation! I will stick with the 8K vocab size since my model has aorund 300M params and the vocab size does matter a bit.

**Comment by stephenroller** [comment]
FWIW, that sized model can be comfortably trained in ParlAI.
