### ISSUE TITLE
Don't print opts for any example scripts that aren't known to be true

### ISSUE THREAD

**Issue by EricMichaelSmith** [facebookresearch/ParlAI#2837]
As of a few weeks ago, we stopped printing the opt args when running `examples/train_model.py` because we realized that the printed opts were not always correct. But this can be the case when calling other scripts in `examples/` as well: for instance, when calling `python examples/display_model.py -mf zoo:blender/blender_90M/model -t blended_skill_talk`, fields like `model` and `dict_file` are shown as `None` but clearly aren't in reality. @stephenroller points out that anywhere where `--model-file` is being set *possibly* outputs these incorrect args. This task is to identify such cases and fix the printed args, or at a minimum stop printing incorrect args

**Comment by klshuster** [comment]
we now print arguments
