### ISSUE TITLE
BlenderBot inference is very slow - takes more than 10 seconds 

### ISSUE THREAD

**Issue by vladgets** [facebookresearch/ParlAI#2844]
I am running an example: python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_3B/model

And response generation is very slow, takes about 13 seconds every time.
I have 4Gpus Tesla V100 machine, with 32Gb of memory each.

I also put attention that when the model is loaded, it loads itself into 4 Gpus in parallel, taking about 4Gb of memory on each.
Is there a way to load it only on a single GPU? Can it improve performance?
NVIDIA_VISIBLE_DEVICES=0 prefix did not work for me.

Also, is there a way not to use its safety feature to improve the performance?

**Comment by vladgets** [comment]
I found a way to run model on single GPU and it runs now more than 10 times faster!

**Comment by stephenroller** [comment]
for posterity, at inference time `--model-parallel false` is much faster.
