### ISSUE TITLE
Heroku/Turk error

### ISSUE THREAD

**Issue by ashleylew** [facebookresearch/ParlAI#2858]
We are trying to run the multi_agent_dialogue on the Turk sandbox, as we are hoping to use it as a template for a task we are creating.  The command I entered is: `python run.py -nc 2 -r 0.05 --sandbox` but we haven't been able to figure out why it gets stuck on this step:

> webpack --mode development -q

### This is the error message: 

> 
> Hash: c1c7f964c5b25d6182fb
> Version: webpack 4.43.0
> Time: 216ms
> Built at: 07/20/2020 4:49:38 PM
>                   Asset     Size  Chunks             Chunk Names
> server/static/bundle.js  6.7 KiB    main  [emitted]  main
> Entrypoint main = server/static/bundle.js
> [./dev/main.js] 2.9 KiB {main} [not cacheable] [built] [failed] [1 error]
> 
> ERROR in ./dev/main.js
> Module build failed (from ./node_modules/babel-loader/lib/index.js):
> /home/lewis.2799/ParlAI/parlai/mturk/tmp/heroku_server_83ccce7c-multiagentdialog/node_modules/schema-utils/dist/util/hints.js:16
>   const currentSchema = { ...schema
>                           ^^^
> 
> SyntaxError: Unexpected token ...
>     at NativeCompileCache._moduleCompile (/home/lewis.2799/ParlAI/parlai/mturk/tmp/heroku_server_83ccce7c-multiagentdialog/node_modules/v8-compile-cache/v8-compile-cache.js:242:18)
>     at Module._compile (/home/lewis.2799/ParlAI/parlai/mturk/tmp/heroku_server_83ccce7c-multiagentdialog/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
>     at Module.require (module.js:504:17)
>     at require (/home/lewis.2799/ParlAI/parlai/mturk/tmp/heroku_server_83ccce7c-multiagentdialog/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
>     at Object.<anonymous> (/home/lewis.2799/ParlAI/parlai/mturk/tmp/heroku_server_83ccce7c-multiagentdialog/node_modules/schema-utils/dist/ValidationError.js:11:5)
>     at Module._compile (/home/lewis.2799/ParlAI/parlai/mturk/tmp/heroku_server_83ccce7c-multiagentdialog/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
>     at Module.require (module.js:504:17)
>     at require (/home/lewis.2799/ParlAI/parlai/mturk/tmp/heroku_server_83ccce7c-multiagentdialog/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
>     at Object.<anonymous> (/home/lewis.2799/ParlAI/parlai/mturk/tmp/heroku_server_83ccce7c-multiagentdialog/node_modules/schema-utils/dist/validate.js:14:47)
>     at Module._compile (/home/lewis.2799/ParlAI/parlai/mturk/tmp/heroku_server_83ccce7c-multiagentdialog/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
>     at Module.require (module.js:504:17)
>     at require (/home/lewis.2799/ParlAI/parlai/mturk/tmp/heroku_server_83ccce7c-multiagentdialog/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
>     at Object.<anonymous> (/home/lewis.2799/ParlAI/parlai/mturk/tmp/heroku_server_83ccce7c-multiagentdialog/node_modules/schema-utils/dist/index.js:3:18)
>     at Module._compile (/home/lewis.2799/ParlAI/parlai/mturk/tmp/heroku_server_83ccce7c-multiagentdialog/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
> 
> npm ERR! Linux 3.16.0-10-amd64
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
> npm ERR! node v6.17.1
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! parlai-mturk-task-compiler@1.0.0 dev: `webpack --mode development -q`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the parlai-mturk-task-compiler@1.0.0 dev script 'webpack --mode development -q'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the parlai-mturk-task-compiler package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     webpack --mode development -q
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs parlai-mturk-task-compiler
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls parlai-mturk-task-compiler
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/lewis.2799/ParlAI/parlai/mturk/tmp/heroku_server_83ccce7c-multiagentdialog/npm-debug.log
> Traceback (most recent call last):
>   File "run.py", line 94, in <module>
>     main()
>   File "run.py", line 37, in main
>     mturk_manager.setup_server()
>   File "/home/lewis.2799/ParlAI/parlai/mturk/core/mturk_manager.py", line 1120, in setup_server
>     tmp_dir=self.opt['tmp_dir'],
>   File "/home/lewis.2799/ParlAI/parlai/mturk/core/server_utils.py", line 609, in setup_server
>     tmp_dir=tmp_dir,
>   File "/home/lewis.2799/ParlAI/parlai/mturk/core/server_utils.py", line 350, in setup_heroku_server
>     'Webpack appears to have failed to build your '
> Exception: Webpack appears to have failed to build your frontend. See the above error for more information.
> 

We are at a bit of a loss as to why this is happening and how to fix it. Any input would be really helpful!!

**Comment by stephenroller** [comment]
@JackUrb

**Comment by JackUrb** [comment]
Hi @ashleylew - what version of `npm` and `node` do you have installed locally? This looks like an issue where `node` is unfamiliar with the `...` syntax, which happens with some older versions.

Also, if you're just getting started, let me take a moment to plug [`Mephisto`](https://github.com/facebookresearch/Mephisto), which is where all future development into ParlAI's MTurk integration will come from. The existing methods will be deprecated in the next few months, so [Mephisto's ParlAI task](https://github.com/facebookresearch/Mephisto/tree/master/examples/parlai_chat_task_demo) may be a better starting point.

**Comment by ashleylew** [comment]
Hi @JackUrb, thanks so much for your response, it was really helpful! We've migrated over to Mephisto, but we're struggling with Heroku now. (see below) I attempted to verify my Heroku account but that didn't seem to fix the issue, and when I check what is running, it doesn't appear that anything is. I'm assuming that I'm missing something essential about how Heroku works/interfaces with ParlAI and Mephisto, but I can't find any instructions for how to set it up properly. Thanks again, we're really appreciative! 


<img width="839" alt="Screen Shot 2020-07-26 at 15 51 17" src="https://user-images.githubusercontent.com/68515763/88488511-3c5a2f80-cf53-11ea-8f11-89ead29a96cf.png">

**Comment by JackUrb** [comment]
Ah this is a display error on the Mephisto side - the real bug is that the unixname that's being used to construct your app name has a dot in it, and we're not filtering that out. I can put out a fix in Mephisto for this tomorrow (or accept a PR with it). The fix would be [here](https://github.com/facebookresearch/Mephisto/blob/10a9d109d3f708a2f91d919964f9cb907710e942/mephisto/server/architects/heroku_architect.py#L298)

**Comment by ashleylew** [comment]
thanks so much!

**Comment by JackUrb** [comment]
Hi @ashleylew - this bug is now resolved in Mephisto's master branch
