### ISSUE TITLE
Unexpected Killed  

### ISSUE THREAD

**Issue by tanmaycharthal** [facebookresearch/ParlAI#2862]
I am on AWS LightSail Ubuntu 18.04 instance . After running messenger chat service this happened .     
>[ optional arguments: ] 
[  datapath: /home/ubuntu/ParlAI/data ]
[ Chat Services: ] 
[  config_path: parlai/chat_service/tasks/chatbot/config.yml ]
[  is_debug: False ]
[  password: None ]
[ Facebook Messenger: ] 
[  bypass_server_setup: False ]
[  force_page_token: False ]
[  local: False ]
[  log_level: 20 ]
[  verbose: False ]

>You are going to allow people on Facebook to be agents in ParlAI.During this process, Internet connection is required, and you should turn off your computer's auto-sleep feature.

>Please press Enter to continue... 

>Setting up Messenger webhook...
Heroku: Collecting files...
Heroku: Starting server...
Enabling http-session-affinity for applebananacat-parlai-messenge... done
Scaling dynos... done, now running web at 1:Free
Webhook address: https://applebananacat-parlai-messenge.herokuapp.com/webhook
Local: Setting up WebSocket...
done with websocket
22:59:24 INFO | loading dictionary from /home/ubuntu/ParlAI/data/models
blender/blender_90M/model.dict
22:59:25 INFO | num words = 54944
22:59:25 INFO | TransformerGenerator: full interactive mode on.
Killed

Am i doing something wrong ?Any suggestions would be really helpful.

**Comment by stephenroller** [comment]
My suspicion is that you ran out of RAM. The thing that Killed you is not part of ParlAI anywhere.

**Comment by tanmaycharthal** [comment]
Thank you @stephenroller , Increasing RAM worked . But even after loading the model the bot didn't respond to any incoming messages.      
> [ optional arguments: ]
 [  datapath: /home/ubuntu/ParlAI/data ]
 [ Chat Services: ] 
 [  config_path: parlai/chat_service/tasks/chatbot/config.yml ]
 [  is_debug: False ]
 [  password: None ]
 [ Facebook Messenger: ] 
 [  bypass_server_setup: False ]
 [  force_page_token: False ]
 [  local: False ]
 [  log_level: 20 ]
 [  verbose: False ]
>
> You are going to allow people on Facebook to be agents in ParlAI.During this process, Internet connection is required, and you should turn off your computer's auto-sleep feature.
>
> Please press Enter to continue... 
>
> Setting up Messenger webhook...
 Heroku: Collecting files...
 Heroku: Starting server...
 Enabling http-session-affinity for applebanacat-parlai-messenger... done
 Scaling dynos... done, now running web at 1:Free
 Webhook address: https://applebanacat-parlai-messenger.herokuapp.com/webhook
 Local: Setting up WebSocket...
 done with websocket
 13:06:29 INFO | loading dictionary from /home/ubuntu/ParlAI/data/models/blender/blender_90M/model.dict13:06:29 INFO | num words = 54944
 13:06:30 INFO | TransformerGenerator: full interactive mode on.
 13:06:31 WARN | DEPRECATED: XLM should only be used for backwards compatibility, as it involves a less-stable layernorm operation.
 13:06:31 INFO | Total parameters: 87,508,992 (87,508,992 trainable)
 13:06:31 INFO | Loading existing model params from /home/ubuntu/ParlAI/data/models/blender/blender_90M/model

Thanks for helping out.

**Comment by viprocket1** [comment]
Thank you , Increasing the RAM finally solved the problem . Thanks for helping out

**Comment by tanmaycharthal** [comment]
Thank you , Increasing the RAM finally solved the problem . Thanks for helping out

**Comment by afiqmuzaffar** [comment]
> Thank you , Increasing the RAM finally solved the problem . Thanks for helping out

Hi @tanmaycharthal , may we get to know more how many GB of RAM needed to run ParlAI ?
