### ISSUE TITLE
F1-score vs Rouge-1 score

### ISSUE THREAD

**Issue by geekygirl123** [facebookresearch/ParlAI#2863]
How is F1-score calculated ? How is it different from rouge-1 score?

**Comment by priyanksonis** [comment]
check this for ROUGE: [What is ROUGE and how it works for evaluation of
summarization tasks?](http://www.ccs.neu.edu/home/vip/teach/DMcourse/5_topicmodel_summ/notes_slides/What-is-ROUGE.pdf)

**Comment by stephenroller** [comment]
Rouge-1 is unigram recall. F1 is the unigram F1.

https://github.com/facebookresearch/ParlAI/blob/81bea6485d694fd30b69277550e7a25ab14223dd/parlai/core/metrics.py#L376-L385

**Comment by geekygirl123** [comment]
Isn't the method used to calculate rouge-1 (precision, recall and f1) same as that for F1-score (precision, recall and f1-score)?


	` @staticmethod
	    def _prec_recall_f1_score(pred_items, gold_items):
	        """
	        Compute precision, recall and f1 given a set of gold and prediction items.
	
	        :param pred_items: iterable of predicted values
	        :param gold_items: iterable of gold values
	
	        :return: tuple (p, r, f1) for precision, recall, f1
	        """
	        common = Counter(gold_items) & Counter(pred_items)
	        num_same = sum(common.values())
	        if num_same == 0:
	            return 0, 0, 0
	        precision = 1.0 * num_same / len(pred_items)
	        recall = 1.0 * num_same / len(gold_items)
	        f1 = (2 * precision * recall) / (precision + recall)
	        return precision, recall, f1`

![image](https://user-images.githubusercontent.com/57398409/88214889-7b992f80-cc78-11ea-8986-0940dc0b95c9.png)

**Comment by stephenroller** [comment]
I don't recall the definition of Rouge precisely, sorry. For F1, we compute it as in the method above (by computing simple unigram overlap). For Rouge, we make a call to an external library.

**Comment by stephenroller** [comment]
But from this, I'm pretty sure Rouge is just recall:

![image](https://user-images.githubusercontent.com/31896/88295549-90eb7980-cccb-11ea-8bd8-816eaedf51dd.png)

**Comment by stephenroller** [comment]
Seems like your questions are resolved, @geekygirl123? Closing this, but feel free to reopen.
