### ISSUE TITLE
What's the best dataset format when fine-tuning blender?

### ISSUE THREAD

**Issue by nonstopfor** [facebookresearch/ParlAI#2866]
I want to fine-tune blender on my own dataset now. From the tutorial, I see this kind of data format:
`text:hello how are you today?   labels:i'm great thanks! what are you doing?
text:i've just been biking.     labels:oh nice, i haven't got on a bike in years!       episode_done:True`

But it seems that this kind of format requires even number of sentences for an episode. But in my dataset, there are some episodes which contain odd number of sentences. How to deal with this? Could I simply put all the sentences except the last sentence in the "text" field and put the last sentence in the "labels" field? 
By the way, I just want to get the final response given the previous dialog history so I don't need the model to generate the response in the mid of the dialogue.

**Comment by stephenroller** [comment]
We often handle this issue in the following way. Let’s say the convo is A B C D E.

We generate one convo:
A-> B
C-> D

And another convo
S->A
B->C
D->E

Where S is a special token called “silence”

**Comment by nonstopfor** [comment]
> We often handle this issue in the following way. Let’s say the convo is A B C D E.
> 
> We generate one convo:
> A-> B
> C-> D
> 
> And another convo
> S->A
> B->C
> D->E
> 
> Where S is a special token called “silence”

Ok, so what format should my dataset be? 
Also, when considering C -> D, will A and B be input into the model?

**Comment by stephenroller** [comment]
When doing C->D, the model will see A, B, C and be trained to predict D.

Use the format you pasted above.

text:A <tab> labels:B
text:C <tab> labels:D <tab> episode_done:True

**Comment by nonstopfor** [comment]
> When doing C->D, the model will see A, B, C and be trained to predict D.
> 
> Use the format you pasted above.
> 
> text:A labels:B
> text:C labels:D episode_done:True

Thanks! But when I have A, B, C, D, E, when will the format be like?

**Comment by stephenroller** [comment]
There will be a second convo that I showed you already.

**Comment by nonstopfor** [comment]
> There will be a second convo that I showed you already.

So I should use the format below?
text:S labels:A
text:B labels:C
text:D labels:E episode_done:True

Also, if I only care about the last sentence (in dialog) generation, could I just use the format below?
text:A. B. C. D. labels:E episode_done:True

**Comment by stephenroller** [comment]
Yup, that's right!

**Comment by nonstopfor** [comment]
> Yup, that's right!

Ok, really thanks for your patient explanation! I will close the issue.
