### ISSUE TITLE
Blender - Using Persona with Context History

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#2872]
Hello,

I wanted to know if I was using the persona correctly with also setting a context history for the Blender model.

- First, I use the ConvAI2 task in the `interactive.py` script by adding a `-t convai2`
- I override the `def _load_personas(opt):` to return a list with a string like so: `["your persona: i am a basketball player"]. (This persona is intended to be for the Blender bot, not the human interacting with the Blender bot)
- I finally set the context in each episode before the first call to `world.parley()` like so:

The context is meant to be three turns like so:

```
Human: Hello ...
Blender: Hello ...
Human: How are you?
```

This was the code I used:

```
result = human_agent.act()                      
agent.observe(result)            
agent.self_observe({'text':utt})
# human_agent doesn't seem to need to observe because all it does is print out the utterance?
print("Blender:", utt)
```

**My Question is the following:**

This is the order of the output. Notice that the context is in the middle of the chat. 
```
[EvalAgent] blah blah blah
[TransformerGenerator]: blah blah blah
[context]: your persona: i am a basketball player
[EvalAgent] blah blah blah
[TransformerGenerator]: blah blah blah
```

**Does this mean that the order of the context Blender receives is the following?**

1. The previous dialog turns given via `observe` and `self_observe`
2. Blender's persona

Instead of:

1. Blender's persona
2. The previous dialog turns given via observe and self_observe

Wouldn't giving blender its persona right before we want it to generate an utterance cause Blender to focus more on its persona rather than the previous context it was given? If this is so, how can I ensure the persona is the first context Blender gets instead of the context supplied via `self_observe`?

I.e, so instead of this:

```
[EvalAgent] blah blah blah
[TransformerGenerator]: blah blah blah
[context]: your persona: i am a basketball player
[EvalAgent] blah blah blah
[TransformerGenerator]: blah blah blah
```

It would be more like this:

```
[context]: your persona: i am a basketball player
[EvalAgent] blah blah blah
[TransformerGenerator]: blah blah blah
[EvalAgent] blah blah blah
[TransformerGenerator]: blah blah blah
```

Thank you!

**Comment by stephenroller** [comment]
The persona lines should be _first_, before the conversation begins at all.

You can look at `agent.history.get_history_str()` to see the agent’s view of the conversation and ensure it’s orderly. I’m recalling from memory, so I might be misremembering the exact name.

**Comment by josharnoldjosh** [comment]
Hmm, I think something is definitely wrong on my end.

To make things easier, is it possible to just have the human utter: "your persona: blah blah**\n**Hello, how are you?", i.e, manually make the human state the bots persona along with the first utterance instead of overriding the return value of `def _load_personas(opt):`? Thanks!

_Originally posted by @josharnoldjosh in https://github.com/facebookresearch/ParlAI/issues/2820#issuecomment-663869594_

**Comment by stephenroller** [comment]
Here's a minimal example:

```python
from parlai.core.agents import create_agent_from_model_file
blender_agent = create_agent_from_model_file("zoo:blender/blender_90M/model")

# forget everything. Important if you run this multiple times.
blender_agent.reset()

# concatenate the persona and the first thing the human says
first_turn = "\n".join([
    "your persona: I like cheese",
    "your persona: I am from New York City",
    "Hi, where are you from"
])
# Model actually witnesses the human's text
blender_agent.observe({'text': first_turn, 'episode_done': False})
print(f"You said: {first_turn}")
# model produces a response
response = blender_agent.act()
print("BlenderBot replied: {}".format(response['text']))
print()

# now another turn
second_turn = "do you like cheese?"
print(f"You said: {second_turn}")
blender_agent.observe({'text': second_turn, "episode_done": False})
response2 = blender_agent.act()
print("BlenderBot replied: {}".format(response2['text']))
print()
print('-' * 40)
print()
print("BlenderBot's history view:")
print(blender_agent.history.get_history_str())
```

Output:
```
2020-07-25 18:53:25,523 INFO     | loading dictionary from /usr/local/lib/python3.6/dist-packages/data/models/blender/blender_90M/model.dict
2020-07-25 18:53:25,731 INFO     | num words = 54944
2020-07-25 18:53:27,395 INFO     | Total parameters: 87,508,992 (87,508,992 trainable)
2020-07-25 18:53:27,396 INFO     | Loading existing model params from /usr/local/lib/python3.6/dist-packages/data/models/blender/blender_90M/model
You said: your persona: I like cheese
your persona: I am from New York City
Hi, where are you from
BlenderBot replied: i ' m from the city of new york . i love cheese . what do you like to eat ?

You said: do you like cheese?
BlenderBot replied: yes , i love it . it ' s one of my favorite foods . what ' s your favorite food ?

----------------------------------------

BlenderBot's history view:
your persona: I like cheese
your persona: I am from New York City
Hi, where are you from
i ' m from the city of new york . i love cheese . what do you like to eat ?
do you like cheese?
yes , i love it . it ' s one of my favorite foods . what ' s your favorite food ?
```

**Comment by mavisakal** [comment]
> Here's a minimal example:
> 
> ```python
> from parlai.core.agents import create_agent_from_model_file
> blender_agent = create_agent_from_model_file("zoo:blender/blender_90M/model")
> 
> # forget everything. Important if you run this multiple times.
> blender_agent.reset()
> 
> # concatenate the persona and the first thing the human says
> first_turn = "\n".join([
>     "your persona: I like cheese",
>     "your persona: I am from New York City",
>     "Hi, where are you from"
> ])
> # Model actually witnesses the human's text
> blender_agent.observe({'text': first_turn, 'episode_done': False})
> print(f"You said: {first_turn}")
> # model produces a response
> response = blender_agent.act()
> print("BlenderBot replied: {}".format(response['text']))
> print()
> 
> # now another turn
> second_turn = "do you like cheese?"
> print(f"You said: {second_turn}")
> blender_agent.observe({'text': second_turn, "episode_done": False})
> response2 = blender_agent.act()
> print("BlenderBot replied: {}".format(response2['text']))
> print()
> print('-' * 40)
> print()
> print("BlenderBot's history view:")
> print(blender_agent.history.get_history_str())
> ```
> 
> Output:
> 
> ```
> 2020-07-25 18:53:25,523 INFO     | loading dictionary from /usr/local/lib/python3.6/dist-packages/data/models/blender/blender_90M/model.dict
> 2020-07-25 18:53:25,731 INFO     | num words = 54944
> 2020-07-25 18:53:27,395 INFO     | Total parameters: 87,508,992 (87,508,992 trainable)
> 2020-07-25 18:53:27,396 INFO     | Loading existing model params from /usr/local/lib/python3.6/dist-packages/data/models/blender/blender_90M/model
> You said: your persona: I like cheese
> your persona: I am from New York City
> Hi, where are you from
> BlenderBot replied: i ' m from the city of new york . i love cheese . what do you like to eat ?
> 
> You said: do you like cheese?
> BlenderBot replied: yes , i love it . it ' s one of my favorite foods . what ' s your favorite food ?
> 
> ----------------------------------------
> 
> BlenderBot's history view:
> your persona: I like cheese
> your persona: I am from New York City
> Hi, where are you from
> i ' m from the city of new york . i love cheese . what do you like to eat ?
> do you like cheese?
> yes , i love it . it ' s one of my favorite foods . what ' s your favorite food ?
> ```

I'm using the browser_chat. Is it possible to add the personas from the command line arguments or in the config.yml file, without hardcoding them? I use the following command and config.yml to run the bot without personas.

**browser_chat command:**
`python parlai/chat_service/services/browser_chat/run.py --config-path path/to/config.yml --port 5001`

**config.yml:**
```
tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:  # Additional model opts go here
  debug: True
  models:
    blender_90M:
      model: transformer/generator
      model_file: zoo:blender/blender_90M/model
      interactive_mode: True
      no_cuda: False
      include_personas: False
additional_args:
  page_id: 1 # configure your own page
```

**Comment by Hilal-Urun** [comment]
![image](https://user-images.githubusercontent.com/37075702/104158421-64a0f200-53fe-11eb-8c06-08bdbbe45873.png)

**Comment by mavisakal** [comment]
> Hi, when I try to change the model for example blender_1Bdistill it gives this error:
> 
> 08:07:57 | --skip-generation true produces limited metrics
> Traceback (most recent call last):
> File "trial.py", line 19, in
> response = blender_agent.act()
> File "/home/ParlAI/parlai/core/torch_agent.py", line 1947, in act
> self.self_observe(response)
> File "/home/ParlAI/parlai/core/torch_agent.py", line 1748, in self_observe
> last_reply = self_message['text']
> KeyError: 'text'

Where did you make the change? can you share your config.yml ?

**Comment by Hilal-Urun** [comment]
> > Hi, when I try to change the model for example blender_1Bdistill it gives this error:
> > 08:07:57 | --skip-generation true produces limited metrics
> > Traceback (most recent call last):
> > File "trial.py", line 19, in
> > response = blender_agent.act()
> > File "/home/ParlAI/parlai/core/torch_agent.py", line 1947, in act
> > self.self_observe(response)
> > File "/home/ParlAI/parlai/core/torch_agent.py", line 1748, in self_observe
> > last_reply = self_message['text']
> > KeyError: 'text'
> 
> Where did you make the change? can you share your config.yml ?

Thank you so much for your response! I just change the model file which is->  model_file: zoo:blender/blender_1Bdistill/model

**Comment by stephenroller** [comment]
Ah you might have skip_generation set to True instead of False.

We try to flip that automatically for you as appropriate, but your setup may be missing it.

**Comment by Hilal-Urun** [comment]
Hi @stephenroller ,
I want to ask one more question about setting up the persona :) If we want to talk a spesific character of an agent then when we set up persona in the first turn as above, is it enough ? or also need to  set _load_context() .

**Comment by klshuster** [comment]
setting up the persona as specified above is enough

**Comment by imthebilliejoe** [comment]
> Here's a minimal example:
> 
> ```python
> from parlai.core.agents import create_agent_from_model_file
> blender_agent = create_agent_from_model_file("zoo:blender/blender_90M/model")
> 
> # forget everything. Important if you run this multiple times.
> blender_agent.reset()
> 
> # concatenate the persona and the first thing the human says
> first_turn = "\n".join([
>     "your persona: I like cheese",
>     "your persona: I am from New York City",
>     "Hi, where are you from"
> ])
> # Model actually witnesses the human's text
> blender_agent.observe({'text': first_turn, 'episode_done': False})
> print(f"You said: {first_turn}")
> # model produces a response
> response = blender_agent.act()
> print("BlenderBot replied: {}".format(response['text']))
> print()
> 
> # now another turn
> second_turn = "do you like cheese?"
> print(f"You said: {second_turn}")
> blender_agent.observe({'text': second_turn, "episode_done": False})
> response2 = blender_agent.act()
> print("BlenderBot replied: {}".format(response2['text']))
> print()
> print('-' * 40)
> print()
> print("BlenderBot's history view:")
> print(blender_agent.history.get_history_str())
> ```


Hi there, i really appreciated the semplicity of this code and wanted to ask you if is there a line of code i could add to this code if I want to feed information to the model so that he could use it to answer the question (if is possible). Let me make an example of what I mean directly from your code in the variable second_turn:

```python
from parlai.core.agents import create_agent_from_model_file
blender_agent = create_agent_from_model_file("zoo:blender/blender_90M/model")

# forget everything. Important if you run this multiple times.
blender_agent.reset()

# concatenate the persona and the first thing the human says
first_turn = "\n".join([
    "your persona: I like cheese",
    "your persona: I am from New York City",
    "Hi, where are you from"
])
# Model actually witnesses the human's text
blender_agent.observe({'text': first_turn, 'episode_done': False})
print(f"You said: {first_turn}")
# model produces a response
response = blender_agent.act()
print("BlenderBot replied: {}".format(response['text']))
print()

# now another turn
second_turn = "\n".join([
    "information externally provided to answer: information about Napoleon are on this link https://en.wikipedia.org/wiki/Napoleon",
    "Where can i find informations about Napoleon?"
])
print(f"You said: {second_turn}")
blender_agent.observe({'text': second_turn, "episode_done": False})
response2 = blender_agent.act()
print("BlenderBot replied: {}".format(response2['text']))
print()
print('-' * 40)
print()
print("BlenderBot's history view:")
print(blender_agent.history.get_history_str())
```

So that the model could answer something like: " You can find the information about Napoleon on this link: https://en.wikipedia.org/wiki/Napoleon"

is this possible?
