### ISSUE TITLE
Displaying multiple model outputs with delayed beam search

### ISSUE THREAD

**Issue by mvh57** [facebookresearch/ParlAI#2882]
Hello all, 
How would I adjust the transformer / generator model and/or the interactive.py script to display multiple candidate outputs, so that I can implement my own discriminator model to pick the best?
For example, given a human input (running the interactive.py script) "How are you today?" I want to access some arbitrary number of candidate model responses. Thanks for your help with this!
Michael

**Comment by stephenroller** [comment]
https://github.com/facebookresearch/ParlAI/blob/8807542b00bbbc0599ccd75b6224bce34c7d908b/parlai/core/torch_generator_agent.py#L1111

So this line can never actually trigger, but if you replace it with true, and add `--loglevel debug`, then this chunk of code will show you all the different beams.

If you want to pass those beams around, you'll need to modify the code to include them in the `Output` object here:
https://github.com/facebookresearch/ParlAI/blob/8807542b00bbbc0599ccd75b6224bce34c7d908b/parlai/core/torch_generator_agent.py#L892
