### ISSUE TITLE
ImportError: Could not find pretrained model in parlai.zoo.personachat.kvmemnn.kvmemnn or parlai.zoo.personachat.kvmemnn.build.

### ISSUE THREAD

**Issue by min942773** [facebookresearch/ParlAI#2891]
When trying to run
`python projects/personachat/scripts/kvmemnn_interactive.py`
the following error occurs:
`Traceback (most recent call last):                                                                                        File "C:\Users\user\ParlAI\parlai\core\build_data.py", line 423, in modelzoo_path                                         my_module = importlib.import_module(module_name)                                                                      File "C:\Users\user\Anaconda3\lib\importlib\__init__.py", line 127, in import_module                                      return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked                                            ModuleNotFoundError: No module named 'parlai.zoo.personachat'                                                                                                                                                                                   During handling of the above exception, another exception occurred:                                                                                                                                                                             Traceback (most recent call last):                                                                                        File "C:\Users\user\ParlAI\parlai\core\build_data.py", line 430, in modelzoo_path                                         my_module = importlib.import_module(module_name_)                                                                     File "C:\Users\user\Anaconda3\lib\importlib\__init__.py", line 127, in import_module                                      return _bootstrap._gcd_import(name[level:], package, level)                                                           File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked                                              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked                                            ModuleNotFoundError: No module named 'parlai.zoo.personachat'                                                                                                                                                                                   During handling of the above exception, another exception occurred:                                                                                                                                                                             Traceback (most recent call last):                                                                                        File "projects/personachat/scripts/kvmemnn_interactive.py", line 24, in <module>                                          opt = parser.parse_args()                                                                                             File "C:\Users\user\ParlAI\parlai\core\params.py", line 1012, in parse_args                                               self._process_args_to_opts(args)                                                                                      File "C:\Users\user\ParlAI\parlai\core\params.py", line 979, in _process_args_to_opts                                     self.opt.get('datapath'), self.opt[each_key]                                                                          File "C:\Users\user\ParlAI\parlai\core\build_data.py", line 435, in modelzoo_path                                         f'Could not find pretrained model in {module_name} or {module_name_}.'                                              ImportError: Could not find pretrained model in parlai.zoo.personachat.kvmemnn.kvmemnn or parlai.zoo.personachat.kvmemnn.build.`

Did anyone have a similar issue?

**Comment by stephenroller** [comment]
I think you're going to need to rewind to an older commit, but sadly I don't know which.

**Comment by mdhuggins** [comment]
@min942773 Did you ever determine which commit? I'm having the same issue

**Comment by stephenroller** [comment]
I found a commit that works, 59dbf489de9bfcb5cd9e621fdcee763f0b04da08. It's not the last one that works, but it's as good a flag point as any.

I've set a [`personachat` tag](https://github.com/facebookresearch/ParlAI/releases/tag/personachat) to mark it. After pulling, you can `git checkout personachat`

**Comment by min942773** [comment]
Thanks for helping.
