### ISSUE TITLE
Save display_model output to file

### ISSUE THREAD

**Issue by aslu98** [facebookresearch/ParlAI#2893]
Hello, I'm new to NLP and I'm trying to use the bot, my question could be trivial.

I would like to fetch some strings to a Blender model, for example the 2.7B parameters, from a file and receive the answers the model would give written into another file.
Said in another way, I would like to reproduce the behaviour of the bot when executing a script like "safe_interactive.py" but without typing all my requests, just having them written into a file and being automatically taken from the chatbot.
I tried to use self_chat but I don't think this is the purpose of that script.

How could I do that?

Update: I found out that display_model does just what I was looking for, now I only need to save the output to a file, how can I do that?

I already tried to use the arg -of but I had no luck.

**Comment by aslu98** [comment]
Update: I found out that `display_model` does just what I was looking for, now I only need to save the output to a file, how can I do that?

I already tried to use the arg `-of` but I had no luck.

**Comment by stephenroller** [comment]
Instead, use eval_model. Use:


—report-filename output.json —save-world-logs true

**Comment by aslu98** [comment]
Thank you!

I tried this:
`parlai eval_model -mf zoo:blender/blender_3B/model -t fromfile:parlaiformat --fromfile_datapath ../mini-human-meena.txt —report-filename output.json —save-world-logs True`

but I got a Parse Error:
`Parse Error: unrecognized arguments: —report-filename output.json —save-world-logs True`

**Comment by aslu98** [comment]
I tried it and it saves output to file, but it doesn't have the output I want 

display_model output is like:
text:
 label:
 model:
text:
 label:
 model:
-----

but eval_model output file is just what I gave as an input file:
text: 
 label:
text:
 label:
----

I would like to have also the model answer in my output file, is that possible?
