### ISSUE TITLE
finetune blender in fairseq?

### ISSUE THREAD

**Issue by hckh** [facebookresearch/ParlAI#2900]
The blender paper (https://parl.ai/projects/recipes/) says that the models were originally trained in fairseq, but they are released as parl.ai models.

Is it possible to perform inference on the released models in fairseq and/or finetune tune them in fairseq?

**Comment by stephenroller** [comment]
Possible? yes. Easy? no.

You'd need to convert the models and the data to fairseq.

**Comment by hckh** [comment]
Is this the script that was used to convert it from fariseq in to parlai? 

https://github.com/facebookresearch/ParlAI/blob/abfb771ac4ed2966d6f3ea22c7a38e4ebc9cc0f0/parlai/agents/bart/convert_fairseq_to_parlai.py

**Comment by stephenroller** [comment]
Yes, that takes you fairseq -> parlai.

**Comment by hckh** [comment]
Thanks!

**Comment by iRmantou** [comment]
@stephenroller 
hi, I want to pretrain the **Generator model** from scratch mentioned in the [Recipes for building an open-domain chatbot](https://arxiv.org/pdf/2004.13637.pdf) paper.  In this paper, you use Fairseq to do the pretraining for speed, then use ParlAI to do the finetuning, but I notice in https://github.com/facebookresearch/ParlAI/pull/2226 you say **Fairseq has been broken a long time** and delete some codes releated it. Here is my questions:

1. If I want to do a pretraining, should I use **ParlAI** which CAN also be used for pretraining as I know or **Fairseq** for speed but maybe not necessary?

2. if I should use **Fairseq**, could u provide some command scripes releated **Generator model pretraining** in Fairseq ? I did not find any commands like "[fairseq-train --arch xxx_model](https://fairseq.readthedocs.io/en/latest/getting_started.html#training)" in ParlAI repo and how faster Fairseq than ParlAI when pretrain 90M blend model?

**Comment by stephenroller** [comment]
You can do pretraining in ParlAI. It's about half the speed of doing in fairseq.

The issue you link to is unrelated. It has to do with a very old system we had for training fairseq architectures in parlai.

We describe hyperparameters in the paper.

**Comment by stephenroller** [comment]
And the 90M model was trained entirely in ParlAI. See the dodeca paper for info about that model.

**Comment by iRmantou** [comment]
Thanks for your reply! Where can I find this old system/codes or are you suggesting that I shouldn't be using this very old system？

**Comment by stephenroller** [comment]
The old system is irrelevant. We pretrained the largest models in fairseq using 100% fairseq code, and then converted the model to parlai. The conversion script is in the "parlai/agents/BART" folder. For instructions on how to train a model in fairseq, see the fairseq docs.
