### ISSUE TITLE
Implementing Blender 90M Chatbot model to a Website

### ISSUE THREAD

**Issue by Ufukdogann** [facebookresearch/ParlAI#2903]
Hello people,

I am trying to use Blender 90M Chatbot model on my local browser.

After reading the https://parl.ai/docs/tutorial_chat_service.html website, I just tried to run the command 

`python Parlai/parlai/chat_service/services/browser_chat/run.py --config-path Parlai/parlai/chat_service/tasks/chatbot/config.yml --port 8000`

and I also tried with port number 10001 just be sure that is the problem the port. After my trials nothing happened actually.

No local website, or anything popped up. I also wrote the other command which is 

`python client.py --port 8000
`

But again, nothing happened.

Can you let me know what I am doing wrong? I also put a screenshot as well.

<img width="1410" alt="Screenshot 2020-07-30 at 00 02 09" src="https://user-images.githubusercontent.com/8861458/88858186-ece85d80-d1f7-11ea-83b7-8ef65987b239.png">

PS: I have all parlai folders under Parlai folder, so that's why I am writing like "Parlai/parlai"

Best regards,

**Comment by Ufukdogann** [comment]
Dear @klshuster @stephenroller 

I am trying to do this for my thesis, so it would be really perfect if one of you can help me as soon as possible.

Best regards,

**Comment by klshuster** [comment]
from the screenshot, it looks like you're typing `python client.py` in the same window as the `run.py` command - try running `python client.py` in a separate window after running `run.py` in that initial window

**Comment by Ufukdogann** [comment]
@klshuster thanks a lot, now it is working!

<img width="988" alt="Screenshot 2020-07-30 at 01 14 14" src="https://user-images.githubusercontent.com/8861458/88863010-fd9dd100-d201-11ea-97c8-46f688607194.png">

Now, I have another question. 

How may I interact with a specific model like Blender 90M Chatbot? Since, I did not specify the model in the terminal code, I think parlai lets me talk with default Chatbot model.

Can you also help me with this please?

And also, I want to implement this on my web page, is there any guide for it?

Best regards,

**Comment by stephenroller** [comment]
In the yml config, there is a model_file argument. You can change that to one of the likewise arguments listed on our projects pages or model zoo list in the docs.

**Comment by Ufukdogann** [comment]
@stephenroller like this?

`model_file: zoo:blender/blender_3B/model
`

**Comment by stephenroller** [comment]
Yes, I think so!

**Comment by Ufukdogann** [comment]
@stephenroller thanks a lot, really!

Now, my question is how may I connect this with my website. I am able to work on my local website but may I connect it with an existed website or how may I make my local website available for other people as well?

Because what I need to do is, letting people to talk with chatbot and gather the conversations basically, so I need to integrate this chatbot to an url.

I know I am asking many questions but I could not find various documentations and in this link, https://parl.ai/docs/tutorial_chat_service.html there is just 2 lines of code for it, so I am sorry for asking everything to you guys.

Thanks in advance!

**Comment by Ufukdogann** [comment]
@stephenroller @klshuster 

After changing config.yml like the screenshot, which is the exactly same with the code specified here, https://parl.ai/docs/tutorial_chat_service.html "except override part"

<img width="490" alt="Screenshot 2020-07-30 at 02 23 41" src="https://user-images.githubusercontent.com/8861458/88866785-fbd90b00-d20b-11ea-9b6d-fe9fec0930ee.png">

I am facing this problem actually, do you know why?

<img width="972" alt="Screenshot 2020-07-30 at 02 22 01" src="https://user-images.githubusercontent.com/8861458/88866781-f976b100-d20b-11ea-9f47-ecb003443030.png">

Best regards, thanks in advance

**Comment by Ufukdogann** [comment]
@stephenroller @klshuster 

I have found this issue, https://github.com/facebookresearch/ParlAI/issues/2633, which is kinda related to mine and I have tried to do the same things he did, but I am receiving error below.

```
World default had error KeyError('models',)
NoneType: None
Next task: None

```

What I have done is,

-     MODEL_KEY = 'legacy_seq2seq' is changed to MODEL_KEY = 'blender' and line 82 commented in the worlds.py

- <img width="376" alt="Screenshot 2020-07-30 at 02 58 49" src="https://user-images.githubusercontent.com/8861458/88868491-9a676b00-d210-11ea-940e-c0e6bec18030.png"> in the config.py

Best regards, thanks in advance.
