### ISSUE TITLE
Couldn't able to run Blenderbot inside 2 GPU machine ?

### ISSUE THREAD

**Issue by aadityachapagain** [facebookresearch/ParlAI#2908]
I couldn't able to run 2.7B Blenderbot inside machine with 2 GPU. 
GPU : Nvidia v100.
when using 1 GPU machine it will load using CUDA. But when try to run inside 2 GPU , it load in CPU?
Is there any way we could specify which GPU to use, incase of multi GPU machine ?

and Is there any way we could do inference with  Blenderbot using 2 GPU  ? so that we could have inference faster than 1 GPU machine .

thanks

**Comment by stephenroller** [comment]
Please post the commands you’re trying to run.

**Comment by aadityachapagain** [comment]
@stephenroller 
I tried to run with this command.
python run.py --config-path ../../tasks/chatbot/config.yml

It works fine on single GPU machine but dosen't load with CUDA inside multi GPU machine. 
After that i tried adding --gpu 1 in params, and still didnt work.

**Comment by stephenroller** [comment]
The —gpu argument is for setting it onto a specific gpu, so I don’t think that helps.

Pretty sure the default config.yml has a “no_cuda” line. Can you post your config?

**Comment by aadityachapagain** [comment]
below is the config.yml I have been using.
`tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 540
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    blender_90M:
      model: transformer/generator
      model_file: zoo:blender/blender_3B/model
      interactive_mode: True
      no_cuda: False
`

I am pretty sure that, we need to set no_cuda to false to load model on GPU.

**Comment by stephenroller** [comment]
What about in interactive.py?

**Comment by aadityachapagain** [comment]
I don't know if there is any problem with interactive.py. This same config works just fine with single GPU machine but don't work with multiGPU machine.

**Comment by stephenroller** [comment]
Can you test interactive on the same machine and see if both gpus get used?

**Comment by aadityachapagain** [comment]
I try running interactive.py on 2 GPU machine, But it doesn't run with CUDA.
```
python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_3B/model
07:09:00 WARN | Overriding opt["task"] to blended_skill_talk (previously: internal:blended_skill_talk,wizard_of_wikipedia,convai2:normalized,empathetic_dialogues)
07:09:00 WARN | Overriding opt["model_file"] to /home/fm-lt/FuseMachinesChat/ParlAI/data/models/blender/blender_3B/model (previously: /checkpoint/edinan/20200331/finetune_bst_gen_baseline_convai2_normal/de6/model)
07:09:00 INFO | loading dictionary from /home/fm-lt/FuseMachinesChat/ParlAI/data/models/blender/blender_3B/model.dict
07:09:00 INFO | num words = 8008
07:09:00 INFO | TransformerGenerator: full interactive mode on.
07:09:42 INFO | Total parameters: 2,696,268,800 (2,695,613,440 trainable)
07:09:42 INFO | Loading existing model params from /home/fm-lt/FuseMachinesChat/ParlAI/data/models/blender/blender_3B/model
Killed
```

**Comment by aadityachapagain** [comment]
I think the problem is in cuda version.
Both of my machine (1 GPU,  2 GPU machine ) use same cuda version of 10.1 **BUT SOMEHOW **   same Interactive.py doesn't work on 2 GPU machine but works  on 1 GPU machine.

**Comment by stephenroller** [comment]
I would check your pytorch installation.

```
$ python -c 'import torch; print(torch.cuda.is_available())'
True
```

**Comment by aadityachapagain** [comment]
Its  look like problem was due to pytorch.I downgrade pytorch version to 1.4 and now it is working.
Thanks for your help. I will close this issue now.
