### ISSUE TITLE
Modifying the Local Browser

### ISSUE THREAD

**Issue by Ufukdogann** [facebookresearch/ParlAI#2915]
Dear @stephenroller,

I would like to modify the view of the website that comes up right after when I run the terminal codes of the chatbot for local browser.

This is the screenshot of the page.

<img width="1002" alt="Screenshot 2020-07-30 at 10 14 48" src="https://user-images.githubusercontent.com/8861458/89108517-64f19600-d439-11ea-92d8-cc4c62d4dfee.png">

How may I do it?

**Comment by Ufukdogann** [comment]
@stephenroller @klshuster guys, can u help me with that?

Thanks in advance!

**Comment by stephenroller** [comment]
Please look for the HTML in parlai/chat_services folder and edit it as you need.

**Comment by Ufukdogann** [comment]
@stephenroller thanks for the reply, but I could not see any HTML in that folder. Are you sure?

Best regards,

**Comment by stephenroller** [comment]
https://github.com/facebookresearch/ParlAI/blob/c3cb2621f0b0b58fe6ba5a5d34030d57980e20eb/parlai/chat_service/services/browser_chat/client.py#L11

Ah, looks like it's using the HTML in `interactive_web.py`. 

But you can have anything you want sent over the wire here:

https://github.com/facebookresearch/ParlAI/blob/c3cb2621f0b0b58fe6ba5a5d34030d57980e20eb/parlai/chat_service/services/browser_chat/client.py#L91

**Comment by Ufukdogann** [comment]
@stephenroller thanks a lot!

I can edit the WEB_HTML variable in parlai.scripts.interactive_web or create a new web_html variable for my already existed page. Is this what you want to say, right?

Best regards.
