### ISSUE TITLE
Questions about Gorecdial

### ISSUE THREAD

**Issue by caijie12138** [facebookresearch/ParlAI#2920]
May I ask if the **GoRecdial** dataset is in the task list? I can't seem to find it.

Link of paper is as follow:
https://arxiv.org/pdf/1909.03922.pdf

**Comment by stephenroller** [comment]
You can find the dataset linked in #2200. No one has implemented an actual teacher for it yet though. I would happily welcome one.

Closing as a duplicate. Feel free to continue to ask questions or reopen.
