### ISSUE TITLE
[Blender] How can I get Blender to use Nucleus sampling?

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#2930]
Currently, from my understanding, Blender uses MLE which is deterministic. I was hoping to have a non-deterministic model.

Is it possible to change the decoding strategy of Blender to be non-deterministic, e.g, instead of beam search, using nucleus sampling?

The way I currently initialize blender is:

```python
from parlai.core.agents import create_agent_from_model_file

blender = create_agent_from_model_file("zoo:blender/blender_90M/model")
```

What would I need to change to alter the decoding strategy?

Thank you!

**Comment by josharnoldjosh** [comment]
Update: I found the `model.dict.opt` file under `data/models/blender/blender_90M/`. I also found the `"inference": "greedy",` key. Is this the key that I want to change, or is it a different key? Is there anywhere I can see the possible values I can choose from? Thank you!

**Comment by josharnoldjosh** [comment]
Update 2: I changed the keys to:

`"inference": "nucleus",` and `--topp 0.7`

I think this solves it!

**Comment by stephenroller** [comment]
Yup, you got it.
