### ISSUE TITLE
ModuleNotFoundError: No module named 'parlai.tasks.dialogue-nli'

### ISSUE THREAD

**Issue by min942773** [facebookresearch/ParlAI#2943]
I want to use Dialogue Natural Language Inference dataset and I found it in projects folder's [README.md](https://github.com/facebookresearch/ParlAI/tree/master/projects#chit-chat) file. 
![image](https://user-images.githubusercontent.com/41141885/89507745-e5ccdb00-d807-11ea-8a0c-dbce6c4492bb.png)
But I can't find the file in the projects folder and dataset isn't available.
How can I find it and use it?
`parlai display_data -t dialogue-nli`

![image](https://user-images.githubusercontent.com/41141885/89507877-144ab600-d808-11ea-81c6-5b3265904d14.png)

**Comment by stephenroller** [comment]
For posterity, the correct argument is "dialogue_nli"
