### ISSUE TITLE
 Unexpected formatting of the dataset is used in persona-chat datasets

### ISSUE THREAD

**Issue by masahiro-mi** [facebookresearch/ParlAI#2944]
**Bug description**
In persona-chat datasets, unexpected formatting of the dataset is used.
I found same issue in https://github.com/facebookresearch/ParlAI/issues/2576, but no answer yet.

In the Persona-chat dataset, the paper says "(i) Personas: we crowdsource a set of 1155 possible personas, each consisting of at least 5 profile
sentences, setting aside 100 never seen before personas for validation, and 100 for test."

However, the contents of the dataset obtained by this command include
It contains a set of persona sentences that are less than 5 sentences and a number of persona sentences that contain spelling errors.

**Reproduction steps**
```
parlai display_data --task personachat --datatype train
cat ./data/Persona-Chat/personachat/*_original.txt | less
...
1 your persona: i have a father and a brother.
2 your persona: my favourite food is sushi.
3 your persona: i listen to rap music.
4 your persona: i like to work out.
5 partner's persona: i have two sons.
6 partner's persona: i am going to hairdresser school.
7 partner's persona: i collect vintage 50 s decorations.
8 partner's persona: i eat granola for breakfast every day.
9 partner's persona: i have an exotic fish aquarium.
10 hi , do you have sons ? i have two . a younger brother and no children is all . besides dad          italian food . chicken alfredo . sigh .|oh that sounds so cool ! my name is melanie .
...
```
"your persona" is only 4 sentences, it is less than 5.

```
cat *_original.txt | grep usine | grep persona | less
...
2 partner's persona: i like italian cusine.
2 partner's persona: i like italian cousine.
2 partner's persona: i like italian cousine.
2 partner's persona: i like italian cousine.
5 partner's persona: i like italian cousine.
4 partner's persona: i like italian cusine.
2 partner's persona: i like italian cusine.
5 partner's persona: i like italian cusine.
5 partner's persona: i like italian cusine.
2 partner's persona: i like italian cousine.
5 partner's persona: i like italian cousine.
2 partner's persona: i like italian cusine.
...
```
These "cusine" or "cousine" are properly "cuisine".

**Additional context**

There are 1491 unique sets of persona sentences (we count sets that contains 5 sentences only) in ParlAI's persona-chat dataset.
However, the original paper says that the unique sets of persona sentence are 1155.

And more, we count up unique sets of persona sentences by human-hands to fix miss spells and duplication, but, we find only 1054 sets of persona sentences only.

Why is there a mismatch between the statistics of these ParlAI datasets and the original paper?
How can I reproduce the same dataset as in the original paper?
I need a way to how to fix these persona-chat dataset mismatch.

I hope this issue solving helps to increase the appropriateness of this research.
Thank you,

**Comment by stephenroller** [comment]
I think probably mispellings are counted as separate personas. Additionally, IIRC not all persona values were were used (or equally used) when the actual dialogue dataset was created. 

I would recommend emailing the original author. The data that is in public ParlAI is the officially released version, as he released it.
