### ISSUE TITLE
Using GPU during training

### ISSUE THREAD

**Issue by aslu98** [facebookresearch/ParlAI#2960]
Hello, I'm sorry for this question, this is probably trivial and maybe this is not he right place to ask it.

I used to train my models in Colab (with its GPU), now I switched to a local GPU and i'm trying to train them inside a docker container. 
I installed cuda, abilitated the container to use the GPU and specified to use it when I run **but** when I check for the processes running with GPU (running `-nvidia-smi` in another window) there is none.

I feel like I'm missing something and I'm wondering if I need to install something else (pyTorch maybe?) or specify some particular argument to force using the GPU when I run the training script. 

The training starts anyway but I would like to make sure that it is using the GPU.

**Comment by stephenroller** [comment]
I’m sorry, we can’t assist you with that. Search google and the machine learning subreddit for info about docker and Nvidia etc

**Comment by aslu98** [comment]
Thanks, I figured as much, just wanted to make sure that I was not missing something on the specific script I was executing.

**Comment by stephenroller** [comment]
Make sure `python -c 'import torch; print(torch.cuda.is_available())'` is printing True inside the docker.

**Comment by aslu98** [comment]
The problem was I was checking `python -c 'import torch; print(torch.cuda.is_available())` during the building of my image, not while it was running. During the building it always returns False because the gpu "connects" to the image only while it is running.
