### ISSUE TITLE
Teaching Model to Down-Weight Bad Responses

### ISSUE THREAD

**Issue by mvh57** [facebookresearch/ParlAI#2966]
Hello all,
I want to teach the transformer / generator model to avoid (down-weight) certain types of candidate responses by showing it examples of such responses. Is there a way in the Parlai framework that I could go about doing this -- I'm thinking something like showing the model a training set with stereotypically undesirable responses (somehow indicating to the model that these are undesirable), so it can learn to down-weight these types of outputs? 
I've read through the training parameters, particularly those specific to training tasks, and I can't see a way to do this (I was considering possibly inputing a negative multi-task weight for the task containing bad responses, but not sure this would work). 
Thanks for your help!

**Comment by stephenroller** [comment]
You might interested in Unlikelihood training:
- https://arxiv.org/abs/1908.04319
- https://arxiv.org/abs/1911.03860
- https://parl.ai/projects/dialogue_unlikelihood/

Specifically the reward agent:
https://github.com/facebookresearch/ParlAI/blob/2739c2304c6a6ae30eb61633b4ca5102909e4a94/projects/dialogue_unlikelihood/agents.py#L49-L55

@hadasah can perhaps share an example of training with it.

**Comment by mvh57** [comment]
Thank you so much. Yes, an example would be very helpful!

**Comment by mvh57** [comment]
Hi @stephenroller and @hadasah,
Just following up on this issue to see if it would be possible to get an example of how to use unlikelihood training (i.e., collect training examples of offensive / bad responses and train the model not to make such responses). I've read the papers you've attached @stephenroller, but am still having difficulty determining which scripts I need to modify (I assuming I need to specify a different loss function for the model to use when training on offensive data, but am not sure how to go about doing this.) Thanks so much for your ongoing help.

**Comment by hadasah** [comment]
Hi @mvh57! So sorry about the delay. I started working on better documentation but haven't finished/merged it in yet. You can see it in [draft state](https://github.com/facebookresearch/ParlAI/blob/6bdfc06e0687eee1d2cdbe0e48bf4fae10c0b815/projects/dialogue_unlikelihood/README.md), but unfortunately one of the parts I'm still working on is the reward unlikelihood agent (relevant to you).  

The tl;dr is that to use the reward unlikelihood agent, all you need to do is create a ParlAI task - creating a simple file to read from would be easiest as written [here](https://parl.ai/docs/tutorial_task.html#quickstart-adding-a-new-dataset) - and to add, in addition to text and label fields, a reward field, with negative values for examples you want to push down on. Positive, nonnegative, and omitted reward values are all interpreted as denoting positive examples - for regular MLE training.

With this task written, you could train the reward unlikelihood agent thus:
`parlai train_model -m projects.dialogue_unlikelihood.agents:RewardUnlikelihoodAgent -t jsonfile --json-datapath <path/to/your/task/file>`
or
`parlai train_model -m projects.dialogue_unlikelihood.agents:RewardUnlikelihoodAgent -t fromfile:parlaiformat --fromfile-datapath <path/to/your/task/file>`
depending on which of the two task formats you use.

**Comment by mvh57** [comment]
@hadasah thank you so much. This is extremely helpful. I now feel like I have a sense of how to go about using unlikelihood training. I'm still getting an error when I try to train with the unlikelihood agent. When I run
`parlai train_model -m projects.dialogue_unlikelihood.agents:RewardUnlikelihoodAgent -t my_own_task`
I get
`AttributeError: module 'projects.dialogue_unlikelihood.agents' has no attribute 'RewardUnlikelihoodAgent'`
When I check the `agents.py` file (within the dialogue_unlikelihood project directory), I see a class called `RewardUnlikelihoodAgentTrait`, but no class with `RewardUnlikelihoodAgent` name, so I believe this is where the error is coming from, however I'm not sure where to find this agent. Thanks for your help with this!

**Comment by stephenroller** [comment]
It's probably RewardUnlikelihoodTransformerAgent or similar. We implemented it as an abstract trait that could be attached to many models.

**Comment by hadasah** [comment]
As stephen said, sorry about that typo - it's TransformerUnlikelihoodAgent - as defined [here ](TransformerUnlikelihoodAgen)

**Comment by mvh57** [comment]
This is great! I think I've got it up and running. 2 remaining questions I have that I can't seem to find in documentation:
(1)  What is the range of the `Reward` parameter that is specified in the training data? I understand that a negative value will be used for pushing down bad responses and positive will be used for positive responses, however I'm not sure how to determine the magnitude of this value. (-1,1), (-10,10), etc?
(2) The transformer / generator model can be trained on episodes of multiple dialogue turns. Is there a way to specify a negative reward for an entire episode that we'd want pushed down. (For example, an episode that is generally poor, where context is forgotten, etc. ) I'm imagining something like this:
`text:Hello how are you?<tab>label:hi there, I've forgotten what you said. `
`text:That's not good.<tab>label:yes, this would be a negative training example.  
<tab>episode_done:True<tab>reward:-1`
(i.e., we'd be pushing down the entire episode by specifying reward parameter after the episode_done parameter).

**Comment by stephenroller** [comment]
It occurs to me that we need to carve out a special case in the 'reward' field here, to make sure it's parsed as integers:

https://github.com/facebookresearch/ParlAI/blob/d69778fe452094d7eb4ee24f896f4a8546dd8023/parlai/utils/misc.py#L633-L646

Also, the magnitude of the reward field is not currently used. Only binary negative/non-negative. That may be a worthwhile future extension.

For both of these above, I would thoroughly welcome a PR

**Comment by hadasah** [comment]
@mvh57 Stephen's answered (1) I believe. Feel free to submit PRs, but if needed, I can make the change to ensure that reward gets parsed as a float or int if you haven't done so already. I can also add the ability to make rewards non-binary (negative/non-negative) but as Stephen said, that doesn't exist at the moment and you're very welcome to send a PR.

For (2), no - and since it's typically the case that you'd need to parse your dataset into one of our formats anyways, it's probably similar amounts of work to have the reward field in each turn. If you have a particular reason to want rewards associated with an episode, we could potentially talk about adding that functionality.

**Comment by mvh57** [comment]
Thanks @stephenroller and @hadasah !! This is extremely helpful!
In regard to (1), that sounds good. If you'd be willing to make that change @hadasah so that reward is parsed as an integer I think that would be great. I haven't made it yet. In regard to (2), it's not so much about the amount of work, as it is I wonder about the case where individual dialogue pairs are acceptable, but the overall episode is poor quality due to lack of consistent context throughout (which I've had happen before). Then it seems it would make more sense to have a negative reward apply more globally to the episode than to each dialogue pair.

I'll delve more deeply into the code base so that I can make some contributions going forward. Still relatively new to both Parlai (and Python for that matter!), though I'm excited to continue learning more, as I think this is such exciting work.

**Comment by stephenroller** [comment]
If you wanted to do a global reward for the whole convo, just apply the reward to every turn

**Comment by mvh57** [comment]
> Thanks @stephenroller and @hadasah !! This is extremely helpful!
> In regard to (1), that sounds good. If you'd be willing to make that change @hadasah so that reward is parsed as an integer I think that would be great. I haven't made it yet. In regard to (2), it's not so much about the amount of work, as it is I wonder about the case where individual dialogue pairs are acceptable, but the overall episode is poor quality due to lack of consistent context throughout (which I've had happen before). Then it seems it would make more sense to have a negative reward apply more globally to the episode than to each dialogue pair.
> 
> I'll delve more deeply into the code base so that I can make some contributions going forward. Still relatively new to both Parlai (and Python for that matter!), though I'm excited to continue learning more, as I think this is such exciting work.

Hi @hadasah and @stephenroller, following up on this issue from September, I am wondering if you've had a chance to update the unlikelihood model so that the reward parameter can be non-binary (ie, take on integer or float value, including 0). Thanks for your help with this.
