### ISSUE TITLE
Unsafe model reply detected meaning

### ISSUE THREAD

**Issue by aslu98** [facebookresearch/ParlAI#2976]
Hello, I have a very simple question about the meaning of the message `[Unsafe model reply detected. Clearing agent history. Please try again.]` when using BlenderBot.
I guess it has something to do with the safety layer to prevent the model from answering in an inappropriate way.
Does this mean that **my** message is "too rude" or that the model produced an answer to my message and the safety layer filtered it beacuese **the bot** answer would have been inappropriate?

I tend to the second explanation but thought it was better to ask.

**Comment by stephenroller** [comment]
I believe the released version filters on both the human and the bot, but gives different messages for each.
