### ISSUE TITLE
Printing a Message After episodeDone = True

### ISSUE THREAD

**Issue by Ufukdogann** [facebookresearch/ParlAI#2983]
@stephenroller 

I am using the web browser version of chatbot and after writing [DONE], without showing anything on the website, the connection closes.

So, I would like to show a message like "Thanks" after the user writes [DONE].

I have tried this on **chatbot/worlds** file, **line 70**. However, it did not work.

Can you help me with that, please?

```
        if a is not None:
            if '[DONE]' in a['text']:
                self.agent.observe(
                    {
                        'id': 'World',
                        'text': 'Thanks',
                    }
                )
                a = self.agent.act()
                self.episodeDone = True
```

**Comment by Ufukdogann** [comment]
@stephenroller 

I debugged the code and I saw that whenever I wrote a message in the website, the code below is running.

```
    def _interactive_running(self, reply_text):
        data = {}
        data['text'] = reply_text.decode('utf-8')
        if data['text'] == "[DONE]":
            print('[ Closing socket... ]')
            SHARED['ws'].close()
            SHARED['wb'].shutdown()
        json_data = json.dumps(data)
        SHARED['ws'].send(json_data)
```

So, I have tried to modify if data['text'] == "[DONE]": with adding 

```
        json_data = json.dumps(data)
        SHARED['ws'].send(json_data)
```
lines in order to send the '[DONE]' to the do_POST function in the same folder however, it does not send it.

**Comment by stephenroller** [comment]
Not sure, but I think it needs to be handled in the world.

Please don’t @ individuals when filing issues.

**Comment by Ufukdogann** [comment]
@stephenroller oh okay, sorry for the mentions.

I handled in client.py folder. 

I solved like this because after closing the terminal, what I see is the model_response['text'] is written. So, what I have done is, I added the closing terminal code and now terminal closes, and I am seeing the message I want to show.

Maybe it is a bad way to do it but it is working, so please let me know if you have a better solution.

```
    def _interactive_running(self, reply_text):
        data = {}
        data['text'] = reply_text.decode('utf-8')
        if data['text'] == "[DONE]":
            self.send_response(200)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            model_response = {'id': 'Model', 'episode_done': False}
            model_response['text'] = 'In order to finish the experiment, please do the test on that link. xxx.com '
            message_available.clear()
            json_str = json.dumps(model_response)
            self.wfile.write(bytes(json_str, 'utf-8'))
            print('[ Closing socket... ]')
            sys.exit()
            #SHARED['ws'].close()
            #SHARED['wb'].shutdown()

        json_data = json.dumps(data)
        SHARED['ws'].send(json_data)
```

**Comment by stephenroller** [comment]
Hmm, That reason reasonable enough
