### ISSUE TITLE
Heroku's App Name with Unexpected Tokens

### ISSUE THREAD

**Issue by jasonwu0731** [facebookresearch/ParlAI#2985]
**Bug description**

The default name to a Heroku app is [here](https://github.com/facebookresearch/ParlAI/blob/master/parlai/mturk/core/server_utils.py#L136), but Heroku has some restriction on the app name. 

```
Name must start with a letter, end with a letter or digit, and can only contain lowercase letters, digits, and dashes.
```

The default user_name is the email name, which may consider some tokens such as "." This will cause an error to create the App. Also, the error message afterward is pointing to a wrong reason

```
You have hit your limit on concurrent apps with Heroku, which are required to run multiple concurrent tasks.
Please wait for some of your existing tasks to complete. If you have no tasks running, log in to Heroku and delete some of the running apps or verify your account to allow more concurrent apps
```

**Comment by JackUrb** [comment]
Hi @jasonwu0731 - Indeed this is a bug in ParlAI-MTurk's methodology for handling heroku app names. We are currently in the process of deprecating ParlAI-MTurk entirely in favor of [Mephisto](https://github.com/facebookresearch/Mephisto) and won't be making further updates to it, though we're still migrating and archiving tasks as well as updating documentation to reflect this change.

This problem specifically was solved in mephisto [here](https://github.com/facebookresearch/Mephisto/pull/212/files), and the same fix could be applied locally [here](https://github.com/facebookresearch/ParlAI/blob/291970a63470d9824a40143754c500e2dfd9c652/parlai/mturk/core/server_utils.py#L146) to unblock you.
