### ISSUE TITLE
parlai command doesn't work well when using python3.8

### ISSUE THREAD

**Issue by Reveyer** [facebookresearch/ParlAI#2995]
When I run the following command:
  `parlai train_model -t babi:task10k:1 -m seq2seq -mf /tmp/model_s2s -bs 32 -vtim 30 -vcut 0.95`
there will be some error like:
  `Parse Error: argument -mtw/--multitask-weights: invalid 'multitask_weights' value: 'seq2seq'`

When changed to the following command to run normally
`parlai train_model -t babi --model seq2seq -mf /tmp/model_s2s -bs 32 --validation-every-n-secs 30 --validation-cutoff 0.95`
or
`python -m parlai.scripts.train_model -t babi:task10k:1 -m seq2seq -mf /tmp/model_s2s -bs 32 -vtim 30 -vcut 0.95`

**Comment by stephenroller** [comment]
Thanks for reporting!

**Comment by stephenroller** [comment]
We need to solve this asap

**Comment by stephenroller** [comment]
Fixed with #3284
