### ISSUE TITLE
browser_chat Error: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by aslu98** [facebookresearch/ParlAI#3001]
**Bug description**
Followed the setup instructions here https://github.com/facebookresearch/ParlAI/tree/master/parlai/chat_service/services/browser_chat, but when I run the client script I get this error:

```
Connecting to port:  10001
[Errno 99] Cannot assign requested address
Connection closed
```

**Reproduction steps**
`python3 parlai/chat_service/services/browser_chat/client.py --port 10001`

**Expected behavior**
Be able to chat with the model on a browser page.

**Additional context**
I tried to run the `client.py` inside a docker image which published and exposed ports 8080, 80 and 10001 while the `run.py `was running in a docker image which exposed port 10001.

**LITTLE BUG**
First time I run it, I got `ModuleNotFoundError: No module named 'tornado`'. Solved it installing tornado with `python3 -m pip install tornado`.

**Comment by stephenroller** [comment]
I think something else is on that port, maybe another copy?

You can use `lsof -i TCP:10001`, preferably as root, to try to find find it

**Comment by aslu98** [comment]
Sorry, I forgot to mention that I already checked if the port was free with `netstat`, also tried `lsof -i TCP:10001` now and got no output.
Thanks for answering.

**Comment by aslu98** [comment]
I'm sorry, this was really an issue regarding Docker. I had to use `--network==host` to expose my ports. I'm closing this issue.

**Comment by stephenroller** [comment]
I haven't used docker with parlai at all. Can you give a brief list of all the issues you've had? Something we might want to write down for posterity or improve in future releases?

**Comment by aslu98** [comment]
Sure, these are the things I remember I had some trouble with, but I'm new also to docker so they may be trivial:

>  Trying to train the model during building: this can't be done because it is not possible to use the GPUs, that can be used just at run time. Also, the availability of the GPUs must be checked at run-time.
> Missing `wget` and `tornado` as I mentioned in other issues (my start image was 10.0-cudnn7-devel-ubuntu18.04), that were not installed during setup
> To use chat_browser, `--network==host` must be specified as an arg of the `run` command in both the server and client container 

If anything else comes to my mind I will edit this post.

**Comment by stephenroller** [comment]
Thanks for the feedback!
