### ISSUE TITLE
Can't train with parlai train_model while python3 parlai/scripts/train_model.py is working

### ISSUE THREAD

**Issue by aslu98** [facebookresearch/ParlAI#3016]
**Bug description**
If I try to use the command parlai I get an error. `python3 parlai/scripts/train_model.py` with the same args works nicely.

**Reproduction steps**
`parlai train_model -t blended_skill_talk,wizard_of_wikipedia,convai2:normalized -m transformer/generator --multitask-weights 1,3,3,3 --init-model zoo:tutorial_transformer_generator/model --dict-file zoo:tutorial_transformer_generator/model.dict --embedding-size 512 --n-layers 8 --ffn-size 2048 --dropout 0.1 --n-heads 16 --learn-positional-embeddings True --n-positions 512 --variant xlm --activation gelu --skip-generation True --fp16 True --text-truncate 512 --label-truncate 128 --dict-tokenizer bpe --dict-lower True -lr 1e-06 --optimizer adamax --lr-scheduler reduceonplateau --gradient-clip 0.1 -veps 0.25 --betas 0.9,0.999 --update-freq 1 --attention-dropout 0.0 --relu-dropout 0.0 --skip-generation True -vp 15 -stim 60 -vme 20000 -bs 16 -vmt ppl -vmm min --save-after-valid True --model-file /tmp/test_train_90M
`

**Logs**
Please paste the command line output:

```
Traceback (most recent call last):
  File "/Users/asialucchi/opt/anaconda3/bin/parlai", line 11, in <module>
    load_entry_point('parlai', 'console_scripts', 'parlai')()
  File "/Users/asialucchi/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/asialucchi/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2851, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'parlai') not found
```

**Comment by stephenroller** [comment]
I think upgrading to myst-parser and tokenizers messed up a few people's environments. Try this:

```
pip install -U tokenizers==0.8.0 docutils==0.15
python setup.py develop
```
and retry

**Comment by aslu98** [comment]
Thanks, now it works

**Comment by stephenroller** [comment]
Hi @aslu98 next week the whole team is spending a full day doing nothing but writing tutorials and docs. Do you have requests?

**Comment by aslu98** [comment]
Hi, thank you for considering to ask me this!
I think the main aspects I would like to be explained further are:
- Specify which args you **must** put in the training command (the ones you must put) and for some of them example values. For example, I still have no idea what to put in `--bpe-vocab` and `--bpe-merge` if I want to use` --dict-tokenizer bytelevelbpe` instead of bpe with blender3B.
- Specify the meaning of all args, even if some of them seems obvious. For example, I did not find the meaning of `--dict-lower`, `--history-add-global-end-token`, `--learn-positional-embeddings ` and others (using the docs search). 
- Suggest ways to attempt doing the training if you don't have enough GPU ram

**Comment by aslu98** [comment]
Very simple question so I'm adding it here as I found nothing about this in the docs and it might be worth adding:

- Is Gradient Checkpointing available with the transformer? Is it done by default, is it possible to do it by using some arg or is it not implemented at all?

**Comment by stephenroller** [comment]
I implemented it a few months ago, but never landed it because it turned out to not be valuable for us

**Comment by aslu98** [comment]
Thanks for the quick answer.
