### ISSUE TITLE
how to use poly-encoder for a retrieval model

### ISSUE THREAD

**Issue by noowad93** [facebookresearch/ParlAI#3032]
Hello.
I have a question about the retrieval task using poly-encoder.
Your papers (**Recipes for building an open-domain chatbot** or **Deploying Lifelong Open-Domain Dialogue Learning**, etc.) say that poly-encoder was used as a retrieval model, but I think poly-encoder is not suitable for ANN search (like faiss) because of the architecture of a scoring module. 
How do you perform retrieval on a million scale or a billion-scale answer selection task?

**Comment by stephenroller** [comment]
We don’t. Our retrieval models are over the fine tune sets, which are on the order of hundreds of thousands.
