### ISSUE TITLE
ValueError: Dictionaries should be pre-built before distributed train.

### ISSUE THREAD

**Issue by 731935354** [facebookresearch/ParlAI#3058]
**Bug description**
I tried to use 4 GPUs for distributed training, but got:
"ValueError: Dictionaries should be pre-built before distributed train."

**Training command**
```
parlai multiprocessing_train -df zoo:bert/bert-base-uncased-vocab.txt -m bert_ranker/cross_encoder_ranker \
    -t convai2 --type-optimization ${type_optimization} --num-epochs 10 --batchsize ${batchsize} \
    --label-truncate 60 --text-truncate 360 --candidates ${candidates} --dict-lower true \
    --optimizer adamax --fp16 true --model-file ${model_file} --update-freq 1 -veps 0.2 \
    --validation-patience 5 --validation-metric-mode max --dynamic-batching full
```

**Logs**
2020-09-08 17:00:49,315 INFO     | Distributed group initialized
2020-09-08 17:01:15,366 INFO     | building dictionary first...
Traceback (most recent call last):
  File "/path/to/ParlAI/bin/parlai", line 11, in <module>
    load_entry_point('parlai', 'console_scripts', 'parlai')()
  File "/ath/to/ParlAI/parlai/core/script.py", line 272, in superscript_main
    SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/path/to/ParlAI/parlai/core/script.py", line 88, in _run_from_parser_and_opt
    return script.run()
  File "/path/to/ParlAI/parlai/scripts/multiprocessing_train.py", line 86, in run
    return launch_and_train(self.opt, port)
  File "/path/to/ParlAI/parlai/scripts/multiprocessing_train.py", line 60, in launch_and_train
    retval = multiprocess_train(0, opt, port)
  File "/path/to/ParlAI/parlai/scripts/multiprocessing_train.py", line 42, in multiprocess_train
    return single_train.TrainLoop(opt).train()
  File "/path/to/ParlAI/parlai/scripts/train_model.py", line 275, in __init__
    build_dict(opt, skip_if_built=True)
  File "/path/to/ParlAI/parlai/scripts/build_dict.py", line 93, in build_dict
    raise ValueError('Dictionaries should be pre-built before distributed train.')
ValueError: Dictionaries should be pre-built before distributed train.

**Additional context**
It worked well when I use DataParallel.

**Comment by stephenroller** [comment]
It's not a bug, it's a real requirement. Use "parlai build_dict" to build a dictionary and pass the prebuilt dictionary to train_model as the --dict-file argument.

**Comment by 731935354** [comment]
Hi Stephen, I tried to build a Bert dictionary for my own dataset using
```
parlai build_dict -t mytask --dict-file bert.dict \
        --bpe-vocab /path/to/ParlAI/data/models/bert_models/bert-base-uncased-vocab.txt \
        -m parlai.agents.bert_ranker.cross_encoder_raner:CrossEncoderRankerAgent
```
And an error came out:
`Parse Error: argument -mtw/--multitask-weights: invalid 'multitask_weights' value: 'parlai.agents.bert_ranker.cross_encoder_raner:CrossEncoderRankerAgent'`

I tried to omit the `-m` parameter, the dictionary could be built, but I don't think the `bert-base-uncased-vocab.txt` was used correctly, the vocabulary just looked like a word-level vocab (instead of word-piece level). I checked the `bert-base-uncased-vocab.txt` and the vocab file contains word pieces.

**Comment by 731935354** [comment]
This command worked well for me:
```
parlai build_dict -t mytask --dict-file bert.dict \
--bpe-vocab /ptah/to/ParlAI/data/models/bert_models/bert-base-uncased-vocab.txt \
--dict-class 'parlai.agents.bert_ranker.bert_dictionary:BertDictionaryAgent'
```
Though `--dict-class` is not a directly visible argument for `parlai build_dict`. And I found that the built dictionary only contains 4 tokens. I guess other tokens are covered implicitly in BertDictionaryAgent. I will really appreciate it if you can provide more clarification here.
