### ISSUE TITLE
run interactive_web error

### ISSUE THREAD

**Issue by tearsroad** [facebookresearch/ParlAI#3062]
**Bug description**
Please enter a clear and concise description of what the bug is.

**Reproduction steps**
Enter steps to reproduce the behavior.

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Logs**
Please paste the command line output:

```
Output goes here
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)
![image](https://user-images.githubusercontent.com/10541854/92596681-c9293480-f2d8-11ea-82e8-6a6f7fac9b6b.png)

**Comment by stephenroller** [comment]
Thanks for reporting

**Comment by stephenroller** [comment]
A bit flummoxed as to why datapath would be none. Opts look like they're being set correclty.
