### ISSUE TITLE
Need help regarding pretraining Blenderbot  with reddit .

### ISSUE THREAD

**Issue by aadityachapagain** [facebookresearch/ParlAI#3071]
@stephenroller  We are trying to replicate the run at 1B parameters using the exact hyperparameter settings and input data but we will be using Parlai instead of Fairseq.

Could you confirm for us how many Reddit threads you used for training and the exact hyperparameter settings?

My understanding is that it took 4 days using 128 gpus in Fairseq, each with 32gb memory. Did you use SLURM
to run across those gpus?

We would like to begin by investing/risking 2 days for our initial run. Since we will be running for half as long with a framework that is half as fast and with 16gb gpus, could you advise the best way to modify the hyperparamters to achieve this?

**Comment by stephenroller** [comment]
For BlenderBot, see the details in the paper for specifics (num threads and hyperparameters).

Yes we use SLURM. the `distributed_train` script is designed to run in a SLURM environment.

I trained a 1B model on a slightly different version of reddit (filtered a bit more heavily. can't share details.) and got 16.4ppl after 210k updates. This was trained in ParlAI in 4 days, with these hyperparameters on 128 GPUs:

```
python -u -m parlai.scripts.distributed_train -t REDACTED_LIKE_REDDIT -dt train:stream -vtim 900 --attention-dropout 0.1 --batchsize 4 --eval-batchsize 8 --model transformer/generator --embedding-size 1536 --ffn-size 6144 --variant prelayernorm --n-heads 16 --n-positions 512 --n-encoder-layers 2 --n-decoder-layers 22 --dict-tokenizer bytelevelbpe --dict-file zoo:blender/reddit_3B/model.dict --dropout 0.1 --fp16 True --label-truncate 128 --log_every_n_secs 10 -lr 0.0003 --optimizer adam --relu-dropout 0.0 --activation gelu --model-parallel false --load-from-checkpoint false --text-truncate 512 --warmup-updates 10000 --fp16-impl apex --update-freq 2 --gradient-clip 10.0 --skip-generation True -vp -1 -vmt ppl -vmm min --dynamic-batching full -tblog true --lr-scheduler cosine --max-lr-steps 200000 [OTHER REDACTED BUT UNRELATED] --model-file [redacted]/model --distributed-world-size 128
```

It did 0.67 epochs of the dataset in that time.

**Comment by aadityachapagain** [comment]
Thanks stephen, that helped me a lot.
