### ISSUE TITLE
Documentation for parlai.core.build_data.DownloadableFile fails to mention that the Checksum is sha256

### ISSUE THREAD

**Issue by skiingpacman** [facebookresearch/ParlAI#3075]
Documentation for parlai.core.build_data.DownloadableFile fails to mention that the required argument Checksum is sha256. Would be great to mention to avoid the need to ask around or digging around in the code.

**Comment by skiingpacman** [comment]
Oh! Seems I'm blind - I looked at Checksum and not hashcode.

**Comment by stephenroller** [comment]
Still not a bad thing to mention in the FAQ and the task tutorial
