### ISSUE TITLE
Training 90M Blender model from scratch with own dataset of different language. 

### ISSUE THREAD

**Issue by VikasRajashekar** [facebookresearch/ParlAI#3076]
I am planning to pre-train the model from scratch in the German language. 
Is there some sample code/Notebook available on how to train the model from scratch using its own data set in a different language? 

I am looking at the 90M model at: https://parl.ai/projects/recipes/

**Comment by aadityachapagain** [comment]
For different language you have to train your own tokenizer.
If you are planning to use parlai for pretraining here are the list of the things you can do to train your own model from scratch. 
1.  Train tokenizer on your datasets. (use huggingface tokenizer). This will produce 3 files .dict, <filename>.dict-merge.txt, <filename>.dict-vocab.txt, <filename>.dict.
2. Replace --dict-file with your own dict file path.
3. You can use scripts mentioned in 90m recipe page, with slight modification, replace `-t` with your own task. I suggest you to create your own task inside tasks directory, as it will provide you much flexibility, especially when you have large datasets (for large datasets use -dt train:stream, but you have configure your tasks to actually use that functionality .

or You can use fariseq. Last time i tried training with fairseq, it was faster than parlai.

**Comment by stephenroller** [comment]
This is accurate.

I also recommend creating a ChunkTeacher for very large datasets, which avoids loading the full dataset into memory while retaining strong randomness.
