### ISSUE TITLE
Run generative WoW in interactive mode with gold standard facts and no topic

### ISSUE THREAD

**Issue by melody-ju** [facebookresearch/ParlAI#3080]
Hi, apologies in advance if this is not the correct place to ask this question.

I would like to use the WoW model to have fact-grounded dialogues. However, instead of having a topic chosen at the beginning and relevant facts for the conversation then extracted from Wikipedia, I would like to provide my own (gold standard) facts at the start of the conversation. 

From trying to trace backward from the "parlai interactive" command, I can't tell which script(s) to modify in order to modify the interactive setup this way for WoW. Would really appreciate any pointers in the right direction.

Thanks so much,

Melody

**Comment by stephenroller** [comment]
I'm looking forward to when GitHub releases their new Discussions feature.

You can add the knowledge field, which is a long piece of text with each piece of knowledge separated by '\n'. See this docstring:

https://github.com/facebookresearch/ParlAI/blob/a3f581cad075db981707dfa070f7b2e9c8bba44b/parlai/tasks/wizard_of_wikipedia/agents.py#L187

**Comment by melody-ju** [comment]
Hey @stephenroller , thanks for your quick reply. Am I correct to switch to this agent by supplying the following for the -t flag to interactive:

`parlai interactive -mf models:wizard_of_wikipedia/end2end_generator/model -t wizard_of_wikipedia:WizardDialogKnowledgeTeacher`

After that, do I simply supply the knowledge to the model in this format:
`Enter Your Message: knowledge:{sent 1}\n{sent 2}\n{sent 3} text: {the message to begin the conversation}`?

**Comment by stephenroller** [comment]
Ah no, interactive has some other stuff that complicates it (these Worlds that set up the pipeline).

As a starter, I recommend creating a [custom teacher](https://parl.ai/docs/tutorial_task.html#dialogteacher) that has a knowledge field (in addition to text/labels). Then use 

`parlai display_model -mf models:wizard_of_wikipedia/end2end_generator/model -t my_custom_teacher`
