### ISSUE TITLE
Unit test failure

### ISSUE THREAD

**Issue by EricMichaelSmith** [facebookresearch/ParlAI#3093]
**Bug description**
`test_dialogpt - tests.nightly.gpu.test_dialogpt.TestDialogptModel` sometimes fails the CI check.

**Reproduction steps**
See for instance https://app.circleci.com/pipelines/github/facebookresearch/ParlAI/6870/workflows/dc20f774-df69-42a2-a818-b4df8faba13c/jobs/53834

**Comment by stephenroller** [comment]
We should probably just double the number of epochs on this and give it a retry decorator.

**Comment by EricMichaelSmith** [comment]
Okay, let's see if this works with https://github.com/facebookresearch/ParlAI/pull/3097
