### ISSUE TITLE
error: requests 2.18.4 is installed but requests<3,>=2.21.0 is required by {'tensorboard'}

### ISSUE THREAD

**Issue by datawisely** [facebookresearch/ParlAI#3126]
Ubuntu 18.04.5 LTS
PyTorch 1.6.0
TorchVision 0.7.0

xxx@xx:~/ParlAI$ sudo -H python3 setup.py develop
running develop
running egg_info
creating parlai.egg-info
writing parlai.egg-info/PKG-INFO
writing dependency_links to parlai.egg-info/dependency_links.txt
writing entry points to parlai.egg-info/entry_points.txt
writing requirements to parlai.egg-info/requires.txt
writing top-level names to parlai.egg-info/top_level.txt
writing manifest file 'parlai.egg-info/SOURCES.txt'
reading manifest file 'parlai.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'parlai.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python3.6/dist-packages/parlai.egg-link (link to .)
parlai 0.9.2 is already the active version in easy-install.pth
Installing parlai script to /usr/local/bin

Installed /home/xxx/ParlAI
Processing dependencies for parlai==0.9.2
error: requests 2.18.4 is installed but requests<3,>=2.21.0 is required by {'tensorboard'}

xxx@xxx:~/ParlAI$ sudo -H pip install --upgrade requests
Requirement already up-to-date: requests in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests)
Requirement already up-to-date: chardet<4,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests)
Requirement already up-to-date: idna<3,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests)
Successfully installed certifi-2020.6.20 chardet-3.0.4 idna-2.10 requests-2.24.0 urllib3-1.25.10

Thanks!

**Comment by stephenroller** [comment]
``` $ pip freeze | grep requests
requests==2.22.0
```

Thanks for reporting. Will need to update requirements.txt to say `requests<3,>=2.21.0`.

**Comment by dianaglzrico** [comment]
Updated.
