### ISSUE TITLE
display_data.py printing duplicate episodes

### ISSUE THREAD

**Issue by ANarayan** [facebookresearch/ParlAI#3127]
When run on the empathetic dialogues dataset (empathetic_dialogues:EmpatheticDialogues), the display_data() function in scripts/display_data.py returns duplicate episodes.

the command is as follows: `parlai display_data -t empathetic_dialogues:EmpatheticDialogues`

Some sample duplicate episodes look like the following. I don't know why this is happening, but I do not believe it is the intended output. 

--- NEW EPISODE: empathetic_dialogues:EmpatheticDialogues - - -
I remember going to see the fireworks with my best friend. It was the first time we ever spent time alone together. Although there was a lot of people, we felt like the only people in the world.
   **Was this a friend you were in love with, or just a best friend?**
_This was a best friend. I miss her._
   **Where has she gone?**
_We no longer talk._
   Oh was this something that happened because of an argument?
--- NEW EPISODE: empathetic_dialogues:EmpatheticDialogues - - -
**Was this a friend you were in love with, or just a best friend?**
   _This was a best friend. I miss her._
**Where has she gone?**
   _We no longer talk._
--- NEW EPISODE: empathetic_dialogues:EmpatheticDialogues - - -
 it feels like hitting to blank wall when i see the darkness
   **Oh ya? I don't really see how**
_dont you feel so.. its a wonder_ 
   **I do actually hit blank walls a lot of times but i get by**
 _i virtually thought so.. and i used to get sweatings_
   Wait what are sweatings
---NEW EPISODE: empathetic_dialogues:EmpatheticDialogues - - -
**Oh ya? I don't really see how**
   _dont you feel so.. its a wonder_ 
**I do actually hit blank walls a lot of times but i get by**
    _i virtually thought so.. and i used to get sweatings_

**Comment by stephenroller** [comment]
It's two sides of the same conversation. In one, speaker A is the prompt and speaker B is the label, and in the other, speaker B is the prompt and speaker A is the label.
