### ISSUE TITLE
Document that when subclassing DialogTeacher `opt["datafile"]` needs to be populated

### ISSUE THREAD

**Issue by skiingpacman** [facebookresearch/ParlAI#3139]
Documentation should indicate that `opt["datafile"]` needs to be populated (if `shared` is not) before calling `__init__.super()` when subclassing DialogTeacher as the current error/traceback doesn't clearly indicate what the issue is (example below) without diving deeply into the code.

Alternatively catch this in DialogTeacher and produce a more meaningful error, or provide a default in DialogTeacher if `opt["datafile"]` isn't set.

```
Traceback (most recent call last):
  File ".../parlai/core/worlds.py", line 1211, in _create_task_agents
    task_agents = my_module.create_agents(opt)  # type: ignore
AttributeError: module 'parlai_fb.tasks.work_in_progress.agents' has no attribute 'create_agents'

During handling of the above exception, another exception occurred:
...
<snip>
...
    super().__init__(opt, shared)
  File ".../parlai/core/teachers.py", line 546, in __init__
    **kwargs,
  File ".../parlai/core/teachers.py", line 678, in __init__
    self._load(data_loader, opt['datafile'])
KeyError: 'datafile'
```

**Comment by stephenroller** [comment]
I had actually debated with myself on changing the default to something I thought was more sensible. (#3140).  You've pushed me to make a PR.
