### ISSUE TITLE
How do I switch models in blender?

### ISSUE THREAD

**Issue by zaharPonimash** [facebookresearch/ParlAI#3150]
Hello! Blender, as I understand it, has three learning modes.
The first is learning to search the base, the second is a generative model, and the third is a combination of the first two.
As far as I understand, it is easiest to train the first model, because it is enough to change the dictionary of answers and retrain. I would like to know how to switch training between the first, second and third model?

**Comment by stephenroller** [comment]
They're entirely different models, not different modes.  We only released the generative models, which were by far the best.

**Comment by zaharPonimash** [comment]
Thank you very much for your reply!

**Comment by zaharPonimash** [comment]
What is the approximate size of the dataset required to fine-tune a model with 2.7 billion parameters?

**Comment by stephenroller** [comment]
More is always better, but about 10k will get you somewhere pretty impressive.

**Comment by zaharPonimash** [comment]
Thank you for your response!
