### ISSUE TITLE
Add --version flag to parlai command

### ISSUE THREAD

**Issue by DNGros** [facebookresearch/ParlAI#3163]
**Is your feature request related to a problem? Please describe.**
Make parlai "super command" conform the unix idiom of a --version flag.

Usecase: A user switching between virtual environments or reading about the release of a new feature should be able to easily identify which version they have on their path.

**Describe the solution you'd like**
```bash
$ parlai --version
parlai version X.X.X
# Optionally any relevant install info (not probably not any)
# Optionally copyright/license info (up to the maintainers whether you want this here or not)
```

**Describe alternatives you've considered**
```bash
$ python -c "import parlai; print(parlai.__version__)"
0.9.2
```
A little less natural

**Comment by stephenroller** [comment]
Seems like a good idea.
