### ISSUE TITLE
Cannot change the locale (in MTurk's Sandbox)

### ISSUE THREAD

**Issue by gentaiscool** [facebookresearch/ParlAI#3169]
I have an issue in testing "PersonaChat" task in MTurk's Sandbox. I cannot change the `LocaleValues` qualification. 
It still uses the default English-speaking country locales `AU, CA, GB, NZ, US`.
My current locale is `HK`.

Previously, I added the following code and it worked about a month ago.

`
agent_qualifications = [
            {
                'QualificationTypeId': "00000000000000000071",
                'Comparator': 'EqualTo',
                'LocaleValues': [{'Country': 'HK'}],
            }
        ]
`
`
        mturk_manager.create_hits(qualifications=agent_qualifications)
`

Thanks in advance!

**Comment by stephenroller** [comment]
@JackUrb

**Comment by gentaiscool** [comment]
Got it! Thanks for your help 👍
