### ISSUE TITLE
Inconsistency for fine-tuning guide on PolyEncoders

### ISSUE THREAD

**Issue by shuuki4** [facebookresearch/ParlAI#3170]
Hello,
I am currently using ParlAI to fine-tune pre-released pretrained transformers (`zoo:pretrained_transformers/bi_model_huge_reddit/model`) in other dialogue datasets.

I found two READMEs about this fine-tuning procedure, one in the `polyencoder` project page and one in the model zoo `pretrained_transformers`.
- https://github.com/facebookresearch/ParlAI/tree/master/projects/polyencoder
- https://github.com/facebookresearch/ParlAI/tree/master/parlai/zoo/pretrained_transformers

However, README file in these two project pages have different guides for fine-tuning: The former one suggests `--polyencoder-type codes`, and the latter one suggests `--polyencoder-type n_first`.
I guess the model opt file contains `polyencoder_type=n_first`, however, the default & recommended parameter in the PolyEncoder agent is `polyencoder_type=codes`, which makes me quite confused.

Could you guys provide a unified guide for using these polyencoder models? :) Thanks!

**Comment by stephenroller** [comment]
It's a hyperparameter. Iirc sometimes one does better than the other. Either is probably fine but the other night do slightly better.
