### ISSUE TITLE
Huggingface Integration to models other than GPT2

### ISSUE THREAD

**Issue by vishakhpk** [facebookresearch/ParlAI#3172]
#2364 mentions that the goal is to eventually expand to more generative models from Huggingface. 
Dialogpt (#3007) and Distilgpt (#2997) use largely the same agent and model. Is there a way to extend the same to the other models currently?

My understanding is that it would require a new model class and agent analogous to the ones in [gpt2.py](https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/hugging_face/gpt2.py). Since the HF models all have similar interfaces, I thought this should be possible to develop. What are the specific points where it might fail?

**Comment by emilydinan** [comment]
Hi @vishakhpk thanks for posting! 

We don't have immediate plans to extend this to other agents, but doing so should be somewhat straightforward depending on the agent. Here are some places to start:
- PR #3007 is a good example of what it takes to extend a GPT2 agent. It would be a bit more complicated to extend a different agent. #2634 is the PR that originally added the GPT2 agent if you want to take a look there.
- You mentioned in your email that you're looking to use the Hugging Face Bart agent. I would point you to the [parlai Bart code](https://github.com/facebookresearch/ParlAI/tree/master/parlai/agents/bart) to see if using this is suitable on it's own. 
- If the ParlAI Bart is not suitable, [this doc](https://parl.ai/docs/tutorial_torch_generator_agent.html) gives a pretty good demo of what's need to extend a torch generator agent.

**Comment by stephenroller** [comment]
We would welcome any PRs that added more integrations.

**Comment by stephenroller** [comment]
(Also yes, our Bart agent works out of the box and actually works marginally better than HF's due to some weird obscurities in BART's start tokens)
