### ISSUE TITLE
How to keep mturk link alive

### ISSUE THREAD

**Issue by Stefan1220** [facebookresearch/ParlAI#3173]
Hi guys,

I am using parlai mturk and trying to run a task on sandbox. After that, I could get a link to reach the HIT task. But the problem is that the link can be valid only for a while. I tried the 'screen' command in linux to let the task running on the background, but after like 24 hours, the link still became invalid. Any idea or suggestions about how to keep the link alive for a long time? 

Thanks for your help!

**Comment by stephenroller** [comment]
@JackUrb i didn't think there was a timeout?

**Comment by JackUrb** [comment]
I also didn't think there was a timeout - @Stefan1220 what happens when you visit the link, does MTurk say there are no HITs available, or does it direct you somewhere with a heroku app that isn't running?

**Comment by Stefan1220** [comment]
Yeah, when I visit the link, the mturk website shows that "There are no more of these HITs available"

**Comment by Stefan1220** [comment]
when I run the task on remote server, It seems that I have to always keep the session on shell alive. When I get disconnected with the remote server, the link becomes dead along with the window session. That's why I used the 'screen' command to let it run on the background, but it seems 'screen' command cannot guarantee the session always alive (it becomes invalid around 24 hour later)

**Comment by JackUrb** [comment]
I also run my tasks in `screen` (and have had tasks that run for upwards of a week without issue). What's in the terminal if you come back to the screen?

**Comment by Stefan1220** [comment]
when I come back to the screen, it's weird that those screen sessions actually have been cleared. But I didn't manually interrupt them. So I suspect that 'screen' cannot last for a long time like over 24 hours. But since you are also using screen and it seems it can run for a long time, then I think I will try it again to see it will work or not and let you know. Thanks!

**Comment by JackUrb** [comment]
It is possible that your remote server is killing tasks that last for more than a certain duration, in which case you'll have to talk to your server admin.

**Comment by Stefan1220** [comment]
I tried 'nohup' command, and it seems more stable and can last for a long time. Thanks for you help!
