### ISSUE TITLE
Deploying chat service to AWS or Heroku

### ISSUE THREAD

**Issue by jakeane** [facebookresearch/ParlAI#3174]
Hi all,

I swear the solution to this is staring me right in the face, but I definite answer from you is likely better in the long run.

I have been part of a team with @mvh57 that is developing a custom chat service through your platform, and we have been interacting with it through the "Browser" method specified on your documentation. However, we want to bring take this chat service to a remote server hosted on AWS (or Heroku), so multiple users can have one-on-one conversations with the chat service through the client application we have also built. However, I am not sure how to proceed with this.

It seems like the file chat_service/core/server/server.js is a potential entry point, but I wonder if the chat_service/services/browser_chat/run.py file we have previously used has any part in this solution. So, I suppose the question here is this: Given a chat service we have successfully run through a local browser, which is based on a custom model, how can this be deployed onto AWS or Heroku? Such that multiple users can interact with it one-on-one?

Let me know if there are any additional bits of context that you need to answer this question. Otherwise I really appreciate you all for this platform.

-Jack

**Comment by stephenroller** [comment]
@klshuster

**Comment by stephenroller** [comment]
And @JackUrb 

I know they have deployed to AWS before for an external demo.

**Comment by JackUrb** [comment]
Hi Jack - hard to know quite what you're trying to do here - is the goal to just put the model onto the AWS server and launch the client there, or to have a proxy setup where heroku or aws routes the incoming requests to the server running ParlAI? 

For the former, you should just be able to just run the same script on the remote server and access it at at the public address and port. (If you want that to be addressable without port, you'll need to set up some reverse proxy to route 80 to the launched port, or run python as admin). 

For the latter, it's a somewhat complicated setup and we haven't incorporated the router setup that ParlAI MTurk used into the chat service implementation.

**Comment by jakeane** [comment]
Hi @JackUrb. Thanks for getting back so quickly.

So my goal is similar to the former you mentioned. We are trying to put a chat service onto a server through AWS, which would then be accessed through a separate client application. However, my backend and AWS knowledge is quite limited, so if you could describe the process in more detail, that would be great!

**Comment by JackUrb** [comment]
I'm by no means an expert on this stuff, just got it set up for a different project. [This guide](https://www.nginx.com/blog/setting-up-nginx/) covers a lot of the steps, and if you follow up through "Opening your webpage". Unfortunately the rest of that guide is setting up nginx for another purpose, so other guides can cover the part of configuring it as a reverse proxy. The "Configure nginx as a reverse proxy" step of [this guide](https://medium.com/@ramavathvinayak/deploy-a-node-js-application-on-aws-ec2-with-nginx-as-a-reverse-proxy-e8f41f1edaef) may prove helpful. There are other resources online about this that will be better than the advice I can give.

**Comment by klshuster** [comment]
One thing I will contribute to this is that we have the `websockets` chat service implementation designed specifically to work with external servers - note that the `browser_chat` is actually just an implementation fo the `websockets` service that utilizes a local browser, however `websockets` should be able to handle most of the work here

**Comment by Parvez2017** [comment]
Hi all, 
I am also facing similar issues with deployment on heroku. Can I use only a binary model like blenderbot on a remote server and get response through a webhook which messenger is using?

Thanks in advance

**Comment by jakeane** [comment]
@JackUrb thank you so much for the help. Went through the guides you provided, and they more or less helped me get there! Also learned a lot through this process.

For those who will inevitably come across this thread in the future:
- Follow [this guide](https://www.nginx.com/blog/setting-up-nginx/#open-web-page) (same one as above) until you reach the "Installing NGINX Software" section.
    - One important note is the instance type you select. The free type, "t2.micro" may not provide enough RAM to run the program, so you likely will have to go to larger. I picked "t2.large" for what its worth.
    - Another difference I did here was within "Configure Security Group" (step 6 of setting up AWS). I added an additional rule where type was "custom TCP", the port was 8080, and the service was anywhere.
- Assuming you are connected to the instance, transport your ParlAI files in. One thing to note though:
    - The ParlAI directory tends to be bloated (sorry devs), so I would recommend trimming off as much fat as possible. This will allow you to install other modules (PyTorch was giving me memory space issues for a bit. Would recommend install it before transferring ParlAI).
- From there start your script using port 8080. Use PM2 to run in background.

**Comment by stephenroller** [comment]
We should link to this post from the docs.

**Comment by jakeane** [comment]
Hi all, again,

I found an issue with the setup I detailed above. If the chatservice is left running for an extended period of time, ~1-2 days, it will become non-responsive, as in not replying to any incoming messages. The "band-aid" solution for this is to set up a cron job to restart the chatservice every 8 hours, which has not let to any issues *yet* as we just have a small test group using the app. The solution is exactly as follows:
- From the EC2 instance, type `crontab -e`. You may have to set some preferences like what editor to use for it.
- At the bottom of the file, add `0 */8 * * * /usr/local/bin/pm2 restart chatbot`. Then save and quit.

However, this would clearly not scale, and it would inevitably lead to some bad experiences for users. I am not sure if the root cause of this issue lies on AWS or ParlAI or somewhere in between. I know the setup I currently have, detailed above, is kind of 'hacky', so maybe I have to set up the Websocket API in the AWS API Gateway for more 'proper' usage. If you guys have any knowledge on keeping the chatbot websocket service running over long periods of time, let me know.

There is also another issue going on here, when a user connects with the websocket, starts having a conversation, and then stops for a brief period of time, ~5-10 minutes, the chatbot becomes unresponsive to the user. Currently I restart the page in order to restart the websocket connect, but of course this is a "band-aid" solution again. In this respect, I am wondering if there is a way to keep the connect 'active' with a 'poke' or something. If you guys have any knowledge on maintaining active websocket connections with users, let me know.

I definitely need to do some research on AWS for this issues, but I think some knowledge on the ParlAI websocket program would also be very helpful, as I currently do not know it very well. I'll likely study the code later, but if you guys, the ParlAI devs, could provide a brief overview of the websocket program for the chatbot service, that would really help me get a better understanding of the program overall.

**Comment by stephenroller** [comment]
Hmm, do you have any monitor of RAM?

**Comment by jakeane** [comment]
Not over a period of time, but I just set up a cronjob to log the memory every 30 minutes. Currently, with 8gb of RAM and after 100 minutes of runtime, 2gb is used, 2gb is free, 3.7gb is buff/cache, and 5.5gb is available. We will see how these numbers change over the course of a few hours.

**Comment by stephenroller** [comment]
Hmm okay, ya I expect something maybe isn't freeing up on a timeout. I'm not too familiar with the chat services code, but I'll ask @klshuster for ideas this week and see if I can look at it.

**Comment by jh-skaion** [comment]
> One thing I will contribute to this is that we have the `websockets` chat service implementation designed specifically to work with external servers - note that the `browser_chat` is actually just an implementation fo the `websockets` service that utilizes a local browser, however `websockets` should be able to handle most of the work here

@klshuster is there a guide you can share on how to deploy the websocket to a local network?
i can run it locally in my computer and connect clients to it, but i would like to install the model in a server and establish connections from other computers in the same network.
thanks

**Comment by klshuster** [comment]
Perhaps @JackUrb may have more context on a concrete example of doing this?

**Comment by JackUrb** [comment]
I don't have any concrete examples unfortunately, but I imagine if you run the service on a networked server on a specific port, then any computer on that network that can access <networked-ip>:<running-port> would be able to hit it, as is. The hard part is updating the client side code to point to that location in a configurable way.

**Comment by jh-skaion** [comment]
> I don't have any concrete examples unfortunately, but I imagine if you run the service on a networked server on a specific port, then any computer on that network that can access : would be able to hit it, as is. The hard part is updating the client side code to point to that location in a configurable way.

So i have a python file that create websocket connection pointing to: "ws = await websockets.connect('ws://localhost:{}/websocket'.format(port))" 

so my question would be how to instead of localhost i can change the config to use a server address.

i noticed parlai is using tornado to create an web application but i am not sure what to do in order to change the localhost.
