### ISSUE TITLE
Beat the Bot Code Availability

### ISSUE THREAD

**Issue by dwlmt** [facebookresearch/ParlAI#3178]
I just noticed when I did a pull from the Facebook master into a fork of mine the Beat the Bot project - https://parl.ai/projects/beat_the_bot/ . I'm interested in doing some interactive evaluation (though not for a while) and so am wondering if the code for this World is available in the repo; mainly the capability to have multiple responses by different agents at the same point in the dialog and the option to choose between them. I did a quick search and apart from the README could not find anything on the master or any see relevant branches.

**Comment by stephenroller** [comment]
The code depends on internal infrastructure so we couldn't open source it, but maybe @emilydinan can share just that section of the world?

**Comment by dwlmt** [comment]
Thanks for the prompt reply. I probably won't do anything in this area for a while because I'm working on some models and datasets at the moment. My main topic is not specifically dialogue but more general generation/understanding task. I'm just thinking that an interactive evaluation chat format with a choice, e.g. choose the answers with property x comparing human/model, gold/model, model/model might be nicer than rank these exported blocks of text or rate them out of 5 evaluation. So the more general code would be helpful.
