### ISSUE TITLE
Unable to connect ParlAI to Mechanical Turk

### ISSUE THREAD

**Issue by derekchen14** [facebookresearch/ParlAI#318]
I am trying to test out the ParlAI in the MTurk sandbox and hitting an issue with Heroku with git.  I read about options to mess with git_url, but I don't believe I have access to this, but I may be missing something basic.  Any idea on how to resolve?

```
You are going to allow workers from Amazon Mechanical Turk to be an agent in ParlAI.
During this process, Internet connection is required, and you should turn off your computer's auto-sleep feature.
Enough HITs will be created to fulfill 1.5 times the number of conversations requested, extra HITs will be expired once the desired conversations start.
Please press Enter to continue... 

Setting up MTurk server...
Heroku: Collecting files...
Heroku: Starting server...
Creating derekchen-bb8a3776-modelevalua... done
Enabling http-session-affinity for derekchen-bb8a3776-modelevalua... done
Traceback (most recent call last):
  File "run.py", line 91, in <module>
    main()
  File "run.py", line 40, in main
    mturk_manager.setup_server()
  File "/Users/derekchen/Documents/active/ParlAI/parlai/mturk/core/mturk_manager.py", line 650, in setup_server
    self.task_files_to_copy)
  File "/Users/derekchen/Documents/active/ParlAI/parlai/mturk/core/server_utils.py", line 214, in setup_server
    return setup_heroku_server(task_name, task_files_to_copy=task_files_to_copy)
  File "/Users/derekchen/Documents/active/ParlAI/parlai/mturk/core/server_utils.py", line 170, in setup_heroku_server
    sh.git(shlex.split('push -f heroku master'))
  File "/Users/derekchen/Applications/anaconda/envs/parlai/lib/python3.6/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/Users/derekchen/Applications/anaconda/envs/parlai/lib/python3.6/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/Users/derekchen/Applications/anaconda/envs/parlai/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/derekchen/Applications/anaconda/envs/parlai/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_128: 

  RAN: /usr/local/bin/git push -f heroku master

  STDOUT:


  STDERR:
fatal: could not read Username for 'https://git.heroku.com': Device not configured
```

**Comment by JackUrb** [comment]
Hi Derek - I'm pretty sure this is related to getting heroku fully initialized. Have you run `heroku login` from the command line? I've been a bit behind on adding everything to the docs but I think that's what's missing here

**Comment by JackUrb** [comment]
Can you check the contents of your $HOME/.netrc file? Somewhere in it should be something like:
`machine api.heroku.com
  password a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6
  login yourEmail@domain.com
machine git.heroku.com
  password a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6
  login yourEmail@domain.com`

If you don't have anything there it might explain the issue. You can create it yourself and populate it with this, just replace the `login` with your heroku login and the `password` with the output of `heroku auth:token`

**Comment by JackUrb** [comment]
Further investigation leads me to believe this could be a git version issue, as some older versions of git do not support credentials in `.netrc`. What version of git are you using?

**Comment by derekchen14** [comment]
Hi Jack, thanks for jumping in.   My .netrc file includes:
```
machine api.heroku.com
  login MyEmail@domain.com
  password 4ea6ba71-3a62-4390-<other numbers>
machine **code.**heroku.com
  login MyEmail@domain.com
  password 4ea6ba71-3a62-4390-<same numbers as above>
```
It was missing a line for **git.**heroku.com, as in your example.  After adding that in along with my login and password, the system seems to be working now!

**Comment by JackUrb** [comment]
Good to hear! I'll investigate why the git.heroku.com line was not included on login and I'll see if I can automate adding the git.heroku.com line to the .netrc if it's missing.

**Comment by derekchen14** [comment]
Thanks so much!
