### ISSUE TITLE
Questions about BERT Ranker

### ISSUE THREAD

**Issue by huhk-sysu** [facebookresearch/ParlAI#3183]
1. I find there are both "bert_ranker/bi_encoder_ranker" and "transformer/biencoder" , and the [project](https://parl.ai/projects/polyencoder/) uses the latter. What's the difference between them, and which one should I choose?
2. The "bert_ranker/bi_encoder_ranker" use "BERT-base-uncased" by default. How can I use another version of BERT, or specific a path to my own BERT?
3. The library 'pytorch-pretrained-bert' has upgraded to ['transformers'](https://github.com/huggingface/transformers). Is there any plan to follow it?

Thanks!

**Comment by stephenroller** [comment]
1. The former is older, and built on hugging face transformers. The latter is built natively in ParlAI, and supports a pretrained model derived from Reddit threads downloaded from pushshift.io
2. I recommend you edit the code
3. I would accept a PR upgrading, if the newer transformers library is found to be compatible. We probably won't update it ourselves, as we tend to use the `transformer/*` models with great frequency, but the BERT ones almost never.
