### ISSUE TITLE
How to style style_gen C75-D+ Generator

### ISSUE THREAD

**Issue by plkmo** [facebookresearch/ParlAI#3191]
Hi there, 
I have been trying out the style_gen model in the model zoo (https://parl.ai/docs/zoo.html#style-controlled-generation-c75-d-generator).

I run the following interactive command:
`parlai interactive --model projects.style_gen.style_gen:StyleGenAgent --model-file zoo:style_gen/c75_labeled_dialogue_generator/model --use-style-frac 1.00`

However, I can't seem to be able to find any documentations (neither here or in the paper) on how exactly the output can be conditioned. Do I append say '[Open]' as a style token before/after my chat inputs? I've tried and it didn't seem to work.

**Comment by stephenroller** [comment]
@EricMichaelSmith

**Comment by stephenroller** [comment]
(seems like we need an interactive mode perhaps?)

**Comment by EricMichaelSmith** [comment]
Cool, good idea - will target working on this during the middle of next week.

**Comment by plkmo** [comment]
Great, thank you

**Comment by EricMichaelSmith** [comment]
Hi plkmo! Unfortunately I don't have time to release a full interactive mode for this given my current roadmap. However, it shouldn't be hard to do this yourself: the key is to, in the dictionary-like object that gets passed to the bot agent through its `.observe()` method, set the 'personality' key to the style that you want the bot to respond with. (If you're not familiar with ParlAI, these dictionary-like objects are `Messages`: https://parl.ai/docs/core/messages.html?highlight=message#module-parlai.core.message)

**Comment by NannaMarcher** [comment]
Hi! I am also curious to know how to pass a personality style to the style_gen model. I am trying to input the personality as a part of a dictionary in the interactive mode, e.g., {personality: sad, text: I have had a bad day}. It does, however, not seem to work - probably since it parses the input from interactive mode as a string and not a dictionary. I am very interested in getting this working, can you help me with this? Thank you in advance!

**Comment by EricMichaelSmith** [comment]
Hi @NannaMarcher! To get this working with interactive mode, you could for instance write a subclass of `InteractiveWorld` that parses the user input string to see if a style is included, and then stick that style into the `'personality'` field of the `Message` representing the user's input.

**Comment by NannaMarcher** [comment]
Thank you so much! Will try that :-)
