### ISSUE TITLE
Receiving several answers from the blender

### ISSUE THREAD

**Issue by zaharPonimash** [facebookresearch/ParlAI#3192]
Hello!
I want to receive several answers to one request.
The idea is to stir up the noise with a little std after the encoding into hidden states. And run the decoder on different vectors. This way I get a lot of answers. 
Could you tell us where the computational graph of the blender is?

**Comment by stephenroller** [comment]
- #3123 makes it so the return message of act()/batch_act() includes all the beams from beam search (or other samples from nucleus/topk). This can easily be used to generate lots of answers.
- BlenderBot is built in pytorch, which doesn't use graphs.

**Comment by zaharPonimash** [comment]
Thank you very much!
