### ISSUE TITLE
I deleted pretrained checkpoints, now they do not auto-download

### ISSUE THREAD

**Issue by zhenduow** [facebookresearch/ParlAI#3195]
Hi, I previously deleted the biencoder checkpoints on reddit. Now it does not automatically download for me when I run interactive.py.

What is the correct way to download the checkpoints again? Thank you!

**Comment by stephenroller** [comment]
Delete the entire "models/pretrained_transformers" folder (in your datapath), or delete "models/pretrained_transformers/.built"

**Comment by zhenduow** [comment]
> Delete the entire "models/pretrained_transformers" folder (in your datapath), or delete "models/pretrained_transformers/.built"

Thank you so much! Now it's working.
