### ISSUE TITLE
[bert_classifier] dictionary problem

### ISSUE THREAD

**Issue by wyshi** [facebookresearch/ParlAI#3209]
**Bug description**
running the command in the readme here https://github.com/facebookresearch/ParlAI/tree/master/parlai/agents/bert_classifier
gave the wrong dictionary, see logs below

**Reproduction steps**
```
parlai train_model -m bert_classifier -t snli --classes 'entailment' 'contradiction' 'neutral' -mf /tmp/BERT_snli -bs 20
```

**Logs**
```
18:22:55 INFO | loading dictionary from /tmp/BERT_snli.dict
18:22:55 INFO | num words = 4
```

**Comment by stephenroller** [comment]
The print is wrong, but the logic underneath is correct. Due to where it is, it's difficult to correct it (it prints before we load the BERT values).

Task should be filed to delete that print and out later ones after the models load.
