### ISSUE TITLE
Storing conversations with an Interactive Model - Retrieving act list

### ISSUE THREAD

**Issue by Bharathi-A-7** [facebookresearch/ParlAI#3214]
I need to be able to store the conversations I have with a pretrained/custom model in a file . I found out that this can be achieved by calling the save_conversations function of parlai.utils.conversations.Conversations class . 

The save_conversations function requires a parameter act_list which is a basically a list of episodes with act pairs . My question is , how do I get this act_list ? 

Supposing I'm running this command in the command line to interact with an Empathetic Dialogue model :

` parlai interactive -mf zoo:dodecadialogue/empathetic_dialogues_ft/model --inference beam --beam-size 5 --beam-min-length 10 --beam-block-ngram 3 --beam-context-block-ngram 3 `

How do I store the conversation in the act_list in order to pass it to the save_conversations function ? Can someone please help me with this ?

**Comment by stephenroller** [comment]
Interactive has a --save-world-logs arg (or something like this) which will store the logs in the provided filename.

If you want the retrieval results reranked, that will require a bit more hacking, but ultimately just put it into the output Message from the agent, and it will get logged.
