### ISSUE TITLE
[distributed_eval] the number of examples evaluated is different from that specified in the command line

### ISSUE THREAD

**Issue by wyshi** [facebookresearch/ParlAI#3217]
Command
```
python -u distributed_eval.py --verbose True -mf some_model -m bart -t some_task -dt valid --skip-generation True --dynamic-batching full -ne 10000 -bs 8  --distributed-world-size 8 &

```

I set `-ne 10_000`, it more likely means i want to validate on a max of 10_000 examples with all workers. But in the log I got `distributed-world-size * num_examples=~80000` examples validated, and each worker validated on 10_000 examples. So if i want to validate on a max of 10_000 examples with all workers, i had to manually do the calculation and set `-ne 10_000/num_workers`.

so would it make sense to add an argument like `--max-num-examples` and  do the calculation `10_000/num_workers` in the code?

**Comment by stephenroller** [comment]
Probably can't fix. We could do the max num examples divide by num_workers, but it would still be only approximate. Things like Dynamic Batching already throw a big wrench into this.
