### ISSUE TITLE
How to bond a qualification task with HITs

### ISSUE THREAD

**Issue by Stefan1220** [facebookresearch/ParlAI#3220]
Hi,

I am using ParlAI to implement a MTurk task, and would like to incorporate a custom qualification task into my HIT. On ParlAI, I know that maybe I can use  **_mturk_manager.create_hits(qualifications=...)_** to give some qualifications like locations before launching the task. But the qualification task in my setting is like a survey website which would contain several multi-choice questions. Do you guys have any idea about how to bond HIT with this kind of qualification tasks?

Thanks so much for your help!

**Comment by stephenroller** [comment]
@JackUrb  @EricMichaelSmith

**Comment by JackUrb** [comment]
For something like this I'd suggest making your qualification task a separate task launched through regular MTurk, and have it only be completable by workers once. We don't really support this kind of functionality in ParlAI-MTurk. If you were to create your form/survey in react, or use a multi-turn conversation to onboard your workers, you can do that using `bootstrap-chat` with [Mephisto](https://github.com/facebookresearch/Mephisto).

**Comment by Stefan1220** [comment]
Thanks for your response! I finally wrote two xml files for questions and answers for the qualification task, and changed the code of function _**find_or_create_qualification**_ in _**mturk_utils.py**_, added two additional parameters as input including 'questions' and 'answers' by reading those two xml files, and it works now.

Meanwhile, I have another question that I would like to limit the number of HITs an individual worker can submit for my task, is there any hyper argument on ParlAI that I can set to implement this? Thanks!

**Comment by JackUrb** [comment]
That would be the opt `max_hits_per_worker`.

**Comment by JackUrb** [comment]
Closing as the original issue was answered. Feel free to re-open if you have more follow-ups.

**Comment by Stefan1220** [comment]
Hi, 

A quick question about mturk: when I launch a nturk task through ParlAI, is there a way to limit the number of workers who can do our HIT task? Any suggestions for this?

Thanks!

**Comment by JackUrb** [comment]
Are you trying to limit the number of unique workers, or the number of workers actively working on a task at the same time? The former I'm not sure the best way to approach (other than perhaps launching a task that qualifies workers, and then launching another task relying on that qualification for only qualified workers to do). The latter you can do with `max_connections`.
