### ISSUE TITLE
Missing key(s) in state_dict while training bimodel_huge_reddit model

### ISSUE THREAD

**Issue by AkshayAgarwal13** [facebookresearch/ParlAI#3237]
I am trying to fine-tune a retrieval-based model using "bimodel_huge_reddit model" as a base but I am getting the following error:
RuntimeError: Error(s) in loading state_dict for TransformerMemNetModel:

I am using the following parameters to train the model.

TrainModel.main(
    
    task = 'empathetic_dialogues', 
    model='transformer/biencoder',
    model_file='transformer_pretrained_biencoder1/model',
    
    # initialize with a pretrained model
    init_model='D:\CS 224U\Project_Repo\Task-Oriented-Chatbot-With- 
              Empathy\data\models\pretrained_transformers\pretrained_transformers\bi_model_huge_reddit\model',
  
    n_heads=12, n_layers=12, n_positions=1024, text_truncate=360,
    label_truncate=72, ffn_size=3072, embedding_size=768,
    embeddings_scale =  False,
    dict_endtoken = '__start__',
    activation='gelu', variant='xlm',
    dict_lower=True, dict_tokenizer='bpe',
    n_segments =2,  
    learn_positional_embeddings='True',
    candidates = 'batch',
    eval_candidates = 'batch',
    attention_dropout =  0.1,  
    lr=1e-4, optimizer='adamax',
    warmup_updates=100,
    save_every_n_secs = -1,   
    validation_metric='hits@1',    
    max_train_time=300, validation_every_n_epochs=0.01,   
    batchsize=512,fp16=True, fp16_impl='mem_efficient',
)_
**Expected behavior**
Give a clear and concise description of what you expected to happen.

I am getting the following stack trace for error:

RuntimeError: Error(s) in loading state_dict for TransformerMemNetModel:
        Missing key(s) in state_dict: "cand_encoder.transformer.embeddings.weight", "cand_encoder.transformer.position_embeddings.weight", "cand_encoder.transformer.norm_embeddings.weight", "cand_encoder.transformer.norm_embeddings.bias", "cand_encoder.transformer.segment_embeddings.weight", "cand_encoder.transformer.layers.0.attention.q_lin.weight", "cand_encoder.transformer.layers.0.attention.q_lin.bias", "cand_encoder.transformer.layers.0.attention.k_lin.weight", "cand_encoder.transformer.layers.0.attention.k_lin.bias", "cand_encoder.transformer.layers.0.attention.v_lin.weight", "cand_encoder.transformer.layers.0.attention.v_lin.bias", "cand_encoder.transformer.layers.0.attention.out_lin.weight", "cand_encoder.transformer.layers.0.attention.out_lin.bias", "cand_encoder.transformer.layers.0.norm1.weight", "cand_encoder.transformer.layers.0.norm1.bias", "cand_encoder.transformer.layers.0.ffn.lin1.weight", "cand_encoder.transformer.layers.0.ffn.lin1.bias", "cand_encoder.transformer.layers.0.ffn.lin2.weight", "cand_encoder.transformer.layers.0.ffn.lin2.bias", "cand_encoder.transformer.layers.0.norm2.weight", "cand_encoder.transformer.layers.0.norm2.bias", "cand_encoder.transformer.layers.1.attention.q_lin.weight", "cand_encoder.transformer.layers.1.attention.q_lin.bias", "cand_encoder.transformer.layers.1.attention.k_lin.weight", "cand_encoder.transformer.layers.1.attention.k_lin.bias", "cand_encoder.transformer.layers.1.attention.v_lin.weight", "cand_encoder.transformer.layers.1.attention.v_lin.bias", "cand_encoder.transformer.layers.1.attention.out_lin.weight", "cand_encoder.transformer.layers.1.attention.out_lin.bias", "cand_encoder.transformer.layers.1.norm1.weight", "cand_encoder.transformer.layers.1.norm1.bias", "cand_encoder.transformer.layers.1.ffn.lin1.weight", "cand_encoder.transformer.layers.1.ffn.lin1.bias", "cand_encoder.transformer.layers.1.ffn.lin2.weight", "cand_encoder.transformer.layers.1.ffn.lin2.bias", "cand_encoder.transformer.layers.1.norm2.weight", "cand_encoder.transformer.layers.1.norm2.bias", "cand_encoder.transformer.layers.2.attention.q_lin.weight", "cand_encoder.transformer.layers.2.attention.q_lin.bias", "cand_encoder.transformer.layers.2.attention.k_lin.weight", "cand_encoder.transformer.layers.2.attention.k_lin.bias", "cand_encoder.transformer.layers.2.attention.v_lin.weight", "cand_encoder.transformer.layers.2.attention.v_lin.bias", "cand_encoder.transformer.layers.2.attention.out_lin.weight", "cand_encoder.transformer.layers.2.attention.out_lin.bias", "cand_encoder.transformer.layers.2.norm1.weight", "cand_encoder.transformer.layers.2.norm1.bias", "cand_encoder.transformer.layers.2.ffn.lin1.weight", "cand_encoder.transformer.layers.2.ffn.lin1.bias", "cand_encoder.transformer.layers.2.ffn.lin2.weight", "cand_encoder.transformer.layers.2.ffn.lin2.bias", "cand_encoder.transformer.layers.2.norm2.weight", "cand_encoder.transformer.layers.2.norm2.bias", "cand_encoder.transformer.layers.3.attention.q_lin.weight", "cand_encoder.transformer.layers.3.attention.q_lin.bias", "cand_encoder.transformer.layers.3.attention.k_lin.weight", "cand_encoder.transformer.layers.3.attention.k_lin.bias", "cand_encoder.transformer.layers.3.attention.v_lin.weight", "cand_encoder.transformer.layers.3.attention.v_lin.bias", "cand_encoder.transformer.layers.3.attention.out_lin.weight", "cand_encoder.transformer.layers.3.attention.out_lin.bias", "cand_encoder.transformer.layers.3.norm1.weight", "cand_encoder.transformer.layers.3.norm1.bias", "cand_encoder.transformer.layers.3.ffn.lin1.weight", "cand_encoder.transformer.layers.3.ffn.lin1.bias", "cand_encoder.transformer.layers.3.ffn.lin2.weight", "cand_encoder.transformer.layers.3.ffn.lin2.bias", "cand_encoder.transformer.layers.3.norm2.weight", "cand_encoder.transformer.layers.3.norm2.bias", "cand_encoder.transformer.layers.4.attention.q_lin.weight", "cand_encoder.transformer.layers.4.attention.q_lin.bias", "cand_encoder.transformer.layers.4.attention.k_lin.weight", "cand_encoder.transformer.layers.4.attention.k_lin.bias", "cand_encoder.transformer.layers.4.attention.v_lin.weight", "cand_encoder.transformer.layers.4.attention.v_lin.bias", "cand_encoder.transformer.layers.4.attention.out_lin.weight", "cand_encoder.transformer.layers.4.attention.out_lin.bias", "cand_encoder.transformer.layers.4.norm1.weight", "cand_encoder.transformer.layers.4.norm1.bias", "cand_encoder.transformer.layers.4.ffn.lin1.weight", "cand_encoder.transformer.layers.4.ffn.lin1.bias", "cand_encoder.transformer.layers.4.ffn.lin2.weight", "cand_encoder.transformer.layers.4.ffn.lin2.bias", "cand_encoder.transformer.layers.4.norm2.weight", "cand_encoder.transformer.layers.4.norm2.bias", "cand_encoder.transformer.layers.5.attention.q_lin.weight", "cand_encoder.transformer.layers.5.attention.q_lin.bias", "cand_encoder.transformer.layers.5.attention.k_lin.weight", "cand_encoder.transformer.layers.5.attention.k_lin.bias", "cand_encoder.transformer.layers.5.attention.v_lin.weight", "cand_encoder.transformer.layers.5.attention.v_lin.bias", "cand_encoder.transformer.layers.5.attention.out_lin.weight", "cand_encoder.transformer.layers.5.attention.out_lin.bias", "cand_encoder.transformer.layers.5.norm1.weight", "cand_encoder.transformer.layers.5.norm1.bias", "cand_encoder.transformer.layers.5.ffn.lin1.weight", "cand_encoder.transformer.layers.5.ffn.lin1.bias", "cand_encoder.transformer.layers.5.ffn.lin2.weight", "cand_encoder.transformer.layers.5.ffn.lin2.bias", "cand_encoder.transformer.layers.5.norm2.weight", "cand_encoder.transformer.layers.5.norm2.bias", "cand_encoder.transformer.layers.6.attention.q_lin.weight", "cand_encoder.transformer.layers.6.attention.q_lin.bias", "cand_encoder.transformer.layers.6.attention.k_lin.weight", "cand_encoder.transformer.layers.6.attention.k_lin.bias", "cand_encoder.transformer.layers.6.attention.v_lin.weight", "cand_encoder.transformer.layers.6.attention.v_lin.bias", "cand_encoder.transformer.layers.6.attention.out_lin.weight", "cand_encoder.transformer.layers.6.attention.out_lin.bias", "cand_encoder.transformer.layers.6.norm1.weight", "cand_encoder.transformer.layers.6.norm1.bias", "cand_encoder.transformer.layers.6.ffn.lin1.weight", "cand_encoder.transformer.layers.6.ffn.lin1.bias", "cand_encoder.transformer.layers.6.ffn.lin2.weight", "cand_encoder.transformer.layers.6.ffn.lin2.bias", "cand_encoder.transformer.layers.6.norm2.weight", "cand_encoder.transformer.layers.6.norm2.bias", "cand_encoder.transformer.layers.7.attention.q_lin.weight", "cand_encoder.transformer.layers.7.attention.q_lin.bias", "cand_encoder.transformer.layers.7.attention.k_lin.weight", "cand_encoder.transformer.layers.7.attention.k_lin.bias", "cand_encoder.transformer.layers.7.attention.v_lin.weight", "cand_encoder.transformer.layers.7.attention.v_lin.bias", "cand_encoder.transformer.layers.7.attention.out_lin.weight", "cand_encoder.transformer.layers.7.attention.out_lin.bias", "cand_encoder.transformer.layers.7.norm1.weight", "cand_encoder.transformer.layers.7.norm1.bias", "cand_encoder.transformer.layers.7.ffn.lin1.weight", "cand_encoder.transformer.layers.7.ffn.lin1.bias", "cand_encoder.transformer.layers.7.ffn.lin2.weight", "cand_encoder.transformer.layers.7.ffn.lin2.bias", "cand_encoder.transformer.layers.7.norm2.weight", "cand_encoder.transformer.layers.7.norm2.bias", "cand_encoder.transformer.layers.8.attention.q_lin.weight", "cand_encoder.transformer.layers.8.attention.q_lin.bias", "cand_encoder.transformer.layers.8.attention.k_lin.weight", "cand_encoder.transformer.layers.8.attention.k_lin.bias", "cand_encoder.transformer.layers.8.attention.v_lin.weight", "cand_encoder.transformer.layers.8.attention.v_lin.bias", "cand_encoder.transformer.layers.8.attention.out_lin.weight", "cand_encoder.transformer.layers.8.attention.out_lin.bias", "cand_encoder.transformer.layers.8.norm1.weight", "cand_encoder.transformer.layers.8.norm1.bias", "cand_encoder.transformer.layers.8.ffn.lin1.weight", "cand_encoder.transformer.layers.8.ffn.lin1.bias", "cand_encoder.transformer.layers.8.ffn.lin2.weight", "cand_encoder.transformer.layers.8.ffn.lin2.bias", "cand_encoder.transformer.layers.8.norm2.weight", "cand_encoder.transformer.layers.8.norm2.bias", "cand_encoder.transformer.layers.9.attention.q_lin.weight", "cand_encoder.transformer.layers.9.attention.q_lin.bias", "cand_encoder.transformer.layers.9.attention.k_lin.weight", "cand_encoder.transformer.layers.9.attention.k_lin.bias", "cand_encoder.transformer.layers.9.attention.v_lin.weight", "cand_encoder.transformer.layers.9.attention.v_lin.bias", "cand_encoder.transformer.layers.9.attention.out_lin.weight", "cand_encoder.transformer.layers.9.attention.out_lin.bias", "cand_encoder.transformer.layers.9.norm1.weight", "cand_encoder.transformer.layers.9.norm1.bias", "cand_encoder.transformer.layers.9.ffn.lin1.weight", "cand_encoder.transformer.layers.9.ffn.lin1.bias", "cand_encoder.transformer.layers.9.ffn.lin2.weight", "cand_encoder.transformer.layers.9.ffn.lin2.bias", "cand_encoder.transformer.layers.9.norm2.weight", "cand_encoder.transformer.layers.9.norm2.bias", "cand_encoder.transformer.layers.10.attention.q_lin.weight", "cand_encoder.transformer.layers.10.attention.q_lin.bias", "cand_encoder.transformer.layers.10.attention.k_lin.weight", "cand_encoder.transformer.layers.10.attention.k_lin.bias", "cand_encoder.transformer.layers.10.attention.v_lin.weight", "cand_encoder.transformer.layers.10.attention.v_lin.bias", "cand_encoder.transformer.layers.10.attention.out_lin.weight", "cand_encoder.transformer.layers.10.attention.out_lin.bias", "cand_encoder.transformer.layers.10.norm1.weight", "cand_encoder.transformer.layers.10.norm1.bias", "cand_encoder.transformer.layers.10.ffn.lin1.weight", "cand_encoder.transformer.layers.10.ffn.lin1.bias", "cand_encoder.transformer.layers.10.ffn.lin2.weight", "cand_encoder.transformer.layers.10.ffn.lin2.bias", "cand_encoder.transformer.layers.10.norm2.weight", "cand_encoder.transformer.layers.10.norm2.bias", "cand_encoder.transformer.layers.11.attention.q_lin.weight", "cand_encoder.transformer.layers.11.attention.q_lin.bias", "cand_encoder.transformer.layers.11.attention.k_lin.weight", "cand_encoder.transformer.layers.11.attention.k_lin.bias", "cand_encoder.transformer.layers.11.attention.v_lin.weight", "cand_encoder.transformer.layers.11.attention.v_lin.bias", "cand_encoder.transformer.layers.11.attention.out_lin.weight", "cand_encoder.transformer.layers.11.attention.out_lin.bias", "cand_encoder.transformer.layers.11.norm1.weight", "cand_encoder.transformer.layers.11.norm1.bias", "cand_encoder.transformer.layers.11.ffn.lin1.weight", "cand_encoder.transformer.layers.11.ffn.lin1.bias", "cand_encoder.transformer.layers.11.ffn.lin2.weight", "cand_encoder.transformer.layers.11.ffn.lin2.bias", "cand_encoder.transformer.layers.11.norm2.weight", "cand_encoder.transformer.layers.11.norm2.bias", "cand_encoder.mlp.0.weight", "cand_encoder.mlp.0.bias", "cand_encoder.mlp.2.weight", "cand_encoder.mlp.2.bias".

It will great if you can help me with the same. I have tried changing parameter values for ffn_size and n_positions but I am still getting the same error. Thanks a lot in advance. Please let me know if you need any additional information

**Comment by stephenroller** [comment]
Based on the missing items, I'm guessing you have share_encoders=False but the original model was trained with True.

**Comment by AkshayAgarwal13** [comment]
Thanks a lot. It's working now
