### ISSUE TITLE
Question about decoding control in Lifelong Dialogue Learning (LIGHT)

### ISSUE THREAD

**Issue by noowad93** [facebookresearch/ParlAI#3241]
Hello!
I have a question about Question about decoding control strategy in the paper "Deploying Lifelong Open-Domain Dialogue Learning".
I think that decoding control in (See at al. 2019) can only be used in generation-based models, but it is described as if it were used in a retrieval-based model (poly-encoder).
How did you use decoding control strategy in Poly-encoder?
<img width="445" alt="스크린샷 2020-10-30 오후 2 43 43" src="https://user-images.githubusercontent.com/49383323/97665243-50677d00-1abe-11eb-8792-5e2760dd1825.png">

**Comment by stephenroller** [comment]
@JackUrb @klshuster

**Comment by JackUrb** [comment]
Hi @noowad93 - The decoding control in the cited work (See et al. 2019) is built for generation based models, but here we used a simple reranking heuristic for a similar purpose. In our case the model's output rankings were combined with a specificity measurement to down-weigh candidates that were too specific.
