### ISSUE TITLE
Creating User profile 

### ISSUE THREAD

**Issue by Bharathi-A-7** [facebookresearch/ParlAI#3243]
I am looking to create a dynamic user profile (User - any user chatting with the model from a single machine) that keeps updating itself with data from conversations with the model .

My simple idea was to create a JSON or text file that will store key details in each conversation and keeps updating itself as I automate the process of parsing recent conversations to store important facts .

But , Whenever I chat with a model(Trained/Pretrained) , the conversations are only stored on a new file . I mean , for each new conversation , a new file is being created .

My requirement is that for all conversations taking place in my system , I want the conversation data to be appended to a single file meant for this purpose , the details of which will be parsed and stored in the user profile.

How do I move forward with that ? Or could someone please suggest an alternate idea to create a dynamic user profile in ParlAI?

**Comment by stephenroller** [comment]
I would generally recommend new files, and aggregate them later, but if you insist on appending, you could change this mode from `'w'` to `'a'`

https://github.com/facebookresearch/ParlAI/blob/f9e67b7286fcd7b9adfb94b62c3b5cb8fe0c9038/parlai/utils/conversations.py#L301

**Comment by Bharathi-A-7** [comment]
Thank you very much . Does this also work with the '--outfile' CLI argument to save conversations ?

**Comment by stephenroller** [comment]
Yes, I believe so.

**Comment by Bharathi-A-7** [comment]
Changing to append mode works with the default 'conversations' format and metadata but if I choose my save-format to be 'parlai' , appending does not work and the file is overwritten . Could you please tell me what to do about it ?

**Comment by stephenroller** [comment]
Find the other "w" mode and change it to an "a"
