### ISSUE TITLE
Could eval_model compute the distinct metrics?

### ISSUE THREAD

**Issue by iseesaw** [facebookresearch/ParlAI#3255]
Hi, I would like to compute **the distinct metrics** using the `eval_model` command. 

But I saw the CLI Arguments (as follows), it likely could not support to compute **the distinct metrics**. Is it?

```
-mcs, --metrics | List of metrics to show/compute, e.g. all, default, or give a list split by, like ppl,f1, accuracy, hits@1, rouge, bleu. the rouge metrics will be computed as rouge-1, rouge-2, and rouge-l
```

**Comment by stephenroller** [comment]
We don't have any implementation of that right now. I would welcome a PR implementing it.

Implementation would need to go here:
https://github.com/facebookresearch/ParlAI/blob/fb44a721cd5288fa097622e3d0b95e3379f29e74/parlai/core/metrics.py#L719-L735

**Comment by stephenroller** [comment]
What's the definition of distinct? Unique n-grams over generations from the entire corpus, or unique n-grams per utterance?

**Comment by iseesaw** [comment]
The distinct metric was first introduced in [A Diversity-Promoting Objective Function for Neural Conversation Models](https://arxiv.org/pdf/1510.03055.pdf), the original paper said as follows

> We report the degree of diversity by calculating the number of distinct unigrams and bigrams in generated responses. The value is scaled by the total number of generated tokens to avoid favoring long sentences (shown as distinct-1 and distinct-2 in Tables 2 and 3).

But they didn't release their implementation, we usually compute the n-grams over generations from the entire corpus (it will be very higher than the original paper if computed per utterance)

[Here](https://github.com/PaddlePaddle/models/blob/release/1.6/PaddleNLP/Research/Dialogue-PLATO/plato/metrics/metrics.py) is an implementation. I will add it to ParlAI later :(

**Comment by stephenroller** [comment]
Hm, the method I linked you to assumes metrics are computed per-utterance, independently across the corpus. Computing IntraDistinct should be relatively straightforward. InterDistinct is a bit trickier, as we need to keep the ngrams across the corpus. Something like this should work, at least when not in distributed mode.


```python
class InterDistinctMetric(Metric):
    def __init__(self, counts):
        self._counts = counts

    def __add__(self, other):
        return DistinctMetric(self._counts + other._counts)

    def value(self):
        return (len(self._counts) + 1e-12) / (sum(self._counts.values()) + 1e-5)

    @classmethod
    def _ngram(cls, seq, n):
        for i in range(len(seq) - n + 1):
            yield seq[i : i + n]

    @classmethod
    def compute(cls, text, ngram=1):
        tokens = normalize_answer(text).split()
        return InterDistinctMetric(Counter(cls._ngram(tokens, ngram)))
```

**Comment by iseesaw** [comment]
OK, thanks! I'll test this.

**Comment by stephenroller** [comment]
Seems like OP lost interest. I'll commandeer the PR, I would like to see that metric added.
