### ISSUE TITLE
Command line parser

### ISSUE THREAD

**Issue by ahsmourad** [facebookresearch/ParlAI#3268]
**Bug description**
I was trying to follow the Quick-start tutorial when it broke down at the second step of training a model. The `-m` parameter is interpreted by the parser as `-mtw`. The only way to get around it was to use `--model`.

**Reproduction steps**
Enter steps to reproduce the behavior.

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Logs**
Please paste the command line output:

```
Output goes here
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by stephenroller** [comment]
Thanks. This issue exists in Python 3.8+ but not 3.7. Just a potential workaround.

**Comment by mathematicalmichael** [comment]
why does this issue exist?

**Comment by stephenroller** [comment]
This was fixed recently and python 3.8 is fine now.
