### ISSUE TITLE
Running ParlAI Project on Server

### ISSUE THREAD

**Issue by Ufukdogann** [facebookresearch/ParlAI#3270]
Dear @stephenroller, @klshuster 

I am using ParlAI project on my thesis project and I need to run the chatbot on a server. 

I read the documentation, https://parl.ai/docs/tutorial_chat_service.html. Then, on the websocket part I was redirected to the https://github.com/facebookresearch/ParlAI/tree/master/parlai/chat_service/services/browser_chat link.

What I understand is, "browser_chat" is an extension of "websocket" for servers, is that correct? If I want to run the chatbot on a server, I need to use "browser_chat"?

However, there is only one example is for "browser_chat" and whenever I run it, it prints "Please connect to the link: "http://localhost:8080" on my local computer. 

![WhatsApp Image 2020-11-17 at 03 19 31](https://user-images.githubusercontent.com/8861458/99323777-f28bb100-2883-11eb-97e5-62514a0d878c.jpeg)

Can you tell me where and how should I add my server IP?

Thanks a lot in advance!

Best regards,

**Comment by Ufukdogann** [comment]
![WhatsApp Image 2020-11-17 at 03 19 31](https://user-images.githubusercontent.com/8861458/99323777-f28bb100-2883-11eb-97e5-62514a0d878c.jpeg)

I am running the code as in the tutorial, I am running on 10002 port number, but the connection link is still "localhost:8080", I do not know how to connect the chatbot from my server.

And even though I try the reach the website using <serverip>:10002 I am seeing this page.

<img width="1680" alt="Screenshot 2020-11-17 at 03 25 58" src="https://user-images.githubusercontent.com/8861458/99324141-abea8680-2884-11eb-8f0f-2aabc5589f99.png">

![WhatsApp Image 2020-11-17 at 03 32 51](https://user-images.githubusercontent.com/8861458/99324642-c7a25c80-2885-11eb-8b26-9b0f84e63163.jpeg)

**Comment by Ufukdogann** [comment]
Then, I have tried to run the commands on 8080 port. At the beginning when I do `lsof -i :8080` to check is this port used, it showed empty.

So, I run the first command that is `python parlai/chat_service/services/browser_chat/run.py --config-path parlai/chat_service/tasks/chatbot/config.yml --port 8080`

Everything seems correct for the first part.

<img width="1378" alt="Screenshot 2020-11-17 at 04 10 23" src="https://user-images.githubusercontent.com/8861458/99327362-d17a8e80-288a-11eb-95ff-614e6fe9a4dd.png">

Then I tried to run the second command that is `python parlai/chat_service/services/browser_chat/client.py --port 8080`

The result was;

<img width="862" alt="Screenshot 2020-11-17 at 04 11 34" src="https://user-images.githubusercontent.com/8861458/99327419-fc64e280-288a-11eb-94fa-c171e5d7e79f.png">

Should not I use the same port for these commands? 

Best regards,

**Comment by JackUrb** [comment]
Hi @Ufukdogann - IIRC the browser webapp will be running on the port labelled `serving_port`, in this case `8080`, and the model server will be running at your other specified port, `port`. So in this case you'll want to visit `<serverip>:8080`. The system should be configured to then forward requests to the model to the provided `port`.

**Comment by Ufukdogann** [comment]
Dear @JackUrb,

Today I have made some research about it and I found that post. 
https://github.com/facebookresearch/ParlAI/issues/2397

Then I have tried to run in the other server like 8081, in order to do that, in the client.py file I have changed the port to 8081 as well.

This is what it shows after running both commands with using 8081.

<img width="567" alt="Screenshot 2020-11-17 at 22 14 53" src="https://user-images.githubusercontent.com/8861458/99436264-5369c680-2922-11eb-8039-e81495f88c25.png">

Then, I checked the status of the opened services. The result was like this, 

![WhatsApp Image 2020-11-17 at 22 11 32](https://user-images.githubusercontent.com/8861458/99436880-b52a3080-2922-11eb-9b48-ca2bd4463d80.jpeg)

On 8443 port I am running the landing page of my thesis project.

Then I did what you said, I went to the http://195.176.181.153:8080/ to see the chatbot web browser however I did not see anything in there.

<img width="1679" alt="Screenshot 2020-11-17 at 22 19 10" src="https://user-images.githubusercontent.com/8861458/99437028-edca0a00-2922-11eb-8d97-43c25cee7d11.png">

So, I still do not know which URL should i go to see the browser chatbot.

I hope with screenshots I explain my problem better right now.

Thanks in advance!

Best regards,

**Comment by JackUrb** [comment]
You may need to also specify the `--host` argument. This defaults to `localhost`, but `0.0.0.0` should allow all connections, and putting your actual IP may work as well.

Beyond this I don't really have enough experience with chat services to suggest more, and will defer back to @klshuster if this doesn't work.

**Comment by Ufukdogann** [comment]
@JackUrb thanks a lot.

In the second command when I add the --host parameter it started working under the 8080 port.

Best regards, hats off!
