### ISSUE TITLE
Limiting the number of workers + qualification task

### ISSUE THREAD

**Issue by ashleylew** [facebookresearch/ParlAI#3273]
Our task gives a bonus to workers after they complete the first HIT (to compensate them for the time they spend reading our tutorial and doing the qualification task). The problem is that we want to limit the number of workers who can do the task, as we're trying to make sure that each worker does several HITs if they want to and that we don't end up paying several bonuses to workers who can only complete 1-2 HITs (our number of available HITs is fairly low). I know that it's possible to limit the number of HITs, but I can't find any way to limit the number of individuals doing those HITs. Any suggestions for this? 

Second, we're running into a small problem with our qualification task, which is a short quiz. The first three questions are demographic questions that do not count toward their score, and the rest are content questions that DO count. We are currently having ParlAI/Turk auto-grade the responses so the qualification can be granted immediately/automatically, but we want to be able to see the answers to the questions so that we have the demographic information. Currently we are only able to return an overall score for the qualification test, but not the answers themselves. Is there any way to do this without having to grade them manually?

Thanks so much!

**Comment by stephenroller** [comment]
@jackurb @EricMichaelSmith do y'all know?

**Comment by EricMichaelSmith** [comment]
@JackUrb I suppose the first of these could be solved with a `SharedTaskState` attribute, right? Namely, there could be an attribute consisting of an allowlist of workers who have completed their first HIT (and thus who are qualified for further HITs).

As far as keeping track of per-question stats about demographic info, I imagine that a `SharedTaskState` attribute can be used for that too - for instance, in `parlai.crowdsourcing.tasks.model_chat.worlds`, `ModelChatOnboardWorld.onboard_statistics` is an attribute of `SharedModelChatTaskState` that persists onboarding stats across workers

**Comment by JackUrb** [comment]
Is this built on Mephisto or ParlAI-MTurk? The latter doesn't really have great support for either of these.

On Mephisto, for the first it's generally sufficient to limit the number of hits released at a time. Another valid setup though is to launch two tasks, the first which can only be completed once and grants a qualification for completion, and the second that requires the qualification. You can use this setup to gate the number of workers on the second by the number of tasks you release in the first.

For the second in Mephisto you would be able to view this information in the `OnboardingAgent`'s stored data, accessible with a `get_data()` call. The onboarding data for a specific worker on a specific task can thus be found with `db.find_onboarding_agents(worker_id=?, task_id=?)[0].get_data()`.
