### ISSUE TITLE
Web Browser Multiple User At The Same Time

### ISSUE THREAD

**Issue by Ufukdogann** [facebookresearch/ParlAI#3276]
Hello, 

I am a newbie and trying to use ParlAI for my thesis project. I have done many updates on the code for my needs and I am stuck right now. I hope you can help me with that. I hope you can provide me some ideas or code examples.

I am using the Blender M90 model. I was testing everything on my local computer and this week with the university webserver I had the opportunity to take my project live.

A small test group has tried it and we found out some problems that I have not seen before.

```
python parlai/chat_service/services/browser_chat/run.py --config-path parlai/chat_service/tasks/chatbot/config.yml --port 8000

python parlai/chat_service/services/browser_chat/client.py --port 8000
```

I am basically running these lines to activate the model and the front-end. I am running these codes on the server so that whenever a user closed their conversation with the model, the websocket session automatically closes and the other user can not use it unless I re-activate the chatbot via running the commands on the terminal. So, the first question is, what can I do here to prevent it? Is there any feature like just killing the agent but not the session and then re-activate or re-create the agent?

After a user activates the chatbot, a random user can start to communicate with the chatbot at the same time, immediately. However, before activating the chatbot, I am gathering some information about the user such as the mail address via `MessengerOverworld`. Like below,

<img width="994" alt="Screenshot 2020-11-21 at 01 58 28" src="https://user-images.githubusercontent.com/8861458/99857778-10675780-2b9d-11eb-86e5-a4586dba2392.png">

<img width="460" alt="Screenshot 2020-11-21 at 01 55 15" src="https://user-images.githubusercontent.com/8861458/99857596-9afb8700-2b9c-11eb-92a7-98876161caf4.png">

 So, how can I prevent overlapping? I want all users to start at the same time with the same path. How may I do it?

Thanks in advance!
Best regards,

**Comment by klshuster** [comment]
hi there,

given the way browser chat is currently implemented, connecting to the same port I believe connects to the same world session ; it is mostly useful for one-on-one chatting. You would most likely want to handle multi-user logic within your world (perhaps tracking via agent ids?) if you wanted to continue using that solution.

I would recommend looking into using the `websockets_chat` directly if you are spinning up an actual server (see discussion on #3174), or alternatively you can try out the Facebook Messenger integration (see https://parl.ai/docs/tutorial_chat_service.html for a tutorial on how to set that up). With those services, each user who connects would have their own session with the bot.

Hope that helps!

**Comment by Ufukdogann** [comment]
Dear @klshuster,

I am already running the code right now. You can reach out from http://195.176.181.153:8080/. You can try it as well

I have used `browser_chat` instead of `websoockets_chat`.

So my new question is, is there any possibility to kill an agent and re-create it or restart it under some conditions such as; if a user clicks this button. So, with that maybe I can just restart the agent when a user clicks to finish the conversation button, and then the new user will be able to start from the beginning.

One more thing, on webserver chatbot, seems so slow. Do you have any idea?

Just wanted to be sure, you mentioned the Facebook Messenger implementation just because you thought I did not put the project live right? Or is there anything similar to my question? 

Best regards,

Thanks in advance!

**Comment by Ufukdogann** [comment]
@klshuster Hello again,

I read your message one more time and since you said that using `websocket` will solve my problem, I want to give it a shot.

I could not find any websocket command examples, so I tried to combine some codes.

Firstly, I have tried this and it worked.

`python parlai/chat_service/services/websocket/run.py --config-path parlai/chat_service/tasks/chatbot/config.yml`

<img width="1165" alt="Screenshot 2020-11-21 at 04 53 58" src="https://user-images.githubusercontent.com/8861458/99864639-92637a80-2bb5-11eb-9c9d-c8748551bf1b.png">

However, `websockets` does not have `client.py` like `browser_chat`. I have tried with all files under websockets but I could not go further, can you help me with that?

Should I run, `python parlai/chat_service/services/browser_chat/client.py` again? I do not think so, it is for `browser_chat` but I want to be sure about it.

Any kind of help would be so useful.

PS: I can't use Facebook Messenger, unfortunately. 

Best regards,

Thanks in advance!

**Comment by klshuster** [comment]
Hi there, sorry for the delayed response. To use the websockets chat service setup, you would need to serve your own websockets UI. @JackUrb might be able to weigh in with how you might set this up. Running `browser_chat/client.py` would most likely give you the same problem as before.

**Comment by JackUrb** [comment]
I don't have particularly strong guidance on how to use the websockets setup from scratch (as I'd only considered it for a project), but the basic setup is that you create a UI that, upon load or whatever condition you'd like, opens a websocket connection with the `websockets_chat` server. Doing this will connect the player to the service, but you'll be able to control closing out individual connections and chats without shutting down the whole thing.

**Comment by Ufukdogann** [comment]
Hi guys, @JackUrb @klshuster 

I want to ask, do you have any web API for the project? 

What I mean is, instead of having struggles with these, may I use blender90m chatbot directly and implement it on my web page?

If you have a web API, I can do post and get requests to send the sentence of the user and get the reply of the chatbot, easily.

Best regards,

**Comment by klshuster** [comment]
we currently do not host the model/provide a web API to it, sorry

**Comment by raj166** [comment]
I am facing the same issue of using the web Socket to connect to the ParlAi model, I am able to connect it using the terminal but I don't know how to connect it using the web browser. I am using the AWS instance to train and deploy the model. 

I want to know to integrate this mode on the webpage.

Best regards,
