### ISSUE TITLE
Training a bot with a specific personality

### ISSUE THREAD

**Issue by albusdemens** [facebookresearch/ParlAI#3277]
Use this to open other questions or issues, and provide context here.
Hello, newbie here. I'm looking for a way to train a chatbot so that it has a specific personality (defined by me during the fine-tuning). Could you point me to any tutorial, documentation or training material? Thanks!

**Comment by stephenroller** [comment]
Please read our Task tutorial and check out the fine-tune commands for BlenderBot.

**Comment by albusdemens** [comment]
Thanks for the hint! Do you have any specific page to point to?

**Comment by albusdemens** [comment]
Thanks for the hint! I'll head to https://parl.ai/docs/tutorial_task.html#getting-a-new-dataset-into-parlai-the-simplest-way.
