### ISSUE TITLE
using agents for asynchronous chatting

### ISSUE THREAD

**Issue by nikhil-iyer-97** [facebookresearch/ParlAI#3278]
Hi, I am trying out something where I create multiple agents and use the parley function to send the query and the agents process it to output the reply. Now, if i want to have multiple people using this service at the same time, I observe that the inputs are processed synchronously by the agents. I looked into agent cloning for multiple personalities of the agents but cant find anything in the docs for concurrent inference by the models and the agents. Please let me know how to proceed further. Thanks!

**Comment by stephenroller** [comment]
Depends on what you mean by concurrent, I guess. Python has terrible concurrency.

However, many agents do have `batch_act`, if you can queue up multiple queries have have them all executed at once.

See this part of the docs: https://parl.ai/docs/tutorial_worlds.html

**Comment by nikhil-iyer-97** [comment]
Thanks for the reply, I wanted something along the lines of using the agents ( specifically blenderbot) to answer 1000's of user queries while maintaining user context and remembering their previous dialog turns. Since multiple users may use the service at the same time, I felt the need to raise this issue to understand how to try and resolve this. 

Agent cloning seems like the best solution but each time the user hits the endpoint with their query, a clone is created that answers the query and the clone is deleted to save memory. I tried saving the last 3 user queries and passing them to the clone's observe() method to make it respond as if it already knows the user's previous history. Seems like there could be a better solution for this problem. Let me know if there is any. Thanks!!

**Comment by stephenroller** [comment]
You should definitely clone, one clone per user. Clones are cheap, and only really store the current dialogue history -- There's no need to separately store it.

You do want to clean them up some, but a timeout is a reasonable way for that.

**Comment by nikhil-iyer-97** [comment]
Thanks , closing this issue
