### ISSUE TITLE
 Train a model with 3 billion parameters

### ISSUE THREAD

**Issue by zaharPonimash** [facebookresearch/ParlAI#3279]
At the moment I am training a blender model with 90M parameters using the following command:
`python '/content/drive/My Drive/ParlAI/parlai/scripts/train_model.py' -t fromfile:parlaiformat --fromfile_datapath /content/blender -m transformer/generator --multitask-weights 1,3,3,3 --init-model zoo:tutorial_transformer_generator/model --dict-file zoo:tutorial_transformer_generator/model.dict --embedding-size 512 --n-layers 8 --ffn-size 2048 --dropout 0.1 --n-heads 16 --learn-positional-embeddings True --n-positions 512 --variant xlm --activation gelu --skip-generation True --fp16 True --text-truncate 512 --label-truncate 128 --dict-tokenizer bpe --dict-lower True -lr 1e-06 --optimizer adamax --lr-scheduler reduceonplateau --gradient-clip 0.1 -veps 0.25 --betas 0.9,0.999 --update-freq 1 --attention-dropout 0.0 --relu-dropout 0.0 --skip-generation True -vp 15 -stim 60 -vme 20000 -vmt ppl -vmm min --save-after-valid True --model-file /tmp/test_train_90M -bs 4`. 

Can I train a model with 3 billion parameters with the same command, replace the end of the command, where the architecture is indicated with this one:  
`parlai train_model -t blended_skill_talk,wizard_of_wikipedia,convai2:normalized,empathetic_dialogues --multitask-weights 1,3,3,3 -veps 0.25 --attention-dropout 0.0 --batchsize 128 --model transformer/generator --embedding-size 2560 --ffn-size 10240 --variant prelayernorm --n-heads 32 --n-positions 128 --n-encoder-layers 2 --n-decoder-layers 24 --history-add-global-end-token end --delimiter '  ' --dict-tokenizer bytelevelbpe  --dropout 0.1 --fp16 True --init-model zoo:blender/reddit_3B/model --dict-file zoo:blender/reddit_3B/model.dict --label-truncate 128 --log_every_n_secs 10 -lr 7e-06 --lr-scheduler reduceonplateau --lr-scheduler-patience 3 --optimizer adam --relu-dropout 0.0 --activation gelu --model-parallel true --save-after-valid True --text-truncate 128 --truncate 128 --warmup_updates 100 --fp16-impl mem_efficient --update-freq 2 --gradient-clip 0.1 --skip-generation True -vp 10 -vmt ppl -vmm min --model-file /tmp/test_train_27B`

**Comment by stephenroller** [comment]
Yeah, you've got model parallel on, so that should work. You'll need several GPUs to do it though, so you might need to use distributed/multiprocessing training.

**Comment by stephenroller** [comment]
If you only have 2-8 gpus on a single node though, this will work. It will just be slow.

**Comment by stephenroller** [comment]
Side note, we just landed some speedups to model parallel that will make it less painful (maybe ~40% faster?)

**Comment by zaharPonimash** [comment]
Thank you so much for your answer!
