### ISSUE TITLE
runtime error: need to set model argument to use create_agent

### ISSUE THREAD

**Issue by HotblackDesiato42** [facebookresearch/ParlAI#3282]
**Bug description**
When following the quick tutorial https://parl.ai/docs/tutorial_quick.html
and entering the command "parlai train_model -t babi:task10k:1 -mf /tmp/babi_memnn -bs 1 -eps 5 -m memnn --no-cuda"
I get:

Parse Error: argument -mtw/--multitask-weights: invalid 'multitask_weights' value: 'memnn'

When I remove the "-m memnn" option I get 

Parse Error: unrecognized arguments: --no-cuda

When I remove "--no-cuda" I get:

 File "~/ParlAI/parlai/core/agents.py", line 419, in create_agent
    raise RuntimeError('Need to set `model` argument to use create_agent.')
RuntimeError: Need to set `model` argument to use create_agent.

The example in your quick tutorial doesn't work at all.

I am using Arch Linux.

**Reproduction steps**
Follow quick tutorial: https://parl.ai/docs/tutorial_quick.html

**Expected behavior**
Not to stop with parse or runtime errors for the examples given in the quick tutorial.

**Logs**

parlai train_model -t babi:task10k:1 -mf /tmp/babi_memnn -bs 1 -eps 5
16:43:46 | building dictionary first...
16:43:46 | Opt:
16:43:46 |     aggregate_micro: False
16:43:46 |     allow_missing_init_opts: False
16:43:46 |     batchsize: 1
16:43:46 |     bpe_add_prefix_space: None
16:43:46 |     bpe_debug: False
16:43:46 |     bpe_dropout: None
16:43:46 |     bpe_merge: None
16:43:46 |     bpe_vocab: None
16:43:46 |     datapath:~/ParlAI/data
16:43:46 |     datatype: train
16:43:46 |     dict_class: None
16:43:46 |     dict_endtoken: __end__
16:43:46 |     dict_file: /tmp/babi_memnn.dict
16:43:46 |     dict_include_test: False
16:43:46 |     dict_include_valid: False
16:43:46 |     dict_initpath: None
16:43:46 |     dict_language: english
16:43:46 |     dict_loaded: False
16:43:46 |     dict_lower: False
16:43:46 |     dict_max_ngram_size: -1
16:43:46 |     dict_maxexs: -1
16:43:46 |     dict_maxtokens: -1
16:43:46 |     dict_minfreq: 0
16:43:46 |     dict_nulltoken: __null__
16:43:46 |     dict_starttoken: __start__
16:43:46 |     dict_textfields: text,labels
16:43:46 |     dict_tokenizer: re
16:43:46 |     dict_unktoken: __unk__
16:43:46 |     display_examples: False
16:43:46 |     download_path: None
16:43:46 |     dynamic_batching: None
16:43:46 |     eval_batchsize: None
16:43:46 |     evaltask: None
16:43:46 |     hide_labels: False
16:43:46 |     image_cropsize: 224
16:43:46 |     image_mode: no_image_model
16:43:46 |     image_size: 256
16:43:46 |     init_model: None
16:43:46 |     init_opt: None
16:43:46 |     load_from_checkpoint: True
16:43:46 |     log_every_n_secs: 10
16:43:46 |     loglevel: info
16:43:46 |     max_train_time: -1
16:43:46 |     metrics: default
16:43:46 |     model: None
16:43:46 |     model_file: /tmp/babi_memnn
16:43:46 |     multitask_weights: [1]
16:43:46 |     num_epochs: 5.0
16:43:46 |     override: "{'task': 'babi:task10k:1', 'model_file': '/tmp/babi_memnn', 'batchsize': 1, 'num_epochs': 5.0}"
16:43:46 |     parlai_home: ~/ParlAI
16:43:46 |     save_after_valid: False
16:43:46 |     save_every_n_secs: -1
16:43:46 |     short_final_eval: False
16:43:46 |     starttime: Dec01_16-43
16:43:46 |     task: babi:task10k:1
16:43:46 |     tensorboard_log: False
16:43:46 |     tensorboard_logdir: None
16:43:46 |     validation_cutoff: 1.0
16:43:46 |     validation_every_n_epochs: -1
16:43:46 |     validation_every_n_secs: -1
16:43:46 |     validation_max_exs: -1
16:43:46 |     validation_metric: accuracy
16:43:46 |     validation_metric_mode: None
16:43:46 |     validation_patience: 10
16:43:46 |     validation_share_agent: False
16:43:46 |     verbose: False
16:43:46 | Current ParlAI commit: 21bda4ff10006cfe54a8301dfb36be6d415d1523
16:43:46 | creating task(s): babi:task10k:1
16:43:46 | loading fbdialog data: ~/ParlAI/data/bAbI/tasks_1-20_v1-2/en-valid-10k-nosf/qa1_train.txt
Building dictionary:   0%|                                                                                                                                                                                       | 0.00/9.00k [00:00<?, ?ex/s]16:43:46 | loading fbdialog data: ~/ParlAI/data/bAbI/tasks_1-20_v1-2/en-valid-10k-nosf/qa1_train.txt
Building dictionary: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.00k/9.00k [00:00<00:00, 14.7kex/s]
16:43:47 | Saving dictionary to /tmp/babi_memnn.dict
16:43:47 | dictionary built with 26 tokens in 0.0s
16:43:47 | No model with opt yet at: /tmp/babi_memnn(.opt)
Traceback (most recent call last):
  File "/usr/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "~/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "~/ParlAI/parlai/core/script.py", line 299, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "~/ParlAI/parlai/core/script.py", line 89, in _run_from_parser_and_opt
    return script.run()
  File "~/ParlAI/parlai/scripts/train_model.py", line 768, in run
    self.train_loop = TrainLoop(self.opt)
  File "~/ParlAI/parlai/scripts/train_model.py", line 282, in __init__
    self.agent = create_agent(opt)
  File "~/ParlAI/parlai/core/agents.py", line 419, in create_agent
    raise RuntimeError('Need to set `model` argument to use create_agent.')
RuntimeError: Need to set `model` argument to use create_agent.

```
Output goes here
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by stephenroller** [comment]
Grr sorry, I really need to fix this bug. Python 3.8 changed how CLI parsing works. So now we recommend using either Python 3.7, or using the full expansions of arguments. (--model instead of -m)

Sorry, it's been on my todo for a while.

**Comment by stephenroller** [comment]
This did get fixed recently.
