### ISSUE TITLE
Eval model output metrics fail to include hits@1 and can not eval on the test set

### ISSUE THREAD

**Issue by XuhuiZhou** [facebookresearch/ParlAI#3290]
I am trying to eval the blender model with the following commend:
```python parlai/scripts/eval_model.py --task personachat:self_original -mf zoo:blender/blender_90M/model -bs 32 --metrics hits@1 -dt test```
But I do not see the hits@1 being reported and it also shows that test set does not exist, any insight?

**Comment by stephenroller** [comment]
BlenderBot is a generative model, and so normally isn't used for ranking (e.g. hits@1). PPL, F1, and BLEU are more typical metrics for it. If you are comparing to something which generates `hits@1` metrics, then say, the poly-encoders are a more fair comparison

That said, you enable ranking with the generative model with `--rank-candidates true`.
