### ISSUE TITLE
AttributeError when using blender 3B

### ISSUE THREAD

**Issue by Markfryazino** [facebookresearch/ParlAI#3292]
Hi! I am trying to use blenderbot 3B, creating the agent via 
```python
blender_agent = create_agent_from_model_file("zoo:blender/blender_3B/model")
```

However, when running
```python
blender_agent.observe({'text': 'Hi!', 'episode_done': False})
blender_agent.act()
```
I get the following error:

> AttributeError: 'SlowBytelevelBPE' object has no attribute 'special_tok_map'

Could you please tell me what goes wrong here and how to fix it? 
Also, maybe it is somehow connected to another strange thing 
I've noticed. In the output of the code that creates the agent, there are these lines:

> WARNING: You have chosen to use Huggingface's tokenizer.
> Please install HuggingFace tokenizer with: pip install tokenizers.
> For now, defaulting to the GPT2Tokenizer.

This is also weird, because the `tokenizers` package is already installed.

**Comment by stephenroller** [comment]
Do you mind reporting the results of `pip freeze`?

I think HF released some new versions last week. Our CI seems broken too.

**Comment by Markfryazino** [comment]
@stephenroller I've pasted all the outputs of `pip freeze` [here](https://pastebin.com/qksBiQRD). I am doing it in Google Colab with the following setup:
```
!git clone https://github.com/facebookresearch/ParlAI.git ParlAI
!cd ParlAI; python setup.py develop
%cd ParlAI
!pip install -r requirements.txt
```

**Comment by stephenroller** [comment]
can you install the requirements before you call `setup.py develop`?

Something's really weird here. It's like it's calling two separate places of code which are separated by the "can we import tokenizers?"...

**Comment by Markfryazino** [comment]
Yes, installing the requirements before calling `setup.py` solves it. Thank you!
