### ISSUE TITLE
 About the use of "local human agent"

### ISSUE THREAD

**Issue by tanyue2019** [facebookresearch/ParlAI#3293]
Use this to open other questions or issues, and provide context here.
Hello, I would like to ask, when using "local human agent", what form should "-- local human candidates file" be？
We are looking forward to your reply. Thanks

**Comment by stephenroller** [comment]
Ooo, I don't remember this option. I don't know.

One sentence per line, maybe?

**Comment by stephenroller** [comment]
https://github.com/facebookresearch/ParlAI/blob/2b9d120ddf20ba908a614ee395a342c12fb2d808/parlai/utils/misc.py#L121-L155

Yeah I think one candidate per line.

Still not sure what this option is really needed for. Maybe @alexholdenmiller remembers?

**Comment by tanyue2019** [comment]
Hello, thank you very much for your reply！
I'm thinking about using function“ interactive.py ”when implementing the dialogue with my custom model, it seems that the local human agent can not correctly pass [label candidates] to my agent, so I wonder if I need to specify this parameter.

**Comment by stephenroller** [comment]
Yes, that appears to be what the option is for.

Most of our ranking models have the option of offline candidates though.
