### ISSUE TITLE
Build a conversational chatbot from scratch

### ISSUE THREAD

**Issue by Abhay1994s** [facebookresearch/ParlAI#3295]
Hi I am new to ParlAI and I have an experience of building conversational chatbots in other domains. Can anyone help me how to  build and trained a conversational chatbot in ParlAI from scratch using our custom data i dont want to use the existing trained models of ParlAI. 

I want to know the flow structure as well to train the below conversational flow between the bot and user using ParlAI:

Hey! Welcome to IT Support. Would you like to report an IT Problem?
User:  Yes

Great! May I have your Employee ID please?
User: js2345

Please provide your Mobile Number.
User 66XXXXXXXX

Thank You ! What’s the issue?
(Account Locked)
(Network Error)

User: Clicked on Network Error

Have you tried restarting your machine?
User: Yes

Please explain the problem you are facing
User: My internet is not working

We apologize for the inconvenience caused. I have raised an IT ticket IT8975 and sent you an email. A member from IT team will call you or visit your workstation shortly.
User: ok

Thank You for contacting us. You have a wonderful day!

**Comment by stephenroller** [comment]
Please see https://parl.ai/docs/tutorial_task.html. The quickstart is probably sufficient for your needs.
