### ISSUE TITLE
Dodeca Empathetic dialogues MT+FT test set responses

### ISSUE THREAD

**Issue by manzar96** [facebookresearch/ParlAI#3298]
Hello,
Is there any way to find the generated responses that the dodecadialogue model (MT+FT) produced on the test set of the Empathetic Dialogues dataset?
I am running the eval mode, but I cannot find a way to extract the generated responses.
Thank you in advance.

**Comment by stephenroller** [comment]
Yes, set `--save-world-logs true --report-filename myoutputfolder/ed.json` and you'll find files containing the model's outputs.

**Comment by manzar96** [comment]
Thank you!
However, with the use of:

> parlai eval_model -mf zoo:dodecadialogue/empathetic_dialogues_ft/model -t empathetic_dialogues --save-world-logs true --report-filename /home/ed.json

I receive the responses generated on the validation set. Is there any way to receive the responses on the test set? In order to calculate some further metrics?

**Comment by stephenroller** [comment]
add `-dt test` to your `eval_model` command

**Comment by manzar96** [comment]
Hi again,

Can you please report the exact decoding parameters (beam-size, beam-min-length, beam-block-ngram, beam-context-block-ngram, etc) that you used in the referenced paper for the MT+FT model on the EmpatheticDialogues task?

I a little bit confused with the avg-BLEU metric, as I cannot reproduce the reported results on the paper (8.1 for the MT+FT and 8.4 for the MT)
