### ISSUE TITLE
Rest Api

### ISSUE THREAD

**Issue by Abhay1994s** [facebookresearch/ParlAI#3299]
How to create a Rest API for existing models.

**Comment by stephenroller** [comment]
You can see the tutorial on chat services, or you can build a minimal service using just Flask and the ParlAI introduction tutorial. The issues for this repo also has numerous people who have stood up similar stuff.

**Comment by Abhay1994s** [comment]
Hi Can you please help me how to proceed to create a flask app for GET/POST requests in which my input will be the text message and output is the model response.
