### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS with pytorch 0.2.0_3

### ISSUE THREAD

**Issue by hwaranlee** [facebookresearch/ParlAI#331]
In order to use the new version of pytorch 0.2.0_3, I re-installed it.
Then again run "python setup.py develop"
However, I faced with the following error.
Any comments for this problem?

python version :3.6.0
pytorch version: 0.2.0_3
Ubuntu 14.04.5 LTS

> 
Traceback (most recent call last):
File “examples/train_model_seq2seq_ldecay.py”, line 272, in 
main()
File “examples/train_model_seq2seq_ldecay.py”, line 93, in main
parser = ParlaiParser(True, True)
File “/data2/hwaranlee/convai/ParlAI-v2/parlai/core/params.py”, line 77, in init
self.add_model_args(model_argv)
File “/data2/hwaranlee/convai/ParlAI-v2/parlai/core/params.py”, line 202, in add_model_args
agent = get_agent_module(model)
File “/data2/hwaranlee/convai/ParlAI-v2/parlai/core/agents.py”, line 306, in get_agent_module
my_module = importlib.import_module(module_name)
File “/home/hwaranlee/anaconda3/lib/python3.6/importlib/init.py”, line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File “”, line 978, in _gcd_import
File “”, line 961, in _find_and_load
File “”, line 950, in _find_and_load_unlocked
File “”, line 655, in _load_unlocked
File “”, line 678, in exec_module
File “”, line 205, in _call_with_frames_removed
File “/data2/hwaranlee/convai/ParlAI-v2/parlai/agents/seq2seq/seq2seq.py”, line 10, in 
from torch.autograd import Variable
File “/home/hwaranlee/anaconda3/lib/python3.6/site-packages/torch/init.py”, line 53, in 
from torch._C import *
ImportError: dlopen: cannot load any more object with static TLS

https://discuss.pytorch.org/t/importerror-dlopen-cannot-load-any-more-object-with-static-tls-torch-only/7864

**Comment by hwaranlee** [comment]
For me,
I resolved the problem by `import torch` in advance `import nltk`.

Maybe it can also depend on OS.

**Comment by alexholdenmiller** [comment]
Hi @hwaranlee, sorry for the delayed response! That error is strange--I've gotten it before from trying to "import torch" while in the same directory as a pytorch clone, but it doesn't look like that was the case here. Glad to hear you were able to resolve it.
