### ISSUE TITLE
Maybe a fvcore error

### ISSUE THREAD

**Issue by kuroko730** [facebookresearch/ParlAI#3312]
While I'm trying to run Controllable_dialogue program on Windows,
First,I met the problem like [https://github.com/facebookresearch/ParlAI/issues/3311](url) this.
Then,I follow [https://github.com/facebookresearch/ParlAI/issues/3185](url) this way to solve this problem, it works.
But,there is a new problem like this.

PS I:\ParlAI> python projects/controllable_dialogue/interactive.py -mf models:controllable_dialogue/convai2_finetuned_baseline

********************************************************************************
WARNING: This dialogue model is a research project that was trained on a
large amount of open-domain Twitter data. It may generate offensive content.
********************************************************************************

22:11:49 | [33mOverriding opt["batchsize"] to 1 (previously: 64)[0m
22:11:49 | [33mOverriding opt["beam_size"] to 20 (previously: 1)[0m
22:11:49 | [33mOverriding opt["model_file"] to i:\parlai\data\models\controllable_dialogue/convai2_finetuned_baseline (previously: /private/home/abisee/models/baseline)[0m
22:11:49 | Downloading https://parl.ai/downloads/controllable_dialogue/data_v1.tar.gz to i:\parlai\data\controllable_dialogue\data_v1.tar.gz
Downloading data_v1.tar.gz: 0.00B [00:00, ?B/s]
22:11:56 | Downloading https://parl.ai/downloads/controllable_dialogue/wordstats_v1.tar.gz to i:\parlai\data\controllable_dialogue\wordstats_v1.tar.gz
Downloading wordstats_v1.tar.gz: 0.00B [00:00, ?B/s]
Traceback (most recent call last):
  File "projects/controllable_dialogue/interactive.py", line 24, in <module>
    interactive(parser.parse_args())
  File "i:\parlai\parlai\scripts\interactive.py", line 83, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "i:\parlai\parlai\core\agents.py", line 402, in create_agent
    model = create_agent_from_opt_file(opt)
  File "i:\parlai\parlai\core\agents.py", line 355, in create_agent_from_opt_file
    return model_class(opt_from_file)
  File "i:\parlai\projects\controllable_dialogue\controllable_seq2seq\controllable_seq2seq.py", line 269, in __init__
    initialize_control_information(opt)
  File "i:\parlai\projects\controllable_dialogue\controllable_seq2seq\controls.py", line 97, in initialize_control_information
    build(opt)
  File "i:\parlai\projects\controllable_dialogue\tasks\build.py", line 37, in build
    build_data.untar(dpath, fname_wordstats)
  File "i:\parlai\parlai\core\build_data.py", line 255, in untar
    return _untar(path, fname, delete=delete, flatten=flatten_tar)
  File "i:\parlai\parlai\core\build_data.py", line 294, in _untar
    with PathManager.open(fn, 'wb') as wf, tf.extractfile(item.name) as rf:
  File "E:\Users\Kuroko-Fy\anaconda3\lib\site-packages\fvcore\common\file_io.py", line 647, in open
    path, mode, buffering=buffering, **kwargs
  File "E:\Users\Kuroko-Fy\anaconda3\lib\site-packages\fvcore\common\file_io.py", line 382, in _open
    opener=opener,
OSError: [Errno 22] Invalid argument: 'i:\\parlai\\data\\controllable_dialogue\\wordstat_files/control_questionb11e10.valid.usemodelreply.beam20.beamminnbest10.setcontrols:question10.WDfeatures:extrep_2gram-3.5_extrep_nonstopword-1e+20_intrep_nonstopword-1e+20.wordstats.json'

if someone has an idea what could be causing it?

**Comment by stephenroller** [comment]
This could be an issue with the filenames being incompatible with windows machines...

**Comment by Misterion777** [comment]
Same error, is there any fix?

**Comment by stephenroller** [comment]
Can you try to untar the file outside of parlai?

**Comment by kuroko730** [comment]
Thanks for your reply.
I try to run it on a ubuntu machine and it works smoothly...
for windows , I try to run it with a full English environment and it also works.

**Comment by Misterion777** [comment]
> Can you try to untar the file outside of parlai?

Yes, I unpacked it myself, but there was a warning about max length of a filename. (It seems parlai counts this warning as a error)
