### ISSUE TITLE
Code of conduct violation

### ISSUE THREAD

**Issue by scanlime** [facebookresearch/ParlAI#3332]
This bug was closed without any discussion, in an apparent violation of the code of conduct for this project.

https://github.com/facebookresearch/ParlAI/issues/3331

**Comment by JoelMarcey** [comment]
Hi @scanlime. We certainly support your right to any particular viewpoints. On GitHub, however, the ParlAI project should be utilized for project-specific feedback, improvement suggestions and/or problems you are having with the project itself -- we really appreciate the feedback and discussions from the community and respond to anything actionable. We will continue to close out issues that are not project-specific and feel doing so does not violate our own code of conduct.
