### ISSUE TITLE
About the Image chat dataset - dialogue length and broken image urls

### ISSUE THREAD

**Issue by silverriver** [facebookresearch/ParlAI#3336]
Hi,

I am exploring the dataset Image-chat, but i find some issues. I think it is better to post these issues here:

1. Only 84540 sessions of dialogue in the training split contain 3 utterances. 102242 sessions of dialogues in the training split only contain 1 utterance. However, for my understanding regard to the paper (arxiv: 1811.00945v2), there should be a 3-utterance-dialogue for each image. 
2. To train the dialogue generation model in the paper, only these 3-utterances-dialogues are used? Am I right?
3. It seems that some image urls are broken when constructing the image-chat dataset. (specifically, the images begin with ac8*, e.g. ac8e6eca5713ee25f631e79d9a3355ac.jpg). I understand these images are hosted on yfcc server, not by parlai. But I am wondering if these are any way to obtain these images?

It will be great if my questions can catch @klshuster 's attention, and then be answered. Thanks in advance.

Best

**Comment by klshuster** [comment]
Hi there,

1. There are in fact only 85k 3-turn "dialogues" in the training set; the remaining 100k dialogues are 1-turn examples, the same as in the Personality-Captions dataset. Note that the validation and test sets (5k and 10k dialogues respectively) each have 3-turn dialogues; thus, out of the 200k images in the dataset, half have 3-turn dialogues, which totals to ~400k utterances.
2. All of the 185k image dialogues are used (1-turn and 3-turn) when training the models
3. Indeed, some of the images can no longer be downloaded from the yfcc server; fortunately it is my understanding that the number of images no longer attainable is a small percentage of the overall dataset

Hope that answers your questions!

**Comment by silverriver** [comment]
Thank you very much for the quick reply.

That solves my question.

BTW, this dataset is a great work. love it ;)

Best
