### ISSUE TITLE
Error while creating my own Task

### ISSUE THREAD

**Issue by VishalPallagani** [facebookresearch/ParlAI#3337]
I am trying to create my own task called as DialogPlan. I have followed the example of echobot i n order to create my own task.
I have created a folder parlai_internal after cloning the parlai repo and the file structure for parlai_internal is as follows:

parlai_internal
-agents
  --dialogplan
   ---dialogplan.py
-tasks
  --dpbot
   ---agents.py
   ---worlds.py

The parlai_internal folder can be accessed at: https://drive.google.com/drive/folders/1aumHBWTyXVeTc9XGOqOJqLMz8GOFRwKS?usp=sharing

While trying to execute the created dialogplan task, I am getting an error saying the dialogplan agent isn't found.
It would be a lot helpful if somebody can help me fix this issue.
Thanks in advance.

**Comment by stephenroller** [comment]
Can you post the full exception? Typically that error message comes with a printout of two exceptions, as it derived from a dynamic import.

**Comment by stephenroller** [comment]
Also the command you're running.

**Comment by VishalPallagani** [comment]
I am attaching the snapshot of the error and also the command that I used to execute the code.
<img width="591" alt="Capture" src="https://user-images.githubusercontent.com/22969140/103476919-b5519300-4ddf-11eb-8bd6-f170594ae938.PNG">

**Comment by stephenroller** [comment]
Okay this reads like parlai_internal isn't being imported. Do you have `__init__.py` files in all folders inside parlai_internal?

**Comment by VishalPallagani** [comment]
Yes. I have added the __init__.py files but the same error persists. However, the __init__.py files I have added are without any code. Is that where I am doing something wrong.

**Comment by VishalPallagani** [comment]
The error I committed was naming the agent as Dialogplan, but how it should be actually named is DialogplanAgent. Making this particular change worked for me. 
Thanks for all the help.

**Comment by stephenroller** [comment]
Thanks for updating the task with your findings
