### ISSUE TITLE
BST dataset: where is 'mode' for each utterances?

### ISSUE THREAD

**Issue by ahnjaewoo** [facebookresearch/ParlAI#3338]
Hi, I have a question about BST dataset (https://arxiv.org/pdf/2004.08449.pdf).
<img width="971" alt="스크린샷 2021-01-03 오후 9 48 39" src="https://user-images.githubusercontent.com/15323600/103478953-7afeea80-4e0d-11eb-9a1d-c5b87b237d48.png">

While the paper and Fig. 1 tell us that each utterance are annotated with the 'mode' (e.g., _PB,K,E,S_),
 I cannot find it in raw BST dataset (i.e., `train.json, valid.json, test.json`) unfortunately :(

Without it, one cannot even reproduce **MT Two-Stage model** in the paper because the model is based on a dialog manager that classifies the mode given utterance.

Is the 'mode' only used for private perhaps?

Thanks.

**Comment by stephenroller** [comment]
The modes are derived from a classifier which was trained on the original 3 datasets. See Section 3.2 for details.

**Comment by stephenroller** [comment]
Perhaps @EricMichaelSmith could release his pretrained classifier or at least the command to train a fresh one (which shouldn't be hard).

**Comment by ahnjaewoo** [comment]
Thanks for the comment in details :)

But beyond the classifier, the paper says that the authors collected crowdsourced skill annotation in Section 3.1
Table 3 and Figure 1 also explain that each utterance or dialogue is labeled by multiple modes.

**Comment by EricMichaelSmith** [comment]
Hi! I'm currently looking into whether the two-stage model and/or crowdsourced annotations can be easily open-sourced. I'll reach back out when I have an update on this.

**Comment by EricMichaelSmith** [comment]
Hi @ahnjaewoo See the above PR for how to find the human annotations of modes in the BST dataset.
