### ISSUE TITLE
Readme says use python 3.6.  setup says python 3.7+.  Neither works.  When was this broken?  Should I use an older branch?

### ISSUE THREAD

**Issue by MikeyBeez** [facebookresearch/ParlAI#3357]
Use this to open other questions or issues, and provide conteReadme says use python 3.6.  setup says python 3.7+.  Neither works.  When was this broken?  Should I use an older branch?xt here.

**Comment by stephenroller** [comment]
3.7+ is correct; I'll update the README. We are all using 3.7 or 3.8. We moved away from 3.6 when numpy did.

What is broken? Can you provide details and stack traces?

**Comment by MikeyBeez** [comment]
I'm starting over:  ❯ pip3 list
Package    Version
---------- -------------------
certifi    2020.12.5
pip        20.3.3
setuptools 51.0.0.post20201207
wheel      0.36.2
╭─░▒▓  ─────────────────────────────────────────────────────────────────────────── ✔ ▓▒░─╮
├─░▒▓ on   master                                   ▼  parlai   at 08:47:01 PM  ▓▒░─┤
├─░▒▓  ~/ParlAI                                                                          ─┤
╰─❯ 
❯ python3 setup.py develop
running develop
running egg_info
error: [Errno 13] Permission denied

sudo python3 setup.py develop
running develop
running egg_info
writing parlai.egg-info/PKG-INFO
writing dependency_links to parlai.egg-info/dependency_links.txt
writing entry points to parlai.egg-info/entry_points.txt
writing requirements to parlai.egg-info/requires.txt
writing top-level names to parlai.egg-info/top_level.txt
reading manifest file 'parlai.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'parlai.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python3.8/dist-packages/parlai.egg-link (link to .)
parlai 0.10.0 is already the active version in easy-install.pth
Installing parlai script to /usr/local/bin

Installed /home/bard/ParlAI
Processing dependencies for parlai==0.10.0
error: Markdown 3.1.1 is installed but markdown~=3.2 is required by {'py-gfm'}

**Comment by stephenroller** [comment]
Thanks for reporting.

**Comment by MikeyBeez** [comment]
sudo python3 --version
Python 3.8.5

This is strange.  When I run sudo, it uses a different version of python -- not the one in my conda environment.

**Comment by MikeyBeez** [comment]
So this fixes part of it:  

sudo env "PATH=$PATH" python setup.py develop

I still get this warning:  n file included from ext/_yaml.c:596:
ext/_yaml.h:2:10: fatal error: yaml.h: No such file or directory
    2 | #include <yaml.h>
      |          ^~~~~~~~

But it seems to install okay.  I'll run some tests and let you know.  BTW, doesn't everyone install this into a virtual environment?  Shouldn't your README cover that?  Anyway, cheers, and thank you for sharing your software. :)

**Comment by MikeyBeez** [comment]
I think making myself part of the staff group might also solve this issue.  Then I wouldn't need to sudo to write to /usr/local/lib/python . . .

**Comment by MikeyBeez** [comment]
Being in group staff all the time is dangerous.  It's like being root; so caveat emptor.  ;)

**Comment by stephenroller** [comment]
We typically recommend using virtualenv or conda to create a user level environment.

**Comment by stephenroller** [comment]
Updated readme in #3359.

**Comment by MikeyBeez** [comment]
Thanks.
