### ISSUE TITLE
Is there a community forum?  Could you start one? ;) 

### ISSUE THREAD

**Issue by MikeyBeez** [facebookresearch/ParlAI#3361]
**Is your feature request related to a problem? Please describe.**
I dan't find a Parla community forum

**Describe the solution you'd like**
I'd like a link to a Parlai community forum

**Describe alternatives you've considered**
Asking questions in the issues section.

**Additional context**
https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.buntINTHFLyDODyMKXNYcgHaEK%26pid%3DApi&f=1

**Comment by stephenroller** [comment]
I would really like that. GitHub is apparently betaing a "Discussions" tab for exactly this. I've been waiting for that to release. I'll check with the corporate OSS people to see if we can enable the beta.

https://github.com/dear-github/dear-github/issues/44

**Comment by stephenroller** [comment]
Hey Mikey. Good news, it's in open beta now. We've enabled the tab. Please feel free to open the inaugural discussion!

**Comment by MikeyBeez** [comment]
Cheers, Stephen!  You guys rock.
