### ISSUE TITLE
Dynamic Batching x Chunk Teacher x Distributed Training hangs during evaluation

### ISSUE THREAD

**Issue by emilydinan** [facebookresearch/ParlAI#3367]
In certain settings Dynamic Batching x Chunk Teacher x Distributed Training hangs during evaluation. Hanging happens before first eval step. Cannot reproduce with <=16 gpus and without dynamic batching.

**Comment by stephenroller** [comment]
Suspicion is buffer doesn't fill on such wide distribution

**Comment by emilydinan** [comment]
That is my suspicion as well, although it has worked in the past with a smaller number of validation examples.
