### ISSUE TITLE
Tokenizer problem? There is always space between the punctuations

### ISSUE THREAD

**Issue by wyshi** [facebookresearch/ParlAI#3377]
**Bug description**
Blender bot, there is always space between the punctuations, seems like there is something like ``" ".join(tokens)``.
e.g. 
[TransformerGenerator]: hello , how are you ? i just got off work at mcdonalds . what do you do ?
(Noe the spaces)

>>> tokenizers.__version__
'0.9.2'
>>> parlai.__version__
'0.10.0'

**Reproduction steps**
``python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_90M/model``

**Comment by stephenroller** [comment]
That's correct. The 90M was trained with a vanilla BPE tokenizer, _not_ a ByteLevelBPE tokenizer.

The 400M distilled has a ByteLevelBPE tokenizer if you want something small, but is whitespace-aware.
