### ISSUE TITLE
Training with pytorch

### ISSUE THREAD

**Issue by anand-ar** [facebookresearch/ParlAI#338]
I am new to using pytorch - are there examples or guideline on how to do training for squad dataset

Just for a trial - I started it on my local mac box and am not sure when it is going to complete 

Thanks

**Comment by alexholdenmiller** [comment]
Hi @anand-ar,

I believe the SQuAD dataset takes quite some time to train on, especially without a GPU (ie if your local mac box doesn't have one).
It also depends on the model you are training with. If you are using the drqa model, maybe followup on github.com/facebookresearch/drqa instead--I'm not totally sure on how long it took them to train.

**Comment by anand-ar** [comment]
Thanks
