### ISSUE TITLE
projects/contradiction request for model release

### ISSUE THREAD

**Issue by akhileshgotmare** [facebookresearch/ParlAI#3391]
@jaseweston @easonnie 
https://github.com/facebookresearch/ParlAI/tree/master/projects/contradiction
Curious if/when you're planning to release the sota RoBERTa contradiction in dialog detectors (one trained using unstructured and other using structured utterance based approach) described in Section 4.1. Would be a big help in replicating the results from your paper https://arxiv.org/pdf/2012.13391.pdf.
Thanks!

**Comment by easonnie** [comment]
Hi @akhileshgotmare, thanks for reaching out.

We plan to release the contradiction detector upon publication.

As for now, you can play our pre-trained contradiction detector with the code snippet below:
```
from transformers import AutoTokenizer, AutoModelForSequenceClassification # 4.0.1
import torch # 1.7

if __name__ == '__main__':
    max_length = 256

    premise = "I'm an Spanish teacher."
    hypothesis = "I don't know how to speak Spanish."

    hg_model_hub_name = "ynie/roberta-large_conv_contradiction_detector_v0"

    tokenizer = AutoTokenizer.from_pretrained(hg_model_hub_name)
    model = AutoModelForSequenceClassification.from_pretrained(hg_model_hub_name)

    tokenized_input_seq_pair = tokenizer.encode_plus(premise, hypothesis,
                                                     max_length=max_length,
                                                     return_token_type_ids=True, truncation=True)

    input_ids = torch.Tensor(tokenized_input_seq_pair['input_ids']).long().unsqueeze(0)
    # remember bart doesn't have 'token_type_ids', remove the line below if you are using bart.
    token_type_ids = torch.Tensor(tokenized_input_seq_pair['token_type_ids']).long().unsqueeze(0)
    attention_mask = torch.Tensor(tokenized_input_seq_pair['attention_mask']).long().unsqueeze(0)

    outputs = model(input_ids,
                    attention_mask=attention_mask,
                    token_type_ids=token_type_ids,
                    labels=None)

    predicted_probability = torch.softmax(outputs[0], dim=1)[0].tolist()  # batch_size only one

    print("Premise:", premise)
    print("Hypothesis:", hypothesis)
    print("Non contradiction:", predicted_probability[0])
    print("Contradiction:", predicted_probability[1])
``` 

Note that the model is trained with the utterance-based approach (on DECODE data). When you apply it to dialogue data, you need to pair each of the previous utterances with the last utterance and then check the maximum of all their contradiction probabilities.

I hope it can help.

**Comment by akhileshgotmare** [comment]
Thanks so much @easonnie for sharing the code snippet! 

Just to confirm: does the model you shared here correspond to Table 4: RoBERTa trained on DECODE (93.19 on Main (test)) with the utterance-based approach (which does slightly worse than the unstructured one on in-domain test, but generalises better to other domains as shown in Fig 3)? 

Is this the same model you used for generation re-ranking and auto-eval in Section 5.3?

**Comment by easonnie** [comment]
Hi @akhileshgotmare. Yes, that is correct. It is RoBERTa trained on DECODE and it is the same model we used in Sec 5.3.
