### ISSUE TITLE
Task settings of Browser chat

### ISSUE THREAD

**Issue by castalta** [facebookresearch/ParlAI#3392]
Hello!

In terminal chat, I tried the task of "blender_90M model" + "Wikipedia" with the following command.

python3 parlai/scripts/interactive.py -t wizard_of_wikipedia -mf zoo:blender/blender_90M/model

So,
I'd like to try the same combination in a browser chat, can I specify "Wikipedia" in "config.yml" for the task?
Or is there a way to set the task in another file?
I would appreciate it if you could give me tips.

(I added a task to the options in "config.yml", but it doesn't seem to be correct.)

tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  task: wizard_of_wikipedia  #Does not work...
  debug: True
  models:
    blender_90M:
      model: transformer/generator
      model_file: zoo:blender/blender_90M/model
      tasks:
      interactive_mode: True
      no_cuda: True
additional_args:
  page_id: 1

**Comment by stephenroller** [comment]
I don't believe we have direct support for tasks in the chat services at this time.

We sometimes handle this by building custom Worlds within the chat services frameworks.

**Comment by stephenroller** [comment]
@klshuster do you think it would make sense to have custom worlds in task folders similar to self chat? Or keep isolated?

**Comment by klshuster** [comment]
in the current setup it makes most sense to keep isolated...i think it would be a worthwhile refactor to have `chat_services` handle custom interactive worlds easily

**Comment by castalta** [comment]
Thank you for your answers.
I will more carefully study the mechanisms of chat services frameworks.
