### ISSUE TITLE
Starting over or resetting a conversation

### ISSUE THREAD

**Issue by Abhay1994s** [facebookresearch/ParlAI#3394]
Hi, i have loaded blender bot model(opt['model_file']) and created an by agent = create_agent(opt, requireModelExists=True) and have created multiple clones of that agentClone_0 = agent.clone(), agentClone_1 = agent.clone(). I want to know how to clear the context or reset the conversation only for agentClone1 not for agentClone0?

**Comment by stephenroller** [comment]
A few options:
- have agentClone1 observe `{'episode_done': True}`
- call agentClone1.reset()
- Throw away agentClone1 and create a new clone

All 3 options should have the same effect.
