### ISSUE TITLE
How to Fine tune the Existing 90M and 3.7B Models for closed domain application with a custom dataset in Google Colab.

### ISSUE THREAD

**Issue by peterhead007** [facebookresearch/ParlAI#3404]
I'm really confused where and how to start the Fine tuning the existing 90M model in Google Colab 

I needed the **exact code for fine tuning the existing 90M model with dataset txt file in Google Colab for a closed domain application ** and also wanted to know time taken for each Epoch for 100 dialogues dataset and also wanted to know how many epochs are to be put.

I've created a dataset of 100 dialogues in PARTAI dialogue format and tried fine tuning with the code below:

`!python -m parlai.scripts.train_model -t fromfile:parlaiformat --fromfile_datapath /content/train_file.txt -m transformer/generator --multitask-weights 1,3,3,3 --init-model zoo:tutorial_transformer_generator/model --dict-file zoo:tutorial_transformer_generator/model.dict --embedding-size 512 --n-layers 8 --ffn-size 2048 --dropout 0.1 --n-heads 16 --learn-positional-embeddings True --n-positions 512 --variant xlm --activation gelu --skip-generation True --fp16 True --text-truncate 512 --label-truncate 128 --dict-tokenizer bpe --dict-lower True -lr 1e-06 --optimizer adamax --lr-scheduler reduceonplateau --gradient-clip 0.1 -veps 0.25 --betas 0.9,0.999 --update-freq 1 --attention-dropout 0.0 --relu-dropout 0.0 --skip-generation True -vp 15 -stim 60 -vme 20000 -bs 16 -vmt ppl -vmm min --save-after-valid True --model-file /content/drive/Models/new_model/test_train_90M`

But the above code is taking so long to train even for the very small dataset. And I had to stop the training in middle as it was taking so long.

Please  If anyone can give me a solution , it is very much appreciated.

Thank You in advance..

**Comment by stephenroller** [comment]
Our colab tutorial entirely covers that. https://colab.research.google.com/drive/1bRMvN0lGXaTF5fuTidgvlAl-Lb41F7AD#scrollTo=KtVz5dCUmFkN
