### ISSUE TITLE
New agent convenience function

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#3408]
Right now when we "deploy" models in different environments, we tend to manually implement the parley loops. This leads to a lot of code that looks roughly like this

```python
agent1 = agent.clone()
agent1.observe({'text': 'yada ydada', 'episode_done': True})
response = agent1.act()
return response['text']
```

I would like us to create a helper function in the very top level Agent class:

```python
def respond(self, text: str, **other_message_fields) -> str:
     pass
```

which should implement the above template, including a `self.clone()`.

Additionally, also implement a `batch_respond`:
```python
def batch_respond(self, texts: List[str], **other_message_fields) -> List[str]:
    pass
```
The primary difference is this one should leverage `batch_act` instead. See the [worlds tutorial](https://parl.ai/docs/tutorial_worlds.html) the implementation of BatchWorld for details.

The methods should be:
- documented with an excellent docstring
- unit tested directly with several agents, such as: repeat_query, one of the test torch agents (see test_transformer.py), and probably a mock agent
- documented in the worlds tutorial and the tips and tricks docs.

Afterwards, talk to Ankita about upgrading the implementation in the Wizard deployment.

**Comment by klshuster** [comment]
should we close this issue given the PR landed?
