### ISSUE TITLE
Improve error message on failed model zoo import

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#3414]
Users are sometimes unable to import our recent model zoo items because their branch is too far behind. Make the model import failure message a bit nicer here:

https://github.com/facebookresearch/ParlAI/blob/67433e376fc361dee5aa045cb6bb2b68d3faa478/parlai/core/build_data.py#L501-L503

While you're at it, please convert it to use [exception chaining](https://docs.python.org/3/tutorial/errors.html#exception-chaining)

**Comment by hadasah** [comment]
Done in #3445
