### ISSUE TITLE
example chat service stuck on model params loading

### ISSUE THREAD

**Issue by zlakomanoff** [facebookresearch/ParlAI#3426]
**Bug description**
i run chat example as described in your instruction and got stuck on "Loading existing model params" :/

**Reproduction steps**
git clone https://github.com/facebookresearch/ParlAI.git ~/ParlAI
cd ~/ParlAI
python3.7 setup.py develop
config - https://github.com/facebookresearch/ParlAI/blob/master/parlai/chat_service/tasks/chatbot/config.yml
python3.7 /home/ubuntu/ParlAI/parlai/chat_service/services/browser_chat/run.py --config-path ~/chat-config.yml --port 8080

**Expected behavior**
chat is ready for interact

**Logs**
```
12:54:59 | building data: /home/ubuntu/ParlAI/data/models/blender/blender_90M/BST0B.tgz
12:54:59 | Downloading http://parl.ai/downloads/_models/blender/BST0B.tgz to /home/ubuntu/ParlAI/data/models/blender/blender_90M/BST0B.tgz
Downloading BST0B.tgz: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 161M/161M [00:07<00:00, 20.5MB/s]12:55:10 | Loading model with `--beam-block-full-context false`
12:55:11 | loading dictionary from /home/ubuntu/ParlAI/data/models/blender/blender_90M/model.dict
12:55:11 | num words = 54944
12:55:11 | TransformerGenerator: full interactive mode on.
12:55:13 | DEPRECATED: XLM should only be used for backwards compatibility, as it involves a less-stable layernorm operation.
12:55:13 | Total parameters: 87,508,992 (87,508,992 trainable)
12:55:13 | Loading existing model params from /home/ubuntu/ParlAI/data/models/blender/blender_90M/model
```

**Additional context**
environment - ASW EC2 instance (ubuntu 18)
CPU usage - 0%

**Comment by stephenroller** [comment]
Does it crash?

It's a pretty reasonably sized model ("small") but some people running on AWS have needed to use instances with more memory.

**Comment by zlakomanoff** [comment]
Does it crash? - no
running on AWS have needed to use instances with more memory - we're using 32 gigs instance :/

**Comment by stephenroller** [comment]
Can you use a simple pytorch program successfully?

**Comment by zlakomanoff** [comment]
what you mean ?
**parlai display_data --task babi:task10k:1** -> work well

**Comment by stephenroller** [comment]
My question is, leaving parlai entirely, does pytorch work as expected?

What if you add no_cuda: True to your config?

I'm wondering if you're having GPU issues

**Comment by yannc2021** [comment]
I have the same issue running the blender_90M model on my computer. It is stuck on "loading existing model params". How did you fix it?
