### ISSUE TITLE
how can i use new wikipedia data link with avoiding parlai module

### ISSUE THREAD

**Issue by Hilal-Urun** [facebookresearch/ParlAI#3433]
Hi @klshuster  I have changed just https://github.com/facebookresearch/ParlAI/blob/3cd5a8fe5f50c51ec71882a074c2a810d995024c/parlai/tasks/wikipedia/build.py#L12 
link of this from my dataset from enwiki, but when downloading process starts, it gets the link from parlai modüle which is same as above. How can I handle with this?

**Comment by klshuster** [comment]
can you please paste the full stack trace?

**Comment by Hilal-Urun** [comment]
![image](https://user-images.githubusercontent.com/37075702/106653565-06ec6980-65a8-11eb-98cd-ec20adb46ead.png)
And after that-> 
 python3 parlai/scripts/train_model.py -t blended_skill_talk,wikipedia:full -m transformer/generator --init-model zoo:tutorial_transformer_generator/model --dict-file zoo:tutorial_transformer_generator/model.dict --embedding-size 512 --n-layers 8 --ffn-size 2048 --dropout 0.1 --n-heads 16 --learn-positional-embeddings True --n-positions 512 --variant xlm --activation gelu --skip-generation True --fp16 True --text-truncate 512 --label-truncate 128 --dict-tokenizer bpe --dict-lower True -lr 1e-06 --optimizer adamax --lr-scheduler reduceonplateau --gradient-clip 0.1 -veps 0.25 --betas 0.9,0.999 --update-freq 1 --attention-dropout 0.0 --relu-dropout 0.0 --skip-generation True -vp 15 -stim 60 -vme 20000 -bs 16 -vmt ppl -vmm min --save-after-valid True --model-file "/home/dtarge/ParlAI2/test_train_90M"

4 hour ago it was using the link in the orijinal one but now,  I dont know what is changed it is changed and works :
![image](https://user-images.githubusercontent.com/37075702/106654712-8890c700-65a9-11eb-875c-2b82ec31b212.png)

Thanks for your time, I'm sorry to keep you busy 🙏

**Comment by klshuster** [comment]
glad to see it's working! please let me know if you have any other questions

**Comment by Hilal-Urun** [comment]
Thanks a lot 🙏 @klshuster

**Comment by stephenroller** [comment]
Closing since this looks addressed. Please reopen or create a new issue if you have more issues.

**Comment by klshuster** [comment]
hi @Hilal-Urun , it is best if we keep discussion in this single thread, rather than referencing very old, unrelated pull requests (pulling discussion from #2002)

if you'd like to use your own wikipedia dump, I recommend downloading the file manually, then running the following commands.

Let's suppose your path to your ParlAI checkpout is `PATH`; and the path to the wikipedia tar download (e.g., enwiki-latest-pages-articles.xml.bz2) is `PATH2`

```
$ cd PATH/data
$ git clone https://github.com/attardi/wikiextractor PATH/wikiextract 
$ cd PATH/wikiextract 
$ python WikiExtractor.py PATH2 --filter_disambig_pages -o PATH/data/wikipedia/full/wiki_extracted --json
```

This will populate the ParlAI `data/wikipedia` folder with the relevant extracted files. Then you can use `-t wikipedia` with your own dump files.

**Comment by Hilal-Urun** [comment]
> hi @Hilal-Urun , it is best if we keep discussion in this single thread, rather than referencing very old, unrelated pull requests (pulling discussion from #2002)
> 
> if you'd like to use your own wikipedia dump, I recommend downloading the file manually, then running the following commands.
> 
> Let's suppose your path to your ParlAI checkpout is `PATH`; and the path to the wikipedia tar download (e.g., enwiki-latest-pages-articles.xml.bz2) is `PATH2`
> 
> ```
> $ cd PATH/data
> $ git clone https://github.com/attardi/wikiextractor PATH/wikiextract 
> $ cd PATH/wikiextract 
> $ python WikiExtractor.py PATH2 --filter_disambig_pages -o PATH/data/wikipedia/full/wiki_extracted --json
> ```
> 
> This will populate the ParlAI `data/wikipedia` folder with the relevant extracted files. Then you can use `-t wikipedia` with your own dump files.

Okey, thanks a lot I'm trying now :)  @klshuster
