### ISSUE TITLE
Using ParlAI in flask app

### ISSUE THREAD

**Issue by k1ng61** [facebookresearch/ParlAI#3444]
I was looking to put together a conversational AI flask app but didn't know how to start. I looked at the browser_chat chat service but it was difficult for me to add things onto because it was built on http_server. Can someone point me in the right direction or hop on discord to look at this?

Thanks

**Comment by stephenroller** [comment]
This is a commonly requested feature. Unfortunately no one on our team has time to produce this exactly. If you search through issues, several people have mentioned it before and seemed to have succeeded implementing it. If someone were to make a PR, I would guide them to landing it.

**Comment by stephenroller** [comment]
(FWIW the `interactive_web` script is much simpler and easier to extend)
