### ISSUE TITLE
Building task in BatchWorld takes long time

### ISSUE THREAD

**Issue by backpropper** [facebookresearch/ParlAI#345]
I observed that while creating the VQA v1 task, when I use batchsize > 1, it takes sufficient amount of time before it starts the training (4 sec for every instance, so for a batch of 128, it takes around 9 min). I tried to narrow down the time-consuming part and I found that it copies all the data (questions and annotations) for each batch.https://github.com/facebookresearch/ParlAI/blob/8bf850ff9bfea750a8f0cfda816ed23d68fda71d/parlai/core/worlds.py#L541

**Comment by alexholdenmiller** [comment]
Good catch--it's not actually copying it all, but it is iterating over it. Fix incoming.

**Comment by alexholdenmiller** [comment]
Fixed & merged
