### ISSUE TITLE
Issue terminal chat service

### ISSUE THREAD

**Issue by thies1006** [facebookresearch/ParlAI#3451]
Hello,

First of all thank you for this amazing framework.
I was trying to run the terminal chat example (code from today without changes except port).

It seems that there are only 'max_worker' clients possible to connect in total. For example when I set max_worker=1 in the config.yml, I can connect with the client one time successfully. But when I stop the client ('[DONE]'), start it again and it gets stuck right at the beginning.

How can I prevent the server from getting stuck once >max_workers clients have been connected? I already tried removing the agent from memory, however it seems that the issue is that the thread is just not ending.

![image](https://user-images.githubusercontent.com/32954413/107663358-94f0e000-6c8b-11eb-8cd3-97fd1806197a.png)

I use Python 3.7.5 and Ubuntu 18.04 LTS.

**Comment by stephenroller** [comment]
@klshuster any idea?

**Comment by klshuster** [comment]
sorry for the late response... i've identified the issue, and put up a PR in #3457.

**Comment by klshuster** [comment]
#3457 is merged, closing
