### ISSUE TITLE
Blender 90M model interacting multi-user

### ISSUE THREAD

**Issue by Hilal-Urun** [facebookresearch/ParlAI#3454]
Hi @klshuster , I hope you are doing well. I want to ask a question ; 

I want to use one model which is blender 90M (finetuned on wikipedia data ) then, for example 10 people can interact the same model, is that possible or I have to copy the number of the same model for each user on different clusters each time?

**Comment by stephenroller** [comment]
Once you have an agent, you can make clones by calling `agent.clone()`. Clones maintain their own dialogue state/history, but share the underlying model. You can use this to cheaply have many copies of the model running in parallel -- one per user.

**Comment by Hilal-Urun** [comment]
Okey I got it. Thanks a lot @stephenroller
