### ISSUE TITLE
projects/contradiction request for clarification on auto eval

### ISSUE THREAD

**Issue by akhileshgotmare** [facebookresearch/ParlAI#3460]
Hi @easonnie! (Re: I like fish 🐟, especially dolphins 🐬:∗ Addressing Contradictions in Dialogue Modeling) I've been trying to replicate the contradictory generation problem of Blenderbot that has been summarized in Table 6 (first 2 rows, automatic eval with DECODE contradict % only) and would really appreciate your clarification on these two aspects:

(1) In Section 5.3's last paragraph you mention: ```We consider the same human-bot dialogue logs as before, but only between Blenderbot BST 2.7B and humans, equally sampled between contradicting and non-contradicting utterances.```. 

After loading the DECODE dataset's `human-bot.jsonl` file, I found that each json object has an object `auxiliary`, which contains the value `original_model`. There are 32 unique model names over the entire dataset split of 764 samples, can you confirm which ones correspond to the one used in the table? My guess:
```
'adversarial/generative2.7B_bst_0331',
 'adversarial_v2/generative2.7B_bst_0331',
 'adversarial_v2_20200515/generative2.7B_bst_0331',
 'adversarial_v3/generative2.7B_bst_0331',
 'live/generative2.7B_bst_0331',
 'live/generative2.7B_bst_0331_long',
 'live/generative2.7B_bst_0331_min_beam_1',
 'live/generative2.7B_bst_0331_min_beam_1_again',
 'live/generative2.7B_bst_0331_top_k_40',
```
Did I miss any? How many examples of the 764 correspond to this set that you refer to in the last paragraph of 5.3? 

(2) Assuming each of these 764 examples is a set of utterances `{u1, u2 ... un}` where the label indicates whether `un` contradicts the context `{u1, u2, ... un-1}`, then the input to the BlenderBot for Table 6 experiments is the context only, no? And the generation is then fed with the context to the utterance-based RoBERTa model with DECODE fine-tuning for evaluation, is that correct?

**Comment by stephenroller** [comment]
@jaseweston do you have anything to add here?
