### ISSUE TITLE
Trouble finding code for Blenderbot implementation

### ISSUE THREAD

**Issue by applyinnovations** [facebookresearch/ParlAI#3468]
I am having trouble finding the source code implementation of Blenderbot within this repository. Could someone please point me to the folder / file that contains the BlenderBot model? 

[parlai/zoo/blender/blender_3B.py](https://github.com/facebookresearch/ParlAI/blob/fd1b8bb565a1a27bcc8326a36afde03a963819ba/parlai/zoo/blender/blender_3B.py) contains the code to download the pretrained model, however I would like to make modifications to the Blenderbot source and train from scratch.

Thanks,
Alex

**Comment by stephenroller** [comment]
https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/transformer/modules.py contains most of the modeling code

https://github.com/facebookresearch/ParlAI/blob/master/parlai/core/torch_generator_agent.py contains most of the control logic

https://github.com/facebookresearch/ParlAI/blob/master/parlai/tasks/blended_skill_talk/agents.py contains most of the data code

**Comment by applyinnovations** [comment]
Thanks Stephen,

I assume that [torch_generator_agent.py](https://github.com/facebookresearch/ParlAI/blob/master/parlai/core/torch_generator_agent.py) contains both the dialog and knowledge variants of the Retrieve and Refine (RetNRef) models? From my quick perusal of the code it seems like it is only a generator, or am I missing something?

**Comment by stephenroller** [comment]
No, I actually think didn't end up releasing the RnR model. It worked worse so it wasn't prioritized.

**Comment by applyinnovations** [comment]
Oh okay, so you recommend to use the generator model even for topic bound conversations similar to the Wizards of Wikipedia task?
