### ISSUE TITLE
Multiple CNN initializations causing memory leak

### ISSUE THREAD

**Issue by backpropper** [facebookresearch/ParlAI#347]
CNN initialized multiple number of times for multibatch
https://github.com/facebookresearch/ParlAI/blob/879bb1502a449a72d82603cc56c87c168fe78ace/parlai/core/image_featurizers.py#L101

**Comment by alexholdenmiller** [comment]
`if not self.netCNN` should only evaluate to True the first time this function is called. let us know what you find!

**Comment by backpropper** [comment]
You can reproduce the issue by checking if it goes inside that scope (adding a print statement). 
I got the same using `python examples/display_data.py -t vqa_v1:all -bs 8 --image-mode resnet152` which prints the check multiple times.

**Comment by backpropper** [comment]
I found the issue. It was due to the image_loader object not in the shared dict. So for each task agent call, it initializes the image_loader object https://github.com/facebookresearch/ParlAI/blob/879bb1502a449a72d82603cc56c87c168fe78ace/parlai/tasks/vqa_v1/agents.py#L69
I have fixed the issue in the PR.
