### ISSUE TITLE
RuntimeError: Need to set `model` argument to use create_agent

### ISSUE THREAD

**Issue by vinnik-dmitry07** [facebookresearch/ParlAI#3472]
```RuntimeError: Need to set `model` argument to use create_agent.```
Also I have `KeyError: 'skip_generation'` running DisplayModel.main.

You can reproduce it via the *ParlAI Tutorial* notebook.

**Comment by vinnik-dmitry07** [comment]
It seems to be my bad.

**Comment by younis-ba** [comment]
hello 
I have a model trained I want to convert to ParlAI! how can do it!

**Comment by klshuster** [comment]
where did you train it?

**Comment by younis-ba** [comment]
in Pytorch

**Comment by younis-ba** [comment]
pytorch using BertForSequenceClassification and dataset is Csv

**Comment by younis-ba** [comment]
Enter text (q to quit): how are you 
--- Text: how are you 
--- Prediction: self.depression | Confidence: 0.4847826361656189
--- Confidence for each class
               class  confidence
0       self.Anxiety    0.179089
1       self.bipolar    0.158747
2    self.depression    0.484783
3  self.SuicideWatch    0.114597
4    self.offmychest  
there is the output from my model I want to chat using parlai

**Comment by klshuster** [comment]
you'd need to update the state dict to match one of our existing models; most likely, you're looking for our `transformer/classifier`[https://github.com/facebookresearch/ParlAI/blob/6c02980e58def83acb8bdddbe5b1db49042e0c99/parlai/agents/transformer/transformer.py#L402] agent; specifically, modifying the weights to be a [linear wrapper](https://github.com/facebookresearch/ParlAI/blob/6c02980e58def83acb8bdddbe5b1db49042e0c99/parlai/agents/transformer/modules/wrappers.py#L36) around a [memnet](https://github.com/facebookresearch/ParlAI/blob/6c02980e58def83acb8bdddbe5b1db49042e0c99/parlai/agents/transformer/modules/mem_net.py#L20) model

**Comment by younis-ba** [comment]
is there a tutorial in docs about that!  I am stuck at this point I want clear detail!

**Comment by klshuster** [comment]
No, however, please see [this script](https://github.com/facebookresearch/ParlAI/blob/main/parlai/agents/bart/convert_fairseq_to_parlai.py) for an example of converting a fairseq checkpoint into a ParlAI model
