### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [facebookresearch/ParlAI#3478]
[jw@cn06 parlai]$ sudo python3 setup.py develop --verbose
running develop
running egg_info
writing parlai.egg-info/PKG-INFO
writing dependency_links to parlai.egg-info/dependency_links.txt
writing entry points to parlai.egg-info/entry_points.txt
writing requirements to parlai.egg-info/requires.txt
writing top-level names to parlai.egg-info/top_level.txt
reading manifest file 'parlai.egg-info/SOURCES.txt'
writing manifest file 'parlai.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python3.9/site-packages/parlai.egg-link (link to .)
parlai 1.0.0 is already the active version in easy-install.pth
Installing parlai script to /usr/local/bin

Installed /data/jw/parlai
Processing dependencies for parlai==1.0.0
Searching for jsonlines
Reading https://pypi.org/simple/jsonlines/
Download error on https://pypi.org/simple/jsonlines/: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't find index page for 'jsonlines' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or working download links found for jsonlines
error: Could not find suitable distribution for Requirement.parse('jsonlines')
[jw@cn06 parlai]$ 

sudo python3 setup.py install --verbose

will also complain about jsonlines

**Comment by stephenroller** [comment]
Are you sure you don't have a network issue? https://pypi.org/project/jsonlines/

**Comment by stephenroller** [comment]
Looks like PyPI is having [operational issues](https://status.python.org/).

**Comment by LutzWeischerFujitsu** [comment]
I don't think I have (still) network issues, 'pip3 install's work. 
When installing 'jsonlines' from GitHub, that works. Retrying 'ParlAI', results in the same type of error, but now for 'websocket-server'.

**Comment by stephenroller** [comment]
I'm pretty sure it something with your machine or network. Sorry

**Comment by LutzWeischerFujitsu** [comment]
sudo python3 ... complains about jsonlines. However, sudo python ... about websocket-server. 
python3 ... and python ... about permission denied. 
python3 is 3.8.8, python is 3.9.1 on my installation, currently.

**Comment by stephenroller** [comment]
I recommend setting up a conda environment or a virtual env so that libraries are self contained and don't interfere with system installations.
