### ISSUE TITLE
HITs are not killed completely

### ISSUE THREAD

**Issue by Stefan1220** [facebookresearch/ParlAI#3481]
Hi! 

I launched an mturk task using ParlAI before and have a problem when I am trying the kill the program. To make the program keep running, I use 'nohup' command to let it run in the background. But when I killed the program using command line, this mturk task is still showing up in the HITs list on mturk platform. I also tried to delete the corresponding application on Heroku, but the task is still there. Do you guys have any idea about how to make the task disappear in the HITs list? Thanks!

**Comment by stephenroller** [comment]
there's a delete_hits.py somewhere

**Comment by JackUrb** [comment]
You can find the functionality for this in Mephisto [here](https://github.com/facebookresearch/Mephisto/blob/master/mephisto/scripts/mturk/cleanup.py).

If you happen to be trying to use ParlAI-MTurk, you'll have to go to an earlier branch of ParlAI to use it - [here](https://github.com/facebookresearch/ParlAI/blob/final_mturk/parlai/mturk/scripts/delete_hits.py).
