### ISSUE TITLE
How do I run the Code to Generate Text Adventures

### ISSUE THREAD

**Issue by simonhughes22** [facebookresearch/ParlAI#3485]
The documentation focuses on the logic to train a model on a number of tasks. I am particularly interested in replicating the work in this paper https://arxiv.org/pdf/1911.09194.pdf about generating text adventures. The documentation does not list where the core LIGHT dataset is (only the WILD data), or how to load it and interact with it in a text adventure game. Please advise.

**Comment by stephenroller** [comment]
@JackUrb do you want to answer this?

You're right. It looks like a bunch of datasets might be missing from our [list of tasks](https://parl.ai/docs/tasks.html). Thanks for bringing that to our attention.

The original LIGHT dataset is `light_dialogue`. `parlai display_data -t light_dialogue`.

**Comment by JackUrb** [comment]
Hi @simonhughes22 - sorry for the delay here! We've been working on putting all of the LIGHT code and datasets into a repo for organization and reproducibility purposes, and should have code for training such a model available there in coming months. 

At the moment, the results of that particular paper are somewhat hard to reproduce, as the underlying model and code we used in that paper have fallen out of sync with ParlAI. You can certainly use the Starspace model available in the current repo alongside the data in the `environment.db` file that comes along with the `light_dialog` task to train your own model though.
