### ISSUE TITLE
No -vme ~ --validation-max-exs in the docs

### ISSUE THREAD

**Issue by vinnik-dmitry07** [facebookresearch/ParlAI#3491]
www.parl.ai/docs/cli_usage.html

As well as multitask-weights, betas, variant, lr-scheduler.

**Comment by stephenroller** [comment]
- Betas, variant, lr scheduler are agent specific options. They're listed on [this page](https://parl.ai/docs/agent_refs/transformer.html)
- MTW is was intentionally hidden previously, but reckon we should change that.

**Comment by stephenroller** [comment]
`-vme` is also a hidden option.  That's likely to stay -- I don't like encouraging its use. If you're using dynamic batching or distributed training, it usually is unstable as it does not compute the validation on the same set every single batch.
