### ISSUE TITLE
Want to know the example of finetuning  with blended skill talk

### ISSUE THREAD

**Issue by kazeto111** [facebookresearch/ParlAI#3492]
I want to fine-tune 2.7B model with blended skill talk, but I don't have much money and can't try and error while getting satisfying result.
Could you show me some examples of finetuning with blended skill talk?
I want to use them as the basis.

**Comment by stephenroller** [comment]
The blenderbot3b model we released has already been fine-tuned on BST.

In a few weeks we should release a few patches that should enable FTing on a single GPU.
