### ISSUE TITLE
Is the current Personachat Datasets generated by models?

### ISSUE THREAD

**Issue by connectlym** [facebookresearch/ParlAI#3504]
Hi, 

Sorry to disturb. My team is currently working on making the persona-chat dataset multilingual. Following the paper, we believe that all the chats in persona-chat are made by humans; however, the data format is a bit difficult to understand.
I noticed that you mentioned the format of each line in `train_none_original.txt` before as:

> the format of the 'none' file is as follows:
> 
> ```
> 1 x1<tab>y1<tab><tab>candidate1|candidate2|candidate3
> 2 x2<tab>y2<tab><tab>candidateA|candidateB|candidateC
> ...
> ```
and
> The candidates are not used at all by this model, but they can be used for comparing between ranking models (which models can rank highest the true response out of those twenty?). These are randomly selected other responses from the data.

_Originally posted by @alexholdenmiller in https://github.com/facebookresearch/ParlAI/issues/932#issuecomment-401186567_

So, are the `x1, y1, x2, y2, ...` made by humans (the Turkers) or made by models? 

This would help us a lot since we are looking for chats datasets only containing data made by humans.

Thanks!

**Comment by stephenroller** [comment]
Sorry this slipped under the radar.

The x1, y1, ... are all from humans. The candidates are also made by humans, but they correspond to random y's from other examples.

**Comment by connectlym** [comment]
> Sorry this slipped under the radar.
> 
> The x1, y1, ... are all from humans. The candidates are also made by humans, but they correspond to random y's from other examples.

Thank you so much for replying!
