### ISSUE TITLE
Can I use ParlAI In Japanese

### ISSUE THREAD

**Issue by Nathlmt** [facebookresearch/ParlAI#3512]
I want to build an open domain Chatbot using recipes like that [https://parl.ai/projects/recipes/](https://parl.ai/projects/recipes/)
but my chatbot in Japanese. So my question is Can I use ParlAI and do you have any idea for the data I need.
Thanks for your help

**Comment by stephenroller** [comment]
The code will have no problem dealing with the unicode characters, but our existing tokenizers are likely going to be terrible, and we don't have any Japanese datasets.  So if you can obtain a bunch of Japanese training data, it's probably good, but otherwise, mmm, unlikely to work?
