### ISSUE TITLE
Training chatbot with small data, the prediction will generate some answer not trust 

### ISSUE THREAD

**Issue by nguyentthai96** [facebookresearch/ParlAI#3531]
I have run source and training with my data (I only have tiny data). When I predict with a question similar training data to result okay, but question includes the new word, not in training dictionary as result answer generate random not trust (that I understanding). I want to custom, may-be edit beam search or any line code (I unknown); that it can generate an answer default example "I unknown question, you can contact supporter via phone number 0099001123."
Please, team and community can support me recommend I can dev ParlAI base adding function response answer default when bot AI cannot resolve trusty. I think some line code but I no idea, help new function.
Thanks to the team and the community's help.

**Comment by stephenroller** [comment]
"Trust of responses" is a difficult question.

You could possibly hack in something in `eval_step` or `_generate` to check the batch for the UNK token and then trigger a particular response that way, if it truly is an "unknown" word. In general, you could insert arbitrary rules there if you wanted.
