### ISSUE TITLE
Sample and rank decoding

### ISSUE THREAD

**Issue by frankplus** [facebookresearch/ParlAI#3540]
I would like to try the sample and rank decoding technique. It seems strange to me that it is not already available in the framework since it is one of the best performing and comparable to beam search (according to the papers [Recipes for building an open-domain chatbot](https://arxiv.org/pdf/2004.13637.pdf) and [Towards a Human-like Open-Domain Chatbot](https://arxiv.org/pdf/2001.09977.pdf))

**Comment by stephenroller** [comment]
You can use Meena-style sample and rank with

`--inference topk --topk 40 --beam-size 20`
