### ISSUE TITLE
Pretrained models usage, history, answers problems, questions

### ISSUE THREAD

**Issue by khomchyk** [facebookresearch/ParlAI#3547]
Hi, 

We've been using ParlAI for some time now and we love it. It has significantly improved our conversational engine as well as helped us to support new scenarios that we could not support before.

However, there are some things that we do not know how to fix or implement. We'd appreciate if you could share your thoughts on the below.

For the context, we are currently using the 90M model, but are aiming to transition to 3B model in the next month or so. Most of these issues we managed to reproduce in 3B model too. Maybe if we tested long enough we could reproduce all.

1. There are scenarios when the bot starts being very repetitive. For example, bot can start generating messages like "Ok ok okay okay ok ok ok okay okay okay".
2. There are scenarios when the bot decides to "leave". It starts from adding "Ok, was good talking to you, have a lovely day". And sometimes ends in an infinite cycle of replying "Ok bye bye bye. Goodbye bye bye okay bye goodbye" (see pt 1). It is hard to end that loop even if you try replying something completely different and start a completely different topic.
3. Given the same history and input, the bot replies the same message. For instance, if we start a conversation from "What do you do for living?" it always replies "I am a stay at home mom". Is it possible to add some kind of randomization seed to avoid that?
4. Is it possible to add a personality to the bot? If so, how many "facts" can be added? The example of what we'd like to add is:
    1. I am a 30 years old male. I live in San Francisco. I work in a big tech company. I have two kids, a boy and a girl. I love travelling.
5. How many tokens can be passed as the context/history? We noticed that in certain scenarios the bot repeats itself. For instance, it can ask "Do you have any hobbies?" multiple times during the conversation.

This is how we currently use ParlAI:

```python
from parlai.core.agents import create_agent


def _reload_history(model, history):
    model.history.reset()
    for message in history:
        message_from = message.get('from')
        text = message['text']
        if message_from == 'user':
            model.history.update_history({
                'episode_done': False,
                'text': text,
                'payload': None
            })
        else:
            model.history.add_reply(text)


class ParlaiController:
    def __init__(self):
        model_config = {
            'model': 'local_human',
            'model_file': 'zoo:blender/blender_90M/model'
        }
        self.model = create_agent(model_config)

    def process(self, text, history):
        _reload_history(self.model, history)
        self.model.observe({
            'episode_done': False,
            'text': text,
            'payload': None
        })
        return self.model.act()['text']

```

Would you be so kind to help us to understand these issues and to figure out if anything is wrong with our setup and model's usage?
Thanks!

**Comment by stephenroller** [comment]
I'd recommend using `create_agent_from_model_file` which handles some annoying internal bookkeeping slightly better

Once you do that, there might be a few options you can use:
- `create_agent_from_model_file('zoo:blender/blender_90M/model', {'beam_block_full_context': True})` may improve repetition aspects
- We support a blocklist of words. You COULD try adding "goodbye" and "bye" to the blocklist but no guarantees.
- You can add a prefix of strings to first turn of the history to provide a persona. The model is trained to expect 3-5 of these.
    ```
    your persona: I like dogs.
    your persona: I like to help people.
    your persona: I am a chatbot
    ```
- If you really want replies to be randomized (and I'm not sure I recommend it), you can use a different inference method. For example `--inference topk --beam-size 20 --topk 40` is the Meena generation method. `--inference topp --topp 0.9 --beam-size 1` is also popular. Adjust `--topk` and `--topp` to make it more or less bold
- The 3B model supports a history length of 128 tokens (about 6 turns), and the 90M supports a history of 512 tokens I think. We're working on improving this, but it's a limit of the tech right now.

**Comment by khomchyk** [comment]
Hey, @stephenroller ! Thank you for getting back to us. That was super helpful.

The blocklist worked really well for us. Not just for the "good bye" edge case, but also for the undesired scenarios. The persona worked insanely well too. So thank you for these tips once again!

In regard to the randomized replies:

- Could you please elaborate why you are not sure you would recommend it? Does it have any drawbacks?
- How do we pass `--inference topk --beam-size 20 --topk 40` to the `create_agent_from_model_file`? We tried via `opts` the way you passed `beam_block_full_context` in the example, but that did not work for us (or we just could not see the difference).

In regard to 3B vs 90M model – does the 90M model support a larger history (512 tokens in 90M vs 128 tokens in 3B model), or was it a type and you meant the other way around? 

We also came up with a few new questions and hope that you will be able to help us with those:

- Is there a way to control the minimum length of responses? We have a feeling that at the moment the model always tries to generate the longest possible response. Sometimes it repeats itself in the response. An example would be: `I am okay. I am doing well. I am good. Okay. I am doing well. How are you? You okay??`. Or maybe it can be controlled via something else.

Thank you for your support, Stephen. We appreciate that!

**Comment by stephenroller** [comment]
Sorry for dropping the ball.
- Randomized responses can bring out some really crazy things. It's not clear to me that it's a good choice
- you include `{'inference': 'topk', 'beam_size': 20, 'topk': 40}` as the second argument to create_agent_from_model_file
- Yes I believe the 90M supports 512 tokens.
- Yes, `--beam-min-length` I believe. That particular output shouldn't be happening though, with `--beam-block-ngram 3`

**Comment by khomchyk** [comment]
Thanks for the answers, @stephenroller!

I also have few additional questions:)

1. Does ParlAI always keep "your persona" in history, or do we have to trim history to accommodate "your persona"? Or, in other words, if we set up three "your persona:" configurations and then the history is 100 messages long, will ParlAI take "your persona" + the latest messages from the history, or will it just take latest messages from history and since "your persona" is 100 messages down the history, it won't include that?

2. Do I understand correctly that "your persona:" strings are part of ±128 tokens history and the more persona's configurations you have, the less space there is for the actual conversation history?

3. Is there a way to provide "partner's persona" so that the model knows about the user it talks to? If so, does it have to be a message from the user with the text `partner's persona: I love sushi`, or does it have to be a message from the bot with the same text? Or any other way?

4. Do I understand correctly that the agent expects that the first message in history is from the user, and the model's and user's messages go in order one after another?(user_message - model_message - user_message - ...)?

**Comment by stephenroller** [comment]
1. No, they will fall out of the history. We've found this isn't necessarily a problem in our experience. But you can modify the History object to keep them in view fairly easily
2. That is correct _if_ you implement it so they stay in context.
3. It would require re-fine tuning the model. At least one of the convai2 teachers does provide this information.
4. Correct. In some places we get around this with a special message of `__SILENT__` for the first turn. In convai2, we just do turns with personas but no speaker. In practice, our bot never messages first.
