### ISSUE TITLE
No response when run chat_service.

### ISSUE THREAD

**Issue by khoatranrb** [facebookresearch/ParlAI#3551]
I try to run `python run.py --config-path parlai/chat_service/tasks/qa_data_collection/config.yml`  in `parlai/chat_service/services/terminal_chat` but it has no response. 

Then I stop it with Ctrl+C and received this:

![](https://i.imgur.com/AgpZ0OU.png)

Any idea to fix it?

**Comment by stephenroller** [comment]
Were you able to resolve this? Do you mind sharing what you found?

**Comment by khoatranrb** [comment]
> Were you able to resolve this? Do you mind sharing what you found?

Hm, I have a misunderstanding. When I run `run.py`, it just start the websocket. Then, I run `client.py` to test the model.
