### ISSUE TITLE
a question about repetition dialogue unlikelihood model

### ISSUE THREAD

**Issue by rokslej** [facebookresearch/ParlAI#3554]
Thank you always for sharing your research results!! I am studying dialogue unlikelihood model now.
 However, I'm struggling to understand the implementation below, so can I ask you a question about this?
it is from /projects/dialogue_unlikelihood/agents.py 225 line.

mask = ((1 - self.opt['ctxt_beta']) * lrep_mask) + (
            self.opt['ctxt_beta'] * crep_mask
        )

i'm not sure why it is subtracting the lrep_mask values while adding the crep_mask values.
Shouldn't i add both of these values?

Thank you always!!
https://github.com/facebookresearch/ParlAI/blob/68850f8648a1b85fbda9a282f09f696a51149d24/projects/dialogue_unlikelihood/agents.py#L225

**Comment by stephenroller** [comment]
It's not subtracting either. ctxt_beta should be between 0 and 1, and it's just a weighting between these two parameters.

**Comment by rokslej** [comment]
Now i see!! Thank you for your answer :)
