### ISSUE TITLE
Training for "Engaging Image Captioning via Personality"

### ISSUE THREAD

**Issue by knguyennt** [facebookresearch/ParlAI#3563]
Hi.
First of all. Thank you Parlai for providing the model code and the pretrained weight of Transresnet from "Engaging Image Captioning via Personality".
I am trying to reproduce the result using the script provided in issue [2734](https://github.com/facebookresearch/ParlAI/issues/2734)
`python parlai/scripts/train_model.py --task personality_captions \
-m projects:personality_captions:transresnet --model-file my_model_file  \
--image-mode resnet152 --batchsize 500 \
--validation-every-n-epochs 1 --validation-patience 5 \
--validation-metric accuracy --validation-metric-mode max \
--hidden-dim 500 --num-layers-all 2 --num-layers-text-encoder 1 \
--num-layers-image-encoder 1 --learningrate 0.0005 \
--embedding-type fasttext_cc \
--attention-dropout 0.4 --relu-dropout 0.4 --dropout 0.4 \
--n-heads 6 --ffn-size 1200 --n-layers 4 \
--embedding-size 300 --variant aiayn \
--truncate 32 `
But I can't seem to reproduce the result. I use the same dataset downloaded when running train_model.
Could you give me any insight about why this might happen?
Thank you.

**Comment by stephenroller** [comment]
I'm sorry, this isn't enough information for us to help you.

**Comment by klshuster** [comment]
please note that we do not release the pre-trained transformer encoder used in our experiments, so you may only be able to match performance of row 6 in the table below (~40.6% accuracy on test)

![image](https://user-images.githubusercontent.com/8562788/116406403-9fd4fe80-a7fe-11eb-9391-cebc524b9927.png)

**Comment by knguyennt** [comment]
Hi @klshuster.
Thank you for your response, but when I try training the model from scratch the accuracy is 0 and show no sign of improvement
![image](https://user-images.githubusercontent.com/48175093/128635802-f358b8bc-7d9f-4a7b-aafe-69633fedf20e.png)
 Here is my config for model.dict.opt
`{
    "init_opt": null,
    "allow_missing_init_opts": false,
    "task": "personality_captions",
    "download_path": null,
    "loglevel": "info",
    "datatype": "train",
    "image_mode": "resnet152",
    "hide_labels": false,
    "multitask_weights": [
        1
    ],
    "batchsize": 16,
    "dynamic_batching": null,
    "verbose": false,
    "is_debug": false,
    "datapath": "/media/nguyenntk/DATA/projects/ParlAI/data",
    "model": "projects:personality_captions:transresnet",
    "model_file": "my_model_file",
    "init_model": null,
    "dict_class": "parlai.core.dict:DictionaryAgent",
    "evaltask": null,
    "eval_batchsize": null,
    "eval_dynamic_batching": null,
    "num_workers": 0,
    "display_examples": false,
    "num_epochs": -1,
    "max_train_time": -1,
    "max_train_steps": -1,
    "log_every_n_steps": 50,
    "validation_every_n_secs": -1,
    "validation_every_n_steps": -1,
    "save_every_n_secs": -1,
    "save_after_valid": false,
    "validation_every_n_epochs": 1.0,
    "validation_max_exs": -1,
    "short_final_eval": false,
    "validation_patience": 5,
    "validation_metric": "accuracy",
    "validation_metric_mode": "max",
    "validation_cutoff": 1.0,
    "load_from_checkpoint": true,
    "validation_share_agent": false,
    "metrics": "default",
    "aggregate_micro": false,
    "tensorboard_log": false,
    "tensorboard_logdir": null,
    "wandb_log": false,
    "wandb_name": null,
    "wandb_project": null,
    "wandb_entity": null,
    "dict_maxexs": -1,
    "dict_include_valid": false,
    "dict_include_test": false,
    "log_every_n_secs": -1,
    "image_size": 256,
    "image_cropsize": 224,
    "mutators": null,
    "include_personality": true,
    "include_image": true,
    "num_test_labels": 1,
    "yfcc_path": "data/yfcc_images/",
    "embedding_size": 300,
    "n_layers": 4,
    "ffn_size": 1200,
    "dropout": 0.4,
    "attention_dropout": 0.4,
    "relu_dropout": 0.4,
    "n_heads": 6,
    "learn_positional_embeddings": false,
    "embeddings_scale": true,
    "n_positions": 1000,
    "n_segments": 0,
    "variant": "aiayn",
    "activation": "relu",
    "output_scaling": 1.0,
    "share_word_embeddings": true,
    "n_encoder_layers": -1,
    "n_decoder_layers": -1,
    "model_parallel": false,
    "truncate": 32,
    "image_features_dim": 2048,
    "embedding_type": null,
    "load_encoder_from": null,
    "hidden_dim": 500,
    "num_layers_all": 2,
    "num_layers_text_encoder": 1,
    "num_layers_image_encoder": 1,
    "no_cuda": true,
    "learningrate": 0.0005,
    "additional_layer_dropout": 0.2,
    "freeze_patience": -1,
    "one_cand_set": false,
    "fixed_cands_path": null,
    "pretrained": false,
    "dict_file": "my_model_file.dict",
    "dict_initpath": null,
    "dict_language": "english",
    "dict_max_ngram_size": -1,
    "dict_minfreq": 0,
    "dict_maxtokens": -1,
    "dict_nulltoken": "__null__",
    "dict_starttoken": "__start__",
    "dict_endtoken": "__end__",
    "dict_unktoken": "__unk__",
    "dict_tokenizer": "re",
    "dict_lower": false,
    "bpe_debug": false,
    "dict_textfields": "text,labels",
    "bpe_vocab": null,
    "bpe_merge": null,
    "bpe_add_prefix_space": null,
    "bpe_dropout": null,
    "parlai_home": "/media/nguyenntk/DATA/projects/ParlAI",
    "override": {
        "ffn_size": 1200,
        "attention_dropout": 0.4,
        "relu_dropout": 0.4,
        "n_positions": 1000,
        "task": "personality_captions",
        "model_file": "my_model_file",
        "image_mode": "resnet152",
        "batchsize": 16,
        "validation_every_n_epochs": 1.0,
        "validation_patience": 5,
        "validation_metric_mode": "max",
        "hidden_dim": 500,
        "num_layers_all": 2,
        "num_layers_text_encoder": 1,
        "num_layers_image_encoder": 1,
        "learningrate": 0.0005,
        "dropout": 0.4,
        "n_heads": 6,
        "n_layers": 4,
        "embedding_size": 300,
        "variant": "aiayn",
        "truncate": 32,
        "yfcc_path": "data/yfcc_images/",
        "no_cuda": true
    },
    "starttime": "Aug02_14-34"
}`
I don't know what went wrong during the training process. Could you give me some insights about why this might happen and how to fix it?
Thank you.

**Comment by klshuster** [comment]
could you please share the command itself used for training?

**Comment by knguyennt** [comment]
Hi, this is the command i used:
```
python parlai/scripts/train_model.py --task personality_captions -m projects:personality_captions:transresnet
--model-file my_model_file --image-mode resnet152 --batchsize 32 --validation-every-n-epochs 1
--validation-patience 5 -validation-metric accuracy --validation-metric-mode max 
--hidden-dim 500 --num-layers-all 2 --num-layers-text-encoder 1 --num-layers-image-encoder 1 --learningrate 0.0005 
--attention-dropout 0.4 --relu-dropout 0.4 --dropout 0.4 --n-heads 6 --ffn-size 1200 --n-layers 4 --embedding-size 300 
--variant aiayn --truncate 32 --embedding-type fasttext_cc
```

**Comment by klshuster** [comment]
Hi, a couple things will most likely solve this issue:

1. You'll want to bump up the batchsize significantly, if you can. We generally trained with `--batchsize 500`
2. You'll want to set `--dict-file zoo:personality_captions/transresnet/model.dict

Hopefully that helps!

**Comment by knguyennt** [comment]
Thanks @klshuster , I tried your suggestions and I encounter some errors hope you can help me with it:
1. I try to bump up the batchsize to 128 which is the max capacity for my machine, and add `--dict-file zoo:personality_captions/transresnet/model.dict` but the accuracy while training still remain zero. Here is the result afte running 16 epochs:
```
/data/nguyenntk/anaconda3/envs/parlai/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3419: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/data/nguyenntk/anaconda3/envs/parlai/lib/python3.8/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
12:10:26 | time:4936s total_exs:2982400 total_steps:23300 epochs:15.97
            100  accuracy    bleu-4  exs      f1   loss
   all                  0 2.339e-12 6400 .002664 .03867
   hits@1 .0804

/data/nguyenntk/anaconda3/envs/parlai/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3419: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/data/nguyenntk/anaconda3/envs/parlai/lib/python3.8/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
12:10:34 | time:4944s total_exs:2988800 total_steps:23350 epochs:16.00
            100  accuracy    bleu-4  exs     f1   loss
   all                  0 2.291e-12 6400 .00288 .03903
   hits@1 .0766

/data/nguyenntk/anaconda3/envs/parlai/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3419: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/data/nguyenntk/anaconda3/envs/parlai/lib/python3.8/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
12:10:36 | time:4946s total_exs:2990080 total_steps:23360 epochs:16.01
            100  accuracy    bleu-4  exs     f1   loss
   all                  0 2.542e-12 1280 .00221 .03857
   hits@1 .0800

12:10:36 | running eval: valid
12:11:43 | eval completed in 66.86s
12:11:43 | valid:
           100  accuracy  bleu-4  exs    f1  hits@1  hits@10  hits@100  hits@5     loss  med_rank
   all            .08322  .07788 4999 .1323  .08323    .3900         1   .2631 -.008003        17
   hits@1    1
```
2. I did work around the code a little bit in order for it to run, I wonder if the changes I made might cause errors in training, here are the errors encounter while training, hope you can help me with it:
+ When downloading the yfcc-images using the script `parlai display_data -t personality_captions`, it keep asking to re-download the images eventhough the yfcc-path was given. My suspect is that because there are 55 errors image so it keep asking to re-downloaded the images. So i try changing `parlai/tasks/personality_captions/download_images.py` by commenting the download code and only keep the `build_data.mark_done(image_path, version)` after completing download the data
![image](https://user-images.githubusercontent.com/48175093/129139194-19c1ba80-dc62-44b6-ad6b-6fa63f462dcb.png)
+ when running the training script, when not specify `--no-cuda`, the error `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0!` was raised, the error occur at this line https://github.com/facebookresearch/ParlAI/blob/70ee4a2c63008774fc9e66a8392847554920a14d/projects/personality_captions/transresnet/modules.py#L293 here the complete error log:
```
/media/nguyenntk/DATA/anaconda3/envs/parlai/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448234945/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "parlai/scripts/train_model.py", line 940, in <module>
    TrainModel.main()
  File "/media/nguyenntk/DATA/projects/ParlAI/parlai/core/script.py", line 129, in main
    return cls._run_args(None)
  File "/media/nguyenntk/DATA/projects/ParlAI/parlai/core/script.py", line 101, in _run_args
    return cls._run_from_parser_and_opt(opt, parser)
  File "/media/nguyenntk/DATA/projects/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "parlai/scripts/train_model.py", line 936, in run
    return self.train_loop.train()
  File "parlai/scripts/train_model.py", line 900, in train
    for _train_log in self.train_steps():
  File "parlai/scripts/train_model.py", line 803, in train_steps
    world.parley()
  File "/media/nguyenntk/DATA/projects/ParlAI/parlai/core/worlds.py", line 865, in parley
    batch_act = self.batch_act(agent_idx, batch_observations[agent_idx])
  File "/media/nguyenntk/DATA/projects/ParlAI/parlai/core/worlds.py", line 833, in batch_act
    batch_actions = a.batch_act(batch_observation)
  File "/media/nguyenntk/DATA/projects/ParlAI/projects/personality_captions/transresnet/transresnet.py", line 322, in batch_act
    loss, num_correct, num_examples = self.train_step(
  File "/media/nguyenntk/DATA/projects/ParlAI/projects/personality_captions/transresnet/transresnet.py", line 233, in train_step
    loss, num_correct, num_examples = self.model.train_batch(
  File "/media/nguyenntk/DATA/projects/ParlAI/projects/personality_captions/transresnet/modules.py", line 322, in train_batch
    context_encoded, captions_encoded = self.forward(
  File "/media/nguyenntk/DATA/projects/ParlAI/projects/personality_captions/transresnet/modules.py", line 245, in forward
    img_encoded = self.forward_image(image_features)
  File "/media/nguyenntk/DATA/projects/ParlAI/projects/personality_captions/transresnet/modules.py", line 296, in forward_image
    stacked = torch.stack(image_features)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument tensors in method wrapper__cat)
```
It seem the image_features was a mixed tensors of cuda and cpu so it is not on the same device, i work around it by manually setting image_features tensors to cuda
![image](https://user-images.githubusercontent.com/48175093/129141089-7581fda6-43f9-429d-b48a-0cbaaedd2a26.png)
+ When loading fasttext embeddings by using `--embedding-type fasttext_cc`, the project get stuck at loading at line https://github.com/facebookresearch/ParlAI/blob/70ee4a2c63008774fc9e66a8392847554920a14d/projects/personality_captions/transresnet/modules.py#L579 . I try debugging and it seem the condition `if word in pretrained` is the problem, seem like it checking a string format with vecors, so I try changing the condition to check if the vecor of the word is 0 in order for it to run
![image](https://user-images.githubusercontent.com/48175093/129141994-89c77810-cac9-4f53-acfd-7b5536805760.png)
I dont know if any of these might affect the training process. Hope you can help me.
Thanks

**Comment by klshuster** [comment]
> I try to bump up the batchsize to 128 which is the max capacity for my machine, and add --dict-file zoo:personality_captions/transresnet/model.dict but the accuracy while training still remain zero. Here is the result:

I would pay more attention to the `hits@1` metric during training, which measures recall@1/100. It looks like we're seeing some progress there

 > by commenting the download code and only keep the build_data.mark_done(image_path, version) after completing download the data

This is an appropriate fix

> when running the training script, when not specify --no-cuda, the error RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! was raised, the error occur at this line

Hmm, how often is this occurring? This would most likely be the case if blank image features are being fed for examples (e.g. the 55 images you mentioned could not download). If this is frequent, there may have been something wrong in the image featurization process.

> loading fasttext embeddings

Yes, I noticed this too. An appropriate fix I found is: 

```python
def load_fasttext_embeddings(dic, embedding_dim, datapath):
    """
    Load weights from fasttext_cc and put them in embeddings.weights.
    """
    print('Initializing embeddings from fasttext_cc')
    from parlai.zoo.fasttext_cc_vectors.build import download

    pretrained = download(datapath)
    print(
        'Done Loading vectors from fasttext. {} embeddings loaded.'.format(
            len(pretrained)
        )
    )
    pretrained_words = set(pretrained.stoi)
    used = 0
    res = nn.Embedding(len(dic), embedding_dim)
    words = list(dic.tok2ind.keys())
    for i in range(len(words)):
        word = words[i]
        index = dic.tok2ind[word]
        if word in pretrained_words and res.weight.data.shape[0] > index:
            res.weight.data[index] = pretrained[word]
            used += 1
    print('{} have been initialized on pretrained over {} words'.format(used, len(dic)))
    return res
```

**Comment by knguyennt** [comment]
Thanks, @klshuster. 
The error
>when running the training script, when not specify --no-cuda, the error RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu, and cuda:0! was raised
occur everytime I run the training script without specifying --no-cuda. 
>This would most likely be the case if blank image features are being fed for examples (e.g. the 55 images you mentioned could not download)
I don't think this is the case cause before training the dataset, I did some preprocessing to remove empty images from the dataset
I checked the image features and it seemed some of the features went to cuda and others went into cpu. 
> there may have been something wrong in the image featurization process
Do you know if there is any workaround for this problem?
Thank you.

**Comment by klshuster** [comment]
> When I checked the image features and it seemed some of the features went to cuda and others went into cpu.

Are you able to identify which are going to cuda and which to cpu? that doesn't really make sense to me

> RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)

I'm not sure what this issue is, if you're running pytorch 1.9 you may need to upgrade your cuda version?
