### ISSUE TITLE
Websocket worker does not delete on disconnect

### ISSUE THREAD

**Issue by jakeane** [facebookresearch/ParlAI#3568]
**Bug description**
As a part of the config for running a chatbot websocket, there is a specification for `max_workers`. That is, "How many max human connections you plan on supporting for your service" per the [docs](https://parl.ai/docs/tutorial_chat_service.html#overview). However, when I run the websocket server via `parlai/chat_service/services/websocket/run.py`, it seems that the server does not keep track of active connections with respect to the `max_workers` parameter. Instead, it seems that `max_workers` specifies the *total* number of 'human connection' supported over the lifespan the the server, even if the connections are long dead.

**Reproduction steps**

1. Run `python3 parlai/chat_service/services/websocket/run.py --config-path <path>`. Ensure that the parameter `max_workers` is set to 2 in the config, the rest of the parameters can be default.
2. Open 2 websocket client connections, I used Google Chrome's "Simple Web Socket Client" to do so. After connecting, send `{"text": "hi"}` from each client, thus establishing a human connection. Both messages will receive an onboarding response from the server.
3. Disconnect one of the clients, I pressed the "close" button on the client GUI.
4. Connect a new websocket client and send `{"text": "hi"}`. In this case, there will be no response from the server, even though there are only 2 active connections.

**Expected behavior**
When connecting the last client in step 4, an onboarding message from the server was expected, but there was no response at all.

**Logs**

```
[I 210401 16:41:19 web:2239] 101 GET /websocket (::1) 1.44ms
[I 210401 16:41:19 sockets:40] Opened new socket from ip: ::1
[I 210401 16:41:19 sockets:41] Current subscribers: {'d4383ef8-66c9-416c-89e1-5dd998570aa0': <parlai.chat_service.services.websocket.sockets.MessageSocketHandler object at 0x147b50d30>}
[I 210401 16:41:26 sockets:60] websocket message from client: {"text": "hi"}
[I 210401 16:41:26 agents:40] Sending new message: {'id': 'Overworld', 'text': 'Welcome to the overworld for the ParlAI messenger chatbot demo. Please type "begin" to start, or "exit" to exit', 'quick_replies': ['begin', 'exit']}
[I 210401 16:41:31 web:2239] 101 GET /websocket (::1) 0.57ms
[I 210401 16:41:31 sockets:40] Opened new socket from ip: ::1
[I 210401 16:41:31 sockets:41] Current subscribers: {'d4383ef8-66c9-416c-89e1-5dd998570aa0': <parlai.chat_service.services.websocket.sockets.MessageSocketHandler object at 0x147b50d30>, '1e511ec1-90f6-4f01-9dc0-956b42495445': <parlai.chat_service.services.websocket.sockets.MessageSocketHandler object at 0x147b3dcd0>}
[I 210401 16:41:34 sockets:60] websocket message from client: {"text": "hi"}
[I 210401 16:41:34 agents:40] Sending new message: {'id': 'Overworld', 'text': 'Welcome to the overworld for the ParlAI messenger chatbot demo. Please type "begin" to start, or "exit" to exit', 'quick_replies': ['begin', 'exit']}
[I 210401 16:41:39 web:2239] 101 GET /websocket (::1) 0.53ms
[I 210401 16:41:39 sockets:40] Opened new socket from ip: ::1
[I 210401 16:41:39 sockets:41] Current subscribers: {'d4383ef8-66c9-416c-89e1-5dd998570aa0': <parlai.chat_service.services.websocket.sockets.MessageSocketHandler object at 0x147b50d30>, '0728b71c-599c-48bd-99b6-ea8d4e756e40': <parlai.chat_service.services.websocket.sockets.MessageSocketHandler object at 0x147b481c0>}
[I 210401 16:41:41 sockets:60] websocket message from client: {"text": "hi"}
```
Notice how the last "websocket message from client" does not have a corresponding "Sending new message".

**Additional context**
This is a problem as I would have to restart the server periodically as it will not accept any new connections at a certain point. A cap on active connections make sense, but it seems that the websocket server is not managing disconnects well if at all. So, if I set an absurdly high `max_workers` parameter, there may be memory issues down the road as tons of dead connections are still being maintained.

**Comment by stephenroller** [comment]
@EricMichaelSmith @JackUrb

**Comment by JackUrb** [comment]
I feel like this was something @klshuster addressed for the terminal chat setup, but I'm not entirely sure. It's likely the same bug to some extent? Or another form of it.

**Comment by klshuster** [comment]
Yes, this was solved in #3457 (for issue #3451) for specifically terminal chat, so I imagine a similar fix would solve it for websockets

**Comment by jakeane** [comment]
Ah. Let me pull from master again, test this problem, and get back to you on this. The version I used may have been a bit stale. Thanks!

**Comment by stephenroller** [comment]
Thanks everyone
