### ISSUE TITLE
Agent not displaying episodes properly

### ISSUE THREAD

**Issue by kausik1998** [facebookresearch/ParlAI#3574]
Hi, I am new to ParlAI. I am trying to create a simple agent which would produce the reverse of a given word by shuffling the word multiple times until it reaches its goal. I am sharing my code. Can you please tell me where I am going wrong?
Thank you.

```python
#!/usr/bin/env python3

import os
from parlai.core.agents import Agent
from parlai.core.message import Message

import random


class utils():
    def calc_reward(word,answer):

        target = word[::-1]
        w = zip(answer,target)
        out = []

        # print("Letters in correct position are: \n")
        for i,j in w:
            if i == j:
                #print(i,'->',j)
                pass
            else:
                out.append(j)

                #print(out)
            if len(out) != 0:
                reward = -(len(out))
                #print("Reward accumulated so far is: ",reward)

        return reward



class ReverseAgent(Agent):
    def __init__(self,opt,shared=None):
        super().__init__(opt)
        self.id = 'Reverse'

    def act(self):
        reply = {}
        episodes=10
        reply['episode_done'] = False
        for episode in range(episodes):
            words = ["rabbit","apple","orange","branch","water","difficult","level"]
            given_word = random.choice(words)
            reply['id'] = self.getID()
            reply['reward'] = 0

            reply['text'] = ''.join(random.sample(given_word,len(given_word)))
            reply['labels'] = given_word[::-1]

            if reply['text'] == given_word[::-1]:
                reply['reward'] = reply['reward'] + 10
                reply['episode_done'] = True
            else:
                reply['reward'] = reply['reward']+ utils.calc_reward(given_word,reply['text'])

        reply['episode_done'] = True
        return Message(reply)

```

**Comment by stephenroller** [comment]
- I notice your definition of `calc_reward` is missing a `self` argument
- Your message you return from `act` needs to only contain the `text` field as its response (unless you're trying something more complex by combining it with other agents)
- If you do combine this with other agents, `labels` should be a list, not a single string
- for a 5 letter word, there are 5! = 120 ways the letters can be ordered (ignoring repeated letters), so the chance of a reversal is 1/120. So the probability that you'll find a correct shuffle in only 10 runs is 1 - (119/120)^10 = 8%. So the odds of you finding a correct reversal is quite low. Your for look probably needs to be a while loop.
- The loop also seems to not have a break in it, so even when you do find the correct reversal, your code continues to shuffle things.

Hope this helps.

**Comment by kausik1998** [comment]
Thank you for the response!
