### ISSUE TITLE
Human Evaluation and statistical significance

### ISSUE THREAD

**Issue by manzar96** [facebookresearch/ParlAI#3576]
Hello, 
I have recently conducted a human evaluation of a chatbot via a survey. I wonder how I can prove that the results are statistically significant.
More specifically, I compared the generated responses of two chatbots and calculated each one's win rate. Moreover, participants were asked to rate each model according to "relevance" and "fluency" using a scale ranging from 1 to 5.
According to some references (e.g. [DodecaDialogue paper](https://arxiv.org/pdf/1911.03768.pdf#page=9&zoom=100,402,185) ), they prove that the results are statistically significant using binomial testing.

How can I apply binomial testing in the aforementioned case?

I would like to kindly mention @stephenroller as he was one of the authors of  [DodecaDialogue](https://arxiv.org/pdf/1911.03768.pdf#page=9&zoom=100,402,185)  and [ACute-Eval](https://arxiv.org/pdf/1909.03087.pdf) papers, on which binomial testing was used for proving the statistical significance of the results on a very similar issue/case.

**Comment by stephenroller** [comment]
For ACUTE, you use a binomial test. Since you've collected Likert ratings (1-5), you should use a non-paired two tail t-test.

**Comment by manzar96** [comment]
Thank you for your answer.

Supposing that I use the non-paired two-tailed t-test method, I should define a null and an alternative hypothesis. Letting the null hypothesis be m_a==m_b and the alternative one be m_a!=m_b, will reject or accept the alternative hypothesis. However, the issue is to determine if those means are different or to determine if one is greater than the other? For determining the latter one, is it "accepted" to use the one-tail method?
