### ISSUE TITLE
How can I designate number of context turn?

### ISSUE THREAD

**Issue by tree-park** [facebookresearch/ParlAI#3589]
Thank you for your great project. I have a question about usage.    
When I use a polyencoder, how can I specify how many turns go into context?   

Thank you!

**Comment by stephenroller** [comment]
Most of our models have a maximum number of tokens they can fit in memory. our poly-encoders is 512 IIRC. There's also a `--history-size` option that can set a bound on the maximum number of turns, but inherently the number of tokens is the more common bottleneck.

**Comment by tree-park** [comment]
Thank you for your clear answer. so, if history-size make sample shorter than default maximum number, it cut by maximum number of turn. and even though history-size longer than 512 IIRC, it couldn't be changed.

That's what I understood. it is right?

**Comment by stephenroller** [comment]
Correct. The models have a maximum word limit, and that tends to be the bottleneck
