### ISSUE TITLE
Trouble to fine-tunning from parlai format dataset

### ISSUE THREAD

**Issue by tree-park** [facebookresearch/ParlAI#3595]
Hello geniuses, I always approciate to your projects.

## 1. Fail to create new task with parlai format dataset
It keep failing to create new task from parlai format dataset.
I followed this tutorial page(https://parl.ai/docs/tutorial_task.html). then I understood as I should
1. Quickstart: Adding a new dataset
2. FromFile Task Agent (https://github.com/facebookresearch/ParlAI/tree/master/parlai/tasks/fromfile)
    -python parlai/scripts/display_data.py -t fromfile:parlaiformat --fromfile_datapath /tmp/data.txt
    
but, it is nothing happened. **where is the new task? how can I find task just created?**  probably I am wrong.

## 2. Fine-tunning pretrained model with new dataset
Plus, I tried to train-model cmd line as this to fine-tunning pretrained model with my own parlai-format dataset, it doesn't work.
```console
!parlai train_model \
    --init-model zoo:pretrained_transformers/bi_model_huge_reddit/model \
    --batchsize 20 **-t fromfile:parlaiformat --fromfile_datapath /content/parlal_form.txt** \
    --model transformer/biencoder --eval-batchsize 6 \
    ...
```

Could you guid me to get out from trouble?
My ultimate goal is fine-tunning pretrained model with new data corpus.

Best regards,

**Comment by stephenroller** [comment]
The commands look correct to me, but I don't know what your file contains. If display data doesn't work, there may be a problem with your file.
