### ISSUE TITLE
How to reproduce the performance of Bi-encoder without using reddit pretrained model?

### ISSUE THREAD

**Issue by min942773** [facebookresearch/ParlAI#3618]
Hello, I try to reproduce the Bi-encoder model which is pretrained with Toronto books + wikipedia (Table4 in paper)
But I was only able to find the code train with pretrained with reddit model.
I want to reproduce the performance in the paper using model which is pretrained with toronto books and wikipedia.

Could you please help me reproduce the performance of the model Bi-encoder? That is very important for me to fellow the paper. Thank you so much!

This is the only code that I could find in parlai website
```
parlai train_model \
    --init-model zoo:pretrained_transformers/bi_model_huge_reddit/model \
    --batchsize 1 -t personachat \
    --model transformer/biencoder --eval-batchsize 1 \
    --warmup_updates 100 --lr-scheduler-patience 0 \
    --lr-scheduler-decay 0.4 -lr 5e-05 --data-parallel True \
    --history-size 20 --label-truncate 72 --text-truncate 360 \
    --num-epochs 10.0 --max_train_time 2000000 -veps 0.5 -vme 8000 \
    --validation-metric accuracy --validation-metric-mode max \
    --save-after-valid True --log_every_n_secs 20 --candidates batch \
    --dict-tokenizer bpe --dict-lower True --optimizer adamax \
    --output-scaling 0.06 \
     --variant xlm --reduction-type mean --share-encoders False \
     --learn-positional-embeddings True --n-layers 12 --n-heads 12 \
     --ffn-size 3072 --attention-dropout 0.1 --relu-dropout 0.0 --dropout 0.1 \
     --n-positions 1024 --embedding-size 768 --activation gelu \
     --embeddings-scale False --n-segments 2 --learn-embeddings True \
     --share-word-embeddings False --dict-endtoken __start__ --fp16 True \
     --model-file /home/minju/data/pl_to_pc/model_file/augment_reddit/model
```

**Comment by klshuster** [comment]
Hi there, you can simply change the `--init-model` argument to `zoo:pretrained_transformers/bi_model_huge_wikito/model`; all other hyperparameters stay the same.

Let me know if that works for you!

**Comment by klshuster** [comment]
i would also make sure you increase the `--batchsize`, as we train these models with in-batch negatives (higher batchsize = more negatives = generally better performance)

**Comment by min942773** [comment]
Thank you for your comments.
I changed `--init-model` and `--batchsize` like this.

`parlai train_model \
    --init-model zoo:pretrained_transformers/bi_model_huge_wikito/model \
    --batchsize 128 -t personachat \
    --model transformer/biencoder --eval-batchsize 8 \
    --warmup_updates 100 --lr-scheduler-patience 5 \
    --lr-scheduler-decay 0.4 -lr 5e-05 --data-parallel True \
    --history-size 20 --label-truncate 72 --text-truncate 360 \
    --num-epochs 5 --max_train_time 2000000 -veps 0.5 -vme 8000 \
    --validation-metric accuracy --validation-metric-mode max \
    --save-after-valid True --log_every_n_secs 20 --candidates batch \
    --dict-tokenizer bpe --dict-lower True --optimizer adamax \
    --output-scaling 0.06 \
     --variant xlm --reduction-type mean --share-encoders False \
     --learn-positional-embeddings True --n-layers 12 --n-heads 12 \
     --ffn-size 3072 --attention-dropout 0.1 --relu-dropout 0.0 --dropout 0.1 \
     --n-positions 1024 --embedding-size 768 --activation gelu \
     --embeddings-scale False --n-segments 2 --learn-embeddings True \
     --share-word-embeddings False --dict-endtoken __start__ --fp16 True \
     --model-file /home/minnju/workspace/persona/pl_to_pc/model_file/wiki/model \`

And training works well but evaluating in last step makes an error.
`RuntimeError: Error(s) in loading state_dict for TransformerMemNetModel:
size mismatch for embeddings.weight: copying a param with shape torch.Size([54944, 768]) from checkpoint, the shape in current model is torch.Size([13504, 768]).
        size mismatch for cand_embeddings.weight: copying a param with shape torch.Size([54944, 768]) from checkpoint, the shape in current model is torch.Size([13504, 768]).
        size mismatch for context_encoder.embeddings.weight: copying a param with shape torch.Size([54944, 768]) from checkpoint, the shape in current model is torch.Size([13504, 768]).
        size mismatch for cand_encoder.embeddings.weight: copying a param with shape torch.Size([54944, 768]) from checkpoint, the shape in current model is torch.Size([13504, 768]).
        size mismatch for memory_transformer.embeddings.weight: copying a param with shape torch.Size([54944, 768]) from checkpoint, the shape in current model is torch.Size([13504, 768]).`

I can't understand why this happens because validation worked well while training (like 0.5, 1.0, 1.5 epoch...).
I would be really grateful if you could answer this question.
Thank you.

**Comment by klshuster** [comment]
hi, this error occurs when ParlAI cannot locate the dictionary file, or has trouble loading the dict tokenizer.

if you try running `parlai eval_model --model-file /home/minnju/workspace/persona/pl_to_pc/model_file/wiki/model --task personachat` do you still get the same error?

**Comment by min942773** [comment]
Yes, I still get the same error when I try running `parlai eval_model --model-file /home/minnju/workspace/persona/pl_to_pc/model_file/wiki/model --task personachat`
![image](https://user-images.githubusercontent.com/41141885/116338016-0f0a1d00-a816-11eb-8b36-83a866a25863.png)

**Comment by klshuster** [comment]
hmm, try adding `--dict-tokenizer bpe --dict-file zoo:pretrained_transformers/bi_model_huge_wikito/model.dict`

**Comment by min942773** [comment]
I simply added .checkpoint to model-file and it works well. Thanks for your help!
`parlai eval_model --model-file /home/minnju/workspace/persona/pl_to_pc/model_file/wiki/model.checkpoint --task personachat`

**Comment by klshuster** [comment]
the `model.checkpoint` file is a copy of the model that is saved after every validation, while the `model` file is the model saved that achieved the best validation metric during training. you may just need to specify `--dict-file /home/minnju/workspace/persona/pl_to_pc/model_file/wiki/model.checkpoint.dict` while keeping `--model-file /home/minnju/workspace/persona/pl_to_pc/model_file/wiki/model`
