### ISSUE TITLE
Easiest way to train Q&A Bot

### ISSUE THREAD

**Issue by kahancock** [facebookresearch/ParlAI#3630]
RIPL is considering using ParlAI as a Q&A bot as we discussed with the FB team yesterday. We have pulled our current Q&A from existing sources and formatted it as outlined in "Quickstart: Adding a new dataset" here https://parl.ai/docs/tutorial_task.html#creating-a-new-task-the-more-complete-way. We've created a teacher using `ParlAIDialogTeacher` and have skipped the build as we are running files locally for now. We can successfully execute `parlai display_data --task ripl-bot` and see the Episode data. Trying to execute `parlai interactive --task ripl-bot` returns an error `ModuleNotFoundError: No module named 'parlai.agents.ripl-bot`. I've also tried to train the model and receive a similar error about a missing model.

I was able to execute this very long command but to be honest I'm not 100% sure if it's creating a model or not (based on this thread https://github.com/facebookresearch/ParlAI/issues/2632)

`python train_model.py -t fromfile:parlaiformat --fromfile_datapath /home/ubuntu/ripl_bot.txt -m transformer/generator --multitask-weights 1,3,3,3 --init-model zoo:tutorial_transformer_generator/model --dict-file zoo:tutorial_transformer_generator/model.dict --embedding-size 512 --n-layers 8 --ffn-size 2048 --dropout 0.1 --n-heads 16 --learn-positional-embeddings True --n-positions 512 --variant xlm --activation gelu --skip-generation True --fp16 True --text-truncate 512 --label-truncate 128 --dict-tokenizer bpe --dict-lower True -lr 1e-06 --optimizer adamax --lr-scheduler reduceonplateau --gradient-clip 0.1 -veps 0.25 --betas 0.9,0.999 --update-freq 1 --attention-dropout 0.0 --relu-dropout 0.0 --skip-generation True -vp 15 -stim 60 -vme 20000 -bs 16 -vmt ppl -vmm min --save-after-valid True --model-file /tmp/test_train_90M -bs 4`

As you have probably realized I'm lost at this point. What are the appropriate next steps to take to simply run blender bot Q&A against our dataset? Any & all direction is greatly apricated (& if I have gone in a horribly wrong direction please don't hesitate to tell me)!

**Comment by stephenroller** [comment]
- I don't think that task names can contain dashes. I would recommend naming the folder `ripl_bot` or `ripl` and calling it `class RiplTeacher` for the latter case.
- Yes, that is creating a generative model, trained on `ripl_bot.txt` data, and saving it to `/tmp/test_train_90M`. You can interact with that model with `parlai interactive -mf /tmp/test_train_90M`
