### ISSUE TITLE
Training Blenderbot for other languages

### ISSUE THREAD

**Issue by detuvoldo** [facebookresearch/ParlAI#3631]
Hi,

Thanks for providing a great platform for training conversational models. I briefly look at the usage and I see that we can fine-tune Blenderbot model. 

I want to ask if we can change the language model and reproduce Blenderbot for other languages, using our dataset in that language. For example, can we use a Korean language model (KoBERT, ...) and train Blenderbot on a Korean conversation dataset?

**Comment by stephenroller** [comment]
See [here](https://github.com/facebookresearch/ParlAI/discussions/3633) for previous discussion on the matter.
