### ISSUE TITLE
Seq2seq model

### ISSUE THREAD

**Issue by Hilal-Urun** [facebookresearch/ParlAI#3639]
Hi, I just used to seq2seq model in parlai/tasks/examples/ file and train model with custom dataset which is Turkish.  There was not any error while training. After the model file created I test the model but I can not take any answer from the model. What do you think about this problem?  @stephenroller

**Comment by stephenroller** [comment]
Maybe you need to turn off `--skip-generation`?

**Comment by Hilal-Urun** [comment]
okey I'm going to try now, thanks a lot

**Comment by Hilal-Urun** [comment]
It worked, thanks again @stephenroller
