### ISSUE TITLE
Failed to install parlai because of incompatible package version

### ISSUE THREAD

**Issue by 731935354** [facebookresearch/ParlAI#3645]
I tried to install parlai by `python setup.py develop`, during the installation process, an error message came out:
`error: docutils 0.17.1 is installed but docutils<0.17 is required by {'sphinx-rtd-theme'}`.

Then I tried to fix it manually by reinstalling the docutils 0.17.1 and reinstall a lower version. However when I run
`parlai display_data --task babi:task10k:1`, it reported some packages are missing. Is there any idea how to fix this?

Note: I could install parlai successfully last year (can't remember the exact time). I think the problem may result from the new feature in pip after October 2020.

**Comment by stephenroller** [comment]
Can you share an error message after you attempted the downgrade?

**Comment by 731935354** [comment]
Hi stephen, I have resolved the problem, which arises from my old-version pytorch (1.4.1). After upgrading to pytorch 1.8.0, the installation works fine. Thanks
