### ISSUE TITLE
Test after  training a BERT Classifier on the SNLI task

### ISSUE THREAD

**Issue by ruolanyang** [facebookresearch/ParlAI#3651]
Hi, i'm wondering how can i directly test the classifier after training. For example, input two utterances = ['i'm happy.', 'i'm sad.'], then ask the classifier to output the label.

**Comment by stephenroller** [comment]
```
$ parlai interactive -mf /path/to/model
Enter your message: Premise: A boy is jumping on skateboard in the middle of a red bridge.\nHypothesis: The boy is wearing safety equipment.
[Model will output here]
```

To evaluate on the full test set (tho I don't remember if SNLI has a hidden test set?)
`parlai eval_model -mf /path/to/model -t snli -dt test`
