### ISSUE TITLE
Connection to retrieval server is failed. when eval the transformeragent

### ISSUE THREAD

**Issue by xfysec** [facebookresearch/ParlAI#3654]
ConnectionRefusedError: [Errno 111] Connection refused
ValueError: Connection to retrieval server is failed.
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fe80e8366d8>: Failed to establish a new connection: [Errno 111] Connection refused

**Comment by stephenroller** [comment]
Wut? Lol no idea what's going on here

**Comment by xfysec** [comment]
from parlai.scripts.eval_model import eval_model, setup_args as base_setup_args


def setup_args(parser=None):
    parser = base_setup_args(parser)
    parser.set_defaults(
        task='convai2:self:no_cands',
        datatype='valid',
        hide_labels=False,
        dict_tokenizer='split',
        metrics='f1',
    )
    return parser


def eval_f1(opt, print_parser):
    report = eval_model(opt, print_parser)
    print('============================')
    print('FINAL F1: ' + str(report['f1']))
    return report


if __name__ == '__main__':
    parser = setup_args()
    parser.set_defaults(model='agent:TransformerAgent')
    opt = parser.parse_args()
    report = eval_f1(opt, parser)


Thanks for your response, the source code is here, it employ the eval_model in parlai.scripts. The result is shown below.
.......
.......
.......
[  replace_ngram: True ]
[  replace_repeat: True ]
[  sample: False ]
[  split_into_sentences: True ]
[  wild_mode: False ]
[ Current ParlAI commit: 8c79dac43882d61f08cdb98bb01ee1836420bb57 ]
HEAD http://localhost:9200/ [status:N/A request:0.000s]
Traceback (most recent call last):
  File "/home/winter/.conda/envs/torch37/lib/python3.7/site-packages/urllib3-1.25.11-py3.7.egg/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/winter/.conda/envs/torch37/lib/python3.7/site-packages/urllib3-1.25.11-py3.7.egg/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/winter/.conda/envs/torch37/lib/python3.7/site-packages/urllib3-1.25.11-py3.7.egg/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
.......

**Comment by stephenroller** [comment]
This is a bit confusing. Our code shouldn't be making any requests. You look like you're making a request to local host somewhere.

**Comment by stephenroller** [comment]
Seems like 9200 is commonly used for Elastic Search...

**Comment by xfysec** [comment]
ok, I got this, thanks again.
