### ISSUE TITLE
Help with training 1.4B distilled dialogue model on GPU

### ISSUE THREAD

**Issue by jakeane** [facebookresearch/ParlAI#3663]
Hi all,

Currently, I am trying to figure out how to utilize my college's GPU cluster to train the 1.4B parameter dialogue model. We have Tesla K80's, which have 11.4GB of size. As you may expect, this is not enough to utilize the GPUs, as the model is too big, and we get out-of-memory errors. However, your the paper you all wrote about these models details how you went about training these massive dialogue models. The models were "vertically sliced" and each slice was placed on their own GPU, or at least that is what I gathered. I am not sure how to set this up. My notion is to use `multiprocessing_train.py`, but I did not see an option on the docs to allow that. If I could get some pointers about how to go about this, that would be great!

**Comment by stephenroller** [comment]
Use --model-parallel true, along with the regular train script. If you have a slurm cluster, you can use multiple nodes with distributed_train.

**Comment by jakeane** [comment]
Awesome that worked. Thank you!
