### ISSUE TITLE
[BlendedSkillTalk] Plans on releasing the utterance classifier used in BlendedSkillTalk dataset?

### ISSUE THREAD

**Issue by skywalker023** [facebookresearch/ParlAI#3664]
Hi! 👋 
I read the BlendedSkillTalk dataset and found that there is a pretrained utterance classifier for {PersonaChat, EmpatheticDialogues, WizardOfWikipedia}.
I also found that the annotation was released, but the classifier wasn't. (https://github.com/facebookresearch/ParlAI/pull/3405/files)

According to this issue (https://github.com/facebookresearch/ParlAI/issues/3338), releasing the pretrained classifier or at least releasing the training command isn't that hard.
So I am wondering if there is a plan for doing so..?

I am always appreciating your awesome job on developing the framework!
Thank you!

**Comment by EricMichaelSmith** [comment]
Hi - the code for training the utterance classifier is very old by this point, and there's currently no bandwidth to fix it up, but I'm happy to provide it as-is upon request if anyone is interested in trying to get it to work.

**Comment by skywalker023** [comment]
That would be awesome! Thank you!
