### ISSUE TITLE
Why this framework can’t find the relevant experimental model of the DECODE contextual contradiction data set

### ISSUE THREAD

**Issue by ahf876828330** [facebookresearch/ParlAI#3665]
Thank you very much for the efforts of the author! I want to see the relevant test model code of the **DECODE** contextual contradiction data set, but I can’t find it in the framework. Is it not integrated into the framework?

**Comment by stephenroller** [comment]
https://github.com/facebookresearch/ParlAI/tree/master/projects/contradiction

I'm afraid that this is all that @easonnie has open sourced at this time.

**Comment by easonnie** [comment]
Hi @ahf876828330, I hope the code in https://github.com/facebookresearch/ParlAI/issues/3391 might help you.
