### ISSUE TITLE
Does parlai support task oriented dialogue like intent detection and slot extraction ?

### ISSUE THREAD

**Issue by robbine** [facebookresearch/ParlAI#3673]
I think task oriented agent needs to adopt an intent/slots representation in order to chat with human.
e.g. to book a plane ticket, an agent needs to ask date as well as departure/arrival city.
Does Parlai support this kind of task ? If so, a state tracker is often needed to keep track of sessions and turns.
I searched in docs and didn't find related topics or issues.

**Comment by stephenroller** [comment]
We're in the process of adding support and should release soon.
