### ISSUE TITLE
 How do we give an agent as a model for the browser chat?

### ISSUE THREAD

**Issue by SparshAgrawal1** [facebookresearch/ParlAI#3675]
Attached the pic of the issue that we are facing.
![Capture](https://user-images.githubusercontent.com/56772551/119803123-c9b43a80-befc-11eb-9022-995afe9a41c8.PNG)

**Comment by mojtaba-komeili** [comment]
Sorry for the delay. Have you tried installing the package mentioned at the end of the error message manually?
