### ISSUE TITLE
about the performance of BART FiD RAG in project hallucination

### ISSUE THREAD

**Issue by Vonderland** [facebookresearch/ParlAI#3687]
Hi!
I read the paper https://arxiv.org/abs/2104.07567 and have noticed that BART FiD RAG is superior on human evaluation (table 3 in the paper), especially on the metric "hallucination" and "consistency", compared with other models.
But I have used the checkpoint from https://github.com/facebookresearch/ParlAI/tree/master/projects/hallucination, the performance of BART FiD RAG is not as good as my expectation. And in the performance table from the readme of project hallucination, PPL of BART FiD RAG on exact index is 14.65, while it is 11.0 as declared in table 15 of the paper. Should I edit or change something to get the expected performance as shown in the paper?

**Comment by klshuster** [comment]
hi there! will definitely look into this on my end but, just to confirm, would you mind sharing the command you used to evaluate the model?

**Comment by Vonderland** [comment]
> hi there! will definitely look into this on my end but, just to confirm, would you mind sharing the command you used to evaluate the model?

The command I used to evaluate the BART FiD RAG is:
parlai eval_model  -t wizard_of_wikipedia:generator:random_split --datatype test -mf zoo:hallucination/bart_fid_rag/model --add-missing-turns all --compressed_indexer_nprobe 64

Using the command above, I can get the PPL 12.63, which is similar to the number (12.54) on github readme performance table. But, it is quite different from the PPL in the paper (11.0 in table 15)...

Thank you for your reply!!

**Comment by klshuster** [comment]
After some investigation, it looks like I uploaded the incorrect file for BART FiD RAG in the model zoo; will be uploading and putting out a patch shortly to address this. Thanks for flagging!

**Comment by klshuster** [comment]
If you pull and try again from master, you should be able to get performance more near that reported in the paper. the README table on the hallucination project page has also been updated to reflect this
