### ISSUE TITLE
Question on Gender Bias Controlled Training

### ISSUE THREAD

**Issue by gabrielle-lau** [facebookresearch/ParlAI#3689]
@emilydinan Thanks for your work on gender bias mitigation in the [paper](https://arxiv.org/pdf/2010.07079.pdf). I would like to clarify how the genderedness bins were used, whether they were used for:

1. training Blender 2.7B from scratch (section 3.4 and another [paper](https://arxiv.org/pdf/1911.03842.pdf)), 
2. finetuning a pre-trained Blender 2.7B model, or 
3. finetuning a finetuned "BST 2.7B" Blender model (section 6.5)? 

Thank you.

**Comment by gabrielle-lau** [comment]
For future reference, it's finetuning the pre-trained [Reddit 2.7B](https://parl.ai/docs/zoo.html#reddit-2-7b).

**Comment by stephenroller** [comment]
Thanks for leaving this for future searchers!
