### ISSUE TITLE
Another question about reproducing the performance of bi-encoders on the DSTC7 data

### ISSUE THREAD

**Issue by Doragd** [facebookresearch/ParlAI#3698]
Use this to open other questions or issues, and provide context here.
Hi Kurt, @klshuster, sorry to bother you.
Are the dstc7 results of the bi-encoder (R@1/100 dev: 56.5 test: 66.8) obtained by training on the augmented data?
If so, I would like to ask about the results of the bi-encoder when training on the original dstc7 data.

**Comment by klshuster** [comment]
Hi there, yes the results are obtained by training on the augmented data. We do not have results from training on the original data.

**Comment by Doragd** [comment]
Thanks for your kind and quick reply. I got it.
