### ISSUE TITLE
code or interface for the contradiction NLI

### ISSUE THREAD

**Issue by wizare** [facebookresearch/ParlAI#3705]
I notice your new project, i.e., ``I like fish 🐟, especially dolphins 🐬:∗ Addressing Contradictions in Dialogue Modeling`` in arxiv.

It is an interesting idea, Therefore, I want to evaluate whether the generated responses are contradicted with the conversation history. However, it seems that the NLI model I trained is not accurate enough. For example, the responses provided by ordinary Seq2Seq, can achieve 0.17 contradict score, which is far below than the score reported in your paper.

Can you provide the code or interface for the contradiction NLI.?

**Comment by stephenroller** [comment]
@easonnie

**Comment by wizare** [comment]
Your paper proposes two contradiction evaluation methods, i.e., ``Utterance-based`` and  ``Unstructured``.
As for the ``Unstructured`` method, my implementation was able to approach the score mentioned in the paper. However, I failed to reproduce the  ``Utterance-based``  method.

I think it is for the following reasons:
In the  ``Utterance-based``  method,  the number of positive classes will be several times more than the number of negative classes. Unbalanced number of samples leads to degradation of model performance。
