### ISSUE TITLE
"Building flattened data" super slow on ImageChat when fine-tuning MMB

### ISSUE THREAD

**Issue by ypc82** [facebookresearch/ParlAI#3706]
**Bug description**
I am finetuning the [multimodal blenderbot](https://github.com/facebookresearch/ParlAI/blob/master/parlai/zoo/multimodal_blenderbot/README.md) (MMB).
Building flattened data on other datasets including BST, ConvAI2, empatheticDialog, and WoW were pretty smooth, with the speed of around 12k ex/s, however, it's only about **1.2 ex/s** on the ImageChat dataset and would took nearly 90 hours to complete.
I'm not sure if there is anything wrong.

**Reproduction steps**
Run the [finetuning script](https://github.com/facebookresearch/ParlAI/blob/master/parlai/zoo/multimodal_blenderbot/README.md#fine-tuning) of MMB.

**Expected behavior**
I expect the data preprocessing step would take much less time.

**Logs**
Please paste the command line output:
It'll take 84hrs for the 356K ImageChat dataset:
![image](https://user-images.githubusercontent.com/11627300/121555733-d761d800-ca45-11eb-9799-828e0c84ede8.png)

But it only took 20s for the 74.1K WoW dataset:
![image](https://user-images.githubusercontent.com/11627300/121556374-6838b380-ca46-11eb-9422-d18946815b92.png)

Thank you.

**Comment by klshuster** [comment]
hi there, this is likely taking a while because the image extractor needs to run on each image; if you'd like, you can run something like `parlai extract_image_feature -t image_chat:Generation --image-mode faster_r_cnn_152_32x8d` to do this separately. once all the images are extracted, this flattening should be quicker

**Comment by ypc82** [comment]
I see. Thank you so much for your reply!
