### ISSUE TITLE
Reproducing BlendedSkillTalk Multi-task Two-stage model

### ISSUE THREAD

**Issue by min942773** [facebookresearch/ParlAI#3707]
Use this to open other questions or issues, and provide context here.
Hi!
I read the BlendedSkillTalk dataset and want to reproduce Multi-task Two-stage model in section 3.2.
Is it possible with Parlai command?
If so, could you please help me reproduce the Multi-task Two-stage model? 

Also, according to the issue (#3338), I am wondering if releasing the pretrained classifier or at least releasing the training command is possible.

I would be really grateful if you could answer this question.
Thank you.

**Comment by EricMichaelSmith** [comment]
Hi @min942773 ! Unfortunately the two-stage model is not in a state where it can be easily released, but if you give me your email address I'd be happy to send you the raw code to use it :)

**Comment by min942773** [comment]
Thank you so much!
My email adress is minnju@yonsei.ac.kr

Thank you for your help.

**Comment by EricMichaelSmith** [comment]
Great! Just sent you an email.
