### ISSUE TITLE
A Plan of Rating/Improving the Persona-chat Dataset

### ISSUE THREAD

**Issue by connectlym** [facebookresearch/ParlAI#3734]
Hi,

Thank you for publishing the Persona-chat dataset.
My team is currently working on a project based on the persona-chat dataset. 
According to our investigation on the test dataset, there are a certain number of cases where the utterances of a dialog are not smoothly connected. For example, the gap between horses and juice looks strange in this dialog:
```
person 1	hi want to get to know each other ?
person 2	yes we got to act quickly
person 1	i am going for a horse ride tomorrow . do you like horses ?
person 2	i never have juice , just water .
person 1	is that hard for you ? i love sugar
person 2	yes i do i work on the baby floor an i want no kids lol
person 1	i am looking forward to retirement
person 2	no it is easy especially being single an i like it
person 1	well i have some heath issues , maybe i will try it
person 2	i do get it i do
person 1	will water help my circulation . i have an achy leg
person 2	yes get on it now
person 1	i will thank you for the advice
person 2	anytime are you okay now ?
person 1	yeah . it does not hurt oo bad . i still ride
person 2	do you where do you go ?
```
(The above dialog is taking directly from the test dataset.)

As a result of investigating the first 11 dialogs of the test dataset, 4 dialogs were unnatural like this. 
My team is planning to have crowdsourcing workers to either rate or improve the quality of dialogs, but not sure whether you have already had similar plans or not. If you have any plans or suggestions, we are happy to discuss them together.
Again, thank you for publishing the dataset, it is way-out helpful and valuable in the NLP researches. 

We are looking forward to your reply.

**Comment by stephenroller** [comment]
We don't comment on ongoing research from our group. Your proposal sounds interesting and I encourage it.

**Comment by connectlym** [comment]
> We don't comment on ongoing research from our group. Your proposal sounds interesting and I encourage it.

Gotcha, I'm glad to hear from you about this!
I will close this issue for now and re-open it once we have done our jobs.
Thank you!

**Comment by VolantBoy** [comment]
I can't find the download link of the personal-chat dataset

**Comment by klshuster** [comment]
the parlai quick start should help you out with installing/using parlai: https://parl.ai/docs/tutorial_quick.html

once you've gone through that, you can use `parlai display_data -t personachat` to download and view the dataset
