### ISSUE TITLE
More hash func for "Hash Layers For Large Sparse Models"

### ISSUE THREAD

**Issue by YongtaoGe** [facebookresearch/ParlAI#3735]
In the paper, several hash functions are used to map tokens to expert modules. Could you please give me some suggestions on how to implement hash functions like bigram hash, previous token hash, or clustered hash?

I found only the **random hash function** is implemented in this codebase.
https://github.com/facebookresearch/ParlAI/blob/d02d864151923ed75483e456d5f300e841f390d2/projects/params_vs_compute/hash_ladder/hash_ladder.py#L169-L183

**Comment by stephenroller** [comment]
Clustered & dispersed hashes were computed offline by taking a baseline transformer and performing k-means on the tokens. We then stored cluster assignments to a text file and loaded them up. Balanced hash was also done by loading a text file, but we assigned things to buckets based on unigram frequencies.

I believe bigram hashes were computed with `hash = input[time] % buckets + (prime * input[time - 1]) % buckets` but I'd have to check with @jaseweston.
