### ISSUE TITLE
Issue in running eval script for wizards on wikipedia pre-trained agent

### ISSUE THREAD

**Issue by swatianand25** [facebookresearch/ParlAI#3755]
The script stops running after running ~50%.

Ran the following script after installing parlai module using pip

parlai eval_model -bs 64 -t wizard_of_wikipedia:generator:topic_split -mf models:wizard_of_wikipedia/end2end_generator/model

The colab pro environment has 27gb RAM and is GPU enabled.
The following is the output given before abruptly stopping

tcmalloc: large alloc 3227770880 bytes == 0x55d7efaf0000 @  0x7fe264f85001 0x7fe206e8754f 0x7fe206ed7b58 0x7fe206edae83 0x7fe206edb07b 0x7fe206f7c761 0x55d2c8e4ecc0 0x55d2c8e4ea50 0x55d2c8ec2be0 0x55d2c8ebd7ad 0x55d2c8e503ea 0x55d2c8ebe60e 0x55d2c8ebd7ad 0x55d2c8e503ea 0x55d2c8ebe60e 0x55d2c8e5030a 0x55d2c8ebe60e 0x55d2c8e5030a 0x55d2c8ebe60e 0x55d2c8e5030a 0x55d2c8ebe3b5 0x55d2c8e5030a 0x55d2c8ebe3b5 0x55d2c8e5030a 0x55d2c8ebe60e 0x55d2c8e5030a 0x55d2c8ec27f0 0x55d2c8e50561 0x55d2c8ebe3b5 0x55d2c8e5030a 0x55d2c8ebe3b5
^C

**Comment by stephenroller** [comment]
Looks like you ran out of RAM. Try lowering the batchsize.
