### ISSUE TITLE
Adding Taskmaster-3 data set

### ISSUE THREAD

**Issue by YovaKem** [facebookresearch/ParlAI#3758]
Is anyone working on adding [Taskmaster-3](https://github.com/google-research-datasets/Taskmaster/tree/master/TM-3-2020) (a.k.a TicketTalk) to ParlAI? If not, I'll give it a go.

**Comment by stephenroller** [comment]
We have an internal version that we hope to release soon, with some extra bells and whistles. But in the mean time, if you wish to add it, I'd happily accept. As I recall, it was possible to use the TM2 code almost verbatim.
