### ISSUE TITLE
Agent with two models

### ISSUE THREAD

**Issue by roholazandie** [facebookresearch/ParlAI#3762]
I want to create an Agent that basically combines two Agents, one is a template-based chatbot like Alice and another a TorchAgent which is Blender. I am contemplating this and how can this be done in one single Agent. The problem is when I am passing the arguments I can either choose ``model`` or ``model_file`` but not both.  What is the cleanest way to approach this problem without changing the base classes in Parlai?

**Comment by stephenroller** [comment]
I would suggest creating a novel agent that instantiates both of them inside of it. Something like:

```
class HybridAgent(Agent):
    def __init__(self, opt, shared=None):
        if shared is None:
            self.blenderbot = create_agent_from_model_file('zoo:blender/blender_3B/model')
            self.alice = create_agent_from_model_file('/path/to/your/alice/agent')
        else:
            self.blenderbot = shared['blenderbot']
            self.alice = shared['alice']

    def share(self):
        shared = super().share()
        shared['blenderbot'] = self.blenderbot
        shared['alice'] = self.alice

    def observe(self, obs):
        obs = super().observe(obs)
        obs = self.alice.observe(obs)
        obs = self.blenderbot.observe(obs)
        return obs

    def act(self):
        # use self.observation to determine which agent should answer
        # and then return either self.blenderbot.act()  or self.alice.act()
```

**Comment by roholazandie** [comment]
This is a great solution. Thanks. Just one more question: I have read the documentation but I am still not clear about the role of shared. Why do you use it?

**Comment by mojtaba-komeili** [comment]
As it was explained [here](https://parl.ai/docs/tutorial_worlds.html?highlight=clone#agent-sharing), the goal is keeping clones of agents that have access to shared resources, which helps in reducing redundancy. For example, in your case if you are going to instantiate two clones of your agent in one program. They don not need to each keep a copy of the heavy blenderbot model. If you clone your agent, parlai loads blenderbot only once, and then refers each of the clone to the one that was initially instantiated (see `if shared is None` in `__init__` above).

**Comment by roholazandie** [comment]
Perfect! that's exactly what I want for my application. Thanks for the nice explanation.
