### ISSUE TITLE
total_exs not defined for DrQA report

### ISSUE THREAD

**Issue by backpropper** [facebookresearch/ParlAI#377]
In the train_model file, there is no necessary condition for the 'total' argument to be present in the train_report. Currently, the training cannot be done for some user-defined num_epoch.
Quick fix would be to define the total argument for DrQA's report or add a condition in the train_model file.
```
python examples/train_model.py -m drqa -t babi:task10k:1 -bs 32 -e 50 -mf test
```
https://github.com/facebookresearch/ParlAI/blob/ef2491719ff69e81eabb7d23d1f6752da74df817/examples/train_model.py#L166

**Comment by alexholdenmiller** [comment]
changed to only display `time_left` when `total_exs > 0`
