### ISSUE TITLE
Is it a bug ?

### ISSUE THREAD

**Issue by robbine** [facebookresearch/ParlAI#3771]
https://github.com/facebookresearch/ParlAI/blob/dd773e983ff11f2bb29218ae149ccb426b5749ff/parlai/core/torch_agent.py#L353
Seems more reasonable to replace obs[self.field] with text
text = self._add_person_tokens(
                        text, self.p1_token, self.add_p1_after_newln
                    )

**Comment by mojtaba-komeili** [comment]
Could you explain with more details why you think so, please?

**Comment by robbine** [comment]
Sure. Let's say we have an observation as follows,
obs_labs = Message(
            {
                'text': '1111111\n2222222\n3333333\n44444444',
                'labels': ['Do.', 'Do not.'],
                'episode_done': True,
            }
        )
    kwargs['split_lines'] = True
    kwargs['add_p1_after_newln'] = True
    kwargs['person_tokens'] = True
After calling history.update_history(obs_labs, '000000000')
I print out history.get_history_str(), and it looks like this, which looks weird to repeat the whole query 4 times.
1111111
2222222
3333333
__p1__ 44444444
1111111
2222222
3333333
__p1__ 44444444
1111111
2222222
3333333
__p1__ 44444444
1111111
2222222
3333333
__p1__ 44444444000000000
It seems more reasonable to have a result like the following
__p1__ 1111111
__p1__ 2222222
__p1__ 3333333
__p1__ 44444444000000000
