### ISSUE TITLE
Parlai return always same answer 

### ISSUE THREAD

**Issue by ibrahimjelliti** [facebookresearch/ParlAI#3777]
Hello,

I am running parlAi with 90M model
Sometimes the model stuck and replay the same answer always like when I ask tell me a joke. 

How can tell the model to be more random?

**Comment by stephenroller** [comment]
You can use `--inference nucleus --topp 0.7`

**Comment by ibrahimjelliti** [comment]
I am running the blended_skill_talk, option for inference and topp are not available.
> python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_90M/model

**Comment by stephenroller** [comment]
```
$ python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_90M/model --inference nucleus --topp 0.7
14:09:23 | Overriding opt["inference"] to nucleus (previously: beam)
14:09:23 | Overriding opt["topp"] to 0.7 (previously: 0.9)
14:09:23 | Loading model with `--beam-block-full-context false`
14:09:23 | Using CUDA
14:09:23 | loading dictionary from /private/home/roller/working/parlai/data/models/blender/blender_90M/model.dict
14:09:23 | num words = 54944
14:09:23 | TransformerGenerator: full interactive mode on.
...
```

**Comment by ibrahimjelliti** [comment]
I could run the blended_skill_talk  without  a persona with `--include_personas=False `.
is there a way to run it without a context and in question answer format, the goal is to run it as a question answer bot, where user ask question and the model response with no prior context set.

**Comment by stephenroller** [comment]
Try `parlai interactive -mf zoo:blender/blender_90M/model --single-turn true`.
