### ISSUE TITLE
get each response from bot to store it

### ISSUE THREAD

**Issue by Munia-AK** [facebookresearch/ParlAI#3786]
I'm starting a chat with the the 90M Blender model and it's working fine
using this cmd command python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_90M/model
or even using interactive script

However I'm trying to access the bot's response in order to analyze its emotion. How can I get each response and store it somehow then continue with the chat? I believe the answer lies in the worlds.py script. Any help please!

**Comment by stephenroller** [comment]
interactive supports an `--outfile` argument which will write the conversations to disk on exit.

**Comment by Munia-AK** [comment]
@stephenroller thank you I already realized that but as far as I understood that works when finishing the conversation entirely and exiting then it stores the whole conversation .. what I need is to get each response while the conversation is still being held, before exit .. is it possible ?

**Comment by stephenroller** [comment]
Sure, just call world.get_acts()

**Comment by Munia-AK** [comment]
@stephenroller 
that worked thank you so much!!
