### ISSUE TITLE
how to export BlenderBot v1 Models ?

### ISSUE THREAD

**Issue by Adeel-Intizar** [facebookresearch/ParlAI#3809]
Hello, Thank you for your amazing work
I want to export the blenderbot model to use it outside the ParlAI, but i am unable to export, 
kindly help me with it,
Thank you

**Comment by Thierryonre** [comment]
I would also like to know how to do this

**Comment by pablogranolabar** [comment]
Use the HuggingFace BlenderBot 1 implementation.
