### ISSUE TITLE
pickle agent

### ISSUE THREAD

**Issue by take2make** [facebookresearch/ParlAI#3810]
I try to pickle agent with its own history and parameters, but when I try to pickle it I get the error.
```python
import pickle
from parlai.core.agents import create_agent_from_model_file

agent = create_agent_from_model_file(f"zoo:blender/blender_90M/model")
pickled_object = pickle.dumps(agent) # at this moment I get error
```
Error:
Can't pickle <class 'abc.TransformerGeneratorModel_Swappable'>: attribute lookup TransformerGeneratorModel_Swappable on abc failed.

Do you have any suggestions?

**Comment by Abdualml** [comment]
Rt

**Comment by Abdualml** [comment]
T

**Comment by klshuster** [comment]
what are you trying to accomplish by pickling it?

**Comment by take2make** [comment]
I try to save an agent with a specific state (history) so I could use it in the future.

**Comment by klshuster** [comment]
You can access the agent's history via the `agent.history` object; specifically, you can try calling:

- `agent.history.get_history_str()` --> returns a string version of the history
- `agent.history.get_history_vec()` --> returns a tokenized version of the history


these are both pickleable (python `str` and `list` objects respectively
