### ISSUE TITLE
Batch Generate Safe Utterances

### ISSUE THREAD

**Issue by ethanjperez** [facebookresearch/ParlAI#3820]
**Is your feature request related to a problem? Please describe.**
I can't seem to find an easy way to batch-generate from safe versions of the dialogue models like BST 2.7B (e.g., the behavior you get with [safe_interactive.py](https://github.com/facebookresearch/ParlAI/blob/master/parlai/scripts/safe_interactive.py)). If there's already a way to do this, I'd greatly appreciate a pointer (and it might be worth adding to the documentation somewhere).

**Describe the solution you'd like**
I think there are several possible solutions:
1. Have [eval_model.py](https://github.com/facebookresearch/ParlAI/blob/master/parlai/scripts/eval_model.py) support safe generation (e.g., with extra command line flags)
2. Have a separate script for batch safe generation

Thanks for providing all of these helpful resources and open-source models for safe dialogue!

**Comment by ethanjperez** [comment]
@stephenroller told me to tag @jxmsML

**Comment by jxmsML** [comment]
Hi @ethanjperez , we may have some script that can apply as safety layer that can be used with any `TransformerGeneratorAgent` in  ParlAI during inference time, is that what you have in mind?

**Comment by ethanjperez** [comment]
Yes, that is what I have in mind - would you mind pointing me to the script?

**Comment by jxmsML** [comment]
Unfortunately it's not in this repo yet but I can migrate here.

**Comment by ethanjperez** [comment]
Okay, thanks - that would be very helpful!
