### ISSUE TITLE
Not able to run Multi-Modal BlenderBot from the downloaded weights

### ISSUE THREAD

**Issue by AndrewMpapalika** [facebookresearch/ParlAI#3822]
**Bug description**
I received the link and dowloaded MMB model weights. Many thanks to Eric and the team.

However, I have had a few problems trying to run the model. I tried a few things but I am still stuck.

If there is a different and correct way to run the model than the way I did below, then I will be very grateful to receive the correct instructions.

**Firstly, I run** 

export FINETUNED_MODEL_PATH=/home/gcp/parlai/data/models/blender/mmb_degenpos/model

and then

parlai safe_interactive \
-t blended_skill_talk \
-mf ${FINETUNED_MODEL_PATH} \
--model projects.multimodal_blenderbot.agents:BiasAgent \
--delimiter $'\n' \
--beam-block-ngram 3 \
--beam-context-block-ngram 3 \
--beam-min-length 20 \
--beam-size 10 \
--inference beam \
--model-parallel False \

and got the **error**:

OSError: File /checkpoint/kshuster/projects/multimodal_blender/sweep_7_Mon_Jul__6/61e/model.dict-vocab.json does not exist. --bpe-vocab must be pretrained.

**Secondly, I added** 

export BPE_VOCAB=/home/gcp/parlai/data/models/blender/mmb_degenpos/model.dict-vocab.json

then run

parlai safe_interactive \
-t blended_skill_talk \
-mf ${FINETUNED_MODEL_PATH} \
--model projects.multimodal_blenderbot.agents:BiasAgent \
--delimiter $'\n' \
--beam-block-ngram 3 \
--beam-context-block-ngram 3 \
--beam-min-length 20 \
--beam-size 10 \
--inference beam \
--bpe-vocab ${BPE_VOCAB} \
--model-parallel False \

and got the **error**

OSError: File /checkpoint/kshuster/projects/multimodal_blender/sweep_7_Mon_Jul__6/61e/model.dict-merges.txt does not exist. --bpe-merge must be pretrained.

**Thirdly**, I then downloaded the merges.txt file from Huggingface GPT2 tokeniser ([link](https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-merges.txt)), and passed the downloaded folder location with

export BPE_MERGE=/home/gcp/parlai/parlai/utils/model.dict-merges.txt

I then run 

parlai safe_interactive \
-t blended_skill_talk \
-mf ${FINETUNED_MODEL_PATH} \
--model projects.multimodal_blenderbot.agents:BiasAgent \
--delimiter $'\n' \
--beam-block-ngram 3 \
--beam-context-block-ngram 3 \
--beam-min-length 20 \
--beam-size 10 \
--inference beam \
--model-parallel False \
--bpe-vocab ${BPE_VOCAB} \
--bpe-merge ${BPE_MERGE} \

but I get the error

File "/home/gcp/parlai/parlai/utils/bpe.py", line 849, in __init__
self.tokenizer = ByteLevelBPETokenizer(
File "/root/anaconda3/envs/blender/lib/python3.8/site-packages/tokenizers/implement
ations/byte_level_bpe.py", line 36, in __init__
BPE(

Exception: Error while initializing BPE: expected value at line 1 column 1

Your help will be much appreciated.

**Comment by EricMichaelSmith** [comment]
Hi @AndrewMpapalika ! Can you try putting all of the files in the original zipped file (i.e. including `model.dict-merges.txt`) into the same directory, `/home/gcp/parlai/data/models/blender/mmb_degenpos/`? The model should run in safe interactive mode in that case

**Comment by AndrewMpapalika** [comment]
Thanks @EricMichaelSmith for the reply. The zipped file I accessed only had these files [model, model.opt, model.dict-vocab.json and model.dict.opt]. 

"model.dict-merges.txt" was not in there, and also
"model.dict" is not there

**Comment by AndrewMpapalika** [comment]
@EricMichaelSmith : I also moved "model.dict-merges.txt" to ..../blender/mmb_degenpos/, but no luck

I run

parlai safe_interactive 
-t blended_skill_talk 
-mf ${FINETUNED_MODEL_PATH} 
--model projects.multimodal_blenderbot.agents:BiasAgent 
--delimiter $'\n' 
--beam-block-ngram 3 
--beam-context-block-ngram 3 
--beam-min-length 20 
--beam-size 10 
--inference beam 
--model-parallel False \


and got the same error as before


OSError: File /checkpoint/kshuster/projects/multimodal_blender/sweep_7_Mon_Jul__6/61e/model.dict-vocab.json does not exist. --bpe-vocab must be pretrained.

**Comment by EricMichaelSmith** [comment]
Hi @AndrewMpapalika can you try unzipping again? I just tried unzipping again on my end, and I can see all 5 files

**Comment by AndrewMpapalika** [comment]
Great! It is now working like a charm. The latest download had all the 6 files. I don't know how the previous one didn't, maybe there was an interruption during the downloading process. Many thanks @EricMichaelSmith for taking the time to resolve my issue quickly, and thanks to the MMB team.
