### ISSUE TITLE
ParlAI colab tutorial has a bug at add_cmdline_args function

### ISSUE THREAD

**Issue by tkaratekin** [facebookresearch/ParlAI#3826]
I am going through the main parlAI tutorial with the colab link. I reach the part on implementing a very simple agent without errors. Here it gives an error , which is suggested to be resolved by following the updated code at: 
https://github.com/facebookresearch/ParlAI/pull/3328

However, when I replace the code with the one from the suggested pull request, then I get the error that 'Optional' is not defined.

I think the tutorial should ask for such code replacement in the first place, but even with the suggested code replacement, a new error arises where part of the the newly added 3rd argument is not defined.

**Reproduction steps**
Just run the tutorial upto the cell where a simple agent is expected to be created.

**Expected behavior**
The tutorial should run without errors on google colab, but even with the suggested code replacement from the 

**Logs**
Please paste the command line output:
TypeError: add_cmdline_args() takes 2 positional arguments but 3 were given

The above exception was the direct cause of the following exception:
TypeError: Agent 'hello' appears to have signature add_cmdline_args(argparser) but we have updated the signature to add_cmdline_args(argparser, partial_opt). For details, see https://github.com/facebookresearch/ParlAI/pull/3328.
```
Output goes here
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by stephenroller** [comment]
Thanks for reporting
