### ISSUE TITLE
Download link for raw file of DECODE dataset is not available.

### ISSUE THREAD

**Issue by ddehun** [facebookresearch/ParlAI#3827]
Hi. The link for DECODE dataset is not available. The project and dataset links are below.

[Project Link]
https://github.com/facebookresearch/ParlAI/blob/master/projects/contradiction/download_with_raw_format.md

[Dataset link with raw format]
https://sharenlpfile-01.s3.amazonaws.com/data/decode_v0.1.zip

Thank you!

**Comment by asivokon** [comment]
This was fixed in https://github.com/facebookresearch/ParlAI/pull/3878

The new link is http://parl.ai/downloads/decode/decode_v0.1.zip

**Comment by ddehun** [comment]
Thanks!
