### ISSUE TITLE
[Question]: model management in BatchWorld scenario

### ISSUE THREAD

**Issue by aleSuglia** [facebookresearch/ParlAI#384]
Hello,

I'm trying to train a custom Seq2Seq agent that I have created for a custom Task that I have implemented from scratch. Following the original Seq2Seq implementation I have seen that when the parameter `shared`is not None, the model initialization is completely skipped. 

My question is: how are the agents created after the first (for which `shared` is None) able to get the previously defined instance of the model if it is not shared? At the moment, I am having some problem in understanding this concept because for me seems really counterintuitive. For instance, if I try to debug the code the first time the model is correctly initialized because the `shared` parameter is None, but the second time it is initialized so the if branch is executed and the model member of the class it is not initialized (see https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/seq2seq/seq2seq.py#L142). Is there another way thanks to you are able to share this information? 

Thank you for your answer!

Best,
Alessandro Suglia

**Comment by alexholdenmiller** [comment]
Hi Alessandro!

The way the batchworld is initialized is followed:
- first, a normal world is created (of whatever type is default for the task, probably DialogPartnerWorld), with a teacher and an agent initialized inside it as usual. This is all the same as when batchsize is set to 1.
- then, for every batch row, a shared instance is created. that is, with `-bs 32`, we have 32 "shared" copies of the worlds and agents. For the DialogPartnerWorld, the worlds aren't any different, but the inner agents might be
- for the seq2seq model, we only want one instance of all its parameters--we don't want to push 32 models into RAM / the GPU. so for the shared instances, we don't initialize nearly anything. the shared instances will only have their `__init__` and `observe` functions called, if the class implements the `batch_act` function. This way, each of those shared instances can keep track of their batch row's local information--e.g., the previous utterances in the episode. Those observations will be collected back through the batchworld, and delivered to the original instance's batch_act method.

Hopefully that helps, let me know if you have any other questions!

**Comment by jaseweston** [comment]
perhaps this should be clearly explained somewhere in tutorials (or is it
already) so we can just link to it also?

**Comment by aleSuglia** [comment]
Thank you for your answer. 

So if I have correctly understood, the *batch_act* method directly uses the model initialized for the first agent?  

Moreover, what will be the observations object at each turn? Will it be a single utterance or it will be the batch of utterances from which I need to extract the specific example for the current agent? It would be great if you can provide a simple visual explanation of the process!

Thank you again for your support!

Best,
Alessandro

**Comment by alexholdenmiller** [comment]
@jaseweston you're right

@aleSuglia the first agent instance is the one for whom batch_act is called--it's also the only one which receives "None" for the `shared` parameter, so this is why the other agents in ParlAI use this field to decide whether to create the whole model. `batch_act` receives a `list` of `dict` objects in the `observations` parameter.

The shared instances (the ones which receive a dict in the `shared` argument) each have their `observe` method called. Whatever `observe` returns (which can include logic remembering past utterances, as the example models in parlai do) gets concatenated into a `list`, which is the `observations` argument that `batch_act` receives.

**Comment by stephenroller** [comment]
Closing, as this seems resolved, and is outdated given `TorchAgent` these days.
