### ISSUE TITLE
blenderbot2 module not found 

### ISSUE THREAD

**Issue by Jkintree2** [facebookresearch/ParlAI#3847]
**Bug description**
I get a module not found error at colab when I run
Interactive.main(
    model_file='zoo:blenderbot2/blenderbot2_400M/model'
)
 
 
**Reproduction steps**
See above

**Expected behavior**
Expect to interact with blenderbot2_400M the way I can with other zoo models.

**Logs**

ModuleNotFoundError                       Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/parlai/core/build_data.py in modelzoo_path(datapath, path)
    489         try:
--> 490             my_module = importlib.import_module(module_name)
    491             my_module.download(datapath)
 
24 frames

ModuleNotFoundError: No module named 'parlai.zoo.blenderbot2'
 

```
Output goes here
```

**Additional context**
@klshuster

**Comment by klshuster** [comment]
Hi @Jkintree2, depending on how you've installed ParlAI, there are two fixes here:

1. *Installed via pip*: we recently (earlier today) put out a new release for ParlAI (v 1.4.0), so I'd go ahead and upgrade your pip install
2. *Installed from source* Simply pull from master and you should be good to go!

Let me know if you have any other questions!

**Comment by Jkintree2** [comment]
It looked like reinstalling parlai at colab with pip fixed it, the tgz downloaded, but then gave the same error message. 

21:36:56 | building data: /usr/local/lib/python3.7/dist-packages/data/models/blenderbot2/blenderbot2_400M/model.tgz
21:36:56 | Downloading http://parl.ai/downloads/_models/blenderbot2/blenderbot2_400M/model.tgz to /usr/local/lib/python3.7/dist-packages/data/models/blenderbot2/blenderbot2_400M/model.tgz
Downloading model.tgz: 100%|██████████| 2.42G/2.42G [00:54<00:00, 44.4MB/s]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-4aa94939756d> in <module>()
----> 1 Interactive.main(model_file='zoo:blenderbot2/blenderbot2_400M/model')

18 frames
/usr/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'projects.blenderbot2'

**Comment by Jkintree2** [comment]
Sorry. The original error message was ModuleNotFoundError: No module named 'parlai.zoo.blenderbot2'

Now the error mess is ModuleNotFoundError: No module named 'projects.blenderbot2'

**Comment by Jkintree2** [comment]
The tgz file downloaded this time, but now I get an error message,
ModuleNotFoundError:
No module named 'projects.blenderbot2'

I posted this in the issue at github.

John

**Comment by hitchingsh** [comment]
I get the same error whether I install with pip install or or git clone:

git clone https://github.com/facebookresearch/ParlAI.git ./ParlAI

**Comment by klshuster** [comment]
Ahh yes this is an issue on our end; will try to put up a patch shortly

**Comment by hitchingsh** [comment]
Thanks!

**Comment by klshuster** [comment]
The fix is in for cloning from source (make sure to run `python setup.py develop` after pulling from master); I will update here when it makes it into a pip release

**Comment by agilebean** [comment]
@klshuster i just followed your instructions but still get the ModuleNotFoundError.

Here's my stack:

```
rm -rf Parlai
git clone https://github.com/facebookresearch/ParlAI.git
cd ParlAI/
python setup.py develop
cd ParlAI && python parlai/chat_service/services/websocket/run.py --config-path parlai/chat_service/tasks/chatbot/config.yml --port 10001
```
throws

```
    model_class = load_agent_module(opt_from_file['model'])
  File "/Users/chaehan/opt/miniconda3/envs/vb/lib/python3.7/site-packages/parlai/core/loader.py", line 188, in load_agent_module
    my_module = importlib.import_module(module_name)
  File "/Users/chaehan/opt/miniconda3/envs/vb/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'projects.blenderbot2'
```
Am I missing something?

config.yml:
  models:
```
#    blender_90M:
     blenderbot2:
      model: transformer/generator
#      model_file: zoo:blender/blender_400M/model
      model_file: zoo:blenderbot2/blenderbot2_400M/model
      interactive_mode: True
      no_cuda: True
additional_args:
  page_id: 1 # Configure Your Own Page
```

**Comment by agilebean** [comment]
i found out the solution thanks to @jwchoi09 :

1. in config.yml change these three lines:
```
  models:
    blenderbot2:
      model: projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent
      model_file: zoo:blenderbot2/blenderbot2_400M/model
```
2.  if you had previously installed by pip, first uninstall it:
`pip uninstall parlai`
Then remove ParlAI directory, then 
a) clone it again and 
b) `python setup.py develop`

**Comment by klshuster** [comment]
hi, yes the recent 1.4.1 release should handle this issue now! closing as it has been pushed, please upgrade to v1.4.1 and reopen  (or file a new issue) if there are further errors

**Comment by agilebean** [comment]
thanks, i can confirm the 1.4.1 release does not show the ModuleNotFoundError for `projects.blenderbot2`
