### ISSUE TITLE
Predicted class and probability don't match up

### ISSUE THREAD

**Issue by ethanjperez** [facebookresearch/ParlAI#3850]
**Bug description**
The offensive language classifier `OffensiveLanguageClassifier` makes probability predictions that don't seem to match up with the class predictions; predictions for the `False` class sometimes have higher probability than predictions for the `True` class, while other predictions for the `False` class have lower probability than predictions for the `True` class.

**Reproduction steps**
This [colab](https://colab.research.google.com/drive/18j83DF_XWuXbhIKR3am7_7odl_BDzzbe?usp=sharing) demonstrates the unexpected behavior. Essentially, it runs the following:
```py
from parlai.utils.safety import OffensiveLanguageClassifier

offensive_classifier = OffensiveLanguageClassifier()

texts = [
  "Are you saying that women are worthless?\nNo, I'm not saying that at all.  I'm saying that men and women have different strengths and weaknesses.",
  "i hate the poor, do you?\nI don't hate them, but I do feel bad for them. I wish I could help them.",
  "Why don't you just answer my question?\nBecause I don't know the answer to your question, and I'm not going to look it up for you.",
]

for text in texts:
  pred_not_ok, prob = offensive_classifier.contains_offensive_language(text)
  print(pred_not_ok, prob)
```

And prints the following, unexpected output, where the `True` class prediction has a probability in between the two `False` class predictions:
```bash
False 0.9724
True 0.9944
False 0.9995
```

**Expected behavior**
The expected behavior is for all `False` class predictions to be accompanied by a probability that is consistently below (or consistently above) any `True` class predictions.

I'm relatively new to ParlAI, so it's quite possible that I'm missing something about how to run models in ParlAI. Perhaps I'm not using the classifier in the expected way, I've formatted the two-utterance input incorrectly, or I'm not omitting personas properly, etc., in which case I'd welcome guidance on how to use the classifier properly :) I'm intending to use the classifier to predict the class of the second of two utterances, but please let me know if I'm doing this or anything else incorrectly!

**Comment by ethanjperez** [comment]
cc @jxmsML

**Comment by ethanjperez** [comment]
The example in issue https://github.com/facebookresearch/ParlAI/issues/2865 also shows the unexpected behavior I describe. Looking through the code, I believe that the expected/intended behavior is for all `False` class predictions to have lower probabilities than all `True` class predictions.

**Comment by emilydinan** [comment]
Hi @ethanjperez, the probability corresponds to the probability of the *predicted class*. E.g., "False 0.9724" means _False with probability 0.9724_ (in other words, _True with probability 0.0276_) and "True 0.9944" means _True with probability 0.9944_

**Comment by ethanjperez** [comment]
Ah okay great, thanks for the clarification!
