### ISSUE TITLE
No module named 'transformers'

### ISSUE THREAD

**Issue by Jkintree2** [facebookresearch/ParlAI#3853]
**Bug description**
Parlai in colab can now find blenderbot2.  Thanks. I am still unable to interact with it. A new ModuleNotFoundError is generated, see the following. 

Interactive.main(model_file='zoo:blenderbot2/blenderbot2_400M/model')

14:38:04 | building data: /usr/local/lib/python3.7/dist-packages/data/models/blenderbot2/blenderbot2_400M/model.tgz
14:38:04 | Downloading http://parl.ai/downloads/_models/blenderbot2/blenderbot2_400M/model.tgz to /usr/local/lib/python3.7/dist-packages/data/models/blenderbot2/blenderbot2_400M/model.tgz
Downloading model.tgz: 100%|██████████| 2.42G/2.42G [03:35<00:00, 11.2MB/s]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-4aa94939756d> in <module>()
----> 1 Interactive.main(model_file='zoo:blenderbot2/blenderbot2_400M/model')

17 frames
/usr/local/lib/python3.7/dist-packages/parlai/agents/hugging_face/t5.py in <module>()
     13 import torch
     14 from typing import Optional, Dict, Any, Tuple
---> 15 from transformers import T5ForConditionalGeneration
     16 
     17 try:

ModuleNotFoundError: No module named 'transformers'

**Reproduction steps**
See above.

**Expected behavior**
I expected to be able to interact with blenderbot2. 

**Logs**
Please paste the command line output:

```
Output goes here
```

**Additional context**
@klshuster

**Comment by klshuster** [comment]
please install transformers via `pip install transformers`

**Comment by Jkintree2** [comment]
Using '!pip install transformers' did the job. Thanks.
