### ISSUE TITLE
Unrelated response about the word "beginning"

### ISSUE THREAD

**Issue by agilebean** [facebookresearch/ParlAI#3854]
**Bug description**
Please enter a clear and concise description of what the bug is.

The response is completely unrelated to the conversational turn, and repeatedly contains a statement about the word 'beginning':

```
411580:  what is the name of a Toni Morrison novel
TRANSCRIPT_what is the name of a Toni Morrison novel
Response: The word "beginning" was first recorded in the 10th century. It means "to begin".
```

**Comment by klshuster** [comment]
hi, can you please paste the command you used?
