### ISSUE TITLE
I was wondering if there is a setting to preserve state between runs with blenderbot2.0

### ISSUE THREAD

**Issue by copypasteearth** [facebookresearch/ParlAI#3855]
Hi everyone:

I am trying out the blenderbot2.0 400M version and I can teach it its name, but i was wondering if there is a way to preserve the state between runs. I load it back up and it starts new and thinks its name is something else.

Thanks for your time

**Comment by klshuster** [comment]
hi, how are you interacting with the model? we don't support a native way to preserve state between runs, but there are ways to present conversation history to the model depending on how the model is being used

**Comment by copypasteearth** [comment]
Ahh ok. I was using parlai -interactive.

So you can load the previous conversation back into it?

**Comment by klshuster** [comment]
if you run `parlai interactive --outfile <outfile>`, it will save the conversations to a .jsonl file; you can then take the conversation from there and present to the model as a delimited string in the first message in the next interactive run (note that BB2's delimiter is a double space)

**Comment by copypasteearth** [comment]
Ok, thanks

**Comment by alelasantillan** [comment]
> if you run `parlai interactive --outfile <outfile>`, it will save the conversations to a .jsonl file; you can then take the conversation from there and present to the model as a delimited string in the first message in the next interactive run (note that BB2's delimiter is a double space)
@copypasteearth, you mean that we have to replace '\n' by double spaces to feed in the .jsonl contents to BB2?

**Comment by klshuster** [comment]
correct --> BB2 stores its conversation history as double-space-delimited; so, if you send over the conversation history as the first message, it's important to keep that delimiter so that BB2 can understand it is seeing separate utterances within a conversation

**Comment by DillFrescott** [comment]
@klshuster Im a bit confused by this. I don't have any \n breaks in my Json history and it's all one line. When I feed it back into BB2 it asks me what the hell I'm talking about and continues to change its name :/

**Comment by klshuster** [comment]
@DillFrescott could you please provide more details/context?

**Comment by DillFrescott** [comment]
@klshuster Sure! I am talking with Blenderbot2 using the 'parlai interactive' command.

Basically I was just wondering if there was a way to continue the conversation after closing the terminal. 

What I mean by this is for the AI to remember its name, and the topics we talked about.

I did figure out a way to retrain the model using the outfile and this seems to work, but I wasn't sure if it was a good approach.

-Cross

**Comment by klshuster** [comment]
if you're presenting the history as the first utterance, you'll also want to set `--memory-key full_text`, so that the model knows to extract memories from the incoming text

**Comment by DillFrescott** [comment]
@klshuster Got it. I appreciate the help.

Do I copy paste the history as the first message or is there a way to point it to the file?

Also, this is using the parlai save format correct? Or will it work with the json format as well?

**Comment by klshuster** [comment]
copy paste as first message; the save format doesn't matter, just how you present it in the first message
