### ISSUE TITLE
Correct way to format input to BAD classifier?

### ISSUE THREAD

**Issue by ethanjperez** [facebookresearch/ParlAI#3858]
What is the right way to format the input to the Bot Adversarial Dialogue classifiers? In particular, I'm interested in classifying the last of two utterances, where neither speaker has a persona. Below is my current best guess about how to do this classification:
```py
from parlai.utils.safety import OffensiveLanguageClassifier

clf = OffensiveLanguageClassifier(custom_model_file='zoo:bot_adversarial_dialogue/multi_turn/model')
clf.contains_offensive_language('Utterance 1\nUtterance 2')
```

In particular, I'm not sure about:
1. Whether the separator between utterances should be the newline character ('\n' as used above) or the literal backslash-n ('\\n' as in the BAD data files)
2. Whether I'm omitting persona information from the input in the way that the model expects
3. Whether I should do any preprocessing to the text, such as lowercasing
4. Anything else I might be doing incorrectly

Tagging BAD authors @jxmsML / @emilydinan who might know. Thanks so much for your help answering my questions!

**Comment by ethanjperez** [comment]
Great, thanks so much!

**Comment by ethanjperez** [comment]
Does the BAD classifier support new line characters within a single utterance? If so, should the new line characters be formatted as `\\n` (e.g., a single input utterance like `Hello!\\nMy name is Ethan.`)? I'm wondering because the delimiting character is `\n`.

**Comment by ethanjperez** [comment]
cc @jxmsML @emilydinan

**Comment by stephenroller** [comment]
Our models are trained with the delimiter between turns inserted via multiple calls to observe. A literal newline character can be included (iirc, via a true newline, not a \\n), but is probably taking the model slightly out of distribution already.

**Comment by stephenroller** [comment]
(To emphasize, byte level BPE tokenizers May or May not tokenize a newline as a singleton token, but our multi-turn logic *always* inserts a singleton token)
