### ISSUE TITLE
Colab error after downloading blenderbot2 

### ISSUE THREAD

**Issue by Jkintree2** [facebookresearch/ParlAI#3861]
**Bug description**
After downloading blenderbot2 at colab, further downloads are started until 
ValueError: Must provide a valid server for search

**Reproduction steps**

 !pip install parlai

!pip install transformers

from parlai.scripts.interactive import Interactive

Interactive.main(model_file='zoo:blenderbot2/blenderbot2_400M/model')

01:31:36 | building data: /usr/local/lib/python3.7/dist-packages/data/models/blenderbot2/blenderbot2_400M/model.tgz
01:31:36 | Downloading http://parl.ai/downloads/_models/blenderbot2/blenderbot2_400M/model.tgz to /usr/local/lib/python3.7/dist-packages/data/models/blenderbot2/blenderbot2_400M/model.tgz
Downloading model.tgz: 100%|██████████| 2.42G/2.42G [01:55<00:00, 21.0MB/s]
01:34:44 | Overriding opt["model_file"] to /usr/local/lib/python3.7/dist-packages/data/models/blenderbot2/blenderbot2_400M/model (previously: /checkpoint/kshuster/projects/knowledge_bot/kbot_memfix_sweep25_Fri_Jul__9/338/model.oss)
01:34:44 | loading dictionary from /usr/local/lib/python3.7/dist-packages/data/models/blenderbot2/blenderbot2_400M/model.dict
01:34:44 | num words = 50264
01:34:44 | Downloading https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/vocab.bpe to /usr/local/lib/python3.7/dist-packages/data/gpt2/vocab.bpe
Downloading vocab.bpe: 0.00B [00:00, ?B/s]01:34:45 | Downloading https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/encoder.json to /usr/local/lib/python3.7/dist-packages/data/gpt2/encoder.json
Downloading encoder.json: 0.00B [00:00, ?B/s]
01:34:46 | BlenderBot2Fid: full interactive mode on.
Downloading: 100%
232k/232k [00:00<00:00, 1.51MB/s]
Downloading: 100%
466k/466k [00:00<00:00, 1.18MB/s]
Downloading: 100%
28.0/28.0 [00:00<00:00, 470B/s]
Downloading: 100%
570/570 [00:00<00:00, 12.9kB/s]
01:34:54 | building data: /usr/local/lib/python3.7/dist-packages/data/models/hallucination/bart_rag_token/model.tgz
01:34:54 | Downloading http://parl.ai/downloads/_models/hallucination/bart_rag_token/model.tgz to /usr/local/lib/python3.7/dist-packages/data/models/hallucination/bart_rag_token/model.tgz
Downloading model.tgz: 100%|██████████| 950M/950M [00:45<00:00, 20.8MB/s]
01:36:03 | Creating the search engine retriever.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-4aa94939756d> in <module>()
----> 1 Interactive.main(model_file='zoo:blenderbot2/blenderbot2_400M/model')

16 frames
/usr/local/lib/python3.7/dist-packages/parlai/agents/rag/retrieve_api.py in _validate_server(self, address)
     97     def _validate_server(self, address):
     98         if not address:
---> 99             raise ValueError('Must provide a valid server for search')
    100         if address.startswith('http://') or address.startswith('https://'):
    101             return address

ValueError: Must provide a valid server for search

**Expected behavior**
Successful setup of Interactive blenderbot2 

**Logs**
See above 

```
Output goes here
```

**Additional context**
@klshuster 
Thanks for your patience.

**Comment by ajay-sreeram** [comment]
Hi @Jkintree2 , you need to provide --search-server too, provided url should accept a get request with request and responses as follows: 
https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/rag/retrieve_api.py#L120

**Comment by Jkintree2** [comment]
Thanks, @ajay-sreeram .  I tried

Interactive.main(model_file='zoo:blenderbot2/blenderbot2_400M/model' --search-server 'https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/rag/retrieve_api.py#L120')

and got a syntax error.  Please further help.

**Comment by ajay-sreeram** [comment]
try this @Jkintree2 

https://github.com/facebookresearch/ParlAI/issues/3808#issuecomment-881996633

**Comment by ajay-sreeram** [comment]
@Jkintree2, 

JulesGM written the required web search server code that uses google search.

https://github.com/JulesGM/ParlAI_SearchEngine/blob/master/colab.ipynb

**Comment by Jkintree2** [comment]
Thanks.
John

**Comment by klshuster** [comment]
thanks @ajay-sreeram - feel free to reopen, @Jkintree2, if you have any further issues
