### ISSUE TITLE
How to set beam arguments for browser chat service?

### ISSUE THREAD

**Issue by jwchoi09** [facebookresearch/ParlAI#3866]
Hi, I recently fine-tuned a blender_90M model. To chat with the models, I am using the browser chat service.
After placing the model files and configuring the config.yml to locate it, I am able to interact with the chatbot in browser.
However, the quality of responses were not good. (repetitive response) So, I came across a GitHub issue of setting beam arguments [here](https://github.com/facebookresearch/ParlAI/issues/2731#issuecomment-639954599).
I attempted to set the beam arguments in the config.yml, but it had no effect. 
Below is what my config.yml file looks like:
```
tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    blender_90M:
      model: transformer/generator
      model_file: data/models/blender/blender_90M_72000_ConvAI2/model
      interactive_mode: True
      no_cuda: True
      beam-min-length:  20
      beam-block-ngram: 3
      beam-context-block-ngram: 3
      beam-size: 10
      inference beam: beam
additional_args:
  page_id: 1 # Configure Your Own Page
```

How would I set beam arguments to be applied my custom models?

**Comment by stephenroller** [comment]
Use underscores instead of dashes.

**Comment by jwchoi09** [comment]
Thank you very much. 
Using underscores instead of dashes did it for me.
However, I needed to put them under "override: " to actually take effect.

As follows:
```
tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    blender_90M:
      model: transformer/generator
      model_file: data/models/blender/blender_90M_72000_ConvAI2/model
      interactive_mode: True
      no_cuda: True
      override:
        beam_size: 10
        beam_min_length: 20
        beam_context_block_ngram: 3
        beam_block_ngram: 3
        inference: beam
additional_args:
  page_id: 1 # Configure Your Own Page
```

Thanks again.
