### ISSUE TITLE
Deploy BlenderBot 2.0 as an API

### ISSUE THREAD

**Issue by scy6500** [facebookresearch/ParlAI#3871]
Hi. I saw the release of Blender Bot 2.0 a while ago. 

I want to use BlenderBot 2.0 through the api call after deploying it as a Blender Bot 2.0 api server. 

I saw the colab example in issue [#3808](https://github.com/facebookresearch/ParlAI/issues/3808#issuecomment-881996633) but it doesn't seem like it can be deploying as an api. 

How can I deploy it in the form of an api?

**Comment by 589hero** [comment]
I have a same problem. Anybody help me!

**Comment by klshuster** [comment]
we offer some lightweight chat services integration: https://parl.ai/docs/tutorial_chat_service.html

I would also search through prior issues to see how folks have worked with the chat services

**Comment by scy6500** [comment]
By checking issue #3835, I succeeded in creating a config file and running it locally. I want to distribute this so that many people can easily use the demo and API of BlenderBot2.0.

However, as a result of using it now, it seems to be confirmed that conversations are mixed by sharing one chatbot rather than using different chatbots when used at the same time. How can I solve this? Help me

**Comment by klshuster** [comment]
the way our chat service integration is currently set up should prevent leakage between separate connections - would you mind sharing your evidence of this?

**Comment by scy6500** [comment]
Hi @klshuster.

It is understood that the process of browser_chat execution is web socket communication through the client.py server. Why are you communicating through the client.py server instead of the websocket communication with the server directly from the javascript front? There must be a reason for doing this, but I'm not sure, so I'm asking.

I want multiple people to use one client.py without mixing conversations.

**Comment by theainerd** [comment]
Hey, can i host blender bot as an api in cpu, gpu or both. @klshuster @scy6500

**Comment by klshuster** [comment]
> It is understood that the process of browser_chat execution is web socket communication through the client.py server. Why are you communicating through the client.py server instead of the websocket communication with the server directly from the javascript front? There must be a reason for doing this, but I'm not sure, so I'm asking.

As mentioned above, our integration is rather lightweight and extendable to a variety of use cases; I don't have a clear answer for you as to why we chose one way of doing so over the other.

> Hey, can i host blender bot as an api in cpu, gpu or both. 

You can specify certain command-line arguments to determine whether to have BB2 be on CPU or GPU; there is not a clear way at the moment to split up various components for use on _both_ CPU and GPU

**Comment by theainerd** [comment]
> specify certain command-line arguments

Can you point me to the documentation. I ran on cpu and gpu both ; cpu run was giving a lot of errors so i asked this question.

**Comment by klshuster** [comment]
what errors? the control we generally use is to specify `--no-cuda` to ignore GPUs

**Comment by pablogranolabar** [comment]
>You can specify certain command-line arguments to determine whether to have BB2 be on CPU or GPU; there is not a clear way at the moment to split up various components for use on both CPU and GPU

So if one were so inclined to split up BB2 into modular components for distributed inference via API, what would the suggested approach be and which tasks could run in parallel with each other? The thought was to experiment with pre-fetching the Internet search data while other tasks are running in parallel to reduce inference time and overall memory consumption so that BB2 could run on lower end GPUs or perhaps CPU inference via Kubernetes. Any thoughts and information about the internal flow of BB2 would be greatly appreciated!

**Comment by klshuster** [comment]
the biggest gpu constraints for BB2 are the following:

1. Search query generation
2. Memory decoding (i.e., generating new memories from the context)
3. Response generation

The third point is by far the most compute intensive; prefetching search data may be useful only in decreasing latency on that end, but retrieving search results (and/or retrieving memories from the Long Term Memory) are not at all computationally significant components in the whole process.

**Comment by renziver** [comment]
@klshuster does that mean that currently, to have significant optimization in the performance, a higher end (or couple of high end GPUs) must be used since the response generation from the BB2 language model is the most compute intensive workload in the framework?

**Comment by klshuster** [comment]
> @klshuster does that mean that currently, to have significant optimization in the performance, a higher end (or couple of high end GPUs) must be used since the response generation from the BB2 language model is the most compute intensive workload in the framework?

At the moment, potentially yes. Note that we offer a smaller end (400m) BB2 model that is not nearly as compute intensive as the 2.7B model; neither has been properly tested on our end with CPU inference, but I would imagine the 400m would be faster.

There are also additional, in-code optimizations that we have not yet implemented (e.g. incremental decoding) that would bring significant speed improvements regardless of gpu/cpu utilization.

**Comment by agilebean** [comment]
@klshuster 
Can I ask when you will integrate these in-code optimizations? This would be very very beneficial!
