### ISSUE TITLE
Lower num words for Blender 400M Distilled than for 90M

### ISSUE THREAD

**Issue by anelkhvan** [facebookresearch/ParlAI#3882]
Hello! 
When I run the interactive script for Blender 90M:
`from parlai.scripts.interactive import Interactive'
'Interactive.main(
    # the model_file is a filename path pointing to a particular model dump.
    # Model files that begin with "zoo:" are special files distributed by the ParlAI team.
    # They'll be automatically downloaded when you ask to use them.
    model_file='zoo:blender/blender_90M/model')`

I see that num words is 54944. When I ran the same script for Blender 400M Distilled model, I noticed that num words is 8008. I was wondering why is this the case that the larger model has a lower number of words in the dictionary?

**Comment by klshuster** [comment]
The larger model is based on the original pre-trained weights of blenderbot1, which uses a `bytelevelbpe` tokenizer comprising 8008 tokens; the smaller model is based on a BART-style model, which uses the GPT2 dictionary comprising 54944 tokens
