### ISSUE TITLE
Fine-tuning Blender with new tokens. Should they be added to the dict?

### ISSUE THREAD

**Issue by kazeto111** [facebookresearch/ParlAI#3886]
When I use blender, sometimes it has speaker identification problem, I mean it responses to what itself says like the example below

> Blender: What color do you like
> Me: {emoji with thinking}
> Blender: I like Black. How about you?

To solve this problem, I want to fine-tune Blender with blended_skill_talk added new token '[U1]' and '[U2]' at the end of each utterances so that blender can understand the switching of speakers.

My question is just adding new tokens to the fine-tuning  dataset is OK or not?
Should they be added to the dict or in the dict are tokens we can use freely prepared?

Thank you so much

**Comment by klshuster** [comment]
you can specify a list of tokens to add to the dictionary via `--special-tok-lst comma,separated,list,of,tokens`; this is ideal to ensure BB tokenizes the new tokens correctly:

`--special-tok-lst [U1],[U2]` should work for your case

**Comment by kazeto111** [comment]
Thank you so much!!!!
It worked well.
By the way, where --special-tok-lst is processed? I mean I browsed setup_args() of ParlAI/parlai/scripts/train_model.py  but --special-tok-lst wasn't there.

**Comment by klshuster** [comment]
The vast majority of agents/models that function within ParlAI are some form of `TorchAgent`; that is where the parameter is defined: https://github.com/facebookresearch/ParlAI/blob/master/parlai/core/torch_agent.py#L711

Glad to hear it works! Will close for now, please reopen if there are additional concerns

**Comment by kazeto111** [comment]
@klshuster 
You meant bytelevelbpe by BB tokenizer, right?

Sorry despite closed issue, thank you so much

**Comment by klshuster** [comment]
yes, that is correct, the bytelevelbpe tokenizer for BB

**Comment by kazeto111** [comment]
Thank you so much!!!
