### ISSUE TITLE
Difference between BAD classifiers in ParlAI Zoo?

### ISSUE THREAD

**Issue by ethanjperez** [facebookresearch/ParlAI#3887]
The ParlAI Zoo lists [two safety classifiers from BAD](https://parl.ai/docs/zoo.html#bot-adversarial-dialogue-models) which sound almost the same, but one is trained on "filtered" dialogues, while the other is trained on "truncated" dialogues. Would you mind elaborating on what this difference is? I couldn't find it in the paper, but sorry if I missed it!

cc @jxmsML @emilydinan

**Comment by jxmsML** [comment]
Thanks for the comment. The distinction between filter and truncation is:
- The filtered multi-turn bot adversarial dialogue are those of with number of dialogue turns to be **exactly** <bad_num_turns>
- The truncated multi-turn bot adversarial dialogues are those with number of dialogue turns to be **no more than**  <bad_num_turns>

therefore the "filtered" version was trained on fewer data points. We recommend and the results reported on the paper are based on the truncated version which is `zoo:bot_adversarial_dialogue/multi_turn/model`

**Comment by ethanjperez** [comment]
Great, thanks for clarifying!
