### ISSUE TITLE
How to create the counts.txt file when I use the dialogue unlikelihood training objective?

### ISSUE THREAD

**Issue by passing2961** [facebookresearch/ParlAI#3890]
Hi, 

I am Young-Jun Lee, and currently, I try to train the `T5-small` model on the `EmpatheticDialogues` dataset using the dialogue unlikelihood training objective. 

So, for the context and label repetition, I modified the base code into the below:

```python
class RepetitionUnlikelihoodT5Agent(RepetitionUnlikelihoodAgentTrait, T5Agent):
    pass
```

This code is well working. Additionally, I tried to apply a modified loss function corresponding to the vocabulary usage, which is described in the original paper. But, I encountered an issue related to the "counts.txt" file in the below code. So, this is my question, how to create the "counts.txt" file?

```python
class SequenceVocabUnlikelihoodAgentTrait(_VocabUnlikelihoodTrait):
    """
    Abstract Trait.
    Applies unlikelihood loss to vocabulary distribution by generating, calculating
    proportion of tokens per vocabulary frequency bin, and computing loss accordingly
    """

    def __init__(self, opt, shared=None):
        super().__init__(opt, shared)
        self.NUM_STEPS = opt['queue_size']
        if shared is None:
            self._reset_running_histories()
            self._last_was_training = True
            self.truebins = {}
            counts_file = self.opt['counts_file']
            if counts_file is None:
                counts_file = os.path.join(
                    os.path.dirname(self.opt['model_file']), 'counts.txt'
                )
                if not PathManager.exists(counts_file):
                    raise RuntimeError(
                        'Please give a --counts-file to use vocab unlikelihood'
                    )
            with PathManager.open(counts_file) as f:
                for line in f:
                    record = json.loads(line)
                    self.truebins[record['word_id']] = record['bin']
``` 

Sincerely,
Thank you

**Comment by klshuster** [comment]
hi there - if you run the following command, you can check out what a `counts.txt` file would look like:

```bash
python parlai/scripts/interactive.py -mf zoo:dialogue_unlikelihood/vocab_alpha1e0/model -m projects.dialogue_unlikelihood.agents:TransformerSequenceVocabUnlikelihoodAgent
```

This will download a sample `counts.txt` file to `ParlAI/data/models/dialogue_unlikelihood/vocab_alpha1e1/`

**Comment by passing2961** [comment]
Thanks for your kind explanation for convenience,

It looks like using the vocabulary and tokenizer which are used for training. Am I right to understand?

And is it possible to request the ad-hoc script from the author of "Dialogue Unlikelihood Training" paper?

**Comment by stephenroller** [comment]
Yes it's the same tokenizer/vocab as the original model. We just had a second round of counting the vocab across the training corpus to try to him it.

Unfortunately *I* am the one who wrote and ran that script and I'm not sure I have it anymore. I'll look though.

**Comment by stephenroller** [comment]
Okay I did find the script:

https://gist.github.com/stephenroller/58363f5ce79c8e06fa1406146caabf60

Looks like invocation was originally something like:

`python count_words.py -t convai2 -m repeat_label -df zoo:blender/blender_90M/model.dict --dict-tokenizer bpe --dict-lower true`

**Comment by stephenroller** [comment]
Closing this issue since it seems resolved. Reopen if there are more questions.
