### ISSUE TITLE
long-term memory and personas

### ISSUE THREAD

**Issue by nika2312** [facebookresearch/ParlAI#3891]
Hello,

First of all thanks for the awesome work!
I have a few questions about the persona mechanism in BB2.
1. In the original BB, the bot persona was set by prepending the input with the "your persona: ...\n" prefix. From the MSC paper it seems that this mechanism was replaced by the long-term memory, so if I want to add a persona I should add it as a list to the first observation in the conversation using opt["memory_key"], and then it will be fetched from the memory and inputted to the decoder as a document. Is my understanding correct?
2. Following the method in 1, did you notice a persona confusion in the generator? I saw some examples where both "your persona" and "partner's persona" items were chosen from the memory, and the model was confusing the partner's persona as its own in the generated text. How would you deal with such cases?
3. Why did you choose for the memory query vector to encode the whole conversation context? Won't encoding just the last utterance or two be better for retrieving the relevant memory?
4. Why is the memory vector overriden on each turn? https://github.com/facebookresearch/ParlAI/blob/master/projects/blenderbot2/agents/modules.py#L713 IIUC it populates the same batch position with the memory vector from the observation + the generated memories, so if for example the bot or user personas are not present in the current observation, they will not be populated anymore. Doesn't it contradict the purpose of it being a long-term memory? This can be solved by always loading the personas in the batch, but I was wondering whether this was the intended usage.
5. Did you experiment with conversations in which the bot starts? I saw that you mentioned a special silent token in the previous version, could you elaborate on that and what would be the correct persona usage in this case?

Thanks a lot!

**Comment by klshuster** [comment]
Hi there, thank you! To answer your questions:

1. Yes, that is correct; make sure that you set the `opt['memory_extractor_phrase']` correctly (or, not at all) to ensure that the memories are extracted from the list appropriately
2. Presumably the model _should_ have learned on which lines to condition during training, so this may just be a shortcoming of the model. One could presumably try training further on the tasks (either with these personas prepended in the context, as in BB1, or not) to have the model better understand what each is informing.
3. We followed insights from [this project](https://parl.ai/projects/hallucination/) (and [associated paper](https://arxiv.org/abs/2104.07567)) in which retrieving based on the whole context, at least for retrieving global knowledge, was better than simply retrieving on the last turn of context (see Table 7 on page 12). We did not experiment with encoding just the last one or two utterances for memory retrieval but that would be interesting to try!
4. This was purely an engineering decision for batched training, as we don't actually keep track of episodes across batches on the model side; the memory key during training was always the `full_text` so it would necessarily always include the bot/user personas. While this was not computationally efficient, it was also not super compute intensive relative to the rest of the model (i.e. writing memories using BERT-base vs. a full 2.7B-parameter encoder/decoder forward pass)
5. Yes, we did; our human evaluations started with the bot messaging first after observing some prior context (for multi-session-chat eval) or the human's "persona" lines (for wizard of internet-style, knowledge-grounded eval). If one wanted the bot to go first with _no context_, indeed you could have the model observe `__SILENCE__` and ask the model to act first. However, usually the model has some sort of context on which to ground

**Comment by nika2312** [comment]
Thanks for your answers!
To clarify, in 4 - does this mean that you did not use the "personas" list in the observation during training but prepended the personas to the context, like in BB1? (Because how else could the personas get into "full_text"? Or am I missing something?)
And in 5, in the case of observing the human's persona or previously generated summaries as prior context, do you mean as part of the memory?

**Comment by klshuster** [comment]
For 4, I misspoke - we did indeed use the personas in the `observation['personas']` key (you can see what these look like via `parlai dd -t msc -v`; we split them by newline in the agent)

For 5 - yes, that is what I meant specifically for the multi-session-chat eval. For the knowledge-grounded eval, we evaluated in a similar fashion to what was done in the wizard of internet paper, where the model observed the human's "persona" lines before responding.

**Comment by nika2312** [comment]
Got it, thanks!
