### ISSUE TITLE
Correct parameters/options for running BlenderBot 2.0

### ISSUE THREAD

**Issue by sm-jonathana** [facebookresearch/ParlAI#3902]
What are the correct parameters for running the BlenderBot 2.0? To date I have seen this command line:
```
python -m parlai interactive --model-file zoo:blenderbot2/blenderbot2_3B/model --search_server 0.0.0.0:8080
```
Which work successfully with a search server such as https://github.com/JulesGM/ParlAI_SearchEngine

However:

1) Run this way, I can see evidence that the model is doing Internet searches BUT don't see any indication that the "memory" feature is being used. In fact the model often generates contradicting statements in two adjacent conversation turns. 
2) Should a task also be specified (similar to what is done when running BlenderBot 1.0) ?

Any pointers would be appreciated.

**Comment by klshuster** [comment]
No task is required to be specified; and, while BB2 is a significant upgrade from BB1, there is still work to be done to ensure that contradictions are handled correctly (as we mention in the [blog post](https://ai.facebook.com/blog/blender-bot-2-an-open-source-chatbot-that-builds-long-term-memory-and-searches-the-internet/) towards the end). If you run with `--loglevel debug` you may be able to see some more of what's going on under the hood (search query generation, documents retrieved, memories written, etc.)

**Comment by sm-jonathana** [comment]
Thanks!
