### ISSUE TITLE
Will Empathetic dialogues for other languages work ?

### ISSUE THREAD

**Issue by averroes96** [facebookresearch/ParlAI#3916]
Before going further, i was wondering if it is possible to translate the empathetic dialogues dataset without overpassing its licensing, surely i tried to read it but they gave no clear answer. What i know is that i'm not going to claim it's mine or use it for commercial use but just to use it for my graduation project.

For my issue, if i use the translated version just like the tutorial say, will i have to change anything else ? is the BERT pretrained model trained only on english or is it trained on multilingual

**Comment by stephenroller** [comment]
My MS student uses machine translation to translate ED to French. It worked okay.

I see no conflicts with the license (CC-BY-NC; just cite it in your thesis).

**Comment by averroes96** [comment]
Thanks for your reply stephen 

I'm not sure it's the same thing as machine translation but i'm using Helsinki nlp translator and it works well, for the emp dialogues should i just replace the original dataset with the translated one? i'm not sure if tokenization and other steps are problem since french and english are quite close and similar

**Comment by stephenroller** [comment]
I'm afraid I cannot advise on that front. I will note we also used Helsinki's (excellent) MT systems.
