### ISSUE TITLE
How to find the model size in parameters?

### ISSUE THREAD

**Issue by albertobeto** [facebookresearch/ParlAI#3921]
Hello!

How can I know the model size in parameters for a project?

I see some projects have BlenderBot 90 million parameters, etc.

For a newly trained model, how can I compare the size of my model?
(For example, with a transformer, having 3 layers with 600 embedding size vs 6 layers with 300 embedding size).

Will fp16 or fp32, etc change the number of parameters?

Is there an easy way to compute this for newly trained models or existing Parlai projects?

Thanks so much!! :D

**Comment by stephenroller** [comment]
It will print in the training log (something like Total Parameters:).

Fp16 doesn't change the number of parameters but does lower GPU memory usage.

**Comment by albertobeto** [comment]
Oh I found it, thanks so much for your help! :D
