### ISSUE TITLE
Export Blenderbot1.0 with torchscript

### ISSUE THREAD

**Issue by bornhagel** [facebookresearch/ParlAI#3936]
We would like to export our model, a fine tuned Blenderbot 1.0, using torchscript, with beam search. The torchscript export only supports BART models however. Are there any plans on extending this to blenderbot, and if not, can you give us some guidance on how to implement this ourselves?

As I understand we would need to:
1. Implement a ScriptableBpeHelper similarly to ScriptableGpt2BpeHelper
2. Implement TorchScriptBeamSearch similarly to TorchScriptGreedySearch
3. Add support for these in scripts/torchscript.py 

Am I missing something significant?

**Comment by rerngvit** [comment]
I am wondering the same question as the OP above. Any clarification would be greatly help. (It is totally fine, if there are no plans, since these kinds of implementation are not prioritised at the moment.)
