### ISSUE TITLE
Required hardware for Blenderbot 2 (3_B) under certain circumstanzas

### ISSUE THREAD

**Issue by Marcophono2** [facebookresearch/ParlAI#3939]
Hello!
I want to setup a chatbot basing on Blenderbot 2 (pre-trained 3B model) which is able to put out 10 short answers/comments per second while there are up to 50 different dialoges running. "short" means: In average 10 words input and 10 words output. The responding time for each input can take up to 10 seconds. 
I think leting run different dialoge threads to the same time is not possible or not senseful at least. And that would mean that the average response time is 0.1 seconds to fill the 10 outputs per second. But an additional problem could be that the model cannot hold the memory for the 50 simultanously running dialogues. If so, I would need one running model for every single dialogue. 
I was not able to find any informations about the needed hardware for this requirement and also not if this could work generally, undependingly from the hardware. I think a 2x Geforce 3090 system will not be enough, right? ;)
Which Google Cloud VM would/could be a matching one?

Thank you and best regards
Marc

**Comment by klshuster** [comment]
We generally share the same model parameters across various "shared" instances; each instance manages its own dialogue history (which requires little overhead), so memory is not an issue for total # of conversations. The issue lies in simultaneous model calls, you will have to experiment yourself to see how many conversations can run concurrently on your system.

**Comment by Marcophono2** [comment]
Thank you, Kurt, that helps! 
Is there any benchmark table available where the number of simultanously instanzes and/or the processing time of certain commands depending on the model (400M, 3B etc.) and depending on the hardware (like the Google VM a2-megagpu-16g -> https://cloud.google.com/blog/products/compute/a2-vms-with-nvidia-a100-gpus-are-ga ) is displayed)
Just to get a raw overview. I could not find such benchmarks.

Best regards
Marc

**Comment by klshuster** [comment]
we have not run any such benchmarks, sorry

**Comment by Marcophono2** [comment]
Good to know. Then it wasn't my search skill that lacked. ;)

Thanks again, Kurt!
Marc

**Comment by klshuster** [comment]
No problem - closing this issue for now, please reopen or file a new one if you have further concerns

**Comment by argideritzalpea** [comment]
Hi @klshuster, thanks for addressing the original question. Has the team released or been made aware of resources (code / documentation) that shows how to manage multiple parl.ai (blenderbot 2) model instances with shared parameters that you mention / how to set up parameter sharing while maintaining instance-level Blenderbot 2.0 conversational contexts?

**Comment by stephenroller** [comment]
You can make clones of agents which share models but not history with `agent.clone()`
