### ISSUE TITLE
Use Reinforcement Learning Agent in ParlAI

### ISSUE THREAD

**Issue by HongyuanLuke** [facebookresearch/ParlAI#3941]
Hi, I am working on a project that on RL.

So my pipeline works as the following:

The dialogue agent sends its output to the RL agents (which is a neural network), then RL agent sends back a reward to the dialogue agent for loss backwards. 

I am wondering how I should incorporate this RL agent in the ParlAI framework. Should I subclass it as some Agent?

**Comment by HongyuanLuke** [comment]
I see there is a torch classifier agent, I guess I could subclass from this module to create a classifier agent as my RL agent? I am wondering in this case, I would have 2 students and 1 teacher agent... Which world should I use then? MultiAgentDialogWorld?

**Comment by stephenroller** [comment]
RL is something that _should_ be possible in ParlAI, but we've never done the engineering to make it very accessible. Sorry :(

**Comment by stephenroller** [comment]
My best guess suggestion is to add a reward field on the send back and have batch_act check for it in the beginning of batch_act
