### ISSUE TITLE
Hosted location of downloadable models?

### ISSUE THREAD

**Issue by ethanjperez** [facebookresearch/ParlAI#3942]
In what country/region are ParlAI models hosted? I'm frequently downloading these models to Google Cloud instances, and I notice significant differences in download times based on where the instance is located (e.g., Mid-Europe vs. West-US). I'd like to choose to spawn my instances in locations that are near the ParlAI hosting location.

I'm particularly interested in where these two download locations are:
- Blender (2.7B params) http://parl.ai/downloads/_models/blender/BST3B.tgz
- Bot-Adversarial Dialogue Offensiveness Classifier: http://parl.ai/downloads/_models/bot_adversarial_dialogue/multi_turn/models_v1.tar.gz

**Comment by stephenroller** [comment]
They should be behind a CDN, mirroring to somewhere geographically reasonable to you.

**Comment by stephenroller** [comment]
But the mirror originally sources from something like US-Ohio. But again, it should be wrapped in a CDN...

**Comment by ethanjperez** [comment]
Great, thanks Stephen!
