### ISSUE TITLE
RagSequence.marginalize seems returning an incompatible dimension size 

### ISSUE THREAD

**Issue by robbine** [facebookresearch/ParlAI#3947]
the purpose of marginalize is to marginalize among difference docs so that the expected dimension reduced to [bsz *seqlen* voc_dim]. whereas in RagSequence.marginalize implementation a tensor of size [bsz, n_docs, seqlen, voc_dim] is returned .

**Comment by klshuster** [comment]
yes, that is true - it's a bit of a misnomer for `RagSequence`, as the true marginalization happens in `RagSequence.compute_loss` (specifically, `RagSequence._rag_sequence_loss`); `marginalize` here merely combines the doc scores with the token outputs per document

**Comment by robbine** [comment]
It seems right with the training part. But as for the generation phase, RagAgent._generate calls RagAgent._rag_generate which then calls TorchGeneratorAgent._generate. I'm afraid  score[:, -1:, :] might not get the last token representation as it should be.

score, incr_state = model.decoder(decoder_input, encoder_states, incr_state)
            # only need the final hidden state to make the word prediction
            score = score[:, -1:, :]

**Comment by klshuster** [comment]
`RagSequence` generation assumes each context/document pair is a separate batch item, and thus produces `n_beams * n_docs` beams for each example. The model then either uses [fast decoding](https://github.com/facebookresearch/ParlAI/blob/6d59d0464ba031519da95dd64031d821d9be2614/parlai/agents/rag/model_types.py#L453) or [thorough decoding](https://github.com/facebookresearch/ParlAI/blob/6d59d0464ba031519da95dd64031d821d9be2614/parlai/agents/rag/model_types.py#L493) during the call to `RagAgent._rerank_beams` to marginalize over the resulting generations

**Comment by robbine** [comment]
By saying generation actually I mean the  decoding phase. Sorry for the confusing. I misused these two words.

**Comment by klshuster** [comment]
The answer remains the same as above
