### ISSUE TITLE
How to batch generate with conversational history?

### ISSUE THREAD

**Issue by ethanjperez** [facebookresearch/ParlAI#3948]
Hello, I just wanted to sanity check my understanding of how to batch-generate from dialog models with ParlAI, after reading the helpful [Batching tutorial](https://parl.ai/docs/tutorial_worlds.html).

As I understand, every other utterance in a two-party dialogue should be provided to Blender via `observe` (e.g., utterances from a human speaker) and the remaining utterances should be provided via `self_observe` (to indicate that these utterances came from the model itself). In addition, all utterances should be provided alongside `episode_done: False`, except for the last provided utterance (right before generating), which should be provided alongside `episode_done: True`. Is my understanding correct? I've included a code snippet below that shows how I'm generating a next utterance from Blender:

```python
# Load a pretrained model
from parlai.core.agents import create_agent_from_model_file

agent = create_agent_from_model_file(
    "zoo:blender/blender_90M/model", {'model_parallel': False}
)

# Setup data
convos = [
  [
    'Hello, I am Alfred.',
    'Hello, I am Joe.',
    'What is your name?',
  ],
  [
    'Hello, I am Alfred.',
    'Hello, I am Joe.',
    'What is your full name?',
  ],
]

# Setup batch
observations = []
for convo in convos:
  # Setup convo history
  clone = agent.clone()
  clone.observe({
      'text': convo[0],
      'episode_done': False,
  })
  clone.self_observe({
      'text': convo[1],
      'episode_done': False,
  })

  # Add new observation to take action on
  observations.append(clone.observe({
      'text': convo[2],
      'episode_done': True,
  }))

# Batch generate responses
responses = agent.batch_act(observations)
for response in responses:
  print(response['text'])
```

**Comment by stephenroller** [comment]
Yes that's right. But if you're fixing the responses, you can just dump to a dataset and use eval_model + world logging

**Comment by ethanjperez** [comment]
Great, thanks for clarifiying!
