### ISSUE TITLE
Does Blender handle newline characters?

### ISSUE THREAD

**Issue by ethanjperez** [facebookresearch/ParlAI#3949]
Does the Blender 1.0 support newlines within a single utterance? If so, should the newline be formatted as usual (a newline character), or does it need to be formatted in some other way as with some other models (e.g., literal backslash, following by a literal n)?

**Comment by stephenroller** [comment]
It's a weird limbo bc of byte level BPE. The answer is that we use newlines between persona lines, but a newline token (tokenizer by itself) between other turns.

--split-lines true is roughly this behavior

**Comment by ethanjperez** [comment]
Okay, so if I'm passing a multi-line utterance to the model with the `observe()` method, I can just pass in the utterance directly, as shown below? And the tokenizer will handle the newlines properly?

```python
from parlai.core.agents import create_agent_from_model_file

agent = create_agent_from_model_file(
    "zoo:blender/blender_90M/model", {'model_parallel': False}
)

clone = agent.clone()
observation = clone.observe({
    'text': 'Hello!\nMy name is Alfred.',
    'episode_done': True,
})

responses = agent.batch_act([observation])
for response in responses:
  print(response['text'])
```

**Comment by nika2312** [comment]
If I may jump in on this - Stephen, could you please elaborate on why you changed the turn delimiter to be two spaces in Blender2?
