### ISSUE TITLE
Chatbot docs claim sane behaviour with no overworld, but an exception is generated

### ISSUE THREAD

**Issue by drevicko** [facebookresearch/ParlAI#3951]
The [chatbot demo docs](https://github.com/facebookresearch/ParlAI/blob/master/docs/source/tutorial_chat_service.md#L124) suggest that 

>  3. Tasks with no overworld will immediately attempt to put a user into the queue for the default task onboarding world or actual task world (if no onboarding world exists), and will do so again following the completion of a world (via `episode_done`).

However this is not the case, as [ChatServiceWorldRunner expects an overworld to be specified and to exist](https://github.com/facebookresearch/ParlAI/blob/master/parlai/chat_service/core/world_runner.py#L164). You can drill back from there to eg.  and find that no checks are done to see if an overworld is not specified, and [an overworld must be specified in a chatbot config](https://github.com/facebookresearch/ParlAI/blob/master/parlai/chat_service/core/chat_service_manager.py#L183).

**Comment by klshuster** [comment]
Yes, it appears you are correct, an overworld is required - I will update the docs accordingly
