### ISSUE TITLE
RAG-Sequence and RAG-Token formulas in code

### ISSUE THREAD

**Issue by gianlucabusatta** [facebookresearch/ParlAI#3953]
I was searching [here](https://github.com/facebookresearch/ParlAI/tree/6d59d0464ba031519da95dd64031d821d9be2614/parlai/agents/rag) for the code implementation of the RAG-Sequence and RAG-Token formulas described in the [RAG paper](https://arxiv.org/abs/2005.11401)  (_2.1 Models_) but I couldn't find them.

Could someone help me identify the relevant parts of code?

**Comment by klshuster** [comment]
Hi there - the following links should help:

- [RAG-Token marginalization](https://github.com/facebookresearch/ParlAI/blob/6d59d0464ba031519da95dd64031d821d9be2614/parlai/agents/rag/model_types.py#L840)
- [RAG-Sequence marginalization](https://github.com/facebookresearch/ParlAI/blob/6d59d0464ba031519da95dd64031d821d9be2614/parlai/agents/rag/model_types.py#L840); [subsequent loss computation](https://github.com/facebookresearch/ParlAI/blob/6d59d0464ba031519da95dd64031d821d9be2614/parlai/agents/rag/model_types.py#L530)

For RAG-Sequence, here are the generation functions for [fast-decoding](https://github.com/facebookresearch/ParlAI/blob/6d59d0464ba031519da95dd64031d821d9be2614/parlai/agents/rag/model_types.py#L453) and [thorough-decoding](https://github.com/facebookresearch/ParlAI/blob/6d59d0464ba031519da95dd64031d821d9be2614/parlai/agents/rag/model_types.py#L493)
