### ISSUE TITLE
How to utilize fairseq ckpts in ParlAI

### ISSUE THREAD

**Issue by hannnnnxd** [facebookresearch/ParlAI#3959]
Hi all,

I am trying to use a fairseq-based model as a weight initialization for ParlAI model. I could get a model.pt and a dict.txt from fairseq. I can find an example in [bart zoo](https://github.com/facebookresearch/ParlAI/blob/master/parlai/zoo/bart/build.py), which downloads bart.large from the fariseq website and convert it to ParlAI agents. Is there any official instruction here?

**Comment by stephenroller** [comment]
No, there are no official instructions. We occasionally hand convert specific models we need, but it's hard to do it in the general case. The BART conversion code is generally a good place to start though.
