### ISSUE TITLE
Blenderbot 2.0 Long Term Memory

### ISSUE THREAD

**Issue by doquangminh28** [facebookresearch/ParlAI#3962]
Hello, can I print or modify the BB2 LTM in anyway? Do I have to manually use Memory Decoder model and save it on my own?
Thanks in advance.

**Comment by doquangminh28** [comment]
Update: I've been chatting with it for a while, and there was one thing like this.
The bot said it like playing video games, and after 2 or 3 utterances, it said it had never play a video games.
It occurred in the same session.
I will post the chatlog if needed.

**Comment by klshuster** [comment]
the model will also write memories you put in the `--memory-key` of an observation. I'm not sure how you're interacting with the model, but there are a few ways of incorporating this into your pipeline

**Comment by doquangminh28** [comment]
Thanks for the response,
I am using parlai interactive command to interact with it.

**Comment by klshuster** [comment]
if you set `--loglevel debug`, you'll see the model writing memories to its LTM

**Comment by doquangminh28** [comment]
Thank you! I'm closing this issue now.
