### ISSUE TITLE
Cannot find a way to initialize Poly-encoder with DPR's weight in the "Hallucination" project.

### ISSUE THREAD

**Issue by acha21** [facebookresearch/ParlAI#3968]
Hello. I am Yeonchan Ahn.

I read your paper titled "Retrieval Augmentation Reduces Hallucination in Conversation" and the codes carefully.
 
But, I can't find a way to use Joint DPR-Poly, which the you said that "one can also choose to initialize the Poly-encoder
with the DPR model weights, a method we denote Joint DPR-Poly" in that paper.

Am I missing something ?

Best regards,
Yeonchan.

**Comment by klshuster** [comment]
Hi there - we did not include the implementation for the Joint DPR-Poly method, as we saw negligible (if any) performance improvements over just the DPR-Poly method.
