### ISSUE TITLE
disabling search server (blenderbot2)

### ISSUE THREAD

**Issue by jaekookang** [facebookresearch/ParlAI#3972]
Hi, I have been exploring BlenderBot2 extensively lately and had a question about the search server.

Is there a way to disable the search server by any chance so that searching on the web does not happen at all during the chat?

I just wanted to continue testing BlenderBot2 without an intermittent 5-7 sec latency from the search server that I've been using based on https://github.com/JulesGM/ParlAI_SearchEngine.

I tried setting the `--search_server` parameter as `None`, but it didn't work.

**Comment by klshuster** [comment]
you can specify the `--knowledge-access-method` to avoid web searches; the following is taken from the [parameter definition](https://github.com/facebookresearch/ParlAI/blob/7506a84e00e0ba526dca01b8aea97d009c91fa50/projects/blenderbot2/agents/blenderbot2.py#L183-L193)

- `classify` => classify the input text, determine which knowledge to access
- `memory_only` => only access memories
- `search_only` => only access search
- `all` => for each input, access from memories and search
- `none` => do not access any knowledge.

**Comment by jaekookang** [comment]
@klshuster It worked! Thank you for your answer.

For folks who might wonder, I specified `knowledge_access_method` parameter as `memory_only` in my custom yml config file.
```
models:
...
    blenderbot:
    ...
    override:
        knowledge_access_method: memory_only
        search_server: None
```

**Comment by AndrewMpapalika** [comment]
@jaekookang:  I tried the above 

tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    blenderbot2_400M:
      model: projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent
      model_file: zoo:blenderbot2/blenderbot2_400M/model
      interactive_mode: True
      beam-size: 3
      no_cuda: True
      override:
        search_server: None
        knowledge_access_method: memory_only

additional_args:
  page_id: 1 # Configure Your Own Page




But unfortunately, I got the error below:



[E 210921 22:22:27 logging:44] World default had error AttributeError("'NoneType' object has no attribute 'size'")                                                 [73/1258]
World default had error AttributeError("'NoneType' object has no attribute 'size'")
Traceback (most recent call last):
  File "/root/anaconda3/envs/blender/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/blender/parlai/chat_service/core/world_runner.py", line 128, in _world_fn
    return self._run_world(task, world_name, agents)
  File "/home/blender/parlai/chat_service/core/world_runner.py", line 99, in _run_world
    ret_val = world.parley()
  File "/home/blender/parlai/chat_service/tasks/chatbot/worlds.py", line 101, in parley
    response = self.model.act()
  File "/home/blender/parlai/core/torch_agent.py", line 2143, in act
    response = self.batch_act([self.observation])[0]
  File "/home/blender/parlai/core/torch_agent.py", line 2239, in batch_act
    output = self.eval_step(batch)
  File "/home/blender/projects/blenderbot2/agents/blenderbot2.py", line 782, in eval_step
output = super().eval_step(batch)                                                                                                                              [57/1258]
  File "/home/blender/parlai/core/torch_generator_agent.py", line 877, in eval_step
    beam_preds_scores, beams = self._generate(
  File "/home/blender/parlai/agents/rag/rag.py", line 608, in _generate
    gen_outs = self._rag_generate(batch, beam_size, max_ts, prefix_tokens)
  File "/home/blender/parlai/agents/rag/rag.py", line 647, in _rag_generate
    return self._generation_agent._generate(
  File "/home/blender/parlai/core/torch_generator_agent.py", line 1114, in _generate
    encoder_states = model.encoder(*self._encoder_input(batch))
  File "/home/blender/projects/blenderbot2/agents/modules.py", line 802, in encoder
    enc_out, mask, input_turns_cnt, top_docs, top_doc_scores = super().encoder(  # type: ignore
  File "/home/blender/projects/blenderbot2/agents/modules.py", line 211, in encoder
    expanded_input, top_docs, top_doc_scores = self.retrieve_and_concat(
  File "/home/blender/projects/blenderbot2/agents/modules.py", line 336, in retrieve_and_concat
    retrieval_type, search_queries = self.query_generator.classify_retrieval(
  File "/home/blender/projects/blenderbot2/agents/sub_modules.py", line 221, in classify_retrieval
  self.retrieval_type = torch.LongTensor(input.size(0))                                                                                                                   
AttributeError: 'NoneType' object has no attribute 'size'
Next task: None

**Comment by klshuster** [comment]
could you try setting the `knowledge_access_method` both under the `blenderbot2_400M:` entry and the `override:` entry? that code path should not execute if this option is being set correctly

**Comment by AndrewMpapalika** [comment]
@klshuster: many thanks for the quick reply. I made the changes you suggested and I also pulled new changes from the repo. It is now working. Thanks.

**Comment by SamsTheGreatest** [comment]
@klshuster is there an example of using BB2 **without command-line interface** and set `knowledge_access_method` to `memory_only`?

**Comment by AndrewMpapalika** [comment]
@SamsTheGreatest: I don't know if this answers your question, but I am using BB2 on a web browser, as shown in 

https://github.com/facebookresearch/ParlAI/tree/main/parlai/chat_service/services/browser_chat

**Comment by AndrewMpapalika** [comment]
I just changed the config file to: 


tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    blenderbot2_3B:
      model: projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent
      model_file: zoo:blenderbot2/blenderbot2_3B/model
      interactive_mode: True
      inference: beam
      beam-size: 3
      no_cuda: True
      knowledge_access_method: memory_only
      search_server: None
      override:
        search_server: None
        knowledge_access_method: memory_only

additional_args:
  page_id: 1 # Configure Your Own Page
