### ISSUE TITLE
Blender Bot 2.0 Model Training Time

### ISSUE THREAD

**Issue by fraziermatthew** [facebookresearch/ParlAI#3973]
I'm attempting to recreate the BlenderBot 2.0 model. I'm doing so on AWS and trying to estimate the overall time and cost associated with the process.

My approach is to start with a copy of BlenderBot 1.0, then training the copy on both the MSC and Wizard of the Internet datasets. 

Given the model training configurations/parameters found in the [Model Card](https://github.com/facebookresearch/ParlAI/blob/master/parlai/zoo/blenderbot2/model_card.md), if I were to recreate the model given the method above, how long should I expect that the training process runs for (1 day, 5 days, 14 days, ...)?

Lastly, is the approach above the best method for recreating the BlenderBot 2.0 model?

**Comment by klshuster** [comment]
Yes, fine-tuning on those datasets (MSC, WizInt) from BB1 would suffice, though you'd be missing the safety datasets as described on the project page.

In terms of length of training, that's pretty dependent on your gpu setup; the 2.7B model was trained with 8 32GB gpus (using model parallel) with a batchsize of 16 for roughly 10k updates, which took between 1-2 days

**Comment by DrMatters** [comment]
@fraziermatthew How are you doing in the BB2 training? Would you please share the script arguments to run the training? I'm stuck with training a large (1024 tokens) context size model, so I would be very glad if you could help.
