### ISSUE TITLE
ImportError: Could not find pretrained model in parlai.zoo.blender.blenderbot2.blenderbot2_3B

### ISSUE THREAD

**Issue by HatterTheMad** [facebookresearch/ParlAI#3986]
**Bug description**
I get
> I get ImportError: Could not find pretrained model in parlai.zoo.blender.blenderbot2.blenderbot2_3B or parlai.zoo.blender.blenderbot2.build. Please check your spelling and make sure you've pulled from master. 

When trying to train blenderbot2

**Reproduction steps**
Just running regular training on the newest cloned git

**Expected behavior**
Well... training 

**Logs**
This is the command:
`parlai train_model --task fromfile:parlaiformat --fromfile_datapath train_q20.txt --datatype train -m transformer/generator --attention-dropout 0.0 --batchsize 192 --model transformer/generator --embedding-size 2560 --ffn-size 10240 --variant prelayernorm --n-heads 32 --n-positions 128 --n-encoder-layers 2 --n-decoder-layers 24 --history-add-global-end-token end --delimiter '  ' --dict-tokenizer bytelevelbpe  --dropout 0.1 --fp16 True --init-model zoo:blender/blenderbot2/blenderbot2_3B/model --dict-file zoo:blenderbot2/blenderbot2_3B/model.dict --label-truncate 128 --log_every_n_secs 10 -lr 7e-06 --lr-scheduler reduceonplateau --lr-scheduler-patience 3 --optimizer adam --relu-dropout 0.0 --activation gelu -eps 3 --model-parallel true --save-after-valid True --text-truncate 128 --truncate 128 --warmup_updates 100 --fp16-impl mem_efficient --update-freq 2 --gradient-clip 0.1 --skip-generation True -vp 10 -vmt ppl -vmm min --model-file /ssd/modelsRaw/b2_3_eps.model`

**Comment by klshuster** [comment]
your init model is not set correctly; it needs to be `--init-model zoo:blenderbot2/blenderbot2_3B/model`
