### ISSUE TITLE
Outfile for brower_chat and/or interactive_web

### ISSUE THREAD

**Issue by fraziermatthew** [facebookresearch/ParlAI#3993]
I have a browser chat configured with a Blender Bot 2.0 model agent. I'm trying to save the conversation to a file but when entering [EXIT] the web socket closes and the conversation is not saved anywhere. Is saving the output of a conversation a feature that is available while using chat services e.g. browser chat?

**Comment by klshuster** [comment]
We don't have anything setup like this, but an easy way to handle this would be to save the dialogue state within the [chatbot world](https://github.com/facebookresearch/ParlAI/blob/7506a84e00e0ba526dca01b8aea97d009c91fa50/parlai/chat_service/tasks/chatbot/worlds.py#L28), and save accordingly within the [`parley` function](https://github.com/facebookresearch/ParlAI/blob/7506a84e00e0ba526dca01b8aea97d009c91fa50/parlai/chat_service/tasks/chatbot/worlds.py#L71-L85) when

**Comment by fraziermatthew** [comment]
Thanks for that tip. I made some local changes to write to a json file and this seems to work.

**Comment by renzs6** [comment]
May I know the format of your saved json file? and how you are loading it back to  reload memory? @fraziermatthew

**Comment by fraziermatthew** [comment]
I capture every utterance from the user and every response from Blenderbot. Then load that into a file so that I can have the full conversation. I am not reloading any memory. I'm not sure what you mean about your second question.
