### ISSUE TITLE
Adding license for dataset task

### ISSUE THREAD

**Issue by kushalchawla** [facebookresearch/ParlAI#4009]
Hi. I am currently working on adding our dataset to the repository as a new task. I am following the guide here: https://parl.ai/docs/tutorial_task.html

I could not find how I can put license information about my dataset. Facebook asks me to sign a CLA, but I think that only applies to the software that goes into the repo and not any rights to the dataset. Is there a way to still apply the license information for the dataset that the code links to? Please advice. Is there a sample task that does that? We released our dataset under CC BY 4.0 license and would like to keep it the same.

Thanks

**Comment by stephenroller** [comment]
We generally just put this info in the README file of that particular task

**Comment by kushalchawla** [comment]
Hey @stephenroller 
Thanks for your response. I was looking for an example but could not find any. Could you please point me to a task that does this?

**Comment by stephenroller** [comment]
Empathetic Dialogues

**Comment by kushalchawla** [comment]
Hey. Great. Thanks a lot for the prompt response!
