### ISSUE TITLE
BlenderBot2 search

### ISSUE THREAD

**Issue by SamsTheGreatest** [facebookresearch/ParlAI#4037]
I am trying to set up blenderbot2 to work on internal corpora. Is it possible? If so, how shall the search server be set up? Can't find any docs neither on the search results formating nor for a general description of that feature, so would appreciate if anyone could explain me whatsup.

**Comment by mojtaba-komeili** [comment]
As long as you have a service that responds to the search query, you can use it with BlenderBot2. For the signature of the service you may look at the retriever api [here](https://github.com/facebookresearch/ParlAI/blob/edb19d30447f3e095b91a5619b84a2a39312d5f3/parlai/agents/rag/retrieve_api.py#L73). Also, there are some search servers built by the community to be used with BlenderBot2 (See [this](https://github.com/facebookresearch/ParlAI/issues/3925) thread for example). They may provide a good example for your to have your own implementation.
