### ISSUE TITLE
[Blenderbot1.0] Time Period of data you used: From when to 2019.07?

### ISSUE THREAD

**Issue by midannii** [facebookresearch/ParlAI#4045]
I want to pre-train with reddit dataset as you did for B.B1. 
I noticed you didn't open reddit dataset you used in parlai 
So I just downloaded the dataset from https://files.pushshift.io/reddit/comments/.
However, I faced a problem. 
You said "through July 2019", but you didn't tell me the exact start period of the data, so I'd like to ask.

**Comment by stephenroller** [comment]
As early as PushShift provided.

**Comment by midannii** [comment]
Do you mean '2005-12' ?

**Comment by stephenroller** [comment]
I believe so

**Comment by midannii** [comment]
Thank you !
