### ISSUE TITLE
No detect_offensive_language argument command 

### ISSUE THREAD

**Issue by yana-xuyan** [facebookresearch/ParlAI#4049]
**Bug description**
Please enter a clear and concise description of what the bug is.
Hello, I'm following the paper "Recipes for Safety in Open-domain Chatbots" and trying to find the word-list based and transformer-based classifier to evaluate the safety factor. What I can find in Parlai github repo is the script called detect_offensive_language.py.

**Reproduction steps**
Enter steps to reproduce the behavior.

However, when I tried to run ```parlai detect_offensive_language --task "convai_chitchat" --display-examples True``` as it's shown in the comments, it shows that "Parse Error: argument COMMAND".

**Expected behavior**
Give a clear and concise description of what you expected to happen.
Could you please tell me how to find and use the two mentioned classifiers in the paper? Thank you very much!

**Logs**
Please paste the command line output:
usage: parlai [-h] [--helpall] [--version] COMMAND ...

       _
      /")
     //)
  ==//'=== ParlAI
   /

optional arguments:
  -h, --help               show this help message and exit
  --helpall                List all commands, including advanced ones.
  --version                Prints version info and exit.

Commands:

  eval_model (em, eval)    Evaluate a model
  display_data (dd)        Display data from a task
  display_model (dm)       Display model predictions.
  train_model (tm, train)  Train a model
  interactive (i)          Interactive chat with a model on the command line
  safe_interactive         Like interactive, but adds a safety filter
  self_chat                Generate self-chats of a model

Parse Error: argument COMMAND: invalid choice: 'detect_offensive_language' (choose from 'help', 'h', 'helpall', 'build_candidates', 'build_dict', 'eval_model', 'em', 'eval', 'convert_to_json', 'convert_to_parlai', 'convo_render', 'data_stats', 'detect_offensive', 'display_data', 'dd', 'display_model', 'dm', 'train_model', 'tm', 'train', 'eval_wordstat', 'extract_image_feature', 'interactive', 'i', 'interactive_web', 'iweb', 'multiprocessing_eval', 'mp_eval', 'multiprocessing_train', 'mp_train', 'party', 'parrot', 'profile_interactive', 'profile_train', 'safe_interactive', 'self_chat', 'token_stats', 'torchscript', 'vacuum', 'verify_data')

```
Output goes here
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by klshuster** [comment]
could you try running `parlai detect_offensive` instead?

**Comment by yana-xuyan** [comment]
Thank you for your reply! 

By rerunning the command with `parlai detect_offensive --task "convai_chitchat" --display-examples True`, I got another error:

Traceback (most recent call last):
  File "/home/xuyan/anaconda3/envs/safety/bin/parlai", line 8, in <module>
    sys.exit(main())
  File "/home/xuyan/anaconda3/envs/safety/lib/python3.7/site-packages/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home/xuyan/anaconda3/envs/safety/lib/python3.7/site-packages/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/home/xuyan/anaconda3/envs/safety/lib/python3.7/site-packages/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/home/xuyan/anaconda3/envs/safety/lib/python3.7/site-packages/parlai/scripts/detect_offensive_language.py", line 129, in run
    return detect(self.opt)
  File "/home/xuyan/anaconda3/envs/safety/lib/python3.7/site-packages/parlai/scripts/detect_offensive_language.py", line 107, in detect
    classify(l, stats)
  File "/home/xuyan/anaconda3/envs/safety/lib/python3.7/site-packages/parlai/scripts/detect_offensive_language.py", line 93, in classify
    if text in offensive_classifier:
  File "/home/xuyan/anaconda3/envs/safety/lib/python3.7/site-packages/parlai/utils/safety.py", line 76, in __contains__
    pred_not_ok, prob = self.contains_offensive_language(key)
  File "/home/xuyan/anaconda3/envs/safety/lib/python3.7/site-packages/parlai/utils/safety.py", line 63, in contains_offensive_language
    response = self.model.act()['text']
KeyError: 'text'

Inquiry: Is this just because of the dataset format problem? If so, could you please tell me how I should do to fix it?

Thank you very much again!

**Comment by klshuster** [comment]
This is actually a small bug in the script, putting out a fix now
