### ISSUE TITLE
[Bug]Spelling mistake

### ISSUE THREAD

**Issue by wayne163** [facebookresearch/ParlAI#4051]
**Bug description**
spelling bug `selected_text_candaidtes ` in projects/wizard_of_internet which should be `selected_text_candidates`
https://github.com/facebookresearch/ParlAI/blob/edb19d30447f3e095b91a5619b84a2a39312d5f3/parlai/crowdsourcing/projects/wizard_of_internet/compile_results.py#L105

https://github.com/facebookresearch/ParlAI/blob/7506a84e00e0ba526dca01b8aea97d009c91fa50/parlai/crowdsourcing/projects/wizard_of_internet/acceptability.py#L131

https://github.com/facebookresearch/ParlAI/blob/7506a84e00e0ba526dca01b8aea97d009c91fa50/parlai/crowdsourcing/projects/wizard_of_internet/webapp/main.js#L203

https://github.com/facebookresearch/ParlAI/blob/7506a84e00e0ba526dca01b8aea97d009c91fa50/parlai/crowdsourcing/projects/wizard_of_internet/worlds.py#L81

https://github.com/facebookresearch/ParlAI/blob/7506a84e00e0ba526dca01b8aea97d009c91fa50/parlai/crowdsourcing/projects/wizard_of_internet/worlds.py#L511

**Expected behavior**
change `selected_text_candaidtes` to `selected_text_candidates`

**Comment by mojtaba-komeili** [comment]
Hi @wayne163 , thanks for reporting this. We will fix it soon.

**Comment by wayne163** [comment]
Hi @mojtaba-komeili , that's great！I will close this issue
