### ISSUE TITLE
Data license is same as ParlAI package license ?

### ISSUE THREAD

**Issue by whaowhao** [facebookresearch/ParlAI#4063]
I am planning to use the dataset in Bot Adversarial Dialog dataset https://parl.ai/projects/safety_recipes/ downloaded through parlai Python package. Does the data have the same license (MIT License) as the parlai Python package? @stephenroller  Thanks!

**Comment by stephenroller** [comment]
Just to flag, not all of our data is released under that license. Check inside specific folders for specific data information. Additionally, some datasets in parlai are not ours, and we only provide code to use them, not the data itself. You'll need to check with those resources to identify the LICENSE
