### ISSUE TITLE
Use of lighter weight BART model for blenderbot2

### ISSUE THREAD

**Issue by Jcwscience** [facebookresearch/ParlAI#4071]
I would really like to try out blenderbot2 on my local machine, however —due to the global GPU shortage— I only have 8GB of GPU memory available. And even that’s pushing it.
I can load the blenderbot2 400M model all the way to the import of bart_large, but my machine gives up there.

Are there any ways to cut down on the memory use of the project? I was hoping that I might have enough memory to load the small bart model, but it’s not in the model zoo and I’m not sure exactly how to change it in the blenderbot2 interactive script anyway.

Any help or suggestions that could be given would be greatly appreciated! Thanks in advance!

**Comment by klshuster** [comment]
The blenderbot2 400m model should only take up ~5gb of GPU memory. Would this suffice for your purpose? If something is going wrong in the loading of the model, please paste the full stack trace.

Although the smallest trained model we provide is the 400m model, there are lots of ways one could reduce the size of the various components (albeit at the cost of model performance). For example, there are two submodules - a query generator and memory decoder - that are both BART-Large models; one could train smaller versions of these models to use to reduce memory usage.

**Comment by Jcwscience** [comment]
@klshuster I had a hunch that could be a problem, but I haven’t really ever seen that talked about on any forms I searched

**Comment by klshuster** [comment]
We load model states [here](https://github.com/facebookresearch/ParlAI/blob/e80c27e5a3eaed2a6e6cb5bcb6e3651575ba9bba/parlai/core/torch_agent.py#L2074). Theoretically you should be able to map the loads directly to a cuda device; see [`torch.load`](https://pytorch.org/docs/stable/generated/torch.load.html) for more info

**Comment by agilebean** [comment]
> We load model states [here](https://github.com/facebookresearch/ParlAI/blob/e80c27e5a3eaed2a6e6cb5bcb6e3651575ba9bba/parlai/core/torch_agent.py#L2074). Theoretically you should be able to map the loads directly to a cuda device; see [`torch.load`](https://pytorch.org/docs/stable/generated/torch.load.html) for more info

Any chance you could integrate this into the ParlAI code?
This could drastically reduce the substantial loading times for BlenderBot 2 which would be great.
It takes 7min for the BB2_400 and 11-11:30 min for the BB2_3B model.
