### ISSUE TITLE
Dodecadialogue training - special tokens

### ISSUE THREAD

**Issue by sanchit97** [facebookresearch/ParlAI#4075]
Currently, `dodecadialogue` does not use person special tokens: `__p1__` and `__p2__` to designate which person talks in the `History` class. However, there is code to enable/disable this behavior in the `TorchAgent` class. Furthermore, to use a `BPE` tokenizer with special tokens (adding new tokens) is somehow disabled.
My question is 2 part:
1. How would one add special tokens to the `BPE` tokenizer?
2. Were special tokens (`__p1__` and `__p2__`) part of the training process of `dodecadialogue` pre-trained model?

**Comment by klshuster** [comment]
You can add special tokens to the BPE dictionary via `--special-tok-lst __p1__,__p2__`. The dodeca models were not trained with these tokens
