### ISSUE TITLE
Error in ParlAI Google colab tutorial 

### ISSUE THREAD

**Issue by sherazlodhi** [facebookresearch/ParlAI#4084]
While running COLAB tutorial. There is an error becuase signature of add_cmdline_args has changed.

TypeError: Agent 'hello' appears to have signature add_cmdline_args(argparser) but we have updated the signature to add_cmdline_args(argparser, partial_opt)

The issue is in two places. I have fixed it and its copy is available here. 

https://colab.research.google.com/drive/1GTc8BEX0b5BYVLH7xzY2qExSbgqrssjj?usp=sharing

**Comment by stephenroller** [comment]
Thank you
