### ISSUE TITLE
Mturk documentation needs updates

### ISSUE THREAD

**Issue by koustuvsinha** [facebookresearch/ParlAI#410]
I am following the guides to setup [Mturk job](http://parl.ai/static/docs/mturk.html) using parlai, and found some inconsistencies in the document:

- To create 2 HITs for the QA Data Collection example with 1 assignment per HIT and $0.05 per assignment in sandbox mode, the doc instructs to run `python run.py -nh 2 -na 1 -r 0.05 --sandbox`, while there is no `nh` or `na` flag for `qa_data_collection` task, only one `nc` flag which is the number of conversations.

- Apparently a free heroku account is required to launch Mturk tasks, which is not mentioned anywhere in the docs. Is there a provision to use custom servers to launch Mturk tasks?

- Needs git config `user.email` and `user.name` set in order to run

**Comment by JackUrb** [comment]
Ah sorry, it seems the docs page isn't up-to-date with the [most recent information](https://github.com/facebookresearch/ParlAI/blob/master/docs/source/mturk.rst). Will push an update

As of now we don't have support for custom servers, however there's no particular reason why this couldn't be added in the future. An alternate function can be added to the server_utils file that  moves the required files to another server. Right now the heroku setup is called from this function, however it can be made to call another function that instead sets up the server in an alternate location.

https://github.com/facebookresearch/ParlAI/blob/8e263df74d04e69b117ae276d8e77297de239a6b/parlai/mturk/core/server_utils.py#L210

**Comment by koustuvsinha** [comment]
Thanks for the clarification! Closing this issue.
