### ISSUE TITLE
TPU usage support 

### ISSUE THREAD

**Issue by Ontopic** [facebookresearch/ParlAI#4101]
Lots of nice stuff here maintainers, thanks!

I currently see very little information on how to run different parts of ParlAI making use of a TPU. Which is understandable - since GPU is by the most common to start with - and things still work fine on just CPU. For really contributing though, and trying out training new skills, unlocking the TPU would be a huge win.

Is there any experiments or documentation I overlooked regarding TPU's? Is it perhaps an idea to centralise this information and maybe set it up with some examples?

If anyone is interested in exchanging some insights or snippers, let me know. Perhaps we can set something up as a nice start for an overview.

**Comment by evelynkyl** [comment]
I'd like to use TPU to train a model on ParlAI as well! Any ideas on how to achieve this?
