### ISSUE TITLE
Intergration

### ISSUE THREAD

**Issue by ColinChau123** [facebookresearch/ParlAI#4110]
Hello, sorry to bother but I am just wondering if you could offer any experience or information  on a question or two of mine.
So I am just wondering, about that parl ai search server, and How I could hook it up., is there any documentation I can read?

Also just wondering, would you happen to know any way to implement blenderbot 2 into a group chat based setting and could we like, idk say use outside software and inject idk words into blender bot so that I remains aware of the context and what happened last message. For example, if I added a separate like intent classification system and on some intents it would say something, would blenderbot be able to be aware or is there a way we could make blender bot aware of it.  Like for say, in a group chat setting, how could I make it differentiate between different people while keeping the same personality.
In addition, is there any way to make blender bot run with a gpu instead of the cpu to speed it up. 

Also I am sorry for asking but is there any way we can get responses to messages or anywhere i can look for this. I am potentially looking ot hook this up elsewhere outside of  facebook, the terminal etc, and is there any way to do so.

**Comment by louis030195** [comment]
Looking for documentation for that "search server" too.

In the meantime digging the whole code...

**Comment by ColinChau123** [comment]
Just wondering do any of you know how to get a response easily from PARLAI
