### ISSUE TITLE
How to add LTM to BB2 before conversation

### ISSUE THREAD

**Issue by kazeto111** [facebookresearch/ParlAI#4112]
I want to add long term memory to BB2 agent before starting the conversation.
Is there a good way to do that?

**Comment by klshuster** [comment]
1. There is currently an in-code [limit of 100](https://github.com/facebookresearch/ParlAI/blob/main/projects/blenderbot2/agents/modules.py#L691); the option `--max-memories` is not actually available but you can edit that number to bump this up (theoretically you can store as many memories as you want, just note we never experimented with more than 100).
2. `--n-docs` controls how many memories are returned by `self.access_long_term_memory`
3. computational cost from retrieving memories is currently negligible compared to generating responses with BB2
4. the query generator determines whether to retrieve from memory, or retrieve from the internet.

**Comment by kazeto111** [comment]
I see! Thank you sooo much.
I really appreciate it.
