### ISSUE TITLE
[BlenderBot 2.0] Questions about MSC data

### ISSUE THREAD

**Issue by min942773** [facebookresearch/ParlAI#4116]
I am confused of some properties of MSC dataset.

Q1. What is 'init_personas' in msc_dialogue file?
There are 5 keys in '/msc/msc/msc_dialogue/session_2/train.txt' file and I can't figure out what 'init_personas' means.

Q2. What are 'followup', 'newfact' and 'init_personachat' in msc_personasummary file?
Also I am confused what 'agg_persona_list' and 'problem_data' are..

**Comment by JeightAn** [comment]
@min942773 
Did you figure it out?
I also can't explain the difference between 'followup' and 'new_facts'.
