### ISSUE TITLE
Could anyone direct me to how to get a response out of Parl AI or a good place to understand

### ISSUE THREAD

**Issue by ColinChau123** [facebookresearch/ParlAI#4128]
Hello Sorry for taking anyone's time who is reading this but currently, I am trying to figure out how to get a response a simple response no messenger app but still use the BB2 model with the search server could anyone explain it to me.

**Comment by klshuster** [comment]
please see the docs for how to [interact with a model on the command line](https://parl.ai/docs/cli_usage.html#interactive). Discussion [here](https://github.com/facebookresearch/ParlAI/issues/3808) on how to interact with bb2 specifically.

Closing for now as this has been explored in various other issues, please let me know if you are still unable to use the model
