### ISSUE TITLE
__unk__ after fine-tuning 90M model

### ISSUE THREAD

**Issue by ai-john** [facebookresearch/ParlAI#4135]
Hey!

I have been playing around with fine-tuning the 90M model on my own dataset. When I finished fine-tuning, I ran the model and noticed that some responses contain `__unk__`. If I understand correctly, it is because those words are not in the dictionary/vocabulary of the 90M model. 

Is there a way for me to extend the tokenizer or re-train/fine-tune the tokenizer?

If not, would using a `model.dict` from 3B model + 3B model tokenizer be an option?

Thank you!

**Comment by stephenroller** [comment]
Unfortunately once a model is trained, it's very hard to change the tokenizer.

I suggest trying the 400M model, which has a tokenizer that is considerably more robust to UNKs, while still being pretty small.

**Comment by ai-john** [comment]
@stephenroller, thank you for your prompt response! Could you please give us a hint on how to find tune the 400M model? If I understand correctly, it is a 2.7B model distilled to 400M, isn't it?

Or should we just take the already trained `blender_400M` model and fine-tune on top? Previously we were fine-tuning the raw `zoo:tutorial_transformer_generator/model`

**Comment by stephenroller** [comment]
Yeah fine tune on top of `zoo:blender/blender_400Mdistill/model` instead. Note it has a lot of different options.

**Comment by ai-john** [comment]
@stephenroller I have updated the script from 90M to 400M and also updated all the parameters to match 400M. I managed to get it running and training without warnings, but whenever I run the model, responses are like this: `__unk__ __unk__ , __unk__ __unk__ es __unk__ __unk__ i __unk__ __unk__ ou __unk__ __unk__`

It feels that I am missing something fundamental, but I cannot get my head around it.

This is the code that I am running:
```
import test_teacher  # noqa: F401
from parlai.scripts.train_model import TrainModel

# https://parl.ai/projects/recipes/
TrainModel.main(
    activation="gelu",
    adam_eps=1e-06,
    attention_dropout=0.0,
    batchsize=128,
    beam_block_ngram=3,
    beam_context_block_ngram=3,
    beam_min_length=20,
    beam_size=10,
    betas=(0.9, 0.999),
    dict_file="zoo:blender/blender_400Mdistill/model.dict",
    dict_lower=True,
    dict_tokenizer="bpe",
    dropout=0.1,
    embedding_size=1280,
    ffn_size=5120,
    fp16=True,
    fp16_impl='mem_efficient',
    gradient_clip=10.0,
    inference="beam",
    init_model="zoo:blender/blender_400Mdistill/model",
    label_truncate=128,
    learn_positional_embeddings=True,
    learningrate=7e-06,
    log_every_n_secs=30.0,
    lr_scheduler="reduceonplateau",
    lr_scheduler_patience=3,
    model_file="tmp/test_train_400M",
    model="transformer/generator",
    n_decoder_layers=12,
    n_encoder_layers=2,
    n_heads=32,
    n_layers=8,
    n_positions=128,
    num_epochs=3.0,
    optimizer="mem_eff_adam",
    relu_dropout=0.0,
    save_after_valid=True,
    save_every_n_secs=-1,
    short_final_eval=True,
    skip_generation=True,
    task="test_teacher",
    text_truncate=128,
    update_freq=2,
    validation_every_n_epochs=1,
    validation_every_n_secs=1800.0,
    validation_max_exs=9920,
    validation_metric_mode="min",
    validation_metric="ppl",
    validation_patience=0,
    variant="prelayernorm",
    warmup_updates=100,
    weight_decay=0.01,
)
```

**Comment by DrMatters** [comment]
@ai-john Hello! Have you managed to fix the issue?

**Comment by stephenroller** [comment]
Switch the dict tokenizer to bytelevel_bpe and retrain (can't remember the exact value right now, on mobile). It's the same value as BB2.7B
