### ISSUE TITLE
Accessing Attention Weights of the Safety Classifier

### ISSUE THREAD

**Issue by Ninarehm** [facebookresearch/ParlAI#4139]
Hi,
Is there a way to access the attention weights of the Safety classifier from safety.py?
Thanks in advance.

**Comment by emilydinan** [comment]
Hi @Ninarehm you will have to look at the nn.module itself. The safety classifier is a transformer/classifier, which uses the [TransformerMemnetModel](https://github.com/facebookresearch/ParlAI/blob/main/parlai/agents/transformer/modules/mem_net.py) as its base model, with a linear layer on top of the context encoder
