### ISSUE TITLE
LTM seems not to be working

### ISSUE THREAD

**Issue by MichalPleban** [facebookresearch/ParlAI#4143]
I am using the following command to run the interactive dialogue script on Ubuntu 20:

`python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blenderbot2/blenderbot2_3B/model --search-server 0.0.0.0 --knowledge-access-method memory_only --memory-reader-model bert_from_parlai_rag`

However, I can't seem to see any indications that the long time memory is used, for example the bot is asking the same questions over and over again. How can I verify that the LTM is working? Where is the LTM actually stored in my filesystem?

**Comment by stephenroller** [comment]
@jxmsML can you look?

**Comment by klshuster** [comment]
the LTM is stored in RAM, not the filesystem. if you run the above with `--loglevel debug`, you should see some informative printouts regarding what is in the long term memory, and what is being retrieved during conversation
