### ISSUE TITLE
BlenderBot2 search_queries not flushed.

### ISSUE THREAD

**Issue by jxmsML** [facebookresearch/ParlAI#4145]
**Bug description**
Whenever `hasattr(self.model_api.retriever, 'search_queries')` is True, the `'search_queries'` field will be included in model act. 
However, `hasattr(self.model_api.retriever, 'search_queries')` is always `True` once the model searched in previous turns in the same episode (even if in the current turn, the model chooses to retrieve from memory not search thus no search is performed)

**Reproduction steps**
```
parlai i -mf zoo:blenderbot2/blenderbot2_400M/model --search-server XXX  --knowledge-access-method classify --query-generator-model-file zoo:sea/bart_sq_gen/model --loglevel debug
```

**Expected behavior**
If no search is performed when generating the model response in some turn, no `search_queries` and `top_docs` fields should be set in the model act

**Logs**
Please paste the command line output:

```
Output goes here
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by mojtaba-komeili** [comment]
Any update on this? I think this is what I noticed in the chatbot too.

**Comment by jxmsML** [comment]
I've merged the pr https://github.com/facebookresearch/ParlAI/pull/4198
