### ISSUE TITLE
Clarification on multi-task training for Blenderbot

### ISSUE THREAD

**Issue by mailong25** [facebookresearch/ParlAI#4155]
Let say that I want to **multi-task training** the Blenderbot on ConvAI, empathetic_dialogues, and wizard_of_wikipedia tasks.

Can the phrase "multi-task training" be interpreted as "training a **single model** with a **single objective** (generating the next response) on a **combination of the above three datasets**."?

And "multi-task" means that we just sample training data randomly from each individual dataset during training?

**Comment by klshuster** [comment]
That is a correct interpretation
