### ISSUE TITLE
Personality-Captions Dataset

### ISSUE THREAD

**Issue by aayushagrawal135** [facebookresearch/ParlAI#4160]
In the validation set for personality captions dataset, what does the attribute `candidates` mean and how is it different from the `comment` attribute? @klshuster

**Comment by klshuster** [comment]
`candidates` is the list of candidates to rank in the ranking task; `comment` is what is actually spoken by the human. The `comment` is one of the candidates within the `candidates` list; this list is what provides us with the recall@k metrics

**Comment by aayushagrawal135** [comment]
Thanks, that helps a lot.

**Comment by aayushagrawal135** [comment]
Hi @klshuster, I am using the images from the `personality caption dataset` to eventually try out various models on the encoder and decoder side. Could you tell the `mean` and the `std` values by which the images need to normalizaed before passing to the encoder?

**Comment by klshuster** [comment]
we use the transform [defined here](https://github.com/facebookresearch/ParlAI/blob/e86cc6b44dc63fedb024b9a6e618c8874ebcfcf4/parlai/core/image_featurizers.py#L101-L110)

**Comment by aayushagrawal135** [comment]
Thank you!
