### ISSUE TITLE
Where is the memory data stored in blenderbot2?

### ISSUE THREAD

**Issue by Jcwscience** [facebookresearch/ParlAI#4167]
As I understand it some of the primary reasons for creating blenderbot2 was to address some of the memory loss and hallucination issues of V1. In a nutshell this is accomplished in part by writing summarizations of the conversation to a memory file correct?

My understanding of the whole process is a little hazy.
I’ve been fiddling around with the interactive script and it seems to perform measurably worse than blenderbot1. I think in part this probably has to do with my configuration being incorrect.

For one, in a debug setting with the “—print-docs” option on, I can see it making rational notes about the conversation. For instance “partner’s persona: my name is John. I work in 3D modeling and programming”. But if I then ask “what is my name?” It doesn’t know. This might not be the target of the memory improvements I know, but it does seem like there is a disconnect.

Also I am almost certain it is not saving conversation info between sessions. I suppose this would make sense for a quick interactive demo, but how do I set the model up properly in an environment with persistent data?

Sorry if this was long winded, and thanks for any help!

**Comment by klshuster** [comment]
> writing summarizations of the conversation to a memory file

not exactly; when interacting with the model, everything the model is using is stored in RAM. to persist across "sessions", you'd need to save out a file of the conversation and load it again in the conversation. The interactive script supports an `--outfile` argument that can save this for you automatically.

as for why the model doesn't answer you correctly, there are a lot of factors going on here, including open research questions. i would say if you are having trouble with the 3B model, perhaps try the 400m model too

**Comment by Jcwscience** [comment]
@klshuster Sorry for the late reply, thanks for the explanation! I think the misunderstanding of how the process works is what caused me confusion.

**Comment by klshuster** [comment]
Ok, I will close for now then, please reopen if you have any further concerns
