### ISSUE TITLE
chat services hangs on loading existing model params 

### ISSUE THREAD

**Issue by zhudanmeng** [facebookresearch/ParlAI#4170]
I'm trying to replicate #3174, but after getting everything set up and running the command for websocket chat service, my machine hangs on "Loading existing model params" forever. I'm only using the blender1B distilled model, which runs quite well when I use interactive.py so I'm guessing it's not a problem with the processing power of my VM. 

I'm thinking the issue has something to do with websocket_manager.py and ascynio, but not completely sure what the problem is. Note that I haven't been able to run chat services locally either since I have a windows machine and can't install the fcntl library, so I can only try it on the VM. 

Appreciate any help!

![ec2](https://user-images.githubusercontent.com/36681583/141670787-000cc631-3f2f-428a-b090-102de24a9bd6.png)

**Comment by klshuster** [comment]
at the moment there is unfortunately no message that indicates the "load" is done. see how long it takes to load in interactive and then wait that amount of time before trying to chat

**Comment by ankepand** [comment]
Facing this issue.
Tried the interactive script, it works perfectly but gets stuck at "Loading Existing params" when using websocket/run.py
Waited for sufficient time for loading to happen ~30 mins.
This is the config I am using
```
tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    blenderbot2_400M:
      model: projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent
      model_file: zoo:blenderbot2/blenderbot2_400M/model
      override:
       search_server: 0.0.0.0:8080
```

**Comment by klshuster** [comment]
like i mentioned above: there is currently no message that indicates loading is done. just try messaging the script after a few minutes and see what happens

**Comment by ankepand** [comment]
I tried and getting 
`websocket._exceptions.WebSocketBadStatusException: Handshake status 404 Not Found`
on client-side and
`[W 220127 14:55:55 web:2250] 404 GET / (127.0.0.1) 0.50ms`
on server-side
Message format is this
`message_from_user = {
  "mid": 105,
  "recipient": {
    "id": 302
  },
  "sender": {
    "id": 555
  },
  "text": "hi",
  "attachment": None
}`
I am kind of stuck at this point. if you could help me debug this. I will be happy to contribute.

**Comment by ankepand** [comment]
I might be doing something wrong from client-side. pls have a look at my client.py

`from websocket import create_connection
wb = create_connection('ws://localhost:8090')

message_from_user = {
  "mid": 105,
  "recipient": {
    "id": 302
  },
  "sender": {
    "id": 555
  },
  "text": "hi",
  "attachment": None
}

while True:
        message_from_user["text"] = input("User: ")
        wb.send(message_from_user)
        message_from_bot = wb.recv()
        print("Bot: {}".format(message_from_bot["text"]))

wb.close()`

corresponding server command
`python parlai/chat_service/services/websocket/run.py --config-path parlai/chat_service/tasks/chatbot/config.yml --port 8090`

**Comment by ankepand** [comment]
was able to make it work by modifying browser_chat/client.py. Thanks!
