### ISSUE TITLE
[wizard_of_internet] questions about the performance and metrics of WizInt Transformer

### ISSUE THREAD

**Issue by Vonderland** [facebookresearch/ParlAI#4192]
Hi!
The idea of using search engine to augment dialogue generation is really fancy and practical! 
Now I am trying to reproduce the experiments in the paper and utilize the WizInt Transformer as the baseline without knowledge for comparison. I use code from the latest main (where the lastest commit is https://github.com/facebookresearch/ParlAI/commit/f1a46aad3dbae55f8a7f8aaa70b2330135c23e35), with the following command (command from the project page, just adding --skip-generation False to get the F1s):

`parlai eval_model -mf zoo:sea/bart_base/model -t wizard_of_internet -dt valid -bs 4 --skip-generation False
`

to evaluate the model.

Here are the metrics I've got:
11:48:35 | Finished evaluating tasks ['wizard_of_internet'] using datatype valid
    accuracy  bleu-4  clen  ctpb  ctps  ctrunc  ctrunclen  exps  exs    f1  gpu_mem  \
           0 .003139 141.7   569 741.6 .007983      1.081 5.201 2881 .1526   .02861   
    knowledge_f1_docs  knowledge_f1_max_docs  knowledge_f1_max_sentences  knowledge_f1_sentences  \
               .02052                 .02049                      .02049                  .06354   
    llen  loss  ltpb  ltps  ltrunc  ltrunclen  ppl  token_acc  token_em   tpb   tps  
   23.95 2.856 95.37 124.3 .001388     .04964 17.4      .4113         0 664.3 865.9

where the ppl is 17.4 and f1 is 15.26. 
But in the paper and project page, the F1 of  WizInt Transformer is 17.6. Should I edit or change something to get the expected performance as shown in the paper?
By the way, which of those knowledge f1 something (like knowledge_f1_docs, knowledge_f1_sentences) is the "KF1" claimed in the paper and the project page?

Looking forward to your reply!!! Thanks again for sharing the ideas and codes!

**Comment by klshuster** [comment]
You'll need to set the generation settings to the following: `--inference beam --beam-min-length 20 --beam-size 3 --beam-block-ngram 3`. I believe `knowledge_f1_sentences` is the appropriate KF1 metric

**Comment by Vonderland** [comment]
> You'll need to set the generation settings to the following: `--inference beam --beam-min-length 20 --beam-size 3 --beam-block-ngram 3`. I believe `knowledge_f1_sentences` is the appropriate KF1 metric

I got it. By the way, as for WizInt Search engine FiD, are the above generation settings also needed for getting much closer performance to the paper?

Thank you!

**Comment by klshuster** [comment]
Yeah, those are the generation settings for nearly every result in the paper, unless otherwise specified
