### ISSUE TITLE
[Image_chat] some questions about Image Chat

### ISSUE THREAD

**Issue by watermelon-lee** [facebookresearch/ParlAI#4203]
Hi！
Thanks for you fancy idea in Image Chat paper. It's really useful for me!
I am trying reproduce the experiments in paper and here're my problems.

I do not found the transformer which pretrained in reddit database, so I use bert(roberta) instead.  Here are my results and your resluts in the paper:

Text Encoder          |  Image Encoder   | Turn 1 R@1 | Trun 2 R@1 | Turn 3 R@1
reddit transofrmer |  ResNext-IGi3.5B  | 54.0             | 51.9             | 44.8
bert                        | ResNext-IGi3.5B   | 43.8             | 48.6             | 44.7
roberta                   |ResNext-IGi3.5B   |  45.0            | 52.0              | 46.6

As you can see, The first turn R@1 in you paper can reach 54%, but my resulut(bert or roberta) only scoring 45%.  
Could you provided me the reddit pretrained transfomers for me or the entire TransResNet model(ResNext-IGi3.5B edition) for me? I only find the TransResNet model(ResNet152 edition) in your model zoo ( zoo:image_chat/transresnet_multimodal/model).
Looking forward for you reply. Thanks!!! @klshuster

**Comment by klshuster** [comment]
for your BERT and RoBERTa results, which image features are you using? Those are most likely the causes of your performance degradations.

**Comment by watermelon-lee** [comment]
> for your BERT and RoBERTa results, which image features are you using? Those are most likely the causes of your performance degradations.

Thanks for you reply!
I use the  [ResNext-WSL(ResNext101 32x48d)](https://pytorch.org/hub/facebookresearch_WSL-Images_resnext/) as Image encoder. And The representation the image is obtained by using the 2048-dimensional output of the image encoder as input to a feed-forward network, just as you paper mentioned.

**Comment by klshuster** [comment]
The features linked are from a model trained on fewer images (960M) compared to the one we used with the paper (3.5B), the features for which we unfortunately are unable to release. The features you use are better than ResNet152 though

**Comment by watermelon-lee** [comment]
I got it~
I only noticed the same names(ResNext101 32x48d) but ignored model description(The provided ResNeXt models are pre-trained in weakly-supervised fashion on 940 million public images) 
Thank you!

**Comment by klshuster** [comment]
No problem, will close as this is resolved but feel free to reopen if there are any further concerns
