### ISSUE TITLE
ACUTE-Eval config parameters meaning

### ISSUE THREAD

**Issue by c00k1ez** [facebookresearch/ParlAI#4206]
Hi everyone!
Im trying to run ACUTE-Eval pipeline with [acute_eval/fast_run.py](https://github.com/facebookresearch/ParlAI/blob/main/parlai/crowdsourcing/tasks/acute_eval/fast_eval.py) on MTurk but find some issues:
* How I can define max number of conversations for ACUTE-eval?
* Where I can find parameter for number of workers per sample?

In general Its not enough information about config parameters meaning. Do you have any docs about it?
THank you!

**Comment by klshuster** [comment]
Hi there, you can find information about general ACUTE config parameters [here](https://github.com/facebookresearch/ParlAI/blob/d1ab7af9c4ed6cc825832550de474d548688bc39/parlai/crowdsourcing/tasks/acute_eval/acute_eval_blueprint.py#L31), and about fast ACUTE args [here](https://github.com/facebookresearch/ParlAI/blob/main/parlai/crowdsourcing/tasks/acute_eval/fast_acute_blueprint.py)
