### ISSUE TITLE
Include an example script to train blenderbot2.0

### ISSUE THREAD

**Issue by rguan1** [facebookresearch/ParlAI#4209]
Hi,

I am having some trouble finetuning blenderbot2.0. For blenderbot1.0, there were a list of helpful commands [here ](https://parl.ai/projects/recipes/) that give you the parameters needed to train blenderbot. However, there is no equivalent reference for [blenderbot2.0](https://parl.ai/projects/blenderbot2/), and so far, I've been unable to get Blender2.0 to finetune on a task. Would you happen to have an example training command for blenderbot2.0? Thanks!

**Comment by daje0601** [comment]
Hello,
Here is hyperparemter tuning value link 
`https://github.com/facebookresearch/ParlAI/blob/main/parlai/zoo/blenderbot2/model_card.md`

**Comment by rguan1** [comment]
Thanks!
