### ISSUE TITLE
Is it possible to output the confidence level BlenderBot2 has while responding to a question?

### ISSUE THREAD

**Issue by krrishdholakia** [facebookresearch/ParlAI#4210]
BlenderBot2 is great but definitely has moments where it responds incorrectly to a question. I'd like to understand if it's possible to output it's confidence level for each response - to judge if there is a way to catch for this.

**Comment by klshuster** [comment]
BB2 does not have an explicit confidence level for the responses. If you run `parlai display_model` with the verbose flag (so, `parlai display_model -v`, you'll be able to see the beam scores.

For example, if you run `parlai dm -mf zoo:blenderbot2/blenderbot2_400M/model --rag-retriever-type dpr --retriever-debug-index compressed -t wizard_of_wikipedia -v`, you'll see the following output for each example, where the `beam_texts` shows the beam generations and their corresponding scores (i.e., losses):


![image](https://user-images.githubusercontent.com/8562788/143963021-9c274420-5ac3-4a81-bd25-fbf199ee854b.png)
