### ISSUE TITLE
Clarification of the data licenses

### ISSUE THREAD

**Issue by shuki-hpcnt** [facebookresearch/ParlAI#4211]
Hello,

There are some datasets in ParlAI that are released by the ParlAI group or facebookresearch group AFAIK, but some datasets do not clarify the license for the usage of the dataset.

Could you clarify the data license of the following datasets?
- `ConvAI2`
- `msc`
- `style_gen`
- `wizard_of_wikipedia`
- `wizard_of_internet`

Thanks in advance! 🙏

**Comment by stephenroller** [comment]
Just adding in here: we recently started putting licenses into different task folders, and have also relicensed some of our datasets under more liberal terms (allowing for commercial use)

**Comment by shuki-hpcnt** [comment]
Thanks for the update! I've checked out that license of most of the datasets listed above have been clarified as CC-BY-4.0. 👍

**Comment by albusdemens** [comment]
Hi, I just checked and I couldn't find any license for the `msc` dataset. Is it also covered by CC-BY-4.0? Thanks!
