### ISSUE TITLE
How can I have a look on generated texts?

### ISSUE THREAD

**Issue by WilliamsToTo** [facebookresearch/ParlAI#4215]
I'm working on [msc project](https://parl.ai/projects/msc/#getstarted).
When I evaluation the model using the following link. It outputs some metric results. But I want to view the real generated texts. How can I do it?

_parlai eval_model -mf zoo:msc/msc3B_1024/model -t msc -dt valid -bs 16 --previous-persona-type raw_history_

**Comment by stephenroller** [comment]
Use display_model instead of eval_model. Or, if you want to see all predictions, take a look at the --world-logs argument
