### ISSUE TITLE
How do I train or interactive a model with ParlAI in Python scripts instead of command line?

### ISSUE THREAD

**Issue by LiShaoyu5** [facebookresearch/ParlAI#4226]
Are there Python APIs to load, train and use models?

**Comment by stephenroller** [comment]
- all of our cli scripts can be imported and called with like TrainModel.main(cli_arg="value")
- you can also use `create_agent_from_model_file` to load up a model and then interactive with either `observe`, `act`, `reset` or `respond`

**Comment by LiShaoyu5** [comment]
> 

Thank you!
