### ISSUE TITLE
Maintaining every user's history. 

### ISSUE THREAD

**Issue by MAlliHaider** [facebookresearch/ParlAI#4231]
Hello there,

Respected @stephenroller  @klshuster @emilydinan and others!

I'm having a wonderful time with ParlAI chat bot. I really want to appreciate your work and I'm very impressed with your efforts to serve the community. 
But I actually get stuck with an issue in ParlAI chat bot. I want to save every user's history separately, so that whenever a particular user exits communication with chat bot it will save it's log, session or history. So, when he/she backs again for communication, conversation will get continue right from where it ended with him/her last time.

Looking for your Response.

Thanks in advance.

**Comment by stephenroller** [comment]
You can access this in `agent.history`.

**Comment by MAlliHaider** [comment]
Thanks @stephenroller  sir, it helped me alot.

**Comment by renzs6** [comment]
Hi @MAlliHaider , how did you save the conversation and reuse it to continue the conversation?
