### ISSUE TITLE
How to create a post-task survey in MTurk

### ISSUE THREAD

**Issue by nhattlm95** [facebookresearch/ParlAI#4234]
Hi, I am working on a crowdsourcing task similar to image chat and I want to collect some data using Mturk.

At the moment, I use the onboarding word as a pre-task survey, but I also want a post-task survey after the conversation. Specifically, after the workers finish chatting and click Done, they should see a new page with some questions.

Is there any easy way to implement it in the current parlAI framework?

Appreciate any help!

**Comment by stephenroller** [comment]
We've been talking about such things recently. @EricMichaelSmith so you have pointers?

**Comment by EricMichaelSmith** [comment]
Hi @nhattlm95 ! See the `parlai/crowdsourcing/tasks/model_chat/` and `parlai/crowdsourcing/projects/wizard_of_internet/` tasks: these both allow for asking the worker questions via a form at the end of the task. However, these display the form at the bottom of the chat window as opposed to on a separate page. Would this be sufficient for you?

**Comment by nhattlm95** [comment]
@EricMichaelSmith 
Yeah, I know that, but the area at the bottom of the chat window is too small for me since I have quite a few questions in the survey. It would be better if I can show them a new page for the questionnaire.

**Comment by EricMichaelSmith** [comment]
Hmm - maybe @JackUrb @pringshia might have templates on adding a new page after the main task?
