### ISSUE TITLE
How to load the parameter files of a model trained on HuggingFace for MTurk

### ISSUE THREAD

**Issue by Stefan1220** [facebookresearch/ParlAI#4235]
Hi,

I am working on model_chat task in crowdsourcing of ParlAI using Mephisto. I am wondering if it is possible that I can use a model trained on HuggingFace as an agent? If so, any documentation that I can refer to about how to load the external model as an agent and how to transform the model parameter files on HuggingFace to the format used on ParlAI?

Appreciate your help!

**Comment by ajyl** [comment]
I'm having the same issue -- is it only possible to interact with models in the Zoo or am I able to use a local model?

**Comment by klshuster** [comment]
we have several example huggingface models in the [huggingface agent directory](https://github.com/facebookresearch/ParlAI/tree/main/parlai/agents/hugging_face), which might be useful
