### ISSUE TITLE
Utility to strip optimizer from a trained/fine-tuned model

### ISSUE THREAD

**Issue by drevicko** [facebookresearch/ParlAI#4241]
When you train a model or fine-tune one of the zoo models, the resulting model saves include the optimizer parameters, which makes them substantially larger.

It would be great if there was a utility to strip out the optimizer parameters from a model file (as has been done for the zoo models) to save space when deploying them.

**Comment by stephenroller** [comment]
`parlai vacuum` is what you're looking for

**Comment by drevicko** [comment]
Many thanks.
