### ISSUE TITLE
Freeing GPU Memory after conversation in Chat Service

### ISSUE THREAD

**Issue by jh-skaion** [facebookresearch/ParlAI#4255]
Is there a way to free the memory after a conversation finish? 

i notice that starting server with the model blender_1Bdistill it takes around 4GB. when a conversation start, the memory grows to 4.5GB and after the conversation finishes it still shows as 4.5GB. i tried model.shurdown and agent.shutdown but there were no changes in memory.

Thanks

**Comment by stephenroller** [comment]
PyTorch holds onto the memory bc it's faster to reuse than to grab more. There should be some PyTorch method for purging the cache.
