### ISSUE TITLE
how to accelerate bb2 model and decrease inference time?

### ISSUE THREAD

**Issue by andysun-sw** [facebookresearch/ParlAI#4257]
I use bb2 2.7B model for chat with 4 gpu with following command:
parlai interactive -mf zoo:blenderbot2/blenderbot2_3B/model --search-server relevant_search_server --knowledge-access-method memory_only
 response time is 20 second. How to decrease below to 100ms?  
I found several ways, which way do you think possible?
1,TensorRT(https://github.com/NVIDIA/TensorRT)
2, knowledge disstilation

**Comment by mojtaba-komeili** [comment]
An easy way for you might be using the lighter version of BB2 with 400M parameters ([here](https://parl.ai/docs/zoo.html#blenderbot2-400m)) instead of distillation. You may upgrade your GPUs as well. We know of cases that can get a turn around time of 2-3 seconds on AWS g4dn instances with the same model you used.

**Comment by klshuster** [comment]
Additionally, chatting on one gpu might be better --> model parallel can slow down generation in some cases

**Comment by andysun-sw** [comment]
why don't you think it is impossible to use tensorRT? think how wonderful to speed up 20 times without degrading performance?
I just don't know how to change parlai model to ONNX. who can tell me?

**Comment by andysun-sw** [comment]
@mojtaba-komeili enlight me to think how to choose between a small pretrained model and a model distilled from a large model.
My estimate is a model distilled from a large model is better than a small pretrained model if they have same parameters. The reason is the model distilled from a large model can gain more dark knowledge.

**Comment by mojtaba-komeili** [comment]
> @mojtaba-komeili enlight me to think how to choose between a small pretrained model and a model distilled from a large model. My estimate is a model distilled from a large model is better than a small pretrained model if they have same parameters. The reason is the model distilled from a large model can gain more dark knowledge.


A distilled model might end up having better performance with the same number of parameters.  But as I mentioned in my comment using our smaller model is "an easy way" you can have a lighter version of BB2 that works with no extra cost.

**Comment by stephenroller** [comment]
TensorRT would probably speed up inference, but probably wouldn't work with beam blocking.

**Comment by sjscotti** [comment]
@stephenroller @klshuster @andysun-sw 
If you find a good way to speed up inference with BB2_3B, please provide some info on how it is done.  I am finding when using a tuned BB2 model (that is also doing internet searches) that a typical response takes about 5 minutes on my Windows desktop. My machine is admittedly under powered, having only an 8GB GPU so it is also using about 12GB of shared (virtual) GPU memory for the model.  (BTW, I am also using `--model projects.blenderbot2.agents.blenderbot2:BlenderBot2RagAgent --rag-model-type sequence` to reduce hallucination per recommendation from @klshuster , but this increases GPU memory requirements over the default options for BB2_3B by about 4GB.)
Thanks!
