### ISSUE TITLE
Where is the MTurk data saved?

### ISSUE THREAD

**Issue by sivareddyg** [facebookresearch/ParlAI#426]
Hi team, I am trying to figure out how to access data collected using ParlAI MTurk functionality. I am using DealNoDeal setup. In the Amazon requester interface, I went to "Manage Hits Individually" and downloaded the "Results CSV" file. I only see one row in it with no conversation data. ParlAI log file contains conversation log, but do you store the data somewhere else in a structured format?

Thanks,
Siva

**Comment by JackUrb** [comment]
Hi Siva - none of the conversation data is actually stored on the MTurk side so we suggest storing the data into an array during parley calls and then saving that array in the `world.shutdown` call. We should probably clarify this in the docs, as currently none of our examples display this behavior.

**Comment by sivareddyg** [comment]
thanks for letting me know, that's very helpful!

**Comment by JackUrb** [comment]
Of course! As of now we only automatically save the conversation log. The structured data is most easily collected by just appending the incoming acts to an array that is saved during shutdown (that's how I've used it in the past at least) though you're also free to process it in the world if you want something different!
