### ISSUE TITLE
What images do we use when interacting with Multi-Modal BlenderBot?

### ISSUE THREAD

**Issue by linhaowei1** [facebookresearch/ParlAI#4260]
Thanks for your brilliant works!
I am running Multi-Modal BlenderBot, directly running the command provided by <https://github.com/facebookresearch/ParlAI/blob/master/parlai/zoo/multimodal_blenderbot/README.md> as follows.
```
python parlai/scripts/safe_interactive.py \
-t blended_skill_talk \
-mf ${FINETUNED_MODEL_PATH} \
--model projects.multimodal_blenderbot.agents:BiasAgent \
--delimiter $'\n' \
--beam-block-ngram 3 \
--beam-context-block-ngram 3 \
--beam-min-length 20 \
--beam-size 10 \
--inference beam \
--model-parallel False
```
Since it's in a multimodal scenario, I think there must be images as input. However, I am wondering what images do we use here? Can I assign my own image datasets?
It'll be highly appreciated if you can reply at your earliest convenience. Thanks again!

**Comment by klshuster** [comment]
We currently do not support sending images in `interactive` mode; you can, however, evaluate the model with your own dataset

**Comment by linhaowei1** [comment]
Got it. Thanks!
