### ISSUE TITLE
How to train poly-encoder with huggingface transformers pre-trained model.

### ISSUE THREAD

**Issue by sooftware** [facebookresearch/ParlAI#4263]
Hi! First of all, thank you for managing this wonderful project.

I have a question about training. It is too difficult for me to grasp the overall project structure. 😂  
I want to train the dialogue retrieval model (poly-encoder) with a hugging face pre-trained model.  
How can I??  
  
I think I need to revise the following.  
  
1. Change the poly-encoder's encoder to my transformers model.   
2. Change the tokenizer to my transformers tokenizer.
3. Train Model.

To do so, first, I changed the poly-encoder's code like follows:

```python
from transformers import AutoModel


class PolyencoderAgent(TorchRankerAgent):
    ...
    ...

    def get_encoder(self):
        return AutoModel.from_pretrained('my-encoder-model')

    ...
    ...
```

Then, I tried to change the tokenizer that fits the model, but I don't know where to change it. 😂. 
  
And assuming that the above has been resolved, the following learning code was created.  
  
- train.txt
```
text:I'm Soohwan Kim.   labels:Awesome!
text:I am playing games.   labels:good good!   episode_done:True
text:Parl-AI is Awesome!!   labels:That's right!
text:Have you ever used it?   labels:Of course!   episode_done:True
text:Do you build a snowman?   labels:No!
text:Okay bye...  labels:..   episode_done:True
```
- train.py

```python
from parlai.scripts.display_model import DisplayModel
from parlai.scripts.train_model import TrainModel
from parlai.core.teachers import register_teacher, DialogTeacher
from parlai.core.agents import register_agent, Agent


@register_teacher("poly_teacher")
class PolyTeacher(DialogTeacher):
    def __init__(self, opt, shared=None):
        # opt is the command line arguments.

        # What is this shared thing?
        # We make many copies of a teacher, one-per-batchsize. Shared lets us store

        # We just need to set the "datafile".  This is boilerplate, but differs in many teachers.
        # The "datafile" is the filename where we will load the data from. In this case, we'll set it to
        # the fold name (train/valid/test) + ".txt"
        # opt['datafile'] = opt['datatype'].split(':')[0] + ".txt"
        opt['datafile'] = 'train.txt'
        print("__init__: ", opt['datafile'])
        super().__init__(opt, shared)

    def setup_data(self, datafile):
        # filename tells us where to load from.
        # We'll just use some hardcoded data, but show how you could read the filename here:
        print(f" ~~ Loading from {datafile} ~~ ")

        with open(datafile) as f:
            new_episode = True

            for line in f.readlines():
                splits = line.split('   ')

                if len(splits) == 3:
                    yield (splits[0].replace('text:', ''), splits[1].replace('labels:', '')), new_episode
                    new_episode = True
                else:
                    yield (splits[0].replace('text:', ''), splits[1].replace('labels:', '')), new_episode
                    new_episode = False


DisplayModel.main(task='poly_teacher', model='poly')
TrainModel.main(
    model='transformer/polyencoder',
    task='poly_teacher',
    batchsize=32,
    validation_every_n_secs=10,
    max_train_time=60,
    cands='batch',
    eval_candidates='batch',
)
```

Am I right? I would appreciate it if you could give me advice on what I couldn't solve and what I was wrong.  
  
Thank you.

**Comment by klshuster** [comment]
Hi there, you're definitely on the right track but it's a bit more nuanced than that. I'll try to outline the steps below; to keep things as simple as possible, I'll assume all code will be within `train.py`.

1. Create a new Polyencoder "module" that will use the huggingface pre-trained model. This is where `get_encoder` is defined.

```python
from transformers import AutoModel
from parlai.agents.transformer.polyencoder import PolyEncoderModule

class MyPolyEncoderModule(PolyEncoderModule):
    ...
    def get_encoder(self, opt, dict_, null_idx, reduction_type, for_context: bool):
        """ 
        Note: for_context is a boolean indicating whether this is the context 
        or candidate encoder in the Poly-encoder setup
        """
        return AutoModel.from_pretrained('my_encoder_model')
```
2. Create a `DictionaryAgent` that builds your own tokenizer. ParlAI already has support for tokenizers from HuggingFace, so you'll only need to subclass [HuggingFaceDictionaryAgent](https://github.com/facebookresearch/ParlAI/blob/main/parlai/agents/hugging_face/dict.py)) and override two methods and two properties:

```python
from parlai.agents.hugging_face.dict import HuggingFaceDictionaryAgent

class MyDictionaryAgent(HuggingFaceDictionaryAgent):

    def get_tokenizer(self, opt):
        """ 
        Instantiate and return the HF tokenizer (e.g. via .from_pretrained())
        """

    def override_special_tokens(self, opt):
        """
        If you want to override special tokens, you can do so here. See the linked file for other examples of this
        """

    def add_special_tokens(self) -> bool:
        """
        Whether to add special tokens when tokenizing
        """

    def skip_decode_special_tokens(self) -> bool:
        """
        Whether to skip decoding of special tokens when converting to text.
        """
```

3. Create a new `Agent` class that subclasses the `PolyencoderAgent`. Here, you'll override `build_model` and `build_dictionary` to use the modules implemented above.

```python
from parlai.agents.transformer.polyencoder import PolyencoderAgent
from parlai.core.agents import register_agent


@register_agent('my_polyencoder')
class MyPolyencoderAgent(PolyencoderAgent):
    ...

    def build_model(self, states=None):
        """
        Return built model.
        """
        return MyPolyEncoderModule(self.opt, self.dict, self.NULL_IDX)

    def build_dictionary(self):
        """
        Return built Dictionary
        """
        return MyDictionaryAgent(self.opt)
````

Then, your `TrainModel` command might look like:

```python
TrainModel.main(
    model='my_polencoder',
    task='poly_teacher',
    batchsize=32,
    validation_every_n_secs=10,
    max_train_time=60,
    cands='batch',
    eval_candidates='batch',
)
```



The only issue you may run into is that the current code assumes that the context encoder is called via `self.encoder_ctxt(input=input_vec)`, and returns [both a representation and a corresponding mask](https://github.com/facebookresearch/ParlAI/blob/66c71e01b79b118a717c1115fecea5e99b12429a/parlai/agents/transformer/polyencoder.py#L475). You can override the kwarg input to the context encoder by overriding the [`_context_encoder_input`](https://github.com/facebookresearch/ParlAI/blob/66c71e01b79b118a717c1115fecea5e99b12429a/parlai/agents/transformer/polyencoder.py#L513) method in `MyPolyencoderModule`. Additionally, it is assumed that the candidate encoder outputs [only a representation](https://github.com/facebookresearch/ParlAI/blob/66c71e01b79b118a717c1115fecea5e99b12429a/parlai/agents/transformer/polyencoder.py#L466) (no mask).

Please let me know if you have any questions.

**Comment by sooftware** [comment]
Thank you for your answer! I'll try!

**Comment by r1ckC139** [comment]
Hi @klshuster, @sooftware 
if i want to train poly_encoder with my own dataset where can i pass my dataset file and what format should it be ?

**Comment by klshuster** [comment]
Please see [this tutorial](https://parl.ai/docs/tutorial_task.html) for how to add a task to ParlAI. I suggest you also check out the [quick start guide](https://parl.ai/docs/tutorial_quick.html)
