### ISSUE TITLE
how to change window size of bb2?

### ISSUE THREAD

**Issue by andysun-sw** [facebookresearch/ParlAI#4266]
Use this to open other questions or issues, and provide context here.

**Comment by andysun-sw** [comment]
I use the following command to interactive with bb2, 
parlai interactive -mf zoo:blenderbot2/blenderbot2_3B/model --search-server relevant_search_server --knowledge-access-method

finding the memory of bb2 is shot, I think one way to have long memory is to enlarge the windonw size, but there are several parameters relavent to window size and I don't know how to differentiate them(https://github.com/facebookresearch/ParlAI/blob/master/parlai/zoo/blenderbot2/model_card.md):
n_positions,truncate,text_truncate

**Comment by klshuster** [comment]
if by window size you mean context fed to the model, then yes, `--text-truncate` and `--truncate` are the way to go; note that `--n-positions` can be no less than the truncation or you will run into some errors

**Comment by andysun-sw** [comment]
@klshuster what's the difference between --text-truncate and --truncate, I can't find in the parlai tutorial

**Comment by andysun-sw** [comment]
@klshuster I tried, but find n-positions should be no more than the truncation. 
And I don't find it is useful to enlarge --text-truncate or --truncate

**Comment by klshuster** [comment]
> what's the difference between --text-truncate and --truncate, I can't find in the parlai tutorial

there are three flags: `--truncate`, `--text-truncate`, and `--label-truncate`. `--text-truncate` refers to input context truncation, and `--label-truncate` refers to the decoded response truncation. If neither is set, they default to the `--truncate` option.

> will run into errors if I changed to 256,1024,2048 or 314

If you use the 400M model, this won't be an issue
