### ISSUE TITLE
Base model in task dodecadialogue. 

### ISSUE THREAD

**Issue by gydpku** [facebookresearch/ParlAI#4279]
Do you have a plan to release the base_model(pretrained on the Reddit dataset)? I want to fine-tune it but the system shows:'ModuleNotFoundError: No module named 'parlai.zoo.dodecadialogue.base_model'.

**Comment by stephenroller** [comment]
The base model for the dodeca paper is the exact same model as the 90M parameter model in the BlenderBot 1 paper

**Comment by gydpku** [comment]
Ok, But when I run ’parlai train_model -m image_seq2seq --init-model zoo:blender/blender_90M -mf /home/base -t wizard_of_wikipedia -bs 24 --fp16 true  --text-truncate 1024 --label-truncate 128 ‘.  
the system shows:‘AttributeError: module 'parlai.zoo.blender.build' has no attribute 'download’‘ and 'Could not find pretrained model in parlai.zoo.blender.build or parlai.zoo.blender.build. Please check your spelling and make sure you've pulled from master.'

Could you give me a correct example to download and run it?

**Comment by stephenroller** [comment]
Instructions are here https://parl.ai/projects/recipes/

**Comment by gydpku** [comment]
OK, I can eval/interact with this pre-trained model now. But when I want to fine-tune the pre-trained model, the system shows 'size mismatch for decoder.layers.1.norm3.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([300]).
'
My code is 'parlai train_model -t wizard_of_wikipedia --init_model zoo:blender/blender_90M/model -bs 24 -eps 1 -mf /home/base_model -m image_seq2seq --fp16 true'

I change the option '-m  image_seq2seq' with '-m bart' or '-m transformer/generator', but it still doesn't match. Could you tell me the correct model for this pre-trained model?
