### ISSUE TITLE
Flask demo

### ISSUE THREAD

**Issue by hafsaEn** [facebookresearch/ParlAI#4281]
Is there a flask demo of the conversational system instead of the terminal? Thanks

**Comment by mojtaba-komeili** [comment]
Have you tried the [Browser Chat](https://github.com/facebookresearch/ParlAI/tree/main/parlai/chat_service/services/browser_chat)?

**Comment by khushaljethava** [comment]
I have done it, also requested the Pull request. Feel free to review it @mojtaba-komeili

**Comment by khushaljethava** [comment]
Try this for flask demo
 https://github.com/khushaljethava/parlai_flask
