### ISSUE TITLE
image_chat dataset in the task "#Dodeca"

### ISSUE THREAD

**Issue by gydpku** [facebookresearch/ParlAI#4285]
Can I skip the image_chat dataset/task when I train my model in the task of "#Dodeca"? The download of each image individually from the s3 server spends me lot of time.  Also, the task "image_chat" is not necessary for my project.

**Comment by klshuster** [comment]
If it's not necessary for your purposes then feel free to omit it

**Comment by gydpku** [comment]
> If it's not necessary for your purposes then feel free to omit it

So how can I train my model only with the other nine tasks when I set the task option as '#Dodeca'?

**Comment by klshuster** [comment]
You could set `--task comma,separated,task,names` with the tasks [listed here](http://parl.ai.s3-website.us-east-2.amazonaws.com/docs/tasks.html#dodeca-tasks)
