### ISSUE TITLE
how to use one gpu to parlai interactive ?

### ISSUE THREAD

**Issue by andysun-sw** [facebookresearch/ParlAI#4288]
I use bb2 2.7B model for chat with 4 gpu with following command:
parlai interactive -mf zoo:blenderbot2/blenderbot2_3B/model --search-server relevant_search_server --knowledge-access-method memory_only

but 4 gpu Not fully utilized，so I want to know:
which CLI Arguments are used to set gpu?

i have used the following command, didn't work:
export NVIDIA_VISIBLE_DEVICES=1

**Comment by stephenroller** [comment]
CUDA_VISIBLE_DEVICES=1 would've worked. Additionally `--model-parallel false` should've worked.
