### ISSUE TITLE
Default python version recognized as python2.7 when running ./setup.sh

### ISSUE THREAD

**Issue by gmkim90** [facebookresearch/ParlAI#43]
First of all, thanks for share this awesome library. 

This is a very novice question.

When I run setup.sh it seems that the program capture default python version as 2.7.
ex) sudo ./setup.sh
Creating /usr/local/lib/python2.7/dist-packages/parlai.egg-link (link to .)

This make error when running base_train.py on Opensubtitles dataset.

I have python3.5 as well in my Ubuntu 14.04 machine, and python in bash link to python3.5 (not python2.7).

Any hints? 
I really appreciate your answer.

**Comment by PaulRenvoise** [comment]
In `setup.sh`, there's a line saying: 
```
--sometimes this won't work properly if you have python aliased
```

What you can do is to run the two commands inside `setup.sh` in your terminal, namely:

`[sudo] pip[3] install -r requirements`
and
`python[3.5] setup.py develop`

Hope that helps

**Comment by gmkim90** [comment]
It works. 
Thank you.
