### ISSUE TITLE
Problem trying to use chat services on windows

### ISSUE THREAD

**Issue by alexvaca0** [facebookresearch/ParlAI#4305]
When trying to use terminal chat or browser chat the following error occurs:

```ModuleNotFoundError: No module named 'fcntl'```

I'm trying to use a chat service so that other processes can communicate with blenderbot via python requests, what possible solution exists? @klshuster

**Comment by alexvaca0** [comment]
you cannot pip install that package on windows... that's the problem. However, that package is not actually needed. I did a hack: 

go to ParlAI\parlai\chat_service\services\messenger\__init__.py and ParlAI\parlai\chat_service\utils\server.py and change `import sh` for `import shutil`. Where sh is used for removing server path (`sh.rm(shlex.split('-rf ' + local_server_directory_path))`) we need to change it for `shutil.rmtree(local_server_directory_path)` in functions **setup_local_server** and **delete_local_server**.

This could be integrated in parlai easilly with a check; e.g 

```{python}
if os.name == "nt":
   # do staff as in windows
else:
   # do staff as in linux
```

When i recover from wrist surgery and can code w 2 hands i'll make a pull request.

**Comment by stephenroller** [comment]
We would welcome a PR
