### ISSUE TITLE
Conversation history in the memory.

### ISSUE THREAD

**Issue by castalta** [facebookresearch/ParlAI#4308]
In case of  "history_size" : 1, the number of the conversation history in the cache memory is always 1?
(The second oldest conversation history be deleted all the time.)

Or Inference calculation uses 1 conversation history, but is all conversation history still in the cache?

**Comment by stephenroller** [comment]
IIRC we actually purge the messages from the cache in the History object, and inference blindly trusts whatever its cache says. You can see it in torch_agent.py.

**Comment by castalta** [comment]
Thank you for your answer!
I see it.

**Comment by Tacacs-1101** [comment]
Where do you find conversation history in blenderbot2, and memory which is written by model. I am not getting this in log file.

**Comment by klshuster** [comment]
it is not saved to the log file, but you can view it manually by setting `--loglevel debug`

**Comment by sjscotti** [comment]
I think this is a related question about history...  in using `parlai interactive` to submit queries to a model, I assumed that setting `--history-size 0` would do the same thing as alternating entering `[DONE]` with entering the actual queries.  But that does not seem to be the case.  Is the history used at all in model interactive queries?  Is there an option that does the equivalent of entering the `[DONE]` after each query?  Thanks!

**Comment by klshuster** [comment]
If you're using `parlai interactive`, you can specify `--single_turn true` to reset the history each turn.

Alternatively, I believe setting the history size to 1 should achieve what you're looking for; the value of 1 implies that the model only remembers the previous utterance (i.e., yours); a history size of 0 would mean the model would unconditionally generate a response
