### ISSUE TITLE
How to evaluate the results reported in "light_whoami" using the released checkpoints?

### ISSUE THREAD

**Issue by SkyAndCloud** [facebookresearch/ParlAI#4313]
Hi, I'm new to the parlai framework. I am interested in the light_whoami project (https://github.com/facebookresearch/ParlAI/tree/main/projects/light_whoami). I want to reproduce the results reported in the paper (http://arxiv.org/abs/2112.05843). But I didn't find any scripts to obtain the reported results. How to evaluate the results reported in "light_whoami" using the released checkpoints? Thanks!

**Comment by klshuster** [comment]
hi there - which results are you interested in?

if you'd like to evaluate the models, you can try running the following:

`parlai eval_model --task projects.light_whoami.task.agents:ResponseClassifierTeacher --model-file <path_to_zoo_model> --predictor-model-file zoo:light_whoami/rpa_reranker/model`

Where the zoo model files are at the linked project page.

For other model configurations (e.g., including PACER or RPA re-ranking), see the project page for how to specify the proper `-m/--model` argument.

It might be good to go through the ParlAI quick-start/documentation to get a sense of how to operate within ParlAI as well (https://parl.ai/docs/tutorial_quick.html)

**Comment by SkyAndCloud** [comment]
Got it. BTW, how to save the whole prediction results? According to the quick-start, I can only obtain partial predictions by  by `parlai display_model`. But I need the whole inference results to do some human evaluation. Thank you!

**Comment by klshuster** [comment]
When you run `parlai eval_model`, there are two additional flags you can specify to save the results:

`--report-filename /path/to/eval_stats.json` - saves the statistics from evaluation (i.e., metrics) in a json file.
`--world-logs /path/to/world_logs.jsonl` - saves the full model outputs in a jsonl file (each line is a full "dialog"). 

You can parse the world logs manually, or see the outputs with the `jsonfile` teacher:

`parlai display_data --task jsonfile --jsonfile-datapath /path/to/world_logs.jsonl`

**Comment by SkyAndCloud** [comment]
Thanks a lot!
