### ISSUE TITLE
ParlAI cannot parse arguments for task-specific mutators.

### ISSUE THREAD

**Issue by zhangmozhi** [facebookresearch/ParlAI#4321]
**Bug description**
When using task-specific mutator, mutator-specific arguments cannot be parsed.

**Reproduction steps**
`parlai display_data --task dailydialog:mutators=episode_shuffle --preserve-context true`

**Expected behavior**
There should be no error.

**Logs**
```
Parse Error: unrecognized arguments: --preserve-context true
```

**Comment by stephenroller** [comment]
Unfortunately, mutator args don't work when specified via the `--task X:mutators=` format. We should update the mutator docs to reflect this.

They will still parse if you specify them as root items (`--task X --mutators episode_shuffle`). You should also be able to force the opt in the task argument (`--task X:mutators=episode_shuffle,preserve_context=True`)

**Comment by zhangmozhi** [comment]
> Unfortunately, mutator args don't work when specified via the `--task X:mutators=` format. We should update the mutator docs to reflect this.
> 
> They will still parse if you specify them as root items (`--task X --mutators episode_shuffle`). You should also be able to force the opt in the task argument (`--task X:mutators=episode_shuffle:preserve_context=True`)

The last option works. Thanks for the help!

**Comment by stephenroller** [comment]
Would you be open to adding this info on the mutator docs?

**Comment by zhangmozhi** [comment]
Will do
