### ISSUE TITLE
ParlAI FixedDialogTeacher don't kill unused Thread created by DataLoader

### ISSUE THREAD

**Issue by c00k1ez** [facebookresearch/ParlAI#4327]
**Bug description**
I tried to implement grid search for BlenderBot generation hyper-parameters using [eval_model.py](https://github.com/facebookresearch/ParlAI/blob/main/parlai/scripts/eval_model.py).
For this task I just added simple for loop, recreated new opt object for each iteration with new parameters & call [eval_model](https://github.com/facebookresearch/ParlAI/blob/f451c6d003b0df5ede687e3f67c6c96cdb6981bd/parlai/scripts/eval_model.py#L218) function.
I noticed that at the end of eval_model (already) unused thread created by agent (DataLoader object inside of ParlAIDialogTeacher class) wasn't killed.
I don't test it with several tasks but I think this issue valid for this case too.

**Reproduction steps**
To reproduce this issue run [this](https://pastebin.com/cKdGrAEW) script with command:
```
python test_threads.py --task blended_skill_talk -mf zoo:blender/blender_90M/model --no-cuda --num-examples 10
```
parlai==1.5.1
To detect threads I used VSCode debugger.
<img width="215" alt="Screenshot 2022-01-27 at 08 20 00" src="https://user-images.githubusercontent.com/16941854/151297314-c52cd443-9104-40d8-b8e3-d389003b949f.png">

**Additional context**
To fix it I added code before [this](https://github.com/facebookresearch/ParlAI/blob/f451c6d003b0df5ede687e3f67c6c96cdb6981bd/parlai/scripts/eval_model.py#L214) line.
```python
for a in world.agents:
    if isinstance(a, DefaultTeacher):
        a.data_loader.request_load(StopIteration, None, None)
```
But I think it will be great to implement way inside FixedDialogTeacher class to kill DataLoader thread like
```python
class FixedDialogTeacher(Teacher):
...
    def kill_thread(self):
        self.data_loader.request_load(StopIteration, None, None)
...
```
Thank you.

**Comment by stephenroller** [comment]
Stale bump

**Comment by drevicko** [comment]
Not sure if it's related, but we're seeing threads that aren't getting killed also. 

In our case, we have parlai running for a long duration and handling multiple conversations (not syncrhonous). After each conversation, a new thread remains alive. After `max_workers` conversations, parlai blocks, as there are no available threads to launch the new world.
