### ISSUE TITLE
Reddit3B very large after fine-tune, can't load

### ISSUE THREAD

**Issue by lenbrocki** [facebookresearch/ParlAI#4332]
**Bug description**
After fine-tuning the Reddit3B model with the empathetic_dialogue task the model file is 37GB, whereas the original model only is 11GB. Also, the model can not be loaded after fine-tuning(Jupyter kernel dies, I suppose OOM)

**Reproduction steps**
Use parameters found in https://parl.ai/projects/recipes/ to fine-tune 2.7B model. Run in Jupyter notebook.

**Expected behavior**
Model should have the same size after fine-tuning.

**Logs**
Can post if needed, very long

**Comment by klshuster** [comment]
This is because we save the optimizer states with the model. You can run `parlai vacuum` on a model file to remove those optimizer states (which should decrease the model size substantially).

**Comment by lenbrocki** [comment]
Yes that solved it, thanks!
