### ISSUE TITLE
BlenderBot2 chat not using memory context (chat contradiction)

### ISSUE THREAD

**Issue by Tacacs-1101** [facebookresearch/ParlAI#4338]
**Bug description**
When I chatted with the blender bot2 3B parameter model it shows lots of contradiction to its own statement even in the same session. Seems like it's not using the chat context.  Also, i can't find memory logs in when i run parlai/chat_service/services/browser_chat/run.py even after enabling loglevel=debug in config. Is something wrong in my config such that it's not using chat context before generation?  Below is a chat sample and my config file snap.

<img width="1110" alt="blenderbot2_chat_contradiction" src="https://user-images.githubusercontent.com/19792093/152478005-d8e6bcee-93bc-425d-993e-fe4edf71fd64.png">

<img width="826" alt="blenderbot2_3B_config" src="https://user-images.githubusercontent.com/19792093/152478199-58528de5-e45c-4670-9fa7-b2c3b5635e30.png">

I run the script **_parlai/chat_service/services/browser_chat/run.py --config-path parlai/chat_service/tasks/chatbot/config-3B.yml_** with the above configuration.

**Expected behavior**
I expect the model to give the semantically the same answer to the same user in the same session.

**Logs**
Please paste the command line output:

```
Output goes here
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by klshuster** [comment]
`loglevel: debug` should go directly under the `opt` key, not in the `blender2_3B` key

**Comment by Tacacs-1101** [comment]
> `loglevel: debug` should go directly under the `opt` key, not in the `blender2_3B` key

Sure. but main concern as seen in the chat is that the model contradicts itself a lot when asked same questions.  Looking like its not using the chat context properly.
