### ISSUE TITLE
Task name not clear for blenderbot2

### ISSUE THREAD

**Issue by Tacacs-1101** [facebookresearch/ParlAI#4339]
**Bug description**
I am trying to use the blenderbot2 model which augment internet searches. what should be the --task parms for this model to use.

**Reproduction steps**
running the interactive_web.py using parlai interactive_web .... command. I am configuring the search_server using --search_serrver arguements but none of my query is going for web search. I have specified --task="wizard_of_internet."

**Comment by klshuster** [comment]
you can specify a different query generator that will always search.

`--query-generator-model-file zoo:sea/bart_sq_gen/model`

**Comment by Tacacs-1101** [comment]
> you can specify a different query generator that will always search.
> 
> `--query-generator-model-file zoo:sea/bart_sq_gen/model`

So for a blenderbot2 model the task should be always "wizard_of_internet"?. Because what i believe is that its also trained on other datasets like wizard_of_wikipedia, multi-session chat, etc.

**Comment by mojtaba-komeili** [comment]
You can use BlenderBot2 with any valid ParlAI task (including custom teachers). Only the default module that generates search query, which is fixed not trained with BB2 is coming from the Wizard of Internet. You may also create your own search query generator model and use it as @klshuster explained above.

**Comment by Tacacs-1101** [comment]
I wanted to use the task chatbot located at parlai/chat_service/task/chatbot, how can i specify this with the task parameter.
