### ISSUE TITLE
BlenderBot2 400M training IndexError: index 2 is out of bounds for dimension 0 with size 1

### ISSUE THREAD

**Issue by gabrielle-lau** [facebookresearch/ParlAI#4340]
**Bug description**
Hi team, I've encountered an index error when I start finetuning/ training Blenderbot2 400M. I used the following command (similar to #3940 but for 400M instead of 2.7B) to finetune BB2 400M on wizard_of_internet, msc and my custom dataset. Appreciate your advice on:
1. How to solve this Index Error when retrieving docs? 
2. Should the init-model be the BB1 of the same model size, ie. "zoo:blender/blender_400Mdistill/model" instead? 

**Reproduction steps**
`python3 ParlAI/parlai/scripts/train_model.py \
-lr 7e-6 \
-bs 16 \
--multitask-weights 4,3,3 \
--task wizard_of_internet,msc,custom_qa \
--model-file user/documents/your_directory_to_save_model \
--model projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent \
--dict-file zoo:blenderbot2/blenderbot2_400M/model.dict \
--wandb-log True \
--wandb-entity laumingyi \
--wandb-project bb2 \
--init-model zoo:blenderbot2/blenderbot2_400M/model \
--optimizer adam \
--skip-generation True \
--knowledge_access_method memory_only \
--search-server None \
--metrics ppl \
--validation-metric ppl \
--model-parallel True \
--memory-decoder-model-file '' \
--fp16 True \
--datatype train:stream \
--embedding-size 2560 \
--ffn-size 10240 \
--dropout 0.0 \
--attention-dropout 0.0 \
--n-heads 32 \
--learn-positional-embeddings False \
--embeddings-scale True \
--n-positions 128 \
--variant prelayernorm \
--activation relu \
--n-encoder-layers 2 \
--n-decoder-layers 24 \
--model-parallel True \
--generation-model transformer/generator \
--query-model bert_from_parlai_rag \
--rag-model-type token \
--rag-retriever-type dpr \
--max-doc-token-length 64 \
--dpr-model-file zoo:hallucination/bart_rag_token/model \
--beam-size 10 \
--beam-min-length 20 \
--beam-context-block-ngram 3 \
--beam-block-ngram 3 \
--beam-block-full-context False \
--inference beam \
--fp16-impl mem_efficient \
--optimizer mem_eff_adam \
--truncate 128 \
--text-truncate 128 \
--label-truncate 128 \
--delimiter '  ' \
--history-add-global-end-token end \
--dict-tokenizer bytelevelbpe \
--warmup-updates 100 \
--search-query-generator-model-file zoo:blenderbot2/query_generator/model \
--search-query-generator-beam-min-length 2 \
--memory-key personas \
--gold-document-titles-key select-docs-titles \
--insert-gold-docs True"`

**Expected behavior**
Start training.

**Logs**

```
2022-02-04 18:53:06,794 INFO | training...
/app/ParlAI/parlai/core/torch_generator_agent.py:1749: 
UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. 
It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). 
This results in incorrect rounding for negative values. 
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), 
or for actual floor division, use torch.div(a, b, rounding_mode='floor'). 
hyp_ids = best_idxs // voc_size
Traceback (most recent call last): 
File "ParlAI/parlai/scripts/train_model.py", line 1002, in <module> 
TrainModel.main() 
File "/app/ParlAI/parlai/core/script.py", line 129, in main 
return cls._run_args(None) 
File "/app/ParlAI/parlai/core/script.py", line 101, in _run_args 
return cls._run_from_parser_and_opt(opt, parser) 
File "/app/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt 
return script.run() 
File "ParlAI/parlai/scripts/train_model.py", line 998, in run 
return self.train_loop.train() 
File "ParlAI/parlai/scripts/train_model.py", line 950, in train 
for _train_log in self.train_steps(): 
File "ParlAI/parlai/scripts/train_model.py", line 857, in train_steps 
world.parley() 
File "/app/ParlAI/parlai/core/worlds.py", line 873, in parley 
batch_act = self.batch_act(agent_idx, batch_observations[agent_idx]) 
File "/app/ParlAI/parlai/core/worlds.py", line 841, in batch_act 
batch_actions = a.batch_act(batch_observation) 
File "/app/ParlAI/parlai/core/torch_agent.py", line 2234, in batch_act 
output = self.train_step(batch) 
File "/app/ParlAI/parlai/core/torch_generator_agent.py", line 734, in train_step 
loss = self.compute_loss(batch) 
File "/app/ParlAI/projects/blenderbot2/agents/blenderbot2.py", line 857, in compute_loss 
loss, output = super().compute_loss(batch, return_output=True) 
File "/app/ParlAI/parlai/agents/rag/rag.py", line 917, in compute_loss 
model_output = self.get_model_output(batch) 
File "/app/ParlAI/parlai/agents/rag/rag.py", line 889, in get_model_output 
model_output = self.model( 
File "/opt/gabrielle/py3env/lib/python3.8/site-packages/torch-1.10.2-py3.8-linux-x86_64.egg/torch/nn/modules/module.py", line 1102, in _call_impl 
return forward_call(*input, **kwargs) 
File "/app/ParlAI/parlai/core/torch_generator_agent.py", line 309, in forward 
encoder_states = prev_enc if prev_enc is not None else self.encoder(*xs) 
File "/app/ParlAI/projects/blenderbot2/agents/modules.py", line 865, in encoder 
enc_out, mask, input_turns_cnt, top_docs, top_doc_scores = super().encoder( # type: ignore 
File "/app/ParlAI/projects/blenderbot2/agents/modules.py", line 223, in encoder 
expanded_input, top_docs, top_doc_scores = self.retrieve_and_concat( 
File "/app/ParlAI/projects/blenderbot2/agents/modules.py", line 407, in retrieve_and_concat 
memories, memory_scores = self.access_long_term_memory( 
File "/app/ParlAI/projects/blenderbot2/agents/modules.py", line 642, in access_long_term_memory 
memories, memory_scores = self.long_term_memory.retrieve( 
File "/app/ParlAI/parlai/agents/rag/retrievers.py", line 419, in retrieve 
docs, scores = self.retrieve_and_score(query) 
File "/app/ParlAI/projects/blenderbot2/agents/modules.py", line 792, in retrieve_and_score 
memories_i, scores_i = argsort_scores_and_docs( 
File "/app/ParlAI/parlai/agents/rag/retrievers.py", line 206, in argsort_scores_and_docs 
ranked_docs = [docs[idx] for idx in scores_sorter.indices[:n_docs]] 
File "/app/ParlAI/parlai/agents/rag/retrievers.py", line 206, in <listcomp> 
ranked_docs = [docs[idx] for idx in scores_sorter.indices[:n_docs]]
IndexError: index 2 is out of bounds for dimension 0 with size 1
```

**Additional context**

- Goal: to finetune BlenderBot2 400M with a custom dataset and a few of the original datasets.
- Docker container used: nvidia/cuda:11.4.2-cudnn8-runtime-ubuntu20.04
- ParlAI code version: commit d6b2fb16fae29f6f3e92bba60625808d5243e392
- Torch version: 1.10.2

Thank you! :)

**Comment by klshuster** [comment]
Hi, this looks like [one of the errors found in the FAQ](https://github.com/facebookresearch/ParlAI/tree/main/projects/blenderbot2/agents#indexerror). From a quick glance at your command I see that you're specifying `--knowledge-access-method memory_only` and `--memory-key personas`; memory only means that BB2 needs to access memories for each example, but that would require two of your tasks (`wizard_of_internet` and `custom_qa`) to specify memories in the `personas` field. If you'd like, you could instead specify `--memory-key full_text`, which will extract memories from the context.

As for the init model, using what you're using is fine.

**Comment by gabrielle-lau** [comment]
Thank you very much! I made that change :) 
For anyone else having the same question, my working finetuning command for BB2 400M is as follows:
```
python3 ParlAI/parlai/scripts/train_model.py \
-lr 7e-6 \
-bs 16 \
--multitask-weights 4,3,3 \
--task wizard_of_internet,msc,custom_dataset \
--model-file user/documents/your_directory_to_save_model \
--model projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent \
--dict-file zoo:blenderbot2/blenderbot2_400M/model.dict \
--wandb-log True \
--wandb-entity your_entity_name \
--wandb-project bb2 \
--init-model zoo:blenderbot2/blenderbot2_400M/model \
--skip-generation True \
--knowledge-access-method memory_only \
--memory-key full_text \
--search-server None \
--metrics ppl \
--validation-metric ppl \
--model-parallel True \
--memory-decoder-model-file '' \
--datatype train:stream \
--generation-model transformer/generator \
--query-model bert_from_parlai_rag \
--rag-model-type token \
--rag-retriever-type dpr \
--max-doc-token-length 64 \
--dpr-model-file zoo:hallucination/bart_rag_token/model \
--beam-size 10 \
--beam-min-length 20 \
--beam-context-block-ngram 3 \
--beam-block-ngram 3 \
--beam-block-full-context False \
--inference beam \
--fp16-impl mem_efficient \
--optimizer mem_eff_adam \
--truncate 128 \
--text-truncate 128 \
--label-truncate 128 \
--history-add-global-end-token end \
--warmup-updates 100 \
--gold-document-titles-key select-docs-titles \
--insert-gold-docs True \
--activation gelu \
--attention-dropout 0.0 \
--dict-tokenizer gpt2 \
--dropout 0.1 \
--embedding-size 1024 \
--embeddings-scale false \
--ffn_size 4096 \
--force-fp16-tokens true \
--fp16 true \
--learn-positional-embeddings true \
--n-decoder-layers 12 \
--n-encoder-layers 12 \
--n-heads 16 \
--n-positions 1024 \
--variant bart"
```
