### ISSUE TITLE
how to change the role who guides the chat with bb2?

### ISSUE THREAD

**Issue by andysun-sw** [facebookresearch/ParlAI#4342]
I use the following way to interactive with blenderbot2:
parlai interactive -mf zoo:blenderbot2/blenderbot2_400M/model --search-server relevant_search_server --knowledge-access-method memory_only

the system wait human people to write the first sentence and then response, how to let the system say the first sentence then let human to answer?
second,if there is one way to let system speak the first sentence, how to control the content of what it says?

**Comment by klshuster** [comment]
if you specify certain tasks they will generate contexts for the model; you can browse tasks that have an `InteractiveWorld` for this functionality, but off the top of my head I believe `convai2`, `blended_skill_talk`, and `wizard_of_wikipedia` all have this functionality (just specify with `--task` when running `interactive`)

As for letting the system respond first -- you can enter `__SILENCE__` as the first message and then proceed as if the bot responded first. We don't have `interactive` set up at the moment to allow the bot to go first.
