### ISSUE TITLE
Can't find parameter to turn off offensive language classifier

### ISSUE THREAD

**Issue by Tacacs-1101** [facebookresearch/ParlAI#4355]
Do we have any parameters to turn off the offensive language classifier in BlenderBot2. I couldn't find it.

**Comment by klshuster** [comment]
As outlined in the "Safety" section of the [project page](https://parl.ai/projects/blenderbot2/), we use baked-in safety, such that the model learns safety during training. So, you cannot turn off this functionality.

**Comment by Tacacs-1101** [comment]
thanks for your response.

**Comment by Tacacs-1101** [comment]
resolved
