### ISSUE TITLE
Using fine-tuned model in chat service

### ISSUE THREAD

**Issue by jh-skaion** [facebookresearch/ParlAI#4356]
Hello team, how can i set the config.yml to use the fine-tuned blender90M model?

![image](https://user-images.githubusercontent.com/82824999/153928362-b39ffeb3-0506-4dfb-ae9d-70240eaff627.png)

**Comment by klshuster** [comment]
if you change the top-level key you'd need to change the [value here](https://github.com/facebookresearch/ParlAI/blob/76ac2bab067a05ee5ba2d722b6ee90eb7e2c0660/parlai/chat_service/tasks/chatbot/worlds.py#L34)

additionally, you'll want to set the `model_file` key to your new model; `checkpoint` is not a valid key in the config. `model_file` is also the direct path to the model file itself, not the directory

**Comment by jh-skaion** [comment]
Thanks
