### ISSUE TITLE
Chat Logs For BlenderBot2?

### ISSUE THREAD

**Issue by DNGros** [facebookresearch/ParlAI#4363]
Thanks for sharing your progress on the Blenderbot system!

I was wondering if there existed chat logs for Blenderbot2, similar to what is available for Blenderbot 1 in [chatlog_2.7B.json](https://github.com/facebookresearch/ParlAI/blob/d26a06d3c393814d29343dac62e43d8ce45e17d5/projects/recipes/chatlog_2.7B.json). For example the logs that are the basis of ratings given in the BlenderBot2 [results tables](https://github.com/facebookresearch/ParlAI/tree/main/projects/blenderbot2#human-evaluation-multi-session-chat).

Do these logs exist in a form that would be easy to share?

cc: @mojtaba-komeili @jxmsML

**Comment by klshuster** [comment]
Unfortunately, we are unable to share these chat logs

**Comment by DNGros** [comment]
Hi @klshuster , thanks for your response! 

I'll close this for now then. If things change (or someone else stumbles upon this and ends up collecting new human dialogues with the published model) the issue can perhaps be reopened. Dialogue samples could the community understand and compare systems.

I understand though that there can be complications here, and I really appreciate the response, as helps with planning. Thanks!
