### ISSUE TITLE
Blenderbot2 episode not ending

### ISSUE THREAD

**Issue by Tacacs-1101** [facebookresearch/ParlAI#4367]
**Bug description**
I am explicitly ending the episode by passing episode_done: True in observe method of agent. But in response i can still see that the episode_done: False. I want blenderbot2 to forget previous memory and generate response only the basis of provided context.

<img width="812" alt="image" src="https://user-images.githubusercontent.com/19792093/154692962-e07b9a7f-5983-4335-963a-908110ef8c79.png">

**Reproduction steps**
opt = {
    "model": "projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent",
    "model_file": model_file,
    "no_cuda": no_cuda,
    "knowledge-access-method": "search_only",
    "query-generator-model-file": "zoo:sea/bart_sq_gen/model",
    "override": {
        "use_memories": False,
        "no_cuda": no_cuda,
        "knowledge-access-method": "search_only",
        "query-generator-model-file": "zoo:sea/bart_sq_gen/model",
        "search_server": "127.0.0.1:10005",
        "history_size": 1,
    }

}
blender_agent = create_agent(opt)
blender_agent.observe({'text': utt, "episode_done": True})
response = blender_agent.act()

**Expected behavior**
I expect the model to end the episode after each utterance I pass

**Additional context**
I am trying to pass some context and blenderbot generate response on the basis of it only, forgetting previous memory.

**Comment by klshuster** [comment]
what is printed there is the bot reply; the bot never sends episode done in its reply, but internally it is registering that the episode is done and so history must reset, etc.

**Comment by Tacacs-1101** [comment]
Thanks for your response, I want to reset history at each turn. Is this the correct way to do?  Do memory decoder also update itself when we ask questions to blenderbot2?

**Comment by stephenroller** [comment]
Sending episode done will make the NEXT turn be reset.  I never liked those mechanics but it's legacy.
