### ISSUE TITLE
Can we make a chatbot using Blenderbot2, that will track packages like the bots in ecommerce websites?

### ISSUE THREAD

**Issue by alan-ai-learner** [facebookresearch/ParlAI#4368]
Hi @klshuster , i want make an chatbot that will perform the following task…
e.g when will my order reach,
last 3 transactions etc

I need some suggestions and approaches.

**Comment by alan-ai-learner** [comment]
> hi there, you can take a look at https://arxiv.org/abs/2110.06905 for some inspiration

Thanks, will go through and let you know.

**Comment by alan-ai-learner** [comment]
Hi @klshuster i want make a chat bot for a custom knowledge base. Like is there any best transformer model that can be integrated to the knowledge base and fetch the answers from it.

**Comment by klshuster** [comment]
You can look at the [rag](https://github.com/facebookresearch/ParlAI/tree/main/parlai/agents/rag) and [fid](https://github.com/facebookresearch/ParlAI/tree/main/parlai/agents/fid) models; the work in https://arxiv.org/abs/2104.07567 applies these methods to dialogue with wikipedia as a knowledge base

**Comment by klshuster** [comment]
they can work with any knowledge base
