### ISSUE TITLE
Searching Alternative Databases/Custom Functions

### ISSUE THREAD

**Issue by TKTSWalker** [facebookresearch/ParlAI#4381]
Hello, I would like to add ways in which Blenderbot can check data using custom made functions through different files such as txt, xslx and such. Formatting it and getting it to "understand" the data returned should be easy, but the hard part actually comes from initiating the search as well as making it local. Can someone point me in the right direction?

**Comment by klshuster** [comment]
I'm not sure I understand the question - are you saying you want to be able to retrieve over a local set of documents?

**Comment by TKTSWalker** [comment]
Pretty much!

**Comment by klshuster** [comment]
You can look at the [rag](https://github.com/facebookresearch/ParlAI/tree/main/parlai/agents/rag) and [fid](https://github.com/facebookresearch/ParlAI/tree/main/parlai/agents/fid) models for that. 

We have implemented several retrieval methods for these models:
1. FAISS-based: retrieve from a FAISS index (an index of dense embeddings of the documents)
2. Search-based: query a search server
3. TFIDF: retrieve from a TFIDF database

If any of those options fit, you can use `--rag-retriever-type <dpr/search_engine/tfidf>`. Instructions for how to build a FAISS index are in the rag link above; instructions for how to use TFIDF can be found [here](https://github.com/facebookresearch/ParlAI/tree/main/parlai/agents/tfidf_retriever) (and you would then specify `--tfidf-model-path` to be your TFIDF index). Instructions for how to use a search engine can be found by searching through the ParlAI issues.

If you want to implement your own search method, you can subclass the [`RagRetriever`](https://github.com/facebookresearch/ParlAI/blob/7c2b199d0b315c9016072897d849811cfc8a5073/parlai/agents/rag/retrievers.py#L363) and implement a `retrieve_and_score` method. Examples in that file show how other methods are implemented.

**Comment by TKTSWalker** [comment]
Thank you! This is exactly what I was looking for!
