### ISSUE TITLE
why validation step take so long time?

### ISSUE THREAD

**Issue by andysun-sw** [facebookresearch/ParlAI#4390]
I use following ways to finetune reddit model and the model will validate every 1.5 epoch, the problem is the time spent on evaluation will be 1 to 2 hours. Is it normal or can I accelerate the process?
parlai train_model -t blended_skill_talk,scan --multitask-weights 10,2  -veps 1.5 --attention-dropout 0.0 --batchsize 16 --model transformer/generator --embedding-size 2560 --ffn-size 10240 --variant prelayernorm --n-heads 32 --n-positions 128 --n-encoder-layers 2 --n-decoder-layers 24 --history-add-global-end-token end --delimiter '  ' --dict-tokenizer bytelevelbpe  --dropout 0.1 --fp16 True --init-model zoo:blender/reddit_3B/model --dict-file zoo:blender/reddit_3B/model.dict --label-truncate 128 --log_every_n_secs 10 -lr 7e-06 --lr-scheduler reduceonplateau --lr-scheduler-patience 3 --optimizer adam --relu-dropout 0.0 --activation gelu --model-parallel true --save-after-valid True --text-truncate 128 --truncate 128 --warmup_updates 100 --fp16-impl mem_efficient --update-freq 2 --gradient-clip 0.1 --skip-generation  False -vp 4 -vmt ppl -vmm min --model-file /py_torch/parlai_finetune_model/test_train_27B

the validation step is:
![valid](https://user-images.githubusercontent.com/89009298/156276802-4aae33b8-2963-4c3d-9bcc-756cd3715263.png)

**Comment by stephenroller** [comment]
Add --skip-generation true
