### ISSUE TITLE
what's the meaning of multitask-weights

### ISSUE THREAD

**Issue by andysun-sw** [facebookresearch/ParlAI#4391]
If I have two dataset or tasks : A has 10000 examples and B has 1000 examples, I want to finetune reddit model,do I need to set:

parlai train_model -t A,B --multitask-weights 10,1

If I set the ratio to 1,10, what will happen? Is it impact the speed or accuracy?

**Comment by stephenroller** [comment]
you can use `--multitask-weights stochastic` to force a 10:1 ratio.

Otherwise, MTW manually sets the sampling ratio between the two datasets.
