### ISSUE TITLE
Host bot on GRPC server 

### ISSUE THREAD

**Issue by Tacacs-1101** [facebookresearch/ParlAI#4394]
**Bug description**
Not actually a but, but creating a blenderbot2 agent in this way is giving weird responses which are not as per claimed in the paper.

model_file = "zoo:blenderbot2/{}/model".format(config.model_name) # point it to downloaded model dir if you have.

parameters for blender2
opt = {
"model": "projects.blenderbot2.agents.blenderbot2:BlenderBot2FidAgent",
"model_file": model_file,
"no_cuda": False,
"override": {
"no_cuda": False,
"search_server": "127.0.0.1:10005",
"history_size": 1,
}
}

blender_agent = create_agent(opt)

I am creating an agent like this for blenderbot2 globally for exposing it through grpc api.

passing a utterance like this
**_blender_agent.observe({'text': utt, "episode_done": False})_**
and getting prediction as **_blender_agent.act()_**

I want to expose this output through a grpc endpoint. I also want to reset history at each turn.
Is this the correct way, because my response are coming but that is not good enough as claimed.

**Comment by mojtaba-komeili** [comment]
Your overall method looks fine to me. You could also use `'episode_done': True` to reset the history after each turn. 
I don't see what the problem is here. Could you explain more? If it is about the quality of the results, or reproducing what we had in our blogpost, they depend on factors such as the search results, persona that you assign, etc.

**Comment by Tacacs-1101** [comment]
I am not able to reproduce the conversation in the blog post. Also, the quality of results is not good. Sometimes it gives a weird response. For example when I ask, who is the president of the USA, sometimes it says Donald J Trump is the president of the USA which is okay, but sometimes it says who is your daddy and what does he do? Seems like responses are not consistent throughout the conversation, and also it contradicts a lot to his own statement.  Also, I want to know if the memory decoder model gets updated during conversation or not.
Can we reset the history after each turn, and pass our own context history before each conversation.
