### ISSUE TITLE
Can I build a Role-playing chatbot?

### ISSUE THREAD

**Issue by Mickal-Jin** [facebookresearch/ParlAI#4398]
Hello, 
I want to make a chatbot with these functions: 
- it has its own personality and a history grounded in a fantasy world that it could recall 
- has to remember its previous conversations with particular users.

I made a prototype with OpenAi using their prompt system, but I couldn’t find any way to do it in ParlAi docs. 

Is that even possible with Blenderbot 2.0? Do you have any suggestions on how to approach it?

**Comment by stephenroller** [comment]
Take a look at the LIGHT projects
- https://parl.ai/projects/light/
- https://github.com/facebookresearch/ParlAI/tree/main/projects/light_whoami/

and more
