### ISSUE TITLE
Model is taking a long time to build a dictionary [using TPU]?

### ISSUE THREAD

**Issue by evelynkyl** [facebookresearch/ParlAI#4410]
Hi there! I am using GCP's TPU for training a pre-trained model with 3 datasets. So after running the command, the program started to build dictionary for the datasets. Out of the three datasets, two of which (wizard of wikipedia and blended skill talks) were built quickly, but the last one (convai2) has taken ~34 hours, and it's still running. 

Below is the last 2 lines of the output
```
12:02:19 | loading fbdialog data: /opt/conda/envs/torch-xla/lib/python3.8/site-packages/data/ConvAI2/train_self_original.txt
Building dictionary: 1.14Gex [33:56:23, 9.12kex/s]
```

I ran this command for training
```
python3 train_model.py   --init-model zoo:pretrained_transformers/poly_model_huge_wikito/model   -t blended_skill_talk,convai2,wizard_of_wikipedia   --multitask-weights 3,2,5  --model transformer/polyencoder --batchsize 4 --eval-batchsize 10   --warmup_updates 100 --lr-scheduler-patience 0 --lr-scheduler-decay 0.4   -lr 5e-05 --data-parallel True --history-size 20 --label-truncate 72   --text-truncate 360 --num-epochs 8.0 --max_train_time 200000 -veps 0.5   -vme 8000 --validation-metric accuracy --validation-metric-mode max   --save-after-valid True --log_every_n_secs 20 --candidates batch --fp16 True   --dict-tokenizer bpe --dict-lower True --optimizer adamax --output-scaling 0.06   --variant xlm --reduction-type mean --share-encoders False   --learn-positional-embeddings True --n-layers 12 --n-heads 12 --ffn-size 3072   --attention-dropout 0.1 --relu-dropout 0.0 --dropout 0.1 --n-positions 1024   --embedding-size 768 --activation gelu --embeddings-scale False --n-segments 2   --learn-embeddings True --polyencoder-type codes --poly-n-codes 64   --poly-attention-type basic --dict-endtoken __start__   --model-file  /home/parlai/model/gen-conv
```

I have modified the training script slightly to experiment training ParlAI with TPU (torch-xla).

Any idea about the issue here and how can I solve it? Thank you so much in advance!!

**Comment by stephenroller** [comment]
Hm seems like a bug. Try building the dict by itself or use a pretrained one like --dict-tokenizer gpt2

**Comment by evelynkyl** [comment]
Thanks for the quick reply! I'll try building the dict by itself or else it doesn't work I might just finetune my own dataset on a pretrained blenderbot model.
