### ISSUE TITLE
Question about use of special tokens in Blenderbot2 400M fine tuning

### ISSUE THREAD

**Issue by sjscotti** [facebookresearch/ParlAI#4412]
Hi
I have fine-tuned a 400M Blenderbot2 using a custom task that has some added special tokens.  Anyway, it seemed to be working as expected except for cases where a word that was defined as a special token was involved. For example, doing an interactive query of the tuned BB2, and using one of the training queries as input, the query generator called for a search did not use the special token from the training phrase as I expected to see, but a couple of subwords of it.  So I was confused why the tokenizer didn't recognize the special token word as an undivided entity.  In digging into what I could find regarding the gpt2 tokenizer used for BB2 400M, I found this info on the huggingface website (in https://huggingface.co/docs/transformers/model_doc/gpt2 )... 
```
add_prefix_space (bool, optional, defaults to False) — Whether or not to add an initial space to the input. This allows to treat the leading word just as any other word. (GPT2 tokenizer detect beginning of words by the preceding space).
```
Since the special token word causing the problem described above is the first word for several of the training exchanges, I was wondering if not having a space before the word in the training task could be causing the issues I am seeing.  

Another way to look at this issue is suppose that I want the string `"abpqrst"` and another string `"uvwxyz"` to be recognized as special tokens and not split into subwords when tokenized.     How do I define them with `"special_tok_lst"` in the file I use as the `--init-opt`  so that they can be recognized in any position in the text being tokenized?.  Using the way I have been doing it, I would be using this input...
```
"special_tok_lst": "abpqrst,uvwxyz"
```
Is that the way it should be done?  Any guidance would be appreciated!
Thanks!

**Comment by klshuster** [comment]
yes, that is the correct way to specify special tokens. If they are not specified like this, any tokens will be tokenized according to the GPT2 tokenizer (which splits subwords)

**Comment by sjscotti** [comment]
Thanks!
