### ISSUE TITLE
BB2 and MSC questions

### ISSUE THREAD

**Issue by ai-john** [facebookresearch/ParlAI#4444]
Hey! Been playing with BB2 and MSC and got a few questions.

1. What is the correct way to run BB2 without external search? I currently managed to get it working via `parlai interactive -mf zoo:blenderbot2/blenderbot2_3B/model --knowledge_access_method memory_only --rag_retriever_type dpr` but not entirely sure it's the most optimal way.
2. When I run BB2 locally, how can I see when MSC writes to local memory facts from the conversation and when reads those facts? I initially assumed that I will be seeing that in the console but after chatting for a few minutes nothing showed up.
3. Where can I find the code that connects MSC to the BB2? What I am trying to achieve is the following – I want to write MSC output to the JSON and then upload recent JSON to the BB2 upon init.
4. Is there a limitation on the number of "facts" that BB2 can process from the MSC?
5. Is MSC the only component that is responsible for memory management in BB2? Are there any other modules connected to that?

Thanks!

**Comment by klshuster** [comment]
In order:

1. That's correct, although you don't need to specify `--rag-retriever-type dpr`
2. If you specify `--loglevel debug` when you run, there should be some informative messages about memory writing and access
3. If by MSC output you mean the long-term memory output, [this function](https://github.com/facebookresearch/ParlAI/blob/24cc648fe8ec60102c17e88a8dc5aaf4db62b05d/projects/blenderbot2/agents/sub_modules.py#L309-L344) generates the memories, [this function](https://github.com/facebookresearch/ParlAI/blob/24cc648fe8ec60102c17e88a8dc5aaf4db62b05d/projects/blenderbot2/agents/modules.py#L734-L755) writes to memory, and [this function](https://github.com/facebookresearch/ParlAI/blob/24cc648fe8ec60102c17e88a8dc5aaf4db62b05d/projects/blenderbot2/agents/modules.py#L771-L810) reads from memory. 
4. There is no limitation, but this is controlled by a hyperparameter `--n-docs`; the default is 5. Feel free to bump that up as high as you wish
5. Not totally sure what the question is here, but to give a brief overview of how the memory works: the long term memory module can read from a `personas` key in an incoming observation and write these immediately to memory. Then, after each conversational turn, the memory generator attempts to generate a memory both from the model output and the human output; these memories are written to the memory for later use.

Hope that helps!
