### ISSUE TITLE
Using ParlAI as API on a server

### ISSUE THREAD

**Issue by Eichhof** [facebookresearch/ParlAI#4450]
Hello

First, thank you very much for the great work. I experimented with Blenderbot using the command line "python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_3B/model". This worked very well.

But now I would like to implement a webpage that uses this model. I have create a webpage (HTML and CSS) where the user can input text and should see the response of the bot. When the user sends a message, the message should be sent to my server. The server should feed the message to the bot and return the response to the webpage. The server I can implement using Javascript (node js) or Flask, that is not a problem. If a new user appears (i.e. the webpage is reopened by the same user or by another user) a new process should be created (because the bot history should not be shared).

The problem is that I don't know how I can use ParlAI for that purpose. When it would be possible to just use ParlAI in Python directly, it would not be a problem. I only found the following demo: https://github.com/facebookresearch/ParlAI/tree/main/parlai/chat_service/tasks/chatbot

How can this be done? I highly appreciate any example and help.

**Comment by mojtaba-komeili** [comment]
One solution for this is cloning the agents: your code can initialize the model before the server starts accepting incoming requests. Then for each incoming user you create a clone of the original agent and have that incoming user interact with the clone. Clones are light weight (because you don't load the model wrights individually). They have a small overhead for tracking history and other internal states related to the state of the conversation. 
I recommend you check our documentation on that [here](https://parl.ai/docs/tutorial_worlds.html#agent-sharing).

**Comment by Eichhof** [comment]
Thanks a lot for the very fast answer. Cloning makes sense. For me implementing the server is not a problem (I did that in the past). But I have really difficult times in understanding how the ParlAI agents etc. work. Is there an example how zoo:blender/blender_3B/model can be used with cloning agents so that a message can be sent to a specific agent that then returns the result?

**Comment by mojtaba-komeili** [comment]
Cloning is already implemented in most of ParlAI agents, including BlenderBot. So getting a clone of the model is as easy as any other agent.
```.python
# Creating the original agent (this may take a while)
agent_original = Agent(opt)

# Rest of your code

# Cloning the agent.
agent_clone = agent_original.clone()
```

**Comment by Eichhof** [comment]
Thanks a lot for the explanation.

How can I instantiate the original agent (i.e., BlenderBot)? I only saw the command line argument for BlenderBot.

And how can I then use this agent to send a message and retrieve a response?

**Comment by mojtaba-komeili** [comment]
The chatbot script you referenced above is a good source to see how you can initiate and interact with a model. But before that have a look at [this page](https://parl.ai/docs/tutorial_basic.html#core-concepts) in the docs for getting more familiar with core concepts in ParlAI.

**Comment by Eichhof** [comment]
What about using a flask server as described here https://github.com/khushaljethava/parlai_flask.
Will that also work?

As far as I can see the model will be initialized when the flask server is started. In the chatbot_response() method I can then clone the agent when a new user arrives.

**Comment by stephenroller** [comment]
We also have an example flask server in parlai/scripts now, but it does not distinguish between multiple users

**Comment by Eichhof** [comment]
I think distinguishing between users should not be too difficult to implement. Whenever a new user is detected a flag can be passed as argument to the chatbot_response() method of the server which then clones an agent and a corresponding session ID could be sent back to the webpage.

The only question is how to determine a new user or session of the webpage (new session = webpage reloaded) and how to detect end of a session (so that agent can be removed on server).

Is this possible in HTML or Javascript?

**Comment by stephenroller** [comment]
You should keep a separate agent clone for every user.

As far as user tracking logic, we cannot help with that. We're focused on the AI backends.

**Comment by Eichhof** [comment]
If I have cloned a agent but I don't need it anymore, how can I trash the clone?

**Comment by stephenroller** [comment]
Just "del" it.

**Comment by AbreuY** [comment]
> If I have cloned a agent but I don't need it anymore, how can I trash the clone?

Hi, I'm triying to manage diferent context for each user conected to the flask server using a clone, I'm trying to manage it by user ID. Were you able to delete the clone agent, after the user has used it?

**Comment by AbreuY** [comment]
> Just "del" it.

Hello, I'm new at this. I have been reading the information in almost all the issues, but I have no idea how to delete the cloned agent after using it. Like the previous colleague, I am using a flask server to serve a REST API. Thanks in advance.

**Comment by stephenroller** [comment]
I mean python keyword "del" it - let the GC destroy it

**Comment by AbreuY** [comment]
> I mean python keyword "del" it - let the GC destroy it

Thank you.
