### ISSUE TITLE
AttributeError: module ‘torchvision.transforms’ has no attribute ‘Scale’

### ISSUE THREAD

**Issue by edwardyoon** [facebookresearch/ParlAI#4454]
With this command "parlai interactive_web -mf zoo:dodecadialogue/all_tasks_mt/model --inference beam --beam-size 3 --beam-min-length 10 --beam-block-ngram 3 --beam-context-block-ngram 3", I receives error. I also tried to change Scale to Resize() but faced another errors. "interactive" instead of "interactive_web" is working.

**Comment by klshuster** [comment]
Thanks for flagging, this is addressed in #4459

**Comment by klshuster** [comment]
fix is merged, please reopen if there are additional concerns.
