### ISSUE TITLE
Confusion about the BlendedSkillTalk

### ISSUE THREAD

**Issue by wshCauchy** [facebookresearch/ParlAI#4456]
Hi there! I was a little confused when I read the paper about the BlendedSkillTalk. When collecting the conversations, are the guided workers instructed to switch between skills and give the most **appropriate** response or  just try to blend the skills over the course of the conversation. Thanks🙏🏻

**Comment by stephenroller** [comment]
@EricMichaelSmith will have the definitive answer.

**Comment by EricMichaelSmith** [comment]
> Hi there! I was a little confused when I read the paper about the BlendedSkillTalk. When collecting the conversations, are the guided workers instructed to switch between skills and give the most **appropriate** response or just try to blend the skills over the course of the conversation. Thanks🙏🏻

Hi @wshCauchy , it was a bit of both - the workers were encouraged to give appropriate responses in the context of the conversation but also to use the three skills if possible.

**Comment by wshCauchy** [comment]
Thanks a lot for your reply!
