### ISSUE TITLE
How to convert ParlAI to HuggingFace model?

### ISSUE THREAD

**Issue by takiholadi** [facebookresearch/ParlAI#4457]
I am interested in BlenderBot 1.0 checkpoint, pre-trained on Reddit but without finetuning. It looks like there is no such model at [HuggingFace](https://huggingface.co/models).

How can I get one?

Ideally I want to have script which takes ParlAI files: `model`, `model.dict`, `model.dict.codecs`, `model.opt` and produces HuggingFace files: `config.json`, `model.bin`.

**Comment by whrs1** [comment]
I don't know

**Comment by kauttoj** [comment]
I am also interested in this question, i.e., how to use Parlai-trained model outside Parlai. Maybe first step before conversion to HugginFace model is to save Parlai models as pure Pytorch models? Currently this seems very difficult as finetuned models are not saved fully, but you also need the original (pretrained) model. Breaking the bond with Parlai is probably not easy...

**Comment by klshuster** [comment]
> I am also interested in this question, i.e., how to use Parlai-trained model outside Parlai. Maybe first step before conversion to HugginFace model is to save Parlai models as pure Pytorch models? Currently this seems very difficult as finetuned models are not saved fully, but you also need the original (pretrained) model. Breaking the bond with Parlai is probably not easy...

That's actually not the case; a saved model file contains all of the weights of the trained model. Upon saving, the pre-trained model is not required to load.

The saved `model` is a dictionary; the key `model['model']` is the model's state dict, containing all parameter names and their corresponding weights.

One simply needs a conversion script that maps the relevant key names to their corresponding names in Huggingface. We have a few such conversion scripts that take models trained e.g. in [Fairseq](https://github.com/facebookresearch/ParlAI/blob/main/parlai/agents/bart/convert_fairseq_to_parlai.py) or [Huggingface](https://github.com/facebookresearch/ParlAI/blob/main/parlai/agents/rag/conversion_utils.py) and convert them to ParlAI; perhaps you can use these as examples.

**Comment by ajyl** [comment]
For anyone in the future, I believe the following code should load a GPT2 model trained in ParlAI into Hugging-Face:

```
def load_model():

    hf_model = GPT2LMHeadModel.from_pretrained("gpt2-medium")
    with open(MODEL_PATH, "rb") as file_p:
        hf_states = torch.load(file_p, map_location=lambda cpu, _: cpu)

    model_weights = hf_states["model"]
    converted = {}
    start_idx = model_weights["START"].item()
    for name, weights in model_weights.items():
        if name == "START":
            continue

        clean_name = name.replace("decoder.", "")
        if clean_name == "transformer.wte.weight":
            weights = weights[:start_idx, :]
        if clean_name == "lm_head.weight":
            weights = weights[:start_idx, :]
        converted[clean_name] = weights
    hf_model.load_state_dict(converted)
    return hf_model 
```
