### ISSUE TITLE
Add 'taskntalk' dataset of synthetic shapes to ParlAI. 

### ISSUE THREAD

**Issue by kdexd** [facebookresearch/ParlAI#446]
Task N' Talk is a goal-based cooperative conversation game between two agents - a questioner and answerer. It was described in _Kottur et al. '17 "Natural Language Does Not Emerge 'Naturally' in Multi-Agent Dialog"_ ([arxiv](https://arxiv.org/abs/1706.08502)). 

I implemented this paper using ParlAI ([lang-emerge-parlai](https://www.github.com/karandesai-96/lang-emerge-parlai)). As it works fine, this issue is created to group a bunch of incoming PRs related to the task.

**Comment by karandesai-96** [comment]
Next up: Our QBot and ABot in `parlai/agents`

**Comment by jaseweston** [comment]
Cool.. are they general agents that might work on some of the other parlai
tasks? (
https://github.com/facebookresearch/ParlAI/blob/master/docs/source/_static/img/tasks2.png?raw=true
)

If yes, awesome! If no, they should go in a projects/ folder instead

**Comment by karandesai-96** [comment]
I think they should be re-usable for the VisDial task. If I avoid hardcoding the dimensions of internal modules. I am speaking in context of this figure:

![image](https://user-images.githubusercontent.com/10494087/33867600-cfdd3c2a-df23-11e7-872a-b09585c6d265.png)

Taken from Das et al. 2017a _Learning Cooperative Visual Dialog Agents with Deep Reinforcement Learning_. Even this paper conducts experiments on both, Task N' Talk and VisDial.

Of course, the architecture hyperparameters are different but it has a similar structure. I will try to generalize well enough so that my agents can be used for both tasks. :)

**Comment by karandesai-96** [comment]
For completeness, this figure is from _Natural Language Does Not Emerge 'Naturally' in Multi-Agent Dialog_.
![image](https://user-images.githubusercontent.com/10494087/33867687-5f0dff1a-df24-11e7-9e68-1d629c74d8d0.png)

ListenNet works like Encoder and SpeakNet works like Decoder.

**Comment by karandesai-96** [comment]
@alexholdenmiller @jaseweston Hi, I created the agent classes and made a PR. Now in the `parlai/projects`, I can subclass the dictionary agent and provide task specific mappings (for example, `X` - `1`). Also I shall subclass my agents and simply override `dictionary_agent()` staticmethod. This should serve as an example to show easy subclassing of these agents as per requirement.

**Comment by karandesai-96** [comment]
Next up: A training script in projects and a tutorial doc on how to use these agents or extend them as per necessity.

**Comment by jaseweston** [comment]
what is the status here?

**Comment by karandesai-96** [comment]
I got engaged in academics lately. It is almost done - the teacher is not reading from validation data right now, just making a PR for it in a few days!

**Comment by jaseweston** [comment]
ok thanks!

**Comment by kdexd** [comment]
Gentle reminder to keep involved people updated: my examinations end upcoming Friday. Will get back and remove this reply too.

**Comment by kdexd** [comment]
Completely missed this out, please give me just a week more for this. Then it will be safe to close.
