### ISSUE TITLE
seeker cannot run as service

### ISSUE THREAD

**Issue by yinnxinn** [facebookresearch/ParlAI#4465]
**Bug description**

- using the office commandline  **parlai i -mf zoo:seeker/seeker_dialogue_3B/model -o gen/seeker_dialogue --search-server <search_server>** , the search-server would not be recognized. 
![image](https://user-images.githubusercontent.com/23116748/160735251-264e5a84-d206-4621-947d-4576407da58a.png)
so I add --model paramter : --model projects.seeker.agents.seeker:SeekerAgent .  And the service is ready, but when I post a request, get bug as follows:
![image](https://user-images.githubusercontent.com/23116748/160734991-7fe1a3a7-5983-43d9-bd5f-15693a47d95b.png)

**Reproduction steps**
the command is :  parlai iweb --model-file zoo:seeker/seeker_dialogue_400M/model -t wizard_of_internet --host 0.0.0.0 --port 8081 --search-server http://127.0.0.1:1234/ --model projects.seeker.agents.seeker:SeekerAgent

**Expected behavior**
is it a bug or the parameters are not configed correctly?

**Comment by klshuster** [comment]
[As specified on the project page:](https://parl.ai/projects/seeker/)

> To interact with these models, it is required to specify an initial opt (via -o/--init-opt), in the following way:

```
$ parlai i -mf zoo:seeker/seeker_dialogue_3B/model -o gen/seeker_dialogue --search-server <search_server>
```

**Comment by yinnxinn** [comment]
> [As specified on the project page:](https://parl.ai/projects/seeker/)
> 
> > To interact with these models, it is required to specify an initial opt (via -o/--init-opt), in the following way:
> 
> ```
> $ parlai i -mf zoo:seeker/seeker_dialogue_3B/model -o gen/seeker_dialogue --search-server <search_server>
> ```
__get error as follows:__

Parse Error: unrecognized arguments: --search-server http://127.0.0.1:1234/

**Comment by klshuster** [comment]
I cannot reproduce this issue on my end. can you please run and paste the full stack trace?

**Comment by yinnxinn** [comment]
> I cannot reproduce this issue on my end. can you please run and paste the full stack trace?

command line: export CUDA_VISIBLE_DEVICES='1' && parlai iweb --model-file zoo:seeker/seeker_dialogue_400M/model -t wizard_of_internet --host 0.0.0.0 --port 8081 --search-server http://127.0.0.1:1234/ -o /home/wang/.env3.7/lib/python3.7/site-packages/data/models/seeker/r2c2_blenderbot_400M/model.opt

the error as follows:
![image](https://user-images.githubusercontent.com/23116748/161190333-e57cdbf9-7c5e-4eaa-8137-7090f6b43b25.png)

`
(.env3.7) [weiwei.wang@l-bca-demo-gpu.infdc.test.ali.bc seeker]$ export CUDA_VISIBLE_DEVICES='1' && parlai iweb --model-file zoo:seeker/seeker_dialogue_400M/model -t wizard_of_internet --host 0.0.0.0 --port 8081 --search-server http://127.0.0.1:1234/ -o /home/wang/.env3.7/lib/python3.7/site-packages/data/models/seeker/r2c2_blenderbot_400M/model.opt

usage: parlai interactive_web [-h] [--helpall] [-o INIT_OPT]
                              [--allow-missing-init-opts ALLOW_MISSING_INIT_OPTS]
                              [-t TASK] [-dt DATATYPE] [-bs BATCHSIZE]
                              [-dynb {full,batchsort,None}] [-v] [--debug]
                              [-dp DATAPATH] [-m MODEL] [-mf MODEL_FILE]
                              [-im INIT_MODEL] [-d DISPLAY_EXAMPLES]
                              [--display-prettify DISPLAY_PRETTIFY]
                              [--display-add-fields DISPLAY_ADD_FIELDS]
                              [-it INTERACTIVE_TASK] [--outfile OUTFILE]
                              [--save-format {conversations,parlai}]
                              [-fixedCands LOCAL_HUMAN_CANDIDATES_FILE]
                              [--single-turn SINGLE_TURN]
                              [--log-keep-fields LOG_KEEP_FIELDS]
                              [--port PORT] [--host HOST]
                              [--mutators MUTATORS]
                              [--include-persona INCLUDE_PERSONA]
                              [--skip-empty-text SKIP_EMPTY_TEXT]
                              [--prepend-gold-knowledge PREPEND_GOLD_KNOWLEDGE]
                              [--add-skip-search-if-gold-prepended ADD_SKIP_SEARCH_IF_GOLD_PREPENDED]
                              [-esz EMBEDDING_SIZE] [-nl N_LAYERS]
                              [-hid FFN_SIZE] [--dropout DROPOUT]
                              [--attention-dropout ATTENTION_DROPOUT]
                              [--relu-dropout RELU_DROPOUT]
                              [--n-heads N_HEADS]
                              [--learn-positional-embeddings LEARN_POSITIONAL_EMBEDDINGS]
                              [--embeddings-scale EMBEDDINGS_SCALE]
                              [--n-segments N_SEGMENTS]
                              [--variant {bart,xlm,prelayernorm,aiayn}]
                              [--activation {gelu,relu}]
                              [--output-scaling OUTPUT_SCALING]
                              [--share-word-embeddings SHARE_WORD_EMBEDDINGS]
                              [-nel N_ENCODER_LAYERS] [-ndl N_DECODER_LAYERS]
                              [--model-parallel MODEL_PARALLEL]
                              [--checkpoint-activations CHECKPOINT_ACTIVATIONS]
                              [--beam-size BEAM_SIZE]
                              [--beam-min-length BEAM_MIN_LENGTH]
                              [--beam-context-block-ngram BEAM_CONTEXT_BLOCK_NGRAM]
                              [--beam-block-ngram BEAM_BLOCK_NGRAM]
                              [--beam-block-full-context BEAM_BLOCK_FULL_CONTEXT]
                              [--beam-length-penalty BEAM_LENGTH_PENALTY]
                              [--inference {delayedbeam,greedy,nucleus,topk,beam}]
                              [--topk TOPK] [--topp TOPP]
                              [--beam-delay BEAM_DELAY]
                              [--beam-block-list-filename BEAM_BLOCK_LIST_FILENAME]
                              [--temperature TEMPERATURE]
                              [--compute-tokenized-bleu COMPUTE_TOKENIZED_BLEU]
                              [-i INTERACTIVE_MODE]
                              [-emb {random,glove,glove-fixed,fasttext,fasttext-fixed,fasttext_cc,fasttext_cc-fixed}]
                              [-embp EMBEDDING_PROJECTION] [--fp16 FP16]
                              [--fp16-impl {safe,mem_efficient}]
                              [-opt OPTIMIZER] [-lr LEARNINGRATE]
                              [-clip GRADIENT_CLIP]
                              [--adafactor-eps ADAFACTOR_EPS] [-mom MOMENTUM]
                              [--nesterov NESTEROV] [-nu NUS] [-beta BETAS]
                              [-wdecay WEIGHT_DECAY] [-rc RANK_CANDIDATES]
                              [-tr TRUNCATE] [--text-truncate TEXT_TRUNCATE]
                              [--label-truncate LABEL_TRUNCATE]
                              [--history-reversed HISTORY_REVERSED]
                              [-histsz HISTORY_SIZE] [-pt PERSON_TOKENS]
                              [--split-lines SPLIT_LINES]
                              [--delimiter DELIMITER]
                              [--special-tok-lst SPECIAL_TOK_LST]
                              [-gpu GPU | --no-cuda] [--bpe-vocab BPE_VOCAB]
                              [--bpe-merge BPE_MERGE]
                              [--bpe-dropout BPE_DROPOUT]
                              [--lr-scheduler {reduceonplateau,none,fixed,invsqrt,cosine,linear}]
                              [--lr-scheduler-patience LR_SCHEDULER_PATIENCE]
                              [--lr-scheduler-decay LR_SCHEDULER_DECAY]
                              [--invsqrt-lr-decay-gamma INVSQRT_LR_DECAY_GAMMA]
                              [--init-fairseq-model INIT_FAIRSEQ_MODEL]
                              [--output-conversion-path OUTPUT_CONVERSION_PATH]

Interactive chat with a model in a web browser

optional arguments:
  -h, --help
        show this help message and exit
  --helpall
        Show usage, including advanced arguments.
  -o, --init-opt INIT_OPT
        Path to json file of options. Note: Further Command-line arguments
        override file-based options. (default: None)
  --allow-missing-init-opts ALLOW_MISSING_INIT_OPTS
        Warn instead of raising if an argument passed in with --init-opt is
        not in the target opt. (default: False)
  -t, --task TASK
        ParlAI task(s), e.g. "babi:Task1" or "babi,cbt" (default: interactive)
  -dt, --datatype DATATYPE
        choose from: train, train:ordered, valid, test. to stream data add
        ":stream" to any option (e.g., train:stream). by default train is
        random with replacement, valid is ordered, test is ordered. (default:
        train)
  -bs, --batchsize BATCHSIZE
        batch size for minibatch training schemes (default: 1)
  -dynb, --dynamic-batching {full,batchsort,None}
        Use dynamic batching (default: None)
  -v, --verbose
        Print all messages
  --debug
        Enables some debug behavior
  -dp, --datapath DATAPATH
        path to datasets, defaults to {parlai_dir}/data (default: None)
  -m, --model MODEL
        the model class name. can match parlai/agents/<model> for agents in
        that directory, or can provide a fully specified module for `from X
        import Y` via `-m X:Y` (e.g. `-m
        parlai.agents.seq2seq.seq2seq:Seq2SeqAgent`) (default: None)
  -mf, --model-file MODEL_FILE
        model file name for loading and saving models (default: None)
  -im, --init-model INIT_MODEL
        Initialize model weights and dict from this file (default: None)
  -d, --display-examples DISPLAY_EXAMPLES
  --display-prettify DISPLAY_PRETTIFY
        Set to use a prettytable when displaying examples with text candidates
        (default: False)
  --display-add-fields DISPLAY_ADD_FIELDS
        Display these fields when verbose is off (e.g., "--display-add-fields
        label_candidates,beam_texts") (default: )
  -it, --interactive-task INTERACTIVE_TASK
        Create interactive version of task (default: True)
  --outfile OUTFILE
        Saves a jsonl file containing all of the task examples and model
        replies. Set to the empty string to not save at all (default: )
  --save-format {conversations,parlai}
        Format to save logs in. conversations is a jsonl format, parlai is a
        text format. (default: conversations)
  -fixedCands, --local-human-candidates-file LOCAL_HUMAN_CANDIDATES_FILE
        File of label_candidates to send to other agent (default: None)
  --single-turn SINGLE_TURN
        If on, assumes single turn episodes. (default: False)
  --log-keep-fields LOG_KEEP_FIELDS
        Fields to keep when logging. Should be a comma separated list
        (default: all)
  --port PORT
        Port to listen on. (default: 8080)
  --host HOST
        Host from which allow requests, use 0.0.0.0 to allow all IPs (default:
        localhost)
  --mutators, -mut MUTATORS
        Apply one or more mutators to the data. (default: None)

optional arguments:
  -h, --help
        show this help message and exit
  --helpall
        Show usage, including advanced arguments.
  -d, --display-examples DISPLAY_EXAMPLES
  --display-prettify DISPLAY_PRETTIFY
        Set to use a prettytable when displaying examples with text candidates
        (default: False)
  --display-add-fields DISPLAY_ADD_FIELDS
        Display these fields when verbose is off (e.g., "--display-add-fields
        label_candidates,beam_texts") (default: )
  -it, --interactive-task INTERACTIVE_TASK
        Create interactive version of task (default: True)
  --outfile OUTFILE
        Saves a jsonl file containing all of the task examples and model
        replies. Set to the empty string to not save at all (default: )
  --save-format {conversations,parlai}
        Format to save logs in. conversations is a jsonl format, parlai is a
        text format. (default: conversations)
  --port PORT
        Port to listen on. (default: 8080)
  --host HOST
        Host from which allow requests, use 0.0.0.0 to allow all IPs (default:
        localhost)

Main ParlAI Arguments:
  -o, --init-opt INIT_OPT
        Path to json file of options. Note: Further Command-line arguments
        override file-based options. (default: None)
  --allow-missing-init-opts ALLOW_MISSING_INIT_OPTS
        Warn instead of raising if an argument passed in with --init-opt is
        not in the target opt. (default: False)
  -t, --task TASK
        ParlAI task(s), e.g. "babi:Task1" or "babi,cbt" (default: interactive)
  -dt, --datatype DATATYPE
        choose from: train, train:ordered, valid, test. to stream data add
        ":stream" to any option (e.g., train:stream). by default train is
        random with replacement, valid is ordered, test is ordered. (default:
        train)
  -bs, --batchsize BATCHSIZE
        batch size for minibatch training schemes (default: 1)
  -dynb, --dynamic-batching {full,batchsort,None}
        Use dynamic batching (default: None)
  -v, --verbose
        Print all messages
  --debug
        Enables some debug behavior
  -dp, --datapath DATAPATH
        path to datasets, defaults to {parlai_dir}/data (default: None)

ParlAI Model Arguments:
  -m, --model MODEL
        the model class name. can match parlai/agents/<model> for agents in
        that directory, or can provide a fully specified module for `from X
        import Y` via `-m X:Y` (e.g. `-m
        parlai.agents.seq2seq.seq2seq:Seq2SeqAgent`) (default: None)
  -mf, --model-file MODEL_FILE
        model file name for loading and saving models (default: None)
  -im, --init-model INIT_MODEL
        Initialize model weights and dict from this file (default: None)

Local Human Arguments:
  -fixedCands, --local-human-candidates-file LOCAL_HUMAN_CANDIDATES_FILE
        File of label_candidates to send to other agent (default: None)
  --single-turn SINGLE_TURN
        If on, assumes single turn episodes. (default: False)

World Logging:
  --log-keep-fields LOG_KEEP_FIELDS
        Fields to keep when logging. Should be a comma separated list
        (default: all)

Wizard Base Dialog Teacher arguments:
  --include-persona INCLUDE_PERSONA
        Whether to include the apprentice persona in text (default: True)
  --skip-empty-text SKIP_EMPTY_TEXT
        Whether to skip response to empty messages (may happen if persona is
        not included) (default: True)

Wizard Dialog Knowledge arguments:
  --prepend-gold-knowledge PREPEND_GOLD_KNOWLEDGE
        If true, prepend text with checked sentences (default: False)
  --add-skip-search-if-gold-prepended ADD_SKIP_SEARCH_IF_GOLD_PREPENDED
        If true, add skip search field when prepending text with checked
        sentences (default: False)

Transformer Arguments:
  -esz, --embedding-size EMBEDDING_SIZE
        Size of all embedding layers. Must be a multiple of --n-heads.
        (default: 1024)
  -nl, --n-layers N_LAYERS
        Number of transformer layers. (default: 2)
  -hid, --ffn-size FFN_SIZE
        Hidden size of the FFN layers (default: 4096)
  --dropout DROPOUT
        Dropout used around embeddings and before layer layer normalizations.
        This is used in Vaswani 2017 and works well on large datasets.
        (default: 0.1)
  --attention-dropout ATTENTION_DROPOUT
        Dropout used after attention softmax. This is not used in Vaswani
        2017. (default: 0.1)
  --relu-dropout RELU_DROPOUT
        Dropout used after the ReLU in the FFN. Not used in Vaswani 2017, but
        used in Tensor2Tensor. (default: 0.0)
  --n-heads N_HEADS
        Number of multihead attention heads (default: 16)
  --learn-positional-embeddings LEARN_POSITIONAL_EMBEDDINGS
        If off, sinusoidal embeddings are used. If on, position embeddings are
        learned from scratch. (default: True)
  --embeddings-scale EMBEDDINGS_SCALE
  --n-segments N_SEGMENTS
        The number of segments that support the model. If zero no segment and
        no langs_embedding. (default: 0)
  --variant {bart,xlm,prelayernorm,aiayn}
        Chooses locations of layer norms, etc. prelayernorm is used to match
        some fairseq models (default: bart, recommended: xlm)
  --activation {gelu,relu}
        Nonlinear activation to use. AIAYN uses relu, but more recent papers
        prefer gelu. (default: gelu)
  --output-scaling OUTPUT_SCALING
        scale the output of every transformer by this quantity. (default: 1.0)
  --share-word-embeddings SHARE_WORD_EMBEDDINGS
        Share word embeddings table for candidate and contextin the memory
        network (default: True)
  -nel, --n-encoder-layers N_ENCODER_LAYERS
        This will overidde the n-layers for asymmetrical transformers
        (default: 12)
  -ndl, --n-decoder-layers N_DECODER_LAYERS
        This will overidde the n-layers for asymmetrical transformers
        (default: 12)
  --model-parallel MODEL_PARALLEL
        Shard the layers across multiple GPUs. (default: False)
  --checkpoint-activations CHECKPOINT_ACTIVATIONS
        Recompute activations on backward pass to conserve memory. (default:
        False)

Torch Generator Agent:
  --beam-size BEAM_SIZE
        Beam size, if 1 then greedy search (default: 1)
  --beam-min-length BEAM_MIN_LENGTH
        Minimum length of prediction to be generated by the beam search
        (default: 1)
  --beam-context-block-ngram BEAM_CONTEXT_BLOCK_NGRAM
        Size n-grams to block in beam search from the context. val <= 0
        implies no blocking (default: -1)
  --beam-block-ngram BEAM_BLOCK_NGRAM
        Size n-grams to block in beam search. val <= 0 implies no blocking
        (default: -1)
  --beam-block-full-context BEAM_BLOCK_FULL_CONTEXT
        Block n-grams from the *full* history context. Specify False to block
        up to m tokens in the past, where m is truncation parameter for agent
        (default: True)
  --beam-length-penalty BEAM_LENGTH_PENALTY
        Applies a length penalty. Set to 0 for no penalty. (default: 0.65)
  --inference {delayedbeam,greedy,nucleus,topk,beam}
        Generation algorithm (default: greedy)
  --topk TOPK
        K used in Top K sampling (default: 10)
  --topp TOPP
        p used in nucleus sampling (default: 0.9)
  --beam-delay BEAM_DELAY
        used in delayedbeam search (default: 30)
  --beam-block-list-filename BEAM_BLOCK_LIST_FILENAME
        Load a text file of hard blocks for beam search to never say.
        (default: None)
  --temperature TEMPERATURE
        temperature to add during decoding (default: 1.0)
  --compute-tokenized-bleu COMPUTE_TOKENIZED_BLEU
        if true, compute tokenized bleu scores (default: False)

TorchAgent Arguments:
  -i, --interactive-mode INTERACTIVE_MODE
        Whether in full interactive mode or not, which means generating text
        or retrieving from a full set of candidates, which is necessary to
        actually do full dialogue. However, during training or quick
        validation (e.g. PPL for generation or ranking a few candidates for
        ranking models) you might want these set to off. Typically, scripts
        can set their preferred default behavior at the start, e.g. eval
        scripts. (default: True)
  -emb, --embedding-type {random,glove,glove-fixed,fasttext,fasttext-fixed,fasttext_cc,fasttext_cc-fixed}
        Choose between different strategies for initializing word embeddings.
        Default is random, but can also preinitialize from Glove or Fasttext.
        Preinitialized embeddings can also be fixed so they are not updated
        during training. (default: random)
  -embp, --embedding-projection EMBEDDING_PROJECTION
        If pretrained embeddings have a different dimensionality than your
        embedding size, strategy for projecting to the correct size. If the
        dimensions are the same, this is ignored unless you append "-force" to
        your choice. (default: random)
  --fp16 FP16
        Use fp16 computations. (default: True)
  --fp16-impl {safe,mem_efficient}
        Implementation of FP16 to use (default: safe)
  -rc, --rank-candidates RANK_CANDIDATES
        Whether the model should parse candidates for ranking. (default:
        False)
  -tr, --truncate TRUNCATE
        Truncate input lengths to increase speed / use less memory. (default:
        -1)
  --text-truncate TEXT_TRUNCATE
        Text input truncation length: if not specified, this will default to
        `truncate` (default: None)
  --label-truncate LABEL_TRUNCATE
        Label truncation length: if not specified, this will default to
        `truncate` (default: None)
  --history-reversed HISTORY_REVERSED
        Reverse the history (default: False)
  -histsz, --history-size HISTORY_SIZE
        Number of past dialog utterances to remember. (default: -1)
  -pt, --person-tokens PERSON_TOKENS
        add person tokens to history. adds __p1__ in front of input text and
        __p2__ in front of past labels when available or past utterances
        generated by the model. these are added to the dictionary during
        initialization. (default: False)
  --split-lines SPLIT_LINES
        split the dialogue history on newlines and save in separate vectors
        (default: False)
  --delimiter DELIMITER
        Join history lines with this token, defaults to newline (default: )
  --special-tok-lst SPECIAL_TOK_LST
        Comma separated list of special tokens. In case of ambiguous parses
        from special tokens, the ordering provided in this arg sets
        precedence. (default: None)
  -gpu, --gpu GPU
        which GPU to use (default: -1)
  --no-cuda
        disable GPUs even if available. otherwise, will use GPUs if available
        on the device.

Optimizer Arguments:
  -opt, --optimizer OPTIMIZER
        Optimizer choice. Possible values: adadelta, adagrad, adam, adamw,
        sparseadam, adamax, asgd, sgd, radam, rprop, rmsprop, optimizer,
        nadam, lbfgs, mem_eff_adam, adafactor. (default: sgd)
  -lr, --learningrate LEARNINGRATE
        Learning rate (default: 1)
  -clip, --gradient-clip GRADIENT_CLIP
        gradient clipping using l2 norm (default: 0.1)
  --adafactor-eps ADAFACTOR_EPS
        Epsilon values for adafactor optimizer: regularization constants for
        square gradient and parameter scale respectively (default: 1e-30,1e-3)
  -mom, --momentum MOMENTUM
        if applicable, momentum value for optimizer. (default: 0)
  --nesterov NESTEROV
        if applicable, whether to use nesterov momentum. (default: True)
  -nu, --nus NUS
        if applicable, nu value(s) for optimizer. can use a single value like
        0.7 or a comma-separated tuple like 0.7,1.0 (default: 0.7)
  -beta, --betas BETAS
        if applicable, beta value(s) for optimizer. can use a single value
        like 0.9 or a comma-separated tuple like 0.9,0.999 (default:
        0.9,0.999)
  -wdecay, --weight-decay WEIGHT_DECAY
        Weight decay on the weights. (default: None)

BPEHelper Arguments:
  --bpe-vocab BPE_VOCAB
        path to pre-trained tokenizer vocab (default: None)
  --bpe-merge BPE_MERGE
        path to pre-trained tokenizer merge (default: None)
  --bpe-dropout BPE_DROPOUT
        Use BPE dropout during training. (default: None)

Learning Rate Scheduler:
  --lr-scheduler {reduceonplateau,none,fixed,invsqrt,cosine,linear}
        Learning rate scheduler. (default: reduceonplateau)
  --lr-scheduler-patience LR_SCHEDULER_PATIENCE
        LR scheduler patience. In number of validation runs. If using fixed
        scheduler, LR is decayed every <patience> validations. (default: 3)
  --lr-scheduler-decay LR_SCHEDULER_DECAY
        Decay factor for LR scheduler, or how much LR is multiplied by when it
        is lowered. (default: 0.5)
  --invsqrt-lr-decay-gamma INVSQRT_LR_DECAY_GAMMA
        Constant used only to find the lr multiplier for the invsqrt
        scheduler. Must be set for --lr-scheduler invsqrt (default: -1)

Bart Args:
  --init-fairseq-model INIT_FAIRSEQ_MODEL
        fairseq checkpoint for bart (default: None)
  --output-conversion-path OUTPUT_CONVERSION_PATH
        where to save fairseq conversion (default: None)

Parse Error: unrecognized arguments: --search-server http://127.0.0.1:1234/
`

**Comment by klshuster** [comment]
> export CUDA_VISIBLE_DEVICES='1' && parlai iweb --model-file zoo:seeker/seeker_dialogue_400M/model -t wizard_of_internet --host 0.0.0.0 --port 8081 --search-server http://127.0.0.1:1234/ -o /home/wang/.env3.7/lib/python3.7/site-packages/data/models/seeker/r2c2_blenderbot_400M/model.opt

you'll need to set `-o gen/seeker_dialogue`, not what you have in that command

**Comment by yinnxinn** [comment]
> -o gen/seeker_dialogue

Traceback (most recent call last):
  File "/home/weiwei.wang/.env3.7/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai==1.5.1', 'console_scripts', 'parlai')())
  File "/home/weiwei.wang/.env3.7/lib/python3.7/site-packages/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home/weiwei.wang/.env3.7/lib/python3.7/site-packages/parlai/core/script.py", line 317, in superscript_main
    opt = parser.parse_args(args)
  File "/home/weiwei.wang/.env3.7/lib/python3.7/site-packages/parlai/core/params.py", line 1163, in parse_args
    self.add_extra_args(args)
  File "/home/weiwei.wang/.env3.7/lib/python3.7/site-packages/parlai/core/script.py", line 175, in add_extra_args
    sa.choices[args[0]].add_extra_args(args)
  File "/home/weiwei.wang/.env3.7/lib/python3.7/site-packages/parlai/core/params.py", line 966, in add_extra_args
    self._load_known_opts(parsed.get('init_opt'), parsed)
  File "/home/weiwei.wang/.env3.7/lib/python3.7/site-packages/parlai/core/params.py", line 1016, in _load_known_opts
    new_opt = Opt.load_init(optfile)
  File "/home/weiwei.wang/.env3.7/lib/python3.7/site-packages/parlai/core/opt.py", line 177, in load_init
    f"Could not find filename '{optfile} or opt preset '{optfile}.opt'. "
FileNotFoundError: Could not find filename 'gen/seeker_dialogue or opt preset 'gen/seeker_dialogue.opt'. Please check https://parl.ai/docs/opt_presets.html for a list of available opt presets.

**Comment by klshuster** [comment]
we've bundled all the code in the newest parlai release (1.6.0), so maybe try re-installing via pip? or pull from main and run setup.py again? again, these commands work well for me, so not totally sure what's going on

alternatively, if you can identify where the `parlai/opt_presets/gen/seeker_dialogut.opt` file is locally, you can pass the full path in as well

**Comment by yinnxinn** [comment]
> we've bundled all the code in the newest parlai release (1.6.0), so maybe try re-installing via pip? or pull from main and run setup.py again? again, these commands work well for me, so not totally sure what's going on
> 
> alternatively, if you can identify where the `parlai/opt_presets/gen/seeker_dialogut.opt` file is locally, you can pass the full path in as well

Thanks，through identify locally I fix the  problem . The reason is that **there's no gen files in parlai/opt_presets** . I will check it .
