### ISSUE TITLE
[Seek Help] How to add new optimizer in this platform???

### ISSUE THREAD

**Issue by ruleGreen** [facebookresearch/ParlAI#4471]
I want to implement one self-defined optimizer, more specifically this one => https://github.com/Sanyuan-Chen/RecAdam/blob/master/RecAdam.py. anyone can help me? or tell me what should I do?

**Comment by stephenroller** [comment]
https://github.com/facebookresearch/ParlAI/blob/732c112857205b25f1b6655befea4f22a3d6cf60/parlai/core/torch_agent.py#L437

add a line here like

```
optims["recadam"] = RecAdam
```

**Comment by ruleGreen** [comment]
@stephenroller Thank u for your reply. I put the above optimzier under the utils directory in ParlAI, and then I add the new line in the function u provided. Pls check the screen capture. But I still get the error. is there anything wrong? can u provide more details?

<img width="575" alt="image" src="https://user-images.githubusercontent.com/26263128/161210932-a50c5536-c98a-40bb-b39c-7cd941850c84.png">


<img width="1370" alt="image" src="https://user-images.githubusercontent.com/26263128/161210838-5cebddb3-a662-4c6c-94d1-27de83dbd912.png">

**Comment by klshuster** [comment]
try moving `optims['recadam']` out of the `try/catch` (e.g. to right below `optims['adafactor'] = Adafactor`)
