### ISSUE TITLE
SeeKeR: General Questions

### ISSUE THREAD

**Issue by Mahmoud-Yasser-16** [facebookresearch/ParlAI#4475]
Hi there,
I am reading the source code of SeeKeR and I can not understand what is DRM Mutators in the SeeKeR codes.

Any ideas how to understand them?

**Comment by Mahmoud-Yasser-16** [comment]
Thanks for your reply. 
How about the DRM and KRM mentioned in the seeker_dialogue.opt? 
I understand it's a kind of search for inference (because of drm_beam_size and drm_beam_min_length) but I can't really track where those come from.

Any idea what are these?

**Comment by klshuster** [comment]
DRM == Dialogue Response Model
KRM == Knowledge Response Model

To allow the ability to specify different generation parameters for each of the generation steps, we prefix the normal opt arguments with these 3-letter representations.

**Comment by Mahmoud-Yasser-16** [comment]
Thanks for your response!
Another Question, when search-decision in COMPUTE mode, What I understand from the code that a special token (__is-search-required__) is added to the input text so that the search_decision_agent (which is the encoder-decoder for all the stage) produce an output (__do-search__ or __do-not-search__). 
My questions are the following:
  1) Am I missing something in the description about?
  2) If what i said is true, how was the search_decision_agent trained (datasets, training methodology, etc.)? I can not find find any relevant information about the search_decision_agent in the paper. 

Thanks again for your help! 
And WOW, AMAZING WORK!

**Comment by klshuster** [comment]
This functionality is available but is not tested; you can take a look at the search decision teachers for more information
