### ISSUE TITLE
SeeKer Distilled Edition?

### ISSUE THREAD

**Issue by EmElleE** [facebookresearch/ParlAI#4477]
**Is your feature request related to a problem? Please describe.**

Is there going to be a release of the model in distilled form? It seems like it would be impossible to run unless you had a high spec machine.

**Describe the solution you'd like**

If there can be a distilled model that would be ideal, for lower spec pc's so we can fine tune with that thanks!

**Comment by stephenroller** [comment]
Iirc there's a 400m seeker model already, which is what we target in distillation.

**Comment by EmElleE** [comment]
@stephenroller better question is the preprocessed data for each stage of the modules available for download, I am looking for more of a 100m parameter model.

**Comment by stephenroller** [comment]
We are unlikely to produce a distilled model of that size. We generally find below 400m parameters the quality drops of rapidly, and even 400m can be difficult to stomach for us.

**Comment by ArEnSc** [comment]
Oh I see okay! Well than time is saved on my front than thanks!

**Comment by EmElleE** [comment]
@stephenroller is there any code for preprocessing the training data? I would still like to give it a shot using dark knowledge. Did you guys use the same technique to get the 400M model?

**Comment by klshuster** [comment]
[On the project page](https://github.com/facebookresearch/ParlAI/tree/main/projects/seeker#seeker-dialogue-training), we provide the task names for the SeeKeR training tasks

**Comment by EmElleE** [comment]
@klshuster alright thanks I guess ill read the paper a bit more thanks for the response!
