### ISSUE TITLE
License clarification for dialogue_safety dataset

### ISSUE THREAD

**Issue by airdish-hpcnt** [facebookresearch/ParlAI#4480]
I'm planning to use the datasets released from [dialogue_safety](https://parl.ai/projects/dialogue_safety/) project. (Paper: Build it Break it Fix it for Dialogue Safety: Robustness from Adversarial Human Attack) But I couldn't find data license information under task nor project directory.

Can you specify the license for this dataset?

**Comment by stephenroller** [comment]
Generally we try for CC-BY-SA 4.0. It's probably a reasonable assumption here. I'll flag with relevant people to clarify explicitly.

@meganung

**Comment by stephenroller** [comment]
Some datasets are CC-BY-SA-NC but usually only bc we didn't push though the paperwork to get the NC dropped

**Comment by meganung** [comment]
yeah I'd assume the default license, I don't think there's any special licenses on this one.

**Comment by djaym7** [comment]
The default license is MIT for the ParlAI repository, should we assume that for dataset ?
