### ISSUE TITLE
Integration of custom IR retriever model via agent

### ISSUE THREAD

**Issue by thenewera-ru** [facebookresearch/ParlAI#4485]
Let's say I have some custom IR model built upon other framework / ecosystem. I can wrap it around `Agent` abstraction similarly to how it is being done [here](https://github.com/facebookresearch/ParlAI/blob/f91bd8061658a00249b839aca3800fd73642a6c2/parlai/agents/tfidf_retriever/tfidf_retriever.py#L29). 

---

So, Let's say:
```python
class FancyIRAgent(Agent):
   def __init__(self, ...):
      pass
   def retrieve_top_k(self, query: str, top_k: int = 10):
      # perform search and return candidates
```

How do I integrate custom module wrapped around `class Agent(object):` https://github.com/facebookresearch/ParlAI/blob/f91bd8061658a00249b839aca3800fd73642a6c2/parlai/core/agents.py#L62 into main BB2 pipeline?

- [ ] Are there any other tutorials dedicated to adding custom information retrieval besides interactive stand-alone ?
`parlai interactive --model tfidf_retriever -mf zoo:wikipedia_full/tfidf_retriever/model`

- [ ] If there're no tutorials which part of the codebase would you advice to start from?

P.S.> The codebase is built upon many abstractions and it's challenging to debug and extend it even if you want something as simple as "search by custom api".

Thanks!

**Comment by klshuster** [comment]
Retrievers for our retrieval-augmented models (RAG, FiD, BB2) are all built with some variation of the [`retriever_factory` function](https://github.com/facebookresearch/ParlAI/blob/main/parlai/agents/rag/retrievers.py#L1465), which allows for any type specified in [this enum](https://github.com/facebookresearch/ParlAI/blob/9372227e49dd48e5b690bfad9003631644c9d5e0/parlai/agents/rag/args.py#L80-L91). 

All retrievers subclass [`RagRetriever`](https://github.com/facebookresearch/ParlAI/blob/9372227e49dd48e5b690bfad9003631644c9d5e0/parlai/agents/rag/retrievers.py#L363), and require implementing a [`retrieve_and_score`](https://github.com/facebookresearch/ParlAI/blob/9372227e49dd48e5b690bfad9003631644c9d5e0/parlai/agents/rag/retrievers.py#L425-L438) method.

We offer a sample [`TFIDFRetriever`](https://github.com/facebookresearch/ParlAI/blob/9372227e49dd48e5b690bfad9003631644c9d5e0/parlai/agents/rag/retrievers.py#L707) implementation; hopefully, you can base your custom one on something like that.

Finally, if you were to implement your own `RagRetriever`, you would specify it with the command line arg `--rag-retriever-type my_type`, where `my_type` is a value in the `RetrieverType` enum above.

The [RAG agent page](https://github.com/facebookresearch/ParlAI/tree/main/parlai/agents/rag) may provide some more information about the whole pipeline, if you're curious.

Hope that helps!
