### ISSUE TITLE
Pytorch/Cuda conflict between maskrcnn_benchmark package and ParlAI

### ISSUE THREAD

**Issue by narjislaraki** [facebookresearch/ParlAI#4486]
Hello, 

For context, I've been working with the multimodal_blenderbot, trying to have an image-based conversation through the safe_interactive script. It has come to my knowledge that it wasn't possible directly so I included the image in the batch, and tried to use faster_r_cnn_152_32x8d, with the ImageLoader class to load my pictures as tensors. 

The problem is with the maskrcnn_benchmark package, I've been trying to install it following the INSTALL.md file but I'm currently having trouble with the last build giving me a **RuntimeError: Error compiling objects for extension**. I've managed to bypass this error in the past by downgrading pytorch to 1.8 if I recall correctly, but then there was another issue with the ParlAI project on its own needing >= 1.10 version, and upgrading it does work to a certain extent in which the package is imported but fails later on at the _C import on maskrcnn_benchmark's end, I get **undefined symbol: _ZNK2at6Tensor3addEN3c106ScalarES2_a** which is I'm assuming related to either pytorch or cuda's version as well. 

So I'm stuck in a loophole where upgrading or downgrading pytorch/cuda works for a certain step and ends up creating a problem at another one.

My current environment consists of : 

OS = Ubuntu 20.04.3 LTS
python = 3.9.12
pytorch = 1.11.0+cu113 (from https://download.pytorch.org/whl/torch_stable.html)
torchvision = 0.12.0+cu113 
cuda = 11.3
nvidia's driver version = 510.39.01 

Has anyone of you managed to include this package successfully with no problem ?

**Comment by klshuster** [comment]
You may need to install an earlier release of ParlAI that requires a lower version of pytorch (which is compatible with the maskrcnn_benchmark package). Unfortunately, we are not the maintainers of the maskrcnn_benchmark code, and it looks like it has not been updated in a while, so I'm unsure if it's compatible with later versions of pytorch.

**Comment by narjislaraki** [comment]
> You may need to install an earlier release of ParlAI that requires a lower version of pytorch (which is compatible with the maskrcnn_benchmark package). Unfortunately, we are not the maintainers of the maskrcnn_benchmark code, and it looks like it has not been updated in a while, so I'm unsure if it's compatible with later versions of pytorch.

It worked ! Thank you.
