### ISSUE TITLE
how to create task with  Opt() ?  RuntimeError: No task specified. Please select a task with --task {task_name}.

### ISSUE THREAD

**Issue by tempdeltavalue** [facebookresearch/ParlAI#4490]
parser = ParlaiParser()
opt =  Opt()
// opt['task']="some"

// opt = parser.parse_args()

agent = RepeatLabelAgent(opt)
world = create_task(opt, agent)

code from docs
https://parl.ai/docs/tutorial_basic.html

**Comment by stephenroller** [comment]
ParlaiParser has two Boolean arguments and (I think) the second needs to be set to false explicitly

**Comment by stephenroller** [comment]
You commented out parse_args?

**Comment by tempdeltavalue** [comment]
@stephenroller Yes, because I try to run that code in colab (just want to investigate infrastructure)

**Comment by tempdeltavalue** [comment]
https://parl.ai/docs/core/worlds.html?highlight=create%20world#parlai.core.worlds.create_task

**Comment by stanicaa** [comment]
Just had the same problem ... solution is on the same documentation page, but a bit lower. Basically, one needs to initiate a task after initiating the variable opt, something like
opt['task']="babi:Task1k:1"

Now, you have to download the necessary files in advance. This is done from the command line (ie no need to be in python), specifying the task that needs to be downloaded. 
parlai display_data --task babi:task1k:1

Additional detailed explanations @ https://parl.ai/docs/tutorial_basic.html#what-is-parlai , under 'Tasks'
