### ISSUE TITLE
"parlai eval_model" doesn't produce tensorboard report when "--tensorboard-log" is enabled

### ISSUE THREAD

**Issue by DrMatters** [facebookresearch/ParlAI#4495]
Command to reproduce the bug:

```
parlai eval_model -t blended_skill_talk -mf zoo:blender/blender_90M/model --skip-generation True --tensorboard-log True --tensorboard-logdir ~/tb_report_for_issuue/
```

A user expects to see a folder called `tb_report_for_issuue` in the home directory containing the evaluation report data. The expected behavior is the same as when enabling tensorboard logging with `parlai train_model`.

P.S. It may be helpful to add other loggers (such as WandB) to the `eval_model` script.

**Comment by stephenroller** [comment]
Considering TB expects a time series, not a static evaluation, what should be logged?

Happy to accept a patch for this if you've got an idea.

**Comment by DrMatters** [comment]
PR: #4497
@stephenroller
