### ISSUE TITLE
Import of parlai in Python script fails

### ISSUE THREAD

**Issue by Eichhof** [facebookresearch/ParlAI#4501]
Hello

I'm running Windows 10 with python 3.9.12. I have installed parlai using pip install parlai. That worked and parlai also works on the command line, for example `parlai safe_interactive -t blended_skill_talk -mf zoo:blender/blender_9B/model `on command line works well.

When I now try to import parlai in a python script by using `from parlai.core.agents import create_agent_from_model_file`, I'm getting the following error:

> ModuleNotFoundError: No module named 'parlai.core'; 'parlai' is not a package

How can I solve this error?

**Comment by stephenroller** [comment]
Seems you have not installed correctly. Perhaps you didn't "pip install -e ."?

**Comment by Eichhof** [comment]
Actually, I create a virtual environment in conda and activated that environment. Then I did "python -m pip install parlai". Is that not correct?

**Comment by stephenroller** [comment]
Idk, we don't support Windows, but many of our community members have gotten it working.
