### ISSUE TITLE
What File Prints Out Bot's Response

### ISSUE THREAD

**Issue by shivencar** [facebookresearch/ParlAI#4510]
I was just wondering what file/files are used to print out the bot's response on my terminal window. I am currently running parlai/scripts/safe_interactive.py.

Thanks!!!

**Comment by klshuster** [comment]
if you're using safe_interactive, the print happens in the [safe local human observe method](https://github.com/facebookresearch/ParlAI/blob/857b5de0da947df9ac43f9fc202ceb54ac642dfd/parlai/agents/safe_local_human/safe_local_human.py#L79-L102)

the actual printing of the response is handled by the [display_messages](https://github.com/facebookresearch/ParlAI/blob/857b5de0da947df9ac43f9fc202ceb54ac642dfd/parlai/utils/misc.py#L491) function

**Comment by shivencar** [comment]
Thanks Kurt, happy to say it worked. I was wondering how to remove context ([context]: Skateboarding: I don't want this) and make it run the same each time. I am running python3.9 parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_400Mdistill/model --safety=none --include_personas=False


Cheers!

**Comment by klshuster** [comment]
if you get rid of `-t blended_skill_talk`, that should remove the context line

**Comment by shivencar** [comment]
Appreciate the help.
