### ISSUE TITLE
Feed dialog history to bot

### ISSUE THREAD

**Issue by gabriel-skantze** [facebookresearch/ParlAI#4511]
Use this to open other questions or issues, and provide context here.
Is there a general way to feed an entire dialog history to a bot (e.g. BlenderBot), and generate a response from that?

**Comment by klshuster** [comment]
if you're in interactive mode, you can just feed a delimited version of the history as your first message to the bot; i.e., using `\n` or a double space (BlenderBot's delimiter) to separate turns of context

**Comment by gabriel-skantze** [comment]
Thanks! Where do I find what delimiter is used by a specific bot?

**Comment by klshuster** [comment]
in the associated `model.opt` file, you can look for the `delimiter` key.

So for BlenderBot, you'd find it in `data/models/blender/blender_3B/model.opt`
