### ISSUE TITLE
Blenderbot2 Hyperparameter Documentation

### ISSUE THREAD

**Issue by Jsiewierski11** [facebookresearch/ParlAI#4527]
I was wondering if there was any place to find documentation on what are the different hyper parameters you can use with the BlenderBot2 model.opt file. If there isn't one in place where would be the best place to add the information in a potential pull request (the model card?). I've been digging through the code to find what are the different options to play around with and would be happy to help build out the documentation if it is does not already exist.

**Comment by klshuster** [comment]
We tried to provide useful help strings for the BB2 hyperparams [where they are defined](https://github.com/facebookresearch/ParlAI/blob/ecdfbd0bb2ab76876e9fd3817d4502c3938a2ade/projects/blenderbot2/agents/blenderbot2.py#L228)

More information regarding some of the retrieval hyperparameters [can be found in this file](https://github.com/facebookresearch/ParlAI/blob/main/parlai/agents/rag/args.py)
