### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'passages.tsv'

### ISSUE THREAD

**Issue by ksdihgfmata** [facebookresearch/ParlAI#4528]
### Description
I want to run this, however it does not find the passage.tsv file. 
What am I doing wrong? Have I forgotten something? 

### Reproduction

$ /usr/bin/python generate_dense_embeddings.py -mf zoo:hallucination/bart_fid_rag/model --dpr-model True --passages-file passages.tsv --outfile emb_bart_fid_rag/out --num-shards 1 --shard-id 0 -bs 32

gives me:   File "/usr/local/lib/python3.8/dist-packages/parlai/agents/rag/retrievers.py", line 79, in load_passage_reader
    with f_open(ctx_file) as tsvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'passages.tsv'

but in this case:
$sudo python -m parlai interactive --model-file zoo:hallucination/bart_fid_rag/model

it gives me: FileExistsError: [Errno 17] File exists: '/usr/local/lib/python3.8/dist-packages/data/models/hallucination/wiki_passages'

Now I am a little bit confused.

**Comment by klshuster** [comment]
can you please paste the full stack trace for both errors? 

Additionally, could you please clarify what you're trying to do? The first command looks like you want to generate dense embs for your own passages file -- does this file exist in the location you're specifying?

**Comment by ksdihgfmata** [comment]
Hello thank you for getting in touch. 

 

Maybe you can help me. I would like to give the Blenderbotmodel additional data and integrate it into the knowledge. 

 

I have been slowly getting to grips with everything and am now facing this problem: 

 


~/ParlAI$ sudo python3 parlai/agents/rag/scripts/generate_dense_embeddings.py -mf zoo:hallucination/bart_fid_rag/model --dpr-model true --passages-file data/models/hallucination/wow_passages/psgs_w100.tsv --outfile /tmp/out --num-shards 1 --shard-id 0 -bs 32 /usr/bin/python generate_dense_embeddings.py -mf zoo:hallucination/bart_fid_rag/model --dpr-model True --passages-file passages.tsv --outfile emb_bart_fid_rag/out --num-shards 1 --shard-id 0 -bs 32
usage: generate_dense_embeddings.py [--help] [--helpall] [--init-opt INIT_OPT] [--allow-missing-init-opts ALLOW_MISSING_INIT_OPTS] [--task TASK] [--datatype DATATYPE] [--batchsize BATCHSIZE]
                                    [--dynamic-batching {None,batchsort,full}] [--verbose] [--debug] [--datapath DATAPATH] [--model MODEL] [--model-file MODEL_FILE] [--im INIT_MODEL]
                                    [--passages-file PASSAGES_FILE] [--outfile OUTFILE] [--num-shards NUM_SHARDS] [--shard-id SHARD_ID] [--dpr-model DPR_MODEL]
                                    [--candidates {batch,inline,fixed,batch-all-cands}] [--eval-candidates {batch,inline,fixed,vocab,batch-all-cands}]
                                    [--interactive-candidates {fixed,inline,vocab}] [--repeat-blocking-heuristic REPEAT_BLOCKING_HEURISTIC] [--fixed-candidates-path FIXED_CANDIDATES_PATH]
                                    [--fixed-candidate-vecs FIXED_CANDIDATE_VECS] [--encode-candidate-vecs ENCODE_CANDIDATE_VECS] [--init-model INIT_MODEL] [--train-predict TRAIN_PREDICT]
                                    [--cap-num-predictions CAP_NUM_PREDICTIONS] [--ignore-bad-candidates IGNORE_BAD_CANDIDATES] [--rank-top-k RANK_TOP_K]
                                    [--return-cand-scores RETURN_CAND_SCORES] [--use-memories USE_MEMORIES] [--wrap-memory-encoder WRAP_MEMORY_ENCODER] [--memory-attention {cosine,dot,sqrt}]
                                    [--normalize-sent-emb NORMALIZE_SENT_EMB] [--share-encoders SHARE_ENCODERS] [--learn-embeddings LEARN_EMBEDDINGS] [--data-parallel DATA_PARALLEL]
                                    [--reduction-type {first,max,mean}] [--polyencoder-type {codes,n_first}] [--poly-n-codes POLY_N_CODES] [--poly-attention-type {basic,sqrt,multihead}]
                                    [--poly-attention-num-heads POLY_ATTENTION_NUM_HEADS] [--codes-attention-type {basic,sqrt,multihead}]
                                    [--codes-attention-num-heads CODES_ATTENTION_NUM_HEADS] [--embedding-size EMBEDDING_SIZE] [--n-layers N_LAYERS] [--ffn-size FFN_SIZE] [--dropout DROPOUT]
                                    [--attention-dropout ATTENTION_DROPOUT] [--relu-dropout RELU_DROPOUT] [--n-heads N_HEADS] [--learn-positional-embeddings LEARN_POSITIONAL_EMBEDDINGS]
                                    [--embeddings-scale EMBEDDINGS_SCALE] [--n-segments N_SEGMENTS] [--variant {prelayernorm,xlm,aiayn,bart}] [--activation {relu,gelu}]
                                    [--output-scaling OUTPUT_SCALING] [--share-word-embeddings SHARE_WORD_EMBEDDINGS] [--n-encoder-layers N_ENCODER_LAYERS]
                                    [--n-decoder-layers N_DECODER_LAYERS] [--model-parallel MODEL_PARALLEL] [--checkpoint-activations CHECKPOINT_ACTIVATIONS]
                                    [--generation-model {transformer/generator,bart,t5}] [--query-model {bert,bert_from_parlai_rag,dropout_poly}] [--rag-model-type {token,sequence,turn}]
                                    [--thorough THOROUGH] [--n-extra-positions N_EXTRA_POSITIONS] [--gold-knowledge-passage-key GOLD_KNOWLEDGE_PASSAGE_KEY]
                                    [--gold-knowledge-title-key GOLD_KNOWLEDGE_TITLE_KEY] [--rag-retriever-query {one_turn,full_history}]
                                    [--rag-retriever-type {dpr,tfidf,dpr_then_poly,poly_faiss,search_engine,search_term_faiss,observation_echo_retriever}]
                                    [--retriever-debug-index {None,none,exact,compressed}] [--n-docs N_DOCS] [--min-doc-token-length MIN_DOC_TOKEN_LENGTH]
                                    [--max-doc-token-length MAX_DOC_TOKEN_LENGTH] [--rag-query-truncate RAG_QUERY_TRUNCATE] [--print-docs PRINT_DOCS] [--path-to-index PATH_TO_INDEX]
                                    [--path-to-dense-embeddings PATH_TO_DENSE_EMBEDDINGS] [--dpr-model-file DPR_MODEL_FILE] [--path-to-dpr-passages PATH_TO_DPR_PASSAGES]
                                    [--retriever-embedding-size RETRIEVER_EMBEDDING_SIZE] [--tfidf-max-doc-paragraphs TFIDF_MAX_DOC_PARAGRAPHS] [--tfidf-model-path TFIDF_MODEL_PATH]
                                    [--dpr-num-docs DPR_NUM_DOCS] [--poly-score-initial-lambda POLY_SCORE_INITIAL_LAMBDA] [--polyencoder-init-model POLYENCODER_INIT_MODEL]
                                    [--poly-faiss-model-file POLY_FAISS_MODEL_FILE] [--regret REGRET] [--regret-intermediate-maxlen REGRET_INTERMEDIATE_MAXLEN]
                                    [--regret-model-file REGRET_MODEL_FILE] [--regret-dict-file REGRET_DICT_FILE] [--regret-override-index REGRET_OVERRIDE_INDEX]
                                    [--indexer-type {exact,compressed}] [--indexer-buffer-size INDEXER_BUFFER_SIZE] [--compressed-indexer-factory COMPRESSED_INDEXER_FACTORY]
                                    [--compressed-indexer-nprobe COMPRESSED_INDEXER_NPROBE] [--rag-turn-n-turns RAG_TURN_N_TURNS] [--rag-turn-marginalize {doc_only,doc_then_turn}]
                                    [--rag-turn-discount-factor RAG_TURN_DISCOUNT_FACTOR] [--beam-size BEAM_SIZE] [--beam-min-length BEAM_MIN_LENGTH]
                                    [--beam-context-block-ngram BEAM_CONTEXT_BLOCK_NGRAM] [--beam-block-ngram BEAM_BLOCK_NGRAM] [--beam-block-full-context BEAM_BLOCK_FULL_CONTEXT]
                                    [--beam-length-penalty BEAM_LENGTH_PENALTY] [--inference {nucleus,beam,greedy,topk,delayedbeam}] [--topk TOPK] [--topp TOPP] [--beam-delay BEAM_DELAY]
                                    [--beam-block-list-filename BEAM_BLOCK_LIST_FILENAME] [--temperature TEMPERATURE] [--compute-tokenized-bleu COMPUTE_TOKENIZED_BLEU]
                                    [--interactive-mode INTERACTIVE_MODE] [--embedding-type {random,glove,glove-fixed,fasttext,fasttext-fixed,fasttext_cc,fasttext_cc-fixed}]
                                    [--embedding-projection EMBEDDING_PROJECTION] [--fp16 FP16] [--fp16-impl {safe,mem_efficient}] [--optimizer OPTIMIZER] [--learningrate LEARNINGRATE]
                                    [--gradient-clip GRADIENT_CLIP] [--adafactor-eps ADAFACTOR_EPS] [--momentum MOMENTUM] [--nesterov NESTEROV] [--nus NUS] [--betas BETAS]
                                    [--weight-decay WEIGHT_DECAY] [--rank-candidates RANK_CANDIDATES] [--truncate TRUNCATE] [--text-truncate TEXT_TRUNCATE] [--label-truncate LABEL_TRUNCATE]
                                    [--history-reversed HISTORY_REVERSED] [--history-size HISTORY_SIZE] [--person-tokens PERSON_TOKENS] [--split-lines SPLIT_LINES] [--delimiter DELIMITER]
                                    [--special-tok-lst SPECIAL_TOK_LST] [-gpu GPU | --no-cuda] [--bpe-vocab BPE_VOCAB] [--bpe-merge BPE_MERGE] [--bpe-dropout BPE_DROPOUT]
                                    [--lr-scheduler {reduceonplateau,none,fixed,invsqrt,cosine,linear}] [--lr-scheduler-patience LR_SCHEDULER_PATIENCE]
                                    [--lr-scheduler-decay LR_SCHEDULER_DECAY] [--invsqrt-lr-decay-gamma INVSQRT_LR_DECAY_GAMMA] [--t5-model-arch {t5-small,t5-base,t5-large,t5-3b,t5-11b}]
                                    [--t5-model-parallel T5_MODEL_PARALLEL] [--t5-dropout T5_DROPOUT]
                                    [--t5-generation-config {summarization,translation_en_to_de,translation_en_to_fr,translation_en_to_ro}]

Generate Dense Embs

optional arguments:
  --help, --h
        show this help message and exit
  --helpall
        Show usage, including advanced arguments.
  --passages-file PASSAGES_FILE
        file containing passages to encode. file should be a tsv file. (default: None)
  --outfile OUTFILE
        where to save the passage embeddings (default: None)
  --num-shards NUM_SHARDS
        how many workers to use to split up the work (default: 1)
  --shard-id SHARD_ID
        shard id for this worker. should be between 0 and num_shards (default: None)
  --dpr-model DPR_MODEL
        Specify True to indicate that the provided model file is a DPR Model (default: False)

Main ParlAI Arguments:
  --init-opt, --o INIT_OPT
        Path to json file of options. Note: Further Command-line arguments override file-based options. (default: None)
  --allow-missing-init-opts ALLOW_MISSING_INIT_OPTS
        Warn instead of raising if an argument passed in with --init-opt is not in the target opt. (default: False)
  --task, --t TASK
        ParlAI task(s), e.g. "babi:Task1" or "babi,cbt" (default: None)
  --datatype, --dt DATATYPE
        choose from: train, train:ordered, valid, test. to stream data add ":stream" to any option (e.g., train:stream). by default train is random with replacement, valid is ordered, test is
        ordered. (default: train)
  --batchsize, --bs BATCHSIZE
        batch size for minibatch training schemes (default: 1)
  --dynamic-batching, --dynb {None,batchsort,full}
        Use dynamic batching (default: None)
  --verbose, --v
        Print all messages
  --debug
        Enables some debug behavior
  --datapath, --dp DATAPATH
        path to datasets, defaults to {parlai_dir}/data (default: None)

ParlAI Model Arguments:
  --model, --m MODEL
        the model class name. can match parlai/agents/<model> for agents in that directory, or can provide a fully specified module for `from X import Y` via `-m X:Y` (e.g. `-m
        parlai.agents.seq2seq.seq2seq:Seq2SeqAgent`) (default: None)
  --model-file, --mf MODEL_FILE
        model file name for loading and saving models (default: None)
  --im INIT_MODEL
        Initialize model weights and dict from this file (default: None)

TorchRankerAgent:
  --candidates, --cands {batch,inline,fixed,batch-all-cands}
        The source of candidates during training (see TorchRankerAgent._build_candidates() for details). (default: inline)
  --eval-candidates, --ecands {batch,inline,fixed,vocab,batch-all-cands}
        The source of candidates during evaluation (defaults to the samevalue as --candidates if no flag is given) (default: inline)
  --interactive-candidates, --icands {fixed,inline,vocab}
        The source of candidates during interactive mode. Since in interactive mode, batchsize == 1, we cannot use batch candidates. (default: fixed)
  --repeat-blocking-heuristic REPEAT_BLOCKING_HEURISTIC
        Block repeating previous utterances. Helpful for many models that score repeats highly, so switched on by default. (default: True)
  --fixed-candidates-path, --fcp FIXED_CANDIDATES_PATH
        A text file of fixed candidates to use for all examples, one candidate per line (default: None)
  --fixed-candidate-vecs FIXED_CANDIDATE_VECS
        One of "reuse", "replace", or a path to a file with vectors corresponding to the candidates at --fixed-candidates-path. The default path is a /path/to/model-file.<cands_name>, where
        <cands_name> is the name of the file (not the full path) passed by the flag --fixed-candidates-path. By default, this file is created once and reused. To replace it, use the "replace"
        option. (default: reuse)
  --encode-candidate-vecs ENCODE_CANDIDATE_VECS
        Cache and save the encoding of the candidate vecs. This might be used when interacting with the model in real time or evaluating on fixed candidate set when the encoding of the
        candidates is independent of the input. (default: True)
  --init-model INIT_MODEL
        Initialize model with weights from this file. (default: None)
  --train-predict TRAIN_PREDICT
        Get predictions and calculate mean rank during the train step. Turning this on may slow down training. (default: False)
  --cap-num-predictions CAP_NUM_PREDICTIONS
        Limit to the number of predictions in output.text_candidates (default: 100)
  --ignore-bad-candidates IGNORE_BAD_CANDIDATES
        Ignore examples for which the label is not present in the label candidates. Default behavior results in RuntimeError. (default: False)
  --rank-top-k RANK_TOP_K
        Ranking returns the top k results of k > 0, otherwise sorts every single candidate according to the ranking. (default: -1)
  --return-cand-scores RETURN_CAND_SCORES
        Return sorted candidate scores from eval_step (default: False)

Transformer Arguments:
  --use-memories USE_MEMORIES
        use memories: must implement the function `_vectorize_memories` to use this (default: False)
  --wrap-memory-encoder WRAP_MEMORY_ENCODER
        wrap memory encoder with MLP (default: False)
  --memory-attention {cosine,dot,sqrt}
        similarity for basic attention mechanism when using transformer to encode memories (default: sqrt)
  --normalize-sent-emb NORMALIZE_SENT_EMB
  --share-encoders SHARE_ENCODERS
  --learn-embeddings LEARN_EMBEDDINGS
        learn embeddings (default: True)
  --data-parallel DATA_PARALLEL
        use model in data parallel, requires multiple gpus (default: False)
  --reduction-type {first,max,mean}
        Type of reduction at the end of transformer (default: mean)

Polyencoder Arguments:
  --polyencoder-type {codes,n_first}
        Type of polyencoder, either we computevectors using codes + attention, or we simply take the first N vectors. (default: codes)
  --poly-n-codes POLY_N_CODES
        number of vectors used to represent the contextin the case of n_first, those are the numberof vectors that are considered. (default: 64)
  --poly-attention-type {basic,sqrt,multihead}
        Type of the top aggregation layer of the poly-encoder (where the candidate representation isthe key) (default: basic)
  --poly-attention-num-heads POLY_ATTENTION_NUM_HEADS
        In case poly-attention-type is multihead, specify the number of heads (default: 4)
  --codes-attention-type {basic,sqrt,multihead}
        Type (default: basic)
  --codes-attention-num-heads CODES_ATTENTION_NUM_HEADS
        In case codes-attention-type is multihead, specify the number of heads (default: 4)

Transformer Arguments:
  --embedding-size, --esz EMBEDDING_SIZE
        Size of all embedding layers. Must be a multiple of --n-heads. (default: 300)
  --n-layers, --nl N_LAYERS
        Number of transformer layers. (default: 2)
  --ffn-size, --hid FFN_SIZE
        Hidden size of the FFN layers (default: 300)
  --dropout DROPOUT
        Dropout used around embeddings and before layer layer normalizations. This is used in Vaswani 2017 and works well on large datasets. (default: 0.0)
  --attention-dropout ATTENTION_DROPOUT
        Dropout used after attention softmax. This is not used in Vaswani 2017. (default: 0.0)
  --relu-dropout RELU_DROPOUT
        Dropout used after the ReLU in the FFN. Not used in Vaswani 2017, but used in Tensor2Tensor. (default: 0.0)
  --n-heads N_HEADS
        Number of multihead attention heads (default: 2)
  --learn-positional-embeddings LEARN_POSITIONAL_EMBEDDINGS
        If off, sinusoidal embeddings are used. If on, position embeddings are learned from scratch. (default: False)
  --embeddings-scale EMBEDDINGS_SCALE
  --n-segments N_SEGMENTS
        The number of segments that support the model. If zero no segment and no langs_embedding. (default: 0)
  --variant {prelayernorm,xlm,aiayn,bart}
        Chooses locations of layer norms, etc. prelayernorm is used to match some fairseq models (default: aiayn, recommended: xlm)
  --activation {relu,gelu}
        Nonlinear activation to use. AIAYN uses relu, but more recent papers prefer gelu. (default: relu, recommended: gelu)
  --output-scaling OUTPUT_SCALING
        scale the output of every transformer by this quantity. (default: 1.0)
  --share-word-embeddings SHARE_WORD_EMBEDDINGS
        Share word embeddings table for candidate and contextin the memory network (default: True)
  --n-encoder-layers, --nel N_ENCODER_LAYERS
        This will overidde the n-layers for asymmetrical transformers (default: -1)
  --n-decoder-layers, --ndl N_DECODER_LAYERS
        This will overidde the n-layers for asymmetrical transformers (default: -1)
  --model-parallel MODEL_PARALLEL
        Shard the layers across multiple GPUs. (default: False)
  --checkpoint-activations CHECKPOINT_ACTIVATIONS
        Recompute activations on backward pass to conserve memory. (default: False)

RAG Model Args:
  --generation-model {transformer/generator,bart,t5}
        which generation model to use (default: bart)
  --query-model {bert,bert_from_parlai_rag,dropout_poly}
        Which query model to use for DPR. (default: bert)
  --rag-model-type {token,sequence,turn}
        which rag model decoding to use. (default: token)
  --thorough THOROUGH
        whether to use thorough decoding for rag sequence. (default: False)

Modified RAG Args:
  --n-extra-positions N_EXTRA_POSITIONS
        Specify > 0 to include extra positions in the encoder, in which retrieved knowledge will go. In this setup, knowledge is _appended_ instead of prepended. (default: 0)
  --gold-knowledge-passage-key GOLD_KNOWLEDGE_PASSAGE_KEY
        key in the observation dict that indicates the gold knowledge passage. Specify, along with --debug, to compute passage retrieval metrics at train/test time. (default: checked_sentence)
  --gold-knowledge-title-key GOLD_KNOWLEDGE_TITLE_KEY
        key in the observation dict that indicates the gold knowledge passage title. Specify, along with --debug, to compute passage retrieval metrics at train/test time. (default: title)

RAG Retriever Args:
  --rag-retriever-query {one_turn,full_history}
        What to use as the query for retrieval. `one_turn` retrieves only on the last turn of dialogue; `full_history` retrieves based on the full dialogue history. (default: full_history)
  --rag-retriever-type {dpr,tfidf,dpr_then_poly,poly_faiss,search_engine,search_term_faiss,observation_echo_retriever}
        Which retriever to use (default: dpr)
  --retriever-debug-index {None,none,exact,compressed}
        Load specified small index, for debugging. (default: None)
  --n-docs N_DOCS
        How many documents to retrieve (default: 5)
  --min-doc-token-length MIN_DOC_TOKEN_LENGTH
        minimum amount of information to retain from document. Useful to define if encoder does not use a lot of BPE token context. (default: 64)
  --max-doc-token-length MAX_DOC_TOKEN_LENGTH
        maximum amount of information to retain from document. (default: 256)
  --rag-query-truncate RAG_QUERY_TRUNCATE
        Max token length of query for retrieval. (default: 512)
  --print-docs PRINT_DOCS
        Whether to print docs; usually useful during interactive mode. (default: False)

RAG Dense Passage Retriever Args:
  --path-to-index PATH_TO_INDEX
        path to FAISS Index. (default: zoo:hallucination/wiki_index_compressed/compressed_pq)
  --path-to-dense-embeddings PATH_TO_DENSE_EMBEDDINGS
        path to dense embeddings directory used to build index. Default None will assume embeddings and index are in the same directory. (default: None)
  --dpr-model-file DPR_MODEL_FILE
        path to DPR Model. (default: zoo:hallucination/multiset_dpr/hf_bert_base.cp)
  --path-to-dpr-passages PATH_TO_DPR_PASSAGES
        Path to DPR passages, used to build index. (default: zoo:hallucination/wiki_passages/psgs_w100.tsv)
  --retriever-embedding-size RETRIEVER_EMBEDDING_SIZE
        Embedding size of dense retriever (default: 768)

RAG TFIDF Retriever Args:
  --tfidf-max-doc-paragraphs TFIDF_MAX_DOC_PARAGRAPHS
        If > 0, limit documents to this many paragraphs (default: -1)
  --tfidf-model-path TFIDF_MODEL_PATH
        Optionally override TFIDF model. (default: zoo:wikipedia_full/tfidf_retriever/model)

RAG DPR-POLY Retriever Args:
  --dpr-num-docs DPR_NUM_DOCS
        In two stage retrieval, how many DPR documents to retrieve (default: 25)
  --poly-score-initial-lambda POLY_SCORE_INITIAL_LAMBDA
        In two stage retrieval, how much weight to give to the poly scores. Note: Learned parameter. Specify initial value here (default: 0.5)
  --polyencoder-init-model POLYENCODER_INIT_MODEL
        Which init model to initialize polyencoder with. Specify wikito or reddit to use models from the ParlAI zoo; otherwise, provide a path to a trained polyencoder (default: wikito)

RAG PolyFAISS retriever args:
  --poly-faiss-model-file POLY_FAISS_MODEL_FILE
        path to poly-encoder for use in poly-faiss retrieval. (default: None)

RAG ReGReT args:
  --regret REGRET
        Retrieve, Generate, Retrieve, Tune. Retrieve, generate, then retrieve again, and finally tune (refine). (default: False)
  --regret-intermediate-maxlen REGRET_INTERMEDIATE_MAXLEN
        Maximum length in intermediate regret generation (default: 32)
  --regret-model-file REGRET_MODEL_FILE
        Path to model for initial round of retrieval. (default: None)
  --regret-dict-file REGRET_DICT_FILE
        Path to dict file for model for initial round of retrieval. (default: None)
  --regret-override-index REGRET_OVERRIDE_INDEX
        Overrides the index used with the ReGReT model, if using separate models. I.e., the initial round of retrieval uses the same index as specified for the second round of retrieval
        (default: False)

RAG Indexer Args:
  --indexer-type {exact,compressed}
        Granularity of RAG Indexer. Choose compressed to save on RAM costs, at the possible expense of accuracy. (default: compressed)
  --indexer-buffer-size INDEXER_BUFFER_SIZE
        buffer size for adding vectors to the index (default: 65536)
  --compressed-indexer-factory COMPRESSED_INDEXER_FACTORY
        If specified, builds compressed indexer from a FAISS Index Factory. see https://github.com/facebookresearch/faiss/wiki/The-index-factory for details (default: IVF4096_HNSW128,PQ128)
  --compressed-indexer-nprobe COMPRESSED_INDEXER_NPROBE
        How many centroids to search in compressed indexer. See https://github.com/facebookresearch/faiss/wiki/Faiss-indexes#cell-probe-methods-indexivf-indexes for details (default: 64)

RAG-Turn Args:
  --rag-turn-n-turns RAG_TURN_N_TURNS
        how many turns to split up retrieval into. The most recent text is split by delimiter; all turns after (n-1)th turn are combined. (default: 2)
  --rag-turn-marginalize {doc_only,doc_then_turn}
        how to marginalize rag-turn. (default: doc_then_turn)
  --rag-turn-discount-factor RAG_TURN_DISCOUNT_FACTOR
        discount factor for turns beyond most recent one. We employ exponential discounting. Only considered if 0 < factor < 1.0. (default: 1.0)

Torch Generator Agent:
  --beam-size BEAM_SIZE
        Beam size, if 1 then greedy search (default: 1)
  --beam-min-length BEAM_MIN_LENGTH
        Minimum length of prediction to be generated by the beam search (default: 1)
  --beam-context-block-ngram BEAM_CONTEXT_BLOCK_NGRAM
        Size n-grams to block in beam search from the context. val <= 0 implies no blocking (default: -1)
  --beam-block-ngram BEAM_BLOCK_NGRAM
        Size n-grams to block in beam search. val <= 0 implies no blocking (default: -1)
  --beam-block-full-context BEAM_BLOCK_FULL_CONTEXT
        Block n-grams from the *full* history context. Specify False to block up to m tokens in the past, where m is truncation parameter for agent (default: True)
  --beam-length-penalty BEAM_LENGTH_PENALTY
        Applies a length penalty. Set to 0 for no penalty. (default: 0.65)
  --inference {nucleus,beam,greedy,topk,delayedbeam}
        Generation algorithm (default: greedy)
  --topk TOPK
        K used in Top K sampling (default: 10)
  --topp TOPP
        p used in nucleus sampling (default: 0.9)
  --beam-delay BEAM_DELAY
        used in delayedbeam search (default: 30)
  --beam-block-list-filename BEAM_BLOCK_LIST_FILENAME
        Load a text file of hard blocks for beam search to never say. (default: None)
  --temperature TEMPERATURE
        temperature to add during decoding (default: 1.0)
  --compute-tokenized-bleu COMPUTE_TOKENIZED_BLEU
        if true, compute tokenized bleu scores (default: False)

TorchAgent Arguments:
  --interactive-mode, --i INTERACTIVE_MODE
        Whether in full interactive mode or not, which means generating text or retrieving from a full set of candidates, which is necessary to actually do full dialogue. However, during
        training or quick validation (e.g. PPL for generation or ranking a few candidates for ranking models) you might want these set to off. Typically, scripts can set their preferred
        default behavior at the start, e.g. eval scripts. (default: False)
  --embedding-type, --emb {random,glove,glove-fixed,fasttext,fasttext-fixed,fasttext_cc,fasttext_cc-fixed}
        Choose between different strategies for initializing word embeddings. Default is random, but can also preinitialize from Glove or Fasttext. Preinitialized embeddings can also be fixed
        so they are not updated during training. (default: random)
  --embedding-projection, --embp EMBEDDING_PROJECTION
        If pretrained embeddings have a different dimensionality than your embedding size, strategy for projecting to the correct size. If the dimensions are the same, this is ignored unless
        you append "-force" to your choice. (default: random)
  --fp16 FP16
        Use fp16 computations. (default: False)
  --fp16-impl {safe,mem_efficient}
        Implementation of FP16 to use (default: safe)
  --rank-candidates, --rc RANK_CANDIDATES
        Whether the model should parse candidates for ranking. (default: False)
  --truncate, --tr TRUNCATE
        Truncate input lengths to increase speed / use less memory. (default: 1024)
  --text-truncate TEXT_TRUNCATE
        Text input truncation length: if not specified, this will default to `truncate` (default: None)
  --label-truncate LABEL_TRUNCATE
        Label truncation length: if not specified, this will default to `truncate` (default: None)
  --history-reversed HISTORY_REVERSED
        Reverse the history (default: False)
  --history-size, --histsz HISTORY_SIZE
        Number of past dialog utterances to remember. (default: -1)
  --person-tokens, --pt PERSON_TOKENS
        add person tokens to history. adds __p1__ in front of input text and __p2__ in front of past labels when available or past utterances generated by the model. these are added to the
        dictionary during initialization. (default: False)
  --split-lines SPLIT_LINES
        split the dialogue history on newlines and save in separate vectors (default: False)
  --delimiter DELIMITER
        Join history lines with this token, defaults to newline (default: )
  --special-tok-lst SPECIAL_TOK_LST
        Comma separated list of special tokens. In case of ambiguous parses from special tokens, the ordering provided in this arg sets precedence. (default: None)
  -gpu, --gpu GPU
        which GPU to use (default: -1)
  --no-cuda
        disable GPUs even if available. otherwise, will use GPUs if available on the device.

Optimizer Arguments:
  --optimizer, --opt OPTIMIZER
        Optimizer choice. Possible values: adadelta, adagrad, adam, adamw, sparseadam, adamax, asgd, sgd, radam, rprop, rmsprop, optimizer, nadam, lbfgs, mem_eff_adam, adafactor. (default:
        adamax)
  --learningrate, --lr LEARNINGRATE
        Learning rate (default: 0.0001)
  --gradient-clip, --clip GRADIENT_CLIP
        gradient clipping using l2 norm (default: 0.1)
  --adafactor-eps ADAFACTOR_EPS
        Epsilon values for adafactor optimizer: regularization constants for square gradient and parameter scale respectively (default: 1e-30,1e-3)
  --momentum, --mom MOMENTUM
        if applicable, momentum value for optimizer. (default: 0)
  --nesterov NESTEROV
        if applicable, whether to use nesterov momentum. (default: True)
  --nus, --nu NUS
        if applicable, nu value(s) for optimizer. can use a single value like 0.7 or a comma-separated tuple like 0.7,1.0 (default: 0.7)
  --betas, --beta BETAS
        if applicable, beta value(s) for optimizer. can use a single value like 0.9 or a comma-separated tuple like 0.9,0.999 (default: 0.9,0.999)
  --weight-decay, --wdecay WEIGHT_DECAY
        Weight decay on the weights. (default: None)

BPEHelper Arguments:
  --bpe-vocab BPE_VOCAB
        path to pre-trained tokenizer vocab (default: None)
  --bpe-merge BPE_MERGE
        path to pre-trained tokenizer merge (default: None)
  --bpe-dropout BPE_DROPOUT
        Use BPE dropout during training. (default: None)

Learning Rate Scheduler:
  --lr-scheduler {reduceonplateau,none,fixed,invsqrt,cosine,linear}
        Learning rate scheduler. (default: reduceonplateau)
  --lr-scheduler-patience LR_SCHEDULER_PATIENCE
        LR scheduler patience. In number of validation runs. If using fixed scheduler, LR is decayed every <patience> validations. (default: 3)
  --lr-scheduler-decay LR_SCHEDULER_DECAY
        Decay factor for LR scheduler, or how much LR is multiplied by when it is lowered. (default: 0.5)
  --invsqrt-lr-decay-gamma INVSQRT_LR_DECAY_GAMMA
        Constant used only to find the lr multiplier for the invsqrt scheduler. Must be set for --lr-scheduler invsqrt (default: -1)

T5 Args:
  --t5-model-arch {t5-small,t5-base,t5-large,t5-3b,t5-11b}
  --t5-model-parallel T5_MODEL_PARALLEL
        use HF model parallel (default: False)
  --t5-dropout T5_DROPOUT
        Dropout for T5 (default: 0.0)
  --t5-generation-config {summarization,translation_en_to_de,translation_en_to_fr,translation_en_to_ro}
        Task specific generation config for T5 (default: None)

Parse Error: unrecognized arguments: /usr/bin/python generate_dense_embeddings.py


 

 

 

 

 

 

i would like to change the model to a blenderbot model zoo:blenderbot2/blenderbot2_3B/model would that be possible?

Could you also help me on how to create my own tsv file? I have the information or texts and would like to integrate them as a tsv file into the Blenderbot. 

 

 

 

 

 

 

 

 


 
 

Gesendet: Freitag, 06. Mai 2022 um 21:15 Uhr
Von: "Kurt Shuster" ***@***.***>
An: "facebookresearch/ParlAI" ***@***.***>
Cc: "bkgesl_mata" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [facebookresearch/ParlAI] FileNotFoundError: [Errno 2] No such file or directory: 'passages.tsv' (Issue #4528)


 

can you please paste the full stack trace for both errors?

Additionally, could you please clarify what you're trying to do? The first command looks like you want to generate dense embs for your own passages file -- does this file exist in the location you're specifying?

**Comment by klshuster** [comment]
> `~/ParlAI$ sudo python3 parlai/agents/rag/scripts/generate_dense_embeddings.py -mf zoo:hallucination/bart_fid_rag/model --dpr-model true --passages-file data/models/hallucination/wow_passages/psgs_w100.tsv --outfile /tmp/out --num-shards 1 --shard-id 0 -bs 32 /usr/bin/python generate_dense_embeddings.py -mf zoo:hallucination/bart_fid_rag/model --dpr-model True --passages-file passages.tsv --outfile emb_bart_fid_rag/out --num-shards 1 --shard-id 0 -bs 32`

you have repeated the command twice. You should try the following:

```
~/ParlAI$ sudo python3 parlai/agents/rag/scripts/generate_dense_embeddings.py -mf zoo:hallucination/bart_fid_rag/model --dpr-model true --passages-file data/models/hallucination/wow_passages/psgs_w100.tsv --outfile /tmp/out --num-shards 1 --shard-id 0 -bs 32 
```

In this command, you have specified the wiki passages for embedding generation. If you'd like to use a different set of passages, you'll need to specify a different `--passages-file`. The [instructions on this page](https://github.com/facebookresearch/ParlAI/tree/main/parlai/agents/rag#2-generate-dense-embeddings-1-2-hours-minutes-if-sharded-appropriately---50-x-1-gpu) specify how to format your `.tsv` file. That page also describes how to index the dense embeddings to make a retrieval index.

> i would like to change the model to a blenderbot model zoo:blenderbot2/blenderbot2_3B/model would that be possible?

Once you have created your own set of dense embeddings, you can use the BB2 model. You would simply use the same interactive commands as you normally would (`parlai interactive --model-file  zoo:blenderbot2/blenderbot2_3B/model`) and then specify `--rag-retriever-type dpr --path-to-dpr-passages /path/to/passages/file --path-to-index /path/to/built/index

**Comment by ksdihgfmata** [comment]
Hello, thank you for answering me. 
Exactly I have generated my own .tsv file and made an HNSW32.index from it as indicated. Exactly this call from you I have also already tried, but get this error message: 
EOFError: Compressed file ended before the end-of-stream marker was reached
