### ISSUE TITLE
Train Poly-Encoder with own dataset and huggingface language model

### ISSUE THREAD

**Issue by r1ckC139** [facebookresearch/ParlAI#4535]
Hi there,
I want to train a retrieval model use poly-encoder, my dataset consists of query and documents pairs and corresponding labels (1 for relevance, 0 for not). I use a huggingface transformers pre-trained model, here (#4263) i found how to train poly-encoder with huggingface transformers and dialog dataset but in my case i don't know how to pass my dataset (retrieval dataset) properly.

**Comment by klshuster** [comment]
[Please see my reply](https://github.com/facebookresearch/ParlAI/issues/4263#issuecomment-1122467495) for how to proceed
