### ISSUE TITLE
Running a crowdworker task with a custom "agent"

### ISSUE THREAD

**Issue by colemanhindes** [facebookresearch/ParlAI#4541]
Hi I am enjoying parlai, it seems to be very well written! I have gotten some of the demos up and running and I have written my own "Agent", which works great using the interactive.py script. 

Ultimately my goal is to create tasks for crowdworkers to chat with my custom agent. However I am having a hard time figuring out how to configure a yaml file that includes my newly created agent (which doesn't require any command line parameters). The documentation for the "browser" model chat uses a model from the model zoo, and the same method does not seem to work for custom models. 

Are there examples or documentation I can use for this? 

Thanks for your time

**Comment by klshuster** [comment]
> My goal is to create tasks for crowdworkers to chat with my custom agent

You can take a look at our [crowdsourcing code](https://github.com/facebookresearch/ParlAI/tree/main/parlai/crowdsourcing) (specifically the `projects`) if you want to see what folks have done in the past

> The documentation for the "browser" model chat uses a model from the model zoo, and the same method does not seem to work for custom models.

Anything you'd specify on the command line to instantiate your custom agent would go in the `config.yaml`. E.g., suppose your agent was at `parlai.agents.my_agent.agents:MyCustomAgent`. Looking at the [default config](https://github.com/facebookresearch/ParlAI/blob/5f13a2d805131688aaf5253d4e29adc8b4ad6020/parlai/chat_service/tasks/chatbot/config.yml), you might change it to the following:

```
tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    blender_90M:
      model: parlai.agents.my_agent.agents:MyCustomAgent
      model_file: path/to/my/custom/model
      custom_arg1: custom_value1
      custom_arg2: custom_value2
      custom_arg3: custom_value3
      interactive_mode: True
additional_args:
  page_id: 1 # Configure Your Own Page
```
