### ISSUE TITLE
script to pull out the actual training/validating data points that models did not perform well 

### ISSUE THREAD

**Issue by Ruihua-Fang** [facebookresearch/ParlAI#4544]
**Is your feature request related to a problem? Please describe.**
I havn't found any solution in the documentation for a script that can pull out the actual testing/validating sample data that models did not perform well.  The purpose is to analyze and try to understand why those did not perform well and may render insights for improving the models

**Describe the solution you'd like**
I am interested in writing a script to do this task

**Describe alternatives you've considered**
I havn't found any alternatives and please advice if there is any I might have missed.  Thanks!

**Additional context**
None at the moment

**Comment by stephenroller** [comment]
You can use the `eval_model --world-logs` argument to save predictions, metrics, etc. This outputs a json file that you should be able to reasonable filter/sort/analyze etc.
