### ISSUE TITLE
Rag-Sequence model with gold knowledge

### ISSUE THREAD

**Issue by Youmna-H** [facebookresearch/ParlAI#4547]
Hi,
I would like to test the Rag Sequence model that uses the gold knowledge (as elaborated in https://arxiv.org/pdf/2104.07567.pdf) Is there a pre-trained model that I can test? Also what is the right command to use for that? (cc @klshuster)

**Comment by klshuster** [comment]
All details regarding the hallucination project [can be found here](https://parl.ai/projects/hallucination/); to evaluate the rag sequence model on a given task, you may run the following command:

```
parlai eval_model --model-file zoo:hallucination/bart_rag_sequence/model --task my_task
```

We do not report any RAG Sequence models that utilize gold knowledge

**Comment by Youmna-H** [comment]
Thank you. Yeah the paper reports RAG-token with gold knowledge is that available?

**Comment by Youmna-H** [comment]
Thanks Kurt. I was refering to the "Gold" model in Table 1 in the paper https://arxiv.org/pdf/2104.07567.pdf

**Comment by Youmna-H** [comment]
Ah, so the gold knowledge isn't utilised with the context using Sequence or token models, it is just a simple concatenation? If so, I guess it is fine then, don't worry about it.

**Comment by Youmna-H** [comment]
I see. Thank you so much @klshuster!
