### ISSUE TITLE
[BB2] How can I interact with a bot by multi-session?

### ISSUE THREAD

**Issue by jeesoobang** [facebookresearch/ParlAI#4549]
During the conversation with BlenderBot 2, I confirmed that the bot and I were having a conversation and the conversation summary was saved to memory. 
I chatted with the bot using the below command
`python -m parlai interactive --model-file zoo:blenderbot2/blenderbot2_3B/model --search_server relevant_server`

1. How can I use this memory in the next session? 
2. Does the bot not use this memory in current interacting session, but uses the stored memory only when moving on to the next session?

**Comment by klshuster** [comment]
1. Are you referring to the conversational history, or the generated memory by the model? If the former, you can just feed in a new-line delimited version as your first message with the model; if the latter, you can also feed in as new-line delimited with the appropriate prefixes ("your persona";  "partner's perasona"), and then specify `--memory-key full_text` to let the model know to look in the conversational context to extract the prior memories

2. The bot should be using the memory in the current interacting session

**Comment by jeesoobang** [comment]
Thank you for your response! :)

**Comment by gitsand996** [comment]
@klshuster can I feed in as new-line delimited text the memory I need at each turn of the conversation, or only at the first turn?

**Comment by klshuster** [comment]
as long as it has the appropriate prefix, you can feed in the memory whenever
