### ISSUE TITLE
Build a chatbot that will support multiple users

### ISSUE THREAD

**Issue by adomigold** [facebookresearch/ParlAI#4550]
Hello, I want to build a project where multiple users can chat with the bot on the web interface with a flask with their unique personal conversations I read about how to clone agents to support that but I could not figure out how to do it. I really need help here.
Thanks

**Comment by adomigold** [comment]
Hello i was able to find solution for multiple users. But know i want to delete agent when user doesn't send a message for a certain time.

**Comment by BlueDice37** [comment]
@adomigold I am facing the same issue that you shared. Can you share your approach?
