### ISSUE TITLE
How to create model files for a new agents?

### ISSUE THREAD

**Issue by rguan1** [facebookresearch/ParlAI#4555]
Hi,

I've been working on adding GPT-3 and Eliza as agents that I can use in self-chat. So far, I've been able to add a GPT-3 and Eliza agent. For instance, the following command works:
`parlai self_chat -m gpt3 --num-self-chats 1 --selfchat-max-turns 10 -partner-model-file zoo:blender/blender_90M/model`

However, I am unable to use GPT-3 as a partner-model-file because the agent file is not the same thing as a model file. So, is there any model I can follow to implement a model file for GPT-3 in the zoo folder or otherwise somewhere else?

For reference, the code below is the agent implementation that I used for GPT-3. A very similar implementation that extended Agent was used for the Eliza agent as well. 

```python
#!/usr/bin/env python3

# Copyright (c) Facebook, Inc. and its affiliates.
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
"""

"""

from typing import Optional
from parlai.core.params import ParlaiParser
from parlai.core.opt import Opt
from parlai.core.agents import Agent
from parlai.core.message import Message
import openai  
import os 


def query_completion_api(prompt, engine='text-davinci-001'):
    response = openai.Completion.create(
        engine=engine, 
        prompt=prompt, 
        temperature=0.9, 
        max_tokens=150, 
        top_p=1, 
        frequency_penalty=1, 
        presence_penalty=0.6, 
        stop=["###"]
    )
    
    return response

def prompt_compose(context, instructions, seed_turns):
    return f'{context}\n ###\n{instructions}\n{seed_turns}'


class Gpt3Agent(Agent):
    @classmethod
    def add_cmdline_args(
        cls, parser: ParlaiParser, partial_opt: Optional[Opt] = None
    ) -> ParlaiParser:
        group = parser.add_argument_group('GPT3 Arguments')
        return parser

    def __init__(self, opt, shared=None):
        super().__init__(opt)
        self.id = 'Gpt3Agent'
        self.sturns = ''
        
        openai.api_key = os.getenv("GPT3_KEY")  

    # def act(self):
    #     return Message(
    #         {'id': self.getID(), 'text': self.fixed_response, 'episode_done': False}
    #     )

    def act(self):
        """
        Generate response to last seen observation.

        Replies with a message from using the Alice bot.

        :returns: message dict with reply
        """

        obs = self.observation
        
        context = "This is conversation with an AI assistant"
        instr = "Chat with the other person"
        # sturns = "" if obs is None else obs 

        if obs is None:
            self.sturns += f"Human: \nAI: "
        else:
            self.sturns += f"Human: {obs['text']}\nAI: "

        p = prompt_compose(context, instr, self.sturns)
        resp = query_completion_api(p)
        resp_txt = resp.choices[0].text 

        resp_txt = resp_txt.rstrip()

        self.sturns += f"{resp_txt}\n"
        
        return Message(
            {'id': self.getID(), 'text': resp_txt, 'episode_done': False}
        )

```

**Comment by stephenroller** [comment]
Would you be willing to make a PR adding that agent to parlai? Many would appreciate it.

You could fake a model file with just "touch model" and manually creating a corresponding model.opt that contains only your agent's options. Take a look at another work's model.opt for inspiration.

**Comment by stephenroller** [comment]
Would love an Eliza agent in the lib too :p

**Comment by rguan1** [comment]
Great! I'll try what you suggested for models and see if that works. After that, I'd be happy to make a PR to add GPT-3 and Eliza to ParlAI.

**Comment by rguan1** [comment]
Faking a model with an empty model file and a sparse model.opt file works. Currently, I've located the model file in the data folder (i.e ParlAI/data/models/gpt3). Is that the right place to put it? I only put it there because I can see that model and model.opt files for existing models like BlenderBot are there. 

Also, if I make a PR, should I include the model in the model zoo? If so, how should I proceed?

**Comment by klshuster** [comment]
> Faking a model with an empty model file and a sparse model.opt file works. Currently, I've located the model file in the data folder (i.e ParlAI/data/models/gpt3). Is that the right place to put it? I only put it there because I can see that model and model.opt files for existing models like BlenderBot are there.

Yes, that is where `zoo:` model files get mapped to. E.g., if you had `zoo:gpt3/model`, it would look for `model` and `model.opt` in `data/models/gpt3/`

> Also, if I make a PR, should I include the model in the model zoo? If so, how should I proceed?
Yes, that would be great. 

You would first add your model to the [`model_list.py`](https://github.com/facebookresearch/ParlAI/blob/main/parlai/zoo/model_list.py); there are instructions at the top of the file for how to format your entry, and you can look at other examples to do so. 

Then, you would add a folder with a `build.py` file to the [zoo directory](https://github.com/facebookresearch/ParlAI/blob/main/parlai/zoo/); this will "download" your model file / opt to the appropriate `data/models` location. In your case, it'll require no download, and simply a write to the files.
