### ISSUE TITLE
Same PPL result using different decoding strategies

### ISSUE THREAD

**Issue by Hao0501** [facebookresearch/ParlAI#4556]
Hi,

I was trying to evaluate the empathic dialogue model from the DodecaDialogue model by using command: 

**parlai eval_model -mf zoo:dodecadialogue/empathetic_dialogues_ft/model -t empathetic_dialogues --metrics bleu-4 --skip-generation false --batchsize 64 --inference greedy -topp 0 --topk 0**  or

**parlai eval_model -mf zoo:dodecadialogue/empathetic_dialogues_ft/model -t empathetic_dialogues --metrics bleu-4 --skip-generation false --batchsize 64 --inference nucleus --topp 0.95 --topk 0**

I've tried to evaluate the performance by implementing other decoding strategies like --inference topk, --inference nucleus and --inference beam. But I get the same result for PPL 11.08 no matter which algorithm I choose. Why?

Thanks,
Hao

**Comment by klshuster** [comment]
Hi Hao, perplexity is a generation-agnostic measure; we measure the perplexity with reference to the target label, and it is calculated via looking at each individual token loss for the target tokens. BLEU-4, however (as you've specified via `--metrics`), will change with various decoding algorithms

**Comment by Hao0501** [comment]
> Hi Hao, perplexity is a generation-agnostic measure; we measure the perplexity with reference to the target label, and it is calculated via looking at each individual token loss for the target tokens. BLEU-4, however (as you've specified via `--metrics`), will change with various decoding algorithms

Thanks Kurt, it solve my confusions :)
