### ISSUE TITLE
Store knowledge separate for each user Blenderbot 2.0

### ISSUE THREAD

**Issue by adomigold** [facebookresearch/ParlAI#4561]
Hello.
In your blog for Blenderbot 2.0, I quote "The knowledge is stored separately for each person it speaks with, which ensures that no new information learned in one conversation is used in another". My question is, I wanna know how to do that cause I read the documentation but I never found where it instructs how to achieve that.

**Comment by klshuster** [comment]
This is done automatically within the agent code

**Comment by adomigold** [comment]
@klshuster can you please assist

**Comment by klshuster** [comment]
memories are re-extracted/re-encoded each turn of conversation, so it should not be possible for memories to mix between separate conversations (especially with agent clones). could you please send your command for running the bot?

**Comment by adomigold** [comment]
`parlai flask --model-file zoo:blenderbot2/blenderbot2_400M/model --search-server http://localhost:8000 --no-cuda --loglevel debug`
That is the command that i use

**Comment by klshuster** [comment]
do you have evidence of the mixing of memories?

**Comment by adomigold** [comment]
Can I send the screenshot of those two conversations? because I use a flask for this project

**Comment by klshuster** [comment]
sure
