### ISSUE TITLE
image_chat Image data could not be downloaded completely  

### ISSUE THREAD

**Issue by chengguangtang** [facebookresearch/ParlAI#4571]
**Bug description**
Please enter a clear and concise description of what the bug is.

image_chat Image data could not be downloaded completely
Downloading: 100%|██████████████████████████████████████████████████████████████| 201858/201858 [01:05<00:00, 3067.15it/s]
21:54:14 | Of 55 items attempted downloading, 55 had errors.

**Reproduction steps**
Enter steps to reproduce the behavior.
run command:  parlai eval_model -t image_chat -mf zoo:image_chat/transresnet_multimodal/model -dt test

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Logs**
Please paste the command line output:
(parlai) [root@VM-116-140-centos /data/ParlAI]# parlai eval_model -t image_chat -mf zoo:image_chat/transresnet_multimodal/model -dt test
21:52:56 | Overriding opt["attention_dropout"] to 0.2 (previously: 0)
21:52:56 | Overriding opt["task"] to image_chat (previously: internal:comment_battle:imageDialog)
21:52:56 | Overriding opt["model_file"] to /data/ParlAI/data/models/image_chat/transresnet_multimodal/model (previously: /private/home/kshuster/transresnet_mm_release_models/model)
21:52:56 | Overriding opt["datatype"] to test (previously: train)
21:52:56 | loading dictionary from /data/ParlAI/data/models/image_chat/transresnet_multimodal/model.dict
21:52:57 | num words = 250006
Please confirm that you have obtained permission to work with the YFCC100m dataset, as outlined by the steps listed at https://multimediacommons.wordpress.com/yfcc100m-core-dataset/ [Y/y]: y
NOTE: This script will download each image individually from the s3 server on which the images are hosted. This will take a *very long* time. Are you sure you would like to continue? [Y/y]: y
[downloading images to /data/ParlAI/data/yfcc_images]
  0%|                                                                                          | 0/201858 [00:00<?, ?it/s]21:53:10 | Of 201858 items, 201803 already existed; only going to download 55 items.
100%|████████████████████████████████████████████████████████████████████████▉| 201803/201858 [00:01<00:00, 142371.94it/s]21:53:10 | Going to download 1 chunks with 100 images per chunk using 32 processes.
Downloading: 100%|███████████████████████████████████████████████████████████▉| 201803/201858 [00:20<00:00, 142371.94it/s]21:54:14 | Bad download - chunk: 0, dest_file: ac80c5633d76c27b352ee6352ddbb3.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac88d66ad654f2739bbfdfbe55c2bdb.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8b1beeb050fa26b970dc2fee5ef539.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac81b9680ba5cab4436ad2528555da.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8788acffc6226816827a943e69bbf.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8d98a8fab765d92a678295fe9b2d.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac866ff82c6319994c8568a91f8aa2a.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac845e9d3081d9415d8a4b49c7dca7.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8aaf341c293ed43ce33358c4801c.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8b31a49a2ed5375724ad7e8fd80ff.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac827b33adaaefb430ce867c4fec7732.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac84b4dc481dd318ae3977a755bd3742.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac83a308c357da220a394e7164da956.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8cfa458c978d903e87459ffd66c2a.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac84b63a2b27ddc08dd7e769593b25c2.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac83a907bc318b96b466179876ad093.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac854f4a9d99e34ec5223b991aa2c887.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac80835da2c2e5f021dd63ed56d0be93.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8a4530c32027b32d52bc899697d8.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8ea6f73a10a31c3d4920c174fe96.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac882dd35d8bf3cee5efeddbe1f399.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8d22b10c9dee47015761898ae75.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8ba82a7ae6d761e1d3582dddbdecdf.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac87681e52e3a709e48cb40ce18bedf.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac827d5424278a62aa6aad18d439a.jpg, http status code: 500, error_msg: [Exception during download during fetching] HTTPSConnectionPool(host='multimedia-commons.s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /data/images/ac8/27d/ac827d5424278a62aa6aad18d439a.jpg (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))
21:54:14 | Bad download - chunk: 0, dest_file: ac83f9f225f695c2a633d44dcbbce55.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac833f723b92e13b6e314d644f76837.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8a241d2041cb26eba548ec1e7d128.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac849ffe6d25ee9bb21787a39c1926.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8287a425804c7c8cc56ca590de1435.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8567fbe08f7d825bf47ea6846693dc.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac85d4417242b9a36c3f45a6a32a138.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8bcdc098f3698665b91ab9146cc3.jpg, http status code: 500, error_msg: [Exception during download during fetching] HTTPSConnectionPool(host='multimedia-commons.s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /data/images/ac8/bcd/ac8bcdc098f3698665b91ab9146cc3.jpg (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))
21:54:14 | Bad download - chunk: 0, dest_file: ac8e6eca5713ee25f631e79d9a3355ac.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac817cd3ccfec3358265dee15ec616af.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac84ecd0fc1f3e17772d8f561a11add.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac822b755268b2a6ce231cc0e1ad588.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac83cdb55a9e6a79ecc879451dacb3.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8d7d1ce0f32d1e7ee4d838c9b1b94.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac80a9f51a66169dda8eec89cda2a289.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8ddea4829c7eba37ac0c81a7ef634.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac83184fd40c475501ef12160eefa1c.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac85a84da55bfb3497f038822344596d.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac86f15b386ea87d3d240fac81f166c.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8dd7f5795743061f480a56aec7c97.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac841340786841ee7e665051fe58d9.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8176a2fb143c79c22488d104ece72.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac89925318fa67f3e018da2547bbe2.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac87838e7846735b27d54a7d5dbc4ee.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8628ffeed36884336ceab1586cb1.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac81db90ac691dfdd275b2e6ec299ca4.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8f9ff369308ac4d3643d3114c6718b.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac8ee3225ea20433642b347f8fa8d81.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac83d37bf87d21f31bcbc3c3f7714f99.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
21:54:14 | Bad download - chunk: 0, dest_file: ac85ef996efd9aed1f91293c1552e9e5.jpg, http status code: 404, error_msg: [Response not OK] Response: <Response [404]>
Downloading: 100%|██████████████████████████████████████████████████████████████| 201858/201858 [01:05<00:00, 3067.15it/s]
21:54:14 | Of 55 items attempted downloading, 55 had errors.

```
Output goes here
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by klshuster** [comment]
This has been addressed in other issues (see e.g. [#3336](https://github.com/facebookresearch/ParlAI/issues/3336)); some images are no longer hosted on YFCC

**Comment by chengguangtang** [comment]
OK, thank you very much.
