### ISSUE TITLE
failed to search 

### ISSUE THREAD

**Issue by rohitmishra94** [facebookresearch/ParlAI#4574]
12:49:57 | Search Queries: ['india qatar relationship']
12:49:57 | sending search request to https://www.google.com/
12:49:57 | Failed to retrieve data from server! Search server returned status 405
12:49:57 | Server search did not produce any results for "india qatar relationship" query. returning an empty set of results for this query.
12:49:57 | URLS:

**Comment by klshuster** [comment]
Please read through other issues for more information on search servers compatible with our setup
