### ISSUE TITLE
Train with gradient accumulation

### ISSUE THREAD

**Issue by gitsand996** [facebookresearch/ParlAI#4583]
Hi, 
I'm approaching the training of some BB models, but I'd like to skip the resource limits in the case of more complex models (ie 400M, 2.7B etc).
I didn't find the possibility of use the gradient accumulation approach within the ParlAI framework and I think that's what's right for me.
 
Do you think it's possible to implement it in the train loop? Do you have any suggestions about it?

Thank you for your amazing work and for your reply

**Comment by klshuster** [comment]
We do have this implemented - if you set `--update-freq n`, it will accumulate gradient for `n` updates

**Comment by gitsand996** [comment]
I found it, thanks a lot.
