### ISSUE TITLE
[T5 FiD model] Parse Error: unrecognized arguments

### ISSUE THREAD

**Issue by entaroee** [facebookresearch/ParlAI#4584]
This is a question that follows from #4563 .

After I trained my own T5 based fid model, I'd like to make a conversation with my model through 'interactive' command, like this.

parlai interactive --model-file zoo:sea/bart_fid_sqse/model --task wizard_of_internet --search-server 0.0.0.0:11111 --search-query-generator-model-file zoo:sea/bart_sq_gen/model --rag-retriever-type search_engine -o gen/blenderbot

and this command works.

but, I'd like to make a conversation with my own T5 based model, which searches for information from 'google.com'.

When I try that command above with my model, it makes this argument error.
=> Parse Error: unrecognized arguments: --search-server https://google.com --search-query-generator-model-file zoo:sea/bart_sq_gen/model

I think this is because when I look into ParlAI/data/models/sea/bart_fid_sqse/model.opt, there are '--search-server' and '--search-query-generator-model-file' option.
But, my .opt don't have that options.
Is this the reason that makes argument error?

and if it is right, how can I insert that option into my .opt file? Can I modify it at train time?
Or is there any other good way to make a conversation with my own model?

**Comment by klshuster** [comment]
you'll need to specify the proper `--model` to have those arguments work, i.e., `--model parlai.agents.fid.fid:SearchQuerySearchEngineFiDAgent`

Note that simply specifying `google.com` won't work for you. You'll need to setup your own search server
