### ISSUE TITLE
Preventing BlenderBot2 to append _POTENTIALLY_UNSAFE__ and _PAUSE__

### ISSUE THREAD

**Issue by Eichhof** [facebookresearch/ParlAI#4587]
Hello

I'm using BlenderBot 2.0 on a Python Flask Server using the following code snippets:

```
from parlai.core.agents import create_agent_from_model_file
opt = {'skip_generation': False, 'include_personas': True, "knowledge_access_method": "memory_only", "doc_chunk_split_mode": "word", "search_server": "http://0.0.0.0:8080"}
blender_agent = create_agent_from_model_file("zoo:blenderbot2/blenderbot2_3B/model", opt)
blender_agent .observe({'text': userText, 'episode_done': False})
response = agent.act()
response = str(response['text'])
```

It works well but sometimes the messages of the bot are appended by _POTENTIALLY_UNSAFE__ and _PAUSE__. Of course I could just remove these occurrences from the strings. Is there a way to prevent the chatbot to append such things?

**Comment by klshuster** [comment]
These are built-in safety measures for which the bot identifies that its response may be unsafe; please see the [Safety section](https://parl.ai/projects/blenderbot2/) of the project page for more information

**Comment by Eichhof** [comment]
Thanks a lot. As far as I understand it, the only possibility is to just check the string if it contains such a substring and if yes, remove it. Is that correct? Is it only Are only POTENTIALLY_UNSAFE_ and PAUSE_ appearing or also others?

**Comment by klshuster** [comment]
The model was only trained to generate `POTENTIALLY_UNSAFE`

**Comment by Eichhof** [comment]
Actually the model is generating / hallucinating also other labels than `_POTENTIALLY_UNSAFE__`.

Is there any other safety classifier available? The built in safety classifier of blenderbot2_3B does not work that well.

**Comment by Eichhof** [comment]
Any thoughts about this?

**Comment by Eichhof** [comment]
I'm using now the following: 

```
from parlai.utils.safety import OffensiveStringMatcher, OffensiveLanguageClassifier
offensive_classifier = OffensiveLanguageClassifier()
text_is_unsafe, proba = offensive_classifier.contains_offensive_language(text)
```

What is the default proba threshold used?

Is this the best classifier to detect inappropriate answers or would you recommend another one?

**Comment by klshuster** [comment]
0.5 is generally a good idea. I would then instantiate with the [BAD model](https://parl.ai/projects/safety_recipes/): `OffensiveLanguageClassifier(custom_model_file='zoo:bot_adversarial_dialogue/multi_turn/model')`

**Comment by Eichhof** [comment]
I've tried the BAD model with a proba threshold of 0.5 but it is classifying way too many chatbot responses as inappropriate.

Can I use the BAD model to classify just one chatbot response (e.g. one sentence)? Or should it be used in a different way?

**Comment by klshuster** [comment]
the threshold you pick is entirely up to you. and yes, it can be used with just a single utterance
