### ISSUE TITLE
Randomizing chatbot answers

### ISSUE THREAD

**Issue by Eichhof** [facebookresearch/ParlAI#4588]
Hello

I'm using BlenderBot 2.0 on a Python Flask Server using the following code snippets:

```
from parlai.core.agents import create_agent_from_model_file
opt = {'skip_generation': False, 'include_personas': True, "knowledge_access_method": "memory_only", "doc_chunk_split_mode": "word", "search_server": "http://0.0.0.0:8080"}
blender_agent = create_agent_from_model_file("zoo:blenderbot2/blenderbot2_3B/model", opt)
blender_agent .observe({'text': userText, 'episode_done': False})
response = agent.act()
response = str(response['text'])
```

It works well but the bot always provides the same response for the same input. For example, if I start a new conversation with "Hello", the bot always responds with "Is it me you're looking for? _POTENTIALLY_UNSAFE__".

Is it possible to randomize the chatbot answers a bit (but in a way that they still make sense)?

**Comment by mojtaba-komeili** [comment]
You can switch to other inference methods that are more randomized, such as `topk` or `nucleus`. For example `--inference nucleus`

**Comment by Eichhof** [comment]
I will test it, thank you very much. Would you use topk and nucleus with default parameters?

**Comment by mojtaba-komeili** [comment]
Well, the default parameters are alright. But you may better try tweaking them to see if you could get better results.
