### ISSUE TITLE
SeeKeR Table 2 Repro

### ISSUE THREAD

**Issue by sshleifer** [facebookresearch/ParlAI#4591]
@klshuster @mojtaba-komeili 

![image](https://user-images.githubusercontent.com/6045025/173619045-c3045c3a-f132-4763-b5cd-1c7e052c6fda.png)

Command Guesses
### Row 2
```
eval_wizint () {
    parlai eval_model --task wizard_of_internet --search-server 0.0.0.0:8080 "$@" 
}
eval_wizint --mf zoo:sea/bart_fid_sqse/model  --search-query-generator-model-file zoo:sea/bart_sq_gen/model --ne 10
```
Yields:
```
16:05:10 | Report for wizard_of_internet:
    clen  ctpb  ctps  ctrunc  ctrunclen  exps  exs  gpu_mem  llen  loss    lr  ltpb  ltps  ltrunc  ltrunclen   ppl  token_acc  token_em  tpb   tps
    76.5  78.5 11.56       0          0 .1473   10   .02713  14.2 2.927 1e-10  14.2 2.091       0          0 18.67      .4085         0 92.7 13.65
```

    
### Row 7 
```
eval_wizint -mf zoo:seeker/seeker_lm_xl/model -o gen/seeker_lm --ne 10
```

Yields:
```
16:19:33 | Report for wizard_of_internet:
    accuracy    bleu-4  clen  ctrunc  ctrunclen  exs    f1  gen_n_toks  knowledge_f1_docs  knowledge_f1_max_docs  knowledge_f1_max_retrieved_docs  \
           0 1.897e-08 64.42       0          0   12 .1515       22.92             .02494                      0                            .0597
    knowledge_f1_max_retrieved_sentences  knowledge_f1_max_sentences  knowledge_f1_sentences  llen  loss  ltrunc  ltrunclen   ppl  token_acc  token_em
                                   .2803                           0                   .1466 16.25 2.644       0          0 14.07      .5026         0
```

### Questions
1) The TPS seems low for sea. I assume these are just running on 1 GPU. Are there clargs to use multiple GPUs/configure data parallelism and/or model parallelism during evaluation?
1b) Why TPS reported for  Row 2 cmd but not Row 7 cmd?
2) Is a Mojeek search server implem released? I just took the [first link on google](https://github.com/JulesGM/ParlAI_SearchEngine) and then modified to use Bing (I couldn't find anything in ParlAI with `git grep ojeek`). If not, I'd love to know whether it's in the roadmap/pointers to other repos.  [My Search Server Code](https://gist.github.com/sshleifer/2f530f9ab2375897130881e669fa7420)

Thanks and hope all is well!

**Comment by klshuster** [comment]
For 1 you could also use `--model-parallel`, however we have found that model parallel with generation is actually slower than just using a single GPU

**Comment by sshleifer** [comment]
Which models can I use data-parallel for

```
eval_wizint -mf zoo:seeker/seeker_lm_dialogue_3B/model -o gen/seeker_dialogue --ne 10 --data-parallel
eval_wizint -mf zoo:seeker/seeker_lm_xl/model -o gen/seeker_lm --ne 10 --data-parallel
```
both fail with `Parse Error: unrecognized arguments: --data-parallel`
(same with `--data-parallel 8`)

**Comment by mojtaba-komeili** [comment]
Have you checked out the [distributed eval](https://github.com/facebookresearch/ParlAI/blob/main/parlai/scripts/distributed_eval.py)?
