### ISSUE TITLE
AttributeError: 'ParlaiParser' object has no attribute 'add_pytorch_datateacher_args'

### ISSUE THREAD

**Issue by Deep1994** [facebookresearch/ParlAI#4592]
Hi, I use the ParlAi like:

def setup_args(parser=None):
    if parser is None:
        parser = ParlaiParser(True, True, 'Display data from a task')
    parser.add_pytorch_datateacher_args()
    # Get command line arguments
    parser.add_argument('-ne', '--num_examples', type=int, default=10)
    parser.add_argument('-mdl', '--max_display_len', type=int, default=1000)
    parser.add_argument('--display_ignore_fields', type=str, default='agent_reply')
    parser.set_defaults(datatype='train:stream')
    return parser
parser = setup_args()

But I got  an error `AttributeError: 'ParlaiParser' object has no attribute 'add_pytorch_datateacher_args'`, I don't find any change log from the history about parlai.core.params.py, why dose this happen? Thanks!

**Comment by klshuster** [comment]
That function hasn't existed for a very long time. I would simply delete that line
