### ISSUE TITLE
Reoccurring error while finetuning blenderbot

### ISSUE THREAD

**Issue by urvi-awasthi** [facebookresearch/ParlAI#4595]
I'm finetuning blenderbot with the following script, I've used this script before but it's not thrown an error like this.
`parlai train_model -t fromfile:parlaiformat --fromfile_datapath /content/training_data.txt -m transformer/generator --multitask-weights 1,3,3,3 --init-model zoo:tutorial_transformer_generator/model --dict-file zoo:tutorial_transformer_generator/model.dict --embedding-size 512 --n-layers 8 --ffn-size 2048 --dropout 0.1 --n-heads 16 --learn-positional-embeddings True --n-positions 512 --variant xlm --activation gelu --skip-generation false --fp16 True --text-truncate 512 --label-truncate 128 --dict-tokenizer bpe --dict-lower True -lr 1e-06 --optimizer adamax --lr-scheduler reduceonplateau --gradient-clip 0.1 -veps 1.50 --betas 0.9,0.999 --update-freq 1 --attention-dropout 0.0 --relu-dropout 0.0 --skip-generation True -vp 15 -stim 60 -vme 20000 -bs 1 -vmt ppl -vmm min --save-after-valid True --model-file /content/model
`
This is the error that is occurring:
15:41:28 |     override: "{'task': 'fromfile:parlaiformat', 'fromfile_datapath': '/content/training_data.txt', 'model': 'transformer/generator', 'multitask_weights': (1.0, 3.0, 3.0, 3.0), 'init_model': 'zoo:tutorial_transformer_generator/model', 'dict_file': '/usr/local/lib/python3.7/dist-packages/data/models/tutorial_transformer_generator/model.dict', 'embedding_size': 512, 'n_layers': 8, 'ffn_size': 2048, 'dropout': 0.1, 'n_heads': 16, 'learn_positional_embeddings': True, 'n_positions': 512, 'variant': 'xlm', 'activation': 'gelu', 'skip_generation': True, 'fp16': True, 'text_truncate': 512, 'label_truncate': 128, 'dict_tokenizer': 'bpe', 'dict_lower': True, 'learningrate': 1e-06, 'optimizer': 'adamax', 'lr_scheduler': 'reduceonplateau', 'gradient_clip': 0.1, 'validation_every_n_epochs': 1.5, 'betas': (0.9, 0.999), 'update_freq': 1, 'attention_dropout': 0.0, 'relu_dropout': 0.0, 'validation_patience': 15, 'save_every_n_secs': 60.0, 'validation_max_exs': 20000, 'batchsize': 1, 'validation_metric': 'ppl', 'validation_metric_mode': 'min', 'save_after_valid': True, 'model_file': '/content/model'}"
15:41:28 |     parlai_home: /usr/local/lib/python3.7/dist-packages
15:41:28 |     person_tokens: False
15:41:28 |     rank_candidates: False
15:41:28 |     relu_dropout: 0.0
15:41:28 |     save_after_valid: True
15:41:28 |     save_every_n_secs: 60.0
15:41:28 |     save_format: conversations
15:41:28 |     share_word_embeddings: True
15:41:28 |     short_final_eval: False
15:41:28 |     skip_generation: True
15:41:28 |     special_tok_lst: None
15:41:28 |     split_lines: False
15:41:28 |     starttime: Jun15_15-41
15:41:28 |     task: fromfile:parlaiformat
15:41:28 |     temperature: 1.0
15:41:28 |     tensorboard_log: False
15:41:28 |     tensorboard_logdir: None
15:41:28 |     text_truncate: 512
15:41:28 |     topk: 10
15:41:28 |     topp: 0.9
15:41:28 |     truncate: -1
15:41:28 |     update_freq: 1
15:41:28 |     use_reply: label
15:41:28 |     validation_cutoff: 1.0
15:41:28 |     validation_every_n_epochs: 1.5
15:41:28 |     validation_every_n_secs: -1
15:41:28 |     validation_every_n_steps: -1
15:41:28 |     validation_max_exs: 20000
15:41:28 |     validation_metric: ppl
15:41:28 |     validation_metric_mode: min
15:41:28 |     validation_patience: 15
15:41:28 |     validation_share_agent: False
15:41:28 |     variant: xlm
15:41:28 |     verbose: False
15:41:28 |     wandb_entity: None
15:41:28 |     wandb_log: False
15:41:28 |     wandb_name: None
15:41:28 |     wandb_project: None
15:41:28 |     warmup_rate: 0.0001
15:41:28 |     warmup_updates: -1
15:41:28 |     weight_decay: None
15:41:28 |     world_logs: 
15:41:28 | Current internal commit: 7660197631c06ee41c0ce25c5de37a74b11ecb77
15:41:28 | Current fb commit: 7660197631c06ee41c0ce25c5de37a74b11ecb77
15:41:28 | creating task(s): fromfile:parlaiformat
15:41:28 | Loading ParlAI text data: /content/training_data.txt
15:41:28 | training...
Traceback (most recent call last):
  File "/usr/local/bin/parlai", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/usr/local/lib/python3.7/dist-packages/parlai/scripts/train_model.py", line 1048, in run
    return self.train_loop.train()
  File "/usr/local/lib/python3.7/dist-packages/parlai/scripts/train_model.py", line 1000, in train
    for _train_log in self.train_steps():
  File "/usr/local/lib/python3.7/dist-packages/parlai/scripts/train_model.py", line 907, in train_steps
    world.parley()
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/worlds.py", line 370, in parley
    acts[1] = agents[1].act()
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/torch_agent.py", line 2147, in act
    response = self.batch_act([self.observation])[0]
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/torch_agent.py", line 2238, in batch_act
    output = self.train_step(batch)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/torch_generator_agent.py", line 735, in train_step
    loss = self.compute_loss(batch)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/torch_generator_agent.py", line 694, in compute_loss
    model_output = self.model(*self._model_input(batch), ys=batch.label_vec)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/parlai/core/torch_generator_agent.py", line 310, in forward
    encoder_states = prev_enc if prev_enc is not None else self.encoder(*xs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/parlai/agents/transformer/modules/encoder.py", line 360, in forward
    tensor, mask = self.forward_embedding(input, positions, segments)
  File "/usr/local/lib/python3.7/dist-packages/parlai/agents/transformer/modules/encoder.py", line 266, in forward_embedding
    positions = (mask.cumsum(dim=1, dtype=torch.int64) - 1).clamp_(min=0)
AttributeError: 'bool' object has no attribute 'cumsum'

**Comment by urvi-awasthi** [comment]
It's 1.11.0. Should I change it?

**Comment by klshuster** [comment]
I don't think that's necessary. 

My next question is, are you sure your data is formatted correctly for `fromfile`? I.e., does the data look correct when you run `parlai display_data -t fromfile:parlaiformat --fromfile_datapath /content/training_data.txt`?

I have run your exact command with a different dataset (convai2) and cannot reproduce your error
