### ISSUE TITLE
Beyond Goldfish Memory: how to freeze only part of postitional encodings?

### ISSUE THREAD

**Issue by takiholadi** [facebookresearch/ParlAI#4598]
Paper [Beyond Goldfish Memory](https://arxiv.org/pdf/2107.07567.pdf) says at `Encoder Truncation` section :

```
As BST 2.7B has a truncation of 128 tokens in the encoder, we consider extending this to a larger input.
To do this, we extend its learnable positional encodings from 128 to 256, 512 or 1024 tokens,
and then train these extra parameters at the same time as we fine-tune the whole network on the downstream task.
We add new positional embeddings to be trained such that the existing ones (the first 128) do not change from before.
```

Could you point to the relative code of how to freeze only part of positional embeddings?

I am going to reproduce same at huggingface, and looks like pytorch doesn't allow such a partial freezing. (But easy to increase size and copy part of already trained.)

**Comment by klshuster** [comment]
[I believe the code for that is here](https://github.com/facebookresearch/ParlAI/blob/a3d2d1dae8c17306c1a11de41131836585cc3526/projects/msc/agents/long_tga.py#L53)

note that BST 2.7B uses non-learned embeddings, so extending is just a matter of [creating more sinusoidal embs](https://github.com/facebookresearch/ParlAI/blob/a3d2d1dae8c17306c1a11de41131836585cc3526/parlai/agents/transformer/modules/functions.py#L17)

**Comment by takiholadi** [comment]
Thank you for pointing to `ShiftInvariantEncoder` code!

HuggingFace BlenderBot 1.0 implementation uses by default [learnable positional embeddings](https://github.com/huggingface/transformers/blob/f44e2c2b6f319514d8a80eccc2dd4c480697cc13/src/transformers/models/blenderbot/modeling_blenderbot.py#L111), so do I.

@klshuster In case of BlenderBot with learnable positions and going to use FiD approach for extranal knowledge, it looks like there is no need to change encoder, right? And how should one change decoder, since its shape of input tensor for decoder will become larger?

**Comment by klshuster** [comment]
> @klshuster In case of BlenderBot with learnable positions and going to use FiD approach for external knowledge, it looks like there is no need to change encoder (since independently encoded), right? 

Correct, there shouldn't be a need to change the encoder

> And how should one change decoder, since its shape of input tensor for decoder will become larger (concated outputs from encoder)?

No need to change decoder, either. The decoder can accept arbitrary number of encoded outputs from the encoder; note that FiD is a good example of this, as indeed it accepts concatenated outputs from the encoder which total much higher than the decoder positional embeddings
