### ISSUE TITLE
Error on running the readme instructions

### ISSUE THREAD

**Issue by puneetjindal** [facebookresearch/ParlAI#46]
I cloned the repository and tried to run examples
```
git clone https://github.com/facebookresearch/ParlAI.git
cd ParlAI/
python setup.py install
python examples/display_data.py -t babi:task1k:1
```

### > [task:babi:task1k:1]
> [download_path:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parlai-0.1.0-py2.7.egg/downloads/]
> [datatype:train]
> [numthreads:1]
> [batchsize:1]
> [datapath:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parlai-0.1.0-py2.7.egg/data/]
> [num_examples:10]
> Traceback (most recent call last):
>   File "examples/display_data.py", line 42, in <module>
>     main()
>   File "examples/display_data.py", line 29, in main
>     agent = RepeatLabelAgent(opt)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/parlai-0.1.0-py2.7.egg/parlai/agents/repeat_label/agents.py", line 27, in __init__
>     super().__init__(opt)
> TypeError: super() takes at least 1 argument (0 given)

**Comment by alexholdenmiller** [comment]
Thanks for checking out our repo Puneet! We don't support Python 2 yet.
