### ISSUE TITLE
Parameters for Inference Methods of BlenderBot2

### ISSUE THREAD

**Issue by Eichhof** [facebookresearch/ParlAI#4604]
Hello everybody

I'm using BlenderBot 2 with the following parameters:

```
from parlai.core.agents import create_agent_from_model_file
opt = {'skip_generation': False, 'include_personas': True, "knowledge_access_method": "memory_only", "doc_chunk_split_mode": "word", "search_server": "http://0.0.0.0:8080", "inference": "nucleus"}
blender_agent = create_agent_from_model_file("zoo:blenderbot2/blenderbot2_3B/model", opt)
```

With the default setting for `inference `it works well but is very deterministic. I now also tried `nucleus `and `topk`. The conversation is now less deterministic but sometimes the answer of BlenderBot does not make sense or is just nonsense.

Are there any recommended parameters to use for the different inference methods to make the conversations more consistent and meaningful?

**Comment by klshuster** [comment]
Optimal decoding is an open problem in long-form generation. There are several proposed approaches in the literature; we stick with beam search with minimum generation length of 20 and beam/context blocking, as that has shown to be effective compared to other methods (see [original BB1 paper](https://arxiv.org/abs/2004.13637))

**Comment by Eichhof** [comment]
Thank you very much for your answer. I think this would translate to the following options:

`opt = {'skip_generation': False, 'include_personas': True, "knowledge_access_method": "memory_only", "doc_chunk_split_mode": "word", "search_server": "http://0.0.0.0:8080", "inference": "beam", "beam-min-length": 20}`

I don't know which option corresponds to beam/context blocking.

What values would you propose for `beam-size`, `beam-context-block-ngram`, `beam-block-ngram`, `beam-block-full-context`, `beam-length-penalty`, `beam-delay`, `compute-tokenized-bleu` and `temperature`? If I missed some important parameters, I would be happy if you could add them.

**Comment by klshuster** [comment]
We generally follow the [options specified here](https://github.com/facebookresearch/ParlAI/blob/main/parlai/opt_presets/gen/blenderbot.opt). Specifically:

```
--beam-size 10 \
--beam-context-block-ngram 3 \
--beam-block-ngram 3 \
--beam-block-full-context True \
```

Everything else you can leave as default

**Comment by klshuster** [comment]
either is ok. setting to `True` will block on all context even if it doesnt fit in the model's context truncation window (128 tokens for BB2 3B)

**Comment by Eichhof** [comment]
What does it mean when it blocks on all context?

**Comment by klshuster** [comment]
Suppose you're in a very long conversation, where there are e.g. 1000 tokens of context. With `--beam-block-full-context False`, the model will only perform beam-blocking on the 128 tokens that fit into the context window of BB2. With `--beam-block-full-context True`, the model will perform beam-blocking on all 1000 tokens of context, even though it cannot actually process all of the tokens in a forward pass.

**Comment by Eichhof** [comment]
Thanks a lot for the explanation. That makes it much more clear.

With the parameters that you proposed the chatbot works well but is pretty deterministic. Is there a possibility to introduce a bit more randomness with beam inference?

**Comment by Eichhof** [comment]
Any thought about how to make it more random? Is there some sort of temperature parameter?

**Comment by klshuster** [comment]
Using nucleus sampling (`--inference nucleus`) with a high p value (`--topp 0.9`) will increase randomness. Same with `--inference topk` with high `--topk`. You can indeed play around with `--temperature` as well

**Comment by klshuster** [comment]
closing for now, please reopen if there are further questions
