### ISSUE TITLE
Seeker Finetuning with Custom Dialogue Dataset

### ISSUE THREAD

**Issue by stanleyshly** [facebookresearch/ParlAI#4617]
I've been trying to attempting to finetune the Seeker model with this command:
```
python -m parlai.scripts.multiprocessing_train \
--task projects.seeker.tasks.knowledge,projects.seeker.tasks.dialogue,projects.seeker.tasks.search_query \
--multitask-weights 2,2,1 -bs 1 -vstep 1000 -vmt ppl -vp 5 -vmm min -vme 100000 -lstep 50 \
--init-opt arch/r2c2_base_3B --init-model zoo:seeker/r2c2_blenderbot_3B/model \
--model projects.seeker.agents.seeker:ComboFidGoldDocumentAgent --n-docs 5 \
--text-truncate 1000 --label-truncate 128 --truncate 1000 \
--fp16 True -lr 1e-06 --lr-scheduler reduceonplateau --optimizer adamw --save-after-valid True \
--warmup-updates 100 --update-freq 1 --gradient-clip 1.0 --skip-generation True --dropout 0.1 \
--attention-dropout 0.0 --load-from-checkpoint true --ddp-backend zero2 \
--checkpoint-activations true--model-file /tmp/my_seeker_dialogue_model
```
However, instead of finetuning all of the steps, I merely want to change the conversational style, I figured I would only need to finetune the dialogue section of Seeker. If I delete all of the tasks, and replace it with a conversational dataset like convai2, would this work out of the box?

**Comment by klshuster** [comment]
yes - you'll want to also specify `--mutators skip_retrieval` to make sure that the model does not attempt retrieval when finetuning the dialogue portion.

**Comment by stanleyshly** [comment]
Thanks for the help! Closing now.
