### ISSUE TITLE
Self chat with search server

### ISSUE THREAD

**Issue by louis030195** [facebookresearch/ParlAI#4618]
Hi, I'm trying to run a self chat with Seeker and a search server:

`parlai self_chat --model-file zoo:seeker/seeker_dialogue_400M/model --task empathetic_dialogues --num-self-chats 200 --display-examples True --seed_messages_from_file="./seeds.txt" --outfile="./out" --rag-retriever-type search_engine --search_server http://localhost:8083`

```
18:41:11 | Current ParlAI commit: 6215bcb3dfdf76f3de79d1f9b124c239722dbf47
18:41:11 | Current internal commit: a84d28c4f9e9a56ddf9f8c3b124b61ac5ae991f5
18:41:11 | Current fb commit: a84d28c4f9e9a56ddf9f8c3b124b61ac5ae991f5
18:41:11 | creating task(s): self_chat
```

But I receive

>Parse Error: unrecognized arguments: --search-server http://localhost:8083

Is it possible to use self chat with search server?

Thanks a lot!

**Comment by klshuster** [comment]
you'll need to also specify `--init-opt gen/seeker_dialogue` so that the appropriate arguments are loaded

**Comment by louis030195** [comment]
> --init-opt gen/seeker_dialogue

Oops. Always forget this one, sorry.
