### ISSUE TITLE
How to Limit Number of Searchs that Seeker Makes

### ISSUE THREAD

**Issue by stanleyshly** [facebookresearch/ParlAI#4620]
Right now, I'm running the interactive version of Seeker with `parlai i -mf zoo:seeker/seeker_dialogue_3B/model -o gen/seeker_dialogue --search-server <search_server>`. I notice that when searching for knowledge, it makes a request for 5 webpages to the search server. How do I change the amount of webpages that are searched from the default value?

**Comment by klshuster** [comment]
setting `--krm-n-docs NUM` should change the value

**Comment by stanleyshly** [comment]
Thank you for the information!
