### ISSUE TITLE
[BlenderBot1.0] Retrain embedding weights from scratch

### ISSUE THREAD

**Issue by gitsand996** [facebookresearch/ParlAI#4622]
Hi, 
I would to change the vocabulary for my own BlenderBot transformer generator and I am wondering if it's possible to only retrain the embedding layers from scratch, leaving other layers frozen, instead of full retrain.

Can you help me to setting up the training? I collected a large amount of data and trained my own tokenizer. Now I'm going to build the dict in order to train a 90M transformer using ParlAI. What's next? I think I have to create a new task with an agent and a teacher and start the training without init_model. 

Is there a way to freeze all transformer layers and to train the embedding layer only?

Thank you in advance :D

**Comment by klshuster** [comment]
This depends on your new dictionary. If it is the same number of words as the original dictionary, there are only a few steps you need to do:

1. Still set `--init-model` as before
2. Wrap [this portion of the `encoder.forward`](https://github.com/facebookresearch/ParlAI/blob/a3361c33c08125f196bb16dec0f7e2bf30c56f15/parlai/agents/transformer/modules/encoder.py#L357-L373) and [this portion of the `decoder.forward`](https://github.com/facebookresearch/ParlAI/blob/a3361c33c08125f196bb16dec0f7e2bf30c56f15/parlai/agents/transformer/modules/decoder.py#L662-L671) in a `with torch.no_grad():` context manager.

This will train your embeddings only.

If your new dictionary has a different amount of words, and you still want to load the layer weights from the original BB1 model, you'll need to implement/override [`_resize_token_embeddings`](https://github.com/facebookresearch/ParlAI/blob/a3361c33c08125f196bb16dec0f7e2bf30c56f15/parlai/core/torch_agent.py#L872-L883) to resize the embeddings accordingly. You can see [an example here](https://github.com/facebookresearch/ParlAI/blob/a3361c33c08125f196bb16dec0f7e2bf30c56f15/parlai/agents/transformer/decoder.py#L73)

**Comment by gitsand996** [comment]
Thank you, @klshuster ! What task should I use for this training? I suppose the embedding layers should be trained for language modeling. Is it right?

**Comment by klshuster** [comment]
whatever downstream task you desire - what is your purpose for re-training just the embeddings?

**Comment by gitsand996** [comment]
I would to use the original Blenderbot weights but for another language. My desire is to fine-tune it on a conversational dataset in the same format of Blended Skill Talk. I had pretty good results with a gpt2 model with retrained embeddings on the new target language so I would to repeat the experiment on Blenderbot

**Comment by klshuster** [comment]
I see. Yes, doing a language modeling task in another language might help then

**Comment by gitsand996** [comment]
@klshuster Hi, how can I start the training setting the new tokenizer I trained for the new language?
