### ISSUE TITLE
Unit testing is failing for the script "eval_model.py" in original unchanged code base

### ISSUE THREAD

**Issue by skinan** [facebookresearch/ParlAI#4626]
2 unit tests are failing for "eval_model.py" script when I run this command  `pytest tests/test_eval_model.py` without making any changes to the original code base. I have attached the screenshot of the failing tests here for reference. I am going to make a pull request with some contribution to ParlAI and so I wanted to ensure that these failing tests do not create an obstacle for my pull request to get accepted in the future.

**Screenshots of failed tests:**
![Screenshot from 2022-06-22 22-10-00](https://user-images.githubusercontent.com/46783803/175330844-11845d4e-f7ff-4691-9491-0d0cc7ccc7b5.png)

![Screenshot from 2022-06-22 22-10-16](https://user-images.githubusercontent.com/46783803/175330877-27789ac7-4624-4a9b-bb95-ed7c91864ba7.png)

**Comment by klshuster** [comment]
you may not have `rouge` installed; try `pip install rouge`

**Comment by skinan** [comment]
I have installed rouge but it's still the same. I have attached a detailed log file for this test.

[log_parl_ai_eval_model_test.txt](https://github.com/facebookresearch/ParlAI/files/8984533/log_parl_ai_eval_model_test.txt)

**Comment by skinan** [comment]
@klshuster

**Comment by stephenroller** [comment]
it's actually `pip3 install py-rouge` 🙈
