### ISSUE TITLE
Inapropriate responses from BlenderBot 2.0 (how to handle POTENTIALLY_UNSAFE?)

### ISSUE THREAD

**Issue by Eichhof** [facebookresearch/ParlAI#4628]
Hello

I'm running BlenderBot 2.0 (blenderbot2_3B) using beam search following the [options specified here](https://github.com/facebookresearch/ParlAI/blob/main/parlai/opt_presets/gen/blenderbot.opt).

The main problem is that the answers are sometimes very inappropriate. Especially when asking for a joke, BlenderBot always gets very racist. I think this could be captured with the flag `POTENTIALLY_UNSAFE`. Or is there another workaround?

If I capture a response flagged as `POTENTIALLY_UNSAFE `, what is the best way to handle this sentence in terms of continuing the conversation? I won't display the sentence to the user but how should then the conversation be continued?

**Comment by mojtaba-komeili** [comment]
Yeah, that is using bot's baked-in safety. But as expected, it is not perfect. I refer you to its [model card](https://github.com/facebookresearch/ParlAI/blob/main/parlai/zoo/blenderbot2/model_card.md) for safety evaluations.

**Comment by Eichhof** [comment]
Thank you for your answer. If a sentence is flagged as inappropriate, how should the sentence be handled? Not displaying it to the user won't work because it would break the conversation. Displaying the sentence to the user and flagging it as inappropriate is also not a good solution.

**Comment by mojtaba-komeili** [comment]
I'd say that UX research question and out of scope of our work here.
