### ISSUE TITLE
Persona and knowledge base of a particular (famous) person

### ISSUE THREAD

**Issue by Eichhof** [facebookresearch/ParlAI#4630]
Hello everybody

I'm using BlenderBot 2.0 (blenderbot2_3B) and it works fine most of the time. I think I can kickstart a conversation by using prompt engineering and just feeding some sentences to the chatbot (similar to providing a specific persona). Now, I would like to provide BlenderBot persona and knowledge of a particular person, for example, Marie Curie. Many interviews and other information about Marie Curie are available on the internet. But I think prompt engineering does not work to add this additional knowledge and to make BlenderBot believe that it is Marie Curie.

Is there any possibility to add a knowledge base about a particular person (other than web search) and to add a persona of a specific person?

**Comment by mojtaba-komeili** [comment]
Adding persona line might help to some degree. But you should not have very high expectations that it perfectly plays the role. Maybe fine-tuning on the data available from that character helps too. But then you need to fine tune a model for each character you want it to play. You also need to turn all those data into datasets and run the trainings.

**Comment by klshuster** [comment]
> Is there any possibility to add a knowledge base about a particular person

If you setup your search server to be some sort of sparse retrieval index you can achieve this (e.g., via Lucene). You would then just specify a different search server address

**Comment by Eichhof** [comment]
Thank you for your input.

What exactly do you mean by sparse retrieval index?

Could using a search server with Aquila Custom Search Engine (with only webpages related to the particular person) be what you meant?

**Comment by klshuster** [comment]
Sure, that might work. I simply meant any index not requiring dense retrieval. Or really any sort of search index you'd like

**Comment by Beidaidai0713** [comment]
> Hello everybody
> 
> I'm using BlenderBot 2.0 (blenderbot2_3B) and it works fine most of the time. I think I can kickstart a conversation by using prompt engineering and just feeding some sentences to the chatbot (similar to providing a specific persona). Now, I would like to provide BlenderBot persona and knowledge of a particular person, for example, Marie Curie. Many interviews and other information about Marie Curie are available on the internet. But I think prompt engineering does not work to add this additional knowledge and to make BlenderBot believe that it is Marie Curie.
> 
> Is there any possibility to add a knowledge base about a particular person (other than web search) and to add a persona of a specific person? 

Is it possible to provide a specific persona to the chatbot by using command lines? I saw in the source code that the persona are randomly chosen from the persona text file automatically downloaded from parlai. Is it okay to share your code about assigning a specific persona to the chat bot?

**Comment by klshuster** [comment]
If you specify `--task convai2` when using `parlai interactive`, it'll load up an interactive world [defined in this file](https://github.com/facebookresearch/ParlAI/blob/main/parlai/tasks/convai2/worlds.py#L57). Notice how the [initial "contexts"](https://github.com/facebookresearch/ParlAI/blob/75a58707fd35c6e75d143b051e9455cb01862f80/parlai/tasks/convai2/worlds.py#L76-L77) are a set of personas that can be randomly assigned to both bot and human. You can modify this world to specify your own persona text files.

**Comment by klshuster** [comment]
closing for now as this seems resolved, please reopen if you have further questions
