### ISSUE TITLE
Circle CI unit test fails on "long_gpu_tests" due to a disk space full error

### ISSUE THREAD

**Issue by skinan** [facebookresearch/ParlAI#4638]
Attached full test log that fails.
[pari_ai_long_test_gpu_error.txt](https://github.com/facebookresearch/ParlAI/files/9011035/pari_ai_long_test_gpu_error.txt)

**Comment by stephenroller** [comment]
Ouch.

**Comment by skinan** [comment]
@stephenroller Would it cause any problem for my future pull request to get accepted?

**Comment by skinan** [comment]
Hello @stephenroller , it gets solved with "parallelism: 32". My test successfully ran after this.
