### ISSUE TITLE
Blenderbot2 finetuned on SaFeRDialogues

### ISSUE THREAD

**Issue by Jsiewierski11** [facebookresearch/ParlAI#4640]
I was wondering if you guys had fine-tuned the Blenderbot2 model on the SaFeRDialogues dataset yet. I'm currently finetuning the 400M Blenderbot2 model on the SaFeRDialogues and would be happy to make a pull request once training is completed.

**Comment by klshuster** [comment]
We have not; that sounds useful!

**Comment by Jsiewierski11** [comment]
What would be the best way for me to make a pull request so it could be added to your model zoo that would allow people to download the model?

**Comment by klshuster** [comment]
You can follow the general format of other zoo models:

1. Add an entry to [`model_list.py`](https://github.com/facebookresearch/ParlAI/blob/main/parlai/zoo/model_list.py)
2. Add a build script; see [this for an example](https://github.com/facebookresearch/ParlAI/blob/main/parlai/zoo/blenderbot2/blenderbot2_400M.py)
3. (Highly encouraged) Add a test to our `nightly/gpu` tests to ensure that the model can be downloaded appropriately and used in ParlAI. [Here's an example](https://github.com/facebookresearch/ParlAI/blob/03ca319f440cdffafe7068c0e56c49f568d6de83/tests/nightly/gpu/test_bb2.py#L304-L332)


Let me know if you have any other questions!
