### ISSUE TITLE
Simple Question about BB1

### ISSUE THREAD

**Issue by daje0601** [facebookresearch/ParlAI#4660]
I'm making this model `zoo:pretrained_transformers/poly_model_huge_reddit/model` and I am checking the necessary data.

I'm curious to know if you've trained using all the data in this [link](https://files.pushshift.io/) [https://files.pushshift.io/reddit/authors/].

**Comment by stephenroller** [comment]
We trained on the comments files through 2019

**Comment by daje0601** [comment]
Thank you so much.
The average for each year is around 8-13 GB. You've trained an incredible(huge) amount!
