### ISSUE TITLE
Is the data format exactly same between `fb:google_sgd` and `google_sgd_simulation_splits` in tod_simulator?

### ISSUE THREAD

**Issue by jianguoz** [facebookresearch/ParlAI#4665]
Use this to open other questions or issues, and provide context here.

@moyapchen Thanks for providing the tod_simulator code! I display the data of `google_sgd`,  i.e., GoogleSGD_SystemTeacher, and I found that it's format is the same with `google_sgd_simulation_splits (with both in domains and out of domains)`. 

Since I am trying to recover `fb:google_sgd`, I want to confirm that is the data format also the same between `google_sgd_simulation_splits` and `fb:google_sgd`? If so I can directly use `google_sgd_simulation_splits` or `google_sgd`.

Thanks very much:).

**Comment by klshuster** [comment]
cc @moyapchen maybe?
