### ISSUE TITLE
[BlenderBot 1.0] What's version of the BlenderBot-3B open-sourced in HuggingFace transformers?

### ISSUE THREAD

**Issue by heya5** [facebookresearch/ParlAI#4672]
Is the version of the model here https://huggingface.co/facebook/blenderbot-3B  **fine-tuned in BST dataset?** Or just pre-trained in push.io reddit?
And how can I same response as ParlAI in huggingface transformers?
Thanks for your open source model!

**Comment by klshuster** [comment]
Yes, the model there is the fully-trained BlenderBot model.

You should be able to get the same responses by installing parlai and running the following:

```
parlai interactive -mf zoo:blender/blender_3B/model
```
