### ISSUE TITLE
ValueError depedning on the size of Blenderbot2

### ISSUE THREAD

**Issue by robinsongh381** [facebookresearch/ParlAI#4683]
When I evaluate the blenderbot2_3B model with following command, everything works fine

```bash
parlai eval_model -mf zoo:blenderbot2/blenderbot2_3B/model -t msc -v --knowledge-access-method none --rag_retriever_type dpr --log_every_n_secs 60 --batchsize 32
```

However, chaing the model size to 400M and running the command 

```bash
parlai eval_model -mf zoo:blenderbot2/blenderbot2_400M/model -t msc -v --knowledge-access-method none --rag_retriever_type dpr --log_every_n_secs 60 --batchsize 40
```

gives `ValueError: Expected input batch_size (840) to match target batch_size (800)`

![image](https://user-images.githubusercontent.com/42966248/180832507-afe58788-2718-4e3e-9e04-b6a77d0fd288.png)

I'm running on the recent ParlAI version.

**Comment by klshuster** [comment]
is there a reason you switched to `--batchsize 40`?

**Comment by robinsongh381** [comment]
no. I aslo tried --batchsize 32 and faced the same error.

```bash
parlai eval_model -mf zoo:blenderbot2/blenderbot2_3B/model -t msc -v --knowledge-access-method none --rag_retriever_type dpr --log_every_n_secs 60 --batchsize 32
```
![image](https://user-images.githubusercontent.com/42966248/180836316-c2af4cd4-89b8-40ca-90e9-e9247235c48f.png)

This is quite bizzare !

Do you have any clue ?

**Comment by klshuster** [comment]
If you don't set `-v`, this error should go away

if you still want to set `-v`, you should, for now, wrap [this](https://github.com/facebookresearch/ParlAI/blob/982acb50f99261133ffa90ba04c569881389db6d/parlai/core/torch_generator_agent.py#L779-L795) in a try-catch and return an empty list if there's a `ValueError`
