### ISSUE TITLE
hdf5.h file not found.

### ISSUE THREAD

**Issue by fahr23** [facebookresearch/ParlAI#469]
I am trying to setup ParlAI to ubuntu and mac os. I had following error in both operating configurations.  

**In file included from /var/folders/55/p9wjq0pn1vzg4rdpq_sxqzwc0000gn/T/easy_install-s03lcklg/h5py-2.7.1/h5py/defs.c:569:
./h5py/api_compat.h:27:10: fatal error: 'hdf5.h' file not found
#include "hdf5.h"
         ^~~~~~~~
1 warning and 1 error generated.
error: Setup script exited with error: command '/usr/bin/clang' failed with exit status 1**

**Comment by alexholdenmiller** [comment]
Hi @fahr23, just to make sure we're on the same page, is this error appearing from `pip install h5py`?

**Comment by fahr23** [comment]
Hi @alexholdenmiller, just followed the following installation procedure. Thank you

> Installing ParlAI
> Run the following commands to clone the repository and install ParlAI:
> 
> git clone https://github.com/facebookresearch/ParlAI.git ~/ParlAI
> cd ~/ParlAI; python setup.py develop
> 
>

**Comment by alexholdenmiller** [comment]
Sure thing--during the `python setup.py develop` phase, setup.py tries to install all of the requirements listed in the requirements file. One of them is h5py, and that seems to be failing on your machines. Can you try `pip install h5py` directly?

I tried `pip uninstall h5py && pip install h5py` on my mac and did not receive any errors.

**Comment by fahr23** [comment]
after separately  run 

> pip install h5py

i can install successfully.

**Comment by fahr23** [comment]
thank you

**Comment by alexholdenmiller** [comment]
Great, thanks for reporting!
