### ISSUE TITLE
Question about reddit datasets

### ISSUE THREAD

**Issue by daje0601** [facebookresearch/ParlAI#4699]
Hello, I have a question. 

#Question1
I wonder if the preprocessing reddit datasets used for the poly encoder is not provided.
I only find moive reddit dataset in [this link](https://www.parl.ai/docs/tasks.html?highlight=reddit).

**Comment by klshuster** [comment]
we do not provide the datasets themselves

**Comment by daje0601** [comment]
I read reference paper. And then I find and preprocess dataset. 
Thank you for reply.
