### ISSUE TITLE
How to use Parlai's Pretrained Models on Windows?

### ISSUE THREAD

**Issue by Malfaro43** [facebookresearch/ParlAI#4705]
Hi, 

I am relatively new to NLP and machine learning and have been trying to use the pretrained models, Blenderbot 2.0 400 million parameters and Seeker 400 miilion parameters. Is there any way to use these models or the Parlai pip package on Windows, seeing as Parlai does not support Windows. 

Any help would be very appreciated, Thanks.

**Comment by klshuster** [comment]
you can try installing on windows and then search our issues for specific errors you come across. we simply do not actively support windows, but there have been folks who have found solutions to common problems that might be helpful to you
