### ISSUE TITLE
[Msc model] Are the new positional embeddings of `zoo:msc/blender3B_1024` trained in BST task?

### ISSUE THREAD

**Issue by heya5** [facebookresearch/ParlAI#4706]
hello, what's the difference between `zoo:msc/blender3B_1024` and `zoo:msc/msc3B_1024` ? 
Is the additional positional encoding of the blender3B_1024 model pre-trained on the BST task? Or just do random initialization for new positional embeddings other than the first 128?

**Comment by klshuster** [comment]
unless I am mistaken (cc @jxmsML), `zoo:msc/msc3B_1024` is fine-tuned on the MSC dataset, whereas `zoo:msc/blender3B_1024` is just blenderbot1 with 1024 position encodings (randomly initialized).

**Comment by jxmsML** [comment]
> unless I am mistaken (cc @jxmsML), `zoo:msc/msc3B_1024` is fine-tuned on the MSC dataset, whereas `zoo:msc/blender3B_1024` is just blenderbot1 with 1024 position encodings (randomly initialized).
 
yes the `zoo:msc/msc3B_1024` is finetuned on MSC dataset whereas `blender3B_1024` is not.

`zoo:msc/blender3B_1024` is just blenderbot1 with 1024 position encodings (initialized from `SinusoidalPositionalEmbedding` in `fairseq.modules.sinusoidal_positional_embedding` otherthan the first 128 which is from original blenderbot1)

**Comment by heya5** [comment]
Thank you for your quick reply!
