### ISSUE TITLE
Blenderbot 3 bug

### ISSUE THREAD

**Issue by roblox34** [facebookresearch/ParlAI#4723]
**Bug description**
AI doesn't understand.

**Reproduction steps**
1. Open Blenderbot 3
https://blenderbot.ai/
2. Say hi
3. AI doesn't understand

Thanks

Original post: https://www.linkedin.com/feed/update/urn:li:activity:6961348011885027328?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6961348011885027328%2C6961760162797826048%29

**Comment by stephenroller** [comment]
Next time, you can click on the message to see why it said what it said.
