### ISSUE TITLE
EMPATHY GENERATOR FOR A-I

### ISSUE THREAD

**Issue by DOUBLEDESIGN75** [facebookresearch/ParlAI#4726]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DOUBLEDESIGN75** [comment]
ARTIFICIAL EMPATHY AND THE POSSIBILITIES. ENDLESS AND POSITIVE IS THE MAIN GOAL

**Comment by klshuster** [comment]
The majority of our recent models include the [Empathetic Dialogues](https://github.com/facebookresearch/EmpatheticDialogues) dataset in their training data, so in theory should be able to display empathy when conversing with a chat partner.
