### ISSUE TITLE
Adding task to the flask API

### ISSUE THREAD

**Issue by geo47** [facebookresearch/ParlAI#4735]
Hello,

I am using this Flask project for making API call from ParlAI models. 
https://github.com/khushaljethava/parlai_flask

There I can load the model by 

```
from parlai.core.agents import create_agent_from_model_file

config = {
    "inference": "beam",
    "beam_size": 3,
    "topk": 10,
    "beam_min_length": 5,
    "beam_block_ngram": 3,
    "beam_context_block_ngram": 3,
    "beam_block_full_context": False
}

blender_agent = create_agent_from_model_file("zoo:blender/blender_90M/model", opt_overrides=config)
blender_agent = create_agent_from_model_file("zoo:light/biranker_dialogue/model", opt_overrides=config)
```

How can we add a task in that case `-t light_dialog`?
```
blender_agent = create_agent_from_model_file("zoo:light/biranker_dialogue/model", opt_overrides=config)
```

Thanks!

**Comment by klshuster** [comment]
hi, why would you like to add a task?

**Comment by geo47** [comment]
Hi,
Isn't it use for targeting the particular task from the model trained on multi-tasks?

 For example:
`python parlai/scripts/safe_interactive.py -mf zoo:blender/blender_90M/model -t blended_skill_talk`

**Comment by klshuster** [comment]
specifying the task in `interactive` is simply used as a way to seed the model with some task-specific context

**Comment by geo47** [comment]
Got it, thanks!

**Comment by geo47** [comment]
Hello @klshuster ,

I am reopening it to ask about one thing related. 

I am using Flask API for chatbot. In our case, we use single dialogue conversation. The chat session has ended after the single dialogue (i.e episode_done is always True `{'episode_done': True}`).

With this, I figured out that when there are multiple parallel request to the chatbot model. It gives the following error.
```
{"err":"Last observe() was episode_done, but we never saw a corresponding self_observe to clear the history, probably because you missed an act(). This was changed in #2043. File a GitHub issue if you require assistance."}
```

I looked through the issue [#2043](https://github.com/facebookresearch/ParlAI/pull/2043), but it didn't help much. 
could you please suggest a way to make it working for multiple agents. Single model response to parallel API requests.

Thanks!

**Comment by mojtaba-komeili** [comment]
I believe the source of your problem is having a single agent to serve all the requests. Each ParlAI agent has internal states, such as it history or invariants to make sure the turns happen. Having many requests go to a single agent and the race conditions between these agents may interfere with the internal states. Reseting the agent after each response might help, but again given the threads that the server uses, there is no guarantee for that. 

My suggested solution is cloning a new agent for each connection (server response) and disposing the cloned agent after the session is done. Cloned agents have separate internal states, but share the model weights. Thus they are very light on modern hardware and there shouldn't be too much overhead if the original agent is already loaded.

**Comment by geo47** [comment]
@mojtaba-komeili,  Thanks for your response..!

Could you please give me a code sinnept for cloning the agent. 

Also, does the cloning works in on-demand option or we have to clone the agents at the starting of the program...?
1. If it is on-demand (clone the agent only when the main agent is busy in responding), the cloning the agent and responding the query will take longer time to respond. 
2. If we have to clone the agents at the starting of the program, then we don't know the exact number of agent workers required.

Thanks.

**Comment by geo47** [comment]
Thank you @mojtaba-komeili,

With your suggested solution, I am able to to handle multiple parallel responses by cloning the agent.

Here is my solution that worked for me.

```python
try:
    self.blender_agent.observe({'text': bot_input, 'episode_done': True})
    res = self.blender_agent.act()
except:
    clone_agent = self.blender_agent.clone()
    clone_agent.observe({'text': bot_input, 'episode_done': True})
    res = clone_agent.act()
    clone_agent.reset()
```

**Comment by geo47** [comment]
Thank you so much!

Much appreciated..!
