### ISSUE TITLE
Manually add sentences to history of chatbot

### ISSUE THREAD

**Issue by Eichhof** [facebookresearch/ParlAI#4737]
Hello

I'm running BlenderBot2 (zoo:blenderbot2/blenderbot2_3B/model). In addition, I'm using a safety classifier to flag chatbot answers as inappropriate (parlai.utils.safety.OffensiveLanguageClassifier). Whenever a response is flagged as inappropriate, I change the response and propose a new topic to the user. Unfortunately, this is then not part of the history of the chatbot and thus the follow-up conversation gets often weird.

Is there a possibility to manually add sentences to the end of the history of the chatbot or to replace the last sentences with other sentences?

**Comment by klshuster** [comment]
you can call `agent.self_observe({'text': NEW_TOPIC_TEXT})` to add to the history (not sure how you're handling things specifically but this is the general idea)

**Comment by Eichhof** [comment]
Thank you very much. Is it also possible to replace the last added text in the history (agent.observe) with new text?

**Comment by klshuster** [comment]
you would need access the agent's history directly and replace the last string:

```python
history = agent.history
history.history_strings.pop(-1)
history.history_raw_strings.pop(-1)
history.history_vecs.pop(-1)
history.add_reply(new_reply)
```

where `new_reply` is a string with your new text.

**Comment by Eichhof** [comment]
Thank you very much for your answer. Is the last string just the last sentence or the whole response created by the last call to BlenderBot (also when the response consisted of multiple sentences)?

**Comment by klshuster** [comment]
the last string will be the last full response/message, not just the last sentence
