### ISSUE TITLE
BlenderBot3: inference on a particular module

### ISSUE THREAD

**Issue by lidiyam** [facebookresearch/ParlAI#4744]
Hi, I was wondering how can I inference a particular module of the BB3 model? For example, the generate dialogue response module takes in “Full context + knowledge + memory sequences” and generates a response. How can I feed in my own input to it?

Using the huggingface analogy, I’d tokenize this input string `f”{dialogue_context} {TOKEN_KNOWLEDGE} {knowledge} {TOKEN_END_KNOWLEDGE} {BEGIN_MEMORY} {memory_sequence} {END_MEMORY}”`  and pass it through the model. How to accomplish this using ParlAI? Also I've found the special tokens for BB3 [here](https://github.com/facebookresearch/ParlAI/blob/b1acb681207559da56a787ba96e16f0e23697d92/projects/bb3/constants.py#L36), but am not sure if it's usage is documented elsewhere (would be great to have a guide for this).

Thanks!

**Comment by klshuster** [comment]
Hi there, in #4746 I've written up a README describing the various ways in which to interact directly with the BB3 model (including how to show context to the model). Hopefully that answers your questions! 

(Once that lands, you can find the information [at this link](https://github.com/facebookresearch/ParlAI/blob/main/projects/bb3/agents/README.md)

**Comment by lidiyam** [comment]
Inferencing a module of the 3B model as described in the doc:
`parlai interactive --model projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent --module sdm
` 
returns a parsing error: `Parse Error: unrecognized arguments: --module sdm`

**Comment by klshuster** [comment]
my mistake, you don't need that option for the 3B model. You will want to include `--model-file zoo:bb3/bb3_3B/model` however (I will update the README to reflect that)

**Comment by klshuster** [comment]
#4765 improves the documentation
