### ISSUE TITLE
NarrativeQA support

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/ParlAI#475]
https://arxiv.org/abs/1712.07040 and https://github.com/deepmind/narrativeqa .
I can work on this one also if we want support.

**Comment by jaseweston** [comment]
sure! that'd be awesome

**Comment by apsdehal** [comment]
How would we like to approach this? 

We will have to select on of the following approaches:
- Download all of the stories in one go while building dataset 
- Reading a story interactively each time by making an HTTP request at training time.

I would like to go with the first approach as that allows offline development at a later time.

**Comment by jaseweston** [comment]
On Thu, Jan 4, 2018 at 11:09 AM, Amanpreet Singh <notifications@github.com>
wrote:

> How would we like to approach this?
>
> We will have to select on of the following approaches:
>
>    - Download all of the stories in one go while building dataset
>    - Reading a story interactively each time by making an HTTP request at
>    training time.
>
> I would like to go with the first approach as that allows offline
> development at a later time.
>

Yes, the first approach is fine! But I guess you already have a PR out
(sorry for slowness, been sick)

**Comment by apsdehal** [comment]
No problem, take care, I hope you are healthy and well now.
and yes, the PR uses first approach.
