### ISSUE TITLE
Can I just export all experiment results for every sample in test dataset?

### ISSUE THREAD

**Issue by liangzid** [facebookresearch/ParlAI#4755]
**Is your feature request related to a problem? Please describe.**

I am using ParlAI for a safety evaluation with my custom dataset, and until now I can only obtain some averaged safety results of the whole dataset, while I want to get a log for each sample is safe or not.

I have executed the command like this:
```bash
$python -m parlai eval_model --task fromfile:parlaiformat\
--fromfile_datapath ${mytest_set_path} \
--m parlai.agents.transformer.classifier:ClassifierAgent \
--mf zoo:dialogue_safety/single_turn/model \
--bs 1\
--no-cuda
```
and I have get:

![image](https://user-images.githubusercontent.com/26396476/185531094-14d1fb64-4cb3-4da1-98c7-5cb0a0d0f6b6.png)

So how do I get these info. for every sample?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by klshuster** [comment]
if you specify a `--world-logs /path/to/logs.jsonl` file, this will save each example along with the calculated metrics for that example. World logs can be loaded via the `Conversations` object in parlai:

```python
from parlai.utils.conversations import Conversations

conversations = Conversations('/path/to/world/logs.jsonl')
for convo in conversations:
    teacher_act = convo[0]
    model_response = convo[1]
```

`model_response` should have relevant metrics

**Comment by liangzid** [comment]
thanks!
