### ISSUE TITLE
error in poetry install

### ISSUE THREAD

**Issue by pengzju** [facebookresearch/ParlAI#4760]
[tool.poetry] section not found in xxx/ParlAI/pyproject.toml

It seems that just [tool.black] exists in [pyproject.toml]

**Comment by klshuster** [comment]
we currently don't support a poetry install

**Comment by pengzju** [comment]
i want to install Mephisto for Crowdsourcing tasks
Reference: https://github.com/facebookresearch/ParlAI/tree/main/parlai/crowdsourcing

**Comment by klshuster** [comment]
Can you please paste your commands as well as full stack trace?
