### ISSUE TITLE
Question about SeeKeR

### ISSUE THREAD

**Issue by daje0601** [facebookresearch/ParlAI#4766]
Hello, I just finished learning about Blenderbots 1 and 2. So, I read SeeKeR  paper.
I have a few questions about SeeKeR.

I understood that the biggest difference between SeeKeR and BB2 is that the pre-trained model is re-trained to perform the LM task and a knowledge generator is added.

- Question1 
Below scripts, I understand `--init-model` and  `--model`  is Transformer. Did I understand correctly?
```
$ python -m parlai.scripts.multiprocessing_train \
--task projects.seeker.tasks.knowledge,projects.seeker.tasks.dialogue,projects.seeker.tasks.search_query \
--multitask-weights 2,2,1 -bs 1 -vstep 1000 -vmt ppl -vp 5 -vmm min -vme 100000 -lstep 50 \
--init-opt arch/r2c2_base_3B --init-model zoo:seeker/r2c2_blenderbot_3B/model \
--model projects.seeker.agents.seeker:ComboFidGoldDocumentAgent --n-docs 5 \
--text-truncate 1000 --label-truncate 128 --truncate 1000 \
--fp16 True -lr 1e-06 --lr-scheduler reduceonplateau --optimizer adamw --save-after-valid True \
--warmup-updates 100 --update-freq 1 --gradient-clip 1.0 --skip-generation True --dropout 0.1 \
--attention-dropout 0.0 --load-from-checkpoint true --ddp-backend zero2 \
--checkpoint-activations true--model-file /tmp/my_seeker_dialogue_model
```

- Question2 
Also, looking at the script command above and review code, I understood that `tasks.knowledge`, `tasks.dialogue`, and `tasks.search_query` are all trained in One model with 4 modules(transformer). Did I understand correctly?
However, I am very confused because I think that each module is trained and should be viewed as a model.......
The part that made me think of this question has been captured in the paper.
If not, Since each module contains a token that can be distinguished when it runs, can a single transformer work?
<img width="303" alt="image" src="https://user-images.githubusercontent.com/73736988/186302838-580def82-eef0-4ec0-bbac-acac90d48bfa.png">
<img width="314" alt="image" src="https://user-images.githubusercontent.com/73736988/186302679-711a2164-3275-4158-95db-f26776b5737c.png">

- Question3
If Question2 is completely misunderstood, can I understand that SeeKeR is also learned in a rag-fid style similar to BB2?

I read 3 time SeeKeR paper.. But, I don't know exactly....
I don't trust myself, because I'm a junior, so I ask this question every time.
Thank you so much for always being kind.

--- 

I try to understand seek to use pyreverse and debugging. 
if you click, you can see the big size. 
![image](https://user-images.githubusercontent.com/73736988/186355013-650622ea-658b-4bc0-916d-f79de98c8b26.png)

**Comment by klshuster** [comment]
> Question 1: Below scripts, I understand --init-model and --model is Transformer. Did I understand correctly?

the `--init-model` is indeed a transformer language model (encoder/decoder). However, the `--model` is a `FidModel`, which is essentially a `Transformer` but with a modified forward pass

> Question 2
A single Transformer language model is used to perform each of the modular functions within SeeKeR; we inform the model which task to perform via the special control tokens

> Question 3
SeeKeR is _somewhat_ trained in a FiD style. The `ComboFid` component is that, for certain modules, FiD-style training/decoding is *not required*. FiD is used when there are retrieved documents, which is *only* for the _knowledge_ module; the search query and dialogue response modules do not require FiD and thus are used as regular seq2seq models.

**Comment by daje0601** [comment]
Thank you so much!
