### ISSUE TITLE
Training ParlAI dialog model on KG dataset.

### ISSUE THREAD

**Issue by geo47** [facebookresearch/ParlAI#4774]
Hello,

How can we train the model for reasoning over KG (entity <- relationship -> entity) dataset and generate bot responses (dialogs).

Any suggestions or guidance would be highly appreciated.

Thanks!

**Comment by klshuster** [comment]
you can try just training a vanilla dialogue model, assuming there exists a KG dialogue dataset in ParlAI. If there doesn't, first step is to add one!

**Comment by geo47** [comment]
Thanks for your response.

Can you please provide a sample structure to creating KG dialogue dataset? 
Currently, I have KG dataset in the format `entity -> RELATION -> entity`.

Thanks!

**Comment by geo47** [comment]
In the above example the dataset shows the grounded knowledge under `__knowledge <TEXT> __endknowledge__` tag.

How about incorporation knowledge graph triplets `<entity, relation, entity>` to generate the response text?

**For example:**
From the triple facts in the KG, 
`Adam -> works -> New York ` 

The model should response the input query based on the KG fact, 
```
Input: Where does Adam works?
Output: Adam works in New York.
```

**Comment by klshuster** [comment]
That's a design decision for you to make
