### ISSUE TITLE
How to access information stored in [memories] which are printed in messages when using command : -verbose

### ISSUE THREAD

**Issue by Beidaidai0713** [facebookresearch/ParlAI#4776]
I saw that when using command --v to print all messages, the [memories] feature seem to record the information that the chatbot gained from the ongoing conversation. I wonder if there's any way to access the data stored in [memories]? It is described in the paper that the chat bot has long term memory and it will stored them separately when talking to different people. How does it achieve that? Can I put things into the chat bot's memory by changing source code?

**Comment by mojtaba-komeili** [comment]
When interacting with the bot (like any other ParlAI agent) there is a cycle of `observe` and `act`. The `act` function returns a Message (dictionary) that has multiple fields. If you are using BlenderBot 2 or 3, memory must one of the fields. Check the `world.parley` in the [interactive](https://github.com/facebookresearch/ParlAI/blob/fae3e39c249d202c1c588fb3d9f9cbf6d017606a/parlai/scripts/interactive.py#L78) code for more clarification on how this works and how to modify it for your own code.
About changing the code and having new memory, I know it works with BlenderBot 3 for sure. But you have to respect its memory entries format. Looking at [MemoryUtils](https://github.com/facebookresearch/ParlAI/blob/fae3e39c249d202c1c588fb3d9f9cbf6d017606a/projects/bb3/agents/utils.py#L168) helps you figure that out.

**Comment by Beidaidai0713** [comment]
> When interacting with the bot (like any other ParlAI agent) there is a cycle of `observe` and `act`. The `act` function returns a Message (dictionary) that has multiple fields. If you are using BlenderBot 2 or 3, memory must one of the fields. Check the `world.parley` in the [interactive](https://github.com/facebookresearch/ParlAI/blob/fae3e39c249d202c1c588fb3d9f9cbf6d017606a/parlai/scripts/interactive.py#L78) code for more clarification on how this works and how to modify it for your own code. About changing the code and having new memory, I know it works with BlenderBot 3 for sure. But you have to respect its memory entries format. Looking at [MemoryUtils](https://github.com/facebookresearch/ParlAI/blob/fae3e39c249d202c1c588fb3d9f9cbf6d017606a/projects/bb3/agents/utils.py#L168) helps you figure that out.

Thanks so much for your reply. It's really helpful.
