### ISSUE TITLE
How to intialize interactive_web with outfile from previous chat?

### ISSUE THREAD

**Issue by igisho** [facebookresearch/ParlAI#4780]
Use this to open other questions or issues, and provide context here.
I am usint interactive_web for interaction with blenderbot. I, dike to save session conversation from memory to file so i can reinitialize blednerbot with memory in diferent session. How to do this? Is there any domumentation how --outfile works? Also is there any command how can i init with interactive:web with outfile ? 

python -m parlai.scripts.interactive_web --host 0.0.0.0 --verbose --debug --task blended_skill_talk --model-file zoo:blenderbot2/blenderbot2_400M/model --outfile ./out  --search_server 'my_search_server'

**Comment by Dev-hestabit** [comment]
@igisho  Have you found any solution regarding this, i am trying to achieve similar result with chat service but not able to found any solution
