### ISSUE TITLE
Is there a way for parlai to construct the dataset dynamically?

### ISSUE THREAD

**Issue by LaguePesikin** [facebookresearch/ParlAI#4782]
**Is your feature request related to a problem? Please describe.**
Hello! Our team is working on a dataset with only questions. The dialogue system needs to provide its own answers to these questions. We want this process to be as close to human habits as possible, and the model needs to consider all its historical answers when facing the current sample. This somewhat tricky approach requires the dataset to be constructed dynamically and updated as inferencing.
I wonder if there's some solution in parlai that can implement this approach?

**Comment by stephenroller** [comment]
A teacher is just an agent, and agents can act any way they want.

You won't be able to use any of the FixedDialogTeacher mechanisms, but if you extend from the root Teacher class, you can have your messages be arbitrarily dynamic.

**Comment by LaguePesikin** [comment]
@stephenroller  Thanks for your reply! I will go deeper to see the implementation.
