### ISSUE TITLE
Is there any way to make BB3 to ask specific questions/ say specific things ?

### ISSUE THREAD

**Issue by Beidaidai0713** [facebookresearch/ParlAI#4783]
Hi. I'm trying to use BB3 to create a chatbot that can be used after class by students to help collect their suggestions or comments about teaching methods or contents in class. Is there any way to make BB3 to ask specific questions like :"How do you feel about the discussion part in class?" or "Do you feel overwhelmed because of the current workload of class reading and assignments?" 

I was thinking about adding these as contexts but bb3 does not always use the topics in contexts, but I want to gather the answers of these kind of questions as quick as possible in a short conversation. What part of the code should I look at to add this function into bb3?

**Comment by klshuster** [comment]
There are a few things you can try:

1. If you set up your own custom interactive world, you can simply output those statements directly as openers to the conversation; not sure about your general familiarity with ParlAI, but you can [subclass the `InteractiveWorld` and modify it's parley function](https://github.com/facebookresearch/ParlAI/blob/e217dc45887854564a72d22b10a840c1e777c440/parlai/tasks/interactive/worlds.py#L57-L96) and add it to your own task, then call `--task my_teacher_task` to use it
2. You can seed BB3 with a persona that would make it amenable to asking these questions, e.g., `Person 2's Persona: I am a teacher. I am seeking feedback about teaching methods`. This would require setting the memories directly, via calling `agent.memories = agent.get_opening_memories(memories)`, where memories is a list of persona items

**Comment by Beidaidai0713** [comment]
> There are a few things you can try:
> 
> 
> 
> 1. If you set up your own custom interactive world, you can simply output those statements directly as openers to the conversation; not sure about your general familiarity with ParlAI, but you can [subclass the `InteractiveWorld` and modify it's parley function](https://github.com/facebookresearch/ParlAI/blob/e217dc45887854564a72d22b10a840c1e777c440/parlai/tasks/interactive/worlds.py#L57-L96) and add it to your own task, then call `--task my_teacher_task` to use it
> 
> 2. You can seed BB3 with a persona that would make it amenable to asking these questions, e.g., `Person 2's Persona: I am a teacher. I am seeking feedback about teaching methods`. This would require setting the memories directly, via calling `agent.memories = agent.get_opening_memories(memories)`, where memories is a list of persona items

Thanks so much for the reply. I would try these and see if they help  to finish the task.
