### ISSUE TITLE
Installing blenderbot on a cloud server such as GCP

### ISSUE THREAD

**Issue by Danial1994** [facebookresearch/ParlAI#4791]
Use this to open other questions or issues, and provide context here.
Hi
I wanted to ask if it is possible to install blenderbot on a cloud server such as google cloud services, instead of running it locally, and if it is possible, is there any documentation on doing that?  any tutorial?

Thanks

**Comment by mojtaba-komeili** [comment]
The main goal of ParlAI is providing the agents for the research purposes. However, it is possible to demo these agents with wrapping them inside a server. We have a light weight one [here](https://github.com/facebookresearch/ParlAI/blob/main/parlai/scripts/interactive_web.py). Someone could extend this simple script for serving BlenderBot, after installing ParlAI.
