### ISSUE TITLE
Pre-train r2c2 from scratch

### ISSUE THREAD

**Issue by robinsongh381** [facebookresearch/ParlAI#4797]
I would like to pre-train r2c2-base-400M/3B from scratch with reddit+robert+cc100en datasets on ParlAI. 
Is there any way / script to do that ?

**Comment by klshuster** [comment]
You will need to look elsewhere for the data, as we do not provide it within ParlAI. The SeeKeR paper outlines the training hyperparamters

**Comment by robinsongh381** [comment]
Ok, thank you !
