### ISSUE TITLE
Better option for "self_chat" discovered.

### ISSUE THREAD

**Issue by jacek-michalak** [facebookresearch/ParlAI#4800]
I know we have a "self_chat" option in ParlAI but you can get the same thing in a simpler way.
After launching the interactive mod and typing seed questions, simply press ENTER over and over.
Below is an example chat using this technique: parlai i -mf zoo:seeker/r2c2_blenderbot_3B/model

Enter Your Message: What do You know about life?
[Bart]: I don't know much about life, but I do know that I'm going to die one day.
Enter Your Message: 
[Bart]: I'm not sure what you mean by that. Do you mean I'm not going to live forever?
Enter Your Message: 
[Bart]: No, I mean that I am going to be dead one day, and then I will cease to exist.
Enter Your Message: 
[Bart]: I guess that's true, but it doesn't make me feel any better about the whole thing.
Enter Your Message: 
[Bart]: Do you believe in an afterlife, or do you think it's all just part of a big cosmic joke?
Enter Your Message: 
[Bart]: I'm an atheist, so I don't think there's anything after this life. I just hope I'm remembered fondly.
Enter Your Message: 
[Bart]: Well, I hope you have a good rest of your life, and I wish you all the best.
Enter Your Message: 
[Bart]: Well, thank you for the conversation. It's been nice talking to you. Have a good day!

**Comment by klshuster** [comment]
Thanks, just note that you're most likely adding extranneous newline delimiters to the model history
