### ISSUE TITLE
Questions about the search engine module in bb3

### ISSUE THREAD

**Issue by zetian1025** [facebookresearch/ParlAI#4807]
When I read the code in [projects/bb3/agents/search_agent.py](url), it looks like bb3 only makes one web search for a given query, which can only return the snippets for all retrieved web documents. 

So does it mean bb3 only uses the snippets of retrieved websites as external knowledge to help generate responses? 

Or bb3 use a local look-up table like WizInt to get the full document?

**Comment by mojtaba-komeili** [comment]
The search module in BB3 uses snippets from those retrieved document. WizInt, uses the same technique as well, although we compared it dense retrieval from an indexed data dump as well. I think that's what you mean by "local look-up table".

**Comment by zetian1025** [comment]
I see, thanks for your response!

**Comment by Darth-Carrotpie** [comment]
Any advice how to make the knowledge retrieval faster? It really adds a lot to the delay of response...

**Comment by klshuster** [comment]
depends on how you're doing knowledge retrieval -- it should not add substantial time unless your search server has high latency
