### ISSUE TITLE
Question about the `MemoryDecision` task of BB3

### ISSUE THREAD

**Issue by desperadoola** [facebookresearch/ParlAI#4809]
The format of `MemoryDecision` task seems to conflict during training and interactive mode. On the Agent Information Page, `MemoryDecision` task is described as below, and we observe the same format during interactive mode,

![image](https://user-images.githubusercontent.com/30496727/193214037-b72c6fff-b9a6-491a-906c-d28b367b6372.png)

But the display of task`MSCMemoryDecisionTeacher` seems to provide another format, 

`parlai dd --task projects.bb3.tasks.opt_decision_tasks:MSCMemoryDecisionTeacher`

![image](https://user-images.githubusercontent.com/30496727/193214758-de1fe488-ebc3-4e36-bd80-7843789d147d.png)

What I missed?

**Comment by desperadoola** [comment]
The same conflicts exist on memory generation task, 

according to Agent Information Page:

![4565C98F-7F76-435B-91F1-1445448E44FE](https://user-images.githubusercontent.com/30496727/193235770-d1f7db6b-8d01-47df-8241-535d41aa1e54.png)

But when run the script: `parlai dd --task projects.bb3.tasks.r2c2_memory_generation_tasks:MscMemoryGenerationTeacher`, it generates the below samples. Apparently, a full history of dialogue is used as the context.

![image](https://user-images.githubusercontent.com/30496727/193236114-a879b4b8-7d7b-4878-bea8-15839240807b.png)

**Comment by mojtaba-komeili** [comment]
I think you are confusing the dataset example with the process that happens inside the agent. The examples you show here are the datasets that we used for training modules in BB3. However, the context of the example goes through extra processing (in this case choosing the last turn) to train the model. 
In fact, we often try different approaches for this extra processing and the flags for controlling it might be available in agent. The final released models are based on what had the best performance.

**Comment by desperadoola** [comment]
So what is the best way to print out the training examples after all the extra processing? For example, the task  `projects.bb3.tasks.r2c2_decision_tasks:MSCMemoryDecisionTeacher` when we train bb3.

**Comment by mojtaba-komeili** [comment]
Appreciate your comment here @klshuster.

**Comment by desperadoola** [comment]
I have checked the logbook of bb3 carefully. I'm wondering if the task `projects.bb3.tasks.opt_decision_tasks:MSCMemoryDecisionTeacher` is up-to-date. Since I did find the below descriptions in the logbook, which seems to be the initial trail to introduce personas in the context of memory decision tasks. And it's also the current implementation of the task `projects.bb3.tasks.opt_decision_tasks:MSCMemoryDecisionTeacher`.

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/30496727/195564647-5e75d0fa-fe80-4014-bf95-3904c7d0b457.png">


However, the final version described in Agent Information Page, which uses the full personas as the context, seems not available in current task implementation for training. Correct me if I'm wrong, and thanks for your reply.

**Comment by klshuster** [comment]
Hi there, yes you've identified a mismatch between training and test-time inference.

The memory decision task during training only shows a single persona; this is meant to teach the model whether using such a persona is helpful in responding to the one turn of context; we want to give maximum signal to the model during training. During inference, however, we have several memories on which to possibly condition, so we show them all at the same time. This is simply a design choice.

The memory generation task is similarly setup. During training, we show the model several turns of context, but during inference (in our setup) we only show one turn of context. 

For both of these cases, one could setup inference to be exactly as is seen during training, but again these are design decisions.

**Comment by desperadoola** [comment]
Thanks for your reply. It confused me for a long time. 

It's impressive that the model could figure out the mismatch and give a reasonable response. Great work!
