### ISSUE TITLE
How to make data with knowledge similar to Wizard of Wikipedia

### ISSUE THREAD

**Issue by guijuzhejiang** [facebookresearch/ParlAI#4811]
Thank you very much for publishing the English converse knowledgably about open-domain dataset wizard_of_wikipedia. I would like to make similar datasets for other languages. Can you guide me on how to do this? Is there a script provided? Thanks in advance

**Comment by mojtaba-komeili** [comment]
That is great. Most of our recent datasets are collected using [Mephisto](https://github.com/facebookresearch/Mephisto). You may find examples of similar collected datasets in our crowdsourcing directory in ParlAI [here](https://github.com/facebookresearch/ParlAI/tree/main/parlai/crowdsourcing/projects). I recommend looking at Wizard of Internet as a close one.

**Comment by mojtaba-komeili** [comment]
Hi, no worries. Glad to help. The exact details of such dataset creation might be an open research question. I'm afraid we cannot have a simple clean answer for it in this QA thread.

**Comment by guijuzhejiang** [comment]
Indeed, I think it is difficult to have such a script that identifies keywords and extracts relevant wiki knowledge. Thank you for your reply.
