### ISSUE TITLE
Boilerplate Code for (parallel) Multi-Agent Chat Service Through Browser

### ISSUE THREAD

**Issue by Guest400123064** [facebookresearch/ParlAI#4817]
Hi Everyone,

I am following the [Chat Service tutorial](https://www.parl.ai/docs/tutorial_chat_service.html) to set up a browser interface to chat with the ParlAI agent, in particular BlenderBot2. However, if I understand correctly, the tutorial only allows a one-at-a-time chatting session, which means I need to run multiple `client.py` and open multiple ports so that the chatting sessions can be independent. So, I wonder if there is another tutorial about letting human agents visit the same page (same host + port) and be directed to different sessions.

My web app development skill is very limited. Any recommendation is appreciated. Many thanks for considering my request.

**Comment by stephenroller** [comment]
We never implemented sessioning for that basic tutorial. Maybe @mojtaba-komeili can provide guidance?

**Comment by mojtaba-komeili** [comment]
One way you can have an implementation for that is having a server that keeps session for each user that connects (maybe a websocket connection) and cloning an agent during opening that session. You don't have to create a new agent for each user; you can simply have one initialized when you start your server and then clone that. Cloning is going to make much lighter agents. You can check the tutorial you mentioned for how to handle interacting with the agent.

**Comment by Guest400123064** [comment]
Ok! Thank you!
