### ISSUE TITLE
blenderbot3_30B cpu memory requirement

### ISSUE THREAD

**Issue by Tacacs-1101** [facebookresearch/ParlAI#4818]
how much CPU memory is required to load the bb3_30B model? When i tried to shard bb3_30B model it throws an error that cpuallocator cannot allocate enough memory. I have a machine with 60GB of RAM and 60GB of GPU memory. Can I run blenderbot_30B model with this configuration of the server?

**Comment by mojtaba-komeili** [comment]
Even running the 3B model on CPU is too cumbersome: it takes a long time to load and each inference is taking 1-5 minutes. 
I don't recommend relying on CPU for that model size at all.

**Comment by klshuster** [comment]
the BB3 30B model is around 60gb, fwiw
