### ISSUE TITLE
AttributeError: module 'parlai.tasks.multidoc2dial.agents' has no attribute 'create_agents'

### ISSUE THREAD

**Issue by Linohong** [facebookresearch/ParlAI#4820]
Hi, thank you so much for opening a great research work!

I was trying to make my own task and use display_data to test if it works fine. 
In my parlai/tasks/ directory, 
I copy and pasted the holl_e task and renamed it multidoc2dial directory.

There, I changed Teacher class of Holle to 'MultiDoc2DialTeacher.' 
I was trying to download the multidoc2dial data from the huggingface dataset.

Here is a little bit of a snippet of class MultiDoc2DialTeacher:
```
class MultiDoc2DialTeacher(FixedDialogTeacher):
    """
    Sequence of utterances and responses with background knowledge about movies.

    From the Holl-E dataset. More information found at
    https://github.com/nikitacs16/Holl-E.
    """

    @classmethod
    def add_cmdline_args(
        cls, parser: ParlaiParser, partial_opt: Optional[Opt] = None
    ) -> ParlaiParser:
        super().add_cmdline_args(parser, partial_opt)
        group = parser.add_argument_group('Holl-E Knowledge arguments')
        group.add_argument(
            '--knowledge-types',
            '-kt',
            type=str,
            default='full',
            help='Either "full" (all of the following), "none" (knowledge not used) or comma separated list of knowledge types to include. Possible types: plot, review, comments, fact_table (contains awards, taglines, and similar movies). e.g. -kt plot,review,fact_table or -kt full',
        )
        return parser

    def __init__(self, opt, shared=None):
        super().__init__(opt, shared)
        multidoc2dial_path = _path(opt)
        self.datatype = opt['datatype'].split(':')[0]
        self.id = 'multidoc2dial'
        self.hf_path = 'multidoc2dial'
        self.hf_split = 'train'
        self.episodes = self.setup_data(multidoc2dial_path)
        if shared is not None:
            self.episodes = shared['episodes']
        else:
            self.episodes = self.setup_data(multidoc2dial_path)
        self.reset()

    def setup_data(self, path):
        # use test json if valid is given
        # json_dtype = self.datatype if not self.datatype.startswith('valid') else 'test'
        # json_path = os.path.join(path, f'raw_{json_dtype}_data.json')
        # with PathManager.open(json_path) as f:
        #     data = json.load(f)
        episodes = []
        prev_id = None
        episode = None, []

        self.dataset = datasets.load_dataset(
            path=self.hf_path, split=self.hf_split, ignore_verification=True
        )

        for row in self.dataset:
            query, text_dict = self._get_text_value(row)
            label = self._get_label_value(row)
            label, candidates = self._get_label_candidates(row, label)

            episode_dict = text_dict
            episode_dict['text'] = query
            episode_dict['label'] = label
            episode_dict['label_candidates'] = candidates
            # yield episode_dict, True



        print('EXIT HERE: LINO')
```

However, when I run 
`parlai display_data --task multidoc2dial`
, it gives me following error,

> 2022-10-05 09:11:51,461 INFO     | Opt:
> 2022-10-05 09:11:51,462 INFO     |     allow_missing_init_opts: False
> 2022-10-05 09:11:51,462 INFO     |     batchsize: 1
> 2022-10-05 09:11:51,462 INFO     |     datapath: /home/ubuntu/ts_hong/ParlAI/data
> 2022-10-05 09:11:51,462 INFO     |     datatype: train:ordered
> 2022-10-05 09:11:51,462 INFO     |     dict_class: None
> 2022-10-05 09:11:51,462 INFO     |     display_add_fields: 
> 2022-10-05 09:11:51,462 INFO     |     download_path: None
> 2022-10-05 09:11:51,462 INFO     |     dynamic_batching: None
> 2022-10-05 09:11:51,463 INFO     |     hide_labels: False
> 2022-10-05 09:11:51,463 INFO     |     ignore_agent_reply: True
> 2022-10-05 09:11:51,463 INFO     |     image_cropsize: 224
> 2022-10-05 09:11:51,463 INFO     |     image_mode: raw
> 2022-10-05 09:11:51,463 INFO     |     image_size: 256
> 2022-10-05 09:11:51,463 INFO     |     init_model: None
> 2022-10-05 09:11:51,463 INFO     |     init_opt: None
> 2022-10-05 09:11:51,463 INFO     |     is_debug: False
> 2022-10-05 09:11:51,463 INFO     |     knowledge_types: full
> 2022-10-05 09:11:51,463 INFO     |     loglevel: info
> 2022-10-05 09:11:51,463 INFO     |     max_display_len: 1000
> 2022-10-05 09:11:51,464 INFO     |     model: None
> 2022-10-05 09:11:51,464 INFO     |     model_file: None
> 2022-10-05 09:11:51,464 INFO     |     multitask_weights: [1]
> 2022-10-05 09:11:51,464 INFO     |     mutators: None
> 2022-10-05 09:11:51,464 INFO     |     num_examples: 10
> 2022-10-05 09:11:51,464 INFO     |     override: "{'task': 'multidoc2dial'}"
> 2022-10-05 09:11:51,464 INFO     |     parlai_home: /home/ubuntu/ts_hong/ParlAI
> 2022-10-05 09:11:51,464 INFO     |     starttime: Oct05_09-11
> 2022-10-05 09:11:51,464 INFO     |     task: multidoc2dial
> 2022-10-05 09:11:51,464 INFO     |     teacher_seed: None
> 2022-10-05 09:11:51,464 INFO     |     verbose: False
> 2022-10-05 09:11:51,486 INFO     | Current ParlAI commit: 2e2a2b2ecd9baee14064c97062115bf900f7281b
> 2022-10-05 09:11:51,502 INFO     | Current internal commit: 2e2a2b2ecd9baee14064c97062115bf900f7281b
> 2022-10-05 09:11:51,517 INFO     | Current fb commit: 2e2a2b2ecd9baee14064c97062115bf900f7281b
> 2022-10-05 09:11:51,520 INFO     | creating task(s): multidoc2dial
> No config specified, defaulting to: multi_doc2dial/multidoc2dial
> Downloading and preparing dataset multi_doc2dial/multidoc2dial (download: 6.15 MiB, generated: 143.96 MiB, post-processed: Unknown size, total: 150.11 MiB) to /home/ubuntu/.cache/huggingface/datasets/multi_doc2dial/multidoc2dial/1.0.0/6e2a407c09eb478a5b80845fc04406bb9c9d4bea9f135dd7b8b7610a6b608d84...
> Traceback (most recent call last):
>   File "/home/ubuntu/ts_hong/ParlAI/parlai/core/worlds.py", line 1397, in _create_task_agents
>     task_agents = my_module.create_agents(opt)  # type: ignore
> AttributeError: module 'parlai.tasks.multidoc2dial.agents' has no attribute 'create_agents'

What did I do wrong here? 

Thank you !

**Comment by mojtaba-komeili** [comment]
I wonder if adding the default teacher make it work. Could you add these two line at the bottom of your agent file and try again?
```
class DefaultTeacher(MultiDoc2DialTeacher):
    pass
```
