### ISSUE TITLE
YFCC image path is not opened when reproducing Image-Chat model

### ISSUE THREAD

**Issue by passing2961** [facebookresearch/ParlAI#4826]
Hi, I'm Young-Jun Lee.

I'm currently reproducing the results of the image-chat model. I encountered a problem in that the YFCC image path is not opened (as shown in below error log).
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/yjlee/workspace/DialogCC/data/downloaded_dialog/yfcc_images/418d64c8c8c6df72d38e5d9d95d6984c.jpg'
```
I know why this error happens because of YFCC image path itself is blocked. So, in this case, the below code is not working.
https://github.com/facebookresearch/ParlAI/blob/2e2a2b2ecd9baee14064c97062115bf900f7281b/parlai/core/image_featurizers.py#L218-L230

So, I'm wondering if there is another solution, or should I add a try-except and return the None value for the image?

**Comment by klshuster** [comment]
A try-except sounds like the way to go
