### ISSUE TITLE
[BlenderBot2] Create BB2 Agent using FAISS search

### ISSUE THREAD

**Issue by gitsand996** [facebookresearch/ParlAI#4827]
Hi! 

I'm wondering if I could create a SearchQueryFAISSIndexFiDAgent on BlenderBot2 model. As I see, the class BlenderBot2SearchQueryFAISSIndexFiDAgent doesn't exist in the repository. Anyone tried implementing this class in order to use a search query FAISS FiD agent on top of BB2?

What I want to do is to use the 'search_only' knowledge method with my own FAISS index, rather than with a search server. In this way I'll be able to feed the most similar documents to BB2 generator starting from the query vec.

**Comment by mojtaba-komeili** [comment]
I think there is a simple solution for that. I had done it previously. I will work on it adding it as soon as I get a chance.

**Comment by mojtaba-komeili** [comment]
Seems like you have a good idea about what you are doing. If you want to have a PR adding this new agent, we welcome it. Contributions are always welcome 👍 .

**Comment by gitsand996** [comment]
Ok, thanks a lot. I'll reopen for any doubt on it. Bye
