### ISSUE TITLE
BB3 Response Time

### ISSUE THREAD

**Issue by ryanshea10** [facebookresearch/ParlAI#4832]
Hi, I'm trying to host a chat service with blenderbot3 (3B) across 5 NVIDIA GeForce RTX 2080 Ti gpus. Here is my config file

```
tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 1000
opt:
  debug: True
  models:
    blenderbot3_3B:
      model: projects.seeker.agents.seeker:ComboFidGoldDocumentAgent
      init_opt: gen/r2c2_bb3
      model_file: zoo:bb3/bb3_3B/model
      interactive_mode: True
      no_cuda: False
      override:
        init_opt: gen/r2c2_bb3
        search_server: https://www.google.com
        model_parallel: True
additional_args:
  page_id: 1 # Configure Your Own Page
```

I was wondering if there are any methods I could use to increase the response time for the bot. Currently it takes the bot around 10-15 seconds to respond with my current setup which seems a bit slow, especially compared to the bb3 demo which is faster and uses a larger model. Let me know if there are any other details I can provide

**Comment by mojtaba-komeili** [comment]
For reference the demo models are running on A100 GPUs.

**Comment by ryanshea10** [comment]
Would that account for the difference in response time or are there other adjustments I could make?

**Comment by mojtaba-komeili** [comment]
Actually I see your search server here is just `www.google.com`. You must set up your own server that responding the BB3 requests. One reason your setup is so slow might be that you have part of model crashing or timing out (which may trigger retries).
Also why your mode is set to `projects.seeker.agents.seeker:ComboFidGoldDocumentAgent`?
GPU is an important factor, specially here that an A100 can probably keep your whole model and there is no need to have communication between GPUs. I remember our initial tries with V100 was giving us 7-10 s response time.

**Comment by ryanshea10** [comment]
I see, I'll fix the search server to see if that speeds up anything.
The model is set to `projects.seeker.agents.seeker:ComboFidGoldDocumentAgent` because I read that that was the default option for the agent. Is there something else I should be using?
I was under the impression that using multiple gpus would speed up response time if the inputs are [pipelined](https://pytorch.org/tutorials/intermediate/model_parallel_tutorial.html#speed-up-by-pipelining-inputs), which it seems like they are when using `model_parallel`. Could using multiple gpus actually be slowing down the process? I would assume that the bb3 demo has to be using multiple gpus but is still pretty fast.

**Comment by mojtaba-komeili** [comment]
You are using the seeker model (see the path). Try [this one](https://github.com/facebookresearch/ParlAI/blob/8a97c66b984f9690edbf2d5084f45b787dc485db/projects/bb3/agents/r2c2_bb3_agent.py#L237) instead for BB3.

**Comment by ryanshea10** [comment]
Thanks for your help. I managed to get the the response time to around 3-4 seconds by changing some of the configurations, here is my new config file

```
tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 1000
opt:
  debug: True
  models:
    blenderbot2_3B:
      model: projects.bb3.agents.r2c2_bb3_agent:BB3SubGoldAgent
      init_opt: gen/r2c2_bb3
      model_file: zoo:bb3/bb3_3B/model
      interactive_mode: True
      no_cuda: False
      gpu_beam_blocking: True
      override:
        eval_batchsize: 4
        batchsize: 4
        model: projects.bb3.agents.r2c2_bb3_agent:BB3SubGoldAgent
        history_size: 10
        fp16_impl: mem_efficient
        skip_generation: True
        beam_size: 5
        beam_min_length: 15
        num_workers: 8
        init_opt: gen/r2c2_bb3
        search_server: https://www.google.com
        model_parallel: True
additional_args:
  page_id: 1
```

Currently I'm not having the bot use internet search which is why I'm using `projects.bb3.agents.r2c2_bb3_agent:BB3SubGoldAgent`. Do you think that there could be any speed improvements I'm missing or would it be difficult to get the response time much lower? [Here's](https://user-images.githubusercontent.com/84943760/198750030-55749d5c-6f81-4929-a222-5626a12b4018.svg) a flamegraph I created for `model.act()` and it seems like decoding is taking up a pretty big majority of the response time.

I also wanted to ask if there's any way to limit spikes in response time when blenderbot receives simultaneous requests. For example if one user is chatting with the bot it takes about 3-4 seconds to respond. But if the bot receives ~8 requests at once the response time goes up to around 26 seconds for me. Are there any steps that the blenderbot demo took to limit this? I'm looking to run some experiments with the bot that will involve several people chatting with it at once.

**Comment by mojtaba-komeili** [comment]
3-4 seconds seems reasonable. And you are right that decoding is taking most of the time during inference. There are some ongoing projects for improving decoding. So stay tuned on that. 
For serving multiple users, you may try a batching mechanism that keeps requests in a queue and batches them between each inference. Have a look at batching in [this code](https://github.com/facebookresearch/metaseq/blob/main/metaseq/cli/interactive_hosted.py#L64) for reference.

**Comment by klshuster** [comment]
Additionally, you can change the decoding method to be sampling rather than beam search to speed up response time

**Comment by Dev-hestabit** [comment]
@ryanshea10 Can you please tell the procedure to create flamegraph for bb3

**Comment by ryanshea10** [comment]
@Dev-hestabit check out [cprofile](https://docs.python.org/3/library/profile.html) and [flameprof](https://pypi.org/project/flameprof/), you can use these to profile model.act()

**Comment by Dev-hestabit** [comment]
@ryanshea10 so i need to add in between code flameprof and cprofile or add them as a parameter in parlai command as i have tried them but didn't get response similar to your's

it will help a lot if you could share the command , code or at least the steps to recreate that flamegraph

**Comment by ryanshea10** [comment]
I don't have the exact code I used but here's a quick example that gives the gist of what I did. There are probably a few ways you could do this though.

In world.py (or wherever bb3_agent.act() is being called)
```
​import​ ​cProfile​

​profiler = cProfile.Profile()
​profiler.enable()
​ 
model.​act()

profiler.disable()
​profiler.dump_stats(​"stats.prof"​)
```

Then in the command line.
```
flameprof stats.prof > requests.svg
```
