### ISSUE TITLE
Not able to donwload zoo:bb3/bb3_30B/model

### ISSUE THREAD

**Issue by Tacacs-1101** [facebookresearch/ParlAI#4834]
when i tried to download this model, its corresponding path @ http://parl.ai/downloads/_models/bb3/bb3_30B/model.tgz, it says that this doesn't exist while its mentioned in the repo. Any help regarding this.

**Comment by klshuster** [comment]
oops, that should be `http://parl.ai/downloads/_models/bb3/bb3_30B/consolidated.pt`. let me edit the README

**Comment by klshuster** [comment]
oh the README is up to date, that is the correct URL ^
