### ISSUE TITLE
How to call query generator with multi-turn data?

### ISSUE THREAD

**Issue by yonatanbitton** [facebookresearch/ParlAI#4837]
Hi.
I want to invoke query generator with multi-turn data.
For example, I have the following dialogue: `["Hi, I love Joe Rogan", "Me too!", "How old is he?"]`. How can I use a query generation model for inference on this dialog?
I currently use this cmd line: 
`parlai interactive -mf zoo:blenderbot2/query_generator/model`
Which allows feeding a single turn, not multi-turn. 

An additional question - what's the python code for model inference?
For example, to run model inference in some kind of for-loop. 
I didn't find relevant code in the [documentation](https://parl.ai/docs/index.html), nor in the [ParlAI Tutorial](https://colab.sandbox.google.com/drive/1bRMvN0lGXaTF5fuTidgvlAl-Lb41F7AD#scrollTo=3hzrDhPS1QCW). The tutorial colab only allows Interactive.main interaction.

Thanks

**Comment by mojtaba-komeili** [comment]
Starting with your second questions, as it has part of the answer to the first one as well. ParlAI help you to have inference using its command line tool. If you want to generate some metrics or examples for a model that already exists in ParlAI, all you need to do is to have your data prepared with a task/teacher, and run it with your model (check out `eval_model` in ParlAI, [link](https://parl.ai/docs/cli_usage.html)).
Now about the first question, the data for training this model comes from [SearchQueryTeacher](https://github.com/facebookresearch/ParlAI/blob/8a97c66b984f9690edbf2d5084f45b787dc485db/parlai/tasks/wizard_of_internet/agents.py#L560). You can see the model text input and output by running
```
parlai display_data --task wizard_of_internet:SearchQueryTeacher
```
You will see that the conversation turns are concatenated into a single string via joining them with `\n` character.
