### ISSUE TITLE
Which Messenger App Type to Choose for Academic Purpose Chatbot?

### ISSUE THREAD

**Issue by Guest400123064** [facebookresearch/ParlAI#4842]
Hi!

I am a student at UPenn working on a chatbot service for academic purposes, and we would like to develop a FB Messenger interface. I initially created an Academic Research app, but it seemed that I could not integrate chat services following the messenger tutorial [here](https://www.parl.ai/docs/tutorial_chat_service.html#facebook-messenger). After some exploration, I could only incorporate chat services with the Business app. I wonder if this is the right app to use for academic purposes. If so, how do I add the Privacy Policy and Terms of Use?

Any suggestion is appreciated!

**Comment by klshuster** [comment]
That's entirely up to you, I don't think we can provide guidance here

**Comment by Guest400123064** [comment]
Ok!
