### ISSUE TITLE
Potential Conflict Between ParlAI and PyTorch 1.13 in `parlai.core.torch_generator_agent.py`

### ISSUE THREAD

**Issue by Guest400123064** [facebookresearch/ParlAI#4869]
**Bug description**
I installed `ParlAI` from source `(v1.7.1)`, `Fairseq (v0.12.2)`, and (with pip) `torch (v1.13)`. When running from the command line `parlai interactive -m bart`, it complaints:

`File "/home/wangy49/Projects/empathic-bot/packages/ParlAI/parlai/core/torch_generator_agent.py", line 1599, in advance self.partial_hyps[path_selection.hypothesis_ids.long()], RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)`

**Reproduction steps**
With the version specified above, run `parlai interactive -m bart`

**Expected behavior**
Expected to start an interactive session with BART.

**Logs**

(Some model downloading and loading logs are not shown here)

```
File "/home/wangy49/Projects/empathic-bot/packages/ParlAI/parlai/core/torch_generator_agent.py", line 1599, in advance self.partial_hyps[path_selection.hypothesis_ids.long()], RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

**Additional context**
Running the code with T4 GPU with `cuda 11.6`

When using `torch (v1.12),` the problem was resolved. First mentioned in the followups in #4031

**Comment by klshuster** [comment]
This is resolved on latest ParlAI
