### ISSUE TITLE
Question: Pass custom context to bb3_30B model

### ISSUE THREAD

**Issue by Tacacs-1101** [facebookresearch/ParlAI#4877]
I am not able to figure out, how can i pass custom context to the blender bot model. I want bb3 to response on the basis of the provided context. currently, I am using this code to get a reply from bb3. 

blender_agent = create_agent(OPT, requireModelExists=True)
blender_agent.observe({'id': ID, 'text': context+query, 'episode_done': True})
response = blender_agent.act()
blender_agent.reset() ###calling this because I want the model to forget everything it has seen in the past, and provide a response only on the basis of provided context.

Any help would be highly appreciated.

**Comment by klshuster** [comment]
What you've provided should work

**Comment by Tacacs-1101** [comment]
but this is giving irrelevant output sometime.

**Comment by Tacacs-1101** [comment]
I am using this message format:
{'id': ID, 'text': query, 'temp_history': memory, 'episode_done': True}
so in this case, memory is some conversation context and query is the created by user. so I want bb3 to continue the conversation from here. Is this the correct way to do it. Please suggest, any help is highly appreciated.

**Comment by klshuster** [comment]
That is the correct way to do it. BB3 should stay on topic most of the time
