### ISSUE TITLE
any idea about add Leaderboards for each task?

### ISSUE THREAD

**Issue by Ravi-Jay** [facebookresearch/ParlAI#489]
It's very hard to re-implement chit-chat models have the same performance like papers on opensubtitle dataset, do you have any idea about users share their pre-trained models or something like leaderboards？

**Comment by jaseweston** [comment]
We plan to do this, but have not got that set up yet, sorry.
For comparing to other chit-chat models, maybe the ubuntu dataset is better
(has more results)?

**Comment by jaseweston** [comment]
Note we do have a leaderboard for Personachat in the personachat competition!!
 http://convai.io/

**Comment by stephenroller** [comment]
Closing this for being stale. We will continue to consider leaderboards on a case-by-case basis.
