### ISSUE TITLE
Could not find pretrained model in parlai.zoo.seeker.seeker_dialogue_3B or parlai.zoo.seeker.build. Please check your spelling and make sure you've pulled from master.

### ISSUE THREAD

**Issue by Dev-hestabit** [facebookresearch/ParlAI#4895]
When running zoo/seeker/seeker_dialogue_3B/model then this error coming
if anyone face this issue and found any solution

**Comment by mojtaba-komeili** [comment]
Could you paste your full command, as you used it here? Then we can try to reproduce it and see what might be wrong.

PS. Also check if have pulled the latest merges from our main branch.
