### ISSUE TITLE
Cannot train RAG-Token to the reported performance in Hallucination Projects

### ISSUE THREAD

**Issue by cathyxl** [facebookresearch/ParlAI#4898]
I cannot reach the reported performance by running the RAG-Token model on the WOW dataset, especially for knowledge F1. I can only achieve KG F1 around 21-22, but the reported is 26-27. Could you give some details about the training strategy? The following command is what I used to train the RAG-Token model.

parlai train_model --model rag --task wizard_of_wikipedia \
	--rag-model-type token --rag-retriever-type dpr --dpr-model-file zoo:hallucination/multiset_dpr/hf_bert_base.cp \
	--indexer-type exact \
	--generation-model bart --init-opt arch/bart_large \
	--batchsize 16 --fp16 True --gradient-clip 0.1 --label-truncate 128 \
	--log-every-n-secs 100 --lr-scheduler reduceonplateau --lr-scheduler-patience 1 \
	--model-parallel True --optimizer adam --text-truncate 512 --truncate 512 \
	--learningrate 1e-05 --validation-metric-mode min --validation-every-n-epochs 0.25 \
	--validation-max-exs 1000 --validation-metric ppl --validation-patience 5 \
	--model-file xxxx_dpr \
	--debug

**Comment by klshuster** [comment]
Hi, could you share your evaluation command? KF1, and generation metrics in general, are heavily influenced by your inference parameters

**Comment by cathyxl** [comment]
Thanks for the quick reply. I just use the Knowledge F1 in the WOW task code, which is defined in the function "custom_evaluation ".  I didn't change any code in wizard_of_wikipedia or in rag.  Just by running the script above, I cannot reach the results shown in the paper. 

Btw, to prove my evaluation is right, I tested the RAG-Token model you provided (
zoo:hallucination/bart_rag_token/model), the results are similar what you reported. Thus I'm curious how you trained the model. Why can't I achieve similar results by running your code?

**Comment by cathyxl** [comment]
Sorry I misunderstood your question. The evaluation command is:

parlai eval_model --model rag --task wizard_of_wikipedia:WizardDialogKnowledgeTeacher:random_split --datatype valid \
--rag-model-type token --rag-retriever-type dpr --dpr-model-file zoo:hallucination/multiset_dpr/hf_bert_base.cp \
--indexer-type exact \
--generation-model bart --init-opt arch/bart_large \
--batchsize 16 --fp16 True --gradient-clip 0.1 --label-truncate 128 \
--log-every-n-secs 100 \
--model-parallel True --text-truncate 512 --truncate 512 \
--model-file $model_file \
--debug

**Comment by klshuster** [comment]
you'll need to match the generation parameters of the zoo model:

```
--inference beam --beam-block-ngram 3 \
--beam-size 3 --beam-min-length 20 
```
