### ISSUE TITLE
support jupyter notebooks

### ISSUE THREAD

**Issue by MannyKayy** [facebookresearch/ParlAI#490]
Considering the growing popularity of notebooks, it would be useful to make ParlAI notebook friendly...

The parser is currently the main component limiting this.

**Comment by alexholdenmiller** [comment]
Hi @MannyKayy -- thanks for the suggestion! I haven't been using a notebook myself, can you give an example of how it's breaking the notebook and we can take a look at updating that?

**Comment by MannyKayy** [comment]
Hi, I actually found the fix to this problem (just pass an empty list to `parse_args()`, i.e. `parse_args([])`) and that gets parlai working in notebooks.
