### ISSUE TITLE
BB2 400M, BB2 3G and BB3 3G only last a few interactions before crashing . . too much for VMs?

### ISSUE THREAD

**Issue by philiprhoades** [facebookresearch/ParlAI#4907]
People,

I have a Fedora 37 i7 desktop with 32GB RAM and only an onboard Intel GPU - but because everything seems to require Ubuntu, I have been creating Docker / Podman VMs to run testings.  I successfully installed the ParlAI image and built the VMs for the above models but after getting to the interactive prompts, they only last one to three pairs of inputs before crashing . . 

I am guessing but the problem(s) could be:

1. A severly underpowered PC ?
2. Too much contention on the network to Meta ?

I tried the online BB3 demo and it was pretty good! - I know that is a 175G model but it would be nice to get something like that going for my use case.  Is that facility available commercially from Meta for FB Messenger?

Anyway, it would be good if I could get something working that looks like it might be able to do what I want (ie create a smart chatbot but WITH intra and inter-session memory  for chatting with members of my Australian non-profits).

Suggestions?

Thanks,
Phil

**Comment by mojtaba-komeili** [comment]
What is the crashing message that you see? It might be anything from the memory to the services trying to reach a non-existing search server. Also I am not sure if you could use the needed GPU capabilities on an Intel GPU (most of the functionalities are only available on limited Nvidia GPUs).

There is no official support for running the 175B parameter model from Meta. But you can try the smaller models (3B version of BlenderBot).

**Comment by philiprhoades** [comment]
> It might be . .  the services trying to reach a non-existing search server.

Yes, that is what I see . .

> most of the functionalities are only available on limited Nvidia GPUs)

I thought that might be the case - would not having a Nvidia GPU precipitate the server problem though?

> But you can try the smaller models (3B version of BlenderBot).

Yes I did that (see the subject of this note) but it only worked once - for one question - and then crashed with the server error again . . all the other times it crashed before answering any questions . . 

Thanks for responding!

**Comment by philiprhoades** [comment]
> My guess is that you do not have enough GPU RAM to handle the model. You could try running the model on CPU but that would be quite a bit slower

I'm sure that doesn't help in terms of the speed but the couple of setups I have done recently with just pyTorch and a CLI have been slow but perfectly stable (is ParlAI a problem?) - but I can't test BB3 with that environment . . it would be nice if it was available soon . .

**Comment by klshuster** [comment]
it would be good to see the exact error message you are receiving
