### ISSUE TITLE
What is the license for BB2 and BB3 models?

### ISSUE THREAD

**Issue by akinoriosamura** [facebookresearch/ParlAI#4908]
Hi!

Are the BB2 and BB3 models for research purposes only? Or is it MIT license?

Thanks for the nice project.

Osam

**Comment by klshuster** [comment]
BB2 models are released under the MIT license; BB3 models are released under the [BB3 license](https://github.com/facebookresearch/ParlAI/blob/main/parlai/zoo/bb3/MODEL_LICENSE.md)
