### ISSUE TITLE
How to load blenderbot_30B model?

### ISSUE THREAD

**Issue by mandar-mp** [facebookresearch/ParlAI#4909]
Hi, I have downloaded [consolidated.pt](http://consolidated.pt/) file for blenderbot_30B model and parlai python library. I want to load this model and run it so that i can chat with the model. i am not finding any python code to run this model. i found the code for blenderbot_3B on huggingface but not for 30B. could you please help on how to run blenderbot30B model?

Please suggest.

**Comment by klshuster** [comment]
[The project page](https://parl.ai/projects/bb3/) describes how to run the blenderbot_30B model using the [metaseq library](https://github.com/facebookresearch/metaseq)
