### ISSUE TITLE
UnicodeDecodeError's

### ISSUE THREAD

**Issue by MannyKayy** [facebookresearch/ParlAI#491]
I am getting a series of encoding errors when using ParlAI.

The first is encountered when initially setting ParlAI up which there is a fix #488 : 
![image](https://user-images.githubusercontent.com/7952854/34644758-9fe260e8-f334-11e7-832c-a00b1d651d7e.png)

The rest are encountered on most datasets when using the `display_data.py` to load some examples.

I have created a [Dockerfile](https://gist.github.com/MannyKayy/82c6ae9875db7095ff443a699d4007ef) that can be used to reproduce these errors.

1. To build the docker image:
`docker build -t parlai -f ParlAI_Dockerfile . `

2. To run the container:
`docker run --rm -it parlai bash`

3. The Dockerfile is setup to load you into ParlAI folder, from there you can observe all the encoding errors:
`python setup.py develop`

**Comment by JackUrb** [comment]
@MannyKayy Alright first to ensure that this is something easily solvable by being explicit with encodings during reads, can you run the `display_data` task with the PYTHONIOENCODING environment variable set, as in `PYTHONIOENCODING=utf-8 python3 display_data.py -t squad -n 2`?

**Comment by MannyKayy** [comment]
Hi @JackUrb ,

Thanks for the quick response. Yep, #488 and setting the pythonioencoding environment variable fix the decoding errors.

I have rolled them up into a working [Dockerfile](https://gist.github.com/MannyKayy/82c6ae9875db7095ff443a699d4007ef) for ParlAI. I can make a pull request if you want to include the docker container within ParlAI.

**Comment by MannyKayy** [comment]
It seems that the suggested fix only works for certain types of decoding errors, which defer depending on the dataset.

For example:

SQuAD:

Decoding error:
![image](https://user-images.githubusercontent.com/7952854/34695797-19463fd2-f4c4-11e7-92f3-df57ba39dbd7.png)

Setting pythonioencoding fixes it:
![image](https://user-images.githubusercontent.com/7952854/34695866-6431b17a-f4c4-11e7-89a4-063353793ebd.png)

SimpleQuestions:

Decoding error (plus a missing attribute error):
![image](https://user-images.githubusercontent.com/7952854/34695953-bb4953f0-f4c4-11e7-9302-8781e4c90ef2.png)

setting pythonioencoding **doesn't** fix it:
![image](https://user-images.githubusercontent.com/7952854/34696015-fc55fb6e-f4c4-11e7-8eb2-9ac86875363e.png)

**Comment by alexholdenmiller** [comment]
Hi @MannyKayy, yeah the pythonioencoding param for some reason doesn't adjust all of Python's codec settings, can you try with `LANG=en_US.UTF-8`?

**Comment by MannyKayy** [comment]
@alexholdenmiller yep that was the issue... found a [related fix](https://webkul.com/blog/setup-locale-python3/) that works for all the datasets tested.

Thanks !
