### ISSUE TITLE
ROSCOE: Download human annotated data script not working

### ISSUE THREAD

**Issue by archiki** [facebookresearch/ParlAI#4914]
**Description**
@Golovneva  As per the instructions, human annotated data can be downloaded and processed by running `bash projects/roscoe/roscoe_data/download_annotated.sh`.  However, [annotations.zip](https://dl.fbaipublicfiles.com/parlai/projects/roscoe/annotations.zip) contains no folder called `annotation_release` as expected by the script. It only contains `annotated_data` and has `.json` files.  Correspondingly, `restore_annotated.py` also fails as it expects `<dataset>_reasoning.txt` files in `./projects/roscoe/roscoe_data/generated/` which are not available.

**Trace of the error**
```
Traceback (most recent call last):
  File "/playpen-ssd/archiki/Reasoning/ParlAI/./projects/roscoe/roscoe_data/restore_annotated.py", line 381, in <module>
    main(opt)
  File "/playpen-ssd/archiki/Reasoning/ParlAI/./projects/roscoe/roscoe_data/restore_annotated.py", line 325, in main
    parse_drop(input_file, model_output_reasoning, save_file)
  File "/playpen-ssd/archiki/Reasoning/ParlAI/./projects/roscoe/roscoe_data/restore_annotated.py", line 33, in parse_drop
    with open(reasoning, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './projects/roscoe/roscoe_data/generated/drop_reasoning.txt'
```

**Comment by Golovneva** [comment]
Thank you for reporting the issue!
I have updated the dataset with the right structure, and the script worked on my side:

```
>> sh projects/roscoe/roscoe_data/download_annotated.sh
wget: /public/apps/anaconda3/2020.11/lib/libuuid.so.1: no version information available (required by wget)
--2022-12-16 12:04:38--  https://dl.fbaipublicfiles.com/parlai/projects/roscoe/annotations.zip
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 104.22.75.142, 104.22.74.142, 172.67.9.4, ...

...

Saved DROP dataset in ./projects/roscoe/roscoe_data/generated/drop.json
Saved E-SNLI dataset in ./projects/roscoe/roscoe_data/generated/esnli.json
Saved COSMOSQA dataset in ./projects/roscoe/roscoe_data/generated/cosmos.json
Saved GSM8K dataset in ./projects/roscoe/roscoe_data/generated/gsm8k.json
```

Please, let me know if it worked for you.

**Comment by archiki** [comment]
I am still getting the same error, can you share the updated link of the dataset?

**Comment by Golovneva** [comment]
No, I did not change any code, I just updated the dataset and re-run the command, but I was running from a local copy of the archived data, and my previous data push failed, sorry about that.
I have re-uploaded the dataset (2022-12-16 12:49:33     188880 annotations.zip), removed all local data and re-run the command. It worked.

**Comment by archiki** [comment]
Thanks, it works now!
