### ISSUE TITLE
--init-model of SeeKeR Dialogue Training

### ISSUE THREAD

**Issue by joemzhao** [facebookresearch/ParlAI#4917]
Hi, thanks for the great work!

When training SeeKeR on dialog datasets, it seems the --init-model is zoo:seeker/r2c2_blenderbot_3B/model (https://parl.ai/projects/seeker/ "Train your own SeeKeR")

But  zoo:seeker/r2c2_blenderbot_3B/model seems already finetuned on BST (according to model zoo "R2C2 Blenderbot 3Bm").

According to the SeeKeR paper, I was expecting the --init-model is the pretrained model without BST finetuning, zoo:seeker/r2c2_base_3B/model. Or am I misunderstanding something?

Thank you!

**Comment by klshuster** [comment]
We found the model to be more engaging when fine-tuned on BST prior to fine-tuning on the SeeKeR tasks, so the instructions are indeed correct

**Comment by joemzhao** [comment]
Thank you @klshuster for the reply!
