### ISSUE TITLE
BB3-30b repetition problems 🔁

### ISSUE THREAD

**Issue by volkerha** [facebookresearch/ParlAI#4919]
**Bug description**
After several turns (about 10 on average) I get severe repetition issues with BB3-30b. The repetitions are often literal copies of previous bot responses. Once the bot starts repeating itself, it often gets stuck in a loop. In my specific setup, I actually feed a persona, as memories, to the agent before the first turn.

**Reproduction steps**
1. Start BB30 model in API
2. Start BB30 agent in ParlAI, inject memories, act
```
import copy
import json
from parlai.core.agents import create_agent

config_path = "path_to_bb3_opt_file"
with open(config_path, 'r') as f:
    opt = json.load(f)

opt_override = copy.deepcopy(opt)
opt['override'] = opt_override

agent = create_agent(opt, requireModelExists=False)
agent.get_opening_memories(["My name is Sally", "I work as a dolphin trainer"])

user_input = "Hi!"
agent.observe(user_input)
response = agent.act()
```

Some notes:
* Repetition does not occur in every session but relatively often
* The persona details provided here are just an example (I actually use more persona details)
* The provided example is provided to confirm the general correctness of my implementation. To reproduce the repetition issue, several lines of interaction are necessary.

**Expected behavior**
Less repetition. Especially literal repetitions and repetition loops.

❓ Assuming the implementation is correct, is there a way to reduce repetition through ParlAI decoding parameters?

**Comment by klshuster** [comment]
For BB3 we make use of repetition penalties akin to those described in the OpenAI API

There is an [open PR in metaseq](https://github.com/facebookresearch/metaseq/pull/306) to include these in the main codebase: 

These penalties are controlled by a few parameters, which you can edit in the [opt preset file](https://github.com/facebookresearch/ParlAI/blob/main/parlai/opt_presets/gen/opt_bb3.opt); essentially, anywhere you see a `rm` model, e.g. the `srm`, you have access to the following parameters ([defined in this file](https://github.com/facebookresearch/ParlAI/blob/3f70d6b0979934c7597b34baad3b76eb86b64c74/projects/bb3/agents/opt_api_agent.py#L230-L294)):

```python
        parser.add_argument(
            '--penalize-repetitions',
            default=False,
            type='bool',
            help="""
                Penalize repetitions according to heuristics put forth by OpenAI
                From https://beta.openai.com/docs/api-reference/engines/retrieve:

                mu[j] -> mu[j] - c[j] * alpha_frequency - float(c[j] > 0) * alpha_presence
                Where:

                mu[j] is the logits of the j-th token
                c[j] is how often that token was sampled prior to the current position
                float(c[j] > 0) is 1 if c[j] > 0 and 0 otherwise
                alpha_frequency is the frequency penalty coefficient
                alpha_presence is the presence penalty coefficient
            """,
        )
        parser.add_argument(
            '--penalize-ctxt-repetitions',
            default=False,
            type='bool',
            help='apply repetition blocking heuristics to context as well.',
        )
                parser.add_argument(
            '--alpha-presence',
            default=0.5,
            type=float,
            help='penalty applied to the logits for presence of previous tokens in the generation',
        )
        parser.add_argument(
            '--alpha-frequency',
            default=0.5,
            type=float,
            help='penalty applied to the logits for frequency of previous tokens in the generation',
        )
        parser.add_argument(
            '--alpha-presence-src',
            default=0.5,
            type=float,
            help='penalty applied to the logits for presence of previous tokens in the context',
        )
        parser.add_argument(
            '--alpha-frequency-src',
            default=0.5,
            type=float,
            help='penalty applied to the logits for frequency of previous tokens in the context',
        )
```

to use these, simply add e.g., `srm_<param>` to your opt file
