### ISSUE TITLE
BlenderBot - ModuleNotFoundError: No module named 'torch.distributed.algorithms.join'

### ISSUE THREAD

**Issue by eclipt69** [facebookresearch/ParlAI#4920]
Giving me this error when I try to run the following command: 
interactive.py -t blended_skill_talk -mf zoo:blender/blender_400Mdistill/model
(I placed a copy of the interactive script in the project's "main" folder (ParlAI)

**Comment by klshuster** [comment]
you may need to upgrade your pytorch version
