### ISSUE TITLE
BB3 killed after creating search engine retriever

### ISSUE THREAD

**Issue by OmarJay1** [facebookresearch/ParlAI#4921]
Hello, I'm trying to run an example instance from the BB3 project.

It gives a lot of messages, but then reports that it was "Killed" after messages on the search engine retriever.

This is my first pass at trying to run a ParlAI model, so my apologies if I sound ignorant.

Thanks.

parlai safe_interactive --model-file zoo:bb3/bb3_3B/model --init-opt gen/r2c2_bb3

.....

07:51:51 | Using CUDA
07:51:51 | loading dictionary from /home/omar/.local/lib/python3.8/site-packages/data/models/bb3/bb3_3B/model.dict
07:51:51 | num words = 50264
07:51:52 | BB3SubSearch: full interactive mode on.
/home/omar/.local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/x509.py:14: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  warnings.warn(
07:51:56 | Loading search generator model
07:51:56 | Search query generator model loading completed!
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
07:52:03 | Creating the search engine retriever.
07:52:03 | No protocol provided, using "http://"
Killed

**Comment by klshuster** [comment]
You may be running out of RAM; what system are you running this on?

**Comment by OmarJay1** [comment]
Thanks @klshuster, that was the problem.  I'm running in WSL2 on Windows 11, and I didn't know that it defaults to only 8 GB of memory for instances.  I switched to 16 GB and it worked.

Thanks.

**Comment by klshuster** [comment]
Great! Closing as resolved, please reopen if you run into any further issues
