### ISSUE TITLE
How Could I download prior version of Personachat dataset?

### ISSUE THREAD

**Issue by JHjang223** [facebookresearch/ParlAI#4922]
thanks for implementation of ParlAI.

i want to download old version of personachat dataset. (train set have 10,981 dialogues, 164,356 utterances, writted in [https://arxiv.org/pdf/1801.07243v3.pdf ] .)

i tried parlai display_data -t personachat but Only Newly version could be downloaded. (equal Convai2 train dataset distribution)

i can't find it anywhere.

help me please.

**Comment by klshuster** [comment]
I'm not sure what you mean -- the command you have is the correct one to download the personachat dataset. In the paper, it is noted that there are 10,981 *total* dialogues, with 968 set aside for the valid set and 1000 for the test set
