### ISSUE TITLE
Installing blenderbot 2 on a cloud server such as AWS Sagemaker g4dn.12xlarge

### ISSUE THREAD

**Issue by justlearntutors** [facebookresearch/ParlAI#4926]
Use this to open other questions or issues, and provide context here.
Do you have any docs on how to install blenderbot 2 on a cloud server such as AWS Sagemaker g4dn.12xlarge

**Comment by mojtaba-komeili** [comment]
Depends on what you mean by installing? If you have access to the EC2 instance, you may just install ParlAI there and use it with BlenderBot 2, or any other agent. If you are planning to have interactive sessions with it, ParlAI offers a minimal web interface ([link](https://github.com/facebookresearch/ParlAI/blob/main/parlai/scripts/interactive_web.py)). But you may need to do some custom work to build your server. 
In either case, using the [ParlAI Docker image](https://parl.ai/docs/tutorial_docker.html) might be helpful to reduce the trouble with system setup.
