### ISSUE TITLE
Seeker - Confused About How To Run --search-server

### ISSUE THREAD

**Issue by ericborgos** [facebookresearch/ParlAI#4927]
I would like to use Seeker with my own external text corpus (such as Wikipedia). I have the Wikipedia files locally on my server, but could make that part run as an API on a port if needed.  But I am still unclear as to how to make it work. 

First, when I run this (in Goolge Colab) as a test with no search server:
!parlai i -mf zoo:seeker/seeker_lm_xl/model -o gen/seeker_lm --search-decision never
I get an error saying it needs a search server ("ValueError: Must provide a valid server for search"). 
But that is fine as I want to use a search server anyhow.

So if I then add a search server like:
!parlai i -mf zoo:seeker/seeker_lm_xl/model -o gen/seeker_lm --search-server http://127.0.0.1:1234/
how do I format the Wikipedia feed from my API for use in Seeker?

And, how instead do I just reference the search server corpus locally instead of using an actual search server?

**Comment by mojtaba-komeili** [comment]
You need to have your server implement the API required by [retriever_api](https://github.com/facebookresearch/ParlAI/blob/main/parlai/agents/rag/retrieve_api.py). Checking the functions in this file should help you with that.
