### ISSUE TITLE
How to setup search-server? --search-server ${RELEVANT_SEARCH_SERVER}

### ISSUE THREAD

**Issue by justlearntutors** [facebookresearch/ParlAI#4928]
Use this to open other questions or issues, and provide context here.

parlai interactive -mf zoo:blenderbot3/blenderbot3_175B/model --search-server ${RELEVANT_SEARCH_SERVER}

Do you have any docs or libary or info on how to setup the search server?

**Comment by Dev-hestabit** [comment]
https://github.com/JulesGM/ParlAI_SearchEngine

i am using this repo for creating search server and it is working fine.
