### ISSUE TITLE
Licence commercial

### ISSUE THREAD

**Issue by justlearntutors** [facebookresearch/ParlAI#4929]
Use this to open other questions or issues, and provide context here.
The license for ParlAI is MIT. Can I use blenderbot3 and opt in my commercial app?

**Comment by klshuster** [comment]
The BB3 models are released under the [BB3 Model License](https://github.com/facebookresearch/ParlAI/blob/main/parlai/zoo/bb3/MODEL_LICENSE.md), which specifies only research, non-commercial uses
