### ISSUE TITLE
chat service Agent context/memory Save

### ISSUE THREAD

**Issue by Dev-hestabit** [facebookresearch/ParlAI#4932]
Hello,
i am running BB3 on server using chat Service and implementing multiple user chat using its client script but i want to save agent context so that user can continue chat after reopening that script, i am not able to save context or Memory Knowledge so that i can assign new agent and pass that context or memory to the new agent.

**Comment by mojtaba-komeili** [comment]
Agent memories are part of the response message that it generates. You need to modify the chat service to extract the memory part of the message that BB3 generates and store that somewhere. You also need to have retrieval mechanism to update the internal memory of BlenderBot after users return. Having a closer look at the internals of the agent helps you figure out the details of how memory works, and how to inject external memories.

**Comment by klshuster** [comment]
every output message from bb3 contains the full set of memories available to the agent; you can inspect the resulting message from `agent.act()` to extract the memories
