### ISSUE TITLE
BB3 3B - missing tasks?

### ISSUE THREAD

**Issue by krisstud** [facebookresearch/ParlAI#4937]
**Bug description**
Please enter a clear and concise description of what the bug is.

**Reproduction steps**
Clean pip install of parlai (today), cuda 11.7 - then follow guide to train BB3 3B - or
Clean git clone of parlai repo + provided script installer, cuda 11.7 - then follow guide to train BB3 3B:

python3 -m parlai.scripts.multiprocessing_train -t $TASKS -et $EVAL_TASKS -vstep 1000 -lstep 50 --batchsize 1 --init-opt arch/r2c2_base_3B --init-model zoo:seeker/r2c2_blenderbot_3B/model --model projects.seeker.agents.seeker:ComboFidGoldDocumentAgent --n-docs 5 --text-truncate 1024 --label-truncate 128 --truncate 1024 --fp16 True -lr 1e-06 --lr-scheduler reduceonplateau --lr-scheduler-patience 3 --optimizer adamw --save-after-valid True --warmup-updates 100 --update-freq 1 --gradient-clip 1.0 --skip-generation True --dropout 0.1 --attention-dropout 0.0 -vp 10 -vmt ppl -vmm min -vme 100000 --load-from-checkpoint true --ddp-backend zero2 --checkpoint-activations true --model-file /home/username/path/

**Expected behavior**
Training starts

**Logs**
Please paste the command line output:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/username/.local/lib/python3.10/site-packages/parlai/scripts/multiprocessing_train.py", line 110, in <module>
    MultiProcessTrain.main()
  File "/home/username/.local/lib/python3.10/site-packages/parlai/core/script.py", line 129, in main
    return cls._run_args(None)
  File "/home/username/.local/lib/python3.10/site-packages/parlai/core/script.py", line 100, in _run_args
    opt = parser.parse_args(args=args)
  File "/home/username/.local/lib/python3.10/site-packages/parlai/core/params.py", line 1169, in parse_args
    self.add_extra_args(args)
  File "/home/username/.local/lib/python3.10/site-packages/parlai/core/params.py", line 943, in add_extra_args
    self.add_task_args(evaltask, partial)
  File "/home/username/.local/lib/python3.10/site-packages/parlai/core/params.py", line 849, in add_task_args
    agent = load_teacher_module(t)
  File "/home/username/.local/lib/python3.10/site-packages/parlai/core/loader.py", line 298, in load_teacher_module
    teacher_class = getattr(task_module, teacher)
AttributeError: module 'projects.bb3.tasks' has no attribute 'WoiSearchQueryTeacher'
```

**Additional context**
If i replace the environment variable with another task, i get an error for that one being missing.

**Comment by krisstud** [comment]
When trying to install via git clone and install script python3 setup.py develop:

```
Processing dependencies for parlai==1.7.1
Searching for sphinxcontrib-jquery>=3.0.0
Reading https://pypi.org/simple/sphinxcontrib-jquery/
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: jquery-1.0.0 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: jquery-2.0.0 is an invalid version and will not be supported in a future release
  warnings.warn(
No local packages or working download links found for sphinxcontrib-jquery>=3.0.0
error: Could not find suitable distribution for Requirement.parse('sphinxcontrib-jquery>=3.0.0')
```

**Comment by klshuster** [comment]
could you please list your $TASKS variable?

**Comment by krisstud** [comment]
Thank you for replying! 

I see that i was imprecise in my first report. I think this is related to the EVAL_TASKS, because if i remove eval from the command it will start downloading base models etc.

I have tried this example [bb3-3b-model-training](https://github.com/facebookresearch/ParlAI/tree/main/projects/bb3#bb3-3b-model-training)
:
`:~$ echo $TASKS
projects.bb3.tasks.module_level_tasks:AlwaysSearchTeacher,projects.bb3.tasks.module_level_tasks:MaybeSearchTeacher,projects.bb3.tasks.module_level_tasks:MemoryDecisionTeacher,projects.bb3.tasks.module_level_tasks:SearchQueryGenerationTeacher,projects.bb3.tasks.module_level_tasks:MemoryGenerationTeacher,projects.bb3.tasks.module_level_tasks:MemoryKnowledgeGenerationTeacher,projects.bb3.tasks.module_level_tasks:SearchKnowledgeGenerationTeacher,projects.bb3.tasks.module_level_tasks:EntityKnowledgeGenerationTeacher,projects.bb3.tasks.module_level_tasks:SearchDialogueGenerationTeacher,projects.bb3.tasks.module_level_tasks:EntityDialogueGenerationTeacher,projects.bb3.tasks.module_level_tasks:MemoryDialogueGenerationTeacher,projects.bb3.tasks.module_level_tasks:VanillaDialogueGenerationTeacher`

I can change the task variable, but it will yield the exact same result:
`:~$ echo $TASKS
projects.bb3.tasks.module_level_tasks:VanillaDialogueGenerationTeacher
`
 
I think it's related to the EVAL_TASKS, because if i remove them, the download of base models etc. start:
`python -m parlai.scripts.multiprocessing_train -t $TASKS -vstep 1000 ..
`

The content of EVAL_TASKS is:
`:~$ echo $EVAL_TASKS
projects.bb3.tasks:WoiSearchQueryTeacher,projects.bb3.tasks:MSCMemoryGeneratorTeacher,projects.bb3.tasks:MSCMemoryKnowledgePersOverlapTeacher,projects.bb3.tasks:Convai2MemoryKnowledgePersOverlapTeacher,projects.bb3.tasks:WoiSearchKnowledgeTeacher,projects.bb3.tasks:WowSearchKnowledgeTeacher,projects.bb3.tasks:Convai2EntityKnowledgeTeacher,projects.bb3.tasks:WowSearchDialogueTeacher,projects.bb3.tasks:WoiSearchDialogueTeacher,projects.bb3.tasks:EDEntityDialogueTeacher,projects.bb3.tasks:BSTEntityDialogueTeacher,projects.bb3.tasks:BSTEntityDialogueTeacher,projects.bb3.tasks:MSCMemoryDialogueFromPersOverlapTeacher,projects.bb3.tasks:Convai2MemoryDialogueFromPersOverlapTeacher,projects.bb3.tasks:FitsSearchDialogueTeacher,projects.bb3.tasks:SaferdialoguesVanillaDialogueTeacher,projects.bb3.tasks:GoogleSgdSearchDialogueTeacher,projects.bb3.tasks:LightVanillaDialogueTeacher
`

If i change the EVAL_TASKS variable to just contain  the last eval task (projects.bb3.tasks:LightVanillaDialogueTeacher) i still get the same error, just referencing another task:

`:~$ python -m parlai.scripts.multiprocessing_train -et $EVAL_TASKS -vstep 1000 -lstep 50 --batchsize 1 --init-opt arch/r2c2_base_3B --init-model zoo:seeker/r2c2_blenderbot_3B/model --model projects.seeker.agents.seeker:ComboFidGoldDocumentAgent --n-docs 5 --text-truncate 1024 --label-truncate 128 --truncate 1024 --fp16 True -lr 1e-06 --lr-scheduler reduceonplateau --lr-scheduler-patience 3 --optimizer adamw --save-after-valid True --warmup-updates 100 --update-freq 1 --gradient-clip 1.0 --skip-generation True --dropout 0.1 --attention-dropout 0.0 -vp 10 -vmt ppl -vmm min -vme 100000 --load-from-checkpoint true --ddp-backend zero2 --checkpoint-activations true --model-file /path/to/model/`

`Traceback (most recent call last):
  File "/home/user/anaconda3/envs/parlai1/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/anaconda3/envs/parlai1/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/ParlAI/parlai/scripts/multiprocessing_train.py", line 113, in <module>
    MultiProcessTrain.main()
  File "/data/ParlAI/parlai/core/script.py", line 129, in main
    return cls._run_args(None)
  File "/data/ParlAI/parlai/core/script.py", line 100, in _run_args
    opt = parser.parse_args(args=args)
  File "/data/ParlAI/parlai/core/params.py", line 1169, in parse_args
    self.add_extra_args(args)
  File "/data/ParlAI/parlai/core/params.py", line 943, in add_extra_args
    self.add_task_args(evaltask, partial)
  File "/data/ParlAI/parlai/core/params.py", line 849, in add_task_args
    agent = load_teacher_module(t)
  File "/data/ParlAI/parlai/core/loader.py", line 298, in load_teacher_module
    teacher_class = getattr(task_module, teacher)
AttributeError: module 'projects.bb3.tasks' has no attribute 'LightVanillaDialogueTeacher'`

I can also just reference one eval task directly for same result:
`python -m parlai.scripts.multiprocessing_train -et projects.bb3.tasks:LightVanillaDialogueTeacher -vstep 1000 ..
...
File "/data/ParlAI/parlai/core/loader.py", line 298, in load_teacher_module
    teacher_class = getattr(task_module, teacher)
AttributeError: module 'projects.bb3.tasks' has no attribute 'LightVanillaDialogueTeacher'
`

I received the same error on two different systems with two different python environments (not conda imports or installed using pip requirements from the other).

**Comment by klshuster** [comment]
for specifying eval tasks directly, you need to use `projects.bb3.tasks.r2c2_<TASK_TYPE>:TaskName`

So, rather than `projects.bb3.tasks:LightVanillaDialogueTeacher`, you need `projects.bb3.tasks.r2c2_dialogue_tasks:LightVanillaDialogueTeacher`, and so on

**Comment by krisstud** [comment]
Thank you. Specifying directly works as expected.

**Comment by krisstud** [comment]
I assume specifying training tasks directly would be achieved in the same way?

**Comment by klshuster** [comment]
What are your environment variables? you can feel free to use those, but as I said, the tasks must be specified appropriately
