### ISSUE TITLE
Integrating SearchServer, Persona to blended_skill_talk

### ISSUE THREAD

**Issue by benihime91** [facebookresearch/ParlAI#4939]
Hi, I want to create a open-domain chatbot something similar to `blended_skill_talk` task. I want to have the following features -

1. Ability for the model to access internet to query and fetch latest information on questions like (Who is president of India?)
<img width="861" alt="image" src="https://user-images.githubusercontent.com/52747515/216252044-c12fbd3f-6346-44cd-a8a0-b12f8fbd9a74.png">
So for these kinds of questions the model should query the internet and fetch the answer.

2. Ability to add custom persona to the model so that I can controal to a degree how the models responds. (For example I want my chatbot to always respond in a positive manner & it should always initiate conversation)

3. I want the chatbot to recall information that I tell it. For now the model cannot recall (screenshot attached)
<img width="811" alt="image" src="https://user-images.githubusercontent.com/52747515/216251638-0db28763-3598-4c3e-8a93-0c6872e763ec.png">
to reproduce  -

```bash
$python parlai/scripts/safe_interactive.py -t blended_skill_talk -mf zoo:blender/blender_90M/model --include-initial-utterances True --include-personas True
```
Could point me towards how I could go about tacklinng these issues ? Thanks.

**Comment by mojtaba-komeili** [comment]
You are using BlenderBot 1 here, which doesn't have all those things that you asked for. Try BlenderBot 2, or 3. They match what you need better.

**Comment by klshuster** [comment]
Indeed, both [blenderbot 2](https://parl.ai/projects/blenderbot2/) and [blenderbot 3](https://parl.ai/projects/bb3/) handle what you've described

**Comment by benihime91** [comment]
I went through the bb2 and bb3. I have seen that internet search and memory recall can be integrated in bb3 via  https://github.com/facebookresearch/ParlAI/tree/main/projects/bb3/agents . But I could not find the appropriate document for the same features for bb2 and bb1. 
Am i right to assume that :
- bb2/bb1 does not have internet search
- bb2/bb1 does not have memory recall
If no can you please point me to the appropriate documentation

**Comment by benihime91** [comment]
Hi I tried using bb2, but still facing the same problem of the model not being able to recall information (screenshot attached below). Instead it's giving erratic answers 😄 

To reproduce
```bash
$ python -m parlai.scripts.safe_interactive --task convai2 -mf zoo:blenderbot2/blenderbot2_400M/model --model-file zoo:blenderbot2/blenderbot2_400M/model --search-server None --knowledge-access-method memory_only --inference topk --beam-min-length 15 --beam-length-penalty 1.2 --loglevel debug
```
<img width="1637" alt="image" src="https://user-images.githubusercontent.com/52747515/218982789-5774fe16-5d16-49dd-b365-d70d72dddd29.png">

**Comment by mojtaba-komeili** [comment]
To answer your old question, that you figured out at this point, BB2 has long term memory and uses external (eg internet) search. But BB1 does not.
And about your last question, having the capability of memory access and internet search does not guarantee that these models utilize them efficiently. This is in fact an existing challenge for the chatbots.

**Comment by benihime91** [comment]
Thanks for the clarification.
