### ISSUE TITLE
Error：'DialogPartnerWorld' object is not iterable

### ISSUE THREAD

**Issue by piekey1994** [facebookresearch/ParlAI#494]
when i execute python3 memnn_luatorch_cpu/full_task_train.py -t babi:task10k:1 -nt 8
i got the error message:
......
Setting up dictionary.
[creating task(s): babi:task10k:1]
[loading fbdialog data:/home/piekey/ParlAI/data/bAbI/tasks_1-20_v1-2/en-valid-10k-nosf/qa1_train.txt]
Dictionary building on training data.
Traceback (most recent call last):
  File "memnn_luatorch_cpu/full_task_train.py", line 114, in <module>
    main()
  File "memnn_luatorch_cpu/full_task_train.py", line 64, in main
    for _ in world_dict:
TypeError: 'DialogPartnerWorld' object is not iterable

**Comment by klshuster** [comment]
Closing for now, as this has been fixed by #495 - feel free to reopen if you have any more problems!
