### ISSUE TITLE
How to finetune a model with our dataset?

### ISSUE THREAD

**Issue by txy77** [facebookresearch/ParlAI#4940]
Hey, guys! I plan to finetune the seeker module with our own dataset, how could I use your toolkit to load our dataset and finetune the model? Could you please help me?

**Comment by mojtaba-komeili** [comment]
You need to [create your own task/teacher](https://parl.ai/docs/tutorial_task.html) in ParlAI that has all the fields that SKR model needs. For that you can have a look at the tasks that SKR was trained on [here](https://parl.ai/projects/seeker/) and replicate those teachers for your own task. Then runs it with the training command in the latter link.

**Comment by txy77** [comment]
Thank you for your help!



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 02/08/2023 00:16 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [facebookresearch/ParlAI] How to finetune a model with our dataset? (Issue #4940) |

You need to create your own task/teacher in ParlAI that has all the fields that SKR model needs. For that you can have a look at the tasks that SKR was trained on here and replicate those teachers for your own task. Then runs it with the training command in the latter link.
