### ISSUE TITLE
Questions about Wizard of Wikipedia history

### ISSUE THREAD

**Issue by min942773** [facebookresearch/ParlAI#4945]
Hi. I have some questions about "history" which is used as input along with the current turn before a new episode starts.

When training a model with Wizard of Wikipedia dataset, does the knowledge previously used as input remain in the history of the model (which can be found as `history.get_history_vec()`)? Or is knowledge not included in history? If not, in which code does that processing occur?

I would appreciate it if you let me know.
Thank you!

**Comment by klshuster** [comment]
what model are you training?

if you are using the gold documents prepended task, yes, the knowledge is saved in the history

**Comment by min942773** [comment]
Thank you for the reply. 

I am using the bart model, and I am looking for a way to ensure that knowledge is not included in history. 
Is there any method to ensure that the model gets knowledge as input but does not include it in the history? 
If I use `only-checked-knowledge`, is checked knowledge not included in the history? Can you let me know where can I find the code?

Thank you!

**Comment by klshuster** [comment]
if you use the `flatten` mutator with the training task, this will make sure that each example is it's own "episode", and thus multiple pieces of knowledge will not be saved to the agent's history 

simply set `--mutators flatten`
