### ISSUE TITLE
Persona/Memory Extraction model using dialog context as input.

### ISSUE THREAD

**Issue by mailong25** [facebookresearch/ParlAI#4952]
I wonder if there's a model that extracts the speaker persona based on the dialog context.

The current persona extraction model from BB2 and BB3 seen to use only the last utterance for the extraction, which might not be enough.

For example:
```
Human: My mother is a teacher.
Bot: How old is she?
Human: She is 40 years old.
```
If we use the last utterance "She is in her thirty", then there will be no persona.
However, the extracted persona would be "My mother is  40 years old." if we use the entire dialog context.

Another example:
```
Human: I like Japan.
Bot: Have you ever been there?
Human: No, I have not.
```

**Comment by klshuster** [comment]
This was trained on the `msc:PersonaSummaryTeacher` task
