### ISSUE TITLE
Error when reproducing dailydialog task folds: missing files

### ISSUE THREAD

**Issue by amrohendawi** [facebookresearch/ParlAI#4953]
I am trying to reproduce the folds for the dailydialog task by running `parse.py` in `parlai/tasks/dailydialog`, however, I am encountering the following error:

```bash
C:\Users\ahe\Desktop\Thesis\parlai_venv\Scripts\python.exe C:\Users\ahe\Desktop\ParlAI\parlai\tasks\dailydialog\parse.py 
Traceback (most recent call last):
  File "C:\Users\ahe\Desktop\ParlAI\parlai\tasks\dailydialog\parse.py", line 89, in <module>
    with PathManager.open('topicmap') as f_tm:
  File "C:\Users\ahe\Desktop\Thesis\parlai_venv\lib\site-packages\iopath\common\file_io.py", line 1062, in open
    bret = handler._open(path, mode, buffering=buffering, **kwargs)  # type: ignore
  File "C:\Users\ahe\Desktop\Thesis\parlai_venv\lib\site-packages\iopath\common\file_io.py", line 645, in _open
    return open(  # type: ignore
FileNotFoundError: [Errno 2] No such file or directory: 'topicmap'
```

Additionally, there is no documentation on where to get the dailydialog dataset. I had to discover it myself from [the official link](http://yanran.li/dailydialog). Can you please provide more information on how to obtain the missing file `topicmap` and fix the error when running parse.py?

**Comment by klshuster** [comment]
Hi there, per the doc string in the parse file:
```
This preprocessing script was used to create ParlAI's version of the data.

It was run in a script called parse.py inside ijcnlp_dailydialog/ after uncompressing
the original directory and all subdirectories.
```

is the topicmap file not in the official dataset download?

**Comment by amrohendawi** [comment]
> Hi there, per the doc string in the parse file:
> 
> ```
> This preprocessing script was used to create ParlAI's version of the data.
> 
> It was run in a script called parse.py inside ijcnlp_dailydialog/ after uncompressing
> the original directory and all subdirectories.
> ```
> is the topicmap file not in the official dataset download?
> 
> 

No it's not. That's what I am missing.

**Comment by klshuster** [comment]
Ok, unfortunately I cannot help you then, as that seems to be an issue with the original dataset download
