### ISSUE TITLE
I want to use chat_service to run bb3_3B,What config.yml can i use? 

### ISSUE THREAD

**Issue by LONNIESAN** [facebookresearch/ParlAI#4955]
this is my config.yml.I think it's has some error.can you give me some solutions?

tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    bb3_3B:
      model: transformer/generator
      model_file: zoo:bb3/bb3_3B/model
      interactive_mode: True
      no_cuda: True
additional_args:
  page_id: 1 # Configure Your Own Page

**Comment by klshuster** [comment]
please share your exact error; I also suggest searching through the issues as several other folks have managed to run this model with a chat service config

**Comment by LONNIESAN** [comment]
hi, when I use the bb3 model to chat with bot.After 5-10mins,i get the error message,  is there any solution to help me fix this 
issue?

attn_weights = F.softmax(
RuntimeError: CUDA out of memory. Tried to allocate 768.00 MiB (GPU 0; 10.76 GiB total capacity; 7.76 GiB already allocated; 519.94 MiB free; 9.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by klshuster** [comment]
Looks like you are running out of memory -- what GPU capacity do you have access to?

**Comment by LONNIESAN** [comment]
this is my coda config 
![nevmi](https://user-images.githubusercontent.com/18715018/224460790-968e2f7e-3391-404d-8fc9-a9ddee9b1b78.png)

**Comment by mojtaba-komeili** [comment]
We had success running it with 32GB of GPU memory. 16GB also works sometimes.
