### ISSUE TITLE
i'm using the chatService but i get the warning

### ISSUE THREAD

**Issue by LONNIESAN** [facebookresearch/ParlAI#4961]
i want to use the terminal chatService

 my config like this

            tasks:
              default:
                onboard_world: MessengerBotChatOnboardWorld
                task_world: MessengerBotChatTaskWorld
                timeout: 1800
                agents_required: 1
            task_name: chatbot
            world_module: parlai.chat_service.tasks.chatbot.worlds
            overworld: MessengerOverworld
            max_workers: 30
            opt:
              debug: True
              models:
                blender_90M:
                  model: transformer/generator
                  model_file: zoo:bb3/bb3_3B/model
                  interactive_mode: True
                  no_cuda: True
                  search_server: 0.0.0.0:8080
                  init_opt: gen/r2c2_bb3
              search_server: 0.0.0.0:8080    
            additional_args:
              page_id: 1 # Configure Your Own Page
              search_server: 0.0.0.0:8080

when i use the command 

     python parlai/chat_service/services/terminal_chat/run.py --config-path parlai/chat_service/tasks/chatbot/config-test.yml --port 10001,

i get the following warning

    your model is being loaded with opts that do not exist in the model you are initializing the weights with: evaltask: projects.bb3.tasks.module_level_tasks:AlwaysSearchTeacher,projects.bb3.tasks.module_level_tasks:MaybeSearchTeacher,projects.bb3.tasks.module_level_tasks:MemoryDecisionTeacher,projects.bb3.tasks.module_level_tasks:SearchQueryGenerationTeacher,projects.bb3.tasks.module_level_tasks:MemoryGenerationTeacher,projects.bb3.tasks.module_level_tasks:MemoryKnowledgeGeneratio

**Comment by klshuster** [comment]
this is just a warning, you can ignore it

**Comment by klshuster** [comment]
could you add `http://` before the server address?

**Comment by LONNIESAN** [comment]
![config](https://user-images.githubusercontent.com/18715018/221189436-b67f2e49-a506-4a01-b249-1d57e33fd648.png)
I have add http:// in the config-test.xml like attach file.But when I use this command    python parlai/chat_service/services/terminal_chat/run.py --config-path parlai/chat_service/tasks/chatbot/config-test.yml --port 10001,there is nothing log int the search server.you can see as bleow

![search_server](https://user-images.githubusercontent.com/18715018/221189880-9d4afa32-91e5-4706-9f03-feec624fec30.png)

when I use the command 
parlai interactive -mf zoo:bb3/bb3_3B/model --init-opt gen/r2c2_bb3 --search-server 0.0.0.0:8080,i can the search_server log like this

![search_server_log](https://user-images.githubusercontent.com/18715018/221190209-d843bc91-0635-4308-aa8e-1497f8b548a0.png)

How do I change my configuration file to make search_server work?

**Comment by klshuster** [comment]
could you show your conversation when deploying via the config?
