### ISSUE TITLE
how can I provide multiple persona types option in MSC dataset to my own model?

### ISSUE THREAD

**Issue by terateil** [facebookresearch/ParlAI#4964]
Hi, I'm new to this platform, and I'm trying to build my own dialog model for MSC dataset. I have serveral questions.

1. My model should take both summary and raw dialog history as input, so I'm wondering how should I do this. I've checked that using display_data method, setting --previous-persona-type as 'goldsum_both', 'raw_history' gives what I need separately.
2. The entire model should use some pretrained models from huggingface. In my case, what are the things that I should implement to make it work in parlai?

Thanks.

**Comment by klshuster** [comment]
CC @jxmsML for question 1

for question 2, i would take a look at the agents we have already ported in the `parlai/agents/hugging_face` directory (such as T5, GPT2, and DialoGPT)
