### ISSUE TITLE
Query regarding Dialogue Summarization Model

### ISSUE THREAD

**Issue by muzamil47** [facebookresearch/ParlAI#4966]
I am curious to know about the [Dialogue Summarization Model](https://parl.ai/docs/zoo.html?#dialogue-summarization-model). 

- How the model has been trained?
- How can we fine-tune it on custom dataset?

Any further documentations or ideas would be helpful.
Thanks!

**Comment by klshuster** [comment]
Per the [project page](https://parl.ai/projects/msc/), the model has been trained on the `msc:PersonaSummary` task

You can fine-tune via standard parlai fine-tuning procedures; please see our docs (or other project pages) for inspiration
