### ISSUE TITLE
How run BB3 in non-interactive mode

### ISSUE THREAD

**Issue by SarikGhazarian** [facebookresearch/ParlAI#4967]
I am trying to run BB3 in non-interactive mode such that I can give it a file of dialogue contexts and ask BB3 to generate response for them respectively. Consider, here is a dialogue context:

_Person 1: Hi, this is Jessica. What is your name? 
Person 2: Hi, I am Maggie. Do you want to talk about world cup games? I love world cup. 
Person 1: Oh, yes sure.
Person 2:_ 

Currently, I have the following code which tries to continue the conversation by printing response of Person 2:

```
from parlai.core.agents import create_agent
from parlai.core.message import Message
opt_dict = {'model_file': 'ParlAI/data/models/bb3/bb3_3B/model', 'interactive_mode': True}
agent = create_agent(opt_dict) 
observations=[]
agent_copies = []
agent_copies.append(agent.clone())
act_0 = Message({'id': 'context_0', 'text': "Person 1: Hi, this is Jessica. What is your name? Person 2: Hi, I am Maggie. Do you want to talk about world cup games? I love world cup. Person 1: Oh, yes sure. **Person 2:** ", 'episode_done': False})
  observations.append(agent_copies[0].observe(act_0)) 
response = agent.batch_act(observations)
print(response)
```

which prints a response like this:

[{'id': 'ComboFidGoldDocument', 'episode_done': False, 'text': 'Person 1: Hi, this is Jessica. What is your name?', 'beam_texts': [('Person 1: Hi, this is Jessica. What is your name?', -1.5164902210235596)], 'top_docs': [ID: 
Title: 
Text: , ID: 
Title: 
Text: , ID: 
Title: 
Text: , ID: 
Title: 
Text: , ID: 
Title: 
Text: ], 'metrics': {'clen': AverageMetric(53), 'ctrunc': AverageMetric(0), 'ctrunclen': AverageMetric(0), 'gen_n_toks': AverageMetric(16)}}]

that does not make sense. I look forward for some suggestions!

thanks!

**Comment by klshuster** [comment]
Hi, in your `opt_dict`, you'll also want to specify `'opt_preset' : 'gen/r2c2_bb3.opt'`; that should hopefully help out

**Comment by SarikGhazarian** [comment]
Hi Kurst,

thanks for your reply and hint! The main issue was regarding the format of dialogue context. I replaced Person1: and Person2: with \n to show the dialogue context and now it generates some outputs accordingly.

`
from parlai.core.agents import create_agent
from parlai.core.message import Message
opt_dict = {'model_file': 'ParlAI/data/models/bb3/bb3_3B/model', 'interactive_mode': True, **'init_opt' : 'gen/r2c2_bb3.opt', 'search-server' : '0.0.0.0:8080'**}
agent = create_agent(opt_dict) 
observations=[]
agent_copies = []
agent_copies.append(agent.clone())
act_0 = Message({'id': 'context_0', 'text': "**Hi, this is Jessica. What is your name?\nHi, I am Maggie. Do you want to talk about world cup games? I love world cup.\nOh, yes sure. Who was the winner of latest world cup?\n**", 'episode_done': False})
observations.append(agent_copies[0].observe(act_0)) 
response = agent.batch_act(observations)
print(response)`

**Output of non-interactive mode:**
[{'id': 'ComboFidGoldDocument', 'episode_done': False, 'text': "I am not sure. I don't watch soccer.", 'beam_texts': [("I am not sure. I don't watch soccer.", -6.9718523025512695)], 'top_docs': [ID: 
Title: 
Text: , ID: 
Title: 
Text: , ID: 
Title: 
Text: , ID: 
Title: 
Text: , ID: 
Title: 
Text: ], 'metrics': {'clen': AverageMetric(50), 'ctrunc': AverageMetric(0), 'ctrunclen': AverageMetric(0), 'gen_n_toks': AverageMetric(13)}}]
The model does not do a search on search server (0.0.0.0:8080).

However, if I give the the same query to the model in the interactive mode, I can see that the response is different and indeed model does search and access to memory:

parlai safe_interactive --model-file zoo:bb3/bb3_3B/model --init-opt gen/r2c2_bb3 --search-server 0.0.0.0:8080

**Output of interactive mode:**
[BlenderBot3]:  Portugal won the world cup in 2018. How about you? Do you have a favorite team?

I would appreciate to get some guidance here.

**Comment by mojtaba-komeili** [comment]
Looks like for some reason your model doesn't get loaded in the interactive mode, with generation being on.
Could you try it with `create_agent_from_model_file` instead of `create_agent`?
It would be something like these changes in your code:
```
...
from parlai.core.agents import create_agent_from_model_file
...
opt_dict = {'init_opt' : 'gen/r2c2_bb3.opt', 'interactive_mode': True}
agent = create_agent_from_model_file('zoo:bb3/bb3_3B/model', opt_dict)
...
```

**Comment by klshuster** [comment]
Are you sure you're giving the exact same context for both interactive and non-interactive? Could you share a screenshot of your interactive output?

**Comment by SarikGhazarian** [comment]
@mojtaba-komeili thank you for your suggestion, I changed the code but still the non-interactive output was as it was before.
output from non-interactive code:
<img width="1676" alt="Screen Shot 2023-04-06 at 1 19 50 PM" src="https://user-images.githubusercontent.com/31287614/230486508-3df60790-3e6e-4f4a-835e-e9250a9a4a9a.png">'

@klshuster yes, the contexts are the same. Here I have attached the screenshot of interactive output (only include the relevant sections as it is too long):
<img width="1675" alt="Screen Shot 2023-04-06 at 1 25 41 PM" src="https://user-images.githubusercontent.com/31287614/230487133-b6546fb6-76d6-444d-a95e-8a7cd8689c4e.png">

<img width="1673" alt="Screen Shot 2023-04-06 at 1 27 21 PM" src="https://user-images.githubusercontent.com/31287614/230487339-05c2a1c6-cc9a-4f95-be30-9016c25681eb.png">

As you compare the outputs of these two, only in interactive mode we see "Loading search generator model".

**Comment by klshuster** [comment]
Could you try taking the opt values specified [here](https://github.com/facebookresearch/ParlAI/blob/main/parlai/opt_presets/gen/r2c2_bb3.opt) (`gen/r2c2_bb3`) and putting them in your `opt_dict` when you're doing non-interactive?

**Comment by mojtaba-komeili** [comment]
Glad to see things worked out. The factual correctness of the model, or its grasp of reality and common sense (specially about the recency of events) is an open challenge for AI. SKR and BB3 took steps towards improving it, but still not there yet.
