### ISSUE TITLE
how to create vocabulary for personality captions

### ISSUE THREAD

**Issue by shreyassks** [facebookresearch/ParlAI#4968]
I found out the vocabulary size used in this project which was 250000. But when i tried to use the training and validation json files, there were onnly about 85000 unique tokens. I have not done any preprocessing. I was just wondering to know how the vocabulary size used here is so large. Am i missing something

**Comment by mojtaba-komeili** [comment]
Which model are you talking about? Sometimes the vocabulary size is inherited from the pre-training task.

**Comment by shreyassks** [comment]
I'm using YFCC dataset to train Retrieval model (TransResNet) for Personality captions

**Comment by klshuster** [comment]
Indeed the pre-trained encoder model uses a dictionary from it's pre-training dataset

We do not have any image captioning models in the traditional sense in this repo, but [this project](https://parl.ai/projects/multimodal_blenderbot/) is an example of a generative model used in conversations about images -- as is [this project](https://parl.ai/projects/dodecadialogue/)

**Comment by klshuster** [comment]
We do not have the Updown model in our repo, sorry
