### ISSUE TITLE
Keep multiple checkpoints during training

### ISSUE THREAD

**Issue by hamjam** [facebookresearch/ParlAI#4970]
Hi, 
Is there an option or a way to keep for example 5 best checkpoints in the training process by using [train_model.py](../blob/main/parlai/scripts/train_model.py) and not just the best model checkpoint?
As far as I understood, there isn't any option to keep multiple checkpoints in  [train_model.py](../blob/main/parlai/scripts/train_model.py), and by any option group, the new checkpoint will be overwritten on the only last checkpoint that has been saved.
Should I add this feature and if it's required create a pull request or is there a logic behind the way [train_model.py](../blob/main/parlai/scripts/train_model.py) keeps the checkpoints?

**Comment by ahkarami** [comment]
@hamjam 
I think the [`--save-after-valid`](https://github.com/facebookresearch/ParlAI/blob/main/parlai/scripts/train_model.py#L174) option does what you need it to do.

**Comment by hamjam** [comment]
@ahkarami 
As in [this](https://github.com/facebookresearch/ParlAI/blob/f6c9d04272c3be6fe643c918f20be82501a7a09f/parlai/scripts/train_model.py#L619) part of [train_model.py](https://github.com/facebookresearch/ParlAI/blob/main/parlai/scripts/train_model.py) I don't think by setting this option, a new checkpoint file will be created. It would create a new checkpoint after the validation but the checkpoint will not be saved by a new name and it will be just overwritten on the previously saved checkpoint by the same name.

**Comment by klshuster** [comment]
You are correct, the current logic overwrites the checkpoints for each validation. We would appreciate a pull request that achieves your request if you are able to submit one!
