### ISSUE TITLE
ParlAI model cannot do interactive dialogues on Google Colab

### ISSUE THREAD

**Issue by lugulugu** [facebookresearch/ParlAI#4972]
I followed the ParlAI colab tutorial (https://colab.research.google.com/drive/1bRMvN0lGXaTF5fuTidgvlAl-Lb41F7AD#scrollTo=KtVz5dCUmFkN) until the session "Chatting with a model". However, the model cannot do the interactive dialogues with users and generates an error "indices should be either on cpu or on the same device as the indexed tensor (cpu)". It seems that the error points to the script "[/usr/local/lib/python3.8/dist-packages/parlai/core/torch_generator_agent.py]" at the place:
   1597         self.partial_hyps = torch.cat(
   1598             (
-> 1599                 self.partial_hyps[path_selection.hypothesis_ids.long()],
   1600                 path_selection.token_ids.view(path_selection.token_ids.shape[0], -1).to(
   1601                     hyp_device

Could you please help me explain how can I fix this error?

p.s. at the beginning of this tutorial, it seems that I need to additionally install the NVIDIA apex package as follows:
!git clone https://github.com/NVIDIA/apex
%cd apex
!python3 setup.py install

**Comment by klshuster** [comment]
What version of pytorch do you have installed?

**Comment by lugulugu** [comment]
Many thanks for your hints! I have downgraded to pytorch 1.12, and the colab tutorial works as it is.
