### ISSUE TITLE
Can bb3 directly train different languagess?

### ISSUE THREAD

**Issue by HocherCN** [facebookresearch/ParlAI#4974]
I'm a novice to parlai. Can I use bb3 to train new languages and close the web search section

**Comment by klshuster** [comment]
You can definitely try!

**Comment by HocherCN** [comment]
I want to train chinese data, but  the original bpe does not seem to be very effective. Do you have any recommended bpe？And, i read r2c2 model paper, but i don't understand what the r2c2 model is. Is it based on the combination of transformer and gpt2 after pre-training?

**Comment by klshuster** [comment]
the r2c2 model is an encoder/decoder transformer that is very similar to BART (see [the paper here](https://arxiv.org/abs/1910.13461)). 

I am not super familiar with the best BPE dictionaries for chinese data, you may have to do your own research there
