### ISSUE TITLE
Hints and suggestion regarding creating a contextual chatbot

### ISSUE THREAD

**Issue by muzamil47** [facebookresearch/ParlAI#4977]
@klshuster  How do I create a chatbot based on mission script dialogues that can also respond contextually to any unhandled (random, out-of-context) inputs?

I have a script for multiple missions, written with input and output dialogues. Each dialogue in a mission is a continuation of the previous conversation, starting with a prompt dialogue.
When a user says any input that is in the script, the rule-based system can handle the response. However, if the response is any random input beyond the script or the paraphrased version of the input (with synonyms, for example), the chatbot can't handle that response.

I want a solution for this problem where I provide a model that can handle the out-of-context input in an appropriate manner.

Any help or suggestions would be highly appreciated.
Thanks!

**Comment by klshuster** [comment]
Hi @muzamil47, I would check out some of the dialogue models from our projects page (https://parl.ai/projects), and see if any of those work for your use case

**Comment by muzamil47** [comment]
I would highly appreciate your efforts. Thanks!
