### ISSUE TITLE
Question about Personachat Experiments 

### ISSUE THREAD

**Issue by JPegah** [facebookresearch/ParlAI#4983]
Hi, 
I am trying to reproduce the results of the persona chat paper including the next utterance prediction and profile extraction experiments. 
To reproduce the results of the next utterance prediction I ran two agents (IR_baseline and seq2seq) with the following commands:

`parlai train_model -m ir_baseline -t personachat:none --dict-file /tmp/personachat.dict -ttim 5`
`parlai train_model -m ir_baseline -t personachat:both_original --dict-file /tmp/personachat.dict -ttim 5`
`parlai train_model --task personachat:none --model seq2seq --model-file /tmp/model_s2s --batchsize 32`
`parlai train_model --task personachat:both_original --model seq2seq --model-file /tmp/model_s2s --batchsize 32`

However the results that I am getting are not close to the results reported in the paper.  Are there any parameters that I have to add to these commands?

In the paper it is mentioned that in the profile extraction experiment, the models are similar to the previous experiment(IR_baseline, ...). Is the data for this experiment available? I know I can create the data for this experiment by randomly selecting user personas from other conversations. However I am trying to reproduce the exact results and it would be great to use the exact same data. 

Are the conversations between the conversational model and humans in the experiments publicly available? 

Could you please help me with these issues?

**Comment by klshuster** [comment]
These models are very old and most likely no longer supported - any reason why you are trying to reproduce those results?
