### ISSUE TITLE
Question about the answer of the model bb3 3b

### ISSUE THREAD

**Issue by Vitaliy136** [facebookresearch/ParlAI#4986]
I use the bb3 3b model. In general, the model responds very well

Dialogue example:

Human:  Tell me your name
Bot:    [Sorry, could not process that message. Please try again.]

Human:  I am John. Tell me your name
Bot:    Hello, my name is John. How are you doing today? What do you do for a living?

Launch parameters:

parlai safe_interactive --model-file zoo:bb3/bb3_3B/model --init-opt gen/r2c2_bb3 --search_server localhost:8080 --debug --verbose

Why does the bot sometimes answer me with my own words? Perhaps this behavior is influenced by one of the agents, such as the Memory Knowledge agent? Is it possible to change this behavior?

**Comment by klshuster** [comment]
That is a known issue in dialogue models, see e.g. our study on [maintaining character in dialogue](https://parl.ai/projects/light_whoami/).
