### ISSUE TITLE
can metaseq 125M to 66B OPT model can be used as BB3 model just like 175B model work

### ISSUE THREAD

**Issue by MrD005** [facebookresearch/ParlAI#4988]
i am trying to change BB3 2.7B model with 6.6B OPT model using metaseq but it is not working for me.
if anyone has trying something like that or any other way of achieving it apart from metaseq. I am currently trying to use alpa github repo to test but any suggestions will be helpful

**Comment by klshuster** [comment]
could you elaborate on what you're trying to accomplish?

bb3 2.7B is *not* an OPT-based model. bb3 30b and bb3 175b are *fine-tuned* variants of OPT models

**Comment by MrD005** [comment]
i am using BB3 3B model and now i want to use bb3 30B model using BB3OPT API using metaseq but there is big hardware requirement gap in 3B and 30B model so i am trying to use OPT 6B or 13B similarly using metaseq that we following in 30B and 175B model.

**Comment by MrD005** [comment]
Is there any way that i can fine tune OPT 6B to BB3 6B model. similarly like 30B is fine tune variants of OPT model
