### ISSUE TITLE
BB3 30B setup

### ISSUE THREAD

**Issue by Dev-hestabit** [facebookresearch/ParlAI#4989]
https://parl.ai/projects/bb3/ 
bb3 30B metaseq script is not working

python -m metaseq.scripts.reshard_model_parallel $CONSOLIDATED/consolidated $MP --save-prefix $RESHARD/reshard

i just tried this command and there is no reshard_model_parallel script available. there is one script name reshard_mp but it just gives the error (ValueError: The glob pattern doesn't match any model parallel parts.)

**Comment by klshuster** [comment]
Yeah there has been some consolidation of resharding scripts for metaseq, could you paste the full stack trace?
