### ISSUE TITLE
Tuning BB3 Module

### ISSUE THREAD

**Issue by ryanshea10** [facebookresearch/ParlAI#4990]
Hi, I'm training BB3 on a custom dialogue task using the following command:

```
parlai train_model -m projects.seeker.agents.seeker:ComboFidGoldDocumentAgent --init-opt arch/r2c2_base_3B --init-model zoo:seeker/r2c2_blenderbot_3B/model -mf zoo:bb3/bb3_3B/model --dict-file zoo:seeker/r2c2_blenderbot_3B/model.dict -t edu_bot -bs 1 -eps 1 --model-parallel true -fp16 true
```

After training I'm noticing that many of the bb3 modules get messed up and their output starts to match the content of the training data. For example, before training the search decision module outputs `__do-not-search__` as expected but after training it outputs `Hey, have you ever wondered what the true value of education actually is?` which is a phrase in the training data. Is there any way I can do the training such that I'm only training one module? I would like to only train the dialogue response module.

**Comment by klshuster** [comment]
Additionally, the [agent README](https://github.com/facebookresearch/ParlAI/blob/af9f3a0efcea171ee727e8433bed7bb461fe47cc/projects/bb3/agents/README.md) has more information regarding modules
