### ISSUE TITLE
How to correctly train a simple Q&A model ? 

### ISSUE THREAD

**Issue by jj449** [facebookresearch/ParlAI#4992]
I tried a dataset as below : 

**_text:Hey, have you seen the new Samsung Galaxy S22? I'm thinking of getting it.	labels:No, I haven't. What's so great about it?
text:Well, it has a 6.6-inch AMOLED display with a 120Hz refresh rate. That means everything looks super smooth.	labels:Wow, that sounds impressive. How's the battery life?
text:It has a 5000mAh battery, which should last all day with moderate use. Plus, it supports 25W fast charging.	labels:That's pretty good. What about the camera?
text:It has a triple camera setup, with a 108MP main camera, a 12MP ultrawide camera, and a 5MP macro camera. And the front-facing camera is 20MP.	labels:Nice, I'm into photography, so that sounds appealing. What about the storage capacity?
text:The base model has 128GB of storage, but you can get up to 512GB if you want. And it supports microSD cards up to 1TB.	labels:That's good to know.	episode_done:Trueext:Hey, have you seen the new Samsung Galaxy S22? I'm thinking of getting it.	labels:No, I haven't. What's so great about it?
text:Well, it has a 6.6-inch AMOLED display with a 120Hz refresh rate. That means everything looks super smooth.	labels:Wow, that sounds impressive. How's the battery life?
text:It has a 5000mAh battery, which should last all day with moderate use. Plus, it supports 25W fast charging.	labels:That's pretty good. What about the camera?
text:It has a triple camera setup, with a 108MP main camera, a 12MP ultrawide camera, and a 5MP macro camera. And the front-facing camera is 20MP.	labels:Nice, I'm into photography, so that sounds appealing. What about the storage capacity?
text:The base model has 128GB of storage, but you can get up to 512GB if you want. And it supports microSD cards up to 1TB.	labels:That's good to know.	episode_done:True`_**

and  run the training with following command :  
parlai train_model -t fromfile --fromfile-datapath /tmp/test2.txt -m transformer/generator -mf /tmp/mymodel2 -bs 8 -eps 10

it succesfully generated a model named model2 there .

then I interact that model with following command : 
parlai interactive --model-file /tmp/mymodel2 

but the answer/response from model is strange 
![image](https://user-images.githubusercontent.com/58848201/227530338-42084083-4479-49e6-bbc2-d5fc94375dae.png)

What's wrong? AND How do i fix it ? Thanks .

**Comment by jj449** [comment]
if i try to train with --init-model and  --dict-file  , then the trained model behavors like init-model  , but seems act without my custom Q&A content .... 

`parlai train_model --model transformer/generator \
--task fromfile:parlaiformat --fromfile_datapath /tmp/test2.txt \
--multitask-weights 1,3,3,3 --num-epochs 5 \
--init-model zoo:tutorial_transformer_generator/model \
--dict-file zoo:tutorial_transformer_generator/model.dict \
--embedding-size 512 --n-layers 8 --ffn-size 2048 --dropout 0.1 --n-heads 16 \
--learn-positional-embeddings True --n-positions 512 --variant xlm --activation gelu --fp16 True \
--text-truncate 512 --label-truncate 128 --dict-tokenizer bpe --dict-lower True -lr 1e-06 \
--optimizer adamax --lr-scheduler reduceonplateau --gradient-clip 0.1 -veps 0.25 --betas 0.9,0.999 \
--update-freq 1 --attention-dropout 0.0 --relu-dropout 0.0 --skip-generation True -vp 15 -stim 60 \
--vme 20000 -bs 16 -vmt ppl -vmm min --save-after-valid True --model-file /tmp/model013`

![image](https://user-images.githubusercontent.com/58848201/227790934-d3d0762c-14f1-4bc2-bd60-bc17682528cf.png)

any help? I'm new in parlai

**Comment by klshuster** [comment]
Your second screenshot does not have the message "Hey, have you seen the new Samsung galaxy S22" - could you try with that?
