### ISSUE TITLE
What are `bot_persona` and `your persona` used for in the BAD dataset?

### ISSUE THREAD

**Issue by szhengac** [facebookresearch/ParlAI#4994]
Hi, thanks for the great work in collecting the BAD dataset. I just have a question on the dataset format for BAD since I cannot find its description anywhere in this repo or the paper. I noticed that there are some sentences like 
```
bot_persona:your persona: i made my first movie when i was 18.\nyour persona: i starred in television commercials when i was young.
``` 
appended to each line. I wonder what is the relationship between it and the text (conversation)? It looks a bit irrelevant to the text to me. Thanks!

**Comment by szhengac** [comment]
@klshuster thanks for the response. Are these persona lines reformulated as prompt when AI assistant responding? I checked many examples, but I feel like what the AI assistant responds are not quite relevant to these persona lines.

**Comment by klshuster** [comment]
The dataset was built for eliciting bad responses from the agent, so users were writing messages to not get it to stick to its persona -- so, not all the messages will stick to this persona
