### ISSUE TITLE
Attention visualization

### ISSUE THREAD

**Issue by min942773** [facebookresearch/ParlAI#4995]
Hi!

I have been using various models that involve attention mechanisms, but I am having difficulties in visualizing the attention patterns generated by models (BART). I would like to know if there is any method available in ParlAI that allows me to visualize the attention weights in a simple and intuitive way. If not, I would appreciate some guidance on how to implement this feature.

Thank you for your help!

**Comment by klshuster** [comment]
Unfortunately we don't currently offer any easy ways to access the attentions.

[the multihead attention module returns the dotprod attention in its return value](https://github.com/facebookresearch/ParlAI/blob/main/parlai/agents/transformer/modules/attention.py#L267)

You can extract encoder attentions [at this line](https://github.com/facebookresearch/ParlAI/blob/971a057caeef8b2a283779452155fba673dfd7a6/parlai/agents/transformer/modules/encoder.py#L89) (if you don't access the first elem of the return)

You can extract decoder attentions [here](https://github.com/facebookresearch/ParlAI/blob/971a057caeef8b2a283779452155fba673dfd7a6/parlai/agents/transformer/modules/decoder.py#L532) and [here](https://github.com/facebookresearch/ParlAI/blob/971a057caeef8b2a283779452155fba673dfd7a6/parlai/agents/transformer/modules/decoder.py#L548)

Hope that helps!

**Comment by min942773** [comment]
Thank you for your help!

**Comment by min942773** [comment]
I would like to express my gratitude for the helpful response I received! 
However, I have a follow-up question on how to visualize cross-attention weights.

Specifically, I am using a BART model. 
Could you provide any guidance or resources on how to visualize then in my current model?

Once again, thank you for your time and assistance.

**Comment by klshuster** [comment]
The cross-attentions are the result of the decoder's call to [`self.encoder_attention`](https://github.com/facebookresearch/ParlAI/blob/971a057caeef8b2a283779452155fba673dfd7a6/parlai/agents/transformer/modules/decoder.py#L548)
