### ISSUE TITLE
Issue on 3rd example on Readme

### ISSUE THREAD

**Issue by puneetjindal** [facebookresearch/ParlAI#50]
`python3 examples/eval_model.py -m ir_baseline -t "#moviedd-reddit" -dt valid`

Output is 

> [model_file:]
> [task:#moviedd-reddit]
> [numthreads:1]
> [batchsize:1]
> [model_params:]
> [num_examples:1000]
> [model:ir_baseline]
> [datatype:valid]
> [download_path:/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/parlai-0.1.0-py3.4.egg/downloads]
> [display_examples:False]
> [datapath:/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/parlai-0.1.0-py3.4.egg/data]
> IrBaselineAgent
> Traceback (most recent call last):
>   File "examples/eval_model.py", line 45, in <module>
>     main()
>   File "examples/eval_model.py", line 29, in main
>     agent = create_agent(opt)
>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/parlai-0.1.0-py3.4.egg/parlai/core/agents.py", line 100, in create_agent
>     my_module = importlib.import_module(module_name)
>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/__init__.py", line 109, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
> ImportError: No module named 'parlai.agents.ir_baseline'

**Comment by puneetjindal** [comment]
@alexholdenmiller : Error # resolved __init__.py file needs to be added to the _parlai/agents/ir_baseline_ due to which it is not able to import **ir_baseline as a module**

**Comment by alexholdenmiller** [comment]
Ah thank you, good catch!
