### ISSUE TITLE
Mechanical Turk Hit Requests Getting Hanged/Disconnected for QA_Data_Collection

### ISSUE THREAD

**Issue by algoscale1** [facebookresearch/ParlAI#500]
We are using ParlAI with Mechanical Turk for data collection. Once the link is created after we run run.py, it is getting hanged in worker end after sending the message , where the loading message is shown (waiting for other parties). 

HITs are getting broken with no fixed pattern.Some times on the 1st iteration(question) , sometimes on answer section. We debugged the code with print statements and the halting line is found at

`self.question = self.mturk_agent.act()`
and
`self.answer = self.mturk_agent.act()`

No exceptions are thrown while it is in the waiting period. The session just freezes 

![task](https://user-images.githubusercontent.com/19416539/34993785-778cc8a2-faf7-11e7-9f91-c697efb1e5d2.PNG)

**Comment by JackUrb** [comment]
Hi @algoscale1 - do any errors pop up in the javascript console? Do outgoing network requests to heroku return errors? This kind of error usually relates to the client window not being able to make contact with the remote heroku server.

It's possible that it's happening further downstream (between heroku and your local machine), but let's start there

**Comment by algoscale1** [comment]
hello Jack, There are no error messages in javascript console. The heartbeat message is repeated forever
![javascript](https://user-images.githubusercontent.com/19416539/35009786-b7dd16f8-fb26-11e7-8390-ba82a6125cf6.png)

**Comment by JackUrb** [comment]
Interesting - was the COMMAND_SEND_MESSAGE object received before or after the stalling occurred? And from the network tab did a message go out to the heroku server after hitting the send button?

**Comment by algoscale1** [comment]
Sorry that was before hitting send. After hitting send , we recieved the following message
"New message, 3f9107d8-f513-4a43-b577-e6f7e7296b2b from agent waiting". Then heartbeat signals repeat again. When network was inspected, no outgoing requests were made. There was no network activity .

**Comment by JackUrb** [comment]
Does a message matching `received ack: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` appear in the logs after sending the message? (likely right before "new message ... from agent waiting")

**Comment by JackUrb** [comment]
Also can you run the python client using the `--debug` flag?

**Comment by algoscale1** [comment]
yes. "received ack: d14f979a-d289-449a-b67f-476ecea49ec2" just before the other message.

**Comment by JackUrb** [comment]
Ah okay in that case the message is being successfully acknowledged by the SocketManager class on the machine running ParlAI, so it's not a network issue. The output of the `--debug` is going to be necessary to pin down the issue

**Comment by algoscale1** [comment]
[debug_python_run.txt](https://github.com/facebookresearch/ParlAI/files/1636878/debug_python_run.txt)

**Comment by algoscale1** [comment]
Thanks, Above is whole -- debug information we got after running python client. We saved them in a .txt file and attached here.

**Comment by algoscale1** [comment]
All of the debug information was not recieved though. We have saved in .txt whatever we got after running python client.

**Comment by algoscale1** [comment]
[worlds.txt](https://github.com/facebookresearch/ParlAI/files/1636924/worlds.txt)
Attaching worlds.py as world.txt here as ".py" extension is not supported in here while attaching. Attaching it for your reference. Thanks.

**Comment by JackUrb** [comment]
Based on your symptoms it is clear that the message is being recieved by the ParlAI server and processed all the way up to the point where an incoming message is supposed to be put into an agent's `msg_queue` (where `act()` pulls the data from). Can you add prints before and after this line? https://github.com/facebookresearch/ParlAI/blob/171494d201cd8500ffb834a4440380b76f114383/parlai/mturk/core/agents.py#L99

It would appear that put_data is successfully being called with the sent message based on 
```
Manager received: Packet <{'receiver_id': '[World_qa_data_collection_1516136095]', 'id': '64e57098-3057-44ab-a6a4-de2d99261ae7', 'data': {'text': 'hello. how are you ?', 'id': 'waiting', 'episode_done': False, 'message_id': '46d83d53-908c-4ae9-acdd-f45bce6e0729'}, 'sender_id': 'A1A6T79M7OTZQ0', 'assignment_id': '3V0Z7YWSIY05O8L28URLF9Q1F6OV2D', 'conversation_id': 'w_79d70012-27e9-4f44-b48a-a6a672f4cb9e', 'type': 'message'}>
```
however if it hangs still after that it might be possible that the message isn't being put into the queue

**Comment by JackUrb** [comment]
Wait I think I see your issue - where do you set the agent's id to "waiting"?

**Comment by JackUrb** [comment]
Have you updated or changed your `assign_role_function` as defined in run.py?

**Comment by shinoys222** [comment]
We haven't changed  anything with assign_role_function
```
        def assign_worker_roles(worker):
            worker[0].id = mturk_agent_id
```

**Comment by shinoys222** [comment]
@JackUrb  following up on behalf of @algoscale1

**Comment by JackUrb** [comment]
Ah and is `mturk_agent_id` still set? The issue here is that the agent on the MTurk frontend side isn't properly being associated with its ID and I'm trying to find out why.

**Comment by shinoys222** [comment]
It should be done from front end side right.? This is happening completely random, sometimes in 1st turn, then 2nd turn. Sometimes the hit is completely succesfull

**Comment by JackUrb** [comment]
Do you see any changes in the name on the frontend (like how in the screenshot provided it is "waiting")?

**Comment by shinoys222** [comment]
When the message is sent succesfuly name is changed to "Worker". If it is in halted state it stays "waiting"

**Comment by JackUrb** [comment]
Alright something is being dropped that I'll need to do more research into (a message isn't being processed somewhere properly). 

On the upside there is a band-aid mitigation that should work with no additional effort. Replace this line:
https://github.com/facebookresearch/ParlAI/blob/171494d201cd8500ffb834a4440380b76f114383/parlai/mturk/core/mturk_manager.py#L223
with `agent_id=worker.id,`

Let me know if this resolves your problem. Moving forward I'll try to find out where in the code information is being lost that makes it not change the name

**Comment by JackUrb** [comment]
Also it would be useful to see the complete contents of your javascript console when not using this fix so that I can better debug.

**Comment by shinoys222** [comment]
This temporarily fixed the issue. Let us know once you push a release fixing this. The following file was the complete text from javascript console output during halting stage.

[js.txt](https://github.com/facebookresearch/ParlAI/files/1637136/js.txt)

**Comment by JackUrb** [comment]
Hi @shinoys222 - thanks for the js output, it was very useful in order to find out what was actually happening. I believe I have solved the issue in https://github.com/facebookresearch/ParlAI/pull/503. Please feel free to reopen this issue if you pull the new changes and are still running into problems.
