### ISSUE TITLE
What is the license for Mulit Session Chat?

### ISSUE THREAD

**Issue by chandana1332** [facebookresearch/ParlAI#5000]
Hello,

I don't see license information for Multi Session Chat from [this](https://arxiv.org/abs/2107.07566) paper. Can you please expand on this?

Thank you!

**Comment by chandana1332** [comment]
Can you also clarify for https://github.com/facebookresearch/ParlAI/tree/main/parlai/tasks/fits ?

**Comment by klshuster** [comment]
cc @jxmsML, i believe it is the same license as all other datasets within ParlAI -- CC-BY

**Comment by chandana1332** [comment]
Can you confirm this or is there some place I can investigate?
Asking because other datasets in the repo explicitly mention licensing info. I don't see it for MSC and FITS.

**Comment by klshuster** [comment]
Confirming this. CC @jxmsML but i'm 99% sure that is the case
