### ISSUE TITLE
Question about the configuration of search_server when running SeeKeR

### ISSUE THREAD

**Issue by scpaliuhc** [facebookresearch/ParlAI#5007]
Lately, I have been perusing the paper “SeeKeR: An Open source Search-Augmented Language Model” and endeavoring to experiment with the related models on my machine. However, I encountered some difficulties when attempting to use Bing Search API to search for relevant documents. 

I followed the example indicated on [the official webpage](https://parl.ai/projects/seeker/):

`parlai i -mf zoo:seeker/seeker_dialogue_3B/model -o gen/seeker_dialogue --search-server <search_server>` 

and replaced  <search_server> with https://api.bing.microsoft.com/v7.0/search. But it didn't work as the server_response.status_code is 404. 

![image](https://user-images.githubusercontent.com/28836938/231402656-670a5644-58ac-4d51-828e-f687c2b6a636.png)

Then I added my Key of Bing Search to the request and changed POST to GET:
![image](https://user-images.githubusercontent.com/28836938/231406602-9fb911e1-1778-4dbc-b703-165a3595c442.png)

However, nothing is passed to the next step although the response contains searched results. 
![image](https://user-images.githubusercontent.com/28836938/231407521-2944aee6-68e6-44a8-9096-ab548e8f1556.png). 
![image](https://user-images.githubusercontent.com/28836938/231410003-df3ff57b-089d-42c5-9bb4-40da204dbd16.png)

Would anyone be able to provide a successful example of running SeeKeR with Bing Search?

**Comment by mojtaba-komeili** [comment]
You need to setup your own server which complies with our API. See [this](https://github.com/facebookresearch/ParlAI/blob/d921d22902d0ffb9c0c887cc1c315dacc6de0d80/parlai/agents/rag/retrieve_api.py#L73) for more information about what our agent expects from the API.

**Comment by mojtaba-komeili** [comment]
You can set up a proxy server that sits between your model and any external search service. It forwards the query to the main server and reformats it content to match that, The choice of content type is completely up to you.
