### ISSUE TITLE
How to output the predicted probability distribution of the classifier for various labels

### ISSUE THREAD

**Issue by Oreki-PJ** [facebookresearch/ParlAI#5009]
i run "parlai interactive --model-file zoo:style_gen/prev_curr_classifier/model --model projects.style_gen.classifier:ClassifierAgent --classes-from-file image_chat_personalities_file", and i can only get the result of the classifier. but how can get the output the predicted probability distribution of the classifier for various labels ?

**Comment by Oreki-PJ** [comment]
![image](https://user-images.githubusercontent.com/65594747/232289048-bb9cbbcc-a874-4076-9271-3c8cd83bd285.png)

**Comment by klshuster** [comment]
if you set `--print-scores True` it will print the probability
