### ISSUE TITLE
How to train a model with unlikelihood loss?

### ISSUE THREAD

**Issue by yashkens** [facebookresearch/ParlAI#5011]
Hi! I am trying to train a model according to the [Unlikelihood Training project](https://github.com/facebookresearch/ParlAI/tree/main/projects/dialogue_unlikelihood).

First of all, I would like to replicate the work itself, specifically [Unlikelihood Vocab Model](https://parl.ai/docs/zoo.html#unlikelihood-vocab-alpha-1e0-model), but struggling to understand how to run the training code. I used the following command:
`parlai train_model -t convai2 -m parlai_internal.projects.dontsaythat.agents:TransformerSequenceVocabUnlikelihoodAgent`
but I was asked to specify the model file. I did
`parlai train_model -t convai2 -m parlai_internal.projects.dontsaythat.agents:TransformerSequenceVocabUnlikelihoodAgent -mf zoo:dialogue_unlikelihood/vocab_alpha1e0/model`
but got an error `ModuleNotFoundError: No module named 'parlai_internal'`

Which model file do I specify to replicate the work? And how do I use other models for this task? For example, if I want to finetune a pretrained model from hugging face on the same data as used in the paper. 

Speaking about data, the example usage contains a task named _convai2_, but displaying its data does not show any negative examples (the negative responses from DNLI, I believe). It there a way to display them?

My goal is to use negative examples, such as bad responses to a context, using unlikelihood loss. I suppose, the Agent I need is called [TransformerUnlikelihoodAgent](https://github.com/facebookresearch/ParlAI/blob/main/projects/dialogue_unlikelihood/agents.py#L545), but I did not find any models using in in the Zoo. Does the [TransformerSequenceVocabUnlikelihoodAgent](https://github.com/facebookresearch/ParlAI/blob/main/projects/dialogue_unlikelihood/agents.py#L533) use negative candidates too, or is it using a vocabulary of unwanted tokens? Would be grateful, if you explained what is the between the two and which one suits my task.

Thanks a lot!

**Comment by klshuster** [comment]
The model zoo agents were trained with pre-release code, but should work with the agents you have linked. so, just replace `parlai_internal.projects.dontsaythat.agents` with `projects.dialogue_unlikelihood.agents`

**Comment by yashkens** [comment]
Thanks! Replacing the path helped to start training, but I immediately got an error as shown on the screenshot. 
I didn't modify any code. Am I doing something wrong?
<img width="1221" alt="Снимок экрана 2023-04-21 в 13 11 06" src="https://user-images.githubusercontent.com/42929295/233611181-d56b212e-220a-4036-b087-92400f6a1130.png">

**Comment by yashkens** [comment]
Also, is there any information about which weight (parameter alpha on the screenshot) was used for unlikelihood loss in the experiments concerning contradictions? The paper describes different values of alpha for repetition and vocabulary tasks, but nothing for contradictions. In which range should [this alpha argument](https://github.com/facebookresearch/ParlAI/blob/main/projects/dialogue_unlikelihood/agents.py#L126) be?
<img width="463" alt="Снимок экрана 2023-04-24 в 11 20 26" src="https://user-images.githubusercontent.com/42929295/233941274-3bb466c2-d731-4460-bea2-3d6b434f0027.png">

**Comment by klshuster** [comment]
Hmm not sure what's going on with that error. As for the alpha ranges, I expect they are similar to the ones for repetition and vocabulary
