### ISSUE TITLE
How to create an agent on GPU?

### ISSUE THREAD

**Issue by para-zhou** [facebookresearch/ParlAI#5019]
I was trying to run this project : https://github.com/skywalker023/prosocial-dialog , which was built under ParlAI framework.
This work fine-tuned a T5 model for classification task.

I followed the instructions in above repository, load the model with "model.opt" and call self.agent = create_agent(opt).
However, I cannot run the model on GPU. I tried to modify the "gpu" arg in "model.opt" from -1 to 1, set CUDA_VISIBLE_DEVICES, and use torchrun to start the process, but none of them work.

Could you please help to get the agent run on GPU? Thanks!

**Comment by krisstud** [comment]
From your python environment you can check if cuda and torch is working by for example running:
```
python -c "import torch;print(torch.cuda.is_available())"
python -c "import torch;print(torch.version.cuda)"
```
If that doesn't report True i would suggest looking at your installed pytorch packages closely. They might be of the CPU-only variant.
