### ISSUE TITLE
What's the meaning of __NO__PERSONA__BEAM__MIN__LEN__20__

### ISSUE THREAD

**Issue by LONNIESAN** [facebookresearch/ParlAI#5022]
What's the meaning of __NO__PERSONA__BEAM__MIN__LEN__20__pen other questions or issues, and provide context here.

**Comment by lonnieLuPacvue** [comment]
OK，I continue to research

**Comment by LONNIESAN** [comment]
I found that the BB3 model responds slowly when chatting with it. I have optimized the search_server part for faster response, but the inference process of the model is still time-consuming. Is there any way to speed it up? I'm considering testing it with multiple GPUs, not sure if it will be effective.Can you give me some advice?Thanks.
