### ISSUE TITLE
How to fine tune blunderbot ?

### ISSUE THREAD

**Issue by imrankh46** [facebookresearch/ParlAI#5023]
Hi, I want to train blunderbot for custom dataset. 
I can't find docs for fine tuning.

**Comment by mohamedae17** [comment]
interested

**Comment by imrankh46** [comment]
> For finetuning BlenderBot 1, please see the "Fine-tuning your own models" section of the [project page](https://parl.ai/projects/recipes/)

Thanks. Can you shere me the data sample that required for fine tune. ? Or , I can fine tune with any type of data set !?

**Comment by klshuster** [comment]
Any data set would work. That command also specifies the datasets after the `--task` (or `--t`) command line argument

**Comment by imrankh46** [comment]
> Any data set would work. That command also specifies the datasets after the `--task` (or `--t`) command line argument

Thanks
