### ISSUE TITLE
Getting the processed data for BB3 Search Query Decision (sgm)

### ISSUE THREAD

**Issue by BiEchi** [facebookresearch/ParlAI#5034]
I'm trying to reproduce the datasets for the models. For example, for the SeeKeR model, I found the mutators code [here](https://github.com/facebookresearch/ParlAI/blob/4f4caa92c4710b0842dc52772ca75ea31c8a3c83/projects/seeker/tasks/mutators.py#L145) and teacher models [here](https://github.com/facebookresearch/ParlAI/blob/4f4caa92c4710b0842dc52772ca75ea31c8a3c83/projects/seeker/tasks/search_decision.py). However, reproducing the training data by preprocessing scripts myself requires too much work. Thus, I'm writing to ask whether there is a way to use ParlAI and produce the processed data and store it somewhere? Many thanks for any help!

**Comment by BiEchi** [comment]
I mean, where are the datasets, the finetuning code, etc?

**Comment by BiEchi** [comment]
I mean, I tried to train itself, but after training I get a model parameter, which cannot be loaded by PyTorch. Thus, I try to get the processed data after the mutators and train the model in PyTorch directly.

**Comment by BiEchi** [comment]
Pining @klshuster for better knowledge

**Comment by klshuster** [comment]
you can run `parlai convert_to_json --task projects.bb3.tasks.module_level_tasks:SearchQueryGenerationTeacher --world-logs /path/to/saved/logs --datatype train:stream:ordered` to convert the tasks to jsonl files

**Comment by BiEchi** [comment]
```bash
$ parlai convert_to_json --task projects.bb3.tasks.module_level_tasks:SearchQueryGenerationTeacher --world-logs ./export.log --datatype train:stream:ordered
Traceback (most recent call last):
  File "/opt/conda/envs/seeker/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/home/ec2-user/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/home/ec2-user/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/home/ec2-user/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/home/ec2-user/ParlAI/parlai/scripts/eval_model.py", line 314, in run
    return self.evaluator.eval_model()
  File "/home/ec2-user/ParlAI/parlai/scripts/eval_model.py", line 303, in eval_model
    return eval_model(self.opt)
  File "/home/ec2-user/ParlAI/parlai/scripts/eval_model.py", line 259, in eval_model
    raise ValueError(
ValueError: You should use --datatype train:evalmode if you want to evaluate on the training set.
```

Hmmm.. It seems that we have to use train:evalmode? I looked into the scripts and found that this might be the only way to get the train dataset.

**Comment by BiEchi** [comment]
By the way, what's the difference between always search teacher and maybe search teacher? If a module always generates search query, why should we add it anyway?

**Comment by klshuster** [comment]
That error is probably because the convert to json script subclasses the eval model script

"Always search" teacher teaches a model what contexts require search. "Maybe search" teacher shows varied contexts

**Comment by BiEchi** [comment]
@klshuster So do you mean that when we train an always search model, we should train it on both always search and maybe search tasks?
