### ISSUE TITLE
How to train an end-to-end QA model?

### ISSUE THREAD

**Issue by muzamil47** [facebookresearch/ParlAI#5046]
Hello,

I want to know how can I train a QA model on my own question/answer dataset, and what should be the format of dataset for training an end-to-end QA model.
Thanks!

**Comment by mojtaba-komeili** [comment]
You first need to create a teacher/task for your dataset. See how [here](https://parl.ai/docs/tutorial_task.html). And then train it with one of our agent (recommended), or again create one of your own.

**Comment by muzamil47** [comment]
Thanks for your response @mojtaba-komeili ,

From the available agents there are [transformer](https://parl.ai/docs/agent_refs/transformer.html), and [bert_ranker](https://parl.ai/docs/agent_refs/bert_ranker.html) that looks well fit for my usecase. However I have a question regarding candidates.

How can I define candidates `--candidates`, `--eval-candidates` or ` --ecands` in training dataset?

**Comment by mojtaba-komeili** [comment]
If you think a ranker agent can provide for what you are looking for, please check its documentation [here](https://parl.ai/docs/tutorial_torch_ranker_agent.html) for more information on setting up your agent.
