### ISSUE TITLE
i use a docker and make the container success.when i use docker exec the parlai is success.But when i use ssh to go into the docker container i get the error msg:parlai: command not found

### ISSUE THREAD

**Issue by LONNIESAN** [facebookresearch/ParlAI#5062]
**Bug description**
Please enter a clear and concise description of what the bug is.

**Reproduction steps**
Enter steps to reproduce the behavior.

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Logs**
Please paste the command line output:

```
Output goes here
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by mojtaba-komeili** [comment]
ParlAI image is using a Conda environment. You need to make sure you are in that conda environment.

**Comment by LONNIESAN** [comment]
hi, can you give me some command to enter the conda environment

**Comment by LONNIESAN** [comment]
yes, i find that the reason is for env variable
