### ISSUE TITLE
Model Evaluator task not working

### ISSUE THREAD

**Issue by deshraj** [facebookresearch/ParlAI#509]
Hi @jaseweston @alexholdenmiller, I was trying to run the model evaluator task on AMT but it doesn't seem to work. Here is the screenshot related to the error: 

<img width="1426" alt="screen shot 2018-01-20 at 5 21 38 pm" src="https://user-images.githubusercontent.com/2945708/35188605-9182970c-fe06-11e7-833c-7a2aa7933836.png">

Please find the terminal log here: https://pastebin.com/Jx1qVS5K

If I refresh the page, then it seems to work properly. Please let me know if I am missing something or this is a known issue that needs to be fixed. 

Thanks!

**Comment by jaseweston** [comment]
@JackUrb

**Comment by JackUrb** [comment]
Hi @deshraj, sorry for the late reply here. This is a possible unintended consequence of the fix in #500 which prepares for a change in some browsers that affects how they process things over sockets ever-so-slightly. I haven't been able to reproduce the issue myself however, so I was unable to figure out what would cause the issue if it was something that could actually happen at all.

A few of questions that should be able to help me find the source of this issue:
Are you able to reproduce the issue 100% of the time? What browser and version are you using? Are you able to reproduce the issue if you try it with a version of ParlAI before the #500 fix?

**Comment by JackUrb** [comment]
Hi @deshraj - I found the issue and have resolved it in #512. Let me know if you still have any other problems with the MTurk features!

**Comment by deshraj** [comment]
Hi Jack, thanks for the fix. Will try and let you know if I face any other issue.
