### ISSUE TITLE
OpenSubtitles version

### ISSUE THREAD

**Issue by jsamson008** [facebookresearch/ParlAI#523]
I was wondering why the opensubtitles version is the older version instead of the newer like 2018? 

This is a trivial change in the opensubtitles task agent, but is there a reason? If not, it might be reasonable and nearly trivial to add an option for the version.

**Comment by jaseweston** [comment]
I didn't realize there were a lot of versions or where we could get them ... @alexholdenmiller ?
Sure having access to the current (as we already have) + the latest could make sense?

**Comment by alexholdenmiller** [comment]
Thanks for the heads up @jsamson008!

**Comment by jaseweston** [comment]
@jsamson008  if you are interested in adding this we'd be v. happy also!

**Comment by jsamson008** [comment]
Sure, how would you like the task option to look? 

Some ideas:
1 - opensubtitle:<xxx>:<###>:version? but this doesn't fit. 
2 - I could also do, opensubtitles2018 and then import the standard agent. 
3 - Another option is to add a data version flag; so, this would be like --data-path, just --data-version.

**Comment by jaseweston** [comment]
I think something like

python examples/display_examples.py  -t opensubtitles:2018

would be good, we did that already with things like:


python examples/display_data.py  -t opensubtitles:Task100k
see in this code:
https://github.com/facebookresearch/ParlAI/blob/master/parlai/tasks/opensubtitles/agents.py

and we can change the default one to the latest one

**Comment by emilydinan** [comment]
Hi @jsamson008 -- are you working on this currently? Looking to add something like this very soon, so wanted to check to see if you had started to work on it (before I started). Thanks!

**Comment by jsamson008** [comment]
Yes, I had started, but I'm happy to stop if you want to do it. 

I'm having a problem because python examples/display_data.py  -t opensubtitles:2018:Task100k doesn't work. This is because of the  ":" based split https://github.com/facebookresearch/ParlAI/blob/master/parlai/core/agents.py#L347.

Thinking about going back to --data-version idea.

**Comment by jaseweston** [comment]
you can do  opensubtitles:2018-Task100k if you need subsets like that
if the point is to make the big one though, you dont really need a 100k
version of it, right?

**Comment by jaseweston** [comment]
meanwhile @urikz seems to have written: https://github.com/facebookresearch/ParlAI/pull/562

**Comment by jsamson008** [comment]
@jaseweston I'm closing this issue since I think that the new patch does exactly what my patch intended.

**Comment by jsedoc** [comment]
Would it be possible to add Jiwei Li's cleaned up OpenSubtitles?
http://nlp.stanford.edu/data/OpenSubData.tar

This data is much cleaner than the 2018 default and results in better model performance as evaluated by MTurkers.

**Comment by stephenroller** [comment]
Sure, we'd happily take it. I don't think any of us have bandwidth to build this presently, but we would most happily accept a PR!

Something like `StanfordTeacher` or `JiweiTeacher` in https://github.com/facebookresearch/ParlAI/blob/master/parlai/tasks/opensubtitles/agents.py

Is there a paper about that discusses this cleaned up version?
