### ISSUE TITLE
lua requirement missing

### ISSUE THREAD

**Issue by puneetjindal** [facebookresearch/ParlAI#53]
Error on running `python examples/memnn_luatorch_cpu/full_task_train.py -t babi:task10k:1 -n 8
`
> Traceback (most recent call last):
>   File "examples/memnn_luatorch_cpu/full_task_train.py", line 100, in <module>
>     main()
>   File "examples/memnn_luatorch_cpu/full_task_train.py", line 68, in main
>     agent = ParsedRemoteAgent(opt, {'dictionary': dictionary})
>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/parlai-0.1.0-py3.4.egg/parlai/agents/remote_agent/agents.py", line 123, in __init__
>     super().__init__(opt, shared)
>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/parlai-0.1.0-py3.4.egg/parlai/agents/remote_agent/agents.py", line 51, in __init__
>     args=opt.get('remote_args', '')
>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 859, in __init__
>     restore_signals, start_new_session)
>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 1463, in _execute_child
>     raise child_exception_type(errno_num, err_msg)
> FileNotFoundError: [Errno 2] No such file or directory: 'luajit'

**Comment by puneetjindal** [comment]
solution is install LuaJit compiler is missing and it needs to be installed from here
http://luajit.org/install.html

**Comment by alexholdenmiller** [comment]
You actually need the full torch package, as specified in the README. I'll update the memnn example to check for luajit and give a better error message.
