### ISSUE TITLE
Bug report.

### ISSUE THREAD

**Issue by Jackberg** [facebookresearch/ParlAI#566]
https://github.com/facebookresearch/ParlAI/blob/c6f03dc8d8f1df8a237542ce76e7d9be8d9e338d/parlai/core/utils.py#L435
This line, comparing Torch Variable to Int type, will issue this error: 
_RuntimeError: bool value of Variable objects containing non-empty torch.ByteTensor is ambiguous._

Modifying the former line as: `for c in predictions[i].data:` will solve this problem.

**Comment by jaseweston** [comment]
@alexholdenmiller  or @klshuster
