### ISSUE TITLE
Small suggestion concerning model_file

### ISSUE THREAD

**Issue by Jackberg** [facebookresearch/ParlAI#568]
It's weird that the program can run without model_file. Yet it took me several hours to figure out that the result is totally wrong (using seq2seq model), because the dictionary is almost empty.

Maybe it's a bug, the in-memory dictionary is not correctly build? Or maybe just simply give an error if no model_file path assigned.

**Comment by jaseweston** [comment]
which program are you talking about ---  examples/eval_model.py ?

**Comment by alexholdenmiller** [comment]
@Jackberg I personally do a fair amount of quick runs with only the --dict-file arg set and no model file (don't want to keep the model params but do want it to set up a dictionary).

We should probably find a way to force building / saving / loading more explicitly, but with the current setup it needs some finagling for that.

**Comment by Jackberg** [comment]
@jaseweston I'm using `example/train_model.py`.

**Comment by Jackberg** [comment]
@alexholdenmiller I didn't notice there's such a parameter `--dict-file` since I just found this repo yesterday 😆 

It's really a great work, with all those parameters adjustable, but some of them need stronger check.
