### ISSUE TITLE
Reproducing results in the "Personalizing Dialogue Agents" paper.

### ISSUE THREAD

**Issue by dimeldo** [facebookresearch/ParlAI#570]
Hi, I'm opening this issue in order to track the progress of uploading the necessary files for reproducing the results in the paper "Personalizing Dialogue Agents".

**Comment by emilydinan** [comment]
https://github.com/facebookresearch/ParlAI/pull/611 adds some of the generative models from the paper as well as scripts to interact/evaluate with pretrained models and scripts to train models.

**Comment by jaseweston** [comment]
#639 adds KVMemNN interactive example + eval script

**Comment by jaseweston** [comment]
https://github.com/facebookresearch/ParlAI/pull/662 adds KVMemNN training script

**Comment by jaseweston** [comment]
going to close this task as we've added most of the models now, yay!
