### ISSUE TITLE
Connecting ParlAI to Slack/or other service

### ISSUE THREAD

**Issue by dlozier** [facebookresearch/ParlAI#571]
I'd like to use ParlAI to connect Turkers to a team of local agents. Does ParlAI on the Turker side connect to something like Slack, Zendesk or a similar alternative that our own internal agents couls use?

**Comment by JackUrb** [comment]
Hi @dlozier - for now we support using Facebook Messenger as another way to get real human agents into ParlAI worlds, but there's no simple linkage. You could spin up a task using both an `MTurkManager` and a `MessengerManager` and then linking the `run_conversation` functions for each by having them add workers to respective Messenger and MTurk pools. You can then have a worker thread that pops from those pools and launches a thread to run a world with one of each agent type. That process may be a little tricky to build, but it should be feasible.

I'd like to add functionality to the MessengerAgents to allow them to be used without manually setting up a messenger manager for each task soon (in the next 2 weeks?).

Slack also seems like an interesting use case that we don't support yet, however it should be possible to make an agent that links up observe and act to the slack API. You may be able to modify the `MessengerManager` and `MessengerAgent` files to make Slack versions that work for your use case, as I'm not sure when I'd get a chance to try that out myself.

**Comment by stephenroller** [comment]
This is out of scope for now, so closing this issue. We may revisit this in the future, and would happily receive pull requests at any time.
