### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by deshraj** [facebookresearch/ParlAI#575]
Just tried to run the latest version of ParlAI (master branch) and it seems to break. 

Here is the error log while trying to run the model evaluator task:

```
deshraj at lawn-128-61-36-6 in ~/Documents/pai/parlai/mturk/tasks/model_evaluator on master
$ python run.py -na 2 -r 0.00 --sandbox
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from parlai.core.params import ParlaiParser
  File "/Users/deshraj/Documents/pai/parlai/core/params.py", line 14, in <module>
    from parlai.core.agents import get_agent_module, get_task_module
  File "/Users/deshraj/Documents/pai/parlai/core/agents.py", line 40, in <module>
    from .metrics import Metrics, aggregate_metrics
  File "/Users/deshraj/Documents/pai/parlai/core/metrics.py", line 12, in <module>
    from parlai.core.utils import round_sigfigs, no_lock
  File "/Users/deshraj/Documents/pai/parlai/core/utils.py", line 11, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

Related to #551. Would be great if we can version ParlAI package otherwise I have to add the commit hash manually to use it as a package.

**Comment by emilydinan** [comment]
Hi @deshraj -- looks like I had introduced a pytorch dependency in parlai/core/utils.py. This PR will fix https://github.com/facebookresearch/ParlAI/pull/577/ when it is merged. I'll keep you updated.

**Comment by emilydinan** [comment]
@deshraj should be fixed now

**Comment by deshraj** [comment]
Awesome. Thanks @emilydinan :) It worked perfectly now.
