### ISSUE TITLE
Question about result of "Personalized Dialogue Agent" paper.

### ISSUE THREAD

**Issue by trivi9ri** [facebookresearch/ParlAI#584]
Hello, I have a question about the result of the 'Personalized Dialog Agent' paper. 
I want to reproduce result of this paper. 
I already tried several time, but I don't know how can I do that.
Could you let me know which parameters should be used to see the result?

**Comment by jaseweston** [comment]
Which model are you talking about? 
See also: https://github.com/facebookresearch/ParlAI/issues/540 for some info.
We are in the process of getting all the models online.

**Comment by jaseweston** [comment]
This issue will be used for tracking: https://github.com/facebookresearch/ParlAI/issues/570
so closing this issue right now as duplicate.

**Comment by trivi9ri** [comment]
Thank you!  Could you let me know parameters used for ranking model in paper?

**Comment by jaseweston** [comment]
Yes, we are trying to get all these models online soon. Will let you know.
