### ISSUE TITLE
I have some questions about metric modification and personachat task

### ISSUE THREAD

**Issue by ChanghoPaeon** [facebookresearch/ParlAI#586]
1. At #569 
 @emilydinan modify 'update_ranking_metrics' method of metric class. So now, hits@k doesn't calculated for seq2seq.  But I think that 'hits@1' is meaningful for generative model . Could you explain for me why source modified?

2. Personachat paper 
In the paper ' Personalizing Dialogue Agents: I HAVE A DOG, DO YOU HAVE PETS TOO?' ,  authors used hits@1 as metric for generative model.  But now, hits@1 doesn't calculate for seq2seq. Will the paper be modified?

**Comment by emilydinan** [comment]
@ChanghoPaeon 

1) The Seq2Seq model does indeed still calculate the hits@1, however, you need to specify the flag `--rank-candidates True` when you train. Then, you will see all of the hits@k metrics during validation and testing.

2)We are using a different Seq2Seq model in that paper than the one in ParlAI.

**Comment by alexholdenmiller** [comment]
Note that the hits@1 you were seeing for seq2seq when rank-candidates was false (the default) was the same as accuracy.
