### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Jackberg** [facebookresearch/ParlAI#596]
1. There's a bug when using attention layer. In this line:
https://github.com/facebookresearch/ParlAI/blob/55fcf6127309f3c0e2f15c1fe6eae1fd71afcbcb/parlai/agents/seq2seq/modules.py#L80
new `hidden` states are returned, but never used for getting next prediction. This is the reason why attention model performs extremely bad.  Here's the result for just 30 mins training:
```
TEXT:  I get to read the articles of extradition acordind to the European Court of human rights .
PREDICTION:  i was just a little bit of a lot of people .
~
TEXT:  Yes , you are the very monster I created
PREDICTION:  i will be a good thing
~
TEXT:  Hello , detective Spooner .
PREDICTION:  i don' t know .
~
TEXT:  I' m a tiger .
PREDICTION:  i don' t know .
~
TEXT:  What' ve you got ?
PREDICTION:  i don' t know .
~
TEXT:  We are going to change the way we see the road .
PREDICTION:  i don' t know what you are .
```
What's more, attention model (using `local` for Twitter and `general` for Opensubtitles) can really make loss lower.

2. The default value of lookuptable
https://github.com/facebookresearch/ParlAI/blob/55fcf6127309f3c0e2f15c1fe6eae1fd71afcbcb/parlai/agents/seq2seq/seq2seq.py#L107
will cause much more memory usage, but I didn't find out the reason. Old value `all` works fine.

3. In this line of `vectorize()` function,
https://github.com/facebookresearch/ParlAI/blob/55fcf6127309f3c0e2f15c1fe6eae1fd71afcbcb/parlai/agents/seq2seq/seq2seq.py#L403
it only returns 6 values, but newer version needs 7.

**Comment by alexholdenmiller** [comment]
1) wow, thanks. that was some copypasta from the line above it but was really hurting training with attention. thanks for the catch.

2) `unique` uses 3x more memory than `all`, intentionally. `all` shares the same tensor for the `weight` of the encoder Embedding layer, the decoder Embedding layer, and the final Linear layer producing an output token. `unique` keeps them separate, and `enc_dec` and `dec_out` share the mentioned pairs.

3) fixing, thanks.

**Comment by Jackberg** [comment]
> unique uses 3x more memory than all, intentionally. 
I see... But 3x more is a tremendous amount. Any methods to reduce memory usage?

**Comment by alexholdenmiller** [comment]
Well, it just depends on how big your embedding table is. If you don't have a large dictionary, it's `3 x [small number]`. So it's not always a tremendous cost.

But you do have a few options:
1) set `--dict-minfreq` to a higher number, or `--dict-maxtokens` to a lower number, as one dimension of the embedding weight is the number of tokens in your dictionary. also, consider sedding `--dict-lower true` to only use lowercased text, which will reduce the number of unique tokens in your dictionary.
2) set `--embedding-size` lower. this is the other dimension of the embedding weight.
3) consider the alternative modes of `--lookuptable`. `unique` is the most general. `enc_dec` might be good when your inputs and outputs have similar distribution. `dec_out` might be good when you want to select outputs words based on their meaning (in the same context as when they are inputs into the decoder).  `all` might be good when both of the previous two settings hold. but these should be tested experimentally and may vary by dataset / other hyperparams. anything other than `unique` both reduces memory and the number of learned parameters.

**Comment by alexholdenmiller** [comment]
(closing because 1 and 3 are fixed, happy to discuss further though)

**Comment by dimeldo** [comment]
@Jackberg can you help me with something?
email me at solobo11235@gmail.com

**Comment by alexholdenmiller** [comment]
Adding IBM's seq2seq model if that's helpful for comparison: #601

**Comment by Jackberg** [comment]
Hi @alexholdenmiller , that's great! I tried that implementation before, but the memory leak bug made it less fascinating to me.
