### ISSUE TITLE
How to parse personachat dataset

### ISSUE THREAD

**Issue by fikrisyad** [facebookresearch/ParlAI#618]
I tried to use the dataset of Personalizing Dialogue Agents paper, but I couldn't figure how to parse the data.
Can someone please help me?

**Comment by jaseweston** [comment]
In ParlAI you can look at this dataset like any other dataset with:

python examples/display_data.py -t personachat

This downloads the data and displays it on screen, so you can follow that code..

**Comment by fikrisyad** [comment]
great, thank you!
