### ISSUE TITLE
Use action='store_true' in core params.

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/ParlAI#624]
That would make them essentially flags and won't require adding true in front of them.
For `-bsrt true` can be specified by `-bsrt`

**Comment by alexholdenmiller** [comment]
Hi @apsdehal! We intentionally used a custom bool operator instead of store-true for most params, as it was more compatible with some of our param sweeping code. (e.g. sweep over param -bsrt, with values true and false.) You can also use 1 or 0 for a little less typing.
