### ISSUE TITLE
Tf-idf retriever agent breaks on save when used with train_model example 

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/ParlAI#625]
As tf-idf retriever's save function expects only one parameter and in `train_model` example we call `self.agent.save(opt['model_file'] + '.checkpoint')` it fails with a typeerror.
![image](https://user-images.githubusercontent.com/3616806/37199628-30d795fa-2350-11e8-81a0-718cc0756f36.png)

I am happy to open up a PR for this. What is the expected fix?

**Comment by alexholdenmiller** [comment]
Thanks! fix up
