### ISSUE TITLE
SETC - a standard evaluation tool

### ISSUE THREAD

**Issue by jsedoc** [facebookresearch/ParlAI#646]
We have developed a standard evaluation tool for system comparison. This is in the alpha version.

There will be public checkpoints and preliminary results.

Please take a look [https://goo.gl/forms/26Wu13jYBpxWoAgx1](https://goo.gl/forms/26Wu13jYBpxWoAgx1)

This is a fully open source framework. Look at our code on [Github](https://github.com/jsedoc/SETC).

Amazon Mechanical Turk is not free... we are actively looking for funding.

**WARNING: This is extremely alpha code!!!**

**Comment by jsamson008** [comment]
That's awesome!

Can you send details as to where to locate the checkpoints, and elaborate the README?

**Comment by jsedoc** [comment]
@jsamson008 please see this [link](http://chatbot-eval-data.s3-accelerate.amazonaws.com/results/available_checkpoints.txt) for checkpoints.

**Comment by jsedoc** [comment]
@alexholdenmiller 
would you be interested in talking about SETC with me? I think we will apply for ACL demo and I'd love to get some feedback.
