### ISSUE TITLE
Custom HTML Doesn't work

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#670]
I'm trying to implement a custom HTML page for the multiagent dialog. I make sure the ID's are set (I leave the default values):

![screen shot 2018-03-30 at 2 27 24 pm](https://user-images.githubusercontent.com/25429471/38154486-1a750418-3427-11e8-88c5-16b52d264090.png)

Then, I add the appropriate files:

![screen shot 2018-03-30 at 2 29 21 pm](https://user-images.githubusercontent.com/25429471/38154503-26e25372-3427-11e8-90d3-ef33065b8f45.png)

But for some reason the custom pages do not work. Am I missing anything?

**Comment by JackUrb** [comment]
Hi @josharnoldjosh - sorry for the delay here. It seems you've just slightly mis-named the html files. The title is `<mturk_agent_id>_index.html`. See the `personachat_chat` folder for an example.

**Comment by josharnoldjosh** [comment]
Thank you @JackUrb!
