### ISSUE TITLE
The code in Seq2Seq tutorial lead a memory problem

### ISSUE THREAD

**Issue by EdwardYam** [facebookresearch/ParlAI#671]
I run the Seq2Seq code in the official tutorial. [http://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html](url)

I find that the memory usage increase in each iteration. It is not obvious in the code since its iteration time is small. When I set the iteration time to be a large number, the memory will increase continuously. How can I solve this problem?

**Comment by jaseweston** [comment]
This sounds like a pytorch issue, not a ParlAI issue (not the parlAI repo)? 
We do have seq2seq models, have you tried those?
Closing this for now.
