### ISSUE TITLE
Movie dialog task's Task 3 QA Recs is missing dev set

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/ParlAI#672]
```
[Errno 2] No such file or directory: '<ParlAI_folder>/data/MovieDialog/movie_dialog_dataset/task3_qarecs/task3_qarecs_dev.txt'.
``` 

After looking into the folder, it only contains file for training set.

**Comment by jaseweston** [comment]
cannot reproduce,

I did:

py examples/display_data.py -t "#MovieDD-QARecs"

and it downloaded all the data, and worked:

ls data/MovieDialog/movie_dialog_dataset/task3_qarecs/
task3_qarecs_dev.txt  task3_qarecs_test.txt  task3_qarecs_train.txt

Perhaps try deleting the entire contents of the directory data/MovieDialog so it can redownload?

**Comment by apsdehal** [comment]
Trying that. Will let you know.

**Comment by apsdehal** [comment]
Works. Thanks.
