### ISSUE TITLE
Trivial issue: Unnecessary loops?

### ISSUE THREAD

**Issue by Jackberg** [facebookresearch/ParlAI#720]
I noticed some unnecessary loops, e.g. these snippets:
https://github.com/facebookresearch/ParlAI/blob/25a19b8559e513105c956d8d8f09ff71e7e370d4/parlai/core/worlds.py#L660-L662
https://github.com/facebookresearch/ParlAI/blob/25a19b8559e513105c956d8d8f09ff71e7e370d4/parlai/core/worlds.py#L668-L670

When you're using, say seq2seq model, with 2 agents, these `if` statements will be hit `3*batch_size` times in each parley, but the body will never be executed. For a task with huge dataset, I think these snippets will consume considerable time.

I wonder if there are situations that these `if` statements will be true for just a subset of the batch worlds? If not, maybe add an `else` statement to end the loop earlier will slightly reduce the training time?
```
else:
    break
```

**Comment by alexholdenmiller** [comment]
Thanks for the suggestion! I tried using different batch sizes just to display the data and couldn't find any difference in the runtime unfortunately, but the worlds are the same type as the initial world so it's safe to make the change anyways. (#740)
