### ISSUE TITLE
Tensor Type Error

### ISSUE THREAD

**Issue by haow85** [facebookresearch/ParlAI#743]
I tried the following command : 

`python train_model.py -m seq2seq -t babi:task1k:1 -bs 8 -eps 1 -mf /tmp/model_s2s`

and I met the following error :

`
[ training... ]
/chatbot/parlai/ParlAI/parlai/agents/seq2seq/seq2seq.py:463: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  target_tokens = ys.ne(self.NULL_IDX).long().sum().data[0]
/chatbot/parlai/ParlAI/parlai/agents/seq2seq/seq2seq.py:464: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  self.metrics['loss'] += loss.double().data[0]
Traceback (most recent call last):
  File "train_model.py", line 279, in <module>
    TrainLoop(setup_args().parse_args()).train()
  File "train_model.py", line 242, in train
    world.parley()
  File "/chatbot/parlai/ParlAI/parlai/core/worlds.py", line 666, in parley
    batch_act = self.batch_act(agent_idx, batch_observations[agent_idx])
  File "/chatbot/parlai/ParlAI/parlai/core/worlds.py", line 639, in batch_act
    batch_actions = a.batch_act(batch_observation)
  File "/chatbot/parlai/ParlAI/parlai/agents/seq2seq/seq2seq.py", line 567, in batch_act
    predictions, text_cand_inds = self.predict(xs, ys, cands, valid_cands, is_training)
  File "/chatbot/parlai/ParlAI/parlai/agents/seq2seq/seq2seq.py", line 466, in predict
    loss /= target_tokens  # average loss per token
RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #3 'other'
`

**Comment by jaseweston** [comment]
this is a thing with different version of pytorch @emilydinan  @klshuster  @alexholdenmiller

**Comment by jaseweston** [comment]
We are trying to update to latest while being backward compatible
I think this issue might be fixed in :
https://github.com/facebookresearch/ParlAI/pull/741/files
but it isn't merged yet

**Comment by alexholdenmiller** [comment]
Yes we are merging this fix still, we're targeting pytorch 0.4

**Comment by alexholdenmiller** [comment]
merge in, the command works for me

**Comment by haow85** [comment]
I did a "git remote update" command at the git repository folder but still met the same error . It's still not working.

**Comment by haow85** [comment]
The code still doesn't work after updating the repository.

`(py36) [root@5426d00374dc ParlAI]# git remote update
Fetching origin
remote: Counting objects: 264, done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 264 (delta 166), reused 182 (delta 141), pack-reused 49
Receiving objects: 100% (264/264), 64.98 KiB | 0 bytes/s, done.
Resolving deltas: 100% (181/181), completed with 35 local objects.
From https://github.com/facebookresearch/ParlAI
   1e6b390..2838fa0  master     -> origin/master
 * [new branch]      batch_has  -> origin/batch_has
 * [new branch]      convai2_mturk -> origin/convai2_mturk
 * [new branch]      jaseweston-patch-1 -> origin/jaseweston-patch-1
 * [new branch]      movinon7   -> origin/movinon7
 * [new branch]      movinon8   -> origin/movinon8
 * [new branch]      torchtext_update -> origin/torchtext_update`

**Comment by alexholdenmiller** [comment]
from current master
`python train_model.py -m seq2seq -t babi:task1k:1 -bs 8 -eps 1 -mf /tmp/model_s2s`
work for me with pytorch 0.4.0

if you still have any errors please include the stack trace
