### ISSUE TITLE
Torch 0.4 migration

### ISSUE THREAD

**Issue by jsedoc** [facebookresearch/ParlAI#749]
Is there an ETA for the migration to torch 0.4?

**Comment by jsedoc** [comment]
I actually use ParlAI for a lot, so seq2seq, language_model, MemNN, Fairseq, and starspace

**Comment by alexholdenmiller** [comment]
seq2seq and lm should be good, fairseq will be a little longer as we need to update to current fairseq not just update for pytorch 0.4 (significant changes to the current agent). memnn and starspace might be behind but are probably easy to fix if you want to submit a PR :)

**Comment by zhaoguangxiang** [comment]
What about persona-chat and convAI2?

**Comment by jsedoc** [comment]
upvote for both.

Also, for the LM and seq2seq, is there a 0.4 branch to pull from?

**Comment by alexholdenmiller** [comment]
@jsedoc for lm and seq2seq, should be good on master

for the kvmemnn and persona_seq2seq models, same status as memnn and starspace--will do when we can!

**Comment by alexholdenmiller** [comment]
fix for memnn: #781

**Comment by jaseweston** [comment]
fix for starspace https://github.com/facebookresearch/ParlAI/pull/786

**Comment by alexholdenmiller** [comment]
all models mentioned in this thread except for fairseq are updated. going to close for a fairseq specific thread.
