### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by iamShantanu101** [facebookresearch/ParlAI#75]
Add Dockerfile and a docker image which might make trying out ParlAI easier.

**Comment by chetkhatri** [comment]
@iamShantanu101 Sure, we are working on that.

CC/ @alexholdenmiller

**Comment by alexholdenmiller** [comment]
Low priority for the moment, but will add when we get the chance.

**Comment by alexholdenmiller** [comment]
closing for now without dockerfile support
