### ISSUE TITLE
What is the format of model file such as squad.mdl ?

### ISSUE THREAD

**Issue by haow85** [facebookresearch/ParlAI#757]
What is the format of the model file such as squad.mdl ?

**Comment by alexholdenmiller** [comment]
from parlai/agents/drqa/model.py:
```
def save(self, filename):
        params = {
            'state_dict': {
                'network': self.network.state_dict(),
            },
            'feature_dict': self.feature_dict,
            'config': self.opt,
        }
        try:
            torch.save(params, filename)
        except BaseException:
            logger.warn('[ WARN: Saving failed... continuing anyway. ]')
```

**Comment by jaseweston** [comment]
Yes, that's the format of the original SQuAD data, we just parse it.
In many other datasets we use a standard simple text format:
https://github.com/facebookresearch/ParlAI/blob/master/parlai/core/teachers.py#L867
We will update the doc to make this clearer.
