### ISSUE TITLE
'parlai.tasks.babi.agents' has no attribute create_agents

### ISSUE THREAD

**Issue by attardi** [facebookresearch/ParlAI#768]
Invoking:

    python3 examples/display_data.py -t babi:task1k:1

This just after cloning the master and issuing

    pip3 install -r requirements.txt
    python3 setup.py install

**Comment by alexholdenmiller** [comment]
Thanks for reporting! Can you post the full stack trace? That error is expected and caught, there should be another one.

**Comment by attardi** [comment]
It seems to be a problems with permissions.
I fixed it by doing:

     sudo mkdir /usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/data
     sudo chmod o+w /usr/local/lib/python3.5/dist-packages/parlai-0.1.0-py3.5.egg/data

**Comment by alexholdenmiller** [comment]
Ah I see, it’s because you did “install” instead of “develop” which uses the local directory for the installation
