### ISSUE TITLE
questions about baselines of convai2 and personachat

### ISSUE THREAD

**Issue by zhaoguangxiang** [facebookresearch/ParlAI#769]
Are the baselines based on 'self persona' or 'No persona', what is the goal of the task, to make use of persona profile or to learn the persona.

**Comment by jaseweston** [comment]
they use self persona. the goal is to converse, conditioned on your own
persona (same for humans or bots). the evaluation criteria are ppl or
hits@1.

**Comment by zhaoguangxiang** [comment]
Thank you, there are several papers that try to learn agent's personality from the conversation history. what do think of the difference between your personality, history, and context.

**Comment by jaseweston** [comment]
Please see the paper for analysis: https://arxiv.org/abs/1801.07243

**Comment by alexholdenmiller** [comment]
closing for now, feel free to reopen or open another issue if you have any further questions!
