### ISSUE TITLE
How can I implement a way for HTML data to communicate with the python scripts?

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#794]
Hello,

I want to implement a pretask survey for the personachat demo. I've altered the HTML for the onboarding.html page to look like so:

<img width="1899" alt="screen shot 2018-05-29 at 7 26 31 pm" src="https://user-images.githubusercontent.com/25429471/40699356-9f8762be-6388-11e8-9c76-2dc3422f046d.png">

However, I am not sure how the users response can communicate with the python script. My goal is to save a PKL file with the user ID and it's survey results. 

I saw ParlAI uses websockets to accomplish this and prority queues, but I'm not sure the exact way to implement this. 

Could someone provide a few general steps on how I could best accomplish this task?

Thank you for your time,
Josh

**Comment by emilydinan** [comment]
Hi Josh! If I understand what you're saying, you want to send a packet. For instance, here we call `send_packet` when the user clicks the "Done" button and send a message with this information: https://github.com/facebookresearch/ParlAI/blob/c034a9ac242cd2018254cdcaa10fff02cca92af0/parlai/mturk/tasks/convai2_model_eval/html/PERSON_1_index.html#L91. 

On the python side, you will call something like `act = mturk_agent.act(timeout=<TIMEOUT>)` and `act` will contain the information from the act (in the case I pointed to above, it will contain a dict like `{'text': "I am done with the chat and clicked the 'Done' button, thank you!", episode_done: True}`).

**Comment by alexholdenmiller** [comment]
closing this for now, feel free to reopen if you need more help!
