### ISSUE TITLE
Index Error when trying to train ConvAI2 profilememory baseline

### ISSUE THREAD

**Issue by christqoh** [facebookresearch/ParlAI#808]
[profilememory_log.txt](https://github.com/facebookresearch/ParlAI/files/2067419/profilememory_log.txt)
Original exception was:
Traceback (most recent call last):
[...]
  File "/home/ParlAI/projects/personachat/persona_seq2seq.py", line 1811, in _decode_and_train
    self.loss += loss.data.cpu().numpy()[0]
IndexError: too many indices for array

This unsurprisingly also comes up when trying to train in the personachat project. Any ideas?

**Comment by emilydinan** [comment]
We need to call `.item()` instead of `.data[0]` in pytorch 0.4: see PR #810 for fix.
