### ISSUE TITLE
wmt - agent.py loaded train file in validate

### ISSUE THREAD

**Issue by avr248** [facebookresearch/ParlAI#809]
To fix, I made a change as follows:
LIne 28:  opt['datafile'] = _path(self.task_name, opt, **'train'**)
Need to change to:
LIne 28:  opt['datafile'] = _path(self.task_name, opt, opt['datatype'])

**Comment by jaseweston** [comment]
thanks, updated: 
https://github.com/facebookresearch/ParlAI/blob/master/parlai/tasks/wmt/agents.py
