### ISSUE TITLE
Name server pointing to http://parl.ai

### ISSUE THREAD

**Issue by chetkhatri** [facebookresearch/ParlAI#81]
Currently Name server pointing is not established would be good to have parl.ai -> http://ec2-35-162-199-80.us-west-2.compute.amazonaws.com/

**Comment by alexholdenmiller** [comment]
yes we're just waiting for the nameserver cache to expire, should be updated soon! mine is pointed to the right nameserver now

**Comment by chetkhatri** [comment]
@alexholdenmiller good !

**Comment by chetkhatri** [comment]
@alexholdenmiller Did Source code static html is part of github ? http://ec2-35-162-199-80.us-west-2.compute.amazonaws.com/
