### ISSUE TITLE
Optimizer Adam Runtime Error

### ISSUE THREAD

**Issue by christqoh** [facebookresearch/ParlAI#813]
[profilememory.txt](https://github.com/facebookresearch/ParlAI/files/2068837/profilememory.txt)

using CUDA on GCP I get this:

  File "/lib/python3.6/site-packages/torch/optim/adam.py", line 92, in step
    exp_avg.mul_(beta1).add_(1 - beta1, grad)
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #4 'other'

presumably (also) related to torch 0.4.0?!

**Comment by emilydinan** [comment]
Hi @christqoh this looks unrelated to torch 0.4. An argument is being passed to the optimizer that it expects to be on cpu but that is on gpu. Can you send me the command you run so I can try to reproduce?

**Comment by christqoh** [comment]
Hi @emilydinan I run python projects/convai2/baselines/profilememory/train.py. Occures with and without fourth parser args

**Comment by uralik** [comment]
@christqoh seems like you loading some existing model from /tmp:
Loading existing model params from /tmp/profilememconvai2

if this is not intended, can you try to delete existing model and re-run? maybe that model does not get on gpu when you load it (if it was saved in gpu-free training mode)

**Comment by christqoh** [comment]
that might have been it @uralik rebooting the GCP did the trick for me. however, there shouldn't be a non-gpu model on there ...

**Comment by christqoh** [comment]
just to confirm, I double checked that: trained model on GCP (worked fine), aborted training, tried training again... issue as above.

**Comment by emilydinan** [comment]
The optimizer is not being pushed back to gpu after the model is loaded; see PR #815 for fix

**Comment by christqoh** [comment]
looking good. Also fixed an issue where training aborted due to overflow later on.
