### ISSUE TITLE
Fine-tuning pretrained models

### ISSUE THREAD

**Issue by christqoh** [facebookresearch/ParlAI#823]
So my goal is to fine-tune the pretrained profilememory convai2 model. I got stuck while looking for the according flags.

Regarding flags:
- in scripts/train_model.py there is the -lfc flag to load from checkpoint. 
- i.e. in agents/seq2seq/seq2seq.py there is --init-model which is explicitly for fine-tuning according to #595 

lfc is not doing the job for me. Could add the --init-model flag to the scripts/train_model.py to achieve global functionality or show another way on how to achieve the fine-tuning? 

Also, is there a way to define the path the model is loaded from?

**Comment by emilydinan** [comment]
The `-lfc` flag looks for a model saved at `<model file>.checkpoint`. You can use the model file flag (`-mf` or `--model-file`) to specify the path to load the model from. `--init-model` has a similar functionality: if you specify this and also specify a model file (that does not exist yet), it will load the model from the init model but save to the model file.

**Comment by alexholdenmiller** [comment]
If you're just looking to fine-tune our pretrained convai2 model, you can do the following:

```
# download the pretrained model, you can cancel the evaluation once it starts
python ~/ParlAI/projects/convai2/baselines/profilememory/eval_f1.py
# copy pretrained model to the default model_file location set by train.py, this will prevent you from over-writing the pretrained model file as you're training
cp ~/ParlAI/data/models/convai2/profilememory/profilememory_convai2_model /tmp/profilememconvai2
# train the model using the premade dictionary, will load the pretrained model from /tmp/profilememconvai2
python ~/ParlAI/projects/convai2/baselines/profilememory/train.py --dict-file models:convai2/profilememory/profilememory_convai2.dict
```

**Comment by alexholdenmiller** [comment]
Closing for now, feel free to reopen if you have any more questions!

**Comment by christqoh** [comment]
fine-tuning according to @alexholdenmiller's suggestions works fine. however, when I try fine-tuning using --model-file (pointing to your pretrained version) I run into errors presumably related to the dict size: 

`[ dictionary built with 19260 tokens ]`
`RuntimeError: Error(s) in loading state_dict for Embedding:
	While copying the parameter named "weight", whose dimensions in the model are torch.Size([19260, 300]) and whose dimensions in the checkpoint are torch.Size([18803, 300]).`

**Comment by alexholdenmiller** [comment]
To use the previous pretrained model, you'll need to build the dictionary using `--dict-include-valid False` and `-tok split` to have the same dictionary size. The model doesn't take *that* long to train (trained that previous model in < 2 hrs, and we just sped up the model so if you pull again it should train even faster), however, so I wouldn't be too afraid to train from scratch using the current tokenizer (`-tok re` is default now). Up to you if you want to have UNK's in the validation set or not (i.e. whether you use `--dict-include-valid` set to true or false).

**Comment by christqoh** [comment]
thanks Alex. could you give me a hint about your hardware? I am using a K80 on GCP and I feel like to process takes rather long. also, is there a metric providing information about the epochs trained rather than just the physical time?

**Comment by alexholdenmiller** [comment]
I used a GP100 so definitely faster. not sure exactly how many epochs, I'll run a quick train and let you know.

**Comment by alexholdenmiller** [comment]
I got down to competitive results (31 model-ppl during valid) at 54 minutes / 6 epochs.

(side note: at 90 min / 10 epochs it actually has continued to improve to a few points better than I had gotten in the past)

**Comment by christqoh** [comment]
thanks @alexholdenmiller for getting back to me. And that was using the given settings?

**Comment by alexholdenmiller** [comment]
yes I just ran:
`python ~/ParlAI/projects/convai2/baselines/seq2seq/train.py -bs 128 -vtim -1 -veps 1`

Hm I don't usually see the model ever produce start tokens, did you change anything about the model before beginning training? it also doesn't see any unk tokens during training (unless you changed the params), so that doesn't look right either.

**Comment by alexholdenmiller** [comment]
ah pardon me I thought you were training the vanilla seq2seq baseline for convai2 not the profilememory model
