### ISSUE TITLE
Interactive mode on non-CUDA device

### ISSUE THREAD

**Issue by christqoh** [facebookresearch/ParlAI#831]
Hey guys,
I get `AttributeError: module 'torch._C' has no attribute '_cuda_getDevice'` when running `python projects/convai2/baselines/profilememory/interactive.py ` on a non CUDA device (pretrained models have been downloaded). Could you fix this? Would increase usability of models a lot.
Thanks!

**Comment by emilydinan** [comment]
Hi @christqoh the fix is contained in PR #832

**Comment by alexholdenmiller** [comment]
closing for now since that was merged, feel free to reopen if issues persist
