### ISSUE TITLE
module 'library.PositionalEncoder' not found

### ISSUE THREAD

**Issue by atav32** [facebookresearch/ParlAI#84]
Tried to debug https://github.com/facebookresearch/ParlAI/issues/58 by testing the *LuaJIT* installation with `luajit -e "require 'library.PositionalEncoder'"` from https://github.com/facebookresearch/ParlAI/issues/58#issuecomment-300208728.

Received the following error

```
~/code/ParlAI> luajit -e "require 'library.PositionalEncoder'"
luajit: (command line):1: module 'library.PositionalEncoder' not found:
        no field package.preload['library.PositionalEncoder']
        no file '/Users/brian/.luarocks/share/lua/5.1/library/PositionalEncoder.lua'
        no file '/Users/brian/.luarocks/share/lua/5.1/library/PositionalEncoder/init.lua'
        no file '/Users/brian/torch/install/share/lua/5.1/library/PositionalEncoder.lua'
        no file '/Users/brian/torch/install/share/lua/5.1/library/PositionalEncoder/init.lua'
        no file './library/PositionalEncoder.lua'
        no file '/Users/brian/torch/install/share/luajit-2.1.0-beta1/library/PositionalEncoder.lua'
        no file '/usr/local/share/lua/5.1/library/PositionalEncoder.lua'
        no file '/usr/local/share/lua/5.1/library/PositionalEncoder/init.lua'
        no file '/Users/brian/torch/install/lib/library/PositionalEncoder.dylib'
        no file '/Users/brian/.luarocks/lib/lua/5.1/library/PositionalEncoder.so'
        no file '/Users/brian/torch/install/lib/lua/5.1/library/PositionalEncoder.so'
        no file '/Users/brian/torch/install/lib/library/PositionalEncoder.dylib'
        no file './library/PositionalEncoder.so'
        no file '/usr/local/lib/lua/5.1/library/PositionalEncoder.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/Users/brian/torch/install/lib/library.dylib'
        no file '/Users/brian/.luarocks/lib/lua/5.1/library.so'
        no file '/Users/brian/torch/install/lib/lua/5.1/library.so'
        no file '/Users/brian/torch/install/lib/library.dylib'
        no file './library.so'
        no file '/usr/local/lib/lua/5.1/library.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x01000016c0
```

**Comment by alexholdenmiller** [comment]
that relative import is run from within the KVmemnn directory--does that command work from `~/code/ParlAI/downloads/MemNN/KVmemnn/` ?

**Comment by alexholdenmiller** [comment]
If not, then from within that directory, try running `setup.sh` and trying it again

**Comment by atav32** [comment]
thanks for fast response 😃 

unfortunately, I don't have a `~/code/ParlAI/downloads/` directory?

**Comment by nirmal070125** [comment]
I'm getting following error when executing the command from ```ParlAI/downloads/MemNN/KVmemnn/ ```
`$ luajit -e "require 'library.PositionalEncoder'"`
`
luajit: ./library/PositionalEncoder.lua:10: dlopen(libmemnn.so, 5): image not found
stack traceback:
	[C]: in function 'load'
	./library/PositionalEncoder.lua:10: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: at 0x010e8841e0
`

Seems it's hanging at training (can't see any CPU usage);
`
$ python examples/memnn_luatorch_cpu/full_task_train.py -t babi:task10k:1 -nt 8
/Users/nirmal/torch/install/bin/luajit
[datapath:/Volumes/wso2/git/ParlAI/data]
[num_its:100]
[remote_args:/Volumes/wso2/git/ParlAI/examples/memnn_luatorch_cpu/params_default.lua]
[dict_language:english]
[dict_unktoken:<UNK>]
[task:babi:task10k:1]
[no_images:False]
[datatype:train]
[dict_max_exs:10000]
[dict_nulltoken:<NULL>]
[port:5555]
[download_path:/Volumes/wso2/git/ParlAI/downloads]
[dict_max_ngram_size:-1]
[dict_minfreq:0]
[numthreads:8]
[batchsize:1]
[parlai_home:/Volumes/wso2/git/ParlAI]
[num_examples:1000]
[remote_cmd:luajit /Volumes/wso2/git/ParlAI/parlai/agents/memnn_luatorch_cpu/memnn_zmq_parsed.lua]
Setting up dictionary.
[creating task(s): babi:task10k:1]
[DialogTeacher initializing.]
[loading fbdialog data:/Volumes/wso2/git/ParlAI/data/bAbI/tasks_1-20_v1-2/en-valid-10k-nosf/qa1_train.txt]
Dictionary building on train:ordered data.
[creating task(s): babi:task10k:1]
[DialogTeacher initializing.]
[loading fbdialog data:/Volumes/wso2/git/ParlAI/data/bAbI/tasks_1-20_v1-2/en-valid-10k-nosf/qa1_valid.txt]
Dictionary building on valid data.
Dictionary: saving dictionary to /tmp/dict.txt.
Dictionary ready, moving on to training.
python thread connected to tcp://localhost:5555
[creating task(s): babi:task10k:1]
[DialogTeacher initializing.]
[loading fbdialog data:/Volumes/wso2/git/ParlAI/data/bAbI/tasks_1-20_v1-2/en-valid-10k-nosf/qa1_train.txt]
luajit: ...downloads/memnnlib/KVmemnn/library/PositionalEncoder.lua:10: dlopen(libmemnn.so, 5): image not found
stack traceback:
	[C]: in function 'load'
	...downloads/memnnlib/KVmemnn/library/PositionalEncoder.lua:10: in main chunk
	[C]: in function 'require'
	...arlAI/downloads/memnnlib/KVmemnn/library/memnn_model.lua:15: in main chunk
	[C]: in function 'require'
	...it/ParlAI/examples/memnn_luatorch_cpu/params_default.lua:16: in main chunk
	[C]: in function 'dofile'
	...AI/parlai/agents/memnn_luatorch_cpu/memnn_zmq_parsed.lua:75: in main chunk
	[C]: at 0x010a78d1e0
[DialogTeacher initializing.]
[creating task(s): babi:task10k:1]
[DialogTeacher initializing.]
[DialogTeacher initializing.]
[DialogTeacher initializing.]
[DialogTeacher initializing.]
[DialogTeacher initializing.]
[DialogTeacher initializing.]
[DialogTeacher initializing.]
[DialogTeacher initializing.]
[loading fbdialog data:/Volumes/wso2/git/ParlAI/data/bAbI/tasks_1-20_v1-2/en-valid-10k-nosf/qa1_valid.txt]
python thread connected to tcp://localhost:5556
python thread connected to tcp://localhost:5558
python thread connected to tcp://localhost:5557
python thread connected to tcp://localhost:5561
python thread connected to tcp://localhost:5563
python thread connected to tcp://localhost:5560
python thread connected to tcp://localhost:5559
python thread connected to tcp://localhost:5562
[ training ]
`

**Comment by alexholdenmiller** [comment]
Ah yes, I posted a reply on the other thread!

If you enter the `luajit` interactive mode and execute `print(package.path)`, you should see the path that the libmemnn.so file is symlinked to in your path.

**Comment by nirmal070125** [comment]
Running setup.sh as mentioned in the other thread solved the issue. Thanks.

**Comment by alexholdenmiller** [comment]
closing for now, feel free to reopen if still having issues @atav32
