### ISSUE TITLE
Are the baselines of ConvAI2 on the leaderboard single turn chat?

### ISSUE THREAD

**Issue by zhaoguangxiang** [facebookresearch/ParlAI#840]
I run the train.py of persona_seq2seq, kvmmnn,seq2seq and print the observations , the results show that they are single  turn dialogue.

**Comment by alexholdenmiller** [comment]
Observations are often given to agents a single turn at a time, but the agents can remember the past turns (they do this using the "maintain_dialog_history" function, which we are in the process of updating to a cleaner implementation).
Each model is allowed to do whichever it prefers, but for example the seq2seq model conditions on the entire conversation history (with the personas contained in the first exchange). In contrast, the persona-seq2seq model remembers the personas but forgets the dialog history except for the last utterance.

**Comment by zhaoguangxiang** [comment]
I can't find the  "maintain_dialog_history" function of persona-seq2seq

**Comment by zhaoguangxiang** [comment]
Oh, it is in utils.py

**Comment by zhaoguangxiang** [comment]
Is the "episode_done" of persona_seq2seq always true?

**Comment by alexholdenmiller** [comment]
When you train with `--batch-sort true`, the episodes are flattened so `episode_done` is always true. However, with `--batch-sort false` it will only be true at the end of each conversation (during the last exchange).

**Comment by zhaoguangxiang** [comment]
Thank you!
