### ISSUE TITLE
Seq2seq model loads glove vectors to parlai_home

### ISSUE THREAD

**Issue by fgvbrt** [facebookresearch/ParlAI#844]
Hello, I would like to suggest improvement for seq2seq model. 
In this model you download glove/fasttext vectors in parlai home directory:
https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/seq2seq/seq2seq.py#L252

But for example glove vectors after downloading and extracting occupy about 10 GB which is quite a lot. I thinks that it would be better to add option for downloading it custom directory (for example specified  with datapath option, I also saw that you use this option in function modelzoo_path, so this option could be a good choice).

**Comment by alexholdenmiller** [comment]
Thanks you're right this should have been using the datapath, updating!

**Comment by alexholdenmiller** [comment]
Fixed!
