### ISSUE TITLE
MTurk run.py getting stuck at setting up Websockets

### ISSUE THREAD

**Issue by aanchan** [facebookresearch/ParlAI#846]
Hello,
I'm trying to run the sample qa_data_collection task that comes with ParlAI to post tasks on MTurk. After installing packages like sh, boto3, websockets. Creating and linking up MTurk accounts with AWS, and sigining into my Heroku account I try running `parlai/mturk/tasks/qa_data_collection/run.py`. It gets stuck at the last step (`Local: Setting up WebSocket`).

```[ optional arguments: ] 
[  datapath: /home/data2/work/ParlAI/data ]
[ Mechanical Turk: ] 
[  is_sandbox: True ]
[  num_conversations: 1 ]
[  unique_worker: False ]
[  verbose: False ]
[  task: None ]
[  allowed_conversations: 0 ]
[  block_qualification:  ]
[  is_debug: False ]
[  max_connections: 30 ]
[  reward: 0.05 ]
[  mturk_log_path: /home/data2/work/ParlAI/logs/mturk ]
[  count_complete: False ]
[  min_messages: 0 ]
[  unique_qual_name: None ]
[  log_level: 20 ]
[  hard_block: False ]
[  local: False ]

You are going to allow workers from Amazon Mechanical Turk to be an agent in ParlAI.
During this process, Internet connection is required, and you should turn off your computer's auto-sleep feature.
Enough HITs will be launched over time up to a max of 1.5 times the amount requested until the desired number of conversations start.
Please press Enter to continue... 

Setting up MTurk server...
Heroku: Collecting files...
Heroku: Starting server...
 ›   Warning: token will expire 06/11/2019
 ›   Use heroku authorizations:create to generate a long-term token
Creating polaris-fbd1a9ed-qadatacollect... done
Enabling http-session-affinity for polaris-fbd1a9ed-qadatacollect... done
Scaling dynos... done, now running web at 1:Free
MTurk server setup done.

Creating HITs...
Link to HIT: https://workersandbox.mturk.com/mturk/preview?groupId=3WO7ZNC6SLFV4SNPQ9NFFS9R9BRD8I

Waiting for Turkers to respond... (Please don't close your laptop or put your computer into sleep or standby mode.)

Local: Setting up WebSocket...
```

On the MTurk page it displays the first screen displaying the example, before the user hits accept, and then it shows the following screen.
![selection_029](https://user-images.githubusercontent.com/3464128/41272252-463215d8-6dc9-11e8-806d-5322e8d5c30c.png)

**Comment by aanchan** [comment]
Logger information appears on this line : 
https://github.com/facebookresearch/ParlAI/blob/374d59c857ed9a67651a1fd63ab8efe996364958/parlai/messenger/core/messenger_manager.py#L427

Does it assume that I have a Facebook dev account?

**Comment by JackUrb** [comment]
Hi @aanchan! It seems like you're caught somewhere between our two data collection methods - you don't need any Facebook-related info to use ParlAI-MTurk. That being said you are indeed getting caught up on a web socket setup step, but it's in MTurkManager rather than MessengerManager

**Comment by JackUrb** [comment]
Clan you try running with the flags `--verbose --debug` to see if the additional logs shed some light on what's happening?

**Comment by aanchan** [comment]
That helped. Here is the output.
```
Creating HITs...
Creating 2 hits...
https://aanchan-63718f4d-qadatacollect.herokuapp.com/chat_index?task_group_id=qa_data_collection_1528815463
Link to HIT: https://workersandbox.mturk.com/mturk/preview?groupId=3OXT046PA9GZ5BYL9SAMG27R7FSNLW

Waiting for Turkers to respond... (Please don't close your laptop or put your computer into sleep or standby mode.)

Local: Setting up WebSocket...
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
Socket error AttributeError("module 'websocket' has no attribute 'WebSocketApp'",), attempting restart
```

**Comment by aanchan** [comment]
I did a `pip install websocket-client` after reading [this](https://stackoverflow.com/questions/48730108/attributeerror-module-websocket-has-no-attribute-websocketapp-pip). It now says `Socket open: (<websocket._app.WebSocketApp object at 0x7f1115d46c88>,)`.  Is that the last step, or am I waiting on something else to happen? Not sure if a requirements.txt specifically for this module might help.

**Comment by aanchan** [comment]
Here were some of the additional installs.
Steps
======
1. python setup.py develop
2. pip install websocket-client
3. pip install joblib
4. pip install sh
5. pip install boto3
6. pip install websockets

**Comment by JackUrb** [comment]
Hi @aanchan - once the socket is open you're good to go! At that point you can use the worker sandbox to test out the HIT. 

With regards to ending up with the wrong websocket packet, how did you run across the dependency? You should've hit the messaging in [this](https://github.com/facebookresearch/ParlAI/blob/master/parlai/mturk/core/__init__.py) file, but if you got the info elsewhere I'll update the docs to note that the correct package is `websocket-client`.

**Comment by JackUrb** [comment]
Closing, as it appears the issue was resolved considering the websocket opened. @aanchan feel free to reopen if you're still having issue.
