### ISSUE TITLE
A potential typo

### ISSUE THREAD

**Issue by i-lovelife** [facebookresearch/ParlAI#849]
Hi, I'm puzzled about the following code, in line 216, `states = self.load(opt['model_file'])` seems should be `states = self.load(init_model)` beacuse I don't see anywhere else load the init_model. Is this a typo or intented?
https://github.com/facebookresearch/ParlAI/blob/0446621ca30aa80102104a1e4ab266559bafd128/parlai/agents/seq2seq/seq2seq.py#L205-L216

**Comment by jaseweston** [comment]
hmm looks suspicious, @alexholdenmiller  ?

**Comment by alexholdenmiller** [comment]
thanks for flagging, committed the fix!
