### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'luajit

### ISSUE THREAD

**Issue by qinghua2016** [facebookresearch/ParlAI#87]
I can sucessfully run the command "python3 examples/memnn_luatorch_cpu/full_task_train.py -t babi:task10k:1 -nt 1" in the terminal,but when I run it by pycharm,it occures the error  as follows:
FileNotFoundError: [Errno 2] No such file or directory: 'luajit
Do you know why?@alexholdenmiller

**Comment by ajfisch** [comment]
The PATH environment variable is likely different in the terminal vs the pycharm ide. Try configuring the pycharm PATH environment variable to be the same as the output of `echo $PATH`. Specifically, make sure `luajit` is in there (e.g. for me this is in `$HOME/torch/install/bin`).

**Comment by qinghua2016** [comment]
Hi, ajfisch, thank you for your replying, as what you say, I add the code "sys.path.append('/home/qinghua/program/torch_src/torch/install/bin')" to the file of full_task_train.py,but it still occurs the same error,the whole result of the running is as follows:
/usr/bin/python3.5 /home/qinghua/pythonWork/qa/ParlAI/examples/memnn_luatorch_cpu/full_task_train.py -t babi:task10k:1 -nt 1
[dict_max_ngram_size:-1]
[num_examples:1000]
[download_path:/home/qinghua/pythonWork/qa/ParlAI/downloads/]
[task:babi:task10k:1]
[datapath:/home/qinghua/pythonWork/qa/ParlAI/data/]
[datatype:train]
[remote_cmd:luajit /home/qinghua/pythonWork/qa/ParlAI/parlai/agents/memnn_luatorch_cpu/memnn_zmq_parsed.lua]
[dict_unktoken:<UNK>]
[dict_nulltoken:<NULL>]
[port:5555]
[dict_language:english]
[dict_minfreq:0]
[batchsize:1]
[num_its:100]
[remote_args:/home/qinghua/pythonWork/qa/ParlAI/examples/memnn_luatorch_cpu/params_default.lua]
[numthreads:1]
Setting up dictionary.
[creating task(s): babi:task10k:1]
[DialogTeacher initializing.]
[loading fbdialog data:/home/qinghua/pythonWork/qa/ParlAI/data//bAbI/tasks_1-20_v1-2/en-valid-10k-nosf/qa1_train.txt]
[creating task(s): babi:task10k:1]
[DialogTeacher initializing.]
[loading fbdialog data:/home/qinghua/pythonWork/qa/ParlAI/data//bAbI/tasks_1-20_v1-2/en-valid-10k-nosf/qa1_valid.txt]
Dictionary: saving dictionary to /tmp/dict.txt.
Dictionary ready, moving on to training.
Traceback (most recent call last):
  File "/home/qinghua/pythonWork/qa/ParlAI/examples/memnn_luatorch_cpu/full_task_train.py", line 100, in <module>
    main()
  File "/home/qinghua/pythonWork/qa/ParlAI/examples/memnn_luatorch_cpu/full_task_train.py", line 68, in main
    agent = ParsedRemoteAgent(opt, {'dictionary': dictionary})
  File "/home/qinghua/pythonWork/qa/ParlAI/parlai/agents/remote_agent/agents.py", line 126, in __init__
    super().__init__(opt, shared)
  File "/home/qinghua/pythonWork/qa/ParlAI/parlai/agents/remote_agent/agents.py", line 53, in __init__
    args=opt.get('remote_args', '')
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'luajit'

Process finished with exit code 1
I run "echo $PATH",and it print as follows:
/home/qinghua/bin:/usr/local/cuda/lib64:/usr/local/cuda-8.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/local/MATLAB/R2014a/bin:/home/qinghua/program/torch_src/torch/install/bin:/home/qinghua/program/srilm/bin:/home/qinghua/program/srilm/bin/i686-m64
The information indicat that my torch path is "/home/qinghua/program/torch_src/torch/install/bin". So I can insure I set the right torch path, but why the pycharm can't find luajit?@ajfisch

**Comment by ajfisch** [comment]
Hi,
Appending to sys.path in the code won't do it. That's the same as modifying the PYTHONPATH, or the path that python will use to find modules. We need the environment PATH to be consistent, as the RemoteAgent that the code uses issues a subprocess call. You should try setting the PATH env in the actual IDE setting.

**Comment by ajfisch** [comment]
If you launch PyCharm from the terminal, it should inherit the terminal environment variables automatically. For example: 
```bash
open "/Applications/PyCharm CE.app"
```

**Comment by qinghua2016** [comment]
I set the enviroment path of pycharm by adding the code line:
os.environ['PATH']=os.getenv('PATH')+':/home/qinghua/program/torch_src/torch/install/bin'+":/home/qinghua/pythonWork/qa/ParlAI/downloads/memnnlib/KVmemnn/library/c/"
Then it succeed.

**Comment by ajfisch** [comment]
Yes, that would also do it. You might find that configuring your PATH permanently in your IDE might save you time/trouble down the line though.

Unless you have any other questions, I'll close this out.
