### ISSUE TITLE
Memory Error on Personachat unzipping

### ISSUE THREAD

**Issue by christqoh** [facebookresearch/ParlAI#880]
When running 
`python projects/convai2/baselines/profilememory/interactive.py`

in a fresh clone of the repo (no datasets downloaded yet), it downloads personachat but when unzipping I get

`Traceback (most recent call last):
  File "projects/convai2/baselines/profilememory/interactive.py", line 13, in <module>
    from projects.personachat.persona_seq2seq import PersonachatSeqseqAgentSplit
  File "/ParlAI/projects/personachat/persona_seq2seq.py", line 52, in <module>
    'glove_vectors'
  File "/venv_ParlAI/lib/python3.6/site-packages/torchtext/vocab.py", line 347, in __init__
    super(GloVe, self).__init__(name, url=url, **kwargs)
  File "/venv_ParlAI/lib/python3.6/site-packages/torchtext/vocab.py", line 236, in __init__
    self.cache(name, cache, url=url)
File “/venv_ParlAI/lib/python3.6/site-packages/torchtext/vocab.py", line 322, in cache
    vectors.extend(float(x) for x in entries)
MemoryError`

**Comment by alexholdenmiller** [comment]
Actually should be able to move the glove vectors to only load when initializing a model from scratch (the parlai/agents/seq2seq.py agent does that), which will prevent you from needing to load them into memory if you don't need them. Let me take a look.

**Comment by christqoh** [comment]
Yes @stephenroller , it is a Ubuntu VM, 8GB ram, but it used to work before^^ 
seems to work fine now @alexholdenmiller .
Thank you for your support guys and all the best from Munich!
