### ISSUE TITLE
TorchAgent uses inadequate dialog history

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/ParlAI#901]
Pulled from #894. Current implementation of torch agent uses a highly simplified version of observe.

https://github.com/facebookresearch/ParlAI/blob/ed28cdc55552900f1ec2c4f08a11c35dfa2f4b58/parlai/agents/example_seq2seq/example_seq2seq.py#L161-L170

We should copy the more complex version of observe in parlai/agents/seq2seq.py which uses maintain_dialog_history instead of this simpler `'\n'`-concat.
(and by extension, remove self.episode_done as a field, e.g. in reset as well)
probably needs a little cleanup though
https://github.com/facebookresearch/ParlAI/blob/2951872be31f842cea861bcd52c34ed17e247f23/parlai/agents/seq2seq/seq2seq.py#L455-L475

We also want the reset to be updated too:
https://github.com/facebookresearch/ParlAI/blob/2951872be31f842cea861bcd52c34ed17e247f23/parlai/agents/seq2seq/seq2seq.py#L400-L406

**Comment by stephenroller** [comment]
Fixed in #974

**Comment by stephenroller** [comment]
My mistake, this is not yet resolved yet. `TorchAgent` defines `maintain_dialog_history`, but doesn't actually use it in observe yet. Letting @alexholdenmiller decide how to proceed from here.

**Comment by alexholdenmiller** [comment]
Yes I'll do this next along with adding candidates to the batch! (left it filled with None for now)
