### ISSUE TITLE
Issue during persona chat_chat task.

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#910]
Hello, 

Sometimes when I run multiple conversations , for example with the tag, `-nc 5` I get the following traceback:

<img width="755" alt="screen shot 2018-06-23 at 8 40 22 pm" src="https://user-images.githubusercontent.com/25429471/41823002-5650534c-77ad-11e8-8e97-937baf530d5c.png">

What is causing this? How can I fix it?

**Comment by JackUrb** [comment]
Hi @josharnoldjosh - this appears to be a bug in persona chat_chat. It would appear a non-blocking act was called (can return None) but the act wasn't checked to ensure it existed before dereferenced later.

**Comment by JackUrb** [comment]
It appears you're using a modified version of `personachat_chat` (our version doesn't even have 390 lines) so be sure you're checking that the act returned by `agent.act` is not `None` if you are calling it with `blocking=False`.
