### ISSUE TITLE
How to ensure workers are not paid if task is not completed?

### ISSUE THREAD

**Issue by josharnoldjosh** [facebookresearch/ParlAI#914]
Hello, 

I have a modified version of the personachat_chat task. If the workers fail to complete my task, how can I ensure they are not paid? Could I add the workers to the 'bad' worker list. Will this happen automatically if the task is not complete, e.g, the data is saved as an 'incomplete.pkl' file? I only want to pay workers where my data is saved as 'complete.pkl' files?

Thanks,
Josh

**Comment by JackUrb** [comment]
Hi @josharnoldjosh - most of this information is directly written in our guide on using mechanical turk [here](http://parl.ai/static/docs/tutorial_mturk.html), particularly in the handling disconnects section and below that as well. Incomplete workers are not paid if they were the ones to disconnect, but their partner is as required by MTurk TOS.
