### ISSUE TITLE
Profilememory Memory

### ISSUE THREAD

**Issue by christqoh** [facebookresearch/ParlAI#933]
Maybe going with #932 
The memory is distinguishing the profilememory from a seq2seq. Attention is independent of that for both. Are there any papers on how that memory works/how the training/conditioning in personachat dataset affects it?

**Comment by emilydinan** [comment]
Hi @christqoh, the model you're referring to is the model described in section 4.5 of the paper here: https://arxiv.org/pdf/1801.07243.pdf. In that section, it describes how the profile memory model differs from the seq2seq model used in that paper; in particular, if there is no profile information, the model becomes equivalent to the seq2seq model.

**Comment by christqoh** [comment]
Thank you @emilydinan. So it is as simple as that only the profile information from the personachat dataset makes the profilememory a profilememory instead of a seq2seq? 
Are the profile information in this case the first utterances in the conditioned personachat data ( `self` , `both` , `other` )? Consequently, the `none` personachat data would only make it a seq2seq?

**Comment by alexholdenmiller** [comment]
That's correct--the utterances with "your persona" or "partner's persona" in front of them

**Comment by christqoh** [comment]
ok, thank you guys!
