### ISSUE TITLE
How to reproduce KV Profile Memory model?

### ISSUE THREAD

**Issue by xiaokc** [facebookresearch/ParlAI#942]
Hey, Could you please tell me how to reproduce the model **_KV Profile Memory_** which has best performance in your paper **_Personalizing Dialogue Agents: I have a dog, do you have pets too?_**?
And,
1. It's a ranking model, where is the candidate data set? (persona-self_rephraseTrn-True_rephraseTst-False_lr-0.1_esz-500_margin-0.1_tfidf-False_shareEmb-True_hops1_lins0_model.candspair* which exist in data directory, but only 13w+ lines, I don't know..)
2. What's the effect if or not I add some persona text in observe function? I don't understand the observation dict. In issue [928](https://github.com/facebookresearch/ParlAI/issues/928), some one tell me I can get a model with specific persona if some persona texts added.

Could you please tell me the detailed steps to reproduce this model? Thanks very much!!

**Comment by alexholdenmiller** [comment]
Yes the candspair files are the candidates the model uses. They should have 66k lines.

If you want to reproduce the model evaluation results on the personachat dataset, you can run the "kvmemnn_eval.py" script to show the pretrained model's results or train your own using "kvmemnn_train.sh". If you want to talk to the pretrained model, use "kvmemnn_interactive.py". You can see my additional comments on #928 for how to provide a persona to the model when raining kvmemnn_interactive.py to see how the model uses its assigned persona. Note that the persona is tied to the conversation, not the model--the model learned to use a new persona for every conversation, which was always assigned at the beginning of the conversation.

**Comment by xiaokc** [comment]
You're right. :+1: Thanks again. :)
