### ISSUE TITLE
profilememory interactive mode Attribute Error

### ISSUE THREAD

**Issue by christqoh** [facebookresearch/ParlAI#946]
when I run
`python projects/convai2/baselines/profilememory/interactive.py`
(also tried this in a fresh pull of the ParlAI master repository with only the setup done) I get

`Enter Your Message: hey`
`/ParlAI/projects/personachat/persona_seq2seq.py:1756: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  attn_weights = F.softmax(attn_w_premask)`
`/ParlAI/projects/personachat/persona_seq2seq.py:1505: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  scores = F.log_softmax(scores)`
`[Seq2Seq]: hey , how are you ?`
`Traceback (most recent call last):
  File "projects/convai2/baselines/profilememory/interactive.py", line 32, in <module>
    interactive(opt)
``File "/ParlAI/parlai/scripts/interactive.py", line 49, in interactive
    world.parley()`
  `File "/ParlAI/parlai/core/worlds.py", line 244, in parley
    self.update_counters()`
 `File "/ParlAI/parlai/core/worlds.py", line 208, in update_counters
    if self.max_exs > 0 or self.num_examples():`
`File "/ParlAI/parlai/core/worlds.py", line 282, in num_examples
    return self.agents[0].num_examples()`
`AttributeError: 'LocalHumanAgent' object has no attribute 'num_examples'`

**Comment by klshuster** [comment]
closing per #950, please reopen if you run into further issues!

**Comment by christqoh** [comment]
not quite, it works when you download a new model. does nor work with already downloaded model. (to check just run  `python projects/convai2/baselines/profilememory/interactive.py` twice. then I got
 
`Traceback (most recent call last):`
`  File "projects/convai2/baselines/profilememory/interactive.py", line 10, in <module>`
 `   from parlai.core.build_data import download_models`
`ModuleNotFoundError: No module named 'parlai'`

**Comment by alexholdenmiller** [comment]
That didn't reproduce for me--can you post the entire stdout/stderr from the start of the run til the crash?

**Comment by christqoh** [comment]
there wasn't more. however, running `python setup.py develop` again fixed it for me. don't really understand why that was necessary though?!
