### ISSUE TITLE
Running eval_ppl.py for convai2 seq2seq model

### ISSUE THREAD

**Issue by Henry-E** [facebookresearch/ParlAI#953]
So if I want to run the function projects/convai2/baselines/seq2seq/eval_ppl.py , what command line function do I have to run?

The purpose for this question is I'm trying to implement a wrapper for our model in parlai that only does evaluation. And it seems like the minimum code required is an eval_XXX.py function that returns the kind of output expected by the scripts/eval_XXX.py module. I'm trying to figure out how to design and subsequently test my implementation.

**Comment by alexholdenmiller** [comment]
Hi Henry-E!

Well, just `python projects/convai2/baselines/seq2seq/eval_ppl.py`.

You can copy this file into your own directory, say `projects/convai2/baselines/henrymodel/eval_ppl.py`, and modify it as follows:
- remove the code which download the seq2seq model
- change the `model` param to the path to your agent which implements `observe()` and `act()` or `batch_act()` (and `next_word_probability()` if you're doing eval_ppl)
- change any other params appropriate for your model to behave properly during evaluation

**Comment by Henry-E** [comment]
Yeh, I think it's starting to get a little clearer. I realised after posting it, that it's possible to call the module straight from the command line. 

* We're going to make a new Entry agent that inherits from a more typical agent
* Implement the next_word_probability() function which will call our external model using subprocess
* And the entry agent gets passed to the perplexity world

**Comment by alexholdenmiller** [comment]
great--feel free to reopen / open another issue if you have more questions!

**Comment by Henry-E** [comment]
Very basic question but I wasn't able to figure it out from the code. There's quite a lot of different validation files. Which one in particular is used to validate the submitted models? I'm guessing it's done on both `valid_self_original.txt and `valid_self_revised.txt`. And that at test time we won't have access to the other persona? It's just some of the chats with the messenger bot suggested it had access to my persona as well somehow.

![screen shot 2018-08-10 at 15 08 02](https://user-images.githubusercontent.com/12613144/43962343-5a6a350c-9caf-11e8-9273-79befc9fea18.png)

**Comment by emilydinan** [comment]
@Henry-E For the competition, models will be evaluated on `test_self_original`, as described on the competition website.

**Comment by Henry-E** [comment]
Thanks very much. Sorry didn't notice that you'd added an FAQ. So the revised personas won't be used at all for either validation or test. That's good to know.
