### ISSUE TITLE
Differences between ParlAI starspace model and C++ implementation?

### ISSUE THREAD

**Issue by bfelbo** [facebookresearch/ParlAI#956]
I'm planning to use the StarSpace model originally implemented in C++ as a separate Facebook Research repo ([code](https://github.com/facebookresearch/StarSpace) and [paper](https://arxiv.org/abs/1709.03856)). I was really happy to discover that ParlAI contains a PyTorch version of the starspace model (see [here](https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/starspace/starspace.py)) as that makes it easy for me to modify the algorithm to my needs.

The file description in this PyTorch implementation says that the starspace implementation is a "Simple implementation of the starspace algorithm, slightly adapted for dialogue". Can you clarify what that means more precisely and if there's any substantial limitations as compared to the original C++ version?

**Comment by jaseweston** [comment]
It just doesn't include all the modes of training the c++ version one does, or the similarity metric options. It does include a linear layer between LHS and RHS though which can possibly help for dialogue..  but sure if you use it and find any ways to improve it, submit them!
