### ISSUE TITLE
seq2seq question: several predictions from seq2seq model

### ISSUE THREAD

**Issue by fgvbrt** [facebookresearch/ParlAI#958]
Hello, is it possible to get several prediction from seq2seq model: https://github.com/facebookresearch/ParlAI/tree/master/parlai/agents/seq2seq

How I am calling it with command below and get only one example, but I want to get few examples of beamsearch:
```
obs = {"text": text, "episode_done": False}
agent.observe(obs)
res = agent.act()['text']
```

Thanks in advance.

**Comment by uralik** [comment]
Hi Mikhail! So yea, if you want to do that now, feel free to checkout the PR with beam search for seq2seq agent. There you will find corresponding branch in the modules forward() function where beam is done. There you can request different number of n_best beam candidates and post process them before they are sent to the map_predictions function.

**Comment by fgvbrt** [comment]
Thanks, I will check this PR!

**Comment by uralik** [comment]
@fgvbrt, in the latest commit there nbest_beam_preds and nbest_beam_scores returned as well, so you could use it. If you just want to analyze other paths in the beam, you could set --beam-log-freq and it will save nice plots of the beam trees for some portion of samples.

**Comment by alexholdenmiller** [comment]
just merged!
