### ISSUE TITLE
Squad 2.0

### ISSUE THREAD

**Issue by theSage21** [facebookresearch/ParlAI#969]
Would it be ok if I submit a PR to update the SQuAD task to the 2.0 dataset?

**Comment by alexholdenmiller** [comment]
We would be happy to have a PR for that, although don't erase the existing one--you can create a new version of the task which points to the 2.0 data instead.

**Comment by theSage21** [comment]
You mean copy the existing squad task and call the new one squad2 after making changes? I saw a `version = None` inside the classes in the squad task and thought I needed to make it work with that? So that somewhere we can specify the version (maybe cli) and it's taken care of from there.

**Comment by theSage21** [comment]
Does https://github.com/facebookresearch/ParlAI/pull/983 satisfy what's needed?

**Comment by alexholdenmiller** [comment]
Thanks for opening the PR, I'll take a look when I get the chance! A quick skim looked good overall though.
