### ISSUE TITLE
Windows 10 + python 3.5 (Anaconda) code page error

### ISSUE THREAD

**Issue by reppolice** [facebookresearch/ParlAI#97]
Hi,

I won't be using windows much with ParlAI, still I decided to clone it and "run it", sadly I am not very up to speed with codepages, any ideas if this is from your side or Anaconda?:

python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    readme = f.read()
  File "e:\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 202: character maps to <undefined>

**Comment by ajfisch** [comment]
Hm. The default system codec on Windows might be different. On unix/osx it is utf-8. 

Maybe could you try replacing all of the `open()` calls with:
```python
with open('the_filename', encoding='utf-8') as f:
    the_content = f.read()
```
And see if the error is resolved?

**Comment by bittlingmayer** [comment]
There are a few other places with `open` like fbdialog_teacher.py.  I didn't hit it on my machine but some of my students did.

**Comment by alexholdenmiller** [comment]
closing for now--windows isn't a priority

**Comment by pentagrid** [comment]
FYI, I had this same problem resulting in "UnicodeEncodeError" with the otherwise fun little "blended_skill_talk" in build.py. Just changed the two `open()` calls to hardcode the encoding to utf-8 and it worked.
