### ISSUE TITLE
adding qangaroo dataset (wikihop, medhop)

### ISSUE THREAD

**Issue by taineleau** [facebookresearch/ParlAI#992]
Hi,

I am working on adding the qangaroo dataset and got a question:

the dataset has a masked version (e.g.,`train` and `train.masked`), which is simply masked out the name entities. what's the best practice to do it? Is it okay to modify the choices of `-dt`?

**Comment by klshuster** [comment]
One way you can do this is by adding them as separate teachers in the `agents.py` file. You could then specify `-t quangaroo:maskedTeacher` for  the masked version and `-t quangaroo` for the regular version. See the [personachat](https://github.com/facebookresearch/ParlAI/blob/master/parlai/tasks/personachat/agents.py) or [babi](https://github.com/facebookresearch/ParlAI/blob/master/parlai/tasks/babi/agents.py) datasets for examples of defining multiple teachers.

**Comment by taineleau** [comment]
I see. thank you for pointing it out!

**Comment by klshuster** [comment]
No problem! Closing for now, please reopen if you need additional help.
