### ISSUE TITLE
Reproducing Profilememory Attention in Interactive Mode

### ISSUE THREAD

**Issue by christqoh** [facebookresearch/ParlAI#995]
Thank you @alexholdenmiller for fixing #967, I am able to talk to and get useful answers in the expected form the model now. However, when comparing performance (I know this is a delicate topic) to the pretrained model according to #937 I notice the following: 

- Pretrained model (`python projects/convai2/baselines/profilememory/interactive.py`):
Input: 'your persona: I am a robot\n what are you?'
Output: 'i am a robot . i love robot limbs'
- when interacting with my model (trained as given in code) through 
`python projects/convai2/baselines/profilememory/interactive.py --model-file [location] --dict-file [location] --attention general`
Input: 'your persona: I am a robot\n what are you?'
Output: 'i am a trained plumber'

so the word "robot" is in both dicts, I do not expect the exact same reply but something closely related to the persona given to the attention. I feel like the persona part is not being processed accordingly. Any suggestions what might cause this?

**Comment by alexholdenmiller** [comment]
I'm not sure that there's anything I can suggest here, I added Emily in case she has any thoughts but it's pretty tough to explain the decision of the model. The general seq2seq agent in parlai/agents/seq2seq has beam search now, including the ability to generate an image of other beam paths, which can help a little bit sometimes. You could try printing out the probability of "i am a robo.t . i love robot limbs" and comparing it to the produced sentence's probability.

**Comment by alexholdenmiller** [comment]
I mean, the first the tokens are the same--so having a higher probability (even if it's by a fraction of a percentage point) for different token (here, "trained") after "a" compared to "robot" is not something I would be surprised to see the model do.

**Comment by emilydinan** [comment]
Did you train using the the exact same parameters? As Alex said, I'm not really sure what I can suggest here other than inspecting the probabilities.

**Comment by christqoh** [comment]
ok, I will have a look into that. thank you guys!
